### ISSUE TITLE
Tabbed browsing of emails

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#100]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to open mail in new tab with middle click rather than in the right panel

**Describe alternatives you've considered**
Open snappy mail in multiple tabs, but it's not very smooth

**Additional context**
No additional context

**Comment by the-djmaze** [comment]
It's not perfect, but this change opens the mail in a new window.
I don't like my current solution, but a better is only possible with a much bigger code change.

**Comment by Mer0me** [comment]
I'm not familiar with node.js so I don't know how to test that, but your reactivity is awesome. Thank you very much for your work.

**Comment by the-djmaze** [comment]
> I'm not familiar with node.js so I don't know how to test that

Try https://snappymail.eu/demo/ (i've put the code there)


> but your reactivity is awesome. Thank you very much for your work.

Thank you

**Comment by Mer0me** [comment]
Ok, it works, but it's the text/html version of the message, so you cannot interact with the message in the new opened tab (reply, delete, forward...). I think it's useless as the functionality already exists in the context menu of a message.
Some of our Outlook users are using multiple composition windows at a time, or they are opening multiple mails waiting for a reply, for example.

**Comment by ervee** [comment]
I think this is too much to ask for from a simple (but snappy!) webmail client. If you need to (keep) open multiple emails at a time, just install a proper IMAP mail client. Or use drafts. Or perhaps open multiple tabs in your browser although I have not tested how well that works :)

Just my 2ct,

**Comment by the-djmaze** [comment]
Now i understand what you want.
I agree with @ervee but...
I have some draft code to put message uid in url to improve browsing flow.
This could be used to open message in browser tab.
But the code is still unstable due to current code of messagelist.

This would be possible in the future.

**Comment by Mer0me** [comment]
Message uid in url should be a good start. It opens the door to links to e-mail from the nextcloud search engine or other apps...

**Comment by the-djmaze** [comment]
The system now can open a message instantly because of Nextcloud search.

But because opening the full message in seperate tab is way too big for a code change, i will close this ticket.
