### ISSUE TITLE
Snappymail in Nextcloud doesn't seem to load in Safari

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1000]
**Describe the bug**
When Safari users open the Snappymail app in Nextcloud they just get an error page.  They can open in another browser and it opens fine.

**Screenshots**
<img width="1440" alt="Screen Shot 2023-03-01 at 6 29 48 PM" src="https://user-images.githubusercontent.com/93135814/222543287-1afa5e72-5ae5-4850-b686-1b31a404d027.png">

**Please complete the following information:**
- Browser:  Safari 16.3
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.26.4

**Comment by the-djmaze** [comment]
In only have Safari 16.2 and can't reproduce the issue.

Can you check the Safari developer tools for errors?

**Comment by mmallejac** [comment]
This may be related to #929 
When this happens, I have to manually move the `snappymail` folder from `apps` to `custom_apps` or vice versa, and then it works fine.
