### ISSUE TITLE
messages already read listed as unread

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#1003]
**Describe the bug**
Semi-randomly, already read messages re-appears listed unread.
They belong to threads.  
The account is configured to put sent mails inside the same folder.

This is an issue that either affect only recent releases (or that is tied to this configuration of putting sent mail in the same folder). Because this problem did not occurred with earlier versions (and I can't think of no other configuration change). 

**To Reproduce**

A thread in message list, containing only already read messages but shown as unread :
![Nouveau nom 1](https://user-images.githubusercontent.com/1160681/222894723-10608003-90e8-41e6-be6f-197285f302c7.png)

Viewing the thread, we see the see message listed, strangely the [3] is still associated with the last message (that was in the message list) and it is shown as unread while it was read more than once
![Nouveau nom 2](https://user-images.githubusercontent.com/1160681/222894739-3583bcbd-9141-4466-a575-04bbd614d8be.png)

re-reading this last message
![Nouveau nom 3](https://user-images.githubusercontent.com/1160681/222894788-d6f4c094-b9be-4d74-911e-ed9cb88a1243.png)

getting back to the message list, the thread is still shown as unread
![Nouveau nom 4](https://user-images.githubusercontent.com/1160681/222894811-d48fb715-cdba-4a57-b298-257598b436ee.png)

**Expected behavior**
- read messages never getting once again marked as unread
- no [3] message count visible in the thread view

**Please complete the following information:**
- Browser: firefox 109
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.26.4]

**Comment by the-djmaze** [comment]
This could be caused by the etag of the mailbox/folder status.
Currently it looks at HIGHESTMODSEQ but not at UNSEEN as that is deprecated for SELECT and EXAMINE commands.

Will see if i can fix that.

**Comment by the-djmaze** [comment]
Solve with latest release?

**Comment by yeupou** [comment]
Hi!
Thanks for the work done.


This is fixed :    read messages never getting once again marked as unread

But there is still the [3] message counter visible in the thread view

**Comment by yeupou** [comment]
![image](https://user-images.githubusercontent.com/1160681/229362463-c653a8e7-5090-4ee9-b83a-52016f2accd7.png)

example : the two messages in the thread are already listed

**Comment by yeupou** [comment]
Thanks!
