### ISSUE TITLE
No message notification popup

### ISSUE THREAD

**Issue by HelloWorldo** [the-djmaze/snappymail#1007]
**Describe the bug**
The message notifications popup doesn't work

**To Reproduce**
1. Go to `Settings/General`
2. Click on the arrow next to `Show new messages notification popups`
3. Nothing happens (despite having authorized browser notifications for this domain)

**Expected behavior**
I should see a browser notification

**Please complete the following information:**
- Browser: firefox 110
- PHP version: 8.2.3
- SnappyMail Version: 2.26.4

**Additional context**
I don't remember having ever see this feature work, for the past year as a Snappy user.

**Comment by the-djmaze** [comment]
It is an OS notification and the browser should ask you to allow this.

**Comment by HelloWorldo** [comment]
The browser asks me to allow notifications. 
I allow them of course, but they never show.
I've just tested on Chrome, same thing.

I don't think it's related to the OS notifications. The `Notification `  Web API makes messages appear from the browser, as I've tested with other sites on Firefox.

**Comment by the-djmaze** [comment]
What happens when you click the play button in Settings?
![afbeelding](https://user-images.githubusercontent.com/3752035/224730353-5a8ef75e-8350-4d50-ba6b-8d9c456180cb.png)

**Comment by HelloWorldo** [comment]
Nothing.
This is the very action I've mentioned in the steps to reproduce section.

Nothing in the JS log window as well.
Is there a debug log I can enable somehow to help?

**Comment by the-djmaze** [comment]
When Firefox runs in private mode, the `navigator.serviceWorker` is undefined and does not allow it.
SnappyMail application.ini `[debug] javascript = On` reveals this in the browser console.

In normal mode you could get `TypeError: ServiceWorker script at https://example.com/serviceworker.js for scope https://example.com/ encountered an error during installation.`
This is caused by snappymail running in a sub directory.
I've made a change for this and hope it works in all browsers.

**Comment by HelloWorldo** [comment]
Digging into the application.ini file, I've found that `[labs] use_app_debug_js = On` did the job for me.
And then I've got the TypeError you mentioned.
My installation is in a subdirectory indeed.
I'll wait until the next release to test it.
Thanks.

**Comment by the-djmaze** [comment]
> My installation is in a subdirectory indeed.
> I'll wait until the next release to test it.

You could place servicerworker.js in your root `/` as the release still takes time due to some heavy cache changes.
Also my above change will not work for everyone:
- Nextcloud
- Paths without end  slash (like: `/snappymail` and not `/snappymail/`)

**Comment by HelloWorldo** [comment]
OK, thank you for the workaround.

**Comment by the-djmaze** [comment]
You're welcome
