### ISSUE TITLE
Too few arguments to function ValidateWildcardValues

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#101]
**Describe the bug**
When using some plugins (like ldap-contacts-suggestions, black-list or white-list) an error is thrown in snappymail logs :

ArgumentCountError: Too few arguments to function RainLoop\Plugins\Helper::ValidateWildcardValues(), 2 passed in /var/www/snappymail/data/_data_/_default_/plugins/ldap-contacts-suggestions/LdapContactsSuggestions.php on line 117 and exactly 3 expected in /var/www/snappymail/snappymail/v/2.5.2/app/libraries/RainLoop/Plugins/Helper.php:7

Ldap contact suggestion is broken in this case. 

There is a difference between snappymail Helper.php and the original Rainloop one : function ValidateWildcardValues has lost his default value for the third argument "string &$sFoundedValue"
That causes the bug. When the default value is placed back in the function declaration, the ldap contact suggestion is fixed (the plugin is calling the function with only 2 args).

**To Reproduce**
1. Active ldap contact suggestion plugin
2. Compose a new mail and type some letters in the "To:" field
3. Look at the logs : an error is thrown
4. The ldap suggestion doesn't work

**Expected behavior**
Ldap suggestion should work ! Inconsistance between function declaration in Helper.php and calls in LdapContactsSuggestions.php (and other plugins) should be fixed.

**Additional context**
There must be a reason why this default argument was removed from the function of the original Rainloop Helper.php. @the-djmaze can you explain ?

**Comment by the-djmaze** [comment]
I have no idea how that happened.
I've moved it back
