### ISSUE TITLE
Number of unread mails in additional mail accounts not shown

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#1019]
Hi,
if I'm not wrong at some time SnappyMail could show the number of unread mails inside of additional mail accounts (https://github.com/the-djmaze/snappymail/issues/437).
Looking at the commit connected to #437 it seams that there should be shown an indicator beside the account symbol in the upper right corner of SnappyMail.
Unfortunately I do not see this indicator when I receive new mails in an additional account.

I tried to manually set up the additional account as normally I'm using my plugin to create the additional accounts by ldap, but this did not changed anything.

Is this functionality correctly working for others using SnappyMail 2.26.4? Or do I have to activate this manually somewhere?

**Comment by the-djmaze** [comment]
Currently it only loads once

**Comment by the-djmaze** [comment]
Go to Settings Accounts and open an account, there should be an option

**Comment by cm-schl** [comment]
Thanks!
