### ISSUE TITLE
v2.5.3 not working for me

### ISSUE THREAD

**Issue by gene-git** [the-djmaze/snappymail#102]
2.5.2 has been working fine after the sec fetch tweaks 5 days back. 
With the latest git I get the usual login form, and it seems to accept the login - but then the website spins with 'Loading ...' and the usual index etc never shows up. Something between then and 2.5.3 broke for my use case.

There is nothing in nginx error log - and the last message in the access log is a GET on
snappymail/v/0.0.0/static/js/min/openpgp.worker.min.js
This file hasn't changed in long time so likely not actually useful.

Reverting to 2.5.2 works fine again - not sure how to go about finding the source of the problem - any suggestions where I can look?

Server is nginx mainline on linux fully updated (arch). Client tried both firefox 92 nightly from today - same problem using chrome dev. Clients both running on linux.

nginx-mainline 1.21.1
php 8.0.8

Thanks for any help tracking down the issue.

**Comment by grawlinson** [comment]
I'm the maintainer of the AUR snappymail package.

Are you able to clear your browser's cache and have a look at php/nginx logs?

**Comment by gene-git** [comment]
hiya - cleared browser cache -actually  had to - once it got stuck on 'loading' i needed to clear to test prev builds.
nginx logs show nothing of interest as far as I can tell.

**Comment by gene-git** [comment]
Wonder if this is relevant - to build from git, I am  follwing 

`https://github.com/the-djmaze/snappymail/blob/master/CONTRIBUTING.md`

i notice that the APP_VERSION is not updated but stays stuck onm 0.0.0 - this hasn't been a problem with 2.5.2 but perhaps it is now. The index.php file:
 
`usr/share/webapps/snappymail/index.php`

starts with:
```

if (!defined('APP_VERSION'))
{
        define('APP_VERSION', '0.0.0');
```

and the directory tree is likewise named :
`snappymail/v/0.0.0/`

instead of 'v/2.5.3' or 'v/2.5.2' etc.

I follow the build instructions running yarn and gulp - 

- how do I get the index.php to get updated properly 
- could this be causing a problem


```

**Comment by gene-git** [comment]
i'm using yarn version  1.22.10 and gulp version 4.0.2

**Comment by gene-git** [comment]
probably benign but gulp --verify shows:
```
[22:47:44] Blacklisted plugins found in this project:
[22:47:44] gulp-rimraf: use the `del` module
[22:47:44] gulp-concat-util: duplicate of gulp-concat, gulp-tap, gulp-header, and gulp-footer
[22:47:44] gulp-livereload: abandoned. use gulp-refresh
```

**Comment by gene-git** [comment]
@grawlinson  I looked at your AUR package (snappymail-git) - but seems its not building from git its building from the releases directory.

**Comment by the-djmaze** [comment]
Correct, to buily a releas you need to run release.php
See https://github.com/the-djmaze/snappymail/blob/master/release.php

Running 0.0.0 is only advised for develoent and you must to clear browser cache and de /data/.../cache/ folder.

Else just use the release packages.

**Comment by gene-git** [comment]
Ah thanks - yes clearing the /data/.../cache and installing from release package works fine.  I'll go over he release php script as well.

thank you

**Comment by gene-git** [comment]
@grawlinson  Thank you for providing AUR package - i will switch to your package - clearly better than mine :)
