### ISSUE TITLE
Sorting in folders not working (correctly) or sort order not correct

### ISSUE THREAD

**Issue by new-on-github** [the-djmaze/snappymail#1022]
**Describe the bug**
Mails in a folder are not sorted by date. There is no menu to sort in a different way, therefore I think, the mails should be sorted by date. 

**To Reproduce**
Check a folder with some mails and look at the sorting.

**Expected behavior**
Mails are sorted by date

**Screenshots**
![image](https://user-images.githubusercontent.com/30312140/225647197-44ac6268-8ca9-417b-a267-0663811e837b.png)

**Please complete the following information:**
- Browser: firefox
- IMAP daemon: ???
- PHP version: 8.1.16
- SnappyMail Version: 2.26.4

**Thanks a lot for this amazing mail client**

**Comment by the-djmaze** [comment]
When your IMAP server does not support sorting, the sort is based on the IMAP software and we can't do anything about it.

However there are two kind of dates:
1. the date specified inside email headers
2. the internal date when server received/created the message

By default SnappyMail shows number 1, and 2 is hidden.
In next release 2 is still hidden, but available in the JSON so we can enhance the behavior in future.

A good test to check your server:
1. Download very old email EML
2. Drag&drop the EML inside your mailbox
3. See if message is at the top or not.

Then you know how your IMAP server behaves.

**Comment by new-on-github** [comment]
> 
> A good test to check your server:
> 
>     1. Download very old email EML
> 
>     2. Drag&drop the EML inside your mailbox
> 
>     3. See if message is at the top or not.
> 
> 
> Then you know how your IMAP server behaves.

Thanks a lot for your reply and help. This seems to be the problem. The very old imported Mail is on top in  INBOX. We will have to check the IMAP-Server.

I have a other question in this direction: 
This post from you indicates to me, there is a sorting mechanism in snappymail:
https://github.com/the-djmaze/snappymail/issues/569#issuecomment-1287030832
How did I miss understand this post?

Thanks for your work!

**Comment by the-djmaze** [comment]
> I have a other question in this direction: This post from you indicates to me, there is a sorting mechanism in snappymail. How did I misunderstand this post?

For that, your IMAP software must support https://www.rfc-editor.org/rfc/rfc5256.html

**Comment by new-on-github** [comment]
Thanks a lot for your quick reply, answer and help.

We will therefore check our mail-server!

> > I have a other question in this direction: This post from you indicates to me, there is a sorting mechanism in snappymail. How did I misunderstand this post?
> 
> For that, your IMAP software must support https://www.rfc-editor.org/rfc/rfc5256.html

May I suggest adding a star with the above explanation to the sort-entry of the mentioned table. Then other people will hopefully not ask you again.

Thanks a lot for your quick replies, answers and help.

We will therefore check our mail-server!

**Comment by the-djmaze** [comment]
> May I suggest adding a (foot-)note with the above explanation to the sort-entry of the mentioned table. Then other people will hopefully not ask you again.

I understand, but it should be already noticeable due to the missing sort button at the top.
![afbeelding](https://user-images.githubusercontent.com/3752035/229734431-e223c912-c0bd-452c-8afc-7be6b5b4c755.png)

**Comment by new-on-github** [comment]
> > May I suggest adding a (foot-)note with the above explanation to the sort-entry of the mentioned table. Then other people will hopefully not ask you again.
> 
> I understand, but it should be already noticeable due to the missing sort button at the top. ![afbeelding](https://user-images.githubusercontent.com/3752035/229734589-1ccc73f7-8e50-43c6-a556-91219a25e04d.png)

Do I understand you correctly: If my IMAP-server supports sorting, then there is this sort-button, which toggles sorting order. 
Ok, seems to be logical. But my problem/misunderstanding was, to look for the button because the table tells my sorting is possible. Therefore I suggested to add this information (Snappy can sort, but only if the IMAP-Server supports this).

Thanks a lot for your work an replies.

**Comment by the-djmaze** [comment]
Would it be sufficient to show a different button, instead of hiding it?
Something like:
![afbeelding](https://user-images.githubusercontent.com/3752035/229741651-40fab9cb-f166-477a-a62c-4d5155e055ab.png)

**Comment by new-on-github** [comment]
Thanks a lot!
