### ISSUE TITLE
Version 2.6.4 broke Captcha and never allow me to login

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1023]
**Describe the bug**

Captcha is not loaded when the snappymail is on version 2.6.4
The issue is not present on snappymail 2.6.3

**To Reproduce**

1. Captcha must be enable
2.Try to login and captcha is not load so you cannot login with snappy 2.6.4, works only 2.6.3

**Expected behavior**
Captcha must work also on 2.6.4 when is not

**Please complete the following information:**
- Browser: , firefox 111
- IMAP daemon: xxxx
- PHP version: 8.1
- SnappyMail Version: 2.6.4 (now I use the previous version as this bug never allow login)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Did you update the plugin?

**Comment by PeopleInside** [comment]
> Did you update the plugin?

No as I never get update notification about that.
What I have to do to update?
I will look and update you.

**Comment by the-djmaze** [comment]
Upload the plugin manually as you did before.
https://github.com/the-djmaze/snappymail/tree/master/plugins/recaptcha

**Comment by PeopleInside** [comment]
Thank you, I will activate alert on GitHub also for plugin update. Thanks.

**Comment by PeopleInside** [comment]
Works.
As the plugin is inside the project and is not a separate project I cannot be notified when an extension is updated.
I need to remember to check... sometimes.
