### ISSUE TITLE
v2.27.0 issue with top right dropdown colour/font

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#1025]
I upgraded from v2.26.4 to v2.27.0 and the top right menu has a white background with black font, instead of the previous black background with white font. I don't know if this change was intentional [I had a quick look at the latest commits, but I couldn't spot it]. The box doesn't render as nicely as it used with the original font/colour combination.

Unfortunately I cannot share a screenshot without showing everyone some email addresses.

**Comment by the-djmaze** [comment]
You can test on https://snappymail.eu/demo/ as it depends on which dark theme you use

**Comment by setoy** [comment]
> You can test on https://snappymail.eu/demo/

![image](https://user-images.githubusercontent.com/6497266/226450052-06d387bc-77bc-453a-af32-b732166cdc87.png)

**Comment by ivnmad** [comment]
I use the default theme.
What @setoy just posted is exactly what I see now.
If I visit  https://snappymail.eu/demo/ and select the default theme, I also get the same result.

Without changing any setting, upgrading from v2.26.4 to v2.27.0 make the top right dropdown menu white background with black writing, instead of black background and white writing.

Based on the title of #1026 [The displayed account's style changed in the new version] @Zero3K is also referring to that.

**Comment by the-djmaze** [comment]
Ah, yes.
The change is here: https://github.com/the-djmaze/snappymail/commit/1663cc6ce5ac7ab3cd769a4eac1e5535c24399a3

**Comment by Zero3K** [comment]
Does that change the background color of it?

**Comment by the-djmaze** [comment]
> Does that change the background color of it?

No.
The first commit i mentioned, makes the text part of the button.
The second commit makes the text less bold and more readable.

I did make it part of the button as it was hardly readable in some themes.

It would be better to make buttons more integrated with the themes instead of the default bootstrap.css color.
