### ISSUE TITLE
The displayed account's style changed in the new version

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1026]
Is that intentional or a bug?

**Comment by PeopleInside** [comment]
Also switching to differents account create an infinite loop after a while that never load the web mail anymore.

**Comment by setoy** [comment]
> Also switching to different account than change the account again create an infinite loop after a while that never load the web mail anymore.

This also happens for me when just logging in.

Console:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-mItykQmXoPZYP1W1GLnoSnPldYzwraPOT9Zq5T55bjU='), or a nonce ('nonce-...') is required to enable inline execution.

```

**Comment by setoy** [comment]
Just wanted to reiterate: Does this fix the endless loading that was mentioned as well?

**Comment by the-djmaze** [comment]
> Just wanted to reiterate: Does this fix the endless loading that was mentioned as well? Or should it be discussed in #1025 or a new issue created?

No, it is #1024
