### ISSUE TITLE
Reply is broken

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1027]
Clicking it shows a new message box with nothing filled in it.

**Comment by ivnmad** [comment]
I can confirm the behaviour on https://snappymail.eu/demo
If you click reply on any message, this is what you get:

![Screenshot from 2023-03-20 20-03-37](https://user-images.githubusercontent.com/35845319/226453370-5ee944d3-f945-46ff-8ea6-02e3d0954a64.png)

**Comment by Zero3K** [comment]
When will you make a new version containing this fix?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.27.1

**Comment by Zero3K** [comment]
Thanks :)
