### ISSUE TITLE
Multiple unread mails in threaded view not shown

### ISSUE THREAD

**Issue by mhier** [the-djmaze/snappymail#1028]
**Describe the bug**
In threaded view, multiple unread mails im the same thread are shown like a single unread message. Only after unfolding the thread it becomes apparent that there are multiple unread mails.

**To Reproduce**
1. Turn on threaded view
2. Mark two mails in the same thread as unread
3. Mark exactly one mail (the latest one) in another thread as unread
4. In the inbox list, the two thread entries look identical, i.e. it is impossible to see how many unread mails are in the thread.
5. When clicking the thread entry, in both cases the latest mail is opened. This results in easily missing the older unread mail. 

**Expected behavior**
The number of unread messages should be shown in the inbox list. When clicking the entry, the oldest unread message should be opened (instead of the latest one). If splitted view, the thread should be opened when clicking it. 

**Please complete the following information:**
- Browser: seen with Firefox on Linux and Android
- IMAP daemon: dovecot
- PHP version: 8.1.2
- SnappyMail Version: 2.27

PS: I am aware this is maybe more like a missing feature than a bug, but I am facing this problem frequently and I am seeing emails really late sometomes. This is super annoying and confusing.

**Comment by the-djmaze** [comment]
In the past (RainLoop) when threaded view is used, it queried the imap server for all thread messages to find unread.

This slows down the messages list tremendously on large boxes with many threaded replies.
It also showed the current "read" message as unread, which is a bad user experience ("huh? I already did read message").

So i removed it in favour of clicking the unread count or use search for unread.

RainLoop nor mine are the best approaches and we need to find a better solution.

**Comment by mhier** [comment]
It would be sufficient to do this when the latest message in the thread is unread (this is already shown properly), also just for those which are currently visible (i.e. pagination). If even that is too much, it would already help to do that in the moment the thread is clicked, e.g. my unfolding the thread when reading (will help only when using a split view but it would be at least a start). Maybe displaying a warning when reading a message of a thread which has unread messages that are older than the currently read message can also help.

**Comment by mhier** [comment]
Please note: This problem feels more and more like a real bug to me. I am constantly faced with hidden unread emails. This makes me think whether I should move to a different email system. The label "enhancement" definitively does not feel appropriate to describe the severity of the issue. Please consider fixing this with a higher priority. Thanks!
