### ISSUE TITLE
email and signature not included in reply and forward

### ISSUE THREAD

**Issue by DrGood70** [the-djmaze/snappymail#1034]
Hi there
When clicking reply or forward to an email my signature and the email being replied or forwarded is not included.
In other words - when clicking reply or forward the email is completely empty, is this a feature or a bug?
Thanks
Jesper

**Comment by codiflow** [comment]
Can confirm that.

A bit more information for  debugging:

SnappyMail 2.27.0
PHP 8.0

Console error:
`Uncaught TypeError: y.dateTimeStampInUTC is not a function`

Doesn't matter if I click reply all, reply or forward. The result is the same.

**Comment by DrGood70** [comment]
I have 2.27.0 installed.

**Comment by the-djmaze** [comment]
Duplicate of #1027
