### ISSUE TITLE
535 Incorrect authentication with smtp freenet.de

### ISSUE THREAD

**Issue by di-le** [the-djmaze/snappymail#1038]
I have the problem that I can't send any emails via freenet.de. I get error 535 Incorrect authentication

However, the SMTP server works with a different client and other SMTP servers also work in snappymail.

I used roundcube earlier and had the same problem with freenet.de.
I was able to change the problem back then with the "USE_SINGLE_LINE_AUTH_PLAIN_COMMAND"
from false to true in app/libraries/MailSo/Smtp/SmtpClient.php.
Even if that only lasted until the next update.

Here is a link to the error:
https://github.com/RainLoop/rainloop-webmail/issues/1629

Is there a solution for this in snappymail?
I didn't find the USE_SINGLE_LINE_AUTH_PLAIN_COMMAND.

**Comment by the-djmaze** [comment]
> A solution that survives an update of the app would also be nice.

Of course 😉

**Comment by di-le** [comment]
It works out. Thanks very much. And also thanks for the option in the admin panel.

It was amazing how quickly that went. :-)
