### ISSUE TITLE
2.27.1 breaks toggling between accounts

### ISSUE THREAD

**Issue by ro56** [the-djmaze/snappymail#1039]
I have multiple mail-accounts registered in snappymail. If i switch form my starting account A to another account B, I can't switch back to account A - snappymail won't come back. 
To resolve this lock, closing the tab or even restarting the browser does not help: I have to restart the webserver that's hosting snappymail to clear this situation. 

- Webserver nginx
- Browser: chrome as well as firefox 
- PHP version: 8.1.17
- SnappyMail Version: 2.27.1

**Comment by ro56** [comment]
this issue seems to be limited to a standalone setup of snappymail. I can't reproduce it on a nextcloud-integrated setup.

**Comment by tomasz-c** [comment]
I also have this problem on:
- Webserver: nginx 1.23.3
- Browser: chromium
- PHP: php-fpm 8.2.4
- SnappyMail Version: 2.27.1

The error I get in the browser console (in red):
```/#/:16 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-k+j......A='), or a nonce ('nonce-...') is required to enable inline execution.```

**Comment by the-djmaze** [comment]
Correct. Read #1024

**Comment by ro56** [comment]
thx, fixed with 2.27.2
