### ISSUE TITLE
Packages configuration broken

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#104]
**Describe the bug**
In 2.5.3 or 2.6.0 the admin Plugins section got integrated in the Packages section. Which is good, I never understood why it needed 2 sections :) But for me this broke the ability to configure the plugins. Clicking the cogwheel does nothing.

**To Reproduce**
1. Log into the admin URL
2. Go to Packages
3. Click on cogwheel for an installed package to configure the package 
4. Nothing happens

Also I installed the 2FA plugin and when I try to enable it I get an "Invalid Plug Package" error. When I log out and back in it is still installed but disabled again.

**Expected behavior**
Be able to configure plugins and enable 2FA plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/4435930/127766122-c41973f4-c1d3-4750-9103-74c48c54fb63.png)

**Desktop (please complete the following information):**
 - Firefox 90 (Fedora and Windows 10), Edge 92 (Windows 10).
 - SnappyMail Version [e.g. 2.6.0]

**Comment by the-djmaze** [comment]
I've added some security to the plugins system, it seems that broke the plugin management and i've fixed the issue.
It seems RainLoop was managing plugins based on "name" instead of folder name/id.
