### ISSUE TITLE
Upgrading snappymail now made me loose all time login to the webmail

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1041]
**Describe the bug**

Every time you are now releasing a new version, the upgrade or the downgrade made me loose the login session.
Before the latest few new versions released on that days, this was never happen before.

Is something you introduced or it's a BUG somewhere?
Every time I upgrade snappy-mail I need re-login again with the two factor, captcha, etc.

**To Reproduce**
1. Login in SnappyMail
2. Upgrade the version

Results: you are no more logged in

**Expected behavior**
To stay logged as in the past

**Screenshots**

**Please complete the following information:**
- Browser: Firefox 111.0
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.1
- SnappyMail Version: 2.27.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Correct, the behavior has changed to encrypt data using a token and the app version number.
When the token or version number is changed the data is lost and that's why you must login again.

https://github.com/the-djmaze/snappymail/commit/f5045b9759aec69811f05ffc08773fbebe3f609e
