### ISSUE TITLE
Allow snappymail settings export / import

### ISSUE THREAD

**Issue by scubamuc** [the-djmaze/snappymail#1042]
it would be great feature to export / import snappymail settings and accounts to Nextcloud instance

setting up snappymail is simple. For Nextcloud admins of different instances where access to email is needed, snappymail needs to be setup and configured on each instance.

would it be feasible to create an export/import functionality enabling simple setup and configuration similar to the rainloop upgrade process (profile-transfer).

**Comment by the-djmaze** [comment]
It's not advised because then you require an identical SALT.php on each instance.

However, you can ignore accounts and just copy:
- `nextcloud/data/appdata_snappymail/_data_/_default_/configs`
- `nextcloud/data/appdata_snappymail/_data_/_default_/domains`
- `nextcloud/data/appdata_snappymail/_data_/_default_/plugins`

**Comment by scubamuc** [comment]
Your suggested procedure would require access to the file system on the instance. In many cases an instance is set up and configured remotely without access to file system. As cloud-admin access the file-system is often restricted. These instances may be snap/standalone/hosted/self-hosted some remote and some on premises. 

Sure its no big hassle installing snappymail from scratch. Although it would be very helpful to be able to import accounts, identities and signatures to another instance. Adding passwords would be the smallest issue.

Maybe you could consider this request as "nice to have"? 

Thanks for great software and fantastic support.

**Comment by the-djmaze** [comment]
Would fit best as an extension that has an admin page with that functionality.

Maybe someone will create it.
Example code is at https://github.com/the-djmaze/snappymail/tree/master/plugins/example

**Comment by scubamuc** [comment]
@the-djmaze I'm not seeing **backup** in add-ons?

**Comment by the-djmaze** [comment]
Correct, it is draft code
