### ISSUE TITLE
Viewing a read email causes it to be marked as unread

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1044]
*subject*

**Comment by fazlerabbi37** [comment]
@Zero3K can you please provide more details? I might have seen the similar behavior, where viewing a read email give me -1 in unread. Unfortunately, I have not been able to reproduce it correctly :(

**Comment by Zero3K** [comment]
It is fixed by waiting 5 seconds on the affected message, so it becomes read again.

**Comment by Zero3K** [comment]
I hope it gets fixed soon.

**Comment by Zero3K** [comment]
Well?

**Comment by the-djmaze** [comment]
Only you have this problem as nobody seems to reproduce this issue.

1. change your password
2. login in SnappyMail with the new password
3. DON'T use the password in your other mail clients (this prevents any issue that other clients have)

If you can't reproduce the issue, the issue is the other client.

**Comment by Zero3K** [comment]
I am not using an email client. I am using the webmail interface.

**Comment by Zero3K** [comment]
Does that help with finding what is causing the issue?

**Comment by the-djmaze** [comment]
So you have a caching problem.
Somehow SnappyMail doesn't receive the right mod-sequence value from the server.

Maybe the IMAP server does not support RFC 4551?
https://www.rfc-editor.org/rfc/rfc4551.html

**Comment by Zero3K** [comment]
Software    version
------
Ubuntu    22.04.2 LTS
Postfix   3.6.4
Dovecot   2.3.16
OpenDKIM    2.11.0
OpenDMARC    1.4.2
policyd-spf    2.9.3
Rspamd	3.5
Snappymail    the latest version
Certbot   2.5.0
Apache    2.4.52

**Comment by Zero3K** [comment]
Any news?
