### ISSUE TITLE
Upgrade with Nextcloud stuck in Maintenance mode

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1046]
**Describe the bug**
When I have updated the last two updates, 2.27.1 and 2.27.2 the instance gets stuck in Maintenance Mode.  I believe that this we happening with some recent releases but then seemed to be resolved for a couple of releases.

**Please complete the following information:**
- Browser: Chrome, Brave
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.27.0

**Comment by new-on-github** [comment]
We had this issue also. But I did the update on a large nextcloud via the admin-panel and this seems to be no good idea with a large instance...

**Comment by mmallejac** [comment]
the same happens using `occ` unfortunately

**Comment by the-djmaze** [comment]
> I believe that this we happening with some recent releases but then seemed to be resolved for a couple of releases.

Correct, that was #904 and i still have no clue why Nextcloud is acting so strange and i can't reproduce the issue.

**Comment by the-djmaze** [comment]
Duplicate of  #929
