### ISSUE TITLE
hard coded string "Message body is empty"

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1048]
On 2.27.2, with Nextcloud, if trying to save an empty message, the following error message is shown:

![image](https://user-images.githubusercontent.com/11666281/227154018-ae55729e-65ca-4dbe-ac2d-f0291cc89e93.png)

Tried to find the string in https://snappymail.eu/translate.php?lang=fr-FR but no luck

Hardcoded ?

Many thanks in advance !

**Comment by Zero3K** [comment]
In my opinion, the inability to save and/or send a message with no body should be fixed.

**Comment by mmallejac** [comment]
Despite I may agree with you, this is not the purpose of this issue. Maybe worth a new one ?

**Comment by Zero3K** [comment]
Okay.
