### ISSUE TITLE
Left unattended SnappyMail (at least on Nextcloud) interrupts me to ask if I want to leave the page or not.

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#1049]
**Describe the bug**
Left unattended SnappyMail (at least on Nextcloud) interrupts me to ask if I want to leave the page or not.

![image](https://user-images.githubusercontent.com/2113743/227178670-62c843d4-eb4d-4517-aceb-ff5f04f14f39.png)

**To Reproduce**
1. Open a message in SnappyMail Nextcloud (not yet tested standalone)
2. Go to another tab to work on something
3. Get interrupted and taken to the SnappyMail Nextcloud tab and see this message

![image](https://user-images.githubusercontent.com/2113743/227178670-62c843d4-eb4d-4517-aceb-ff5f04f14f39.png)

**Expected behavior**
I don't expect any unattended open tabs to interrupt my flow nor need any attention whatsoever.

**Screenshots**
![image](https://user-images.githubusercontent.com/2113743/227178670-62c843d4-eb4d-4517-aceb-ff5f04f14f39.png)

**Comment by jdaviescoates** [comment]
Just to add, I *think* this is just an issue with the Nextcloud app (and it never used to happen there, so a relatively recent  - but not that recent, it's been happening fora wee while now - change with the app - or with Nextcloud, I guess - must've introduced it)

**Comment by bk-king1** [comment]
I see the same behaviour with a standard installation (not Nextcloud) - It has happened a few times now. So many, that I came here to see if anyone had already reported this issue.

v. 2.26.4

**Comment by the-djmaze** [comment]
It happens at:

https://github.com/the-djmaze/snappymail/blob/f33ae5e021697a91a99aa2f36f6f435062b32020/dev/App/User.js#L185-L190

Only when:
1. a "popup/modal" is open (composer, language selector, search, etc.)
2. or there is no "split" (mobile view or setting) and a message is open

**Comment by jdaviescoates** [comment]
> or there is no "split" (mobile view or setting) and a message is open

Yes, this is when it happens to me.  I wish it didn't.

> a "popup/modal" is open (composer, language selector, search, etc.)

I've not noticed this (yet), but that would also annoy me.

Why does it happen in these two scenarios?

**Comment by the-djmaze** [comment]
> Why does it happen in these two scenarios?

When you reload/unload the page, you might loose changes you are making.
For example you open a new tab to look something up and you want to copy/paste that data.
When Nextcloud forces reload/unload you can start all over again (or partially when using periodic save).

Or you use private browsing and hit the back button that will unload everything (and cookies/login in some cicrumstances).

To prevent that, the system asks you if you really want to quit (just like a PC app that asks almost the same).

**Comment by jdaviescoates** [comment]
> To prevent that, the system asks you if you really want to quit (just like a PC app that asks almost the same).

I get that.

What I don't get is why SnappyMail has started to refresh the page without me doing anything and when I don't want it to?

**Comment by the-djmaze** [comment]
Maybe you have auto-logout active and that conflicts?
