### ISSUE TITLE
Did the "threads" counter view break with 2.6.1?

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#105]
**Describe the bug**

This (2.6.1):
![image](https://user-images.githubusercontent.com/4435930/128882900-557ff99c-04c2-44bc-9bb2-12c92e0d3270.png)

Used to be this:
![image](https://user-images.githubusercontent.com/4435930/128883031-90babf19-5596-475c-8b4f-5cc3cf5f37b4.png)

**To Reproduce**
Update to 2.6.1. Could have been broken after 2.5.2 but I just noticed it after updating to 2.6.1.

**Desktop (please complete the following information):**
 - Firefox 90.0.2 on Windows 10 20H2.

**Comment by the-djmaze** [comment]
You are right!
While reducing the excessive DOM footprint, i've removed `threads-len-data` from the MailMessageList.html
But forgot to do the same in CSS.
