### ISSUE TITLE
Odd annoying behaviour when copy/ pasting links or email addresses into email and then editing them

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#1054]
**Describe the bug**
Odd annoying behaviour when copy/ pasting links/ email addresses into email and then editing them. Things jump around, extra lines get added, all sorts of weirdness happens.

**To Reproduce**
1. Create new email
2. Paste a link or an email address
3. Note that it pastes onto the next line.
4. Edit the email to get the link where I want it. 
5. All sorts of weirdness happens
6. Give up and use Roundcube instead

**Expected behavior**
I expect things to be pasted onto the line I paste the in (but that's not what really annoys me) and then to not jump around the screen onto other lines when trying to edit the email to get the link/ email address in the correct part of the email (this happening is what's really annoying, but I guess they are related)

**Screenshots**
See e.g. this short screencast showing some of the odd behaviour experienced (although note this doesn't cover it all: quite often extra lines are added between all the existing lines too I've just not done enough testing to work out exactly when that happens nor managed to capture it a screencast). This paste a link, goes on next line, go to beginning of the line where the link is and hit backspace, link jumps to two lines above things seems to be easily to reproduce though: it happens everytime I try it on both SnappyMail Nextcloud app and the standalone SnappyMail app (latest versions of both):

https://youtu.be/O1faHn5BBD4

**Comment by the-djmaze** [comment]
I've tested to see what is happening:

1. Past link
![afbeelding](https://user-images.githubusercontent.com/3752035/228215718-00aee022-fd75-47de-83ae-063dfd08b6d4.png)

2. Backspace
![afbeelding](https://user-images.githubusercontent.com/3752035/228215920-bfa6d337-a43e-456b-8733-9600d1618b77.png)

I've traced back this issue to the solution for #962
So i will try another solution.

**Comment by jdaviescoates** [comment]
Basically at present SnappyMail is unusable for me. I nearly always need to copy/ paste something into an email and then tidy up the formatting, but as soon as I attempt to tidy anything up everything goes haywire, extra lines get added, lines of text jump all over the place. How can I re-open this issue?

**Comment by andreasdirscherl** [comment]
+1
I second this.
Upon deeper testing I experience the exact same behavior as @jdaviescoates :-(

@jdaviescoates - we probably have to open a new issue with this?

**Comment by jdaviescoates** [comment]
> +1 I second this. Upon deeper testing I experience the exact same behavior as @jdaviescoates :-(
> 
> @jdaviescoates - we probably have to open a new issue with this?

Done see #1061

**Comment by andreasdirscherl** [comment]
Thank you!
