### ISSUE TITLE
Improve RTL languages support

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1056]
Hi

First of all, I express my gratitude for your efforts in continuing Rainloop's journey. We have a problem with js files that has been cached on user's browser.

When we modified or added some new features, most of users are not able to see changes and sometimes they have trouble for login too.Our Clients don't see the changes because the browser cached the old files and prevents the changes from being applied.

After running Gulp we have new boot.js file with new version but as you know app.js doesn't has version number in it's name. 

Do you have a solution to force the client browser to ignore its cache and load new changes?

**Comment by the-djmaze** [comment]
The root `.htaccess` has:
```
	ExpiresByType application/javascript A15768000
```

Removing it, might help.

Else you could modify the boot.js with something like:
```js
	loadScript = src => src ? new Promise((resolve, reject) => {
			const script = doc.createElement('script');
			script.onload = () => resolve();
			script.onerror = () => reject('Failed loading ' + src);
			script.src = src + '?v=' + Date.now(); // Always RELOAD
```

**Comment by the-djmaze** [comment]
> we have added the Jalali calendar

SnappyMail dropped moment.js and uses https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
When the language is 'fa-IR' it should show dates in Persian.

> Another change is RTL interface for Webmail and use different default fonts and theme to handle Persian requirement.

You can do this in themes.

> Also, adding links and sections as branding that can be managed and deleted in the admin panel.

Here is such a plugin as example:
https://github.com/the-djmaze/snappymail/tree/master/plugins/login-register

**Comment by rezaei92** [comment]
But some users rather to use English language with Jalali calendar. Do you have any idea to handle this feature? or it's absolutely depended to language.

Because in the matter of localization, calendar and language should not be dependent on each other.

For example, in some Arab countries, most people use the Gregorian as  a work calendar, but the lunar calendar is also used. So the calendar should be language independent.
And some professors in universities are generally preferred to use english language with jalali calendar in over country.

Therefore, we made it possible to select the calendar without depending on the language.
Hence, we are ready to develop for solving this problem.

**Comment by the-djmaze** [comment]
Here you do have an issue.

When you use English it would show "Sunday November 5 2023" but you want "Yekshanbeh 14 Aban 1402".
Or islamic "yawm al-'ahad Rabi`ath-Thani 21 1445"

This would mean that your brain has to switch between languages to get something done, and this drains energy.

Here's a screenshot of the demo in Persian (hijri calendar):
![image](https://user-images.githubusercontent.com/3752035/229531640-4b404076-3478-44bf-9d19-c1e128af6c8f.png)

And Arabic:
![image](https://user-images.githubusercontent.com/3752035/229531783-1bb0ea88-4429-4dd8-b511-c197d46e842c.png)

See `relativeTime` in https://github.com/the-djmaze/snappymail/blob/master/dev/Common/Translator.js
And `Date.prototype.format` in https://github.com/the-djmaze/snappymail/blob/master/dev/prototype.js

**Comment by the-djmaze** [comment]
You can test with https://github.com/the-djmaze/snappymail/releases/tag/v2.27.3

**Comment by the-djmaze** [comment]
Here's a screenshot of my current RTL branch.
![afbeelding](https://user-images.githubusercontent.com/3752035/231242181-c7468af5-a380-43a2-91d0-0e08edab38ac.png)

**Comment by the-djmaze** [comment]
Not perfect, but i also added translating of the pagination numbers.
![afbeelding](https://user-images.githubusercontent.com/3752035/236807922-bc7d8b50-ffe6-4610-8826-eb623208ddbf.png)

**Comment by the-djmaze** [comment]
Now it is 
![afbeelding](https://user-images.githubusercontent.com/3752035/236811736-b6548c90-2944-4522-bf9d-e60f09469b9d.png)
