### ISSUE TITLE
exchange不支持中文搜索

### ISSUE THREAD

**Issue by qxxz** [the-djmaze/snappymail#1059]
exchange imap不支持utf-8 charset，所以snappymail无法进行中文搜索。如何解决这个问题？谢谢！

error message: BADCHARSET The specified charset is not supported

**Comment by the-djmaze** [comment]
Exchange does not support charsets so you must use US-ASCII.
And because of that, Exchange search will never return results in Chinese or any other language that does not use A-Z.

It's better to upgrade to a mail server that does support UTF-8 and is not as limited/old as Exchange.
