### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by mini** [the-djmaze/snappymail#106]
**Describe the bug**
If I click logout the page just reloads

**To Reproduce**
Steps to reproduce the behaviour:
1. Login
2. Click logout

**Expected behaviour**
It logouts out

**Desktop (please complete the following information):**
 - Browser: Firefox 92
 - SnappyMail Version: 2.6.1 but I've noticed this since 2.5.x

**Additional context**
- Logging out of /?admin works fine
- I am running PHP 8 if that matters
- PHP error in logs:
` RainLoop\Actions::ClearSignMeData(): Argument #1 ($oAccount) must be of type RainLoop\Actions\Model\Account, RainLoop\Model\Account given, called in <webroot>/snappymail/v/2.6.1/app/libraries/RainLoop/Actions/User.php on line 217`

**Comment by the-djmaze** [comment]
Did you try at https://snappymail.eu/demo/ ?

**Comment by the-djmaze** [comment]
Thanks for reporting, this bug is fixed
