### ISSUE TITLE
Apparently random order emails

### ISSUE THREAD

**Issue by monachuscc** [the-djmaze/snappymail#1062]
**Describe the bug**

Emails are not sorted correctly by date in the list of messages. The order looks almost random.  This occurs with emails that were transferred from another account; these emails were transferred by most recent first, and probably in the reverse order that is shown in the seemingly random order of the display.

**To Reproduce**
1. View the inbox

**Expected behavior**

The email should be correctly sorted by date with the message with the newest at the top of the list and the oldest at the bottom of the list.

**Screenshots**

This is a screenshot of the inbox folder's rightmost column:
![image](https://user-images.githubusercontent.com/43016639/228975077-4aecf3ac-1f13-4074-ac62-bbac313916c4.png)

**Please complete the following information:**
- Browser: Chrome 111
- IMAP daemon: dovecot
- PHP version: 7.4.28
- SnappyMail Version: 2.27.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)
Attached is a detailed log with obviously sensitive data replaced with asterisks. [Debug log of initial message download.txt](https://github.com/the-djmaze/snappymail/files/11116640/Debug.log.of.initial.message.download.txt)
I have tried turning on and off the Lab setting entitled date_from_headers but it does not seem to change, nor does the disable of the Cache. 

**Additional context**
I am planning to move several email accounts to another mail server, and tested the migration of one account from the old server to another account on the new server.  When I used an old (pre-2019) version of Rainloop, installed on a home server, to view the account on the new server, the messages were in an incorrect order, much like [this person](https://github.com/RainLoop/rainloop-webmail/issues/1817) pointed out in 2019.  I hoped that by upgrading Rainloop and installing Snappymail I would be rid of this problem, but it seems to persist.  Perhaps it might be that there is a blank in the sort field in the initial request, where the log says:
`[2023-03-30 22:24:09.347][eaa1447a] POST[INFO]: {"offset":0,"limit":20,"search":"","uidNext":43,"sort":"","folder":"INBOX","threadUid":0,"Action":"MessageList"}`
Nevertheless, I await your suggestions and questions and help.

**Comment by the-djmaze** [comment]
Please read #1022
It explains why your IMAP server is behaving like that.
