### ISSUE TITLE
Sending Mails to an external Domain not possible - "Relay access denied" Error

### ISSUE THREAD

**Issue by chodid** [the-djmaze/snappymail#1066]
**Describe the bug**
In nextclouds Snappymail extention sending Mails to an external domain isn't possible. It always amounts to a "Relay access denied" error (when looking into the logs)

**To Reproduce**
1) Click New Message
2) Write Message / recipient / subject 
3) Click send

**Expected behavior**
Message will be sent

**Please complete the following information:**
- Browser: Irrespective of the browser (Firefox & Chrome, latest versions)
- IMAP daemon: dovecot on Plesk
- PHP version: 8.1.17
- SnappyMail Version: 2.27.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Provided as txt file:
[debug-log.txt](https://github.com/the-djmaze/snappymail/files/11136189/debug-log.txt)

**Additional context**
In general: Thank you guys very much for this awesome webmail client!
I hope, that I'm in the right place with my problem. Any help is greatly appreciated!

**Comment by the-djmaze** [comment]
Your config is wrong.
Your SMTP requires login so you must go to ?admin and configure the domains properly.

**Comment by chodid** [comment]
Thank you for your quick reply! Now I'm a bit embarrassed as I got it running smoothly within 2min... Sorry for the unnecessary post - Donation as a token of appreciation for your awesome work already went out this morning :) Thank you!!!
