### ISSUE TITLE
2.27.3 broken (at least on nextcloud) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by k4my4b** [the-djmaze/snappymail#1069]
**Describe the bug**
Just updated to 2.27.3 on nextcloud and snappymail doesn't respond (service down)

**To Reproduce**
simply upgrading to 2.27.3 does it

~~**Expected behavior**~~

~~**Screenshots**~~

**Please complete the following information:**
- Browser: Chromium Version 111.0.5563.146 (Official Build) Arch Linux (64-bit)
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: PHP 8.0.28
- SnappyMail Version: 2.73.3

~~**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**~~

**Additional context**
In case anyone else happens to experience the same issue, here's a couple of simple steps to roll back to the previous version: (assuming you are on docker)

1. disable the app from nextcloud apps menu
2. `docker exec -it -u www-data <your nextcloud instance> bash`
3. `rm -r /var/www/html/custom_apps/snappymail`
4. `cd /tmp && curl https://snappymail.eu/repository/nextcloud/snappymail-2.27.2-nextcloud.tar.gz | tar -xzvf -`
6. `cp -r snappymail /var/www/html/custom_apps/`
7. enable snappymail again

**Comment by the-djmaze** [comment]
I removed the `exit;` to fix #1046
But if we don't `exit;`, NextCloud thinks it should echo gzip compressed data.

So again, we have no clue why NextCloud keeps bugging with the maintenance mode

**Comment by the-djmaze** [comment]
I've repackaged it with the rollback. You can update again within 1 day because NextCloud can't handle version numbers properly.
[#1069](https://github.com/the-djmaze/snappymail/wiki/FAQ#nextcloud-app-with-id-snappymail-has-invalid-signature)
