### ISSUE TITLE
SnappyMail Demo isn't working under Fulguris 1.7.7

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#107]
**Describe the bug**
When I try to go to its demo, it tells me that an error occurred and to refresh the page.

**To Reproduce**
1. Go to https://snappymail.eu/demo/

**Expected behavior**
The demo should show up instead of the error.

**Mobile (please complete the following information):**
 - Browser: Fulguris 1.7.7 (User Agent is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36)

**Comment by the-djmaze** [comment]
I've just tested that browser, because i never heard of it.
While testing it seems Fulguris is seriously broken and not suited for SnappyMail.
Please report at https://github.com/Slion/Fulguris

Mobile browsers that work: Firefox Focus, Firefox, Chrome, Samsung, Brave

**Comment by the-djmaze** [comment]
Nevermind, issue seems to be valid where Apache .js.br and .css.br need correct Content-Type for these browsers.
