### ISSUE TITLE
List of messages in a folder is sometimes not being shown

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1071]
Instead of the list of messages, I get an "Empty list." message every now and then.

**Comment by DerDanilo** [comment]
I can confirm this. This is happening since a few weeks. Any way how to solve this? There seem to be no errors in the logs.

**Comment by DerDanilo** [comment]
This seems to be related to the caching settings. Disabling caching or switching to file based caching will display messages again.

@the-djmaze I couldn't find any documention on how to exactly configure caching itself. The about page also doesn't check for memcache/memcached php extension.

The following issue mentions 'tcp://...'. Is this something we have to put into the config?

https://github.com/the-djmaze/snappymail/issues/113

Thanks!

**Comment by the-djmaze** [comment]
Could be related to #1096

**Comment by mmallejac** [comment]
One of my user as also reported this to me yesterday.
Sorry, no logs to add here, I've told the user to let me know about it sooner next time.
From what he said, could me similar to #998

**Comment by Zero3K** [comment]
*bump*

**Comment by the-djmaze** [comment]
Yes, still investigating 😉

**Comment by Drumsk8** [comment]
I am having this issue with my inbox, I know my inbox is fine in roundcube/outlook/android mail. It's not all folders within my inbox either, it's the main inbox folder and some subfolders, some other subfolders show correctly. Most users it's fine, but the odd user like me or the odd folder just wont load the mail. 

I've tried messing with cache settings, it's not helped me at least.

**Comment by Zero3K** [comment]
I am getting aborted and timed out messages when switching between pages.

**Comment by the-djmaze** [comment]
How quick?
As the timeout is 60 seconds.
https://github.com/the-djmaze/snappymail/blob/336fdf074a0dc7174c637ce68cf6ab685b2c320b/dev/Remote/User/Fetch.js#L50-L56

**Comment by Drumsk8** [comment]
Ok so now mine is saying: Can't get message list.

**Comment by the-djmaze** [comment]
> Less than that amount of time.

Is it around 30 seconds?

**Comment by Zero3K** [comment]
I just quickly flip between pages (like around a second or so).

**Comment by the-djmaze** [comment]
> I just quickly flip between pages (like around a second or so).

Then indeed the current request gets aborted and shows aborted messages.
It will then start a new request to get the new messageslist.

Timeout occurs when browser stops the request. The only control we have (and try, but will not always work) is shown above with the 60 seconds.

In the past it just showed "aborted", then it showed nothing, and now it shows one of the two errors.

**Comment by Zero3K** [comment]
It's weird that it doesn't happen all the time.

**Comment by the-djmaze** [comment]
Not that weird. When messagelist is cached the response is in ms, else it could take ages based on IMAP server speed.

**Comment by the-djmaze** [comment]
I am on to something!
There seems to be an issue with multiple requests and timeouts

**Comment by the-djmaze** [comment]
There we go. I've tested with the very slow Hotmail to find these.

**Comment by Zero3K** [comment]
Please provide a new version that contains this fix so I and others can test it.

**Comment by the-djmaze** [comment]
It's not perfect yet, as some other conditions might still have issues, like:
1. Load messages
2. Abort
3. Load other messages
4. Messages loaded
5. Abort signal is now triggert

So i'm thinking to write a messages queue where the next is only called after finish/abort/timeout only.
But it is tricky to test and implement and probably not needed.

**Comment by Zero3K** [comment]
Is there any more work to be done?

**Comment by the-djmaze** [comment]
I don't think so, but will do.some more testing.

**Comment by Drumsk8** [comment]
My inbox still doesn't show. Again other inboxes are fine. Mine is fine with other tools.

I do see this error a lot in my nextcloud log:

stream_socket_client(): Unable to connect to tcp://127.0.0.1:6379 (Connection refused) at /var/www/mywebsite/public_html/apps/snappymail/app/snappymail/v/2.28.1/app/libraries/Predis/Connection/StreamConnection.php#94

**Comment by Zero3K** [comment]
I think releasing a new version would be fine then.

**Comment by the-djmaze** [comment]
> I think releasing a new version would be fine then.

https://github.com/the-djmaze/snappymail/releases/tag/v2.28.2

**Comment by Zero3K** [comment]
I have tried doing what caused it in the previous version. The newest version no longer has this issue.
