### ISSUE TITLE
Archive, Spam and Delete buttons showing twice

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#1072]
Not sure if this has been present for some time, but I only noticed it today [v2.27.2 and v2.27.3]
The Archive, Spam and Delete buttons are showing twice: above the message list section and above the message view section.
Is that expected? Do we really need them twice? [if so, it would be great to understand why]

![Screenshot 2023-04-04 at 21 13 32](https://user-images.githubusercontent.com/35845319/229898088-b612c590-d13f-4480-97aa-0ee5342ddcb0.jpg)

**Comment by jas8522** [comment]
Pretty sure the ones on the right are for the currently viewed message, while the ones on the left are for the selected message(s) from the message list column.

**Comment by ivnmad** [comment]
@jas8522 that makes sense, thank you.
Closing this thread.

**Comment by the-djmaze** [comment]
Also read the discussion at #970
