### ISSUE TITLE
leave settings as they are when updating snappymail

### ISSUE THREAD

**Issue by daniu-de** [the-djmaze/snappymail#1074]
**Describe the bug**
I am annoyed by having to adjust the setting for: "Mark message as read after" everytime the app is updated.

**To Reproduce**
update snappymail - AFAIR everytime this setting (and I don't know which settings besides that) are reset

**Expected behavior**
leave settings that are not related to updates as they are

**Please complete the following information:**
- Browser: Firefox 111.0.1
- IMAP daemon: privat
- PHP version: 8.something
- SnappyMail Version: 2.27.2 (after update) I update to every version ... BTW: I like to use software that is not dead (like rainloop or Horde) but: is it really the best way to update the app that often? Normally I do not see any difference

**Comment by daniu-de** [comment]
I hit the update button in Nextcloud - that's it and it happens quite often that the settings are reset

**Comment by the-djmaze** [comment]
Remove your RainLoop folders and try again.

It is known that Nextcloud has several bugs when it comes to upgrades

**Comment by the-djmaze** [comment]
Are you using the debian package or something?
Maybe that removes the `data` directory at update?
Try moving the data outside the public html using the _include.php

**Comment by razron** [comment]
I'm having similar problems. I'm using the debian package for snappymail. I'm not using nextcloud.
