### ISSUE TITLE
Cannot access the repository at the moment.

### ISSUE THREAD

**Issue by belzebubek** [the-djmaze/snappymail#1075]
Admin panel - extensions - snappymail cannot fetch list of extensions. Error message is:
"Cannot access the repository at the moment."

error message found in WWW server log file:

PHP message: PHP Warning:  stream_socket_client(): php_network_getaddresses: getaddrinfo for snappymail.eu failed: no address associated with name in /htdocs/snappymail/snappymail/v/2.27.3/app/libraries/snappymail/http/request/socket.php on line 79PHP message: PHP Warning:  stream_socket_client(): Unable to connect to **ssl://snappymail.eu:443** (**php_network_getaddresses: getaddrinfo for snappymail.eu failed: no address associated with name**) in /htdocs/snappymail/snappymail/v/2.27.3/app/libraries/snappymail/http/request/socket.php on line 79

Name is resolvable on the same machine:

$ host snappymail.eu
snappymail.eu has address 84.22.110.35
snappymail.eu has IPv6 address 2a02:2770:15:0:21a:4aff:feff:f9b6
snappymail.eu mail is handled by 0 snappymail.eu.

OS: OpenBSD
$  php-8.1 -v
PHP 8.1.17 (cli) (built: Mar 30 2023 08:45:53) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies

**Comment by the-djmaze** [comment]
Restart PHP and try again.

**Comment by belzebubek** [comment]
It deosn't help. I use php-fpm 8.1

**Comment by belzebubek** [comment]
I did. I think this is platform specific - OpenBSD. I did even upgrade from 7.2 to 7.3 recently. The issue persists.
