### ISSUE TITLE
Issue with certain craigslist emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1076]
![craigslist - SnappyMail](https://user-images.githubusercontent.com/6194332/230418350-9a660619-2506-4958-ba09-944c890cc60c.png)
![craigslist - mboxview](https://user-images.githubusercontent.com/6194332/230417336-71d5d9d8-f4c1-4bc9-b1a9-b37b5e29703c.png)
[craigslist- email change request.eml.txt](https://github.com/the-djmaze/snappymail/files/11171839/craigslist-.email.change.request.eml.txt)

**Comment by the-djmaze** [comment]
I don't consider this as an issue.
SnappyMail converts `<blockquote>` to a collapsible block so that you can read quotes when needed.
Craigslist just incorrectly uses that HTML element.

**Comment by Zero3K** [comment]
What should they do instead?

**Comment by the-djmaze** [comment]
For example they could use a div with margin.
