### ISSUE TITLE
After a while Snappymail automatically puts the user back into their default email account 

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#1077]
**SnappyMail version, browser, browser version:**

snappymail version 2.27.2
Nextcloud version 24

**Expected behavior and actual behavior:**

Current behavior:

If the user has several email accounts and decides to use any other address but the default one, after a while snappymail automatically gets back to the default account.

Expected behavior:

User continues to stay in same email account 

**Steps to reproduce the problem:**

1. log into snappymail
2. Select another account
3. Wait between 6 and 45 minutes

This is not strictly reproducible always with all accounts

**Logs or screenshots:**

**Comment by Niveshkrishna** [comment]
Silly me. it is actually setting in application.ini which does this. In case some one does not want this behavior, please set  the following in `config/application.ini`

```
autologout = 0

```

**Comment by the-djmaze** [comment]
Also see user settings:
![afbeelding](https://user-images.githubusercontent.com/3752035/232753330-d055c772-f62f-49fa-b163-e2e71c6279bb.png)
