### ISSUE TITLE
Amazon Emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#108]
Do they display properly in SnappyMail (especially the ones that you get when a question has been answered)?

**Comment by phsc84** [comment]
This is not a forum, this is an issue tracker. Try it yourself and report an issue, if you found a problem.

**Comment by the-djmaze** [comment]
Since we don't know many things of your setup.

1. Try
2. investigate
3. report

**Comment by Zero3K** [comment]
Here's how it looks in SnappyMail:

![Amazon Question Answer Email Screenshot #1](https://user-images.githubusercontent.com/6194332/130310918-0263577a-ec64-4195-af07-d0a1bfef951c.png)
![Amazon Question Answer Email Screenshot #2](https://user-images.githubusercontent.com/6194332/130310921-f34ccaa8-dcc1-42b1-a72e-0a0d7731cba3.png)

Here's how it looks in POP Peeper:

![Amazon Question Answer Email Screenshot #3](https://user-images.githubusercontent.com/6194332/130311407-f1494312-5ac9-4842-8530-132e64dde624.png)

**Comment by the-djmaze** [comment]
I see.
You forgot to investigate why it is.
Open your developer toolbar in browser and find why the header is so high.
There might be a css class conflict.

**Comment by Zero3K** [comment]
I am attaching an archive containing the message as an eml file. Hopefully it can help in finding the cause and then fixing it.

[You have received 2 answers to your question, was this experience helpful.eml.zip](https://github.com/the-djmaze/snappymail/files/7026063/You.have.received.2.answers.to.your.question.was.this.experience.helpful.eml.zip)

**Comment by the-djmaze** [comment]
Found the problem and this is an Amazon issue.
They broke the rules of email HTML by putting @media rules in the <head><style>
Then they use `height: 0px; visibility: hidden;` on HTML elements.

For a good read and support read:
https://www.emailonacid.com/blog/article/email-development/media-queries-in-html-email/
