### ISSUE TITLE
sso passwordlesslogin possible in nextcloud?

### ISSUE THREAD

**Issue by Reis-A** [the-djmaze/snappymail#1081]
Not sure if it is a feature request or bug....

I recently was trying out the OIDC plugin as login mechanism to nextcloud 25.0.5 with keycloak.
And I set it up in the "proxy" setting, where no new account is created at login, but it is connected by the LDAP_uid to the corresponding account created by LDAP Backend Plugin.

Not surprisingly, the passwordless login doesn't work anymore in snappymail.
Of course, there is the workaround with storing or remembering the password for IMAP in nextcloud, though that option is not the desirable solution...

On the other hand, I know that it was possible with the impersonate plugin to login to other imap accounts as an admin, password less. So maybe there is a way to do this?
Or does the oidc login overwrite some values in the nextcloud database when logging in the account?

**Comment by the-djmaze** [comment]
OIDC (OpenID Connect) means the login is outside Nextcloud.
Instead, you get an OAuth token to use in Nextcloud.
Does your IMAP server supports OAuth?

**Comment by the-djmaze** [comment]
See #756

**Comment by the-djmaze** [comment]
When your IMAP/SMTP logins are not connected to the LDAP/OAuth server, then there's nothing you can do.

> I know that it was possible with the impersonate plugin to login to other imap accounts as an admin

The impersonate plugin is not a solution as it doesn't know passwords and can't login to IMAP/SMTP (not to mention the other issues it has).

> Of course, there is the workaround with storing or remembering the password for IMAP in nextcloud, though that option is not the desirable solution...

Although not desirable, it is currently your only option (unless you use a different IMAP/SMTP like dovecot+postfix).

**Comment by MohammedNoureldin** [comment]
I am just curious to know, considering the following scenario:

My mail server does support OAuth2, and I am logging to Nextcloud using OIDC. So Nextcloud already has an access token.

When I use SnappyMail integration in Nextcloud, should the user be logged in automatically out of the box?

**Comment by the-djmaze** [comment]
> When I use SnappyMail integration in Nextcloud, should the user be logged in automatically out of the box?

It should when `Login with OIDC` is enabled in the extension
