### ISSUE TITLE
Help with Nextcloud contacts integration

### ISSUE THREAD

**Issue by tilkov** [the-djmaze/snappymail#1083]
**Describe the bug**
Nextcloud contacts synchronization does not work on my installation. If I put the full URL (including domain) in **Addressbook URL** and type my password in the **Password** field, sync starts working

**To Reproduce**
1. Observe Contacts being empty
2. Start **Sychronization** from the menu - an error appears: Contacts synchronization error
3. Go to **Setting** -> **Contacts**, 
4. Replace the path "/remote.php/dav/..." with the full address "https://my.domain.com/remote.php/dav/..."
5. Full my acccount password in the **Password** field
6. Go to **Contacts**, start **Synchronization** - works

**Expected behavior**
Nextcloud contacts sync should work out of the box without manual settings for every user.

**Screenshots**
![snappy](https://user-images.githubusercontent.com/546928/231671244-b62a1dca-dae6-494a-a855-534b18b0779c.png)

**Please complete the following information:**
- Browser: Chromium 112
- IMAP daemon: dovecot
- PHP version: 8.1.2-1ubuntu2.11
- SnappyMail Version: 2.27.3, nextcloud plugin 2.27.3
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
DAV[WARNING]: No user credentials set
DAV[INFO]: DavClient: User: 309C711C-28F1-449F-9175-2C3B08B0222D, Url: https:///remote.php/dav/addressbooks/users/309C711C-28F1-449F-9175-2C3B08B0222D/contacts/
PROPFIND http://localhost/.well-known/carddav
DAV[DEBUG]: PROPFIND http://localhost/ - 405 Method Not Allowed
DAV[INFO]: Contacts path not found at: /
PdoAddressBook[WARNING]: Sync() invalid DavClient
JSON[INFO]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"AddressBookProvider->Sync() failed","epoch":1681367442}

**Additional context**
Nextcloud authenticating agains Active Directory. It is not possible to set manually the sync settings for every user.

Thanks in advance!

**Comment by cm-schl** [comment]
I think what you're looking for would be the Nextcloud Plugin of SnappyMail: https://github.com/the-djmaze/snappymail/issues/569
At the moment it is only possible to read the contacts of Nextcloud but saving contacts is not possible at the time.

**Comment by cm-schl** [comment]
Maybe it's only a thing where you're looking for the contacts: the Nextcloud integration of SnappyMail makes it possible to search for mail recipients when typing their name inside the `To:` field but does not show the addresses inside Nextcloud Contacts in the SnappyMail Contacts. In theory you could also deactivate the address book of SnappyMail and nevertheless could see the contacts inside the Nextcloud Contacts app
