### ISSUE TITLE
Major issue with certain Amazon emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1086]
![Amazon - SnappyMail](https://user-images.githubusercontent.com/6194332/231911366-ce505115-370d-4e17-be22-7e112ae29acb.png)
![Amazon - mboxview](https://user-images.githubusercontent.com/6194332/231911374-8fd4d8e9-c179-404c-b288-07f7d7e7b6a3.png)
[Together we can defeat scams.eml.txt](https://github.com/the-djmaze/snappymail/files/11227595/Together.we.can.defeat.scams.eml.txt)

**Comment by cm-schl** [comment]
Could you check your settings under General -> Message view?
Especially if you have checked "Allow <style> CSS" and "Prefer HTML to plain text"?

**Comment by Zero3K** [comment]
They are both checked.

**Comment by MI-KY** [comment]
Have you maybe tried to open the same website with an other browser? I'm not sure how Edge is behaving exactly, but could you try to follow this guide https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/inspect and tell if the content of the mail is inside the code of the website (and therefore only not shown) or if it is missing also in the html code?

**Comment by Zero3K** [comment]
Just wait for @the-djmaze to respond.
