### ISSUE TITLE
Spell Check hidden on compose window

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1088]
**Describe the bug**
When I click on a highlighted word marked for spelling or grammar, the suggestions box is popping up behind the Compose window.

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.27.2
- Mode: nextcloud

**Comment by MI-KY** [comment]
Did you check if in your settings of SnappyMail the spell checking functionality is correctly activated?
How do you know, that the suggestions are shown behind the compose window?

**Comment by BiglifeMatt** [comment]
If the word happens to be on the right side of the window, part of the suggestion widow can be seen as a layer under the compose window.Sent from Android deviceOn Apr 15, 2023 6:47 AM, MI-KY ***@***.***> wrote:
Did you check if in your settings of SnappyMail the spell checking functionality is correctly activated?
How do you know, that the suggestions are shown behind the compose window?

**Comment by BiglifeMatt** [comment]
![Screenshot 2023-04-15 080802](https://user-images.githubusercontent.com/93135814/232221520-abd72365-8d33-47e2-bfb7-cf51afe4f25d.png)

**Comment by BiglifeMatt** [comment]
I do see this is only with the Language Tool plugin.  If I disable that, I get the simple pop-up similar to Chrome and it can be seen.  I believe however that Languagetool is included by default.

**Comment by the-djmaze** [comment]
Please report the bug to the browser plugin.
It probably works by injecting html code inside the document, but that will not work in SnappyMail.
