### ISSUE TITLE
Rainloop Issues

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#109]
Have you fixed any of the issues listed at https://github.com/RainLoop/rainloop-webmail/issues/?

**Comment by phsc84** [comment]
This is not a forum, this is an issue tracker. Try it yourself and report an issue, if you found a problem.

**Comment by Zero3K** [comment]
Well, the other people have found issues with the original version of it. I am just wondering if he fixed any of those issues.

**Comment by the-djmaze** [comment]
Yes some are fixed, some are not relevant and some will never.
Look up https://github.com/the-djmaze/snappymail/commits/master for all commits that mention RainLoop issues.
