### ISSUE TITLE
application.ini gets reset when making changes to it

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#1091]
**Describe the bug**

application.ini gets reset to default values when an admin is trying to make changes while the app is being used in production. This is also happening when making changes from admin UI of snappymail. As soon as save is clicked, all changes get reverted and default values are saved in application.ini. 

This happens only when app is enabled and being used by users in production (relatively high load)

**To Reproduce**
1. Go to application.ini
2. Make changes
3. Save
4. See that application.ini is reset

**Expected behavior**

application.ini not getting reset to default values

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: 2.26.2 
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]: Nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
This is a very strange behavior.
The only thing SnappyMail does, is calling [file_put_contents](https://www.php.net/file_put_contents)

There must be something wrong with Nextcloud
