### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by beccon4** [the-djmaze/snappymail#1095]
**Describe the bug**
Logout fails when Snappymail is enabled.

**To Reproduce**
1. Activate SnappyMail
2. try to log out of the session
3. it will fail with "[105] Missing version directory" - the session persists.
4. deactivate Snappymail
5. log out as usual

**Expected behavior**
Logging out of the current session should be possibly under all circumstances. This entails a severe security risk as the session is still active.

**Please complete the following information:**
- Browser: all Browsers, Firefox, Chromium
- PHP version: PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
- SnappyMail Version: 2.27.3
- Mode: standalone, installed in VM

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

[105] Missing version directory

No log entries. apart from

`49.216.56.46 - - [17/Apr/2023:18:47:53 +0000] "GET /index.php/logout?requesttoken=K7eidx59oTDQ49MbDyLXc1ODAXP61LsEfQtsFjiQNlo%3D%3AU%2FTGOu8o43ils6ZOTxrtXASodirOs5BuGUgDQHfiYxk%3D HTTP/1.1" 200 1127 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"`

**Comment by the-djmaze** [comment]
That error is not of SnappyMail, it is RainLoop.
You can't use both

**Comment by Niveshkrishna** [comment]
@beccon4 You have to deactivate rainloop when snappymail is active
