### ISSUE TITLE
Search is broken/ useless

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#1096]
**Describe the bug**
If I do a search for ``suma`` or even specifically search subjects for ``Suma delivery day change`` it does not find an email with the subject ``Suma delivery day change``

**To Reproduce**
1. Search for``suma`` or even specifically search subjects for ``Suma delivery day change``
2. Don't find the email I am looking for
3. Pull my hair out
4. Give up and use Roundcube instead :( 

**Expected behavior**
Search should work.

**Comment by the-djmaze** [comment]
Search does work for me.

The browser developer console Network tab reveals the search:
![afbeelding](https://user-images.githubusercontent.com/3752035/232767484-be34d024-bef9-4950-b07c-8f6ab17910bc.png)

`epoch` reveals the time and date the search is made.
If that value is lower than the current epoch, the search is not executed and fetched from browser cache.

Code starts here:
https://github.com/the-djmaze/snappymail/blob/ad6b51f76f20f8e523ba86c466f68cacd787a89d/snappymail/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php#L614

And in there the `strlen($sSearch)` part is the important searching code

**Comment by jdaviescoates** [comment]
> Search does work for me.

It's not that it doesn't work at all for me. Some results are shown, but *loads* that ought to be, aren't. 

I'll investigate further when I find the time, but I'm fairly certain it isn't working as it should (because if it was search the subject field for the exact subject of the email I couldn't find would find that email).

**Comment by virtualizeone** [comment]
Hello, I am having the same problem, I found out that these emails, when you see the source are with broken encoding.
like `Subject: =?utf-8?B?VHJhbnNmZXLDqm5jaWFzIHJlY2ViaWRhcyBCQiAtIDEyLzA=?= `=?utf-8?B?Ni8yMw==?=` , really don´t know why it happens to some emails and others don´t. But that is why we can´t find them in the search.

**Comment by the-djmaze** [comment]
Interesting. It seems your IMAP server can't decode base64 utf-8 text.

I will test if Dovecot also has issues with them.

**Comment by chsleemsi** [comment]
Hello, I am having the same problem.
[2023-11-16 08:49:35.771][def771e2] [INFO]: Get Serialized UIDS from cache ("INBOX" /  / UNDELETED) [count:23]
[2023-11-16 08:49:35.771][def771e2] [INFO]: Get Serialized UIDS from cache ("INBOX" /  / OR OR OR FROM "VMware End of Support information" TO "VMware End of Support information" CC "VMware End of Support information" SUBJECT "VMware End of Support information" UNDELETED) [count:0]
[

**Comment by chsleemsi** [comment]
SSL/TLS, 993

**Comment by the-djmaze** [comment]
> Sorry, I am not sure what do you mean by IMAP daemon.

We need the name of your IMAP software.

**Comment by chsleemsi** [comment]
Do you mean the IMAP server which is mail.psmail.net?!

**Comment by mschilli87** [comment]
@chsleemsi: I think they refer to the software that is responding to IMAP requests made to that server on that server. For example, I use dovecot on my server, but somebody else might opt for mailu instead. There are many options out there and I think that's what the question is aiming at.

**Comment by chsleemsi** [comment]
Thanks mschilli87!  Sorry for my ignorant.  However, I don't know how to find out what software I am using.  We use SnappyMail v2.29.4 on Nextcloud v26.0.  The email domain is set up through SnappyMail - Admin Panel.  The Nextcloud is hosted on Ubuntu VM.

We used RainLoop before but it is not compatible with Nextcloud v26.0 that was why we migrated to SnappyMail recently and which RainLoop suggest.  

There was no search problem on RainLoop but all of the users facing the problem about Search after we have migrated to SnappyMail.

**Comment by mschilli87** [comment]
@chsleemsi:
> I don't know how to find out what software I am using.

Maybe you could consult https://info.psmail.net/xsupport/?

**Comment by jdaviescoates** [comment]
OK, so searching for the emails SnappyMail couldn't previously find as mentioned in the OP does now work...

BUT I've just hit another even more serious example of search being broken/ useless! :sob: 

I just searched for an email from a specific email address by searching for the exact email address and it doesn't find it! Again, Roundcube finds it fine. 

If I do: 

from:natasha

It actually finds the email fine.

But if I do:

natasha@example.com

It doesn't find anything at all.

Same with:

from:natasha@example.com

What's going on?!?

**Comment by the-djmaze** [comment]
To find out, we need the log.
https://m.youtube.com/watch?v=FR-REDevAzk

**Comment by chsleemsi** [comment]
Morning djmaze, don't know why but the search working now.  I guess someone from the server side did something.

**Comment by jdaviescoates** [comment]
> To find out, we need the log.
> https://m.youtube.com/watch?v=FR-REDevAzk

Haha, I thought that was perhaps going to be handy view about exactly which logs you want and where exactly to find them! But now, it's a clip from Ren and Stimpy (I used to enjoy that show).

I've just enabled logging here at `my-nextcloud-url/apps/snappymail/?admin#/config`

![image](https://github.com/the-djmaze/snappymail/assets/2113743/d5cd6b03-0e8f-4dfa-9dc9-a599e22f1221)

But not sure what (if anything) to put in the path?

I also checked this box here in `my-nextcloud-url/settings/admin/additional`

![image](https://github.com/the-djmaze/snappymail/assets/2113743/4a54bd4a-91d2-4d4e-9253-4934e60c5c38)

What next?

**Comment by the-djmaze** [comment]
By default the lognis in the data directory of Nextcloud.
Something like `data/app_snappymail/default/logs`

**Comment by jdaviescoates** [comment]
OK @the-djmaze so here are some recent logs:

https://paste.uniteddiversity.coop/?d30b147d210a9f32#CU7VfW1gy6Rj1xna47c8tzSReXhyPcZCGhfKZcVB3zBp (pw: snappy)

I'm still finding the search to be pretty useless :sob: I just searched for `inov8` and it didn't find most of the related emails. Then again when searching for `enquiries@inov-8.com` it didn't find any of the emails from that address.  

I may have to just go back to using Roundcube as search works pretty well there. But that'd be a shame as I otherwise like SnappyMail and how it's nicely integrated into Nextcloud. Hopefully the logs will shed some light on why it's not working.

**Comment by the-djmaze** [comment]
SnappyMail relies on the search capabilities of the IMAP server.
Roundcube downloads all messages and seaches in its own database.

**Comment by jdaviescoates** [comment]
from=emailaddress still doesn't work which is rather frustrating

> SnappyMail relies on the search capabilities of the IMAP server.

Is this a SnappyMail issue or is it because of the search capabilities of the IMAP server?

How can I help to investigate why this isn't working?

**Comment by the-djmaze** [comment]
> Is this a SnappyMail issue or is it because of the search capabilities of the IMAP server?

Probably the IMAP server.

Using dovecot i can even search unicode:
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/cbd7e7f3-fa64-48c3-8f87-d63f753c8c96)

**Comment by jdaviescoates** [comment]
> Using dovecot i can even search unicode:

Dovecot is the exact same IMAP server that my system is running too though :thinking:

**Comment by jdaviescoates** [comment]
What's odd is that e.g. searching for admin@sustainablebridport* works, but searching for admin@sustainablebridport.com fails to display any results.

**Comment by the-djmaze** [comment]
Open a message from the search that works.
Look in the From, To, boundary etc. headers for issues.

You can also forward th email as attachment to issue-1096@snappymail.eu and i will take a look/test.
