### ISSUE TITLE
Hide Nextcloud interface (Open Snappymail in frame)

### ISSUE THREAD

**Issue by DragDrop69** [the-djmaze/snappymail#1097]
Good day! i have snap Nextcloud + Rainloop. Today i trying use Snappymail.
How to use Snappymail without Nextcloud interface? In Rainloop can add /nextcloudpath/apps/Rainloop/app/ and Webmail will open without nextcloud.

**Comment by the-djmaze** [comment]
You can't because it is integrated.
Use the standalone version instead.

**Comment by DragDrop69** [comment]
> You can't because it is integrated. Use the standalone version instead.

But rainloop integrated too. Rainloop Was installed as nextcloud application. If add to rainloop address /add/ - nextcloud interface is hide. 

Snappy mail can't?

**Comment by the-djmaze** [comment]
> But rainloop integrated too

Not really. SnappyMail has better integrations.
