### ISSUE TITLE
Openpgp section is visible even after disabling it

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#1098]
**Describe the bug**

Openpgp section is visible in security tab of user even after explicitly disabling it from admin settings 

**To Reproduce**
1. Go to snappymail admin section > security
2. Disable openpgp
3. Go to user account in snappymail > settings > security
4. See openpgp section being visible

**Expected behavior**

Completely remove this section when it is disabled

**Screenshots**

![image](https://user-images.githubusercontent.com/16881005/233070498-3264c830-e848-4061-9833-a096413c2847.png)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: 2.27.3
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]: Nextcloud/standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
OpenPGP is a widely used email encryption standard.
SnappyMail integrates this using:
* OpenPGP.js
* GnuPG
* Mailvelope

The admin/application.ini setting is for OpenPGP.js and not Mailvelope nor GnuPG.
That's why it works and you don't see OpenPGP.js

**Comment by Niveshkrishna** [comment]
@the-djmaze My question is why do we see this section when we explicitly disabled OpenPGP in security settings. Previously this wasn't the case. This section was completely hidden

![image](https://user-images.githubusercontent.com/16881005/235077545-957acfcb-0745-4dfb-966b-b032824cdea2.png)


![image](https://user-images.githubusercontent.com/16881005/235077592-8f94e72b-9615-402f-8a74-551fcaf3a7ef.png)

**Comment by Niveshkrishna** [comment]
@the-djmaze Sorry for digging this issue out of grave. When we disable openpgp.js from application.ini, what is the point of having this `import key` button? There is no response when I paste keys after clicking import key
