### ISSUE TITLE
Time is displayed wrong

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1099]
**Describe the bug**
It displays 24:55 instead of 00:55

**To Reproduce**
1. Change the time format in settings to "24:00 (24 hour)"
2. Receive an email after 00:00
3. Look at the time displayed
4. See it being displayed wrong

**Expected behavior**
It displays 00:55

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43847817/233600883-86b7b5cf-7a60-48ff-bbbe-32e67c832c99.png)

**Please complete the following information:**
- Browser: Firefox 111.0.1
- PHP version: 8.1
- SnappyMail Version: 2.27.3

**Additional context**
I recently changed the hour format in settings from "Default" to "24:00 (24 hour)" and the bug appeared. After changing it back to "Default" (and RELOADING !!!) the bug was gone.

**Comment by the-djmaze** [comment]
This is not a bug, it works as it should.
Try 23:00

**Comment by codiflow** [comment]
That's interesting – never seen this kind of "time format" in the wild ever before.

I must admit that I've not checked the other entries – I just assumed they are like everywhere else (12 / 24h setting). But as I can see now it seems to be on purpose.

Thanks for the clarification, I think we can close the issue.
