### ISSUE TITLE
Sieve filters for beginners

### ISSUE THREAD

**Issue by evritchie** [the-djmaze/snappymail#1101]
I see that snappymail has a feature that users cannot create sieve filters using drop-down menus. However, that does not appear for me. I was at 2.10 and just upgraded to 2.27.3 but still same issue. Im able to create a script using the sieve language and in 2.27.3 there are helpful guides. But for beginners I'd like to offer the gui based filter creation.

Thanks
Eric

**Comment by the-djmaze** [comment]
Did you read #80 ?

**Comment by evritchie** [comment]
Hi,
   I just read post +80, its still not clear to me, are you saying the basic filter mode with the gui is not supported anymore? I now have a checkbox on the filter screen that says "RainLoop user", if I click on that I get an error that the script does not exist.
Thanks
