### ISSUE TITLE
data exceeds "Content-Length" specified in header

### ISSUE THREAD

**Issue by ro56** [the-djmaze/snappymail#1103]
occurs on starting snappymail-app in local nextcloud-setup. Login fails. In standalone setup everything works fine.

chrome-screen says:

An error occurred.
Please refresh the page and try again.TypeError: Failed to fetch

firefox-screen:

An error occurred.
Please refresh the page and try again.TypeError: Decoding failed. 

in nginx logfile I find:

**...upstream sent more data than specified in "Content-Length" header while reading upstream, client:xxx.xxx.xxx.xxx, server: ......, request: "GET /apps/snappymail/?/AppData/0/7792280662262194/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "....."**

nextcloud/snappymail running on
Ubuntu Linux 20.04.6
Nginx 1.22.1
php 8.1
nextcloud 26.0.1
snappymail 2.27.3

**Comment by the-djmaze** [comment]
"upstream sent more data than specified in "Content-Length" header"
There should be no Content-Length header at all in Nextcloud 25.
But you are using Nextcloud 26 and maybe Nextcloud introduced a bug that causes this issue.

To verify, can you check Nextcloud 25?

**Comment by ro56** [comment]
sorry, but I can't get a stable v25 with your latest snappymail. and my logfiles don't go back as far as before v26's install. 
so I can't really tell which update introduced the issue.


Mit freundlichen Grüßen

Rainer Ophoven
Im Pettches Garten 84
64331 Weiterstadt
+49 178 5495609

**Comment by the-djmaze** [comment]
I've analyzed Nextcloud 26 but could not find changes that set the "Content-Length" header.
Are you using a proxy or something else that makes this fail?

**Comment by ro56** [comment]
Attached an nginx debug.log - pretty big. the crucial part is easy to find, the line is weighed "[warn]".

my environment is:
nginx 1.23.4
php8.1-fpm
nextcloud 26.0.1
snappymail 2.27.3
[debug.log](https://github.com/the-djmaze/snappymail/files/11422505/debug.log)

**Comment by ro56** [comment]
it's vanished: 
I upgraded php to 8.2,
amended the latest configuration hints into nginx config files,
removed snappymail and 
reinstalled it.
now everything works fine.
Sorry for the inconvenience

**Comment by the-djmaze** [comment]
> Sorry for the inconvenience

No problem. Good that it works.
