### ISSUE TITLE
Some features are not working

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#1106]
I recently changed server.

Previous server was working everything ok. 

Now, on the new server can't upload above 15 mb files.

nginx and php.ini values are the same.

PHP versions differ: 

Works ok with php 7.4 and not with 8.1, Is it compatible with 8.1?

BTW:
nginx:
`client_max_body_size 1024M;`

php.ini
`upload_max_filesize = 1024M`
`post_max_size = 1024M`

application.ini
; File size limit (MB) for file upload on compose screen
; 0 for unlimited.
attachment_size_limit = 200

**Comment by chrisdent** [comment]
update: It does uploads the same file in Files.

**Comment by the-djmaze** [comment]
Does you SMTP server have limits?
Mostly there is a SMTP limit around 25MB

**Comment by randolf** [comment]
> Does your SMTP server have limits? Mostly there is an SMTP limit around 25MB

Many SMTP servers are also set even lower, to 5MB or 10MB.

SMTP servers should be reporting a 556 "Message too large" error, but not all SMTP servers actually do this.
