### ISSUE TITLE
git  tag for release

### ISSUE THREAD

**Issue by gene-git** [the-djmaze/snappymail#111]
There are git tags for each release up to 2.6.0 but not 2.6.1 or 2.6.2
I've been using the git tag for part of the package name. Should I have the build read  the package.json file and pull version from there instead you think.

thanks as always.

**Comment by the-djmaze** [comment]
Are you sure?
See: https://github.com/the-djmaze/snappymail/tags

**Comment by gene-git** [comment]
Well i just did another git pull and this time  the 2 tags came in  - for some reason they didn't earlier. Bit odd isn't it.
I changed package name to be json_vers-git_tag.
git or github acting up a bit - maybe their nap time :)
