### ISSUE TITLE
New messages audio notification is playing twice

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1110]
The new messages audio notification is playing twice at the same time when in the webmail UI. It is only played once when previewing it in the settings page.

**Comment by Zero3K** [comment]
Can anyone replicate it?

**Comment by Zero3K** [comment]
Hmm?

**Comment by Zero3K** [comment]
Should I make a video of the issue?

**Comment by Zero3K** [comment]
*bump*

**Comment by a-kriya** [comment]
> Should I make a video of the issue?

That'd be helpful.

**Comment by Zero3K** [comment]
Never mind, it is not a bug.

**Comment by Zero3K** [comment]
It seems to be random.
