### ISSUE TITLE
Cannot access Snappymail in Nextcloud with Gmail

### ISSUE THREAD

**Issue by witzker** [the-djmaze/snappymail#1114]
Hi,
I have read there should be some Admin settings for snappy mail, but I have only this in NC 25.0.5
https://github.com/the-djmaze/snappymail/blob/master/integrations/nextcloud/snappymail/README.md

I have put there my@gmail.com address
![grafik](https://user-images.githubusercontent.com/4120266/235437763-fc82c917-582b-446b-852d-b3d9a9367434.png)

go to the Snappy mail 
BUT
![grafik](https://user-images.githubusercontent.com/4120266/235437566-bdfab6f9-86f6-403b-9774-35ebb2e1ff8d.png)

when I tried my Email from IONOS ( hosting)
I get This:
![grafik](https://user-images.githubusercontent.com/4120266/235437883-be7d4a7f-b5a0-46e9-ba71-56cb3e007a83.png)

PLs. Help to get this working
many THX

**Comment by the-djmaze** [comment]
Go to your nextcloud/settings/admin/additional

**Comment by the-djmaze** [comment]
You are looking at the user settings.
As is said, look at the admin settings.

**Comment by witzker** [comment]
Ah…!
Many many THX you for your patience
I still can't log in to Snappy mail as an administrator
How do you do this with the administrator account?
Is there a guide somewhere for me as an absolute dummy?

**Comment by the-djmaze** [comment]
What happens when you click the green circled link?
![afbeelding](https://user-images.githubusercontent.com/3752035/235700088-b44e7181-5cdc-4aff-ac4e-248a333df9e2.png)

**Comment by the-djmaze** [comment]
For gmail you need an app password.
https://support.google.com/accounts/answer/185833?hl=en

**Comment by witzker** [comment]
ok but I have no opion in my google account

Create & use App Passwords
If you use [2-Step-Verification](https://support.google.com/accounts/answer/185839) and get a "password incorrect" error when you sign in, you can try to use an App Password.

Go to your [Google Account](https://myaccount.google.com/).
Select Security.
Under "Signing in to Google," select App Passwords. You may need to sign in. If you don’t have this option, it might be because:
2-Step Verification is not set up for your account.
2-Step Verification is only set up for security keys.
Your account is through work, school, or other organization.
You turned on Advanced Protection.

![image](https://user-images.githubusercontent.com/4120266/235722219-9aa8b4da-8c27-4e14-addd-df8da7d00dcb.png)

**Comment by witzker** [comment]
THX - does that mean I cannot use Gmail in snappy?

**Comment by the-djmaze** [comment]
Go to: Bestätigung in zwei schritten
When active: scroll to the bottom of the page.
You should see something like:
![afbeelding](https://user-images.githubusercontent.com/3752035/236792997-40b45ba4-d1be-42c9-8b38-4d7db7c757a7.png)

**Comment by the-djmaze** [comment]
@m-i-k-e-y 
> Existing app passwords can be used, but you can not create new ones.

I can create new ones ;)

**Comment by m-i-k-e-y** [comment]
@the-djmaze 

We are both correct. You can create new app passwords, if you have already one. But you can't create app passwords, if you don#t have any.

Just verified this with the two accounts I have: 
One account has app passwords and I can create new ones with that account, The other account doesn't have app passwords and I can't create one with that account.

**Comment by m-i-k-e-y** [comment]
@witzker 
You should change the issue description to reflect that this an issue with Gmail accounts and not a general one with Snappymail in Nextcloud.

**Comment by witzker** [comment]
Not only Gmail is affected, I also cannot log in with an Ionos Email address
So the general login process should be described somewhere.
Sorry, I really don't understand the concept of how to be able to log into Snappy mail

Maybe a step-by-step guide could help.
1. install Snappy with apps in Nextcloud
2. GOTO administration under admin GOTO Advanced settings
3.  Login to Go to Snappy Mail Webmail admin panel 
4. create a domain ( IONOS)
5. Create an Alias with the domain after the @ 
6. test the settings - If all green
7. GOTO snappy and login with the email@domain you have edited

So fare OK?

**Comment by the-djmaze** [comment]
> If I can't create an App Password with that account?

Correct!
I could add support for OAuth but it means that you need to register your app at google and submit an explanation with video to approve SMTP support.
I just don't have the power like Thunderbird to register SnappyMail as single app, as it is installed on many different servers (not clients).

**Comment by witzker** [comment]
THX for taking care about the Gmail problem:

As I'm more a user than a serverstuffexpert I sum up what I have understood so far:

 I cannot use Snappy Mail as is with Gmail accounts!

You wrote:

> I could add support for OAuth but it means that you need to register your app at google and submit an explanation with video to approve SMTP support.

Pls. Explain the steps to be taken step by step.
How to:
1. to register your app at Google
2. submit an explanation with video to approve SMTP support.

Many THX for further advice.

**Comment by witzker** [comment]
Where do you see the advantages of using Snappy vs Nextcloud mail App?
