### ISSUE TITLE
Improve UI for Settings -> Filter

### ISSUE THREAD

**Issue by djast** [the-djmaze/snappymail#1115]
**Is your feature request related to a problem? Please describe.**
The Settings -> Filter user interface could be improved:
- When hovering over either the radio button or the name of a script, the entire line is highlighted; this gives the user the incorrect impression that they are a single control (i.e., that clicking the label should have the same effect as clicking the radio button);
- Hovering over a category name (Simple or Advanced) highlights it as though it were clickable;
- "Simple" is presented as a category for filters even though only there can (as far as I know) only ever be one script in the category ("rainloop.user");
- The detail that the simple filters are implemented as a Sieve script named "rainloop.user" could probably be hidden from the user (as it is in Rainloop).

**Describe the solution you'd like**
- Hovering over the radio button for a script should only highlight the radio button;
- Hovering over the name of a script should only highlight the script name (and hovering over text like "Inactive" or "Advanced" should not highlight anything, as these elements are not clickable);
- If it's intended that the rainloop.user script will be the only interface for Simple filters, the interface could be streamlined, e.g., something like:

( ) Inactive
( ) Simple
Advanced
&nbsp;   ( ) User Script 1
&nbsp;   ( ) User Script 2
[+ Add a Script]

(where the user could click on "Simple" to edit the rainloop.user script, and the parentheses above indicate radio buttons).

It might be also worthwhile to add basic instructions to the top of the page on how to create, modify and activate simple and advanced filters.

**Comment by the-djmaze** [comment]
The hover issue is caused by bootstrap.css
https://github.com/the-djmaze/snappymail/blob/a043eaec814897ad949e397b8be5cfb9659dc65f/vendors/bootstrap/less/tables.less#L113-L123

So either it would be no :hover effect at all, or as-is.

**Comment by djast** [comment]
The CSS could be overridden with something like:
> table.table-hover tbody th:hover {
>   background-color: inherit;
> }

**Comment by the-djmaze** [comment]
You can think of something different

```css
.script-item .e-action {
    font-weight: bolder;
    text-decoration: green wavy underline;
}
```
