### ISSUE TITLE
Interface : Allow to see the attachment in top of text page

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#1119]
To add an Attachment, I click on the button on right of button bar (attach +).
But the interface go in "Attachment" mode, hiding the textual part.
The user don't understand why and how going back to textual part.

The proposal is to display the attached file on top of text part and not manage the left button to choose text or attachment.

**Comment by the-djmaze** [comment]
I understand you, but the problem is small screen heights.
You can't have everything in view then.

Instead if the small buttons, we could uses tabs:
![afbeelding](https://user-images.githubusercontent.com/3752035/236773868-c1c81a56-2d9a-4678-8553-c93fbf08b89c.png)

**Comment by dominiquefournier** [comment]
I think the  tabs with the text and the number of attachments may be much better !
Thanks
