### ISSUE TITLE
Recognizion and extraction of .dat files

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#1120]
When a file, e.g. a calender is packed by some programs into a .dat file, snappymail does not split them and show the included files.

The expectation is, the file is extracted correctly and the containing files are shown. 
This works. e.g. with Horde or other mail systems quite well

**Comment by the-djmaze** [comment]
Correct. SnappyMail does not (temporary) store attachments.
It only passthru as-is with some first bytes and content-type header detection.

We can add more detectections if we have the source of the email.

**Comment by Bolli84** [comment]
How can I send you the mail source?

**Comment by the-djmaze** [comment]
You can attach it here (when not privacy is involved) or send to issue-1120@snappymail.eu

**Comment by Zero3K** [comment]
You can remove the email address from it and attach it.
