### ISSUE TITLE
Error when adding to Nextcloud Calendar invite event

### ISSUE THREAD

**Issue by diegotorreslopez81** [the-djmaze/snappymail#1121]
**Describe the bug**
I've installed Snappymail app on Nextcloud v25.0.4. When I received an email with a calendar invite, I click on "Put in Calendar" but nothing happens. Check option in Nextcloud plugin is active.

**To Reproduce**
1. Go to 'snappymail' app nextcloud menu bar.
2. Click on 'Put in Calendar' when you received an invite (.ics) file.
3. Then click on the calendar to add, but nothing happens.
4. See error on Console:

XHRPUT
https://box.pdata.org/remote.php/dav/calendars/mailcow-diego@pdata.org/family/00it5d7di274j99gfcok4bele2@google.com.ics
[HTTP/2 403 Forbidden 138ms]

Uncaught (in promise) Error: [object Object]
    calendarPut https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:1
    promise callback*calendarPut https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:1
    nextcloudSaveICS https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:2
    promise callback*d.nextcloudSaveICS https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:2
    init https://box.pdata.org/apps/snappymail/app/snappymail/v/2.27.3/static/js/min/libs.min.js:1
[snappymail:1:6329](https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/)
XHRPUT
https://box.pdata.org/remote.php/dav/calendars/mailcow-diego@pdata.org/nga/00it5d7di274j99gfcok4bele2@google.com.ics
[HTTP/2 403 Forbidden 137ms]

Uncaught (in promise) Error: [object Object]
    calendarPut https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:1
    promise callback*calendarPut https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:1
    nextcloudSaveICS https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:2
    promise callback*d.nextcloudSaveICS https://box.pdata.org/apps/snappymail/?/Plugins/0/User/2d0b215e9905994bc459a2747921bd04/:2
    init https://box.pdata.org/apps/snappymail/app/snappymail/v/2.27.3/static/js/min/libs.min.js:1

**Expected behavior**
It supposed to be added the calendar event.

**Screenshots**

**Please complete the following information:**
- Browser: firefox 112.0.2 (64-bit)
- IMAP daemon: mailcow
- PHP version: mailcow? (I don't know)
- SnappyMail Version: 2.27.3
- Mode:  nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
don't know how to get it

**Additional context**
nothing else

**Comment by the-djmaze** [comment]
The calendar at `/remote.php/dav/calendars/mailcow-diego@pdata.org/family/` is 403 Forbidden.
Do you have the correct access rights?
