### ISSUE TITLE
HestiaCP Install not working

### ISSUE THREAD

**Issue by LIFETAB** [the-djmaze/snappymail#1128]
**Describe the bug**
I tried to use your v-add-sys-snappymail file to install snappymail on hestiacp, but i get errors.

**To Reproduce**
1. Install hestiacp 
2. Setup the domain and mail services
3. Download the integration for hestiacp form this respository
4. Put it into this directory /usr/local/hestia/bin and give it permissions.
5. run v-add-sys-snappymail as root user in your terminal

**Expected behavior**
I expected snappymail to install with no problems

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/43006406/f1507307-3892-4592-a174-79747e79ecdb)

**Please complete the following information:**
### **I don' know i just used your integration script with hestiacp**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
there are no except for the screenshot above

**Comment by the-djmaze** [comment]
Does the following work?
`wget "[$SM_URL](https://snappymail.eu/repository/latest.tar.gz)" --retry-connrefused --quiet -O "/var/lib/snappymail/snappymail-latest.tar.gz"`

**Comment by LIFETAB** [comment]
The command works, but the installation doesn't :/

![image](https://github.com/the-djmaze/snappymail/assets/43006406/5fd6fd81-1b43-4217-8794-28e16a06381d)

**Comment by LIFETAB** [comment]
Can you fix it or help me out @the-djmaze? Maybe i'm doing something wrong idk.

**Comment by the-djmaze** [comment]
I might could fix it, but i don't have Hestia.
Currently it is draft code and someone might do a better job at it.

Also see https://github.com/hestiacp/hestiacp/issues/2620

**Comment by the-djmaze** [comment]
Try with https://github.com/the-djmaze/snappymail/tree/master/integrations/hestiacp

`bin/v-add-sys-snappymail` to hestia `bin/v-add-sys-snappymail`
`install/deb/snappymail/install.php` to hestia `install/deb/snappymail/install.php`

**Comment by LIFETAB** [comment]
Could you tell me when you have fixed it? Thank you!

**Comment by the-djmaze** [comment]
I can't as i don't use HestiaCP
Someone should test and finish my code at https://github.com/hestiacp/hestiacp/pull/3590

**Comment by LIFETAB** [comment]
Okay

**Comment by jaapmarcus** [comment]
> I can't as i don't use HestiaCP
> 
> Someone should test and finish my code at https://github.com/hestiacp/hestiacp/pull/3590

Working on it..

It should work right now...

**Comment by LIFETAB** [comment]
Thank you!
I've found the error, the plugin 'change_password' has the settings for hestia: "hestia_host" and "hestia_port". The driver for hestia in /plugins/change-password-hesita/driver.php expects a variable of "hestia_login",. 

I would suggest to update this line in the driver for hesita: `$sHost = $this->oConfig->Get('plugin', 'hestia_login');` to 
`$sHost = $this->oConfig->Get('plugin', 'hestia_host');`.

**Comment by jaapmarcus** [comment]
> hestia_login

That fixes the issue...

**Comment by LIFETAB** [comment]
> > hestia_login
> 
> That fixes the issue...

What do you mean? I've changed the line in the driver to get the variable hestia_host from the snappymail plugin and use as the host url of hestia, before that it tried to get the variable hestia_login which is not existing in the plugin configuration, so it tried to access hestia at https://:8083/. Now its working correctly and accessing it with https://[url or ip of hestia]:8083/

**Comment by jaapmarcus** [comment]
https://github.com/the-djmaze/snappymail/pull/1135/commits/0ae7b11776a54fda4f7075025fc45b3d70a32912

**Comment by LIFETAB** [comment]
Oh, nvm I didn't notice you changed it. Btw thank you for such fast work on integrating snappymail into hestia :)

**Comment by michelsouzams** [comment]
Is it possible to install on a normal cpanel hosting like rainloop?

**Comment by the-djmaze** [comment]
jaapmarcus has improved and fixed my attempt and merged it into HestiaCP

**Comment by jaapmarcus** [comment]
Will be released with 1.8  ...

**Comment by michelsouzams** [comment]
I want to install on a cpanel hosting account, it would not be on WHM. Normal hosting as I already do with Rainloop. It's possible ?

**Comment by jaapmarcus** [comment]
In your case you will need to download snappy mail and install it the same way as you did with Rainloop it should work fine.

How ever this is not related to this issue...

**Comment by jaapmarcus** [comment]
Create a new issue. It is not related to this issue or HestiaCP

**Comment by michelsouzams** [comment]
Thanks!

**Comment by demlasjr** [comment]
Hi @the-djmaze,
I just installed snappymail using the v-add-sys-snappymail command, everything installs just well but I cannot login into any email address, either admin panel. This is what I'm getting from the logs. I'm kinda lost trying to debug it.

`[2023-08-17 11:25:10.042][a13636a2] [INFO]: [SM:2.28.4][IP:79.117.16.168][PID:224846][Apache/2.4.57 (Debian) mod_fcgid/2.3.9 OpenSSL/3.0.9][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://webmail.test.net/?/Json/&q[]=/0/]
[2023-08-17 11:25:10.043][a13636a2] JSON[INFO]: Action: DoLogin
[2023-08-17 11:25:10.043][a13636a2] POST[INFO]: {"Email":"test@test.com","Password":"*******","language":"","signMe":"1","Action":"Login"}
[2023-08-17 11:25:10.043][a13636a2] IMAP[INFO]: Start connection to "tcp://locahost:143"
[2023-08-17 11:25:10.044][a13636a2] IMAP[INFO]: Connect (success)
[2023-08-17 11:25:10.044][a13636a2] IMAP[DEBUG]: 0.00020599365234375 (raw connection)
[2023-08-17 11:25:10.049][a13636a2] IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Mail Delivery Agent\r\n
[2023-08-17 11:25:10.049][a13636a2] IMAP[DEBUG]: 0.0058109760284424 (*)
[2023-08-17 11:25:10.049][a13636a2] IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN *******\r\n
[2023-08-17 11:25:12.052][a13636a2] IMAP[INFO]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
[2023-08-17 11:25:12.052][a13636a2] IMAP[DEBUG]: 2.002366065979 (TAG1)
[2023-08-17 11:25:12.052][a13636a2] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(181): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin()
#5 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(418): RainLoop\Model\Account->ImapConnectAndLogin()
#6 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#7 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#8 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#9 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#10 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#11 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#12 /var/lib/snappymail/index.php(11): include('...')
#13 {main}
[2023-08-17 11:25:12.052][a13636a2] IMAP[NOTICE]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(181): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin()
#5 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(418): RainLoop\Model\Account->ImapConnectAndLogin()
#6 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#7 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#8 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#9 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#10 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#11 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#12 /var/lib/snappymail/index.php(11): include('...')
#13 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException: AUTHENTICATIONFAILED Authentication failed. in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php:241
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(418): RainLoop\Model\Account->ImapConnectAndLogin()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#5 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#7 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#9 /var/lib/snappymail/index.php(11): include('...')
#10 {main}
[2023-08-17 11:25:15.039][a13636a2] SERVICE[WARNING]: AuthError[102]
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#6 /var/lib/snappymail/index.php(11): include('...')
#7 {main}
[2023-08-17 11:25:15.039][a13636a2] SERVICE[WARNING]: - AUTHENTICATIONFAILED Authentication failed. @ /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php#241
[2023-08-17 11:25:15.039][a13636a2] [ERROR]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php(181): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin()
#5 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(418): RainLoop\Model\Account->ImapConnectAndLogin()
#6 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#7 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#8 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#9 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#10 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#11 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#12 /var/lib/snappymail/index.php(11): include('...')
#13 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException: AUTHENTICATIONFAILED Authentication failed. in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/MailSo/Imap/ImapClient.php:241
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(418): RainLoop\Model\Account->ImapConnectAndLogin()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#5 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#7 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#9 /var/lib/snappymail/index.php(11): include('...')
#10 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php:429
Stack trace:
#0 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect()
#1 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/User.php(44): RainLoop\Actions->LoginProcess()
#2 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 /var/lib/snappymail/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /var/lib/snappymail/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#6 /var/lib/snappymail/index.php(11): include('...')
#7 {main}
[2023-08-17 11:25:15.039][a13636a2] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"AUTHENTICATIONFAILED Authentication failed.","epoch":1692271515}
[2023-08-17 11:25:15.039][a13636a2] [INFO]: Memory peak usage: 2MB
[2023-08-17 11:25:15.039][a13636a2] [INFO]: Time delta: 5.0003340244293
[2023-08-17 11:25:15.039][a13636a2] IMAP[INFO]: Disconnected from "tcp://localhost:143" (success)
[2023-08-17 11:25:15.039][a13636a2] IMAP[DEBUG]: 4.9959609508514 (net session)
`

Any idea? Thanks!
