### ISSUE TITLE
No email on first access

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#1129]
**Describe the bug**
I updated from 2.27.2 to 2.27.3 and when I logged into my account with SnappyMail for the first time in a web browser, there were always no emails at first, then after a while the emails started showing up.
Is there a feature like past cache view missing in 2.27.3?

**To Reproduce**
1. Log in to SnappyMail via PC or Smartphone

**Expected behavior**
A list view of the last received email.

**Please complete the following information:**
- Browser: Any
- IMAP daemon: Courier
- PHP version: 8.0.27
- SnappyMail Version:　2.27.3
- Mode: standalone

**Comment by the-djmaze** [comment]
The problem here is speed.
Web requests timeout after several seconds, but the process to index mail is still busy.

I have some ideas to solve this, but no definite yet due to all different server configurations.

**Comment by the-djmaze** [comment]
Follow #1071 as this issue is related to that one
