### ISSUE TITLE
Improve Redis configuration

### ISSUE THREAD

**Issue by Alphix** [the-djmaze/snappymail#113]
The `redis` configuration allows a host and port to be set via the `fast_cache_redis_host` and `fast_cache_redis_port` variables.

However, it isn't currently possible to define a `password` and the `database` to use (see the `Connecting to a database` section [here](https://github.com/predis/predis/wiki/Quick-tour)).

I tried hardcoding a `password` by modifying `function __construct` in `app/libraries/MailSo/Cache/Drivers/Redis.php` from:

```
        function __construct(string $sHost = '127.0.0.1', int $iPost = 6379, int $iExpire = 43200, string $sKeyPrefix = '')
        {
                $this->sHost = $sHost;
                $this->iPost = $iPost;
                $this->iExpire = 0 < $iExpire ? $iExpire : 43200;

                $this->oRedis = null;

                try
                {
                        $this->oRedis = new \Predis\Client('unix:' === substr($sHost, 0, 5) ? $sHost : array(
                                'host' => $sHost,
                                'port' => $iPost
                        ));
```
to:
```
        function __construct(string $sHost = '127.0.0.1', int $iPost = 6379, int $iExpire = 43200, string $sKeyPrefix = '')
        {
                $this->sHost = $sHost;
                $this->iPost = $iPost;
                $this->iExpire = 0 < $iExpire ? $iExpire : 43200;

                $this->oRedis = null;

                try
                {
                        $this->oRedis = new \Predis\Client('unix:' === substr($sHost, 0, 5) ? $sHost : array(
                                'host' => $sHost,
                                'port' => $iPost,
                                'password' => 'foobar`,
                                'database' => '0'
                        ));
```

...and it worked. Would it be possible to add two more variables (`fast_cache_redis_password` and `fast_cache_redis_database`) to `snappymail`?

**Comment by the-djmaze** [comment]
Can you push a PR or should i just change it for you?

**Comment by Alphix** [comment]
My `PHP` skills are not the best. I'm trying to figure out what the best approach would be. `Predis` supports a `URL` style syntax which should be able to support all kinds of schemes (and it looks like the current code already looks for a `host` string which starts with `unix:`, as shown in the snippets above, so `URL` style syntax is halfway supported).

Problem is, so far I haven't been able to get the URL syntax to accept a password for `unix:` style connections...so I need to figure this out before I can do a proper PR.

**Comment by the-djmaze** [comment]
Although i merged and closed this issue, i'm reverting your changes for compatibility.
The real bug was only in MailSo\Cache\Drivers\Redis class.

Trick will now become:
fast_cache_redis_host = 'tcp://127.0.0.1:6379'
fast_cache_redis_port = 0

I also made this change to Memcache driver.

**Comment by ossplus** [comment]
#1534
