### ISSUE TITLE
Unable to preview body of encrypted mail in mailvelope reply-to

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#1130]
**Describe the bug**

When replying to an encrypted email in webmail using mailvelope, the original email body doesn't show in the mailvelope reply to window. Issue is similar to https://github.com/the-djmaze/snappymail/issues/1126

**To Reproduce**
1. Go to snappymail
2. Click on reply to for an encrypted email
3. Use mailvelope extension to reply
4. No body of original message to preview 

**Expected behavior**

Show body of original message

**Screenshots**

![image](https://github.com/the-djmaze/snappymail/assets/16881005/42e9c04e-47a0-485e-8872-a027d02cee44)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: 2.27.2
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] : nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
The mailvelope.createDisplayContainer() returns a DisplayContainer object that does not reveal the decrypted text.
Therefore SnappyMail can't access the code on reply/forward.

See:
https://mailvelope.github.io/mailvelope/Mailvelope.html#createDisplayContainer
https://mailvelope.github.io/mailvelope/global.html#DisplayContainer
