### ISSUE TITLE
Issue with arrow shown for address auto-completion

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1132]
The arrow stays after pressing Backspace enough times to remove the inputted text. It should disappear when the text box is made empty.

**Comment by the-djmaze** [comment]
Arrow? I don't see any arrow in inputs.

**Comment by Zero3K** [comment]
![image](https://github.com/the-djmaze/snappymail/assets/6194332/54fb02e0-d49d-4279-b714-411ddf770b6d)

**Comment by Zero3K** [comment]
Is there any alternative that doesn't have this issue?

**Comment by the-djmaze** [comment]
Try Firefox or different OS?
