### ISSUE TITLE
Nextcloud 26 - CSS seems wrong

### ISSUE THREAD

**Issue by celogeek** [the-djmaze/snappymail#1138]
The CSS of the composer seems wrong on nextcloud 26

**To Reproduce**
1. Go to SnappyMail on Nextcloud
2. Click on New Message

**Expected behavior**
It would be great if the look and feel is closer to the not integrated version. 

**Screenshots**
<img width="1012" alt="Capture d’écran 2023-05-21 à 16 20 02" src="https://github.com/the-djmaze/snappymail/assets/65178/1d232fa8-8c68-4f3b-a0ca-6f997dcc5d0b">

**Please complete the following information:**
- Browser: Arc Browser
- IMAP daemon: dovecot
- PHP version: 8.2.6
- SnappyMail Version: 2.27.3
- Mode: nextcloud

**Additional questions**
What are the expected composer screen ?
Did I miss something in my configuration ?

**Comment by the-djmaze** [comment]
Should be solved in next release.

**Comment by celogeek** [comment]
How can I test it ? can I use master branch and build the nextcloud plugin ?

**Comment by celogeek** [comment]
I'm trying to clone the project then:
```
yarn
php release.php --nextcloud
```

**Comment by celogeek** [comment]
I generate cert in $HOME/.nextcloud/certificates
```
openssl genrsa -out snappymail.key 2048
openssl req -new -key snappymail.key -x509 -days 999 -out snappymail.crt
```

**Comment by celogeek** [comment]
Ok finally I manage to install master.

here the result:
<img width="1032" alt="Capture d’écran 2023-05-27 à 12 00 19" src="https://github.com/the-djmaze/snappymail/assets/65178/1d167530-9647-453d-bb38-6ce30aa8b2a1">

It's way better.
Still need some works on the size of the button, they are not equal.
Select and Button have different size.

**Comment by celogeek** [comment]
well, I can't send mail anymore:

When I try to do the test it log this:
```
Call to undefined method MailSo\Smtp\SmtpClient::logMask()
```

**Comment by celogeek** [comment]
Found it, some signal capture lead to
```
May 27 12:25:36 nextcloud nginx[64]: 2023/05/27 12:25:36 [error] 64#64: *40037 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Error installing signal handler for 19 in /app/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/MailSo/Log/Logger.php on line 78; PHP message: PHP Fatal error:  Error installing signal handler for 19 in Unknown on line 0" while reading response header from upstream, client: 2a01:cb00:f9c:aa00:fc3a:8ec0:3137:417a, server: _, request: "GET /apps/snappymail/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "mydomain"
```

I comment in the Logger those signal:
- SIGCONT
- SIGINT
- SIGKILL
- SIGSTOP

**Comment by celogeek** [comment]
```
diff --git a/snappymail/v/0.0.0/app/libraries/MailSo/Log/Logger.php b/snappymail/v/0.0.0/app/libraries/MailSo/Log/Logger.php
index caaaace65..47386efe4 100644
--- a/snappymail/v/0.0.0/app/libraries/MailSo/Log/Logger.php
+++ b/snappymail/v/0.0.0/app/libraries/MailSo/Log/Logger.php
@@ -32,14 +32,14 @@ class Logger extends \SplFixedArray
                'SIGBUS',
                'SIGCHLD',
                'SIGCLD',
-               'SIGCONT',
+//             'SIGCONT',
                'SIGFPE',
                'SIGHUP',
                'SIGILL',
 //             'SIGINT',
                'SIGIO',
                'SIGIOT',
-               'SIGKILL',
+//             'SIGKILL',
                'SIGPIPE',
                'SIGPOLL',
                'SIGPROF',
@@ -47,7 +47,7 @@ class Logger extends \SplFixedArray
                'SIGQUIT',
                'SIGSEGV',
                'SIGSTKFLT',
-               'SIGSTOP',
+//             'SIGSTOP',
                'SIGSYS',
                'SIGTERM',
                'SIGTRAP',
```

**Comment by the-djmaze** [comment]
Thanks! I made your changes

**Comment by celogeek** [comment]
this is great.

<img width="1001" alt="Capture d’écran 2023-05-29 à 09 13 33" src="https://github.com/the-djmaze/snappymail/assets/65178/8dfdce51-f5f8-4355-b847-239925acd7e3">

It would be excellent when you merge on master to create a beta release.
So we can may be have an easy way to take the beta version from nextcloud.

I will close this issue, as it's fixed for me.
