### ISSUE TITLE
Fix width of message list and message contents

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#114]
The width is different between a server's Rainloop instance and the same server's SnappyMail instance. It would be nice if it could be made to be the same as Rainloop's (unless there's a way to do it and have it stay when updating to newer versions of SnappyMail). Here are the screenshots to show what I mean:

Rainloop:
![Rainloop Width](https://user-images.githubusercontent.com/6194332/130311118-f3d45b67-e7c3-48c1-bf47-0007b684030f.png)

SnappyMail:
![SnappyMail Width](https://user-images.githubusercontent.com/6194332/130311123-a78c4866-7eae-471b-98ae-d54aadc7fcf9.png)

**Comment by the-djmaze** [comment]
You are correct because RainLoop has no responsive design for it.
SnappyMail is responsive based on browser width.

**Comment by Zero3K** [comment]
Is there an issue that you see which needs fixing? If so, what is it?

**Comment by the-djmaze** [comment]
There is no issue.
Rainloop uses fixed widths:
```
width: 310px;
width: 400px;
width: 500px;
```

SnappyMail uses responsive widths:
```
width: 50%;
min-width:1401px = width: 40%;
```

This is because there are many screen sizes and we try to have a good size for every screen.
To see it in action you must have a large screen and resize the browser window.
