### ISSUE TITLE
Doc - Improvement of optional plugin doc (fix typo, make it clearer)

### ISSUE THREAD

**Issue by celogeek** [the-djmaze/snappymail#1140]
In the documentation we have:
```
xxtea to be faster then xxtea.php
OpenSSL for better encryption then XXTEA
Sodium for even better encryption then XXTEA and OpenSSL
```

It should be
```
xxtea to be faster than xxtea.php
OpenSSL for better encryption than XXTEA
Sodium for even better encryption than XXTEA and OpenSSL
```

It took me a bit of time to understand if I have to install all of them or only some.

But for a clearer explanation of what we should install

```
For faster, more efficient cryptography, install one of these modules (from best to worst):
- sodium
- openssl
- xxtea
```

Also the ?admin#/about
Should reflect that.

If you can have section when we need to have at least 1 of them like:

```
- Crypt OK (Sodium)
  - Sodium OK
  - Openssl KO
  - XXTEA KO
```

So if you have group like that, and one at least is ok, that would be easier.

Thanks

**Comment by the-djmaze** [comment]
I understand what you mean. The problem is multiple:

1. RainLoop only supports XXTEA. When migrating, SnappyMail needs XXTEA
2. When Sodium is gone (happens with cPanel EasyApache when EPEL is gone/disabled) then OpenSSL is used
3. When OpenSSL was used and you want Sodium, you should keep OpenSSL
4. and some other cases

So having all is the best

**Comment by celogeek** [comment]
Well, by reading the doc it's unclear what module should I install.
In my case I can install anything, all of them or part of them.
I don't know which one is the best.

The About should reflect group of optional dependencies, by best to ok.
So if you have at least one of them, then the group is ok
If you miss all of them, you have an alternative internal method, then a warning should be display.
Like
- Group A (warning: please install one of those to improve performance / security ..., I fallback to XXX)
  - Optional 1 X
  - Optional 2 X

**Comment by celogeek** [comment]
<img width="671" alt="Capture d’écran 2023-05-30 à 15 21 50" src="https://github.com/the-djmaze/snappymail/assets/65178/ef0b0b04-e92e-45f4-b86d-1cf4369932fd">

Here:

Graphic: (use Imagick: best one)
- Imagick | ✔
- Gmagick | ❌
- GD | ✔

**Comment by celogeek** [comment]
May be a description of the usage you have with the dependencies, so the people will install it if it's needed for them.

**Comment by the-djmaze** [comment]
Something like this?
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#xxtea-openssl--sodium

**Comment by celogeek** [comment]
So even if we have Sodium, XXTEA may be used in some cases even if we haven't install it ?
The doc looks ok
A clearer PHP Optional Extensions would be wonderful. In one look we should now which one is missing and which one is the best to install if we have choices.

Like:
```
Cryptographic: (use Sodium)
  - Sodium | Installed (Best one)
  - OpenSSL | Installed
  - XXTEA | Not installed

Graphic: (use Imagick)
  - Imagick | Installed (Best one)
  - Gmagick | Installed
  - GD | Not installed

Mandatory modules:
  - Phar | Installed

Optional modules:
  - Redis | Installed
  - Fileinfo | Installed
```

Just an example, but we can drive missing deps easily with this summary in the admin section.
