### ISSUE TITLE
How to add an item in settings tab by plugin

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1144]
Hello

   I'm writing a plugin that requiers to add an item to the user side settings page, 
I know it can be done by adding a tab, but I don't want to do that.

I want to add an option to an existing tab, for example, 
the General tab in the 

do you have any sugestion?

**Comment by the-djmaze** [comment]
addEventListener('rl-view-model') was missing for Settings.
Is fixed for next release in: https://github.com/the-djmaze/snappymail/commit/ffde5ddfb34ad88d9e6348248e3ffd3e4369fe2f

**Comment by the-djmaze** [comment]
Any luck with v2.28.1 ?

**Comment by rezaei92** [comment]
I'm still working on it, but feel free to close the issue if you want. 
I'll just reopen it later if I need to.
