### ISSUE TITLE
add a short help about password generation

### ISSUE THREAD

**Issue by zeroheure** [the-djmaze/snappymail#1145]
Before a sysadmin does something stupid like changing the admin_password.txt file content , it could help to add some help in admin panel which
- prevent this stupid sysadmin to do that
- explain how to recreate it

I'm sure that stupid sysadmin would be very glad, thanks to you.

Have a nice day
The Stupid Sysadmin

**Comment by zeroheure** [comment]
I know that it is documented in the FAQ, but it would help to put the instructions in the admin panel, so that the admin can readv it at least one time. May be something in `admin_password.txt`  could help too.

**Comment by the-djmaze** [comment]
RainLoop has a simple default password.
Problem is that everyone knows it and can use it for bad.

admin_password.txt is just a replacement to secure the first login attempt.
After that you should change the password through ?admin and the file is removed and never needed.

Did you forget your password?
Then edit the application.ini and remove the password.
Then do the admin_password.txt thing again.

There's nothing more to tell, just follow instructions.
