### ISSUE TITLE
update 2.28.0 crash my nextcloud 

### ISSUE THREAD

**Issue by draddy82** [the-djmaze/snappymail#1146]
hi, 
just try to update to version 2.28.0 on nextcloud 25.0.7 in Docker - with the update an error came up - nextcloud go to Maintenance mode ... 

tryed to  update with occ command and get this output
`Updating <snappymail> ...
An unhandled exception has been thrown:
Error: Undefined constant "SIGCLD" in /config/www/nextcloud/apps/snappymail/app/snappymail/v/2.28.0/app/libraries/MailSo/Log/Logger.php:78
Stack trace:
#0 /config/www/nextcloud/apps/snappymail/app/snappymail/v/2.28.0/app/libraries/MailSo/Log/Logger.php(78): constant()
#1 /config/www/nextcloud/apps/snappymail/app/snappymail/v/2.28.0/app/libraries/RainLoop/Api.php(64): MailSo\Log\Logger->__construct()
#2 /config/www/nextcloud/apps/snappymail/app/snappymail/v/2.28.0/app/libraries/RainLoop/Actions.php(120): RainLoop\Api::Logger()
#3 /config/www/nextcloud/apps/snappymail/app/snappymail/v/2.28.0/app/libraries/RainLoop/Api.php(12): RainLoop\Actions->__construct()
#4 /config/www/nextcloud/apps/snappymail/lib/Migration/InstallStep.php(72): RainLoop\Api::Actions()
#5 /config/www/nextcloud/lib/private/Repair.php(127): OCA\SnappyMail\Migration\InstallStep->run()
#6 /config/www/nextcloud/lib/private/legacy/OC_App.php(1068): OC\Repair->run()
#7 /config/www/nextcloud/lib/private/legacy/OC_App.php(1010): OC_App::executeRepairSteps()
#8 /config/www/nextcloud/lib/private/Updater.php(361): OC_App::updateApp()
#9 /config/www/nextcloud/lib/private/Updater.php(273): OC\Updater->doAppUpgrade()
#10 /config/www/nextcloud/lib/private/Updater.php(141): OC\Updater->doUpgrade()
#11 /config/www/nextcloud/core/Command/Upgrade.php(225): OC\Updater->upgrade()
#12 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#13 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#14 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#15 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#16 /config/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#17 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#18 /config/www/nextcloud/occ(11): require_once('...')
#19 {main}`

i just disabled snappymail via occ command and nextcloud will work - without snappy. 

pls check ;)

**Comment by warumwirleben** [comment]
Same here

PUSH

Please Update, SnappyMail is the one to blame, it deactivated itself and does not reactivate again.
SnappyMail is cool, please keep the good work going, this it the first time it doesn't work

**Comment by joergmschulz** [comment]
duplicate for https://github.com/the-djmaze/snappymail/issues/1147
