### ISSUE TITLE
Issues with Instagram email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1148]
![Instagram - SnappyMail](https://github.com/the-djmaze/snappymail/assets/6194332/f5735792-e37c-4ff3-965d-bae0bd3779f1)
![Instagram - Becky](https://github.com/the-djmaze/snappymail/assets/6194332/e7e4a683-725e-4931-9e8d-a1c51ae71137)
![Instagram - Becky - 2](https://github.com/the-djmaze/snappymail/assets/6194332/107d2bbc-db41-44b9-9b7a-46f3ed4e895a)
![Instagram - Becky - 3](https://github.com/the-djmaze/snappymail/assets/6194332/322c7cb5-fd02-43f6-9930-cf03e920532d)
[Instagram.eml.txt](https://github.com/the-djmaze/snappymail/files/11607634/Instagram.eml.txt)

**Comment by the-djmaze** [comment]
I will not fix this.
They are screwing around with element widt/height and max-width/max-height=0.
