### ISSUE TITLE
Support showing the sender's icon if they have one

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#115]
It would be nice if it showed the sender's icon if they have one (like how Rainloop does so).

**Comment by the-djmaze** [comment]
I've removed this feature because it relies on Gravatar.
It will not be back because many webmail users will not understand why 95% of their contacts has no image.

**Comment by ervee** [comment]
Could this be done by a plug-in though? Perhaps someone is willing to give plug-in making a try :)

**Comment by nomadturk** [comment]
I second this.

Either Gravatar should be there, even if it's optional.
Or you can bring BIMI support. Which might be better.

A lot of my contacts use that feature and missing a working feature is not ideal.

**Comment by the-djmaze** [comment]
About Gravatar: https://github.com/the-djmaze/snappymail/issues/164#issuecomment-981584370

I'm working on a redesign of the AddressBook system in branch https://github.com/the-djmaze/snappymail/tree/addressbook
When working, the sender icon would be better fitted in there.

**Comment by the-djmaze** [comment]
I've added a plugin named `avatars`.
It does Gravatar but it should be extended with BIMI, Contacts vCard.PHOTO, etc.

Currently just download and install manually.

**Comment by the-djmaze** [comment]
This last commit only works in next release.
And i have some trouble where to put avatar in messagelist (on the left).

![afbeelding](https://user-images.githubusercontent.com/3752035/203438021-92d84cdd-d37d-4cae-9393-44326cccf6e3.png)

**Comment by ervee** [comment]
I'm not sure but with older versions the ✅ was to the left of the avatar?

It would be nice when if you have the plugin enabled the UI would hide the check box and make the avatar clickable to select the emails. Perhaps flip the avatar around to reveal a checked box or otherwise visualize "checking" the line.
Without the plugin just leave the check box as it always was.

**Comment by the-djmaze** [comment]
I now have this:
![afbeelding](https://user-images.githubusercontent.com/3752035/203511364-273acdcb-8059-4efc-9891-020e680f827c.png)

**Comment by the-djmaze** [comment]
> I'm not sure but with older versions the white_check_mark was to the left of the avatar?

RainLoop didn't show avatar in MessageList
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/templates/Views/User/MailMessageListItem.html

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.22.0

**Comment by the-djmaze** [comment]
Added support for [identicons](https://wikipedia.org/wiki/Identicon). That makes the list a bit happier.
![afbeelding](https://user-images.githubusercontent.com/3752035/204510681-a8efb2fe-2482-4e9e-8fce-e8aaae2c7b97.png)

**Comment by ervee** [comment]
Works great! I did disable the "delay" option. Why is there this option?

**Comment by ervee** [comment]
Aaaaah! Sweet. My load is low so I just let'm rip.

**Comment by the-djmaze** [comment]
Or do you all prefer this kind of identicons?
![afbeelding](https://user-images.githubusercontent.com/3752035/204851682-f3a6cc6c-f362-4452-b6c5-7fc8c766da81.png)

**Comment by ervee** [comment]
Ooooh I do prefer that over the identicons. Perhaps a toggle option in the addon :)
