### ISSUE TITLE
Improve mobile breakpoints

### ISSUE THREAD

**Issue by hampoelz** [the-djmaze/snappymail#1150]
Currently there is a breakpoint at around 800px for the no split aka mobile layout, that's fine. But between ~1000px and ~800px the screen is too small for the vertically split layout, but still too big for no split. I'd suggest to add a new breakpoint at 1024px (= Nextcloud mobile breakpoint) or similar that toggles to the horizontally split layout, as it uses the space more efficiently in this case.

**Comment by the-djmaze** [comment]
There are two CSS classes in use:
* sm-msgView-side
* sm-msgView-bottom

Based on your setting it is one of these or none.
There is no way that it will switch between these by window size and that is good behavior.

Instead, the `@media screen and (max-width: @maxMobileWidth) {` might could be made more complex based on the two options.

**Comment by the-djmaze** [comment]
Maybe it depends on the device you use?

I can do this:
![image](https://github.com/the-djmaze/snappymail/assets/3752035/52d7f14e-e55a-429f-baaf-810e46e750ae)
![image](https://github.com/the-djmaze/snappymail/assets/3752035/5683d832-cf04-48a5-8db2-70c62398bbd2)

**Comment by hampoelz** [comment]
Mhh, you're right, it's definitely usable with the side panel collapsed. Probably it's just my personal preference to use a wider mail view in this case. _(And the fact that I totally forgot to collapse the side panel)_

But I would suggest that the side panel is automatically collapsed for a more seamless experience.

**Comment by the-djmaze** [comment]
For now i close this as i can't figure out a good solution for a problem regarding expand/collapse state when resizing.
I also wonder how often this issue occurs to put more time/effort into.
