### ISSUE TITLE
Bidi not supported in Squire editor

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1158]
Hello
As you mentioned in #630, would you please add the new version of CKEditor (CKEditor 5) to Snappymail?

The bidi buttons are needed for RTL based languages such as Persian, Hebrew and Arabic, but this is not supported in Squire editor.

I'm also trying to do this and if I succeed, I will send these changes as a PR.

**Comment by the-djmaze** [comment]
Good examples!
Will add something to Squire.
Would all option values be the best?

* ltr
* rtl
* auto
* (empty/undefine)

**Comment by rezaei92** [comment]
Sounds good, thank you.

When do you think this feature will be added to Squire?
What does empty/undefined option do? 
Is it used to write emails in plain text mode?

**Comment by the-djmaze** [comment]
I've made some changes and added to the demo.
Feel free if this is something you want.
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/e938f064-478c-47d5-b514-6d31a75c7f77)

**Comment by rezaei92** [comment]
I appreciate you taking the time to add this feature, but unfortunately, it is not functioning properly.

Hence, I sent the required changes as a PR #1200.
