### ISSUE TITLE
Request has been aborted.

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#1162]
**Describe the bug**
In Version 2.28.0 & 2.28.1 or later, the list of received e-mails is displayed after "Request aborted" is displayed at the first access.

**To Reproduce**
1. Log in to email account with SnappyMail

**Expected behavior**
The list of received e-mails is immediately displayed as in past versions.

**Comment by the-djmaze** [comment]
This behavior is now on purpose to find request errors.
Please read #1071
