### ISSUE TITLE
"⚠Cannot access the repository at the moment." when trying to update to 2.28.1

### ISSUE THREAD

**Issue by m-i-k-e-y** [the-djmaze/snappymail#1164]
**Describe the bug**
I'm using 2.28.0 and wanted to update to 2.28.1, but I when I start the update I get 
"⚠Cannot access the repository at the moment."

**To Reproduce**
1. Go to admin panel
2. Click on About
3. Click update

**Expected behavior**
Update should be executed.

**Screenshots**
![grafik](https://github.com/the-djmaze/snappymail/assets/29158512/6619eec8-834c-4255-9303-60cdbe99acfe)

**Please complete the following information:**
- Browser: Firefox 113.0.2 (64-Bit) on Windows 11
- IMAP daemon: dovecot 2.3.13 on a fully patched Debian Bullsey
- PHP version:
- SnappyMail Version: 2.28.0
- Mode: standalone (nginx 1.18.0/ php-fpm 7.4.33) on the same server as the IMAP daemon

**Comment by m-i-k-e-y** [comment]
Sorry, I wasn't able to check nginx previously. 

Just tried again and checked nginx logfile, but it does not contain much info:
`2023/06/10 11:40:06 [error] 95187#95187: *24646 FastCGI sent in stderr: "PHP message: Extract to /var/www/snappymail" while reading response header from upstream, client: 193.81.26.55, server: [redacted], request: "POST /?admin/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"`

**Comment by m-i-k-e-y** [comment]
@the-djmaze 
could you direct me to the file where to add the changes you made for logging?

**Comment by the-djmaze** [comment]
It's in the compiled `snappymail/v/N.N.N/static/js/admin.js` so javascript debug must be on in application.ini

**Comment by the-djmaze** [comment]
This could be related to #1075

**Comment by m-i-k-e-y** [comment]
> This could be related to #1075

I don't see any of the messages mentioned in #1075, neither in nginx logfile nor in php-fpm logfile.

DNS in general seems to be working (I'm using unbound):

> dig snappymail.eu ANY
>
>; <<>> DiG 9.16.37-Debian <<>> snappymail.eu ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30755
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1
>
>;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;snappymail.eu.                 IN      ANY
>
>;; ANSWER SECTION:
snappymail.eu.          58064   IN      A       84.22.110.35
snappymail.eu.          58064   IN      RRSIG   A 8 2 86400 20230622000000 20230601000000 26808 snappymail.eu. JmYCQcCjy7SMSDWdYnax0yrIO9nV1g0CcCQDGKG0vH6Fpy7M6CAm+jfF 6dh1oBiCznrc3uIoJGUCwDrRsLHFd7A4vJfMGQMP8iTE+qWTIuWsDRWl cMGTtUE1oPBCV+AxqWftscinm+J80Rg7nwIfWEh0NE5oxidw+GPwplRV nSc=
snappymail.eu.          58064   IN      AAAA    2a02:2770:15:0:21a:4aff:feff:f9b6
snappymail.eu.          58064   IN      RRSIG   AAAA 8 2 86400 20230622000000 20230601000000 26808 snappymail.eu. YV+fSOm1VAl8KpRWbIryR6Uh0Ib+Mn0qfTs+g9vqFbbhQE9l1z9P+Wmn 15HbndxjzQNC2D7Jw64VL33POJyliFUVHEH9xiGwVmpxqNkZI4Bxbn44 5hITRbrOlX04wnONvZso8ntw6aajon4xVCsWvA3BOOL33zA0NGx2ME9Z pr4=
snappymail.eu.          86387   IN      MX      0 snappymail.eu.
snappymail.eu.          86387   IN      RRSIG   MX 8 2 86400 20230622000000 20230601000000 26808 snappymail.eu. XLdt3k+WPhw+dZD+qK+99e8TkwAEr/z2h8fIJPnrDpw/6MTPPrPrjmDm 2ny7GQg86tpN3nNs9jc5DtWNoqlO0/tPuBGiIdzCWahkejFJ5mTBHJms qF/b8YaqX3fZpQeMC5jydDiTHHQjNIq5/12Rce1/SUstUgopCth1cDaf NlE=
>
>;; Query time: 27 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon Jun 12 13:48:05 CEST 2023
;; MSG SIZE  rcvd: 621

**Comment by m-i-k-e-y** [comment]
Hmm, I found now the in the developer console of Firefox:

![grafik](https://github.com/the-djmaze/snappymail/assets/29158512/cac1bbe2-8106-44d9-ba0e-b93c0ba81924)

either version 2.28.0 was downloaded instead of 2.28.1 of the update package is not built correctly? I'm just guessing here, so please bear with me.

**Comment by m-i-k-e-y** [comment]
I found now where the debug output is logged to - syslog. And there I see the same message:
`Jun 12 15:09:23 [redacted] snappymail: [2023-06-12 13:09:23.775][60e4f5b4] [NOTICE]: PharException: Extraction from phar "/var/www/snappymail/data/_data_/_default_/c76a3f92c359c759e55dbbfb6527ee48.tar.gz" failed: Cannot extract "snappymail/v/2.28.0/app/libraries/snappymail/dav/client.php" to "/var/www/snappymail/snappymail/v/2.28.0/app/libraries/snappymail/dav/client.php", path already exists in /var/www/snappymail/snappymail/v/2.28.0/app/libraries/snappymail/upgrade.php:208`
`Jun 12 15:09:23 [redacted] snappymail: Stack trace:`
`Jun 12 15:09:23 [redacted] snappymail: #0 /var/www/snappymail/snappymail/v/2.28.0/app/libraries/snappymail/upgrade.php(208): PharData->extractTo()`
`Jun 12 15:09:23 [redacted] snappymail: #1 /var/www/snappymail/snappymail/v/2.28.0/app/libraries/RainLoop/ActionsAdmin.php(316): SnappyMail\Upgrade::core()`
`Jun 12 15:09:23 [redacted] snappymail: #2 /var/www/snappymail/snappymail/v/2.28.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\ActionsAdmin->DoAdminUpgradeCore()`
`Jun 12 15:09:23 [redacted] snappymail: #3 /var/www/snappymail/snappymail/v/2.28.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()`
`Jun 12 15:09:23 [redacted] snappymail: #4 /var/www/snappymail/snappymail/v/2.28.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()`
`Jun 12 15:09:23 [redacted] snappymail: #5 /var/www/snappymail/snappymail/v/2.28.0/include.php(143): RainLoop\Service::Handle()`
`Jun 12 15:09:23 [redacted] snappymail: #6 /var/www/snappymail/index.php(11): include('/var/www/snappy...')`

**Comment by the-djmaze** [comment]
Fixed. It seems i've uploaded the wrong latest.tar.gz

**Comment by m-i-k-e-y** [comment]
Confirmed. I could update now. Thanks @the-djmaze

**Comment by jult** [comment]
This is back again..

**Comment by bitalicious** [comment]
…and again.

I guess it probably has something to do with the fact that snappymail.eu is down.

Am I right?
