### ISSUE TITLE
"Reply to same folder" user setting ignored?

### ISSUE THREAD

**Issue by xparq** [the-djmaze/snappymail#1170]
_(New user here, sorry if I'm misunderstanding sg.)_

**Description**

There's a `mail_reply_same_folder` admin setting, and a `Place replies in the folder of the message being replied to` user setting.
I guess the user setting (checked here, and saved as `"ReplySameFolder":true` in `storage/DOMAIN/USER/settings_local`) is supposed to override the global one (unchecked, and `Off` in `application.ini`), but it doesn't seem to.

I'm not sure if I'm just missing something obvious, but nonetheless, if I reply to messages in various folders, they all get placed in the Inbox.

**Env.:**
- Browser: Chrome 113
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.81.1
- Mode: standalone

**Comment by xparq** [comment]
Just checked: if I flip the admin setting to `On`, it works fine, the reply is placed along the original.

**Comment by the-djmaze** [comment]
`mail_reply_same_folder` is the default (when there no uses settings).
Else the `ReplySameFolder` value in `/_data_/_default_/storage/DOMAIN/USER/settings_local` is used.

After testing i could not reproduce your issue/observations

**Comment by xparq** [comment]
Thanks a lot for looking into it! I'll report here if I find out more.
