### ISSUE TITLE
Allow configuring multiple action links in the message pane, other than just Reply (to all)

### ISSUE THREAD

**Issue by xparq** [the-djmaze/snappymail#1171]
**Is your feature request related to a problem?**

Nope.

**Describe the solution you'd like**

There s a nice `Reply` arrow (shortcut link), kinda like a "toolbar button", near the top right corner of the message view pane.
There's also a user setting ("Default action") to change it's function to `Reply All` instead.

Similarly to other mail clients (e.g. Roundcube), this could be naturally extended to actually show both there, and also `Forward`, as quick action shortcuts, or possibly even more, according to user prefs. (That "empty space" there already offers itself as an ideal place for such a "toolbar".)

Then, replacing the current "Default action" setting, a multi-select list could be provided instead (labelled e.g. as "Quick actions", or "Toolbar actions", or "Action shortcuts" (albeit that would be somewhat confusing, -> e.g. #676), to choose which of the menu actions to display on that "toolbar".

**Describe alternatives you've considered**

The second best would be just having `Reply`, `Reply All`, and `Forward` (a very frequent use case for me) there, without any configuration whatsoever. While despite it might be a slight simplification to the implementation (I guess), it's still a bit of a functional/ergonomic improvement. (And that's also what Rc. offers in the version I currently have here.)

**Additional context**

Not sure how this would affect the existing themes. _(Again, I may just be missing something, and perhaps all this is already available somehow.)_

**Comment by the-djmaze** [comment]
SnappyMail tries to be "mobile first". So having many buttons at the top is not suitable.
That's why you see a burger menu with many options.
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/0eb32955-c1e1-4d20-a2f6-44e20c1e3c15)

On wide screens there is a menu bar at the top.
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/6ea41bdf-bfd1-4644-8889-fe820afb1666)
This is controlled by CSS
```css
@media screen and (max-width: 1400px) {
	html.sm-msgView-side #V-MailMessageView .top-toolbar {
		visibility: hidden;
	}
}
```

**Comment by xparq** [comment]
The mobile-first priority is a very welcome trait, indeed. Thanks for pointing out that the "void toolbar placeholder space" I mentioned may not actually be just "free space" (and e.g. it interferes with long `From:` fields).

However, mainly just FTR (in case of revisiting it in the future etc.), let me recap, why an _option_ to let users decide would still be advantageous:

- The `Reply` icon is already a natural exception (from just being one of the many actions), and duly elevated from the action menu.
- `Reply`, `Reply All` and `Forward` are in a different class of actions from most* others (and hence most others in the menu). Accordingly, `Reply All` is also already treated specially.
  \* _Not all, and the distinction is not clear-cut (albeit there's even a menu separator bar grouping them together, for a good reason), which is why it's recommended as an option only._
- Also according to the above: a) the other, top-level menu/tool bar is a poor alternative, as it contains different kinds of actions, so it's not a natural fit for these; b) that's why some clients offer shortcuts to them, grouped together (preferably even separated from the other actions, for better ergonomics, just like in the SM burger menu).
- Seeing the entirety of long "From:" fields by default is not a priority, given that a) most of it is always visible anyway, b) in the rare case of ambiguity it's very likely immediately identifiable from context (e.g. subject & body (pre)view etc.), and c) the overflow can be handled easily.

(Anyway, it's obviously just a small UX improvement, for a subset of users, so not pushing it; and it could also be extended/tweaked even further (e.g. merging/regrouping the "From: section" (with `Reply` + the burger menu) and the rest of the headers (with the `Tag` action` + labels), so it's kinda open-ended, too, overlapping with theme design etc.)
