### ISSUE TITLE
Search only retrieves from selected folder

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1172]
**Describe the bug**
I was thinking that using the search feature while in Inbox would search all of the available folders within the same account.  But it appears that you have to search each folder if you are not certain of the location of the email you are seeking.  Not sure if this is by design or something I'm doing, or not doing.

**Expected behavior**
It would be great to have the search while the Inbox is selected, to search all folders, or at least have an option in the advanced search to search all folders from the same account.

**Comment by the-djmaze** [comment]
Please read #154
