### ISSUE TITLE
ics file data not showing like other app do

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#1178]
**Describe the bug**
i send an invite and ics file come as an attachment but basic details like title, date and time and location etc are not showing.

**To Reproduce**
1. Go to thunderbird send an invite 
2. open snappy mail and check that invitation mail
3. The email body contains the links to the meeting, not the meeting details (time, day, etc...). The user has to check the attachments and put the meeting in the calendar, download as ZIP or save in his cloud space. The user cannot preview when the meeting takes place.

**Expected behavior**
The email body should show meeting details to enable the user to have a preview of the time.

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by Zero3K** [comment]
Does it show up properly in any other webmail clients?

**Comment by the-djmaze** [comment]
> 3\. The email body contains the links to the meeting, not the meeting details (time, day, etc...). The user has to check the attachments and put the meeting in the calendar, download as ZIP or save in his cloud space. The user cannot preview when the meeting takes place.

Correct. SnappyMail does not instantly download attachments from IMAP server.

You can write a plugin that does what you want.
For example take a look at the Nextcloud plugin `cfg.CalDAV` code at https://github.com/the-djmaze/snappymail/blob/master/plugins/nextcloud/js/message.js

**Comment by Logic-Bits** [comment]
This would be a really cool feature!

**Comment by Luncheon3462** [comment]
I would also love to have this available in snappy for nextcloud.   I don't write code, but am willing to support financially @the-djmaze
