### ISSUE TITLE
Writing plugin for Squire editor

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1192]
I'm developing a plugin to add a new font to the Squire editor, but I am unable to select the Squire font tags using the querySelector() function and return null. 

In general, it seems impossible to write a plugin for Squire, possibly due to a lack of available hooks in the base code.

![image](https://github.com/the-djmaze/snappymail/assets/93854988/909e1d00-0f91-412e-a6fb-01d9b9116545)

**Comment by the-djmaze** [comment]
Correct, there is no event yet in https://github.com/the-djmaze/snappymail/blob/master/dev/External/SquireUI.js

Could add one for it.
