### ISSUE TITLE
Search function not working correctly

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1198]
**Describe the bug**
I'm searching for an email address (From field) and as soon as the email address exceeds a given number of letters (my first assumption was it has to do with the numbers inside but I don't think that's the case) the search does not return any results.

**To Reproduce**
I have four emails in my inbox from the following senders
- testmail-without-number@sweetgood.de
- testmail-with-1-number@sweetgood.de
- testmail-with-number-at-end1@sweetgood.de
- 1testmail-with-number-at-beginning@sweetgood.de

Searching for `from=testmail-with` returns all four emails – thats correct ✅
![image](https://github.com/the-djmaze/snappymail/assets/43847817/9525d450-db30-441c-9c69-9eb51907ae36)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/6e312a6e-f857-4a9f-9a81-57ac75e35ed2)

---

Searching for `from=testmail-with-number` again returns all four emails – that's only correct if the `-` is being ignored 🤔
![image](https://github.com/the-djmaze/snappymail/assets/43847817/018c7061-6000-4511-b7bd-cb5bb5a60bb9)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/d6493446-512f-44b0-8b68-7490e85870fe)

---

Searching for `from=testmail-with-number-at` does not return any results – but it should. 🚫 The json request shows 85 emails as result but the collection is empty 🤔
![image](https://github.com/the-djmaze/snappymail/assets/43847817/39a4eb56-d31f-484b-a3bb-dcbffbfe148c)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/419eb8b2-c744-45f6-be79-6d37472bf49c)

---

Same behaviour if I just search for `testmail with number` (20 letters)
![image](https://github.com/the-djmaze/snappymail/assets/43847817/8fe0610b-a602-425e-843e-03c7a86a89dc)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/fc495090-ef04-4a4f-bf3f-7252bec3c267)

---

Same behaviour if I just search for `testmail with number at` (23 letters)
![image](https://github.com/the-djmaze/snappymail/assets/43847817/9faa71d5-48f1-4312-9c21-925293766295)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/76d2b120-b89c-45dc-a82b-77ea523b0a1f)

**Expected behavior**
see above

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: mailcow
- PHP version: 8.1
- SnappyMail Version: 2.28.3
- Mode: standalone

**Comment by codiflow** [comment]
I first came across this bug because of the following behaviour (this unfortunately does not confirm my "limited number of letter assumption"):

Searching for `from=-kwb-svm-deb@sweetgood.de` works (30 characters):
![image](https://github.com/the-djmaze/snappymail/assets/43847817/552f3008-1837-47c6-8b9e-891619b24e34)

![img-2023-07-01-19-01-55](https://github.com/the-djmaze/snappymail/assets/43847817/32727904-753f-4087-9513-19040a85cf7a)

Searching for `from=1-kwb-svm-deb@sweetgood.de` does **not** work (31 characters):
![image](https://github.com/the-djmaze/snappymail/assets/43847817/c908be02-25e1-4145-ba15-4018c2829c4b)

![image](https://github.com/the-djmaze/snappymail/assets/43847817/0bd4e490-eb51-44b5-957e-415276835975)

**Comment by the-djmaze** [comment]
We need more info about your setup as it works perfectly on my Dovecot in the SnappyMail demo

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/8f68aa66-b824-4a74-b5a0-ecf6815550af)

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/aa219bf1-fd07-4af1-9baf-0d320f89436f)

**Comment by codiflow** [comment]
Hm that's interesting.

I'm using the most recent version of **mailcow-dockerized** (2023-05a).

This includes the docker image [mailcow/dovecot:1.24](https://hub.docker.com/layers/mailcow/dovecot/1.24/images/sha256-9cca8bc552b02c06ac9d972d3683c3029ca4ddada884fefac12c93400fc77dce?context=explore) which uses **Dovecot 2.3.20**

Any more information that I can provide to help finding the issue?

**Comment by the-djmaze** [comment]
Did you enable/setup Solr for IMAP searches?

**Comment by codiflow** [comment]
Not actively. Where could I see if it is used / configured?

The following containers are running:

![grafik](https://github.com/the-djmaze/snappymail/assets/43847817/d0d26cce-087f-4d90-8bca-8b5ab23de68b)

**Comment by codiflow** [comment]
I will try a reindex (as SOLR seems to be in use automatically, yes) and report back.

**Comment by the-djmaze** [comment]
You could also disable this in the Dovecot conf.

Remove `fts_solr` from `mail_plugins` setting.
Also check for something like:
```
plugin {
  fts = solr
  fts_solr = url=https://solr.example.org:8983/solr/dovecot/
}
```

**Comment by codiflow** [comment]
I reindexed all mailboxes on the server and will monitor the situation. I will reopen this ticket if the issue persists.

Thanks for this hint 👍️
