### ISSUE TITLE
Error 500 while trying to fetch the attached thumbnails and pictures

### ISSUE THREAD

**Issue by Factor7771** [the-djmaze/snappymail#1201]
When I open the message that contains attached pictures, the thumbs are not appearing and in the Chrome developers tools I can see error 500 while trying to fetch the data. The same goes with opening the picture - new tab is opened and there's an error 500.

**To Reproduce**
1. Open message that contains an attachment with the picture
2. Try to view the thumbnail
3. Try to open the picture

**Expected behavior**
The thumbnail should generate without any issue and should be displayed in the GUI. After opening the picture, it should be opened in current tab using the lightbox.

- Browser: Chrome/114.0.0.0
- IMAP daemon: dovecot
- PHP version: 7.4 - 8.2
- SnappyMail Version: 2.28.3
- Mode: standalone

The following extensions are installed on the shared server:
![image](https://github.com/the-djmaze/snappymail/assets/32823084/a7088567-3759-4666-b1c7-e88a42548a9a)

I can't debug because after turning the debugging on, the following text appears:

Warning: spl_autoload(): open_basedir restriction in effect. File(mailso/base/utils.php) is not within the allowed path(s): (/usr/home/user/domains/<redacted.domain>/public_html:/tmp:/usr/share:/usr/local/share:/dev:/tmp:/usr/share:/usr/local/share:/dev:/usr/local/share/pear) in /usr/home/user/domains/<redacted.domain>/public_html/snappymail/v/2.28.3/app/libraries/MailSo/Log/Logger.php on line 200

I've tried to simply comment out the line 200 in Logger.php... After doing that, I can only see a white screen with no content at all (there's only response 200).

Is Gmagick required by SnappyMail? I saw the issue #1009 and I've already checked time zone.

**Comment by the-djmaze** [comment]
The problem is an incorrect open_basedir.
Fix that and try again.

**Comment by Factor7771** [comment]
But the file mailso/base/utils.php is in open_basedir directory under /usr/home/user/domains/<redacted.domain>/public_html,
I even tried to enter "mailso/base/utils.php" but that also doesn't work.

I previously had Rainloop installed, and I had not any issue enabling logging or/and debugging (with the same open_basedir configuration etc. I moved Rainloop to temporary directory and unpacked SnappyMail in the public_html)

**Comment by the-djmaze** [comment]
```
spl_autoload(): open_basedir restriction in effect.
File(mailso/base/utils.php) is not within the allowed path(s):
- /usr/home/user/domains/<redacted.domain>/public_html
- /tmp
- /usr/share
- /usr/local/share
- /dev
- /tmp
- /usr/share
- /usr/local/share
- /dev
- /usr/local/share/pear
```

You need to understand how `spl_autoload` works.
Therefore run the following script as `public_html/test.php`:
```php
<?php
echo getcwd();
print_r(explode(PATH_SEPARATOR, get_include_path()));
```
Each path shown must match open_basedir

**Comment by the-djmaze** [comment]
> I've tried to simply comment out the line 200 in Logger.php... After doing that, I can only see a white screen with no content at all (there's only response 200).

200 should not. But did you enable debug mode completely and analyzed the log?

**Comment by Factor7771** [comment]
Output 1:


/usr/home/user/domains/<redacted_domain>/public_htmlArray
 (
[0] => .
[1] => /usr/local/share/pear
  )


Output 2:


Array
(
[0] => .
[1] =>
[2] =>
)


Output 3:


/usr/home/user/domains/<redacted_domain>/public_html/snappymail/v/2.28.3/app/libraries/MailSo/Base/Utils.php<br>




That's the problem, there's no file that I could analyze, nothing is being written by the Logger and the debug mode works the same - I'm only getting a blank page.
I've checked the nginx logs, but there are no issues whatsoever.

I'm really confused about the open_basedir. It should work okay according to the output from the commands you provided? The server's running on FreeBSD 13.0-RELEASE-p12, but I don't really think that it would cause issues with open_basedir.

**Comment by the-djmaze** [comment]
The autoload resolves to `/usr/home/user/domains/<redacted_domain>/public_html/snappymail/v/2.28.3/app/libraries/MailSo/Base/Utils.php` so that indicates the setup is correct.


> There's no file that I could analyze, nothing is being written by the Logger and the debug mode works the same

Strange, there must be a log, something is wrong on your server.

**Comment by tinola** [comment]
Strange...
The thumbnail is not generated, while after click image is shown correctly.
There is come mysterious notice in log file:

> improper image header `/tmp/magick-qdUmdisj4qO3oa_zTr3w4u_Bj3QFxkzy' @ error/png.c/ReadPNGImage/3964

Full log below:

[log.txt](https://github.com/the-djmaze/snappymail/files/11966517/log.txt)

**Comment by the-djmaze** [comment]
`improper image header` is caused when the first 8 bytes of the PNG is incorrect.
Download the image and check the first 8 bytes with a hex editor (or upload here so i can check).

The correct value should be `89 50 4E 47 0D 0A 1A 0A`

**Comment by tinola** [comment]
It has got that value...

![obraz](https://github.com/the-djmaze/snappymail/assets/3160125/5e352e6b-fa7b-4d62-acd5-c3fbc365897f)

Here's example PNG

![godlo](https://github.com/the-djmaze/snappymail/assets/3160125/a9de5070-e00f-4cad-b39f-70461ad91d60)

**Comment by the-djmaze** [comment]
Wow, that makes it weird.
There's a function that does things.
https://github.com/the-djmaze/snappymail/blob/76e82ba159489322e48b320d87b5ae65d0c736fc/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Raw.php#L263-L270

To debug you could modify the imagick code at
https://github.com/the-djmaze/snappymail/blob/76e82ba159489322e48b320d87b5ae65d0c736fc/snappymail/v/0.0.0/app/libraries/snappymail/image/imagick.php#L29-L37
Into the following:
```php
	public static function createFromStream($fp)
	{
		$imagick = new static();
		$data = \stream_get_contents($fp);
		\file_put_contents(APP_PRIVATE_DATA.'cache/image-'.\md5($data).'.png', $data);
		return static::createFromString($data);
	}

```

This should save the raw images at `_data_/_default_/cache/`

**Comment by tinola** [comment]
Thanks @the-djmaze :)

So there's a light in a tunnel...

Before change (original imagick.php)

![before](https://github.com/the-djmaze/snappymail/assets/3160125/4cbc9af0-c89f-452c-881d-10928866d1b4)

After change imagick.php and refreshing web page:

![after](https://github.com/the-djmaze/snappymail/assets/3160125/2b79a7e6-fa55-456e-a7b4-851e5105c92d)

Also, attached image was successfully saved at `_data_/_default_/cache/`

**Comment by the-djmaze** [comment]
So it seems `$imagick->readImageFile` has a bug.
I will use the change (without the `file_put_contents`) to circumvent it.

**Comment by tinola** [comment]
Thanks, this workaround works just fine 🖐️
