### ISSUE TITLE
Can't display some messages

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1209]
Recently I've been facing the issue that SnappyMail can't display some messages. Following is an example of such ones.

https://lists.freebsd.org/archives/dev-commits-ports-all/2023-July/072697.txt

If I crick such message, then it is displayed in message area in a instant but "Unknown error" is displayed as following.

<img width="1529" alt="SnappyMail mail unknow-error" src="https://github.com/the-djmaze/snappymail/assets/5249848/95e8b749-28b4-401a-ab4b-fa764299a616">

I have following two instances of SnappyMail.

1. FreeBSD 13.2-RELEASE amd64, PHP 8.2.8, Apache 2.4.57, SnappyMail 2.28.4
2. Debian 11.7 amd64, PHP 7.4.33, Apache 2.4.56, SnappyMail 2.28.4

And if I try to dispaly the message in question on the same IMAP server. The issue happens with instance 1 but not with instance 2.
So it may be related to PHP version.

**Comment by yasuhirokimura** [comment]
I use Avatars plugin and the issue disappears if I disable it.
As I wrote above I have instance with PHP 7.4. And the issued doesn't happen even if I enable Avatars plugin on it.
So the source may be combination of PHP 8.2 and Avatars plugin.

**Comment by bziman** [comment]
I'm having the same issue after updating my server to Ubuntu 22.04.3 LTS - which updated PHP from 7.x to 8.1.2. (All SnappyMail extensions are disabled.)

**Comment by bziman** [comment]
After enabling logging, I found the culprit:

`Error: Class "DOMDocument" not found in .../snappymail/v/2.11.0/app/libraries/MailSo/Base/HtmlUtils.php:97`

Turns out, the system update ate the xml-dom package. I was able to resolve the issue by (re?)installing that:

`apt-get install php-dom`

**Comment by the-djmaze** [comment]
And on Centos / Fedora / Red Hat:

yum install php-xml

**Comment by yasuhirokimura** [comment]
1. The system in question is FreeBSD.
2. Both php82-dom and php82-xml are installed in it.
3. As I previsouly wrote, the issue happens only if Avatars plugin is installed and enabled.
3. I enabled logging but no error message is written when the problem happens.

So I think my case is different from yours.

**Comment by the-djmaze** [comment]
With PHP 8.2.1 i have no issues.
Could it be related to enabled BIMI or Gravatar setting?

**Comment by yasuhirokimura** [comment]
Before facing the issue I used Avaters plugin with following setttings.

1. Identicon: Name characters else silhouette
2. Enable "Preload valid domain icons"
3. Enable "Delay lookup"
4. Enable "BIMI"
5. Enable "Gravatar"

So I disabled 4 and 5. Then the problem disappears.

**Comment by yasuhirokimura** [comment]
Though I'm not sure if it is releated, I found odd behavior of Avaters plugin while investigating the issue.

As I wrote above, currently I use Avaters plugin with following setttings.

1. Identicon: Name characters else silhouette
2. Enable "Preload valid domain icons"
3. Enable "Delay lookup"
4. Disable "BIMI"
5. Disable "Gravatar"

And with this settings avater is displayed if I open messages that come from `amazon.com`, `github.com`, `google.com`, etc.

It doesn't happen if I disable "Delay lookup".

Is it expected behavior?

**Comment by the-djmaze** [comment]
> So the source may be combination of PHP 8.2 and Avatars plugin.

I think i fixed it for next release.
There was a problem with the `json.after-*` hooks. The `$aResponse` array wasn't recursive as the result wasn't converted to json yet.

**Comment by the-djmaze** [comment]
Any luck with v2.31.0?
