### ISSUE TITLE
Themes with hyphens fail to load background image specified in styles.css

### ISSUE THREAD

**Issue by randolf** [the-djmaze/snappymail#1210]
**Describe the bug**
When creating a customized Theme, if the name of the theme (which is the name of the directory) includes a hyphen (e.g., "Theme-Test"), the background image specified in styles.css doesn't load.

**To Reproduce**
1. Path:  snappymail/v/2.28.4/themes
2. Copy "Default" directory to "Theme-Test"
3. Set as default theme in application.ini:  theme = "Theme-Test"
4. Reload web page

**Expected behavior**
Background image should appear, but it doesn't.  (Changing the hyphen to an underscore {e.g., "Theme_Test"} resolves the problem, but this should only be regarded as a temporary measure.)

**Please complete the following information:**
- Browser:  Current versions of Opera, Chrome, and Firefox
- IMAP daemon:  N/A
- PHP version:  7.4.33
- SnappyMail Version:  2.28.4
- Mode:  standalone (extracted from archive; manual installation with Apache HTTPd v2.4)

**Additional context**
Hyphens are valid characters in filenames, and in internet domain names.

**Comment by the-djmaze** [comment]
Tested and works for me
