### ISSUE TITLE
Timeout when downloading IMAP4 folders with more than 30,000 messages

### ISSUE THREAD

**Issue by randolf** [the-djmaze/snappymail#1211]
**Describe the bug**
When a user tries to access a folder with more than 30,000 messages, after approximately 1 minute they are presented with a "Timeout" error message in large red text where the list of messages is expected to appear.  (RainLoop doesn't exhibit this behaviour, so this is a show-stopper at the moment, but I'm hoping it can be resolved soon.)

**Expected behavior**
List of first 100 messages should appear in less than 1 second.

**Please complete the following information:**
- Browser:  Current versions of Firefox, Opera, and Chrome all exhibit the same behaviour
- IMAP daemon:  Dovecot v2.3.4.1 (64-bit) on Debian (Linux)
- PHP version:  7.4.3.3 (64-bit) on Debian (Linux)
- SnappyMail Version:  2.28.4
- Mode:  standalone (manual installation)

**Additional context**
Mail server is a separate machine.  Traffic is going over Gigabit Ethernet on a private subnet (10.1.1/8), without encryption, which is a physically separate network that's not part of any public-facing IP addresses and networks.  (This means that SnappyMail is accessing IMAP4 over a Gigabit Ethernet link.  RainLoop is too, and is not having this problem.)

Thanks!

**Comment by randolf** [comment]
This problem seems to have cleared itself up.  I hope it doesn't come back.

**Comment by eeuak** [comment]
We also experience this issue altough only when clicking the folder the very first time. Second click on the folder and the contents are shown. So it is surely a loading timeout, the sync itself doesnt seem to run into a timeout.

**Comment by eeuak** [comment]
Is this already a known issue? Anyone has an idea for a fix?

**Comment by the-djmaze** [comment]
Also read #1071

**Comment by the-djmaze** [comment]
Please read https://github.com/the-djmaze/snappymail/wiki/Improve-performance
