### ISSUE TITLE
Sending replies always fails, but sending new messages works properly

### ISSUE THREAD

**Issue by randolf** [the-djmaze/snappymail#1213]
**Describe the bug**
When users try to reply to an eMail message, they get an error message when they click on the "Send" button.  However, when users create a new message (that is not a reply), the message is sent as expected when they click on the "Send" button.

**To Reproduce**
1. Select an eMail message to reply to
2. Click on the Reply button (near the top-right corner)
3. Type some text (compose your reply)
4. Click on the "Send" button

**Expected behavior**
Message is sent and the user is immediately returned to the message/folder view (the user might see a reply or a mailer-daemon report later in their Inbox, but they won't see any error message on their screen).

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/33541170/c50268f1-417b-41c4-b618-6e15638d7688)

**Please complete the following information:**
- Browser:  Current versions of Chrome, Firefox, and Opera all exhibit the same behaviour
- SMTP daemon:  Postfix v3.4.14 (64-bit) on Debian (Linux)
- PHP version:  7.4.33 (64-bit) on Debian (Linux)
- SnappyMail Version:  2.28.4
- Mode:  standalone (manual installation)

**Additional context**
Upgraded from RainLoop.  Overall feedback from users is very positive, and they like some of the new features (searching and sorting, in particular; spam rating in message view, etc.).  If I can't get this problem resolved, I'll have to go back to RainLoop for the time being, and I really don't want to do that because of the security problems that RainLoop has.

**Comment by randolf** [comment]
Resolved by setting the following in `default.json` to:

`SMTP -> UseAuth -> True`

Where can I find documentation about these settings?  Thanks.

**Comment by the-djmaze** [comment]
> Where can I find documentation about these settings? Thanks.

More info can be found at https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#smtp-settings
