### ISSUE TITLE
Issue with certain type of Amazon messages

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1216]
![Amazon - SnappyMail (#2)](https://github.com/the-djmaze/snappymail/assets/6194332/e7adde2b-5a72-4bc5-901a-7da4d9f9d292)
![Amazon - mboxview (#2)](https://github.com/the-djmaze/snappymail/assets/6194332/0a3a3810-5ec4-4f6d-b4ab-1b1e61a175ca)
[Delivery update- Your Amazon package.eml.txt](https://github.com/the-djmaze/snappymail/files/12064836/Delivery.update-.Your.Amazon.package.eml.txt)

**Comment by the-djmaze** [comment]
`bgcolor="ffa723"` is invalid, it should be `bgcolor="#ffa723"`

**Comment by Zero3K** [comment]
Can it be fixed on your end?

**Comment by the-djmaze** [comment]
That would mean we have to check every color option for `^[0-9A-F]{6}$`.

**Comment by Zero3K** [comment]
Why was this marked as completed?
