### ISSUE TITLE
MIME type issue after upgrading, unable to load page

### ISSUE THREAD

**Issue by loganess** [the-djmaze/snappymail#1217]
**Describe the bug**
Hello,

I am getting MIME type issue after trying to upgrade to latest version v2.28.4
How could i fix it?
Thank you.

**To Reproduce**
From admin panel, upgrade to latest version 2.28.4

**Screenshots**
as attached.

![Screenshot 2023-07-18 at 10 14 25 AM](https://github.com/the-djmaze/snappymail/assets/116762656/e5334364-ba72-4ad9-ba02-b7192b12b367)

**Comment by the-djmaze** [comment]
Remove `snappymail/v/2.28.4/static/.htaccess` and try again

**Comment by loganess** [comment]
perfect thanks for your help.
