### ISSUE TITLE
ModSecurity blocks attachment upload on MULTIPART_UNMATCHED_BOUNDARY rule

### ISSUE THREAD

**Issue by captbrando** [the-djmaze/snappymail#1218]
**Describe the bug**
SnappyMail is incorrectly handling the upload of attachments for users with stock ModSecurity installs.

**To Reproduce**
1. run Snappymail on an Apache2 server with ModSecurity enabled.
2. New Message
3. Add someone in the To field
4. Click add attachments, and select file.
5. Attachment text turns red after 100% and ModSecurity logs this (sanitized): 

`[Wed Jul 19 11:52:34.563856 2023] [security2:error] [pid 1284062] [client 1.2.3.4:23232] [client 1.2.3.4] ModSecurity: Access denied with code 403 (phase 2). Match of "eq 0" against "MULTIPART_UNMATCHED_BOUNDARY" required. [file "/etc/modsecurity/modsecurity.conf"] [line "87"] [id "200004"] [msg "Multipart parser detected a possible unmatched boundary."] [hostname "www.example.com"] [uri "/mail/"] [unique_id "XXXXXXXXXX"]`

**Expected behavior**
Attachment should upload successfully.

**Screenshots**
Attachment below on what Snappymail looks like. Here's the config from ModSecurity (Debian bookworm): 
`# Did we see anything that might be a boundary?
#
SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" \
"id:'200004',phase:2,t:none,log,deny,msg:'Multipart parser detected a possible unmatched boundary.'"`

![image](https://github.com/the-djmaze/snappymail/assets/1310378/05f401aa-0ca9-44a7-9944-30f3637d86e2)

**Please complete the following information:**
- Browser: Chrome latest (115?)
- IMAP daemon: dovecot
- PHP version: 8.2
- SnappyMail Version: 2.28.4
- Mode: standalone

**Comment by the-djmaze** [comment]
It seems that ModSecurity has a wrong configuration that produces the false positives.

**Comment by captbrando** [comment]
It was working fine prior to the upgrade, which makes it sound like one of two things needs to happen:

1. Snappymail needs a separate configuration to get this to work. If you can craft that config, I can pop it in and see if it works.
2. Snappymail needs a patch to perform attachment upload activities in a way that ModSecurity thinks is OK out of the box.

**Comment by captbrando** [comment]
Confirmed that test.pdf did work. Very strange. I wonder if even spaces in file names trip it up.
