### ISSUE TITLE
decrypt and verify pgp emails 

### ISSUE THREAD

**Issue by idunwannagotoschool** [the-djmaze/snappymail#1223]
**SnappyMail version, browser, browser version:**

SnappyMail version 2.28.4

Browser: Brave 1.56.11 (chromium 115.0.5790.102), iOS Safari

**Expected behavior and actual behavior:**

Expected behaviour: The message will have "lock" or "cert" icon in inbox. There will be boxes with buttons labelled "decrypt" and "verify" to click. The message will then be decrypted and the signature will be verified.

Actual behaviour: The message have "lock" or "cert" icon in inbox. There are no buttons. Instead, the messages are shown as attachments. However, the emails can be decrypted and verified with thunderbird.

**Steps to reproduce the problem:**

Send an encrypted and signed email to own email address. Try decrypt it and verify the signature.

**Logs or screenshots:**

![image](https://github.com/the-djmaze/snappymail/assets/104383966/828a33bd-afbb-410c-a367-d0779492132c)
![image](https://github.com/the-djmaze/snappymail/assets/104383966/b1a9901b-425f-4455-a51b-5737546c04fe)

**Comment by the-djmaze** [comment]
How does the source of the email look like?
It should be something like:

```
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted";
 boundary="121066cf-c74b-4305-a086-919a940a8d29-1"

--121066cf-c74b-4305-a086-919a940a8d29-1
Content-Type: application/pgp-encrypted
Content-Disposition: attachment
Content-Transfer-Encoding: 7Bit

Version: 1
--121066cf-c74b-4305-a086-919a940a8d29-1
Content-Type: application/octet-stream
Content-Disposition: inline; filename="msg.asc"
Content-Transfer-Encoding: 7Bit

-----BEGIN PGP MESSAGE-----
```

**Comment by idunwannagotoschool** [comment]
Sorry, I have moved to another client.
