### ISSUE TITLE
Subfolders for archiving mails

### ISSUE THREAD

**Issue by Popyllol** [the-djmaze/snappymail#1231]
Hi Snappymail-Team!

**Is your feature request related to a problem? Please describe.**
I haven't found a way to set subfolders for mail archiving so maybe there is no way so far.

**Describe the solution you'd like**
What I would love to get is a possibility to configure archiving in a yearly or maybe even monthly base.
Like:
- Archive
-- 2000
-- 2001
-- 2002
...
or
- Archive
-- 2000
+- 01
+- 02
...
+- 12
-- 2001
...
So if I click on archive a mail from january 2000 is moved to
- Archive
-- 2000
+- 01
and a mail from june 2023 is moved to
- Archive
-- 2023
+- 06
and so on.
**Describe alternatives you've considered**

**Additional context**
Thank you for considering this.
Greetings,
   Lars

**Comment by johnnyq** [comment]
That would be great, and archive wizard would be neat to have as well. When clicked it will rummage through all emails and archive all your existing mail that does not match todays year

**Comment by the-djmaze** [comment]
And how should it work?

Because when a message is from december 31 2022 and a reply is on january 2 2023.
And when you archive both they are not connected anymore as thread.
