### ISSUE TITLE
nextclud after install

### ISSUE THREAD

**Issue by HalloWelt42** [the-djmaze/snappymail#1235]
Serververbindung kann nicht hergestellt werden
Server-Nachricht: Can't connect to host "tcp://localhost:143"

Server Webhosting 8000 SE netcup

**Comment by Biernot74** [comment]
Same error.
Raspberry Pi, Nextcloudpi Image 1.52.4, Nextcloud 27.0.1.2, Snappymail 2.28.4

**Comment by newbie7800** [comment]
I have exactly the same problem.  Has anyone found a solution.  Domains are set up correctly in the admin panel.

**Comment by the-djmaze** [comment]
Please configure the IMAP domains properly.
Read 
https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#menu-domains
