### ISSUE TITLE
Possible Security Issue Snappymail 2.28.4 on Nextcloud 26.0.5

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1236]
I am the administrator on an instance of nextcloud 26.0.5 with snappymail 2.28.4 and want to report a possible security flaw.   

As the admin user, I have configured snappymail to use two email accounts, A and B.  Account A is on the same domain as the nextcloud instance,   Account B is on an entirely different domain.  

Non-admin users, who have separate credentials for the nextcloud instance, are able to access both account A and account B, when the should only be able to access Account A. 

It seems snappymail allows non-admin users to access the email accounts of admin users

**Comment by the-djmaze** [comment]
I've seen the e-mail you send Saturday.
While investigating i see no problem with SnappyMail.

SnappyMail requires IMAP login and if Account A knows the credentials of Account B they can access the mail of Account B.

**Comment by Luncheon3462** [comment]
I don't think you understood, my apologies.   Account A is the admin, Account B is non-admin user.   Account B should not know or have access to Account A's credentials.   When your nextcloud app is NOT installed, everything functions properly.   Account B cannot access anything related to Account A.   When your nextcloud app is installed, Account B (non-admin) can access the email accounts of Account A (admin).   Please reopen issue.

**Comment by Luncheon3462** [comment]
Not using the impresonate plugin.  Appreciate your quick response.

Account A (admin) and Account B (non-admin) both have access to the same email address on the same domain as the nextcloud installation.  That is by design.

I used the "add account" feature of snappymail to add a second email address for Account A (admin).   When I log into nextcloud as Account B (non-admin), that second email address can be used to read or send,.

**Comment by the-djmaze** [comment]
Correct!

SnappyMail login is the email address.
So when Account A and Account B login as `shared@domain.tld` then every additional email account is tied to `shared@domain.tld`.

Instead, you should login with personal accounts like `account-a@domain.tld` and `account-b@domain.tld` and make `shared@domain.tld` an additional email account.

**Comment by Luncheon3462** [comment]
Merci.   

Is there a link where I can donate to your efforts?

**Comment by the-djmaze** [comment]
> Is there a link where I can donate to your efforts?

Currently only https://www.paypal.me/thedjmaze
