### ISSUE TITLE
Delete parent folder issues

### ISSUE THREAD

**Issue by the-djmaze** [the-djmaze/snappymail#124]
**Describe the bug**
@Alphix re-enabled deletion of parent folders #121

However, i forgot to document why it was disabled.
Deletion works but since the parent is now "NonExistent", The demo Dovecot IMAP server does NOT report that nor \Noselect.

**To Reproduce**
1. Go to https://snappymail.eu/demo/
2. Login
3. Go to https://snappymail.eu/demo/#/settings/folders
4. Create folder
5. Create sub-folder
6. Delete the parent folder
7. Exit settings
8. In left pane click the parent folder you just deleted
9. Error: Can't get message list

**Expected behavior**
Dovecot report deleted folder as \NonExistent (RFC5258) OR \Noselect (RFC3501)

**Quirck**
When you rename the deleted folder, it magically does have the \Noselect flag.

**Comment by Alphix** [comment]
Yeah, I've noticed that. Could be a bug in `Dovecot`. I've reported it to the [Dovecot mailing list](https://dovecot.org/pipermail/dovecot/2021-August/122881.html). But I'm not sure it's something that needs to be worked around ATM?

**Comment by the-djmaze** [comment]
Could be an issue with `dovecot.list.index`.
Because when i delete that file, the problem is gone

**Comment by Alphix** [comment]
And at one point simply restarting `Dovecot` seems to have helped though not reproducibly so. Dunno, right now I'll just wait and see if there's a reply on the ML.
