### ISSUE TITLE
addAjaxHook function for custom SnappyMail plugin

### ISSUE THREAD

**Issue by CamZie** [the-djmaze/snappymail#1242]
We are experiencing issues with some of our custom plugins, while trying to migrate our Rainloop webmail to SnappyMail.

In one of our plugins, we are using the  "addAjaxHook" function, which seems to have been removed from the AbstractPlugin. What can we replace this function with?

Many thanks in advance.

**Comment by the-djmaze** [comment]
Since the communication is JSON, the function name is `addJsonHook`.
AJAX is for XML (but people misuse it for JSON) 😉

**Comment by CamZie** [comment]
> Since the communication is JSON, the function name is `addJsonHook`. AJAX is for XML (but people misuse it for JSON) 😉
> 
> Also, use the following for reference: https://github.com/the-djmaze/snappymail/tree/master/plugins#readme

We have used the function `addJsonHook` and we confirm that it works. Thanks a lot!
