### ISSUE TITLE
No CSS on my login screen

### ISSUE THREAD

**Issue by BSDNix** [the-djmaze/snappymail#1246]
**Describe the bug**

I freshly installed this on my OpenBSD 7.3 -current machine, it *works*, but its all plain html and no CSS? 

**To Reproduce**
1. Go to the link
2. Tadaaa

**Expected behavior**
CSS also working and an actual screen to login to..

**Please complete the following information:**
- Browser: Opera GX + chrome
- IMAP daemon: Dovecot
- PHP version: PHP8.2
- SnappyMail Version: Latest
- Mode: Standalone

**Comment by BSDNix** [comment]
If you want to see for yourself: https://webmail.swedishrally.se/

**Comment by the-djmaze** [comment]
Remove `snappymail/v/0.0.0/static/.htaccess` and see what happens.

**Comment by the-djmaze** [comment]
With v2.30.0+ you can now run `/?/Test` to find the problem
