### ISSUE TITLE
snappymail not working any more

### ISSUE THREAD

**Issue by Fraleu** [the-djmaze/snappymail#1256]
using cyberpanel version 2.3.4
Using directly https://92.243.26.99:8090/snappymail/index.php or via Cyberpanel menu , I got same error HTTP 500 # Impossible to manage this request 92.243.26.99
![image](https://github.com/the-djmaze/snappymail/assets/119486565/cd3cdb9f-cc0f-4671-8507-76aea68d6902)

**Comment by the-djmaze** [comment]
Check your apache logs for 500 errors

**Comment by Fraleu** [comment]
Hi the djmaze,
thanks for your message
It semeans i didn't have any Apache services installed on this server ...
=> apache2ctl -v
Command 'apache2ctl' not found,

**Comment by the-djmaze** [comment]
Oh but you use Nginx then, or something else?

**Comment by Fraleu** [comment]
using cyberpanel version 2.3.4

**Comment by the-djmaze** [comment]
Because i have no idea which http cyberpanel uses.
Could be OpenLiteSpeed (for example).
But you know best as you configured it.

**Comment by Fraleu** [comment]
Hi the djmaze,
I finaly get check on plate forme and i have Nginx install but seams not working fine.
So i re-install Nginx but see below 
sudo systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-10-05 07:29:23 UTC; 6h ago
       Docs: man:nginx(8)
    Process: 4850 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 4851 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
   Main PID: 4940 (nginx)
      Tasks: 2 (limit: 2300)
     Memory: 2.7M
        CPU: 84ms
     CGroup: /system.slice/nginx.service
             ├─4940 "nginx: master process /usr/sbin/nginx -g daemon on; master_process on;"
             └─4943 "nginx: worker process" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

**Comment by Fraleu** [comment]
but i still get 
Oct 05 07:29:23 mail systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 05 07:29:23 mail systemd[1]: Started A high performance web server and a reverse proxy server.
l:~$ sudo ufw status
Status: inactive
