### ISSUE TITLE
Message doesn't disappear from Inbox folder after `Delete` icon is clicked.

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1262]
# To Reproduce

0. Assumes some messages are listed in message list area of Inbox.
1. Click one of them -> The message is displayed.
2. Click `Delete` icon.

# Expected behavior

Message list of Inbox is dispalyed again and the message disappears from the list.

# What really happens

Message list of Inbox is dispalyed again but the message still stays in the list.

# Environment

## Client

* 64bit Google Chrome 117.0.5938.132 on Windows 11 22H2
* Microsoft Edge 117.0.2045.4 on Windows 11 22H2
* 64bit Mozilla Firefox 118.0.1 on Windows 11 22H2.

### Instance 1

* FreeBSD 13.2-RELEASE amd64
* Dovecot 2.3.21
* PHP 8.2.11
* SnappyMail 2.29.1

### Instantce 2

* Debian 11.7 amd64
* Dovecot 2.3.13
* PHP 7.4.33
* SnappyMail 2.29.1

**Comment by AlwinAntreich** [comment]
I can chime in. Same versions, but integrated into nextcloud (27.1.1).

The dev tools show below action when deleted through the inbox view. But nothing when you want to use the delete (trash can) button or the "Delete" and "Delete permanently" menu items.

```
Action:  "MessageMove"
```

**Comment by nothingelseavailable** [comment]
Can confirm the issue on my Nextcloud instance. Using MacOS Sonoma 14.0 (23A344) and Chrome Version 117.0.5938.149 (Offizieller Build) (arm64)

**Comment by ruliane** [comment]
Hi,

Same happens when clicking "Archive", or "Junk"/"Not junk" buttons. I can't see no error, neither server-side (Apache2) nor client-side.

(Tested with Edge version 117 or Firefox 118.)

**Comment by ivnmad** [comment]
+1

I can also confirm this is the case [standalone installation on Apache2, not Nextcloud]

**Comment by Hk1020** [comment]
I can confirm this on iPad ios 16.7 with Safari. Didn’t happen with snm 2.28.4.

**Comment by the-djmaze** [comment]
See #1274
