### ISSUE TITLE
v2.29.1 Bug "Add to Calendar"

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1267]
Just updated to v2.29.1 on Nextcloud.   Previously when receiving an email with a .ics file I was able to click on the gear icon, then choose "add to calendar" and then a window would appear showing each of my Nextcloud calendars and I could choose which calendar to add the .ics calendar invite to.   It worked like a charm.

Since 2.29.1, the window that pops up seems truncated, shorter and it doesn't show any of the calendars to add the .ics file to.   

I've tried different desktop OSs and browsers and also iOS.  Same result.  

See screenshots in links.

![Screenshot 2023-10-03 at 1 41 59 PM](https://github.com/the-djmaze/snappymail/assets/140646544/f23dc6c3-87ef-4bed-a360-4b0a0b68a782)

![Screenshot 2023-10-03 at 1 41 48 PM](https://github.com/the-djmaze/snappymail/assets/140646544/3d9f83ee-4c0c-41c3-9249-6289aa977704)

**Comment by Luncheon3462** [comment]
Could the merge for "Improve UX of "Put in Calendar" option in nextcloud plugin #1259" have broken this functionality?

**Comment by Luncheon3462** [comment]
v2.28.4 works properly if that helps.

**Comment by the-djmaze** [comment]
Yes, that could be it when it works with:
https://snappymail.eu/repository/v2/plugins/nextcloud-2.23.tgz

I will see what i can do when i have some time.
For now i need to attent a funeral and some other things.

But i will also think about extension version selector so that you can use a previous when it fails 😉

**Comment by the-djmaze** [comment]
Read #1266
