### ISSUE TITLE
Thank you for quick turn around.   The Nextcloud version with the bug was 2.29.1.   Above you mention you released 2.25 with the fix.

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1268]
Thank you for quick turn around.   The Nextcloud version with the bug was 2.29.1.   Above you mention you released 2.25 with the fix.

I'm not a coder, but will Nextcloud know that 2.25 is more recent than 2.29.1?

@the-djmaze @theronakpatel

_Originally posted by @Luncheon3462 in https://github.com/the-djmaze/snappymail/issues/1266#issuecomment-1747730688_

**Comment by the-djmaze** [comment]
SnappyMail v2.29.1 will use extension ` nextcloud 2.5`

Check in your SnappyMail ?admin area

**Comment by theronakpatel** [comment]
@the-djmaze I see that you've launched the Nextcloud extension at this link: https://snappymail.eu/repository/v2/plugins/nextcloud-2.25.tgz. However, it doesn't seem to have automatic updates. How can we address this issue? Do we need to manually deploy the Nextcloud extension?

**Comment by the-djmaze** [comment]
Read https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#menu-extensions-plugins
