### ISSUE TITLE
Filters "sieve" are activated in all users

### ISSUE THREAD

**Issue by mikeleblank** [the-djmaze/snappymail#1269]
Hi , I create a filter script in a user account and it is activated for all of them, even from different domains.

It is normal?

I use cyberpanel and make this configuration

https://community.cyberpanel.net/t/filtering-spam-in-rainloop-autoreply-and-email-filters-with-sieve/30637

**Comment by the-djmaze** [comment]
> It is normal?

To check: 
1. Open the root of your server (SFTP or SSH)
2. Go to your mail storage
3. Find the sieve scripts

For example i use this:
```
djmaze:~> ssh root@snappymail
Last login: Mon Oct  2 14:44:35 2023
[root@snappymail ~]# locate .sieve
/home/snappymail/mail/dovecot.sieve
/home/snappymail/mail/sieve/USER.sieve
/home/snappymail/mail/sieve/kmail.sieve
/home/snappymail/mail/sieve/rainloop.user.raw.sieve
/home/snappymail/mail/sieve/rainloop.user.sieve
```

Then you can find out what is going on

**Comment by mikeleblank** [comment]
[root@MYSERVER /home] # locate .sieve
/home/vmail/dovecot.sieve
/home/vmail/sieve/SPAM-TEST.sieve
/home/vmail/sieve/rainloop.user.sieve

**Comment by the-djmaze** [comment]
Just what i thought. Somehow your configuration has a fault.
Sieve should be configured per user.
