### ISSUE TITLE
Nextcloud toolbar does not work anymore

### ISSUE THREAD

**Issue by stepcellwolf** [the-djmaze/snappymail#1272]
**Describe the bug**

None of the buttons are anymore working on the email toolbar. Please see screenshot. No Action after clicking.

**To Reproduce**
1. Select and open an email from the left sidebar, and click one of the above toolbars.
2. Delete button, no action

**Expected behavior**
After clicking the delete button, the email should be no longer in the inbox.
If you click on the right toolbar above the email list inbox, it is working as expected.

**Screenshots**
<img width="281" alt="image" src="https://github.com/the-djmaze/snappymail/assets/6190816/fc2ec8b1-441e-48bb-a6bd-5d3503d3fe9d">

Mode: 
- Browser: firefox 118.0.1
- PHP version: PHP 8.1.23
- SnappyMail Version: 2.29.1
- Nextcloud 27.0.2

**Comment by the-djmaze** [comment]
Same as #1274 ?
