### ISSUE TITLE
Snappymail doesn't remember credentials

### ISSUE THREAD

**Issue by eibex** [the-djmaze/snappymail#1275]
**Describe the bug**
I am getting logged out of Snappymail multiple times a day since updating from 2.28.x to 2.29.1 even though I selected remember credentials and set auto-logout to never.

**To Reproduce**
1. Login
2. Close browser
3. Go to snappymail
4. See that you are not logged in

**Expected behavior**
If the account is set to never log out and has remember credentials selected, I shouldn't have to re-enter my them.

**Please complete the following information:**
- Browser: Firefox 118.0.1
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.1-fpm
- SnappyMail Version: 2.29.1
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
No client-side errors

**Additional context**
Maybe related to the old #126 issue

**Comment by franconianmetal** [comment]
Same behaviour with v2.29.1
confirmed

**Comment by eibex** [comment]
I'm not using nextcloud

**Comment by chodid** [comment]
> v2.29.1 needed to re-enter password in nextcloud's "additional setting" works again for me, both after closing browser and logout

@franconianmetal where did you have to re-enter the password? In the admin-panel? I have the same issue WITH Snappymail & Nextcloud and can't quite follow your solution

**Comment by franconianmetal** [comment]
Yes, re-entered in admin panel as done for initial setup and configuration

**Comment by chodid** [comment]
> Yes, re-entered in admin panel as done for initial setup and configuration

I'm sorry but I seem to be stuck in my thinking somewhere when trying to follow your suggestion. 
The issue is appearing on a per-user basis when opening SnappyMail. Plus, the only password-related option in the admin panel I can see is the password-change option for the admin panel itself.

**Comment by relikd** [comment]
I have the opposite problem. I cannot remove the credentials. If I enter invalid credentials, the login will fail. But if I remove the credentials altogether, it will restore the credentials from before.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/blob/e7d7ca48e42368f629448de50ece7acb257a4cac/dev/Stores/User/Settings.js#L65-L74

This logout code is executed every time on touchstart, mousemove or keydown.
But not more then every 5 seconds.
The code clears the logout timer en restarts when automatic logout is set and the "remember me" is off.

However, when i fully close my "private browsing" browser i am logged out because the cookies are removed.

You can investigate the issue with your browser developer tools.

**Comment by eibex** [comment]
Reported as fixed in duplicate issues
