### ISSUE TITLE
UI Bugginess in general

### ISSUE THREAD

**Issue by Disco1** [the-djmaze/snappymail#1287]
**Describe the bug**
There are several bugs in the UI (Using Nextcloud Snappymail, version is up to date).

For example:
- Click on a message to read it
- Click Deleete
- Returns to home screen, but doesn't delete the message

Another example:
- Click the checkbox next to a message on the home screen
- Click Mark as Unread
- Click the checkbox again (to deselect it)
- Rather than deselecting it, it opens the message

**To Reproduce**
See above

**Expected behavior**
See above

**Screenshots**

**Please complete the following information:**
- Browser: Brave
- IMAP daemon: not sure
- PHP version: PHP 7.4.33
- SnappyMail Version: Don't know where to find it, but Nextcloud shows that the app is up to date, so latest
- Mode: [e.g. standalone, nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Correct, read #1274
