### ISSUE TITLE
Disable "Mark message as read after", offer manual toggle

### ISSUE THREAD

**Issue by chri2** [the-djmaze/snappymail#1289]
# Problem

My workflow is that I have a bunch of folders all containing a lot of mails. They are used as an archive as well. If a message is unread in a folder it is something I know I need to attend to. If I'm done with the task (answering, looking at a git for updates, issues, etc.) I actively mark the message as read.

This is possible using the **great snappymail** and I'm generally very happy how it works!

But from my perspective there would be room for a huge improvement.

# Proposed solution

## Workaround

I set the timer for "Mark message as read after" to 10000 seconds and usually no message is marked as read automatically. That's fine. 

But marking a message manually as read still is a pain: I have to navigate the menu to select the function.

## Solution

In the settings page offer a checkbox to disable marking messages as read. 

Checking the checkbox would obviously disable the timer for marking a message as read.

But also it should make an additional button appear that allows to mark the actual message as read either in the message view pane and/or above the message list.

Define a hotkey for toggling the messages status between read and unread (thunderbird uses _m_).

## illustration

![mark_read_unread](https://github.com/the-djmaze/snappymail/assets/15866990/c5f086f9-87f5-40c9-8b17-431b0aaf746b)

The _open letter symbol_ is just a placeholder for the final icon if this feature would be added.

I guess the icon should show the envelope opening in motion - something like the famous icon to send an email of which is symbolized by three horizontal lines beside the envelope.

**Comment by the-djmaze** [comment]
> Define a hotkey for toggling the messages status between read and unread (thunderbird uses _m_).

SnappyMail uses `Q` to mark as read and `U` to mark as unread.


More buttons on the bar is an issue for mobile view / narrow screens.
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/39f1cdcb-a9b1-4ee7-9ac1-180fc41b6dee)
