### ISSUE TITLE
Clicking item in messages list doesn't show clicked message if any item in the list is already selected.

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1290]
# To Reproduce

1. Select folder that includes some messages and display messages list.
<img width="1531" alt="SnappyMail 20231020 1" src="https://github.com/the-djmaze/snappymail/assets/5249848/c753ae71-1b59-48bb-9af2-ac28b11bddef">

2. Select item in the list by checking the box icon. (You may select 1 to all items as it doesn't matter how many items are selected.)
<img width="1531" alt="SnappyMail 20231020 2" src="https://github.com/the-djmaze/snappymail/assets/5249848/74ddc0e4-62c8-4b7f-aa43-73cbad3268ac">

3. Click item in the list. (It doesn't matter if clicked item is selected one or not.)

# Expected behavior

Message that corresponds to clicked item is displayed.

# What really happens

Nothing happens. Message isn't displayed at all.

# Environment

## Browser

* Google Chrome 118.0.5993.89 on Windows
* Microsoft Edge 118.0.5993.89 on Windows
* Mozilla Firefox 118.0.2 on Windows
* Google Chrome 117.0.5938.153 on Android
* Microsoft Edge 117.0.2045.65 on Android
* Mozilla Firefox 118.2.0 on Android

## Server 1

* FreeBSD 13.2-RELEASE amd64
* Dovecot 2.3.21
* Apache HTTP server 2.4.57
* PHP 8.2.11
* SnappyMail 2.29.1

## Server 2

* Debian 11.8 amd64
* Dovecot 2.3.13
* Apache HTTP server 2.4.56
* PHP 7.4.33
* SnappyMail 2.29.1

**Comment by the-djmaze** [comment]
Correct. This behavior has changed.
When you are selecting messages and accidentally click/touch outside the checkbox, your selection is lost.
Now this problem does not happen anymore.
