### ISSUE TITLE
Nextcloud integration should use language as defined in cloud settings

### ISSUE THREAD

**Issue by akhil1508** [the-djmaze/snappymail#1293]
**Is your feature request related to a problem? Please describe.**
- There is a separate language setting in snappymail when I use it inside a nextcloud setup
- This does not make sense to have two separate language settings when I want it to "integrate" with my cloud

**Describe the solution you'd like**
- Use language setting from cloud
- If the cloud language is not available in snappymail, fall back to "en"

**Additional context**
![image](https://github.com/the-djmaze/snappymail/assets/14362579/69500ff0-0e94-45ea-ae92-d8ce237a1336)
![image](https://github.com/the-djmaze/snappymail/assets/14362579/0928d715-f296-4f40-97a2-4857c33546c0)

**Comment by the-djmaze** [comment]
It is now here:
https://github.com/the-djmaze/snappymail/blob/ddc953f4fad60bded880275b4ad25143f01203d4/plugins/nextcloud/index.php#L248-L257
