### ISSUE TITLE
Suggestion to improve the viewing of MMS messages that are received via email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1294]
If the body of a message is blank and there is a single text file that is attached, SnappyMail should display the attachment inline.

**Comment by Zero3K** [comment]
Any thoughts on this request?

**Comment by the-djmaze** [comment]
Depends on the content-type of the attachment

**Comment by Zero3K** [comment]
image/jpeg, etc. and text/plain are the content types.

**Comment by the-djmaze** [comment]
image/jpeg is not valid SMS text.

For example they are:
* application/vnd.3gpp.sms
* application/vnd.wap.mms-message
* text/plain

So the question is: how are they in your mail source?

**Comment by Zero3K** [comment]
Its Apple's iMessage service.

**Comment by the-djmaze** [comment]
You have an example EML file?

**Comment by Zero3K** [comment]
[MMS Emails.zip](https://github.com/the-djmaze/snappymail/files/14182570/MMS.Emails.zip)

**Comment by Zero3K** [comment]
Why not show the image attachment in the email body viewer?

**Comment by the-djmaze** [comment]
Because that needs a lot more code and not really suited for SnappyMail

**Comment by Zero3K** [comment]
Okay.
