### ISSUE TITLE
Issue when using the enter key in a reply window 

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1296]
Using the enter key in a reply window, to start a new line has a strange behavior: sometimes it works, sometimes it jumps one extra lines, sometimes 2, and sometimes even it puts the cursor somewhere inside the signature.
Is has been verified with Firefox and Brave, within 2 different Nextcloud instances.

We use Snappy 2.29.1 within Nextcloud 27.1.2

Thanks in advance for your help !

**Comment by andreasdirscherl** [comment]
+1 
Exactly the same for me.

**Comment by the-djmaze** [comment]
Maybe related to #1339 where Squire added a `<div><br></div>` everywhere.
So check when v2.30 is released

**Comment by the-djmaze** [comment]
Please test my changes at https://snappymail.eu/demo/

**Comment by mmallejac** [comment]
Looking great !
I've done multiple replay test, I couldn't see any problem
I've switched to the Nextcloud25+ just to be sure, and I was using the same
Firefox.
👍

**Comment by andreasdirscherl** [comment]
I can confirm that the behavior persists in version 2.30.
Aldo did a test run on the demo account, and here all seems to work perfectly. Like Michel had already said. Fingers crossed!

Are we sure that is not something weird that Nextcloud introduces for snappymail? Similar to not being able update snappymail through Nextcloud admin?
I'm on the latest Nextcloud version btw - Nextcloud Hub 6 (27.1.4)

At any rate, thanks @the-djmaze for all the hard work!

**Comment by the-djmaze** [comment]
It is Firefox.
Around Firefox 77 the cursor was gone and they fixed that.
But now Firefox has trouble when we set the Range and Selection in JavaScript.
Firefox reverts to the old Range selection.

It must be something in Squire and currently the demo skips the code that handles the `Enter` key.

**Comment by mmallejac** [comment]
Yes, many thanks
Are you aware of some kind of Firefox fix for this ?

Le mar. 5 déc. 2023 à 13:33, Andreas Dirscherl ***@***.***> a
écrit :

**Comment by the-djmaze** [comment]
Firefox bug:
> if you set the Selection Range in the text node after the new line, it draws the cursor before the line break.

Squire:
> Set the this._recordUndoState(range) which creates a hidden bookmark `<input>`
But this fails due to `inUndoState == true`

Workaround: force a _docWasChanged()

Real solution: TODO = find out why _docWasChanged() is not triggered at all

**Comment by mmallejac** [comment]
Unfortunately, I still have some issues here :-\
