### ISSUE TITLE
Edit Script / Filters window does not have a vertical scrollbar (Mac+ios Safari)

### ISSUE THREAD

**Issue by apezio** [the-djmaze/snappymail#1297]
This only happens in Safari Desktop and Mobile.  Opera for example has a scrollbar and the buttons are not covered up.  Also, I have a relatively old version of macOS and Safari, so maybe it's not an issue with the latest versions.

**Describe the bug**
The Edit Script / Filters window does not have a vertical scrollbar and therefore the "Add Filter" and "Save" buttons are off of the viewable area and not able to be used.

This problem occurs depending on screen resolution and the number of saved filters.  Once a certain number of filters are created they push the buttons at the bottom of the page off the viewable area.

My workaround has been to use my web browsers "Zoom Out" function as many times as needed until the buttons are viewable again. When done editing my Filters I "Zoom In" or do a "View -> Actual Size" to get back to a usable text size.

First picture shows "normal" sized text and no way to access the buttons at the bottom.  The second picture (bottom) shows a shrunked page where I can access the buttons (still no scrollbar).

**To Reproduce**
Add as many filters as needed until they push the buttons off the viewable / usable area.

**Expected behavior**
I would expect there to be a scrollbar in the window so the buttons are accessible when having more than ~15 or 20 rules.

Safari 14.1.2, macOS 10.14.6 (.
Safari ?, iOS 15.2.1.

Latest Snappymail 2.29.1 - git clone from 10/29/2023

<img width="738" alt="Screen Shot 2023-10-31 at 11 37 32 AM" src="https://github.com/the-djmaze/snappymail/assets/8996860/fe80e91e-c4f7-470c-8069-2455641ef085">
<img width="365" alt="Screen Shot 2023-10-31 at 11 39 20 AM" src="https://github.com/the-djmaze/snappymail/assets/8996860/0ab92aac-228f-480c-b2b0-cd526cf68608">

**Comment by apezio** [comment]
Also happening in iOS 16.7.2

**Comment by the-djmaze** [comment]
All dialogs have the following rule:
```css
	max-height: calc(100vh - var(--smDialogShrink));
	max-height: calc(100dvh - var(--smDialogShrink));
```

Why it fails in Safari i have no idea, but will test when i have my mac mini up and running again.

**Comment by the-djmaze** [comment]
I can't seem to reproduce this issue, as i can just "scroll" (touch or mouse) through the list.
