### ISSUE TITLE
Some toolbar and mail actions not working since update to v2.29.1

### ISSUE THREAD

**Issue by BlueDotShortcuts** [the-djmaze/snappymail#1299]
**Describe the bug**
Some of the mail actions in the menu (when viewing an email) and also on the toolbar do not seem to work anymore.
When viewing an email the button to delete or archive both do not seem to do anything except return you to the mailbox view (with the message still in the folder).
This occurs whether you use the button on the toolbar at the top of the screen or if you click the hamburger icon and then select delete or archive. If you click delete permanently you are prompted to confirm but when you click yes the same behaviour occurs and the message is not changed.
This has occurred in Safari, Chrome and Firefox on both macOS and iOS and has only been noticed on the mail server since the update to 2.29.1.

**To Reproduce**
TOOLBAR ISSUE
1. Open an email from message view.
2. Click on button in toolbar to either delete or archive the email.
3. You are returned to mailbox view without the message being affected.

MENU ISSUE
1. Open an email from message view.
2. Click on hamburger icon to show message options.
3. Click menu option to either delete, delete permanently or archive the email.
4. You are returned to mailbox view without the message being affected.

**Expected behavior**
Selecting an option to manage an email message that is being viewed should result in that action completing successfully and message being moved to the relevant folder/removed from the current folder.

**Screenshots**
<img width="467" alt="Screenshot 2023-11-03 at 12 38 06" src="https://github.com/the-djmaze/snappymail/assets/81866410/a18040bf-361b-4828-80e6-3784231233e5">
<img width="224" alt="Screenshot 2023-11-03 at 12 40 02" src="https://github.com/the-djmaze/snappymail/assets/81866410/1934b8a3-6ec0-4500-a1ff-4dd16db7bd3e">

**Please complete the following information:**
- Browser: iOS Safari, Chrome + macOS Firefox 118.0.1, Chrome 118.0.5993.117, Safari 17.1
- IMAP daemon: Dovecot
- PHP version: 8.1.2
- SnappyMail Version: 2.29.1
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Attempting to gather further logs, though nothing appears in Chrome or Safari developer console as an error and there is no reported errors in Apache error.log.

**Additional context**
Have not tested all buttons, so possible others may have issues.
Can delete or archive messages from the message list itself.
Some other actions on the toolbar such as moving to the next/previous message seem to work fine.
Some other actions in the hamburger menu such as reply, etc... seem to also work fine.

**Comment by apezio** [comment]
Is this the same as https://github.com/the-djmaze/snappymail/issues/1281 ?

If so it has been fixed in https://github.com/the-djmaze/snappymail/issues/1274

**Comment by BlueDotShortcuts** [comment]
Apologies for not noticing the exisiting history before re-reporting.
Thank you for getting back to me, I will just use the old version and hold tight for the update with the fix at some point.
