### ISSUE TITLE
[Squire] Identities editor bugs

### ISSUE THREAD

**Issue by ss-smk** [the-djmaze/snappymail#1300]
**Describe the bug**
In Settings - Accounts - Identities there is an HTML editor for customizing the signature of messages. 
- First, switching font don't work properly. Even some text marked, after switching font, it isn't switch font really. 
- Changing font color doesn't work at all
- If i paste text in another font, editor begin to work like keyboard "Insert" pressed, and doesn't allow to make newlines.
- Italic blocks to make newlines.
(

**To Reproduce**
1. Go to 'Settings - Accounts - Identities'
2. Click on 'current or new Identity'
3. Switch to HTML editor
4. Try to enter some text and switch to Times font or set any text color. 
4.1 Try to enter another text, make it Italic and press Enter (make newline)

**Expected behavior**
HTML editor must colorize text, always make newlines correctly, and switch fonts

**Screenshots**
It can't be explained with screenshots

**Please complete the following information:**
- Browser: Firefox 119, Chromium 118.0.5993
- IMAP daemon:  dovecot
- PHP version: 8.1.16
- SnappyMail Version: 2.29.1
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
No logs.

**Additional context**

**Comment by the-djmaze** [comment]
v2.31 has many changes in the Squire wysiwyg editor.
Kan you test if it is solved?

**Comment by ss-smk** [comment]
Hi. 
It still doesn't work correctly. 
For example, add new Identity, switch to HTML editor, enter some text, then make it bold or italic - newline (Enter) - become not working.

**Comment by the-djmaze** [comment]
I close this in favor of #1389 which contains more details about current progress
