### ISSUE TITLE
Blank email displayed when "Prefer HTML to plain text" is unchecked and the message is html only

### ISSUE THREAD

**Issue by apezio** [the-djmaze/snappymail#1302]
When "Prefer HTML to plain text" is unchecked, and the message being viewed is HTML only, no message is displayed.

I would expect there to be logic that would show the HTML message if there is no plain text.

To reproduce:

Uncheck "Prefer HTML to plain text" in Settings.
Go to any mailbox and view an html-only message.  it will be blank.
The "View HTML Message" option on the hamburger dropdown will correctly show the message.

NOTE:

Once "View HTML Message" option is selected - upon returning to plain text view there is a stripped down version of the HTML message displayed.

Latest git source.
Dovecot
Safari, Opera, Google Chrome.
standalone mode.

**Comment by apezio** [comment]
Screenshot 1: Message first viewed (prefer plaintext over html option enabled in Settings).
![screenshot1](https://github.com/the-djmaze/snappymail/assets/8996860/e6a43dd2-68c0-4e26-bd55-0184ad803760)

Screenshot 2: "View HTML Message"
![screenshot2](https://github.com/the-djmaze/snappymail/assets/8996860/4f822443-2e91-40ce-8d16-e41638cd4313)

Screenshot 3: "View plain text Message"
![screenshot3](https://github.com/the-djmaze/snappymail/assets/8996860/83ddf2f9-ed04-4deb-91a0-dc0e3d31263d)

**Comment by the-djmaze** [comment]
When you look at the source of the email, you will notice that there is an empty `Content-Type: text/plain` part in there.

This means the sender screwed up the sending of their emails.
You should report to them.

**Comment by apezio** [comment]
Nope. I checked 10 emails with this issue (about 1/4 of the email I receive has this issue) and none have `Content-Type: text/plain`.

I do see this error in Safari's JavaScript Console:

`[Refused to execute a script because its hash or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy](https://stackoverflow.com/questions/73440491/refused-to-execute-a-script-because-its-hash-or-unsafe-inline-does-not-appear)`

Maybe they are related?

**Comment by apezio** [comment]
Happens in Safari 14.1.2 and Opera 97.0.4719.63.  I don't feel like it's a Browser thing.

in class bodyText there are 5 different text-part plain's, 4 are hidden an one is shown.

The hidden ones seems to be the bodies of other emails, while this one is for the current email:

`<div id="rl-msg-0ae22688dee4e88e49646957b8bf67f1" class="b-text-part plain"></div>`

**Comment by apezio** [comment]
This happens with every HTML-only email, unfortunately it's not the sender(s) email format. :)

**Comment by the-djmaze** [comment]
To properly understand the issue, we need to investigate the source of the emails.

For example, here's a multipart with html and plain:
```
Content-Type: multipart/alternative; 
	boundary="----=_Part_113431976_1099401662.1699967195390"

------=_Part_113431976_1099401662.1699967195390
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hey=20
there,


------=_Part_113431976_1099401662.1699967195390
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

For example, here's an html only:
```
Content-Type: text/html; charset="UTF-8"

<html dir=3D"ltr" lang=3D"en">=0A=0A  <head>=0A    <meta http-equiv=3D"Cont=
```

SnappyMail should show these properly and have a toggle button.
If the body of the converted html to plain is empty, we need to figure out why your browser fails.

**Comment by apezio** [comment]
Once I select "view as plain text" in the hamburger menu, the converted message shows.

But before that, the body is blank.  (When Prefer Plain text is set in settings)

I will upload a few email sources if you want to see.

[emails.zip](https://github.com/the-djmaze/snappymail/files/13355418/emails.zip)

**Comment by apezio** [comment]
Tried Chrome 110.0.5481.100.  Same issue.

**Comment by apezio** [comment]
Thanks, that fixed it!
