### ISSUE TITLE
Show size of folders in folders list

### ISSUE THREAD

**Issue by corvus-albus** [the-djmaze/snappymail#1303]
**Is your feature request related to a problem? Please describe.**
Cannot easily investigate, which email is eating up my space. It would be very nice to get an idea where to look after huge emails.

**Describe the solution you'd like**
It would be great if the folder size is displayed along to the folder list (https://.../apps/snappymail/#/settings/folders).

**Comment by corvus-albus** [comment]
Perhaps it helps. There is a roundcube plugin with a very similar function: https://github.com/jfcherng-roundcube/plugin-show-folder-size .

**Comment by the-djmaze** [comment]
The code was already partially there for IMAP4rev2 :wink:

**Comment by corvus-albus** [comment]
Thank you for the last hint. I checked it for our installation, Status size is allowed. If mbox-quota is set, Ican observe the percentage at the openening page.
Nevertheless I can't see any folder size information. Is there another setting needed or do you have to set limits for foldersize?
![grafik](https://github.com/the-djmaze/snappymail/assets/26668681/b7edeac3-15ea-4f65-9d18-6635f366efb8)

**Comment by corvus-albus** [comment]
Ahhh, shame on me. There is a german phrase which says: Who can read, is clearly in advantage. 
Displaying of foldersize is really working and I it was my fault to misunderstand your screenshot. It is clearly written: DISABLE Capabilities. If "status size" is checked, it is obviously disabled!
And finally I understood and the foldersize is displayed. 
So please forget about my last comment.

Thanks again for your fast reaction to this issue!
