### ISSUE TITLE
"Remember Me" does not work in Nextcloud iframe mode

### ISSUE THREAD

**Issue by SergeyMosin** [the-djmaze/snappymail#1306]
**Describe the bug**
In Nextcloud  (iframe mode) `Remember Me` does not work after the browser is closed and re-opened.

**To Reproduce**
Admin: 
1. Make sure the `Users will login manually, or define ....` and `Don't fully integrate in Nextcloud, use in iframe` options are set

User (start as logged out):
1. Go to SnappyMail login page
2. Check the `Remember Me` checkbox
3. Enter credentials and login
4. Close browser
5. Open browser
6. Go to SnappyMail, users expect to be logged in because the `Remember Me` was set
7. 💥 You are logged out (back at the login page)

**Expected behavior**
Users should be logged in after Step `6` above 

**Please complete the following information:**
- SnappyMail v2.29.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
INFO]: Time delta: 1.3408050537109
log-2023-11-08.txt-[2023-11-08 12:33:08.004][691a235f] [INFO]: [SM:0.0.0][IP:172.19.0.1][PID:1449][Apache/2.4.56 (Debian)][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET http://localhost:8080/apps/snappymail/]
log-2023-11-08.txt:[2023-11-08 12:33:08.004][691a235f] smremember[NOTICE]: decrypt
log-2023-11-08.txt-[2023-11-08 12:33:08.005][691a235f] COOKIE[DEBUG]: set smctoken
log-2023-11-08.txt-[2023-11-08 12:33:08.005][691a235f] Crypt[WARNING]: Decrypt() invalid $data or $key
log-2023-11-08.txt:[2023-11-08 12:33:08.005][691a235f] smremember[NOTICE]: invalid
log-2023-11-08.txt-[2023-11-08 12:33:08.005][691a235f] PLUGIN[INFO]: Hook: main.content-security-policy
log-2023-11-08.txt-[2023-11-08 12:33:08.015][691a235f] [INFO]: Memory peak usage: 6MB
```

My best is that the `smctoken` session cookie gets reset/regenerated here: 
https://github.com/the-djmaze/snappymail/blob/36789bd3b547a3078932a27142ec4b3e95ec7fa0/snappymail/v/0.0.0/app/libraries/snappymail/crypt.php#L46-L56

because Nextcloud calls the `getMainAccountFromToken(false)` function from here
https://github.com/the-djmaze/snappymail/blob/36789bd3b547a3078932a27142ec4b3e95ec7fa0/integrations/nextcloud/snappymail/lib/Util/SnappyMailHelper.php#L59

before the browser can pull the `smctoken' out of localStorage and set it as the cookie here:
https://github.com/the-djmaze/snappymail/blob/36789bd3b547a3078932a27142ec4b3e95ec7fa0/dev/boot.js#L28-L36

and when the `smctoken` is regenerated it can not be used to decrypt the `smremember` cookie/token 

Possible fix is to add this check:
```php
 // } else { 
    } elseif(!empty($_COOKIE['smctoken'])) {
       $oAccount = $this->GetAccountFromSignMeToken();
```
here: https://github.com/the-djmaze/snappymail/blob/36789bd3b547a3078932a27142ec4b3e95ec7fa0/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/UserAuth.php#L268-L269

**Comment by PeopleInside** [comment]
I have the same issue, I loose the session after browser is closed, also if remember me is checked.

**Comment by the-djmaze** [comment]
When started using localStorage a bug came regarding this.
Then it was fixed to generate an `smctoken`.
Problem is that the generated `smctoken` never gets into localStorage.
So the `smremember` encryption using `smctoken` will fail somewhere.

I've removed the use of `smctoken` by the `smremember` to prevent issues with integrations all together.
