### ISSUE TITLE
Update Sabre/VObject & Sabre/Xml

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#1311]
The most recent Snappymail 2.29.2 is still based on Sabre/VObject 4.5.0 and Sabre/Xml 3.0.0.

Meanwhile [Sabre/VObject 4.5.4](https://github.com/sabre-io/vobject/releases) and [Sabre/Xml 4.0.4](https://github.com/sabre-io/xml/releases) are out.

Therefore it should be considered to update these libraries.

**Comment by the-djmaze** [comment]
Due to my changes i have created https://github.com/the-djmaze/sabre-xml and https://github.com/the-djmaze/sabre-xml
