### ISSUE TITLE
Theme is reset to default

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1312]
Hello !

Snappymail as been updated on our Nextcloud installations last night, to the latest 2.29.2

This morning we notice that the Snappymail theme is the default one, despite that we force it to be `NextcloudV25+@custom`, by script, every morning.

I see also that the Theme tab is not present in the global Snappymail admin page:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/1f0f0d33-d00c-4a8a-83bf-3efc806c0318)

The Configuration tab shows the expected value:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/0aeefc71-3143-442a-96d3-01c06609e092)

And the theme tab it is still available in the personal Snappymail settings:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/f41b8b3b-b3b1-4371-9d2d-7a63288db8cd)

Thanks in advance !
Michel

**Comment by the-djmaze** [comment]
Change `NextcloudV25+@custom` to `NextcloudV25+`
It is moved :wink: https://github.com/the-djmaze/snappymail/pull/629#issuecomment-1752025230
