### ISSUE TITLE
Remember me doesn't work when browser is closed

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1313]
**Describe the bug**

I updated to snappymail 2.29.2 now when the browser is closed and reopen the session never stay live and get lost, I'm logged out.

    Go to SnappyMail login page
    Check the Remember Me checkbox
    Enter credentials and login
    Close browser
    Open browser
    Go to SnappyMail, users expect to be logged in because the Remember Me was set
    💥 You are logged out (back at the login page)

**Expected behavior**

Session should be not loosed with remember me checked

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: postfix, dovecot
- PHP version: 8.2
- SnappyMail Version: 2.29.2
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] GitHub

I'm not in Nextcloud but the issue seems similar to the bug reported here:
https://github.com/the-djmaze/snappymail/issues/1306

Also for me remember me doesn't work.

**Comment by PeopleInside** [comment]
Seems this issue has been reported also here: https://github.com/the-djmaze/snappymail/issues/1275 but still be unresolved.
I'm not sure the same issue was present in version 2.29.1

**Comment by PeopleInside** [comment]
I reverted back to 2.28.4 that is not affected from this issue.
I will not upgrade until the issue will be fixed. I cannot loose session if every time I need insert two step code, a complex password not stored in the browser and the captcha.

**Comment by the-djmaze** [comment]
Resolved
