### ISSUE TITLE
No tag feature in snappymail 

### ISSUE THREAD

**Issue by Dav-d** [the-djmaze/snappymail#1317]
Hi

**Describe the bug**
There is no tag features in snappymail. No tag icon in the header of message. no tag search option in the search menu.

**To Reproduce**
I use Nextcloud 25.0.13. and the last version of snappymail.

**Please complete the following information:**
- Browser: Brave 160.110
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: PHP 7.4.33
- SnappyMail Version: 2.29.2
- Mode: [Nextcloud 25.0.13.

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

I don't understand how to find logs... but debug mode is activated.

**Additional context**

Thank you

**Comment by the-djmaze** [comment]
Yes there is, but it is not available for IMAP servers that do not support it.
The IMAP server must respond with `\*`

https://datatracker.ietf.org/doc/html/rfc3501#page-64
```
PERMANENTFLAGS

         Followed by a parenthesized list of flags, indicates which of
         the known flags the client can change permanently.  Any flags
         that are in the FLAGS untagged response, but not the
         PERMANENTFLAGS list, can not be set permanently.  If the client
         attempts to STORE a flag that is not in the PERMANENTFLAGS
         list, the server will either ignore the change or store the
         state change for the remainder of the current session only.
         The PERMANENTFLAGS list can also include the special flag \*,
         which indicates that it is possible to create new keywords by
         attempting to store those flags in the mailbox.
```
