### ISSUE TITLE
Managesieve: Configuration option to hide "Forward to" option from Filter Actions

### ISSUE THREAD

**Issue by stefansieg** [the-djmaze/snappymail#1323]
**Is your feature request related to a problem? Please describe.**
The problem occurs when the mail server does not support sieve redirect, but the users have the option to create forwarding rules via the sieve UI.

The redirect option cannot be hidden in the user interface of the filter. The option is therefore always displayed, even if sieve redirection is deactivated.

**Describe the solution you'd like**
It would be nice to have a configuration option to hide "Forward to".

**Comment by the-djmaze** [comment]
https://datatracker.ietf.org/doc/html/rfc5228#section-4
> Implementations MUST support the "keep", "discard", and **"redirect"** actions.

https://datatracker.ietf.org/doc/html/rfc5228#section-4.2
> Implementations MAY ignore a redirect action silently due to policy
   reasons.  For example, an implementation MAY choose not to redirect
   to an address that is known to be undeliverable.  Any ignored
   redirect MUST NOT cancel the implicit keep.

This is not up to SnappyMail

**Comment by stefansieg** [comment]
Hmm,

maybe I didn't describe the feature request well enough, if so I'm sorry.

I found this for roundcube: https://github.com/roundcube/roundcubemail/issues/7922
maybe it describes the request and the solution better than I can.

Thanks in any case for your effort.

**Comment by the-djmaze** [comment]
Ok RoundCube can, but that does not solve the problem.
I can still:
- use the raw script editor to write redirect
- open a different mail app (Thunderbird) and write redirect
- etc.

In this case RoundCube is plain wrong to implement something that breaks it.
