### ISSUE TITLE
Move to button does not work

### ISSUE THREAD

**Issue by Beutlin** [the-djmaze/snappymail#1328]
**Describe the bug**
If I open a message and try to click the "move to folder" button, nothing happens. It does not matter if it is the button from the top panel or from the extended menu.

**To Reproduce**
1. Open webmail on a Desktop browser
2. Go to Inbox
3. Click on a message
4. Click on more (burger-like) icon on top of the message list.
5. click "move to" icon either in the opened menu
6. Nothing happens

**Expected behavior**
A popup appears and I can select the folder

**Screenshots**
<img width="962" alt="Screenshot 2023-11-23 at 09 57 17" src="https://github.com/the-djmaze/snappymail/assets/1647207/2585ae5c-e791-4d15-9148-4c2b6ac99fb5">

**Please complete the following information:**
- Browser: Microsoft Edge 119.0.2151.72
- IMAP daemon: dovecot
- PHP version: 8.2.7
- SnappyMail Version: 2.29.4
- Mode: standalone

**Additional context**
Bug seems to be similiar to https://github.com/the-djmaze/snappymail/issues/1274

**Comment by cm-schl** [comment]
Can confirm the problem. This seams to be a UX problem somehow:

In fact moving a mail works when you use the check mark in front of the mail (inside the list of emails).
When you're using the mobile view you can see that the "move" button is only visible when at least one mail is marked - instead on a PC you always see the button what is confusing to the user.

The solutions could be to always allow to move the active mail to a folder (better) or to gray out / don't show the button when no mail is marked (not so nice).
