### ISSUE TITLE
Theme "Nextcloud V25+" can't be translated

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#1331]
Hi,

I'm using the theme "Nextcloud V25+" created by @hampoelz in #629.
On the german user interface there appear two be two buttons that are not translated / seam to be hard coded: "Create new folder" and "Folder-Settings".
![grafik](https://github.com/the-djmaze/snappymail/assets/63400209/bce8972f-befe-415d-b0c7-d2b4c6962afb)

In fact, "Folder-Settings" is not a good label because this opens the general settings dialog, not only folder settings.

**Comment by the-djmaze** [comment]
Confirmed
https://github.com/the-djmaze/snappymail/blob/bde5060008eaadbbfdc3ccc19b0d4ba755ca77de/snappymail/v/0.0.0/themes/NextcloudV25%2B/styles.css#L1472

Shall think of something.
