### ISSUE TITLE
Is there a way to add a line of email body preview on the email list panel?

### ISSUE THREAD

**Issue by europacafe** [the-djmaze/snappymail#1338]
**Is your feature request related to a problem? Please describe.**
The list of mails in the mail list panel shows only the sender and subject. It would be nice to have one line of the message body shown as a third line. 

**Describe the solution you'd like**
At least, snappymail has the option to show the mail body "preview" as a third line in the mail list panel.

**Describe alternatives you've considered**

**Additional context**
yahoo mail: has the mentioned third line showing message body
![image](https://github.com/the-djmaze/snappymail/assets/51871976/916dc611-b2dc-4173-8217-66b9854193bd)

snappymail shows only sender and subject
![image](https://github.com/the-djmaze/snappymail/assets/51871976/2e0056b8-3fc9-4a80-a6ca-00cdacd4e0be)

**Comment by the-djmaze** [comment]
This will be possible when RFC 8970 is implemented.
https://www.rfc-editor.org/rfc/rfc8970.html

**Comment by the-djmaze** [comment]
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/918a628c-113f-41a6-8601-34e9017f42c1)

**Comment by europacafe** [comment]
For your information, I run docker-mailserver from this github
https://github.com/docker-mailserver/docker-mailserver

**Comment by the-djmaze** [comment]
That uses Dovecot, and i also use Dovecot v2.3.15+.

I wonder why yours fails (older version?).
Because you can see on the demo website it works there.

**Comment by europacafe** [comment]
For my self-hosted mail server accounts, preview does work!, but it won't work for those yahoo, gmail, and outlook.

**Comment by europacafe** [comment]
yahoo doesn't have the "preview"
![image](https://github.com/the-djmaze/snappymail/assets/51871976/228a6c10-62bf-49a9-8f53-5870fcb81712)

**Comment by europacafe** [comment]
Thanks. That's fine. I'm happy with what you've done so far.
BTW, do you know why loading my yahoo and gmal takes quite some time, while the yahoo and gmail web are so fast?
Loading my self-hosted email is fast though, probably due to less volume.
Are they caching them in RAM?

**Comment by the-djmaze** [comment]
> BTW, do you know why loading my yahoo and gmal takes quite some time, while the yahoo and gmail web are so fast?

Read https://github.com/the-djmaze/snappymail/wiki/Improve-performance

**Comment by europacafe** [comment]
I've tried all those suggestions before and there seems to be no noticeable speed improvement.

**Comment by europacafe** [comment]
Hi,
Me again.
I've just tried Stalwart mail-server docker, love its much smaller footprint and its Admin WebUI. I can now switch to it (from mail-server docker).
Stalwart IMAP module supports RFC8970 which supports email preview. Could you incorporate this feature?
[](https://github.com/stalwartlabs/imap-server)

**Comment by the-djmaze** [comment]
RFC8970 PREVIEW is implemented and works.

**Comment by europacafe** [comment]
You mean the partial message body pop up when hovering the mouse cursor over the mail subject; or one extra line of message body below mail subject?

I am asking for the latter type of display.

**Comment by the-djmaze** [comment]
latter type is not there as an extra line will not work due to the way how SnappyMail renders the list.

You can create a plugin that does it by modifying the HTML and CSS

**Comment by europacafe** [comment]
Thanks for the confirmation and your continuous support.
