### ISSUE TITLE
Bug in email signature editor

### ISSUE THREAD

**Issue by MarcouxDesBois** [the-djmaze/snappymail#1339]
**Describe the bug**
When i want to add an email signature with html, the editor transform the code to include some `<div></br></div>` even it's not necessary. The result is a signature with large space between elements.

**To Reproduce**
1. Go to 'Settings - Accounts - Identitie'
2. Click on your mail
3. Insert html code in the editor (on source)
4. Change the layout to see a render with html view
5. See error

**Expected behavior**
HTML code should not have unwanted spaces.

**Screenshots**
Result i have : 
![image](https://github.com/the-djmaze/snappymail/assets/32484368/f07570cf-216e-4a86-911c-2399abc6e510)

**Please complete the following information:**
- Browser: chromium 119.0.6045.159
- SnappyMail Version: 2.29.4
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
I haven't log.

**Comment by the-djmaze** [comment]
> 3\. Insert html code in the editor (on source)

We need the HTML code, else we have no idea why it fails.

**Comment by MarcouxDesBois** [comment]
Thank you for the fix.
