### ISSUE TITLE
Is not working inside an iframe

### ISSUE THREAD

**Issue by cardei** [the-djmaze/snappymail#1340]
I set secfetch_allow to mode=navigate;dest=iframe;site=cross-site and I tried any configuration but I am not able to load it inside a iframe.

I get error on console :

Refused to display 'https://test.app.local/' in a frame because it set 'X-Frame-Options' to 'deny'.

thanks!

**Comment by the-djmaze** [comment]
Please look why your server sets the X-Frame-Options header (htaccess, conf, etc.)

**Comment by the-djmaze** [comment]
You are missing the `frame-ancestors` setting.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
