### ISSUE TITLE
Docker upgrade 2.30?

### ISSUE THREAD

**Issue by MarcusFloeser** [the-djmaze/snappymail#1348]
I have successfully installed snappy with docker compose and it is running fine. But if I call the admin page it is telling me a new version is available. Currently I'm running 2.29.2 - new version should be 2.30.0.

How can I upgrade? docker-compose pull does not give me a new image ....

**Comment by the-djmaze** [comment]
Maybe this works?
`docker-compose pull  && docker-compose up -d`

**Comment by the-djmaze** [comment]
Or this:
`docker pull djmaze/snappymail:latest`

**Comment by MarcusFloeser** [comment]
> Or this: `docker pull djmaze/snappymail:latest`

this is working. Thanks
