### ISSUE TITLE
I have a Question to snappymail

### ISSUE THREAD

**Issue by Blacky244-dev** [the-djmaze/snappymail#1351]
Hello I just wanted to know if I can get this snappyMail to run in my IIS server because I am currently still working on Rainloop because IIS does not understand htacess whether I can also realise this via the and especially how

**Comment by the-djmaze** [comment]
Best is that you just try.
It should work.

**Comment by tokfwen** [comment]
I have been using snappymail with IIS for over a year now and so far it has worked fine.
