### ISSUE TITLE
No login possible since Update to 2.30.0 ("NO Mailbox does not exist, or must be subscribed to")

### ISSUE THREAD

**Issue by besca-red** [the-djmaze/snappymail#1354]
**Describe the bug**
Everything worked fine since the update of SnappyMail (2.30.0). Noone is able to login anymore. In the admin panel I can successfully test the connection with the same credentials that do not work on client side - all users return to SnappyMail's login screen after logging in.

**To Reproduce**
1. Start SnappyMail app in Nextcloud
2. Fill in credentials and log in
3. See log

**Expected behavior**
The login should be successful and the inbox should be shown.

**Please complete the following information:**
- Browser: Firefox and some Chromium based browsers
- PHP version: 8.1.26 (Ubuntu 20.04.6)
- IMAP daemon: Dovecot 1:2.3.7.2-1ubuntu3
- SnappyMail Version: 2.30.0
- Mode: Nextcloud 26.0.9.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[snappymail.log](https://github.com/the-djmaze/snappymail/files/13608422/snappymail.log)

**Comment by BiglifeMatt** [comment]
Is there a way to roll back to a previous version?  2.30 is working for some of my users but not all.
