### ISSUE TITLE
Can't move (reorder) a sieve script - Firefox for Android

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1357]
**Describe the bug**

I can't move (reorder) a sieve script where the "hand" cursor appears on desktop view.
Trying to move the script line scrolls the window instead of reordering the script.

**Please complete the following information:**
- Browser: Firefox 120 Mobile
- SnappyMail Version: [2.29.4](https://github.com/the-djmaze/snappymail/releases/tag/v2.29.4)
- Mode: standalone

**Comment by the-djmaze** [comment]
Touch works differently.
Chrome on Android has it build in, and i wrote code to have same behaviour:

1. Press and hold finger/touch
2. When text becomes transparent move
3. Release finger on position
