### ISSUE TITLE
Distinction between real attachment and inline images attachments

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1360]
**Is your feature request related to a problem? Please describe.**

When I see an HTML message with inline images (`Content-ID` header on the attachment ?) and only one true attachment (let's say a `.pdf` file), all images a displayed as an attachment and it is not easy to find the true attachment.

![1](https://github.com/the-djmaze/snappymail/assets/20357783/b660ed8a-d9dd-4a09-9b87-63d69284cde5)

**Describe the solution you'd like**

Inline attachment are : 
- on a second attachment line or
- reduced or 
- not displayed at all (if I want to save an inline image, I can do it from the e-mail where the image is already displayed)

**Examples**

Not a real attachment : 

```
Content-Type: image/png;
	name="logoXXXXX";
	charset="ISO-8859-1"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="logoXXXXX"
Content-ID: <logo>
```

Not a real attachment : 

```
Content-Type: image/png; name=logo.png
Content-Transfer-Encoding: base64
Content-ID: <logo>
Content-Disposition: inline; filename=logo.png
```

Real attachment : 

```
Content-Type: application/pdf; name=XXXXXXXXXX.pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=XXXXXXXXXX.pdf
```

**Comment by the-djmaze** [comment]
Turn `Show inline attachments in list` off in your settings.

**Comment by Massedil** [comment]
> Turn `Show inline attachments in list` off in your settings.

I don't know where this option is.

I search in admin settings panel and in user settings panel.

(Or may be it is strangely translated in French ?)

**Comment by the-djmaze** [comment]
User settings "Afficher les pièces jointes dans la list"

**Comment by Massedil** [comment]
1. Unchecking this checkbox effectively remove all inline attachments from the attachment zone, thanks.

2. "Afficher les pièces jointes dans la liste" just means "display attachment in the list". I think you should update the translation to something like "Afficher les pièces jointes intégrées dans la liste" even if I imagine, like in English, people don't understand what are "inline" attachment.

3. May be a separation between inline and "normal" attachment can be easier for users. Like a menu "more attachment" to see inline attachments.

**Comment by the-djmaze** [comment]
> 3\. May be a separation between inline and "normal" attachment can be easier for users. Like a menu "more attachment" to see inline attachments.

If you look carefully there's a paperclip with the inline attachments.

**Comment by Massedil** [comment]
> If you look carefully there's a paperclip with the inline attachments.

Exact ! I havn’t seen it before now ! :)
