### ISSUE TITLE
Email Thread not properly showing up in Sent at the most recent date available

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1364]
**Describe the bug**
I have a user that submitted a reply to an email thread.  While the message shows up in the nested thread, when viewing the Sent items folder, the message shows up under a date over a month old from within the thread.  The one pictured was last replied to by the user on Dec. 15, but shows in the sent items under Nov. 8th. 

**Expected behavior**
I would expect all responses to a thread from my account to show up under Sent items as the most recent date.  Perhaps it is even more common for the sent messages to capture the thread within sent items for all the dates sent. 

**Screenshots**
![Screenshot 2023-12-18 091059](https://github.com/the-djmaze/snappymail/assets/93135814/46fc68f0-09e4-4606-afa2-df1248434c21)

**Please complete the following information:**
- Browser: Firefox, Edge, Chrome
- IMAP daemon: Dovecot
- PHP version: 8.1.2
- SnappyMail Version: 2.30.0
- Mode: nextcloud

**Comment by the-djmaze** [comment]
RFC 5256 explains that a thread is sorted by sent date.

What you want is a reversed view of this behavior.
This must be developed as this is not part of the RFC.

**Comment by BiglifeMatt** [comment]
Right but the last sent date is Dec 15th.  So shouldn't it show up in the Sent folder as Dec. 15th and not Nov. 8th?

**Comment by the-djmaze** [comment]
Not really. This depends on the thread algorithm used and the references inside the messages.

See the demo mailbox as example.

**Comment by the-djmaze** [comment]
Sounds like a bug/problem in the IMAP when fetching the threads.

As the mail of dec. 15 also has a completely different subject then the others.

**Comment by BiglifeMatt** [comment]
Yes, I'm seeing it respond differently in other clients.  In Outlook (IMAP) it shows that reply with the new subject name listed under Dec. 15th.  Are you saying then the bug would be within SnappyMail handling the IMAP data?

**Comment by the-djmaze** [comment]
Could be, or the IMAP server.
For that we need the logs.

**Comment by the-djmaze** [comment]
I can't reproduce the issue
