### ISSUE TITLE
"null" tooltip since 2.30.0

### ISSUE THREAD

**Issue by ruliane** [the-djmaze/snappymail#1366]
**Bug description**
Since 2.30.0 upgrade, a tooltip appears when the mouse goes over a message. However, this tooltip always contains "null".
This is due to a Title attribute containing "null".
![image](https://github.com/the-djmaze/snappymail/assets/5471186/ad14c40a-c717-486d-84f2-c2b372558f6b)

**To Reproduce**
1. Go to message list
2. Mouse over a message's subject
3. A tooltip appears.

**Expected behavior**
A tooltip containing the message's subject or any other useful piece of information; or no tooltip at all.

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/5471186/62d6304c-6e3c-43b4-bf0c-0b61c3e90ca1)

**Version information:**
- Browser: Firefox 120 / Edge 120
- IMAP daemon: Courier 5.0.13
- PHP 8.2.7
- SnappyMail Version: 2.30.0 / 2.31.0 (bug not present on 2.29.2)
- Mode: standalone

**Comment by the-djmaze** [comment]
This is due to #1338 and fixed in 2.31.0

**Comment by ruliane** [comment]
We misunderstood, #1338 fixes body preview, while this issue is about the `title` attribute of the message, regardless of preview being activated.
Screenshot is taken from v2.31.0.

**Comment by ruliane** [comment]
After digging more, this is somewhat correlated to #1338.

My mail server has no PREVIEW capability. (which probably explains the "null" value)
The tooltip appears even when the PREVIEW capability is disabled on Snappymail's side.

Is it possible to remove the title attribute when PREVIEW is disabled or unavailable server-side?

**Comment by the-djmaze** [comment]
I see it was fixed for next release, not v2.31
https://github.com/the-djmaze/snappymail/commit/3db4827354d42a78532d3c95c5da9600a500b6aa

**Comment by ruliane** [comment]
Great, thanks you!
