### ISSUE TITLE
Change Password function PDO, unable to save password

### ISSUE THREAD

**Issue by cnscdh** [the-djmaze/snappymail#1368]
This is my setting

<img width="619" alt="image" src="https://github.com/the-djmaze/snappymail/assets/84962597/63cf132a-3bee-4097-9e31-a9f94331d985">

<img width="1109" alt="image" src="https://github.com/the-djmaze/snappymail/assets/84962597/eaee87bd-55d1-44ab-964d-81a19b3f23aa">

2023/12/21 18:46:22 [error] 1172846#0: *149400 FastCGI sent in stderr: ＂PHP message: PHP Notice:  ChangePasswordDriverpdo failed: UnknownNotification[130] in /www/wwwroot/webmail2.XXX.com/data/_data_/_default_/plugins/change-password/index.php on line 184PHP message: PHP Notice:  ChangePassword failed in /www/wwwroot/webmail2.XXX.com/data/_data_/_default_/plugins/change-password/index.php on line 195＂ while reading response header from upstream, client: 127.0.0.1, server: webmail2.XXX.com, request: ＂POST /?/Json/&amp;q[]=/0/ HTTP/2.0＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-74.sock:＂, host: ＂webmail2.XXX.com＂

**Comment by the-djmaze** [comment]
Check your PHP and SnappyMail logs why it failed

**Comment by cnscdh** [comment]
Thank you. I have already identified the problem
