### ISSUE TITLE
[202] Data folder permissions error [is_writable]

### ISSUE THREAD

**Issue by yutanicorp** [the-djmaze/snappymail#1371]
**Describe the bug**
After downloading and unarchiving into destination folder, the public html folder, and opening "[root-domain]/snappymail/index.php", the error "data folder permissions error" is raised

**To Reproduce**
1. execute "wget https://snappymail.eu/repository/latest.tar.gz -O /tmp/snappymail.tar.gz" using ansible
2. extract archive to folder "/var/www/[root-domain]/html/hyperlink-folders/snappymail" using ansible
3. execute "find /var/www/[root-domain]/html/hyperlink-folders/snappymail -type d -exec chmod 755 {} \;"
4. execute "find /var/www/[root-domain]/html/hyperlink-folders/snappymail -type f -exec chmod 644 {} \;"
5. execute "chown -R apache:apache /var/www/[root-domain]/html/hyperlink-folders/snappymail"
6. go to browser and enter in bar "[root-domain]/hyperlink-folders/snappymail/?admin"

**Expected behavior**
An admin UI page

**Screenshots**
Black screen with "[202] Data folder permissions error [is_writable]"
<img width="711" alt="Screenshot 2023-12-25 at 20 42 26" src="https://github.com/the-djmaze/snappymail/assets/50074566/4c6507f4-03cb-41b3-8311-28625656496a">

However, I see a difference between the amount of files inside the data-folder in an older version running for 2-3 years on another server and the latest version running on a new server. The newer version has only a few files. Perhaps this difference can be explained because no "/?admin" was run.
<img width="902" alt="Screenshot 2023-12-25 at 18 55 13" src="https://github.com/the-djmaze/snappymail/assets/50074566/673210a4-a8f9-4cb9-8d1e-ecbbaf142b8f">

**Please complete the following information:**
- Browser: Firefox 120
- IMAP daemon: n/a
- PHP version: 8.0
- SnappyMail Version: 2.31.0 (latest)

- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
I have set group/owner to Apache but didn't help.
I have removed and added write permissions on all files, but that didn't help either.
I didn't have any issues installing/configuring an older version Snappymail a few years ago.

**Comment by the-djmaze** [comment]
SnappyMail now runs several tests to check if it can run properly.

In your case the is_writable test fails for the data folder.
The foldsr must be 0700 for the php process user.

**Comment by yutanicorp** [comment]
Thank you for your swift response! It was indeed SELinux. 
Issuing "setsebool -P httpd_unified 1" and "semanage fcontext -a -t httpd_sys_rw_content_t [directory" solved it.
Great app!

**Comment by the-djmaze** [comment]
> Great app!

Thanks!
