### ISSUE TITLE
Sorting not supported since 2.32.0

### ISSUE THREAD

**Issue by ruliane** [the-djmaze/snappymail#1373]
**Describe the bug**
The sort button shows as if the server had no SORT capability.
This bug happens after upgrading from 2.31.0 to 2.32.0.
Looks like commit https://github.com/the-djmaze/snappymail/commit/e3219a26360073967680c3d2f691f203ca4e52ed is incomplete. returning `$this->aCapaRaw;` in function `Capability()` seems to solve this issue.

**To Reproduce**
1. Upgrade to 2.32.0
2. Open a mailbox
3. The toolbar does nos show ability to sort messages.

**Expected behavior**
The button should allow sorting messages by subject, date, ...

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/5471186/87cdb7c5-ac85-4180-aa32-970cbce9416d)

**Please complete the following information:**
- Browser: Firefox 121
- IMAP daemon: Courier 5.0.13
- PHP version: 8.2.7
- SnappyMail Version: 2.32.0
- Mode: Standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[I cannot grab logs right now, will try to get them later]

**Comment by the-djmaze** [comment]
Make sure ?admin -> Domains -> Domain the `Disable capabilities` is uncheckt.

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/a0722cd5-03ca-4dfb-b791-308c03581161)

**Comment by ruliane** [comment]
Confirmed: No capability is disabled.
![image](https://github.com/the-djmaze/snappymail/assets/5471186/965c124b-a75c-494b-93ff-034ca1d41d69)

Sorting works again if I rollback to 2.31.0, or if I fix the `Capabiliity()` function.

**Comment by the-djmaze** [comment]
Strange. I will look into it.

**Comment by the-djmaze** [comment]
The problem was when you disable SORT, it also disabled ESORT.
But when you enable SORT, it did not enable ESORT.

**Comment by ruliane** [comment]
Nice catch, thank you!
