### ISSUE TITLE
Sieve Filter ERROR 902

### ISSUE THREAD

**Issue by no6una9a** [the-djmaze/snappymail#1375]
Hello,

I set up a Nextcloud server within a docker container. Snappymail is running fine for sending/receiving e-mails. The only thing is: I can not enable sieve functionality to work. 

I configured the domain successfully including valid sieve testing (snappy_domain_setup.png). But if I try to set up filters in the Nextcloud Snappymail filter user section everything I got is "ERROR 902" error (snappy_filter_error.png) - whatever that means.

The sieve function is/was working perfect on a Nextcloud server running on the same host without Docker virtualisation. There was also a predefined "Rainloop" filter option to be used to define filtering rules. The mail backend is (still) running on postfix & dovecot. I just moved the Nextcloud server into a container. 

Snappymail says there are a few PHP extensions (snappy_php_extensions.png) missing. Could it be somehow related to these extensions snappymail is refusing to do sieve filtering? 

The logs on the dovecot server only show "managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>" - nothing else. It seems to me that Snappymail is refusing to authenticate itself to the sieve server?

I already enabled snappymail logging but there is nothing in the logs indicating any error so I am pretty clueless right now :-(

Additional information:
- Browser: Vivaldi, Firefox
- IMAP daemon: dovecot 2.3.19.1 
- PHP version: PHP 8.2
- SnappyMail Version: SnappyMail 2.32.0
- Mode: Nextcloud within Docker container
- Webserver: Nginx 1.22.1 (Reverse proxy)
- Host OS: Debian 12.4
- Docker Engine: 24.0.7
- Nextcloud Container OS: Debian 12.4

1. Go to: Nextcloud-Email -> Folder -> Filter
2. See error: ERROR 902

Kind regards,
Nobunaga

![snappy_domain_setup](https://github.com/the-djmaze/snappymail/assets/49673381/3b8f14fd-9e65-47c1-9071-f07c40b391d3)

![snappy_filter_error](https://github.com/the-djmaze/snappymail/assets/49673381/6c7d98cc-66d4-43d2-b268-0bdb31612573)

![snappy_php_extensions](https://github.com/the-djmaze/snappymail/assets/49673381/b6868ef7-fbcc-4116-9c0d-ea1006ed0b33)

**Comment by the-djmaze** [comment]
Check your SnappyMail log, it should explain why it failed.
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by no6una9a** [comment]
Hello djmaze,

thanx for your reply - attached to this post is a debug log (snappy_debug_server_231228.txt) created by a click on snappymails "Filter" button. 

I also did capture browser debug infos (snappy_debug_browser_231228.png) while clicking on the "Filter" button. There seems to be no error message, only 2 warnings about "NotificationApps....".

Maybe you can see something indicating what the error reason might be?!

Kind regards, Nobunaga

[snappy_debug_server_231228.txt](https://github.com/the-djmaze/snappymail/files/13786494/snappy_debug_server_231228.txt)

![snappy_debug_browser_231228](https://github.com/the-djmaze/snappymail/assets/49673381/015994fa-777e-463d-bbf5-b27c0328b41f)

**Comment by no6una9a** [comment]
Hello,

I am so sorry - I can't believe it but ... the error was on my side :-( My server and its docker containers are protected by a shorewall firewall. I put in a rule to allow access to the managed-sieve port 4190 BUT I USED THE WRONG SOURCE ZONE ("public" instead of "docker"). Since the new Nextcloud install runs in a docker container the docker-zone connection never made it to the managed-sieve instance.

What I still don't fully understand is why I got one single syslog line logged like: "dovecot: managesieve-login: Disconnected: Aborted login by logging out (no auth attempts in 39 secs) ..." although there was no matching shorewall rule.

Anyway - it works! You can close my request. Thank you very much for taking care for this wonderfull piece of software. I am in IT for a long time now and this is by far the best Web-based mailclient I ever used.

Kind regards, Nobunaga
