### ISSUE TITLE
[Feature Request] Store Identities in Persistent Storage/DB 

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#1383]
**Is your feature request related to a problem? Please describe.**
Yes and no? Identities are currently stored in the browser cache, rather than the database. Which means having to set EVERYTHING again, if the cache is cleared.

**Describe the solution you'd like**
Identities are stored in the database to prevent loss of identity information on cache clear.

**Describe alternatives you've considered**
Currently, the only alternative is storing all of your identity data in a file somewhere, which still requires manually setting all of it again.

**Additional context**
Nothing additional.

**Comment by the-djmaze** [comment]
Identities are NOT stored in the browser cache.
They are stored in `/_data_/_default_/storage/[domain]/[local]` (local@domain).

So what is your problem?
