### ISSUE TITLE
OpenPGP public key can not be removed anymore after importing private key of subkey

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1384]
**Describe the bug**
I started to secure my OpenPGP keys and created subkeys for signing while I removed the private key of the main key from it (like suggested here https://wiki.debian.org/Subkeys). After importing the private key of my new subkey to SnappyMail the key in the GnuPG section is not removable anymore.

**To Reproduce**
- Import private key of subkey

- I get the following error in the browser console:
- `Uncaught (in promise) Error: Could not find valid encryption key packet in key 6XXXXXXXXXXXXXXX`

- BUT it automatically creates two keys in "GnuPG" section and one in OpenPGP section looking like this:

![image](https://github.com/the-djmaze/snappymail/assets/43847817/0574ee39-18ac-4ecc-90df-95a16d029eff)

- Now if I want to remove the public key in GnuPG section I get the error message `0 - Delete private key first: 6XXXXXXXXXXXXXXX` – which is absolutely OK!

- Now I delete the private key in OpenPGP.js section and it gets removed from the GUI but there is no network request being sent (which seems to be fine).

- Next I remove the private key for signing in GnuPG section, it disappears and a network request is sent for action "GnupgDeleteKey" with result **true**

- Now I try to remove the public key and I still get the error message `0 - Delete private key first: 6XXXXXXXXXXXXXXX`

- After reloading the page the public key in GnuPG section **reappears** (which is strange because the network request said it was removed successfully) – maybe it gets generated automatically again.

Now I'm stuck in a loop. Reimporting of the whole key does not change anything. Also a reimport of the original key which worked before (and which has the same hash) does not work. So this broke the whole system.

Removing `/data/_data_/_default_/storage/domain.de/xx/.gnupg` repaired the situation for me.

**Expected behavior**
Either I must be able to remove everything after importing it or there must be an error message which prevents me from importing a cert which locks me in like I described above.

**Please complete the following information:**
- Browser: Firefox
- PHP version: 8.0
- SnappyMail Version: 2.32.0
- Mode: standalone

**Comment by the-djmaze** [comment]
subkeys are bound to a primary key pair, so you need them.

subkeys is partially supported because it is difficult to support.

Not to mention the current state with the upcoming OpenPGP refresh
https://datatracker.ietf.org/doc/draft-ietf-openpgp-crypto-refresh/

**Comment by codiflow** [comment]
Thanks for your answer – I also don't really see a need for a fix as my "workaround" also did its job and everything works fine since then :-)

Also thanks for the hint with the crypto refresh – haven't heard of that yet. I'm already a bit curious about this talk :-)

**Comment by the-djmaze** [comment]
> Also thanks for the hint with the crypto refresh – haven't heard of that yet. I'm already a bit curious about this talk. Sad that there is no recorded version available here: https://video.fosdem.org/2024/h2213/

Maybe @twiss can shed some light on the matter?

**Comment by twiss** [comment]
Hey :wave: There was an issue with the recorded video where the slides were 15 seconds ahead of the camera and audio, that I've asked the FOSDEM admins to look into, to see if it can be fixed. In the meantime, I've temporarily uploaded it [here](https://drive.proton.me/urls/7KWPVVKK4M#8MoeKVcoLOjb).
