### ISSUE TITLE
TCP 143 error

### ISSUE THREAD

**Issue by rougerouter** [the-djmaze/snappymail#1386]
**Describe the bug**
Can't login get the error in title
**To Reproduce**
1. Go to '...' Sign in and get the error.

**Expected behavior**
I expect to login
**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile] Any browser
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: Latest
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] Nextcloud on TrueNAS

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Did you check you firewall?
