### ISSUE TITLE
Show BCC in sent mail

### ISSUE THREAD

**Issue by lje** [the-djmaze/snappymail#1387]
**Is your feature request related to a problem? Please describe.**
SnappyMail does not show BCC in sent mails

**Describe the solution you'd like**
I'd like to see BCC like TO and CC

**Describe alternatives you've considered**
Currencly you have to look at the raw original to see BCC

**Comment by the-djmaze** [comment]
> Currencly you have to look at the raw original to see BCC

No. Just click on the `i` situated here: 
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/fc40ab9e-3cbc-4c65-86bb-3df5a87aacb4)

**Comment by lje** [comment]
Thanks, I didn't notice that option yet.
