### ISSUE TITLE
Header markup for spam/virus (maybe more)

### ISSUE THREAD

**Issue by tomszilagyi** [the-djmaze/snappymail#139]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I thought it would be really cool if SnappyMail had the ability to warn the user about possibly dangerous or malicious email. Alternatively, help the user understand why the email has been put into Spam, etc. Please see this very unprofessional mockup to illustrate the concept:
![SnappyMail_HeaderMarkup](https://user-images.githubusercontent.com/5454768/131702034-ce3ad59d-6647-45be-a989-89b62ba25421.png)

**Describe the solution you'd like**
The way I imagine this feature is that when certain headers exist or match a pattern, that header would be included in the message header area (below the subject with large bold letters, sender, date, recipient). Possibly (preferably) with a highlighted background.

So as a concrete example, I could somehow configure SnappyMail that "if the email has a header line that matches `X-Spam-Status: Yes ...`, then please put that header right up there on top of the message with a yellow background so I won't miss it. And if there is a header line that matches `X-Virus: ...`, put that up as well, with a bright red background."

This mechanism would be completely independent of the folder (it would work just the same on all email everywhere), the mockup above shows an email in Spam, but it would be useful to see potentially dangerous emails dropped into the Inbox clearly marked as such (e.g., if the mail server is not configured to automatically move such email to a different place).

**Describe alternatives you've considered**
GMail tries to do something similar by displaying vague text like "this message is in spam because it is similar to other messages already in there", which is not very technical. I think it's best to just display and highlight the given header, if there is a match, as is.

**Additional context**
I guess this is something that would be best handled by an extension, to be enabled and set up site-wide by the SnappyMail administrator.

**Comment by the-djmaze** [comment]
Spam score is already in.
Click on the large `i` at the top of message to see it.
Currently there's also a hidden HTML Meter element in the messageview to show a meter from green to orange to red (33% step).
You can uncomment it and flush cache to see it in action.

**Comment by ervee** [comment]
Should it always show a SPAM score?
![image](https://user-images.githubusercontent.com/4435930/131722401-a6f534a6-7724-482f-bcec-26e4091aad2b.png)

There is a score in the source of the message:
![image](https://user-images.githubusercontent.com/4435930/131722324-f24bf4c6-635c-429d-bb27-e8b307142b62.png)

**Comment by the-djmaze** [comment]
I edited my previous comment.
Did you check the link of the source i mentioned?

The commented out part with `<meter...>` is what you looking for.
A few lines below that, you will see the other part that will only be visible when score is higher then 0

**Comment by tomszilagyi** [comment]
> I edited my previous comment.
> Did you check the link of the source i mentioned?

Yes, I should have mentioned that. Thanks!

**Comment by the-djmaze** [comment]
Added X-Virus-Status detection.
When status is `infected` it shows a red warning box.

**Comment by tomszilagyi** [comment]
Thanks. I haven't tested this yet, but looking at the patch and reading your description I have a problem with it. I use rspamd and that puts an `X-Virus: <name-of-virus>` header if a virus is detected. A cursory look at the documentation (https://rspamd.com/doc/modules/milter_headers.html#x-virus) does not reveal a way to enable an `X-Virus-Status` header.

**Comment by tomszilagyi** [comment]
Perfect, thanks a bunch!
