### ISSUE TITLE
'Invalid token' error for login

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1391]
Describe the bug
Hello,
I encounter an 'invalid token' error on the login page for both user and admin roles. Snappymail works well on its own, but when installed through the Nextcloud app installer interface, this error occurs. I need to have Snappymail within Nextcloud v21 on my local.

To Reproduce
1. Install Nextcloud v21.
2. Install Snappymail by Nextcloud app installer interface.

Expected behavior
Users and admin can log in without problems.

Screenshots
Admin login page:
![image](https://github.com/the-djmaze/snappymail/assets/93854988/50c7c9ae-a798-4712-b05c-5d7efeddd6f7)

Console log:
![image](https://github.com/the-djmaze/snappymail/assets/93854988/ad664da7-94ad-464d-9079-eebff48de574)

Error in log file:
![image](https://github.com/the-djmaze/snappymail/assets/93854988/3c68d95f-df98-4b16-a414-48c092f9e5d4)

User login page:
![image](https://github.com/the-djmaze/snappymail/assets/93854988/17603007-4912-4f07-83ff-1f1251c9a851)

Please complete the following information:
- PHP version: 7
- SnappyMail Version: 2.32.0
- Mode: Nextcloud v21.0.2.1

Regards

**Comment by rezaei92** [comment]
Are you talking about Snappymail within Nextcloud compared to the standalone Snappymail? Both are set up on my localhost, each with a distinct domain address for development purposes.

However, Snappymail works well when I test it standalone. But it has this problem in Nextcloud.

**Comment by the-djmaze** [comment]
This could be related to HTTPS vs HTTP.
I never test using `localhost` but the browser debug console should tell something about that.

**Comment by rezaei92** [comment]
Thank you for your help. 
The issue was with my own system, and it has been resolved.
