### ISSUE TITLE
Avatars plugin: Gravatar is not displayed

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1393]
# To Reproduce

Configure Avatars plugin as following

<dl>
<dt>Identicon</dt>
<dd>Name characters else silhouette</dd>
<dt>Preload valid domain icons</dt>
<dd>On</dd>
<dt>Delay lookup</dt>
<dd>On</dd>
<dt>BIMI</dt>
<dd>On</dd>
<dt>Gravatar</dt>
<dd>On</dd>
</dl>

Then access messages that avatar is provided.

# Expected behavior

All of preload valid domain icons, BIMI and Gravatar are displayed.

# What really happens

Preload valid domain icons and BIMI are displayed, but Gravatar is not.

If I check `_data_/_default_/avatars` directory, there are only `.svg` files.
So it seems image data of Gravatar isn't downloaded.

# Environment

## Browser

* Google Chrome  120.0.6099.22 on Windows
* Microsoft Edge 120.0.2210.133 on Windows
* Mozilla Firefox 121.0.1 on Windows
* Google Chrome 120.0.6099.210 on Android
* Microsoft Edge 120.0.2210.126 on Android
* Mozilla Firefox 121.0.0 on Android

## Server 1

* FreeBSD 13.2-RELEASE amd64
* Dovecot 2.3.21
* Apache HTTP server 2.4.58
* PHP 8.3.1
* SnappyMail 2.32.0
* Avaters plugin 1.12

## Server 2

* Debian 11.8 amd64
* Dovecot 2.3.13
* Apache HTTP server 2.4.56
* PHP 7.4.33
* SnappyMail 2.32.0
* Avaters plugin 1.12

**Comment by the-djmaze** [comment]
Gravatar now forces HTTPS
