### ISSUE TITLE
readonly configuration mount in docker compose

### ISSUE THREAD

**Issue by jpduyx** [the-djmaze/snappymail#1398]
**Is your feature request related to a problem? Please describe.**
I used the unofficial docker image and had everything configured to mount 2 folders with configs readonly so from within the container it is impossible to change any settings and instead those settings are managed by configuration management tool (ansible). 

- ./snappy/configs:/var/lib/snappymail/_data_/_default_/configs:ro
- ./snappy/domains:/var/lib/snappymail/_data_/_default_/domains:ro

This container was deprecated and I was advised to migrate. I changed the settings to match the new container ... but it just didn't start ... 

**Describe the solution you'd like**
I would like to be able to start the official snappymail container while I still use a readonly mount of the configuration. 

**Describe alternatives you've considered**
running the old image is depricated ... changing the entry point and maintaining my own container ... or better try to discuss if there are more people trying to do the same thing and if there is is a way to make it possible to run the official container with readonly mount of externally managed config folders / files. 

**Additional context**
i think the config of the entrypoint saying "set -e" means that any failure of any command will exit the script ... thus when it tries to change the ownership settings of the readonly mounted subfolders ... that command fails and the entrypoint.sh script exits ... making the container unstartable

**Comment by the-djmaze** [comment]
Currently not possible. But maybe someone might solve it.

https://github.com/the-djmaze/snappymail/wiki/Docker
