### ISSUE TITLE
Keyboard keys do not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#14]
**RainLoop version, browser, OS:**
the-djmaze8, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
- click on a mail in the message list
- press delete button on the keyboard => nothing happens
The delete button should move the mail into the trash folder.

It is also not possible to navigate through the message list with the arrow keys. Snappymail just does ignore the keyboard.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
n/a

**Comment by the-djmaze** [comment]
I already thought so!
It's an old script in vendors/keymaster that uses the old Event system.
Nowadays with KeyboardEvent we can achieve better response.
I already did that with SquireUI so i will merge them in a new shortcuts handler.

Also one shortcut is bugging me. It uses the Backtick but on my international keyboard it is a 'Dead' key, and on my Mac there is none.

**Comment by phsc84** [comment]
Works perfectly in SnappyMail 2.0.0-rc1.
