### ISSUE TITLE
Identity Management: add per-identity "sent" folder 

### ISSUE THREAD

**Issue by sm-boogie** [the-djmaze/snappymail#1404]
I am moving to SnappyMail from Horde. The identity manager there is quite powerful.

It would be great if an identity could have a "sent mail" folder different from the system-wide "sent" folder. The system-wide "sent" folder could potentially be removed in favor of per-identity ones.

**Comment by the-djmaze** [comment]
I use KMail on the desktop.
So probably you want something like that?
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/8e05c873-9ab1-493f-a193-a1dc7d45bab0)

**Comment by sm-boogie** [comment]
Yes, that would be perfect.

Horde additionally "pins" the identities' sent-mail folders between the system folders and the general folder list, which is also quite useful for quick access.
