### ISSUE TITLE
Upload attachments >30MB fail

### ISSUE THREAD

**Issue by LarsBel** [the-djmaze/snappymail#1406]
**Describe the bug**
Attachments >30MB cant be added. Snappymail reports an unknown error -> undefined

**To Reproduce**
1. Open new Mail
2. add file >30MB

Admin Interface:
Attachment size limit 0 MB
PHP: upload_max_filesize = 16G; post_max_size = 16G

**Expected behavior**
File will be uploaded

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/39060393/7b8b3bc8-feae-4184-870f-402dd8830862)

**Please complete the following information:**
- Browser: Chrome latest
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.1
- SnappyMail Version: latest
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
No lines are added to Logfile in debug mode when uploading (only when files are smaller like 20MB)

**Additional context**
none

**Comment by the-djmaze** [comment]
Please check over faster upload speed lines (like fiber) and check you httpd logs.
