### ISSUE TITLE
nextcloud integration dynamic property

### ISSUE THREAD

**Issue by prilly-dev** [the-djmaze/snappymail#1409]
**Describe the bug**
 Creation of dynamic property `SnappyMail\DAV\Client::$__UrlPath__` is deprecated at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.33.0/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php#335

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by cohenchris** [comment]
I am also seeing this message in my logs, and Nextcloud has a warning message in the Overview section telling me about it.

**Comment by ColdSphinX** [comment]
This is due to PHP8.2
https://php.watch/versions/8.2/dynamic-properties-deprecated
