### ISSUE TITLE
Small issue on thread counter

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#141]
**Describe the bug**
Somewhere after 2.5.2 the HTML code changed a little for the threads counter display (see screenshots below). There is some spacing missing after the > I think. Perhaps also something to do with #105
I tried debugging the HTML/code, but this is just not my thing I guess. I can't see how to fix this.

**To Reproduce**
On 2.7.0 enable threads view and see the threads counter.

**Expected behavior**
I think there should be a space behind >

**Screenshots**
![image](https://user-images.githubusercontent.com/4435930/132122047-7401ef8a-293e-4a66-899c-8b654decf681.png)
v2.5.2

![image](https://user-images.githubusercontent.com/4435930/132122062-cabf69b7-4393-42ce-86ac-cc9796c81703.png)
v2.7.0

**Desktop (please complete the following information):**
 - Browser: Firefox 90 of Fedora.
 - SnappyMail Version 2.7.0

**Comment by the-djmaze** [comment]
It should be better now
