### ISSUE TITLE
Transparent backgroud for text

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1412]
Sometimes pasting text in the email body leaves a colored background behind the text.  There doesn't seem to be a "remove formatting" or transparent color option.  That would be nice to eliminate any background color.

**Comment by the-djmaze** [comment]
Does the added button work for you?
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/1a325f63-0d38-4bac-8e2d-5d50218cbdaf)
