### ISSUE TITLE
LDAPBackend global language settings not applied after Snappymail update 2.33

### ISSUE THREAD

**Issue by Reis-A** [the-djmaze/snappymail#1414]
After the last update in nextclould to snappymail 2.33 the language changed in the accounts of some users.
I had the language setting applied by the systempanel system wide and did not allow the users to change the language setting individually
In the snappymail admin panel setting the language is set to De_de (both for admin panel and the mailboxes), but they saw the menu in English. So Somehow the update 2.33 had an effect on that.

However, after I allowed the users to change the language setting in their own config panel individually, the German language setting was applied correctly for that user.
So i just wanted to give this feedback. Maybe there is a solution. For now, I allowed the users to change the language setting individually, so it should not be a big issue...

**Comment by the-djmaze** [comment]
When `allow_languages_on_settings` is off, it uses the Nextcloud language.
So what do the users have at Nextcloud -> Settings -> User ?

**Comment by Reis-A** [comment]
ok i read your articles. Now I added 'force_language' => 'de' to my config.php
with the effect that German is enforced for all user on the nextcloud level. In the user properties it is shown no language selected, even though the nextcloud language is now German.
Snappy falls back to English if I put allow_languages_on_settings=off.
 So apparently, the German language is not found in snappymail??
if i remove the force_language property in nextcloud and pick German ("Du") in Nextcloud on a user level, it still switches to English.
To make things more complicated, the language is selected correctly with my local nextcloud admin account.
I have the problem only with accounts, that are provisioned from LDAPBackend.

**Comment by the-djmaze** [comment]
> I have the problem only with accounts, that are provisioned from LDAPBackend.

That at least narrows down the issue. So that might cause the issue.
