### ISSUE TITLE
Suggestion: maybe provide a security.txt on the website

### ISSUE THREAD

**Issue by vonshednob** [the-djmaze/snappymail#1416]
The `SECURITY.md` in the repo is easy enough to find, but my first attempt to reach out in case of security issues is/was to check if there’s a security.txt on snappymail.eu (either in `/.well-known/` or in `/`).

Maybe have one of those, too?

Reference to the standard: [website](https://securitytxt.org/), [RFC9116](https://www.rfc-editor.org/rfc/rfc9116)

**Comment by the-djmaze** [comment]
Good catch, i will add one

**Comment by the-djmaze** [comment]
https://snappymail.eu/.well-known/security.txt

**Comment by vonshednob** [comment]
Perfect, thanks!
