### ISSUE TITLE
No carddav sync when using synology contact

### ISSUE THREAD

**Issue by Bagu** [the-djmaze/snappymail#1417]
**Describe the bug**
Hello, when I use the synology carddav address book, I get the error message "unknown error" when synchronising if I use the form link :
https://myserver:5101/carddav/myuser/myid

And I get no synchronisation and no message if I use the form link :
https://myserver:5101/carddav/myuser

**To Reproduce**
1. Go to 'User menu'
2. Click on 'Parameters'
3. Scroll down to 'contact'
4. Select "Read only"
5. Add the url 'https://myserver:5101/carddav/myuser/myid'
6. Add account and password
7. Go to 'Address book'
8. Click on the three horizontal bars menu
9. Click on 'Sync (CardDAV)'

**Expected behavior**
The address book should synchronise

**Please complete the following information:**
- Browser: Firefox 122.0
- IMAP daemon: Hmailserver 5.6.8
- PHP version: 8.1.27
- SnappyMail Version: 2.33.0
- Mode: standalone

**Comment by the-djmaze** [comment]
Please provide the log

**Comment by Bagu** [comment]
I try, but, when i go to \data\_data_\_default_\config\application.ini and set ;Enable loggin to enable=on, no log file is created under \data\_data_\_default_\logs\ And i get a blank page.

`[03-Feb-2024 13:40:40 UTC] Uncaught exception: Exception: DateTimeZone::__construct(): Unknown or bad timezone (UTC+1) in \snappymail\v\2.33.0\app\libraries\RainLoop\Actions.php:262
Stack trace:
#0 \snappymail\v\2.33.0\app\libraries\RainLoop\Actions.php(262): DateTimeZone->__construct()
#1 [internal function]: RainLoop\Actions->RainLoop\{closure}()
#2 \snappymail\v\2.33.0\app\libraries\RainLoop\Actions.php(263): preg_replace_callback()
#3 \snappymail\v\2.33.0\app\libraries\RainLoop\Actions.php(365): RainLoop\Actions->compileLogParams()
#4 \snappymail\v\2.33.0\app\libraries\RainLoop\Actions.php(132): RainLoop\Actions->compileLogFileName()
#5 snappymail\v\2.33.0\app\libraries\RainLoop\Api.php(12): RainLoop\Actions->__construct()
#6 \snappymail\v\2.33.0\app\libraries\RainLoop\Api.php(54): RainLoop\Api::Actions()
#7 \snappymail\v\2.33.0\app\libraries\RainLoop\Service.php(256): RainLoop\Api::getCSP()
#8 \snappymail\v\2.33.0\app\libraries\RainLoop\Service.php(35): RainLoop\Service::setCSP()
#9 \snappymail\v\2.33.0\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#10 \snappymail\v\2.33.0\include.php(127): RainLoop\Service::Handle()
#11 \index.php(11): include('...')
#12 {main}`

After i set to time_zone = "GMT+1" instead of "UTC+1", i was able to get something.
And the problem is due to a client-side cache problem.
