### ISSUE TITLE
Docker - Persisting configuration

### ISSUE THREAD

**Issue by TheGor1lla** [the-djmaze/snappymail#1421]
Just started using Snappymail in docker.  
My config so far is pretty bare-bones, just added my desired domains and changed the admin credentials.  

How would I persist this config? Browsing around the provided docker-compose there should be a /snappymail/data dir? I'm running v2.33.0 

```
/snappymail # ls
include.php  index.php    snappymail
```

How do I persist my config?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Docker
