### ISSUE TITLE
Sort Inbox Folders with Unread Messages First

### ISSUE THREAD

**Issue by NickDaly** [the-djmaze/snappymail#1427]
### Is your feature request related to a problem? Please describe.

My feature request resolves a usability issue.

My email provider's support of plus-addresses means that my business email-account effectively has a different folder for each company I've interacted with, dozens of them in all.  When new messages come in to folders that are later in the alphabet and beyond the bottom of the screen (beneath the end of the folder list), I will sometimes miss them.

### Describe the solution you'd like

Please add a new option to the "Folders" option page that lets users sort folders with unread messages to the top of the list, or hides folders with unread messages.  I would personally prefer to sort, since the unread folders would remain immediately available, however, hide is probably simpler to implement.

### Describe alternatives you've considered

I've created a workaround through a CSS stylesheet override that works to hide folders with no-unread items.  However, implementing this as an Option would resolve this problem for more people than just me.

```
@-moz-document domain("your.webmail.provider") {
    a.selectable {
        visibility: hidden !important;
        height: 0px !important;
    }
    a[data-unread] {
        visibility: visible !important;
        height: auto !important;
    }
}
```

Thanks for your time,
Nick

**Comment by the-djmaze** [comment]
I had an idea for sorting based on unread.
But this is complex.

Say there is:
- INBOX.folder1 has 0 unread
- INBOX.folder1.sub1 has 1 unread
- INBOX.folder2 has 1 unread

Should folder1 be sorted first because sub1 has unread?
People will say: sort is broken because folder2 is not listed first.

If your IMAP server supports search in subfolders or supports virtual folders, then search for unread will work fine.

**Comment by NickDaly** [comment]
Hi the-djmaze, thank you for reviewing and replying so quickly!  Since this is, at most, a minor usability enhancement, it probably isn't worth many tuits.

I, personally, use subfolders so infrequently that almost any sort method would be acceptable.  My intuition is to sort subfolder-1 first, then folder-2, then folder-1, but I do not have a good explanation as to why that's my intuition.

Thank you for reminding me about IMAP virtual folders and search folders: that works well in desktop email clients (Thunderbird), even though it does require subscribing to each folder individually (and therefore requires updating the folder for each new plus-address).  That, however, is not a problem with Snappymail.

**Comment by the-djmaze** [comment]
I've implemented it as filter.
Just like the search bar above the folders.

This way you can search by name or filter by unread/unseen

**Comment by NickDaly** [comment]
Thank you for implementing this feature, it's just fantastic.
