### ISSUE TITLE
Default language in login page

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1428]
**Describe the bug**
The login page in Nextcloud does not reflect the changes in language and direction that are set in the admin panel. Therefore, when the language is set to anything other than English in the admin panel, the login page’s translation and right-to-left alignment are incorrect.

**Screenshots**
![snappymail1](https://github.com/the-djmaze/snappymail/assets/93854988/612fecf1-2c45-41a2-a116-4fc1702d1d47)
![snappymail2](https://github.com/the-djmaze/snappymail/assets/93854988/54170cf1-1b02-4c39-a471-6f5fd19791e3)

**Please complete the following information:**
- Mode: Nextcloud

**Comment by the-djmaze** [comment]
Nextcloud has a weird support for RTL.
Here it does not:
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/505973fb-4e09-43fe-900c-e75666f8c3bf)

In SnappyMail it does:
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/79d0942b-8e82-4e69-baaa-44c0393e4612)

# As for the languages:

## Login page:
	When allow_languages_on_login is on and determine_user_language is on,
	it tries to detect using the browser Accept-Language header.
	Else the default language is used.

## Logged in:
	When allow_languages_on_settings is on and a language is set, use that.
	Else when determine_user_language is on, it tries to detect using the browser Accept-Language header.
	Else the default language is used.

## Nextcloud integration:
	When allow_languages_on_settings is off,
	it tries to use the Nextcloud -> Personal settings -> Personal info -> Language.
	(not the Locale setting)

**Comment by rezaei92** [comment]
Thank you very much
