### ISSUE TITLE
Text editor chooser (plain/html) seem to have stopped working

### ISSUE THREAD

**Issue by tomszilagyi** [the-djmaze/snappymail#143]
**Describe the bug**
After updating my installation from an earlier release (2.6.x) to 2.7, I noticed that the email composer now shows the Html editor despite the preference set to Plain (which was honored before). I tried changing the user preference back and forth, but regardless of the setting, in the composer popup I always get the Html editor. The only difference is that with the options that end in `(forced)`, I do not see the button to switch over to plain (which I guess is the intended behaviour of force).

**To Reproduce**
1. Set user preference General / Default text editor: Plain
2. Click on Compose
3. Observe Html editor

**Expected behavior**
Honor preference as intended.

**Desktop (please complete the following information):**
 - Firefox 78.14.0esr
 - SnappyMail 2.7.0

**Additional context**
I am a bit concerned about my upgrade procedure. I tried to follow available documentation, and things generally seem to be ok, but I noticed that the bottom of my application.ini still reads
```
[version]
current = "2.6.2"
```
which might indicate that some config schema change was not applied? If so, how can I migrate my config?

**Comment by tomszilagyi** [comment]
Update: after sleeping on it (helps with ideas sometimes) I checked two things.

1. I verified that there is no application.ini coming from the archive of the new version, so I did not accidentally inhibit its installation by untarring on the webserver (where the installed file would potentially have permissions to inhibit overwriting it in this manner).
2. I moved the application.ini to a backup, accessed the web admin interface and saw that there is a newly written application.ini with the current version (2.7.0) and a fresh timestamp of being saved. So that is how it works! Then I diffed this with my backup and saw that the only non-trivial change (other than my own customizations of settings) was the addition of the `message_read_delay` site-wide setting.

Summary: I cannot explain the problem reported above with anything foolish I might have done.

**Comment by tomszilagyi** [comment]
One more quirk I noticed (might or might not be related, but I would classify it as 'undesirable'):
In the compose popup, if the email content is empty (e.g., the initial state before having written anything) the Plain/Html switch on the left that looks like `<>` simply does not work. If the body is non-empty, it does work.

**Comment by the-djmaze** [comment]
You are correct, the editor is not loaded any more beforehand (speeds up boot).
But only opening the compose window the first time, it failed the settings.
Opening a second time the issue is gone.

**Comment by tomszilagyi** [comment]
Thank you for the fix!

I tried to test it out by building a tarball from HEAD myself (done this before, so it should work). However, I ran into the (seemingly unrelated) issue that the message list cannot be loaded. User login works, but then "Can't get message list" in red, where the message list should be.

Simultaneously, I see this in the log:
```
[2021-09-13 20:13:26.752][19909448] INFO[NOTICE]: TypeError: Argument 9 passed to MailSo\Mail\MailClient::MessageList() must be of the type int, string given, called in /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/RainLoop/Actions/Messages.php on line 81 and defined in /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/MailSo/Mail/MailClient.php:1569
Stack trace:
#0 /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/RainLoop/Actions/Messages.php(81): MailSo\Mail\MailClient->MessageList()
#1 /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageList()
#2 /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/RainLoop/Service.php(138): RainLoop\ServiceActions->ServiceJson()
#3 /htdocs/snappymail/snappymail/v/2.7.0/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#4 /htdocs/snappymail/snappymail/v/2.7.0/app/handle.php(45): RainLoop\Service::Handle()
#5 /htdocs/snappymail/snappymail/v/2.7.0/include.php(256): include('/htdocs/snappym...')
#6 /htdocs/snappymail/index.php(12): include('/htdocs/snappym...')
#7 {main}
```

A regression perhaps?

**Comment by tomszilagyi** [comment]
By the way, the fix seems to work! (I realized that despite the above trouble, I can still click 'New message' and test...)

**Comment by the-djmaze** [comment]
Your trouble is caused by a bugfix regarding Unique IDentifiers.
According to IMAP they are integers, but RainLoop used strings.
Everywhere i've tried to convert them to integer, but i missed one ;)
