### ISSUE TITLE
Message was sent but not saved to sent items folder

### ISSUE THREAD

**Issue by gnilebein** [the-djmaze/snappymail#1432]
**Describe the bug**
When I send e-mails, they are not stored in the "Sent" folder. I think there is a bug which is related to this change: https://github.com/the-djmaze/snappymail/issues/1404

If you define a "Sent" folder in the identity, they will also be saved there. However, if you have selected "Standard" there, they will not be saved!

I have verified this in two different Nexcloud installations.

**To Reproduce**
1. Create new Mail
2. Send it
3. Check Sent-Folder
4. Mail not visible there

**Expected behavior**
Mails should be placed in Sent folder.

**Please complete the following information:**
- Browser: Chrome & Firefox
- IMAP daemon: Dovecot
- PHP version: 8.2
- SnappyMail Version: Newest
- Mode: Nextcloud

**Comment by mmallejac** [comment]
Having the same one here  !!

**Comment by codiflow** [comment]
Can confirm what @gnilebein mentioned. I have the same issue here which is fatal because the sent mails seem to be gone forever 🙈

Unfortunately I have to roll back as this version does not seem to be production ready with such a bug 😥

**Comment by codiflow** [comment]
A little workaround until a fix is available would be to check the box for "Place replies in the folder of the message being replied to" and move it manually to the Sent folder after being sent. But new messages without a reply are still being moved into the void.

**Comment by gnilebein** [comment]
> A little workaround until a fix is available would be to check the box "Place replies in the folder of the message being replied to" and move it manually to the Sent folder after being sent. But new messages without a reply are still being moved into the void.

I think a better workaround is, to set the folder in your identity. This covers all scenarios.
![2024-02-14 13_46_41](https://github.com/the-djmaze/snappymail/assets/2871059/d37ea5c3-19f3-4722-bb1e-d5e12fd9d680)

**Comment by xpresas** [comment]
Same problem. Current workaround by @gnilebein works.

**Comment by stan2k** [comment]
Same here. The workaround works only in Nextcloud. Without Nextcloud is useless. All the folders are set, available and visible. It is possible to manually copy a message to Sent.  But outgoing messages are not being saved. No errors, no warnings, Snappy just does not attempt to.

**Comment by KuasarCloud** [comment]
hi...is there any way to recover those sent emails, for us it's critical. I can set this parameter globally, I have more than 100 emails to configure identity

**Comment by the-djmaze** [comment]
I will fix this in a few hours.
Stay tuned!

**Comment by KuasarCloud** [comment]
@stan2k did you where able to copy them to sent?

**Comment by stan2k** [comment]
@KuasarCloud I just tried to drag random message form Inbox to Sent. Just to test, whether Sent folder is writable.

**Comment by the-djmaze** [comment]
> I guess the not saved emails by snappymail are lost forever, right?

Correct, for your mailbox.
Recipient does have them though.


As for the bug. Sorry, i didn't notice why it failed.

1. The property `sentFolder` is a KnockoutJS observable.
2. Observables are functions.
3. I added `toJSON` to the observables so that JavaScript can easily use the value inside JSON.

So what actually happened is:
```js
var sentFolder = identity.sentFolder;
if (sentFolder) {
    // Yes we have it defined, but oops it is the function not the value.
}
```
While it should be
```js
var sentFolder = identity.sentFolder(); // now we get the value
if (sentFolder) {
    // Yes we have the right value!
}
```

**Comment by codiflow** [comment]
Thanks for being completely transparent and clarifying what led to the bug 🎉

And also a big thanks for fixing this so fast! Big Thanks! 🙏

**Comment by KuasarCloud** [comment]
@the-djmaze thanks for your help and explaining what happened. When do you expect to have uploaded to download it from Nextcloud.

**Comment by the-djmaze** [comment]
> When do you expect to have uploaded to download it from Nextcloud.

It is submitted to Nextcloud, it could take minutes up till 1 day (i think) but that is a Nextcloud website thing.
So i deleted the snappymail-2.34.0-nextcloud.tar.gz and snappymail-2.34.1-nextcloud.tar.gz from my server to prevent people downloading the bugged versions.

**Comment by KuasarCloud** [comment]
Working well in Nextcloud
