### ISSUE TITLE
Never Stop Loading on Kubuntu 20.04 WebView

### ISSUE THREAD

**Issue by Cqoicebordel** [the-djmaze/snappymail#1436]
**Describe the bug**
Ok, I have a very niche bug, and I know there is virtually no hope to have it fixed. But just in case here I am.  
I'm stuck on Kubuntu 20.04 for reasons. And I use the Webslice plasmoid (that I have developped) (https://store.kde.org/p/998902/). It uses the standard WebEngine, which I believe is Chromium v69 ("QtWebEngine/5.12.4 Chrome/69.0.3497.128").

And there, it doesn't load, it stays stuck on "SnappyMail" with the throbber.  
Note that in the same conditions, Rainloop works without a hiccup.

So, I'm not expecting a fix or anything because, of course, all of this is outdated. But if the fix is just "copy paste the polyfills.js from rainloop that way and it should work", I would take it.  
I also thought the lack of parity with Rainloop would interest some here too.

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/2286246/78277852-651e-4ac5-9d27-e2494f544520)

**Please complete the following information:**
- Browser: QtWebEngine/5.12.4 Chrome/69.0.3497.128
- PHP version: 8.2
- SnappyMail Version: 2.32.0 & 2.34.2
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
I can't attach devtools to that webview, so can't get logs :/

**Comment by the-djmaze** [comment]
JavaScript has evolved a lot since 2018.
There is no way SnappyMail will work.

Best to make an image of your Kubuntu and put that in a virtual machine.
And use a newer OS to run that virtual machine vor your "stuck" needs only.

**Comment by Cqoicebordel** [comment]
I'm stuck because of hardware and lack of money. Your suggestion doesn't help.

Rainloop is working. So the "There is no way SnappyMail will work." is a bit… excessive. Also , six years is not a lot, at all.

Again, I get it's a "won't fix". I just hoped it wouldn't get dismissed that easily.

**Comment by the-djmaze** [comment]
Not really excessive.
The documentation and readme does say why it will not work.

And to get it working, all JavaScript code has to be rewritten.

Lack of hardware mostly means you have a 32 bit machine.
There should be distributions that still support it.

**Comment by Cqoicebordel** [comment]
Hence my possible suggestion that just adding the polyfills.js could help. Because if it's just the lack of some functions in JS that are limiting the compatibility, adding some polyfills may solve it.

That suggestion of changing distribution is useless to me, too. Don't try to fix an issue you don't know anything about.

**Comment by the-djmaze** [comment]
Polyfill.js won't solve it.
It's not just a lack of some functions.
Don't try to fix an issue you don't know anything about.

Just use the old RainLoop

**Comment by Cqoicebordel** [comment]
That's weird, I thought filing a bug on a bugtracker was _exactly_ to fix issues I knew nothing about. My bad.

Thanks for all the help.
