### ISSUE TITLE
Preview for PDF attachments

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#144]
SnappyMail has to possibility to preview attachments (e.g. JPG, PDF, etc.) without the necessity to download the attachment. This is very convenient.

In SnappyMail 2.7.1 the preview of PDF attachments only works, if the content type is set to "application/pdf". Unfortunately many PDF attachments are set to content type "application/octet-stream". This way they are automatically downloaded, when you click on the preview icon (the eye).

The following attachment can be previewed (copy&paste from a real mail):
Content-Type: application/pdf;
 name="xyz.pdf"
Content-Disposition: attachment;
 filename="xyz.pdf"
Content-Transfer-Encoding: base64

The following attachment can not be previewed (copy&paste from a real mail):
Content-Type: application/octet-stream; name="2021-000126634_a.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment

Is it possible to enable SnappyMail to always preview PDF files regardless of the content type?

**Comment by the-djmaze** [comment]
Does this change solve your problem?

**Comment by phsc84** [comment]
I've just manually applied your patch. And yes, this works perfectly!
Thank you very much!
