### ISSUE TITLE
%DATE% and %TIME% in REPLY_MESSAGE_TITLE is not being rendered

### ISSUE THREAD

**Issue by haheap** [the-djmaze/snappymail#1442]
**Describe the bug**
When responding to messages in Danish, the date and time for the original email is not displayed correctly in the quoted part of the email:

English, works fine:
![reply-date-en](https://github.com/the-djmaze/snappymail/assets/48035047/166b9455-188b-41e1-ba81-9988051931fc)

Danish:
![reply-date-da](https://github.com/the-djmaze/snappymail/assets/48035047/2d57e063-62b7-4a02-b1a8-63ac4121f582)

In the language files, %DATE% and %TIME% is being used multiple places and seems to work anywhere except in the REPLY_MESSAGE_TITLE. The working English translation use the %DATETIME% instead.

https://github.com/the-djmaze/snappymail/blob/9f2b2e50d71755caeb422a1554bfe46040267f5e/snappymail/v/0.0.0/app/localization/da-DK/user.json#L226

**Comment by the-djmaze** [comment]
What if you just use %DATETIME%
