### ISSUE TITLE
Always display external images

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#1444]
**Describe the bug**
Not sure if this is a bug or me doing something wrong :)

I would like to (enable the option to) always show external images on some emails. Specifically I would like to do that per sender address.
I searched the code and issues and there is an option for this somewhere and it also involves DKIM signed messages. Now I have a newsletter which has a valid DKIM signature. At least my Spamassassin says DKIM_VALID, but I see no option to always show images even when I click the "Show external images" button.

Before clicking:
![image](https://github.com/the-djmaze/snappymail/assets/4435930/db7b3fbd-a9f5-4eb9-a5e9-b05fe2a86fbb)

After clicking:
![image](https://github.com/the-djmaze/snappymail/assets/4435930/1b6a34b0-6029-46bf-a467-bb2f2cf633ae)

Source:
![image](https://github.com/the-djmaze/snappymail/assets/4435930/89ae6b2f-4066-47f0-b65e-d1a5103b7815)

**To Reproduce**
1. Open an email with external images
2. Click Display external images

**Expected behavior**
A switch or button to always show external images for that email sender.

**Screenshots**
See above.

**Please complete the following information:**
- Firefox 122.0.1 (32-bit)
- IMAP daemon: Dovecot 2.3.13
- PHP version: 8.1.27
- SnappyMail Version: 2.33.0
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Nothing yet.

**Additional context**

**Comment by the-djmaze** [comment]
For DKIM validity it looks at the `Authentication-Results` header.
https://github.com/the-djmaze/snappymail/blob/7ae53719c4cd26bcb835690a954133da37ff728d/snappymail/v/0.0.0/app/libraries/MailSo/Mime/HeaderCollection.php#L179-L225

**Comment by the-djmaze** [comment]
Also see your account settings
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/61ba798f-f656-4f1b-9e5b-73c8fb9ff4a4)

**Comment by ervee** [comment]
Thank you both. It was the per-user "External images" setting that was set to always ask instead of Whitelist or ask!
