### ISSUE TITLE
v2.34.2 to v2.35.0 "Cannot access the repository at the moment."

### ISSUE THREAD

**Issue by minami-o** [the-djmaze/snappymail#1446]
**Describe the bug**
Getting the "Cannot access the repository at the moment." error message while trying to update from the admin About page.
Always worked like a treat with previous versions, but now consistently fails.
Not sure what the upgrade process is, but I think logs suggest the extractor might want to extract to current version folder instead of new one (which does not exist).

**To Reproduce**
1. Go to admin About page
2. Click on the Update button
3. Wait a few seconds

**Expected behavior**
The "Upgrade successful" message should appear and the page should get back to admin login screen

**Screenshots**
Before
![2024-02-22_09-24-36](https://github.com/the-djmaze/snappymail/assets/3458254/33abc6f5-3af1-4f8a-9ab9-68d381982679)
During
![2024-02-22_09-24-44](https://github.com/the-djmaze/snappymail/assets/3458254/f653a3e8-eab5-4949-a6c0-9ea4c993b22a)
After
![2024-02-22_09-24-49](https://github.com/the-djmaze/snappymail/assets/3458254/d1084aac-9550-410c-8a50-668654f8ca0c)

**Please complete the following information:**
- Browser: tried with Firefox 122.0.1 and Chrome 121.0.6167.187 on Windows, Firefox Nightly 125.0a1 on Android
- IMAP daemon: dovecot 2.3.19.1 on Debian bookworm
- PHP version: 8.2.7 with h2o v2.3.0-DEV webserver
- SnappyMail Version: 2.34.2
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[2024-02-22 14:50:57.143][d96939ce] JSON[INFO]: Action: DoAdminUpgradeCore
[2024-02-22 14:50:57.143][d96939ce] POST[INFO]: {"Action":"AdminUpgradeCore"}
[2024-02-22 14:50:59.646][d96939ce] SERVICE[WARNING]: Extraction from phar "/usr/share/snappymail/data/_data_/_default_/c91a3d14d0681219f977e3054ce7a937.tar.gz" failed: Cannot extract "snappymail/v/2.34.2/app/libraries/snappymail/dav/client.php" to "/usr/share/snappymail/snappymail/v/2.34.2/app/libraries/snappymail/dav/client.php", path already exists
#0 /usr/share/snappymail/snappymail/v/2.34.2/app/libraries/snappymail/upgrade.php(220): PharData->extractTo()
#1 /usr/share/snappymail/snappymail/v/2.34.2/app/libraries/RainLoop/ActionsAdmin.php(356): SnappyMail\Upgrade::core()
#2 /usr/share/snappymail/snappymail/v/2.34.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\ActionsAdmin->DoAdminUpgradeCore()
#3 /usr/share/snappymail/snappymail/v/2.34.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 /usr/share/snappymail/snappymail/v/2.34.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /usr/share/snappymail/snappymail/v/2.34.2/include.php(127): RainLoop\Service::Handle()
#6 /usr/share/snappymail/index.php(11): include('/usr/share/snap...')
#7 {main}

**Additional context**
N/A

**Comment by the-djmaze** [comment]
Thanks for reporting. I've resolved this issue.

**Comment by derStephan** [comment]
Perfect, auto update to 2.35.1 worked now for me. Thanks a lot!
