### ISSUE TITLE
Messages are not signed by default although flag is set in settings

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1448]
**Describe the bug**
In the settings the "Sign" option is set but new mails are not automatically being signed.

**To Reproduce**
Set "Sign" in the settings.
Compose new message.
Sign is not set by default.
The same applies for replies.

Logout and login and re-setting "Sign" in settings does not change anything in the behaviour.

**Expected behavior**
Replies and new mails are always being signed if "sign" is set in the settings.

**Screenshots**
Settings:
![image](https://github.com/the-djmaze/snappymail/assets/43847817/c726585b-f523-4fca-9b44-942c1fe86946)

Result when composing a new message:
![image](https://github.com/the-djmaze/snappymail/assets/43847817/3104e834-22bd-4ae8-a6fb-3b9ef272ea0f)

**Please complete the following information:**
- Browser: Firefox 122
- IMAP daemon: -
- PHP version: 8.1
- SnappyMail Version: 2.35.0 (was also an issue with 2.34.2)
- Mode: Standalone

**Additional context**
Maybe this has to do with recent changes in 2.35.0 named "Sign messages using PGP"?

**Comment by the-djmaze** [comment]
Correct. This should already be fixed for next releade, but i will check.
As you can now also set this option per identity.

**Comment by codiflow** [comment]
Great, the identities hint fixed it for me after setting "Sign" there. I forgot that there could also be a settings like this after the recent "identity" overhauls. Thanks!
