### ISSUE TITLE
When two Nexcloud users use the same primary mail

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1449]
I've noticed that when two users are using the same email, their config folder is the same : 

`.../data/appdata_snappymail/_data_/_default_/storage/[domain]/[firstEmail]/`

That leads to some unsolvable issues, for instance using different signatures.

Is snappymail aware og the Nextcloud username ? It could maybe use it.

**Comment by the-djmaze** [comment]
Why should two users use the same mail?
Are they communicating with eachother so they know who replies to which email or send a new one to someone?

**Comment by mmallejac** [comment]
That is a good question ! A few years ago I would have agreed with you, but
we've seen some changes in the mail usage.

For instance a film festival. Their team is splitted between permanent
people, who do have a nominative mail address, and temporary ones who often
come for one edition, who use non nominative addresses, like organisation@
press@ hospitality@ and so on.
Most of these teams are made of two to three people and they share the same
mail address.

Other than that, we have more and more companies who prefer to use function
mail addresses instead of nominative ones :

   - especially if there is a high turnover, like for low-level, entry
   positions (helpdesk@ customerservice@ ...)
   - they keep the history throughout the different people who successively
   do this job
   - no legal issues : here in Switzerland the content of a nominative mail
   address cannot be read by the employer without the person agreement

For sure two or three people sharing the same mailbox have to be well
organized, but it is quite easy to do with some simple rules (an inbox
subfolder for each of the users is usually sufficient).

Finally in my own company we three share the "support@" mail address (but
we do also have nominative addresses).

Hope this helps !
Michel

**Comment by the-djmaze** [comment]
What is the problem with ACL?

Say you have temporaryuser1@company.tld

```
AUTHENTICATE support@company.tld
SETACL INBOX temporaryuser1@company.tld lrwstipekxacd
```

Now temporaryuser1 has access to support

**Comment by the-djmaze** [comment]
See the `shared` namespace spart in the demo
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/878d98f7-5f21-4a5e-8f20-ab684ed0b003)

**Comment by the-djmaze** [comment]
Also, this is not a Nextcloud issue.
If you use SnappyMail standalone, then it is the same inconvenience.

**Comment by mmallejac** [comment]
Signatures ! They all have different signature files (and why not other
settings).
I was not aware of ACL, I will study that

With regards to Nextcloud, I was wondering if you have access to the user
name, because if so it could be added to the setting path and that would
solve the issue, I believe.

**Comment by the-djmaze** [comment]
ACL is just a simple example.
You could also make shares in your IMAP as admin.
See for Dovecot https://doc.dovecot.org/configuration_manual/shared_mailboxes/



ACL is just a simple example.
You could also make shares in your IMAP as admin.
See for Dovecot https://doc.dovecot.org/configuration_manual/shared_mailboxes/


> With regards to Nextcloud, I was wondering if you have access to the user name, because if so it could be added to the setting path and that would solve the issue, I believe.

This is possible with a custom storage driver.
The demo extension has one that could be used as an example.
https://github.com/the-djmaze/snappymail/tree/master/plugins/demo-account

**Comment by mmallejac** [comment]
Thanks, I'll look into it.
Would it be ok to let this open a little bit, just to see what other people
might think ?

**Comment by the-djmaze** [comment]
Sure.

And here is an example of NextcloudStorage: https://github.com/the-djmaze/snappymail/blob/master/plugins/nextcloud/storage.php
