### ISSUE TITLE
S/MIME encrypted and opaque signed not visible

### ISSUE THREAD

**Issue by pepemadalena** [the-djmaze/snappymail#1450]
**Describe the bug**
I'm using Nextcloud and I've seen that Snappymail in its version 2.35 has implemented S/MIME encryption, but when trying to load the certificates from Snappymail settings, it does not allow them to be incorporated.

**To Reproduce**
1. Go to 'Setup' in app Snappymail
2. Click on 'Security'
3. Scroll down to 'S/MIME Certificates'

**Screenshots**
<img width="385" alt="image" src="https://github.com/the-djmaze/snappymail/assets/131311479/0455cf17-1ba4-4fb9-85a1-46c1dfc9ed67">

Thanks

**Comment by the-djmaze** [comment]
Correct. Next release will have an import button.

**Comment by pepemadalena** [comment]
Hi,
Decryption still does not work; it only allows the import of the public certificate and does not permit the import of the private key.
Thanks

**Comment by the-djmaze** [comment]
Correct. Your private key should go in Settings -> Accounts -> Identity (the key belongs to)

**Comment by pepemadalena** [comment]
Hi,
Thank you very much for the prompt response.
I have put the private key and the certificate in the identity,
![image](https://github.com/the-djmaze/snappymail/assets/131311479/cbe5e12a-c50c-4e58-bbb0-712465290ae5)

 and it still does not decrypt the email.
![image](https://github.com/the-djmaze/snappymail/assets/131311479/9be23109-86e6-4aa6-b0da-426d9e462183)

![image](https://github.com/the-djmaze/snappymail/assets/131311479/ac967839-e1f6-40d4-9b29-4ff4b9e1fc15)

It does not show the content of the message.

Thanks

**Comment by the-djmaze** [comment]
You did it wrong.
It should be PEM format.

I will modify the screen to prevent invalid data.

**Comment by the-djmaze** [comment]
Can you forward the message to me at issue1450@snappymail.eu ?
Maybe i can figure out what is wrong

**Comment by the-djmaze** [comment]
The message did decrypt as the bar is green.
Can you open your browser developer toolbar and then the `network` tab.
Then decrypt the message and see the request and response.

Screenshot is in dutch, but you get the idea:
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/3ecbec49-96ca-4564-83d2-21983345c723)

**Comment by the-djmaze** [comment]
Thanks for the email. I've figured out what the problem is.
Will make a solution for it.

**Comment by the-djmaze** [comment]
Could you email me the decrypt json response?
Looks like the base64 decode fails.

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/e23a240b-f609-4786-a74f-496ae3f21475)

**Comment by pepemadalena** [comment]
Hi, 
After updating to version 2.36.1 of Snappymail in Nextcloud, the email has been decrypted perfectly. 
Thank you very much.
