### ISSUE TITLE
Error 352 when getting Filters

### ISSUE THREAD

**Issue by jhd85** [the-djmaze/snappymail#1455]
**Describe the bug**
I configured a sieve server in SnappyMail to be able to create and manage filter for mail. But opening the Filters section gives me a error:

**To Reproduce**
1. In snappymail 
2. Go to 'Settings' 
3. Go to 'Filters' 
4. receive 'ERROR 352'.

**Expected behavior**
Getting a overview of my current filters

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/61521044/54c61c5d-dfa8-4afb-8ca5-24ae3b00e622)

**Please complete the following information:**
- Browser: firefox 123
- IMAP daemon: https://stalw.art
- PHP version: 8.2.15
- SnappyMail Version: 2.35.0
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)
```
SIEVE[INFO]: > GETSCRIPT "roundcube"\r\n
SIEVE[INFO]: < {335}\r\n
SIEVE[INFO]: < require ["fileinto"];\r\n
# rule:[myrule]\r\n
if allof (header :contains "to" "info@redacted.nu")\r\n
{\r\n
        fileinto "myrule";\r\n
}\r\n
# rule:[paypal]\r\n
if allof (header :contains "to" "paypal@redacted.nu")\r\n
{\r\n
        fileinto "Diensten";\r\n
        stop;\r\n
}\r\n
# rule:[steam]\r\n
if allof (header :contains "to" "steam@redacted.nu")\r\n
{\r\n
        fileinto "Games";\r\n
        stop;\r\n
}\r\n
SIEVE[INFO]: < OK\r\n
SIEVE[INFO]: > LOGOUT\r\n
SIEVE[INFO]: < BYE "Stalwart ManageSieve v0.6.0 bids you farewell."\r\n
SIEVE[ERROR]: MailSo\Net\Exceptions\SocketReadException in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.35.0/app/libraries/MailSo/Net/NetClient.php:275
```

**Additional context**
- I also tried the sieve server with roundcube and that works without issue
- Adding filter seems to work (if you just ignore the errors) but can't select capabilities and it still can't get filters afterwards
- I (have to) use short logins for everything (imap, smtp and sieve), so user@domain.com -> user. But can't select this in the admin panel for snappymail for sieve. Only for imap and smtp. But seeing the logging it looks like getting the data from the server works fine.

**Comment by mdecimus** [comment]
> The server MUST reply with an OK response.

That is incorrect, you are quoting the example. According to the ManageSieve grammar, both `OK, `NO` and `BYE` is a valid responses for the `LOGOUT` command:

```txt
    response-logout       = response-oknobye
    response-oknobye    = response-ok / response-nobye
    response-nobye        = ("NO" / "BYE") [SP "(" resp-code ")"]
                            [SP string] CRLF
                            ;; The string contains human-readable text
                            ;; encoded as UTF-8.
```

**Comment by m-i-k-e-y** [comment]
The RFC states above the example:

```
   The server MUST reply with an  OK response.  The server MUST ignore commands issued by the client
   after the LOGOUT command.

   The client SHOULD wait for the OK response before closing the
   connection.
```

So @the-djmaze is correct.

**Comment by the-djmaze** [comment]
@m-i-k-e-y we both are right.
The problem relies in the RFC.
Probably the grammar part is copy/paste from IMAP RFC where BYE is used.
https://datatracker.ietf.org/doc/html/rfc3501#section-3.4

**Comment by mdecimus** [comment]
I agree, there is a "bug" in the RFC. I will have this fixed to use the same response as Pigeonhole since this is what most software was tested against.

However, even if the server is crashing, I think SnappyMail should follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) and not fail on unexpected responses for non-critical commands.

**Comment by the-djmaze** [comment]
> However, even if the server is crashing, I think SnappyMail should follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) and not fail on unexpected responses for non-critical commands.

True, that's why i made a workaround to not crash on BYE.
Although itbis a server hang-up of the connection for whatever reason.

I did make a mistake in IMAP with that, because it does have an untagged BYE followed with a tagged OK.

**Comment by mdecimus** [comment]
Stalwart has now been [updated](https://github.com/stalwartlabs/mail-server/commit/d94a6a2ec6d5f3b07d9e7868fb5f7bc6007e481c) to return `OK` instead of `BYE`. I also submitted an errata to IETF:

```txt
The following errata report has been submitted for RFC5804,
"A Protocol for Remotely Managing Sieve Scripts".

--------------------------------------
You may review the report below and at:
https://www.rfc-editor.org/errata/eid7825

--------------------------------------
Type: Editorial

Section: 4

Original Text
-------------
response-logout       = response-oknobye


Corrected Text
--------------
response-logout       = response-ok


Notes
-----
The client sends the LOGOUT command when it is finished with a
  connection and wishes to terminate it.  The server MUST reply with an
  OK response.  The server MUST ignore commands issued by the client
  after the LOGOUT command.

Instructions:
-------------
This erratum is currently posted as "Reported". (If it is spam, it 
will be removed shortly by the RFC Production Center.) Please
use "Reply All" to discuss whether it should be verified or
rejected. When a decision is reached, the verifying party  
will log in to change the status and edit the report, if necessary.

--------------------------------------
RFC5804 (draft-ietf-sieve-managesieve-09)
--------------------------------------
Title               : A Protocol for Remotely Managing Sieve Scripts
Publication Date    : July 2010
Author(s)           : A. Melnikov, Ed., T. Martin
Category            : PROPOSED STANDARD
Source              : Sieve Mail Filtering Language
Area                : Applications
Stream              : IETF
Verifying Party     : IESG

```

**Comment by f0rc3r** [comment]
Updates to the newest Release 2.35.2 and still get Error 352

**Comment by europacafe** [comment]
I'm not sure this issue has been solved, but I still get such 352 error with 2.22-2.24.0.
(latest Stalwart mail server)

**Comment by the-djmaze** [comment]
Without the proper logs, this issue is at Stalwart

**Comment by europacafe** [comment]
I had the same issue with Stalwart mailserver.
On snappymail, the sieve server setting must use only ss/ltls to make it work. Starttls doesn't work. I don't know why.

**Comment by f0rc3r** [comment]
I got the same issue with Docker Mailserver.

Error 352

**Comment by the-djmaze** [comment]
@f0rc3r starttls fails, so your Sieve is not using secure connections.

**Comment by f0rc3r** [comment]
Thats right. I set it up without a secure Connection. At the Adminpanel under Domain its okay If i set up and Test it. 

When i try to to Open it i got the Error. I worked in older Versionen very well. I guess it stopped working after 2.33.

**Comment by f0rc3r** [comment]
![image](https://github.com/user-attachments/assets/e2b3e2ff-f7ac-41b2-8f0d-e5cf083a4ba3)

**Comment by the-djmaze** [comment]
Hmmm, maybe a change of the code to force STARTTLS when server announces it, could be an issue.
Will check if that happens.

**Comment by f0rc3r** [comment]
Thank you.

**Comment by europacafe** [comment]
> I had the same issue with Stalwart mailserver. On snappymail, the sieve server setting must use only ss/ltls to make it work. Starttls doesn't work. I don't know why.

Has this been resolved?
