### ISSUE TITLE
SetPassword(): Argument #1 must be of type SensitiveString, string given

### ISSUE THREAD

**Issue by slavafomin** [the-djmaze/snappymail#1456]
Hello!

**Describe the bug**
When trying to enable the Nextcloud App, error occurred:

```
Exception: RainLoop\Config\Application::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in /var/snap/nextcloud/40228/nextcloud/extra-apps/snappymail/lib/Migration/InstallStep.php on line 75 in file '/var/snap/nextcloud/40228/nextcloud/extra-apps/snappymail/app/snappymail/v/2.35.1/app/libraries/RainLoop/Config/Application.php' line 123
```

**Please complete the following information:**
- Browser: Chromium 122.0.6261.69 (Official Build) snap (64-bit)
- IMAP daemon: ?
- PHP version: ?
- SnappyMail Version: latest?
- Mode: nextcloud
- [Nextcloud Hub 6](https://nextcloud.com/) (27.1.6) (snap)

I will be glad to provide any additional information if required.

Thank you.

**Comment by slavafomin** [comment]
Thanks for a quick fix, but what are the estimates for release?

**Comment by the-djmaze** [comment]
> what are the estimates for release?

Depends on the amount of beer i've got :rofl:

**Comment by asferreira** [comment]
Interesting... I'm having a similar error after a fresh install (standalone). In my case, the error is:

`RainLoop\Config\Application::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in /opt/www/root/snappymail/v/2.35.2/app/libraries/RainLoop/Actions.php on line 671`

I'm installing the 2.35.2 version with PHP 8.1
