### ISSUE TITLE
"Search/Unseen" checkbox misplaced above folder list?

### ISSUE THREAD

**Issue by ner00** [the-djmaze/snappymail#1459]
This seems like a bug to me, especially since checking the box hides the entire folder tree list below.

![image](https://github.com/the-djmaze/snappymail/assets/2269603/d43af5a1-e98a-4114-abff-216ad604971e)

**Comment by the-djmaze** [comment]
When there are no unseen/unread messages all folders are invisible.
But... when there are unseen/unread messages in a folder, only that folder is visible (and its parents).

**Comment by ner00** [comment]
Ok, gotcha. Indeed, the color could be changed to something clearer.
