### ISSUE TITLE
Improper mouse cursor being used

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#146]
When I hover over the message list, an arrow with a plus in the upper right-hand corner is shown instead of a hand with the second finger pointing up.

**Comment by the-djmaze** [comment]
Is your keyboard broken?
That cursor should appear when the [Ctrl] key is pressed down and the list is in "copy" mode.

**Comment by Zero3K** [comment]
You were right. Somehow my Ctrl key got stuck.
