### ISSUE TITLE
Dark mode slightly broken

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1463]
With the latest 2.35.2 the folder list on the left appears looks strange. 
Using Nextcloud V25+ theme.
The problem is only with dark mode.

See:
![image](https://github.com/the-djmaze/snappymail/assets/11666281/a14b417a-5659-4d4e-9529-04bec508b103)

**Comment by PeopleInside** [comment]
The fix in style.css seems is never working for me.

**Comment by ner00** [comment]
I'm not a fan of doxxing, could we get the personal information removed from https://github.com/S-A-L13/snappymail/commit/876ed221c3813b641850683491798c4935b72ec3 ?

That's be fucking great.
