### ISSUE TITLE
About sign_me_auto

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1464]
This is more a question, not a bug.

Could you please let us know more about sign_me_auto and its different values ?

We use Snappymail along with Nextcloud. 

Most of the time all users can access Snappymail without issues, as long as the initial set up is done.
Sometime on the other hand, the mail / password of the primary address gets lost, not really sure why.

Could this parameter be of some help ?

Thanks in advance !

**Comment by the-djmaze** [comment]
sign_me_auto is an option used on the login page.
When none is known the "remember me" checkbox has one of the 3 states.
- `DefaultOn` = checked
- `DefaultOff` = unchecked
- `Unused` = checkbox is not available

**Comment by mmallejac** [comment]
Thanks a lot.

What about in the context of Nextcloud integration ? 
I'd say it is useless since you provide this :
![image](https://github.com/the-djmaze/snappymail/assets/11666281/28346db3-5802-4998-8a4b-a16e454a862a)
I am right ?

By the way, I see that these two things are stored within Nextcloud:
- `occ user:setting user snappymail snappymail-email user@example.com`
- `occ user:setting user snappymail snappymail-password "mail password"`

How do you hash the password before being stored ? (if we want to set these settings by script)

**Comment by the-djmaze** [comment]
You are right.

To set the password yourself is tricky. It requires you to load SnappyMail as API and do tricky things.

**Comment by mmallejac** [comment]
Really ? 
Running these two `occ` commands (+ hashing password) wouldn't be enough ?

**Comment by the-djmaze** [comment]
Correct, it is not hashed. It is encrypted

**Comment by mmallejac** [comment]
Ok, I got it.

It would have been great to be able to set up a user by script. 
Quite often they don't know their mail password, and we store it within our user management tool (Keycloak), so it would have been quite easy to do !

**Comment by the-djmaze** [comment]
Then you can create a PHP script that does that
