### ISSUE TITLE
DKIM in phpmail

### ISSUE THREAD

**Issue by pwrsource** [the-djmaze/snappymail#1468]
**Is your feature request related to a problem? Please describe.**
When using phpmail beta option, messages do not send despite dkim being set in the mailserver.

**Describe the solution you'd like**
Add dkim settings into the snappymail admin page.

**Describe alternatives you've considered**
Tried using S/MIME option in snappymail without success.

**Additional context**
Below is a link to phpmail code using dkim:
https://stackoverflow.com/questions/24463425/send-mail-in-phpmailer-using-dkim-keys
https://stackoverflow.com/questions/8705035/how-to-send-email-with-phpmailer-with-dkim-signature

**Comment by the-djmaze** [comment]
It is not using phpmailer.
It uses https://www.php.net/mail

**Comment by pwrsource** [comment]
Hi the-djmaze,
It looks like DKIM appears in the link you shared: https://www.php.net/mail

**Comment by the-djmaze** [comment]
But DKIM should be handled by your SMTPD.
