### ISSUE TITLE
A new return line is added when switching from plain text editor to HTML editor

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1469]
**Describe the bug**

In plain text editor, write :

```
Line 1

Line 2


Line 3
```

Switch to HTML editor and observe you now have : 

```
Line 1


Line 2



Line 3
```

Expected in HTML editor : 

```
Line 1

Line 2


Line 3
```

**Please complete the following information:**
- Browser: Firefox 123.0
- PHP version: 7.4
- SnappyMail Version: 2.35.1
- Mode: standalone

**Comment by floss4good** [comment]
Duplicate of #1389.

**Comment by Massedil** [comment]
> Duplicate of #1389.

Thanks, so I close this issue.
