### ISSUE TITLE
Read Receipts Reference Main Account Email, Not Identities

### ISSUE THREAD

**Issue by electroflame** [the-djmaze/snappymail#147]
**Describe the bug**
When using read receipts and/or delivery receipts, the Disposition-Notification-To and X-Confirm-Reading-To headers use the main account email instead of the designated identity.  Not only is this confusing to the recipient to see a different email in the read receipt request, it exposes the mail account email (which, if you're using an identity, is likely undesirable).

**To Reproduce**
1. Compose mail and select read receipt and/or delivery receipt.
2. Send mail to some other email account you can view.
3. Verify headers, or check the read receipt notification popup.

**Expected behavior**
The sender account identity should be used for both headers instead, to maintain consistency (not confuse the sender), and to preserve privacy.

**Additional context**
This seems to be a long-standing issue with Rainloop, as when I was researching this I found references as far back as 2016.  As far as I can tell, there isn't a legitimate reason for this to happen, so I think it's a bug, not a feature. :wink:

**Comment by the-djmaze** [comment]
Does the above change resolve your issue?

**Comment by electroflame** [comment]
I just updated that line in my install and it seems to have done the trick, thanks!

Additionally, it might be a nice UI improvement to not have the extra hamburger menu automatically close when a checkbox is clicked.  If you want to click more than one box you end up having to open the hamburger menu multiple times.

However this issue seems fixed.  If you want to pursue the additional UI improvement I can open a separate issue for it, if you'd rather have a record of it.

Thanks for the quick commit!

**Comment by the-djmaze** [comment]
Great it solved it.

Problem with the menu closing is that it is based on the old default "registerBootstrapDropdown".
Bootstrap has a feature to always close a menu when you click somewhere (inside and outside the menu).
You could report it as separate issue, but changing/solving it would require important changes.
