### ISSUE TITLE
[Cosmetic] Remove the horizontal scroll bar for squire-toolbar menu

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1470]
**Describe the bug**

**1/2**

There is a horizontal scroll bar with the `<div class="squire-toolbar btn-toolbar">` element.

There is a lot of space around to increase the width of `V-PopupsCompose` now limited to `max-width: 1000px;`.

I tried `max-width: 1200px;`  and it seems fine ; there is no scroll problem anymore.

**2/2**

Also, is it possible to adjust elements with class `btn` to make them grow to occupy all the space available horizontally ?

**Please complete the following information:**
- Browser: Firefox 123.0
- PHP version: 7.4
- SnappyMail Version: 2.35.1
- Mode: standalone

**Comment by the-djmaze** [comment]
> There is a lot of space around to increase the width of `V-PopupsCompose`

Not on all screens.
But feel free to create an extension that does what you want.

**Comment by the-djmaze** [comment]
You could also install the "Compact Composer" extension of Sergey Mosin #1466
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/93127202-b956-4691-807f-7c4e06b39a7f)
