### ISSUE TITLE
Popup to compose a new message is so high that it prevent Firefox Screenshot and other extensions to works

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1471]
**Describe the bug**

Try to make a screenshot with the Firefox Screenshot right click menu. You can't select the new message component because it is on top of the Firefox Screenshot interface. 

I also see this problem with Grammalecte extension : their screen are displayed behind the new message component .

I tried to disable the `z-index` to see if this is the problem, but it is not that. Maybe because it is in a `<Dialog>` component ?

**Please complete the following information:**
- Browser: Firefox 123.0
- PHP version: 7.4
- SnappyMail Version: 2.35.1
- Mode: standalone

**Comment by the-djmaze** [comment]
Not possible. Use external screenshot application.
Printscreen on keyboard just works.

**Comment by Massedil** [comment]
> Not possible.

You can see on this screenshot that Firefox Screenshot is behind the snappymail new compose windows :

![image](https://github.com/the-djmaze/snappymail/assets/20357783/b86f04f8-fae8-4fe3-b47b-24718f301ec3)
