### ISSUE TITLE
"SetPassword(): Argument #1 must be of type SensitiveString, string given" error while accessing admin page

### ISSUE THREAD

**Issue by asferreira** [the-djmaze/snappymail#1472]
**Describe the bug**
After a fresh install I'm getting  the following error when trying to access the ?admin page:
"An error occurred.
Please refresh the page and try again.
Network response error: 500"

Further investigation has shown that the error occurs due to a type mismatch relate to SnappyMail\SensitiveString

RainLoop\Config\Application::SetPassword(): Argument 1 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in /opt/www/root/snappymail/v/2.35.2/app/libraries/RainLoop/Actions.php on line 671

**Please complete the following information:**
- Browser: Firefox 123.0
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.35.2
- Mode:  standalone

**Comment by the-djmaze** [comment]
Solved yesterday https://github.com/the-djmaze/snappymail/commit/d84f39be865de7017c18e927c56ceaf67fa035b2
