### ISSUE TITLE
Possibility to change the check mail interval by default.

### ISSUE THREAD

**Issue by carlosdmendez** [the-djmaze/snappymail#1477]
**Is your request related to a problem? Please describe it.**
I have not found an option to tell the system what the default check interval for new emails should be, and the default number "15" seems too high to me.

**Describe the solution you would like**
Enable an option to change the default check mail interval.

**Comment by the-djmaze** [comment]
15 minutes is not too high.
In your account settings you can change it.

**Comment by randolf** [comment]
As I recall, many eMail client applications default to 5 minutes, and smartphones do the same, so I think 15 minutes is a pretty long time.

**Comment by the-djmaze** [comment]
But many email clients have a direct (open logged in) connection with IMAP server.
SnappyMail does not. It requires: HTTP -> HTTP Server -> IMAP server -> LOGIN -> fetch

You can't compare 2 worlds. You should compare Roundcube with SnappyMail for this setting.

**Comment by carlosdmendez** [comment]
I also consider that it should be 5 minutes. 

I know I can change the interval time in the account settings, but that is not what I want. 

What I am looking for is an option that allows me to set the default interval time for all accounts.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/blob/e07749be6a8168268dcda2304115dc41a040bcdc/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Accounts.php#L211

Can be overridden with a custom extension.

For example see the Demo extension
https://github.com/the-djmaze/snappymail/tree/master/plugins/demo-account
It has two ways for modifying:
1. AfterAccountsAndIdentities (always overrides)
2. Custom Storage engine that sets the defaults https://github.com/the-djmaze/snappymail/blob/e07749be6a8168268dcda2304115dc41a040bcdc/plugins/demo-account/storage.php#L39-L41

**Comment by carlosdmendez** [comment]
Thanks!
