### ISSUE TITLE
Authentication Failed - Nextcloud @ Latest

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#1478]
**Describe the bug**
IMAP and SMTP tests succeed with provided credentials but fail when adding additional accounts inside snappymail UI

**To Reproduce**
1. Go to the admin panel
2. Add a new domain
3. Test the domain settings using valid credentials
4. Observe success
5. Navigate to snappymail user account
6. Select "Add Account"
7. Attempt to login with same credentials as step 3
8. Observe "Authentication Failed"

**Expected behavior**
I should be able to login to the additional account.

**Screenshots**
![https://cdn.thecutefoxxy.com/6R1BSQ.png](https://cdn.thecutefoxxy.com/6R1BSQ.png)
![https://cdn.thecutefoxxy.com/7USGqJ.png](https://cdn.thecutefoxxy.com/7USGqJ.png)
![https://cdn.thecutefoxxy.com/vivdAc.png](https://cdn.thecutefoxxy.com/vivdAc.png)

**Please complete the following information:**
- Browser: Firefox 123.0
- IMAP daemon: Unknown
- PHP version: 8.1.27
- SnappyMail Version: 2.35.2
- Mode: Nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
_I enabled JavaScript logging but its not giving me any error logs, just basic info about loaded modules_

{"Action":"AccountSetup","Result":false,"ErrorCode":102,"ErrorMessage":"AuthError[102]","ErrorMessageAdditional":"","ExceptionCode":0,"epoch":1709481948}

**Additional context**
I just updated my Snappymail to 2.35.2

**Comment by the-djmaze** [comment]
You need the server side log to find out why it fails.

**Comment by TheCuteFoxxy** [comment]
> You need the server side log to find out why it fails.

How can I get those in nextcloud snappymail? There isn't a data directory for snappymail, and if I set the logs path, nothing ever writes (even if I 777 the directory).

**Comment by the-djmaze** [comment]
It's in `nextcloud/data/appdata_snappymail/_data_/_default_/logs`

**Comment by TheCuteFoxxy** [comment]
> It's in your `data/appdata_snappymail/_data_/_default_/logs`

https://hastebin.com/share/razayetenu.txt

**Comment by the-djmaze** [comment]
WhiteListPlugin->FilterLoginCredentials
