### ISSUE TITLE
New installation, get error when accessing ?admin

### ISSUE THREAD

**Issue by lister1308** [the-djmaze/snappymail#1482]
Installed the latest release on fedora 38 server, apache as webserver. I have rainloop installed and working on the same server. When accessing the ?admin portal first time for configuration I get the error: _An error occurred. Please refresh the page and try again. Network response error: 500_. Accessing the URL without the ?admin gives me the login box, but because I could not configure anything, cannot log in.

- Tried different browsers (chrome / safari), used incognito browsing, but still does not work.
- dovecot running on another server, but since i did not configure anything, this server is not accessed
- php 8.2.16
- snappymail 2.35.2
- running standalone

Tried running it in apache from a suburl  (https://myserver.nl/webmail), from the root (https://myserver.nl) and also directly to ip adres of server in the default website, always the same result. Everytime I access the URL, a admin password is generated ./data/_data_/_default_/admin_password.txt, that works. When I enter a dummy string in application.ini after admin_password =, the login box appears, but since the password in the application.ini should be encrypted (i think), i cannot login.

Don't know if it is a bug I am running into or doing something wrong, tried everything I could think of, googled for similar problems, but no result, any suggestions? Posted it here on github. If I should post this anywhere else, let me know.

**Comment by the-djmaze** [comment]
Correct, this will be fixed in next release.

Duplicate of #1472

**Comment by lister1308** [comment]
Ok, thnx, wil wait for this release.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.35.3

**Comment by lister1308** [comment]
Yep, this resolved the problem I had, thnx.
