### ISSUE TITLE
Enabling "Attempt to automatically login with email" results in error

### ISSUE THREAD

**Issue by botsarenthuman** [the-djmaze/snappymail#1483]
**Describe the bug**
When we try to login using snappymail, we get a JS error

**To Reproduce**
In the admin, enable 
`Attempt to automatically login users with their Nextcloud email and password, or user-defined credentials, if set.`
**Expected behavior**
The login is attempted and succeeds or fails
**Screenshots**
![Screenshot 2024-03-09 at 10 20 50 AM](https://github.com/the-djmaze/snappymail/assets/93811503/666d1db2-1a12-481d-81b8-ee7df09f4f48)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: 2.35.2
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

Login will actually succeed if we switch the users to manual login.
I'm guessing that the NC integration is broken somehow since I did manage to track the error down to a minified file which makes a call to the NC API but that call fails. Maybe in one of the recent PRs, the NC integration was busted?

**Comment by botsarenthuman** [comment]
I tracked it down to this commit https://github.com/the-djmaze/snappymail/commit/d832117ae427f797a4ede9e845e481bc747c72aa

If I replace my local file with the contents of
https://raw.githubusercontent.com/the-djmaze/snappymail/bac6c2d3329e24806565bf1efc9ec7be808d2229/integrations/nextcloud/snappymail/lib/Util/SnappyMailHelper.php

The error goes away.

**Comment by the-djmaze** [comment]
Can you check logs and browser debug console what the actual error is?

**Comment by botsarenthuman** [comment]
The actual error is I think right before that error, it calls an API endpoint to get more info about the user (profile info), and that blows up thanks to changes in https://raw.githubusercontent.com/the-djmaze/snappymail/bac6c2d3329e24806565bf1efc9ec7be808d2229/integrations/nextcloud/snappymail/lib/Util/SnappyMailHelper.php somewhere. 

I'll try to look later tonight.

**Comment by botsarenthuman** [comment]
This was fixed [here](https://github.com/the-djmaze/snappymail/commit/18a859c68f9c9482745dcb8f3b2aee84425714ef#diff-15eda2b58aeb3f1ac931978e292e2c5db68849b02137566290e809b90a112195R208), thanks!

**Comment by the-djmaze** [comment]
Great 👍
