### ISSUE TITLE
The SCRAM additions override plugin auth providers

### ISSUE THREAD

**Issue by botsarenthuman** [the-djmaze/snappymail#1485]
If in a plugin, I use a php arrayshift, like this:

```php
                if(!empty($access_token)){
                        $oSettings->Password = $access_token;
                        \array_unshift($oSettings->SASLMechanisms, 'OAUTHBEARER');
                }
```

The recent SCRAM feature overrides that.

**Comment by Neustradamus** [comment]
Thanks @botsarenthuman for this ticket and @the-djmaze for the fix!
- https://github.com/the-djmaze/snappymail/pull/1484

**Comment by Neustradamus** [comment]
Thanks @botsarenthuman for this ticket/fix and @the-djmaze for the merging!
- https://github.com/the-djmaze/snappymail/pull/1484
