### ISSUE TITLE
Unreadable text on dark background

### ISSUE THREAD

**Issue by Juma7C9** [the-djmaze/snappymail#1486]
**Describe the bug**
Using a theme with a dark background, a rich-text email with the text color explicitly set to black and no background color set (which seems to be the default on mails sent from Outlook) is unreadable unless the option to remove the text and background colors is selected.

**To Reproduce**
1. On snappymail set a dark theme and check that the `Remove background and text colors from message body` option is unchecked;
2. Open Outlook's webmail and check that the plaint-text option is not enabled;
3. Compose and send an email with some arbitrary text;
4. On snappymail open the received message;
5. Only the non-black portions of the text are clearly visible, while the black text is visible only when selected.

**Expected behavior**
The text in the received message should be visible, even if the text and reader background color are nearly the same.

**Screenshots**

![Sample message](https://github.com/the-djmaze/snappymail/assets/5333677/a9d97a81-cc85-45fd-aab3-75bbdf592630)
![Same message with the black text selected](https://github.com/the-djmaze/snappymail/assets/5333677/4e8cf190-1ce6-4a77-95b1-be5345e973af)

**Please complete the following information:**
- Browser: Firefox 123.0.1
- SnappyMail Version: 2.35.2 on Nextcloud 28.0.3

**Additional context**

Message source:
```
--_000_MW4PR84MB1418242A1C4C8F6D6C1F060FB7252MW4PR84MB1418NAMP_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

black text
red text

--_000_MW4PR84MB1418242A1C4C8F6D6C1F060FB7252MW4PR84MB1418NAMP_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<style type=3D"text/css" style=3D"display:none;"> P {margin-top:0;margin-bo=
ttom:0;} </style>
</head>
<body dir=3D"ltr">
<div class=3D"elementToProof"><span style=3D"font-family: Aptos, Aptos_Embe=
ddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 1=
2pt; color: rgb(0, 0, 0);">black text</span></div>
<div class=3D"elementToProof"><span style=3D"font-family: Aptos, Aptos_Embe=
ddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 1=
2pt; color: rgb(237, 92, 87);">red text</span></div>
</body>
</html>

--_000_MW4PR84MB1418242A1C4C8F6D6C1F060FB7252MW4PR84MB1418NAMP_--
```

**Comment by the-djmaze** [comment]
You should report the bug to Outlook, not in here.
The option to remove colors works great.

**Comment by Juma7C9** [comment]
I'm not sure how other clients manage this situation, but could it be a good idea to add an option to have a white background for the viewer, regardless of the theme -- at least for rich-text messages?

**Comment by the-djmaze** [comment]
> could it be a good idea to add an option to have a white background for the viewer

Now that is an idea :wink:
