### ISSUE TITLE
v2.35.2 BUG Theme Nextcloud V25+ in dark mode

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1488]
As for this bug https://github.com/the-djmaze/snappymail/issues/1487
the issue is not resolved. The DarkMode still be broken on the Nextcloud V25+ even if I download and replace the file styles.css
https://github.com/the-djmaze/snappymail/blob/593fd4c41d2f21f0de852436ce96f9970744dce8/snappymail/v/0.0.0/themes/NextcloudV25%2B/styles.css

**Comment by the-djmaze** [comment]
It is resolved. It's just not how you tried to solve it.

**Comment by PeopleInside** [comment]
How can resolve the issue please?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.35.3

**Comment by PeopleInside** [comment]
Thank you, this works.
