### ISSUE TITLE
Nextcloud Update SnappyMail 2.35.3 Login- An error occurred.

### ISSUE THREAD

**Issue by wo88888** [the-djmaze/snappymail#1493]
Hello,

after Nextcloud Update SnappyMail 2.35.3 i get the following error when i go to Nextcloud App SnappyMail, SnappyMail don't start:

**_An error occurred.
Please refresh the page and try again.TypeError: (intermediate value).toLowerCase is not a function_**

When i save the login in additional settings the app starts without an error.

Thank you for your help!

W

**Comment by the-djmaze** [comment]
Duplicate of #1491

**Comment by wo88888** [comment]
Thank you very much to solute the problem.

Thank you for solving the problem.
What security do you use when I save the password in Nextcloud in additional settings?

**Comment by the-djmaze** [comment]
Sodium, ooenssl or xxtea, depending on what your PHP supports.

**Comment by wo88888** [comment]
How is the password stored in encrypted form?
Thank you!

**Comment by the-djmaze** [comment]
`[type, iv/nonce/salt, Encrypt(json_encode(password), iv/nonce/salt, key)]`
