### ISSUE TITLE
Project doesn't update if cache isn't cleared 

### ISSUE THREAD

**Issue by vladislavOzhogov** [the-djmaze/snappymail#1494]
Hello, I have encountered a problem, I would appreciate if you helped.

Each time I change something in the code, I need to clear the cache in the docker container in order for my changes to take effect. It is fine when I do it in my dev environment, however it is also a necessary step in production. Is there any way to remove this step?

Thanks in advance!

**Comment by the-djmaze** [comment]
Disable cache?
Look in application.ini for that.

You could also increase cache index number in application.ini
