### ISSUE TITLE
shell_exec() dependence v2.35.3

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#1496]
After upgrade from v2.35.0 to v2.35.3 I get a broken system due this error:

`Got error 'PHP message: Uncaught exception: Error: Call to undefined function shell_exec() in /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/snappymail/gpg/base.php:486`

This depends of my PHP configuration pool that disable special and potential dangerous functions with direttive:

`php_admin_value[disable_functions] = exec,passthru,shell_exec,system`

of course all works fine if re-enable `shell_exec() `

anyway I am not sure where this function are used

strace
`[Thu Mar 14 18:47:05.285751 2024] [proxy_fcgi:error] [pid 2034951] [client 193.38.133.32:41012] AH01071: Got error 'PHP message: Uncaught exception: Error: Call to undefined function shell_exec() in /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/snappymail/gpg/base.php:486\nStack trace:\n#0 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/snappymail/gpg/pgp.php(76): SnappyMail\\GPG\\Base::findBinary()\n#1 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/snappymail/pgp/gnupg.php(15): SnappyMail\\GPG\\PGP::isSupported()\n#2 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/RainLoop/Actions.php(891): SnappyMail\\PGP\\GnuPG::isSupported()\n#3 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/RainLoop/Actions.php(906): RainLoop\\Actions->Capa()\n#4 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/RainLoop/Actions/Themes.php(16): RainLoop\\Actions->GetCapa()\n#5 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/RainLoop/Service.php(174): RainLoop\\Actions->GetTheme()\n#6 /srv/www/snappymail/public/snappymail/v/2.35.3/app/libraries/RainLoop/Service.php(...'
`

Can you do with out shell_exec() ?

thanks

Alessandro

**Comment by the-djmaze** [comment]
v2.35 has the same issue.
Difference is that you must disable GnuPG in application.ini
Before, you did that by disabling openpgp.

So if you don't want to support PGP security, disable it.

**Comment by the-djmaze** [comment]
By the way. The functions you disabled are not all.
There are still many holes.

Hack, i even wrote one years ago that i reported, and PHP refuses to fix it.
