### ISSUE TITLE
iCloud mail doesn’t work in snappymail 

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1497]
Fix for  #1285 at https://github.com/the-djmaze/snappymail/issues/1285

nextcloud mail has coded a fix,  can you implement in snappymail?  

https://github.com/nextcloud/mail/pull/9454#issuecomment-1997450390

**Comment by the-djmaze** [comment]
No. That is about ESEARCH and in SnappyMail you can already disable that.
https://github.com/the-djmaze/snappymail/wiki/IMAP-capabilities

**Comment by Luncheon3462** [comment]
@the-djmaze https://github.com/nextcloud/mail/issues/5181

**Comment by the-djmaze** [comment]
As i said: no

Just follow #1285 until someone finds the solution.

For now https://appleid.apple.com/account fails as well
