### ISSUE TITLE
Download attachments as ZIP doesn't work for PGP encrypted mail

### ISSUE THREAD

**Issue by mindsolve** [the-djmaze/snappymail#1499]
**Describe the bug**
When trying to use the "Download as ZIP" function for attachments in a PGP-decrypted message, a small red "X" appears and nothing else happens.

**To Reproduce**
1. Receive a PGP-encrypted e-mail, with an attachment
2. Open and decrypt the message
3. Click on the small cogwheel below the attachment(s)
4. Select at least one attachment, then click the "Download as ZIP" button
5. Observe a red cross icon instead of the "ZIP archive"-icon before and nothing else happening

**Expected behavior**
I would expect the attachment(s) to be downloaded in a ZIP archive, or, if impossible when using a PGP message, the function to not be visible.

**Screenshots**
![grafik](https://github.com/the-djmaze/snappymail/assets/24863329/2f293037-96f7-47a9-8cfe-a9f640e61c9f)

**Please complete the following information:**
- Browser: Firefox 123.0.1
- IMAP daemon: dovecot
- PHP version: 8.1.2-1ubuntu2.14
- SnappyMail Version: 2.35.3
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[snappymail-debug-pgp-zip-attachment-download.log](https://github.com/the-djmaze/snappymail/files/14619425/snappymail-debug-pgp-zip-attachment-download.log)

**Additional context**

**Comment by the-djmaze** [comment]
It's not only PGP decrypted messages.
It failed for any message that is parsed in JavaScript.

**Comment by the-djmaze** [comment]
It's not only PGP decrypted messages.
It failed for any message that is parsed in JavaScript.

The fix is not pretty as it requires to upload all attachments to the server.
Then the server makes the zip.
Then the server returns link the zip.
Then the browser downloads the zip from server.

Maybe better to have a "create zip" JavaScript library.
