### ISSUE TITLE
Compose new mail - Ctrl+V does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#15]
**RainLoop version, browser, OS:**
2.0.0-rc1, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
- Select the text of an existing mail and press Ctrl+C.
- Compose a new mail, set the cursor in the text field and press Ctrl+V.
- The text is not copied into the new mail.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
Browser log
libs.min.js:1 TypeError: Cannot read property 'before' of null
    at libs.min.js:1
    at Ae.Oe.insertHTML (libs.min.js:1)
    at Ae.Oe.insertPlainText (libs.min.js:1)
    at libs.min.js:1
Oe.didError @ libs.min.js:1
Oe.insertHTML @ libs.min.js:1
Oe.insertPlainText @ libs.min.js:1
(anonymous) @ libs.min.js:1
DataTransferItem.getAsString (async)
ke @ libs.min.js:1
Oe.fireEvent @ libs.min.js:1
Oe.handleEvent @ libs.min.js:1

**Comment by the-djmaze** [comment]
I failed to reproduce this error. I did made some changes in the hope it solves it.
However, for better debugging on which line the error occurs, you must edit application.ini and set `use_app_debug_js` to `true`

**Comment by phsc84** [comment]
Here we go, this is the new log with "use_app_debu_js" enabled.
libs.js:3513 TypeError: Cannot read property 'before' of null
    at insertTreeFragmentIntoRange (libs.js:1892)
    at Squire.proto.insertHTML (libs.js:5076)
    at Squire.proto.insertPlainText (libs.js:5163)
    at libs.js:3284

**Comment by the-djmaze** [comment]
Thanks for the log!
It seems i fixed that line in previous commit.

Will keep this open until confirmed

**Comment by phsc84** [comment]
It is partially fixed with 2.0.0-rc2. If the copied text contains a URL, Ctrl+V still does not work.
Log:
libs.js:3823 TypeError: parent.insertBefore is not a function
at addLinks (libs.js:5302)
at Squire.proto.insertHTML (libs.js:5371)
at libs.js:3592

**Comment by phsc84** [comment]
Hm, strange. I cannot reproduce the error anymore. Neither on my RC2 instance nor on your demo instance. And I tried many different texts (from other mails, from web sites, etc.).

But I've just noticed a little cosmetic flaw: The spaces before and after a link get deleted through Ctrl+V. The screenshot "copy_text_ctrl+c.jpg" shows the original text and the screenshot "copy_text_ctrl+v.jpg" shows the text after copying it.
![copy_text_ctrl+c](https://user-images.githubusercontent.com/2138442/96165911-9567ad00-0f1d-11eb-813c-e6b046139c1c.jpg)
![copy_text_ctrl+v](https://user-images.githubusercontent.com/2138442/96165913-96004380-0f1d-11eb-849b-fe60c6eee74d.jpg)

**Comment by phsc84** [comment]
Meanwhile I've found a URL, that does not work in RC2 (it shows the same error as in this [post](https://github.com/the-djmaze/snappymail/issues/15#issuecomment-706213859)) , but works perfectly fine in your demo.

Therefore I assume the issue is fixed now. Many thanks!
