### ISSUE TITLE
Can't log in if set up TOTP code on Security page

### ISSUE THREAD

**Issue by deimjons** [the-djmaze/snappymail#1501]
**Describe the bug**
Can't login if set up TOPT code

**To Reproduce**
1. Go to the Security page
2. Enter old and new passwords and TOTP code (4 numbers) and save them. 
3. Log out from a snappymail
4. Login in snappymail - Got authorization error 

**Expected behavior**
You should login after entered name, password, TOPT code.

**Please complete the following information:**
- Browser: Chromium Version 116.0.5845.169 (Official Build) (x86_64)
- PHP version: PHP 8.2.16
- SnappyMail Version: 2.35.4
- Mode:  standalone

**Comment by the-djmaze** [comment]
A TOTP code is not 4 numbers.
It's a long string of A-Z0-9 and the you need TOTP software to get the 30 seconds 6 digit code.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/issues/84#issuecomment-896063907

**Comment by deimjons** [comment]
@the-djmaze Thank you.
