### ISSUE TITLE
unclear usage of backup extension

### ISSUE THREAD

**Issue by scubamuc** [the-djmaze/snappymail#1504]
**Describe the bug**
unclear usage of **backup** extension

thanks for creating the **backup** extension. 
assuming that this extension will create a backup of snappymail settings & config for transfer/migration to a new/different instance.

![grafik](https://github.com/the-djmaze/snappymail/assets/54933878/69e36857-e482-4490-8f21-f52e97989bfc)

please explain functionality, possibly point to documentation/manual

thanks for great software and brilliant support

**Comment by the-djmaze** [comment]
The code is based on your #1042

Here you can see what it backups:
https://github.com/the-djmaze/snappymail/blob/9bc56a5abd58c554904b45a2d701fc47c529c655/plugins/backup/index.php#L52-L60

**Comment by scubamuc** [comment]
@the-djmaze thanks for the heads up... I should have remained on #1024 instead of creating a new request

now when trying to configure extension, there' nothing to configure. so I'm guessing this is doing the backup somewhere in the  background. 

only I'm not seeing any archive in the `APP_DATA_FOLDER` at all. this is the reason for me asking... 

possibly this has to do with Nextcloud snap confinement?

**Comment by the-djmaze** [comment]
There is nothing to configure. Just an admin menu
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/aff98d1b-0658-4cbc-a6dc-117f486c8243)

**Comment by the-djmaze** [comment]
Refresh/reload admin

**Comment by the-djmaze** [comment]
I wonder if Nextcloud is setting cache headers and prevents loading.

Will check.

**Comment by scubamuc** [comment]
Hey @the-djmaze, I've figured out how to get thebackup/restore admin menü visible... I disabled the "integrate with Nextcloud" extension.

![grafik](https://github.com/the-djmaze/snappymail/assets/54933878/6a551256-a21b-4c86-ae47-29a7144fe55e)

**Comment by scubamuc** [comment]
@the-djmaze 
so the backup works fine and I can download the archive.
sadly the restore process doesn't work at all
there are no errors displayed and the restore gives me no feedback. even after 15 minutes wait time the settings and configs are not restored.

should I open a new issue or reopen this or #1042

**Comment by the-djmaze** [comment]
Just open your logs and find out why yours is failing.

Mine works flawless

**Comment by scubamuc** [comment]
are you using Nextcloud snap?

**Comment by scubamuc** [comment]
Steps taken:

- backup existing snappymail and download archive
- go to fresh install Nextcloud snap 28.0.3 (testing)
- install snappymail app and activate extension "backup"
- go to "backup & restore" menu and restore by selecting downloaded archive selecting restore

here's my log;

```
[PHP] Fehler: file_put_contents(/var/snap/nextcloud/common/nextcloud/data/appdata_snappymail/_data_/_default_/cache/CACHEDIR.TAG): Failed to open stream: No such file or directory at /var/snap/nextcloud/40721/nextcloud/extra-apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Cache/Drivers/File.php#31
	POST /index.php/settings/apps/enable
	von 93.104.236.100 von scuba um 18.03.2024, 15:29:04
```

**Comment by scubamuc** [comment]
okay @the-djmaze .... it looks like this issue https://github.com/nextcloud-snap/nextcloud-snap/issues/2641 so we'll have to wait until that is resolved and retest.

**Comment by the-djmaze** [comment]
Ok. Since it is not a normal Nextcloud and nextcloud-snap specific.
I will close this and nextcloud-snap should fix issues.

**Comment by scubamuc** [comment]
@the-djmaze thanks for the backup & restore extension upgrade!

just realised, that without the Nextcloud (integrate) extension the auto complete for mail recipients would stop working. so that extension is not obligatory and must be active for address book integration.

thanks for your great work
