### ISSUE TITLE
custom theme not loaded from custom directory

### ISSUE THREAD

**Issue by portanisium** [the-djmaze/snappymail#1508]
**Describe the bug**
When you place a custom theme into /root/themes besides /root/snappymail the theme for example /root/themes/**owntheme**/styles.css is not loaded at startup of snappymail.
You have to copy it to root/snappymail/v/xyz/themes.
That means on every update you have to move the theme to the new directory /v/2.35.4/themes.
There already was an issue at https://github.com/the-djmaze/snappymail/issues/522#issue-1375849335 that is not resoved.

**To Reproduce**
bug in current 2.35.4

**Expected behavior**
Loading the theme from custom directory /root/themes

**Comment by the-djmaze** [comment]
I've made a small change to debug log some things regarding themes.
Somehow mine always work, so debugging would be a good addition.

**Comment by portanisium** [comment]
Found the solution:
Did not select the theme in Admin panel after placing it to custom location.
The entry in config file is now: theme=owntheme@custom
and it works as expected, thanks!
