### ISSUE TITLE
"Download as ZIP" fails

### ISSUE THREAD

**Issue by Rtzftz** [the-djmaze/snappymail#1514]
If I select one or more mail(s) and try "download as ZIP" I always get "Download failed".

Is this a known bug or something I can fix by config?

I'm running Debian Bookworm, nginx, PHP8.2 with all required Modules and the latest SnappyMail.

**Comment by the-djmaze** [comment]
Was caused by https://github.com/the-djmaze/snappymail/commit/0fd0d181546566aec67c04748f197918f3ddec5c

**Comment by Rtzftz** [comment]
WOW... Fixed in realtime... THX!
