### ISSUE TITLE
Support for Gmail Login

### ISSUE THREAD

**Issue by tetra-archos** [the-djmaze/snappymail#1520]
With Gmail ending support for App passwords in [September 2024](https://support.google.com/accounts/answer/6010255?hl=en), should there be any movement to add support for [sign in with google](https://support.google.com/accounts/answer/12849458?sjid=11180729019686178676-NA)? Maybe as an addon instead of directly in the main program.

**Comment by the-djmaze** [comment]
Ok i've created a working plugin for upcoming v2.36.1

1. Go to https://console.cloud.google.com/apis/dashboard
2. Create a project 
![create](https://github.com/the-djmaze/snappymail/assets/3752035/696a12a2-88e7-4878-834d-409f9f5df5d6)
3. Create OAuth credentials 
![credentials](https://github.com/the-djmaze/snappymail/assets/3752035/bbf30618-fc0d-46b0-bb02-8f72bb65eb77)
![credentials-clients](https://github.com/the-djmaze/snappymail/assets/3752035/604f214c-e53d-4bf3-97b3-f0824f35d5e0)

**Comment by X4Applegate** [comment]
I have same issues this,

**Comment by X4Applegate** [comment]
![image](https://github.com/the-djmaze/snappymail/assets/55598343/58eddfa6-3852-479f-b295-110d97531138)

**Comment by githubbbie** [comment]
Getting this same error with using https://snappymail.eu for Authorized Javascript Origins and https://snappymail.eu/demo/ for Authorized Redirect URIs.

Also, get the same error as @X4Applegate by using my own server's URI's.

**Comment by freebrowser1** [comment]
Appears to work now.
Our corporate mail uses Google Workspace. When using an 'app password' (different per mail client app) it does work. You have however to enable two factor authentication (using a TOTP authenticator) on Google mail.
After having done that and verifying the 2FA six digit code, go to https://myaccount.google.com/apppasswords and fill in e.g. Snappymail as app name and you get a 16 letter password in groups of four, e.g.'abcd efgh ijkl mnop'.
I did it on two different accounts successfully, so so complex OAuth crap needed and yet more secure.
