### ISSUE TITLE
SnappyMail An error occurred. Please refresh the page and try again.Failed loading 

### ISSUE THREAD

**Issue by stepcellwolf** [the-djmaze/snappymail#1535]
**Describe the bug**
My Nextcloud was on subdomain and folder (sso.domain.tld/clooud) and I moved it with YunoHost to cloud.domain.tld. Everything else worked except SnappyMail.

I tried several suggestions here and in Nextcloud forum, to remove `.htaccess` file and nginx restart. 
Delete and install, and remove and install the app several times. Still the error exists.
Any help will be highly appreciated we love the app. 

**To Reproduce**
1. Move Nextcloud subdomain and folder to another one
2. When open SnappyMail application it give the error below.
3. Same for SnappyMail Admin portal too.

`An error occurred.
Please refresh the page and try again.Failed loading /cloud/apps/snappymail/app/snappymail/v/2.36.0/static/js/libs.js
`

**Expected behavior**
This should work as expected.

**Please complete the following information:**
- Browser: Chrome, Safari and Firefox
- PHP version: 8.2.17
- SnappyMail Version: 2.36.0
- Nextcloud Version: 28.0.3
- YunoHost Version: 11.2.10.3 (stable)
- Mode: yunohost, nextcloud

**Comment by the-djmaze** [comment]
1. Edit application.ini
2. Remove all `cloud/`

**Comment by stepcellwolf** [comment]
Thanks a lot @the-djmaze that one worked. For the ones that are not that tech-savvy you can find the data folder in Yunohost:
`/home/yunohost.app/nextcloud/data/appdata_snappymail/_data_/_default_/configs/application.ini`

Thanks a bunch! Highly appreciated!
