### ISSUE TITLE
Allow editing and deleting tags (IMAP custom flags)

### ISSUE THREAD

**Issue by 3-w-c** [the-djmaze/snappymail#1536]
**Is your feature request related to a problem? Please describe.**

As of #1317, custom tags (IMAP PERMANENTFLAGS) can be added to messages, and new custom tags can be added. However, once a tag is created, it doesn't currently seem possible to edit or remove it through Snappymail, so if there's a typo or another mistake then it's not clear how to correct it. 

**Describe the solution you'd like**

Adding a delete (X) icon to the tag dropdown would be OK, although it does seem like this UI could risk accidental deletions, and maybe a "Tags" pane in settings would be preferable.

**Describe alternatives you've considered**

Manually editing the files on the IMAP server which contain the tags.

**Additional context**

![image](https://github.com/the-djmaze/snappymail/assets/66082850/30ab4527-6417-4c45-affa-91a2cc25305a)

**Comment by the-djmaze** [comment]
IMAP says: PERMANENT

So it is not possible to edit or delete them.

**Comment by the-djmaze** [comment]
If yiu have access to the server and use dovecot, then you can delete dovecot.index in the mailbox.
That could delete all unused tags.

**Comment by warumwirleben** [comment]
Push. Same here. Can't delete or edit the tags.

**Comment by tqb333** [comment]
It is not even possible to delete or rename custom tags, let alone edit the names of standard ones, as in thunderbird. Wtf guys?

May be somebody found a way to edit it? Even form the server filesystem? 

<img width="700" height="377" alt="Image" src="https://github.com/user-attachments/assets/996d3064-32d5-4949-a3d1-cb69128d7806" />
