### ISSUE TITLE
Login page not loading - Call to undefined function mb_internal_encoding()

### ISSUE THREAD

**Issue by andy-mic** [the-djmaze/snappymail#1537]
**Describe the bug**
I have recently updated my server and snappymail, and now I'm unable to load the login or admin pages for snappmail - I just get a blank page.

**To Reproduce**
Load webmail login page

**Expected behavior**
Prior to the update I was able to see the page and login

**Please complete the following information:**
- Browser: Firefox, Edge, Chrome, Safari
- IMAP daemon: dovecot
- PHP version: 8.3
- SnappyMail Version: 2.36.0
- Mode: standalone / apache2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Each time I load the page, the following error appears in the logs

PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/webmail/snappymail/v/2.36.0/include.php:75\nStack trace:\n#0 /var/www/webmail/index.php(11): include()\n#1 {main}\n  thrown in /var/>

I have checked and mbstring is definitely installed and enabled.  I've also checked the other extensions and they are all installed/enabled too:

    mbstring
    Zlib
    json
    libxml
    dom

**Additional context**
I did try to roll back to PHP8.2 (last working version) without success

**Comment by the-djmaze** [comment]
Are they active in the PHP that your snappymail is using, or does a user php.ini disable the function or doesn't load the extension?

Something must be wrong in your setup.

**Comment by andy-mic** [comment]
> Are they active in the PHP that your snappymail is using, or does a user php.ini disable the function or doesn't load the extension?
> 
> Something must be wrong in your setup.

I'm not sure, how can I check that?

When I issue the php --ini command I see this:
`Loaded Configuration File:         /etc/php/8.3/cli/php.ini`

Looking in the php.ini file, mbstring is enabled:
```
; If enabled, scripts may be written in encodings that are incompatible with
; the scanner.  CP936, Big5, CP949 and Shift_JIS are the examples of such
; encodings.  To use this feature, mbstring extension must be enabled.
zend.multibyte = On
```

I haven't changed anything in my apache/php/dovecot setup/configuration.  What I have done is regular updates for the OS, PHP (8.2 to 8.3), snappymail (2.35.0 to 2.36.0) versions

**Comment by the-djmaze** [comment]
There are several ways to check this.

Easiest is to create a `info.php` with content:
```php
<?php phpinfo();
```

**Comment by andy-mic** [comment]
That just gives a blank page... something is really broken :/
It's odd why a php/snappymail version update would break things so badly...
Sadly I don't know much about php configuration so I'm not sure where to look from here.

**Comment by the-djmaze** [comment]
When you get a blank page, check the php error logs.
