### ISSUE TITLE
Nextcloud Snappymail Inbox Not Showing Contacts

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1539]
**Describe the bug**
Snappymail is configured to use the nextcloud addressbook.  Yet, when I receive an email from someone in my address book, it shows the email address instead of the contact;s name.  

**To Reproduce**
1. Go to '.inbox'
2. Click on '.a mail message from a contact in my nextcloud address book.'
3. See email address of sender instead of contact name.  

**Expected behavior**
Messages received from someone in my address book should show their name.

NC28.0.4
Snappymail 2.36.0

**Comment by the-djmaze** [comment]
That is because contacts are used for sending.
Not for received emails.
Your contact should change how emails are send or leave it as it is
