### ISSUE TITLE
Searching all folders?

### ISSUE THREAD

**Issue by noticz** [the-djmaze/snappymail#154]
How can I have the search use all folders? I know this would have a performance impact but is there an option for this that can be enabled?

**Comment by the-djmaze** [comment]
I've implemented MULTISEARCH for you.
However, i have no idea if it will work because i don't have any accesible IMAP server to test if my code is working.
So you can say the feature is EXPERIMENTAL.

**Comment by Mer0me** [comment]
How multisearch is supposed to be used ?

**Comment by the-djmaze** [comment]
@Mer0me i have no idea which imap mail server supports this.
Better to have a unified mailbox like the gmail "all".
Dovecot see: https://doc.dovecot.org/configuration_manual/virtual_plugin/

**Comment by botsarenthuman** [comment]
Only Oracle support MULTISEARCH https://imapwiki.org/Specs
