### ISSUE TITLE
Snappypage javascript issue

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1540]
Hello !

Since this morning, one of our server is having a weird Snappy issue. At load time, it keeps spinning there:

![pbSnappy](https://github.com/the-djmaze/snappymail/assets/11666281/9f31a7b5-8187-46c2-8e12-161a6c3b3224)

for all users, whatever browser (FireFox, Brave or Chrome).

I can't see any reason to that:
- yesterday it has been reported to be working
- no update since (neither Snappy, Nextcloud, not even on the host server)
- just the usual daily docker compose stop / start this morning

It looks like a client-side issue, since the browser asks to stop the running script. The browser console shows that:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/e3d8177c-9b66-4749-ab64-e2069bcd0ec3)

Only the "Script terminated by timeout" line appears after a while, the lines before appear quite immediately while loading the Snappy page.

Versions in use:
- Snappy 2.36.0
- Nextcloud 28.0.3

All other servers we manage are still Nextcloud 27.1, except one which is 28.0.4, all are Snappy 2.36.0
So I will upgrade Nextcloud to 28.0.4 at lunch time, just in case.

**Comment by mmallejac** [comment]
Unfortunately, no change after Nextcloud upgrade to Nextcloud 28.0.4 :-\

**Comment by the-djmaze** [comment]
Can you enable the javascript debug mode?
That would make it easier to find the problem

**Comment by mmallejac** [comment]
Great !
Within Firefox, is that "Tools / browser tools / console / debug" or is
there a specifix option somewhere?

**Comment by mmallejac** [comment]
Thanks for the explanation.
If you say so :-)

Anything else we could provide to help ?

**Comment by mmallejac** [comment]
Not sure if it is pertinent:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/c4503cb5-04db-40f1-b38f-b7acea616172)

That is whithin the `computedPaginatorHelper` function
Firefox has shown this when it has proposed me to stop and debug
I've stepped 3 or 4 lines until I've made this screenshot

Ok, I've made a video:
https://www.awesomescreenshot.com/video/26537031?key=efa44c6f97e3eeda39df3fa1eafa846c

**Comment by the-djmaze** [comment]
`Infinity` doesn't seem right.
Somehow SnappyMail receives the wrong number.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

So it could be that the `MessagesPerPage` is 0

**Comment by the-djmaze** [comment]
> Infinity is a weird thing for a computer (and fora human too !)

But not for Buzz https://www.youtube.com/watch?v=0aG9wChNX_k&start=23

> Is `MessagesPerPage` somewhere in the config ?

Yes, but you can use
https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/RainLoop/Actions.php

**Comment by mmallejac** [comment]
Holy sh.t ! 
Actually the `application.ini` file is totally messed up :-\
I do not have a clue why, but yes the `messages_per_page` and many may other settings are set to 0 
I will recover from backup but I need more importantly to understand why this has happened

So, really sorry about this (I've learned a lot, but wasted quite of your time !)

**Comment by the-djmaze** [comment]
> So, really sorry about this (I've learned a lot, but wasted quite of your time !)

Not really, as we now hardened SnappyMail a bit more so that Buzz Lightyear can't go Infinity and beyond :wink:
