### ISSUE TITLE
[Nextcloud] Attachments saved in base64

### ISSUE THREAD

**Issue by einhander** [the-djmaze/snappymail#1541]
**Describe the bug**
Attachments saved in base64

**To Reproduce**
1. Go to mail with attachment
2. Click on save to local PC or Nextcloud
3. See files encoded with base64

**Expected behavior**
Files not encoded with base64

**Please complete the following information:**
- Browser: chrome 122
- IMAP daemon: davmail
- PHP version: 8.0
- SnappyMail Version: 2.36.0
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
Raw mail content:
```
Received: from ***** (192.168.0.5) by *****.local
 (192.168.0.5) with Microsoft SMTP Server (TLS) id 15.0.1497.48 via Mailbox
 Transport; Mon, 8 Apr 2024 13:28:15 +0300
Received: from *****.local (192.168.0.5) by *****.local
 (192.168.0.5) with Microsoft SMTP Server (TLS) id 15.0.1497.48; Mon, 8 Apr
 2024 13:28:15 +0300
Received: from *****.local ([::1]) by *****.local ([::1]) with
 mapi id 15.00.1497.048; Mon, 8 Apr 2024 13:28:15 +0300
From: ******* <*******@*****>
To: ******* <*******@*****>
Subject: 1
Thread-Topic: 1
Thread-Index: AQHaiZ92qAQw7fjhTk6SSSo/x3lk/g==
Date: Mon, 8 Apr 2024 10:28:14 +0000
Message-ID: <9540d499629fba44981caa012ea8d6ec5b4e494d@*****>
Accept-Language: ru-RU, en-US
Content-Language: en-US
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: *****.local
X-MS-Has-Attach: yes
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator:
Content-Type: multipart/mixed;
	boundary="_004_9540d499629fba44981caa012ea8d6ec5b4e494d*****_"
MIME-Version: 1.0

--_004_9540d499629fba44981caa012ea8d6ec5b4e494d*****_
Content-Type: multipart/alternative;
	boundary="_000_9540d499629fba44981caa012ea8d6ec5b4e494d*****_"

--_000_9540d499629fba44981caa012ea8d6ec5b4e494d****_
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

DQo=

--_000_9540d499629fba44981caa012ea8d6ec5b4e494d*****_
Content-Type: text/html; charset="utf-8"
Content-ID: <5697F3A50DB0084780232A5DFD5FEE17@*****>
Content-Transfer-Encoding: base64

PCFET0NUWVBFIGh0bWw+DQo8aHRtbD4NCjxoZWFkPg0KPG1ldGEgaHR0cC1lcXVpdj0iQ29udGVu
dC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiPg0KPC9oZWFkPg0KPGJv
ZHk+DQo8YnI+DQo8L2JvZHk+DQo8L2h0bWw+DQo=

--_000_9540d499629fba44981caa012ea8d6ec5b4e494d*****--

--_004_9540d499629fba44981caa012ea8d6ec5b4e494d*****_
Content-Type: application/pdf; name="1.pdf"
Content-Description: 1.pdf
Content-Disposition: attachment; filename="1.pdf"; size=220097;
	creation-date="Mon, 08 Apr 2024 10:28:13 GMT";
	modification-date="Mon, 08 Apr 2024 10:28:13 GMT"
Content-ID: <4FB9584034D8874AAF53425C99477186@*****>
Content-Transfer-Encoding: base64

JVBERi0xLjQKJcjH0MRGCjggMCBvYmoKPDwKL1R5cGUgL1hPYmplY3QKL1N1YnR5cGUgL0ltYWdl
Ci9OYW1lIC9JbTAKL1dpZHRoIDE2NTMKL0hlaWdodCAyMzM4Ci9MZW5ndGggOSAwIFIKL0JpdHNQ
.... Rest of file
```

**Comment by the-djmaze** [comment]
This is a bug in Nextcloud itself.
I´ve checked `/data/USERID/files/Documents/file.pdf` using a hex editor and it is 100% correct.
When i download using `/nextcloud/remote.php/webdav/Documents/file.pdf` the content is base64 encoded BUT the Content-Transfer-Encoding header is missing.

**Comment by einhander** [comment]
@the-djmaze Hmm, both issues are closed, so what should I do to download email attachments unencoded?

**Comment by the-djmaze** [comment]
Can you go to Admin -> Domains -> Domain -> IMAP -> Disable "BINARY"

**Comment by einhander** [comment]
> Can you go to Admin -> Domains -> Domain -> IMAP -> Disable "BINARY"

@the-djmaze  It not work. Attachments still encoded in base64.

**Comment by the-djmaze** [comment]
I meant:
1. Admin -> Domains -> Domain -> IMAP -> Disable "BINARY"
2. Now save an email attachment to Nextcloud
3. Open that attachment

**Comment by einhander** [comment]
@the-djmaze I followed the steps you wrote. Tested both save to local PC and Nextcloud. Attachments still in base64 encoding.  I also tested the Claws-Mail with same server, it saves attachments normally.

**Comment by the-djmaze** [comment]
Please forward the message as eml attachment to me and i can take a look.
issue-1541@snappymail.eu

**Comment by the-djmaze** [comment]
I've tested many ways and all work perfect.
There is no way i can reproduce your issue,

**Comment by einhander** [comment]
@the-djmaze Thanks for your efforts. I'll write here if I can solve it.
