### ISSUE TITLE
Extension: Change Password(pdo) - "Your login passphrase has changed...." pops up again and again

### ISSUE THREAD

**Issue by stefansieg** [the-djmaze/snappymail#1543]
**Describe the bug**

I am using the "Change Password" extension version 2.37. 
When I try to change a password, the message "Your login passphrase has changed. Please fill in your old login password to decrypt data" appears again and again, even if I enter the old login password.
After clicking on cancel, the message "could not save new password" appears. However, the password has actually been changed.
If I then change the passwords in the same window and click on "Set new Password" again, the password is changed without a message.

**Expected behavior**
The popup disappears after entering the old login password

**Please complete the following information:**
- Browser: Firefox, Chrome
- IMAP daemon: dovecot
- PHP version: 7.4.33
- SnappyMail Version: 2.36.0
- Mode: standalone

**Comment by xgbstar1** [comment]
Nice fix. Thank you @the-djmaze ! :+1:
