### ISSUE TITLE
"Use short login" does return the local part of address even if username should be returned

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#1544]
Our SMTP server only accepts a username different from the local part of the mail address, therefore we use the "use short login" function to strip the domain part from the username when automatically logging in with the Nextcloud username.
Before updating to v2.36.0 the username looked like `username@example.com` where the user has an other mail address looking like `name.surname@example.com`. The `use short login` function removed the `@example.com` and therefore the authentication with `username` as login name was possible.

After updating to the last version of Snappymail we saw that connecting to our SMTP servers is not possible anymore. Looking at the debug log with active logging of the secret strings I saw that now inside the base64 encoded string for authentication instead of `username` `name.surname` gets sent to the server and therefore the authentication fails.

I tried the "test" functionality in the domain configuration and there the authentication passes without a problem. 

I also tried the "test" functionality directly inside the Domain settings
![grafik](https://github.com/the-djmaze/snappymail/assets/63400209/446d97b2-d8cb-441d-b65e-d21fbc7b2917)

and inserted an existing username. When the user already used Snappymail once the result looks like `name.surname@example.com matched domain: undefined` and it looks like that somehow the username gets automatically converted to the local part of a mail address.
When I insert an other username that does not exist or that never used SnappyMail then something like `username@example.com matched domain: undefined` gets returned.

**Comment by the-djmaze** [comment]
SnappyMail never intended to work as "Nextcloud username" because of several reasons.
SnappyMail login should always be `name.surname@example.com` else it doesn't know what the correct email address is.

However, Nextcloud integration has some additional features for login:
1. `snappymail-autologin` uses the Nextcloud username (uid) with domain and password
2. `snappymail-autologin-with-email`  Nextcloud email address
3. else use the Nextcloud personal settings -> Additional -> SnappyMail
4. else use the Nextcloud personal settings -> email address

What you need is a login mapping for IMAP, SMTP and Sieve.
A list that converts `name.surname@example.com` to `username`.

**Comment by cm-schl** [comment]
I'm completely fine with the fact that a domain is needed to login. Therefore I'm using a default domain that always gets added to the Nextcloud username. Prior some change this worked because the default domain was automatically added, SnappyMail could retrieve the IMAP/SMTP settings and then strip the domain part because I have activated the short login function.
So I'm in the situation that is also described in https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#default-domain and this also worked until now.

Somehow now the short login functionality does not only strip the domain part but also seams to change the Nextcloud username to the local part of the connected email address. To me this seams a step further than only use a "short login". Maybe I'm missing something here?

From an admin perspective having a list "that converts name.surname@example.com to username" is not really manageable  because when I'm adding a new user to my ldap this user should also have an access to SnappyMail without having to add this user manually to an other list...

**Comment by the-djmaze** [comment]
Oh, then maybe use the short login option at SMTP might help.
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/e30b34e5-0c97-4b82-8fca-4f7d9cbd27d1)

**Comment by cm-schl** [comment]
I'm already using this option since the first install of SnappyMail and it always worked as expected.
![grafik](https://github.com/the-djmaze/snappymail/assets/63400209/6b917199-ee42-465a-b5cd-7b2d8ac37f51)

So would you say that the problem does not resides in the fact that `sSmtpUser` is never set to `sLogin` as done with `sImapUser`? https://github.com/the-djmaze/snappymail/issues/1544#issuecomment-2056808976

**Comment by the-djmaze** [comment]
Any luck with the latest release?

**Comment by cm-schl** [comment]
Hi,
unfortunately no, but I looked into the changes you made (thanks for that).
To make my problem more precise: the situation now only seams to arise when an additional account is used. The additional accounts I use are generated by my plugin `ldap-mail-accounts`.

Looking at the communication with the smtp server I saw that now the username of the additional account is correctly inserted, but the password isn't decrypted. SnappyMail sends the encrypted password to the server - it looks like one of the "hashes" inside the `additionalaccounts` file although inside this file I can't find the string sent to the server. Probably SnappyMail tries to use the password from the main account what could also be connected with my plugin. But the fact that SnappyMail sends the encrypted password to the server seams to be a bug...?

I Hope this helps a bit 🙂

**Comment by cm-schl** [comment]
Just to add additional information: I'm already working on the new version of my plugin https://github.com/cm-schl/snappymail/tree/master/plugins/ldap-mail-accounts - but I'm not sure if the problem is really connected with this plugin or with the handling of the additional accounts...

**Comment by cm-schl** [comment]
Hi @the-djmaze,
it took me days to identify the source of the problem. Unfortunately I can't say exactly where this problem happens, but I try to give you as much information as possible:

In fact the problem starts when inside my plugin I'm using https://github.com/the-djmaze/snappymail/blob/4b63adb0d56080fd51c1006faa23fa0efc8d91c7/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php#L106
to set a smtp password. When this `SensitiveString` is set using this function the password sent to the smtp server is a base64 encoded string that does not contain the smtp password but a crypted version of it.

So after setting the smtp password with `setCredentials` this password seams somehow to get crypted twice. When `SmtpClient::Login(` then tries to get the password string from the `SensitiveString` object it gets a decrypted string that seams to contain an other encrypted string.

My "error" was to try to set the smtp password using `setCredentials` out of my plugin. In fact at the moment this is not needed because SnappyMail automatically uses the imap password also as password for smtp logins when no password is set. So I'm fine at the moment but the error surly could affect other users in the future.
