### ISSUE TITLE
Using Nextcloud's recommended hardening, the App doesn't work / Mime Type no sniff

### ISSUE THREAD

**Issue by Patt92** [the-djmaze/snappymail#1546]
**Describe the bug**

The following error appears, when opening the app in the current version.
"An error occurred.
Please refresh the page and try again.Failed loading /apps/snappymail/app/snappymail/v/2.36.0/static/js/min/libs.min.js"

The browser shows "The loading has been prevented, because of a MIME type conflict ("text/html") blocked (X-Content-Type-Options: nosniff).
The error results from the hardening instructions of scan.nextcloud.com
>> The X-Content-Type-Options response header forbids browsers to guess the Content-Type of a file, this prevents so called "MIME confusion attacks".

causing header: "X-Content-Type-Options: nosniff"
Tested with Firefox 124.0.2

**To Reproduce**
1. Install Nextcloud Docker container
2. Serve it via NGinx 
3. Set Header with add_header X-Content-Type-Options "nosniff";
4. Snappymail can't load, because mime confusion

**Expected behavior**
Snappymail loads all scripts in the background without preventions, caused by a wrong mime type of the JS file.

**Screenshots**
![grafik](https://github.com/the-djmaze/snappymail/assets/6998914/e03d7e44-ebe0-45c1-b1e6-1c995b7241e9)
![grafik](https://github.com/the-djmaze/snappymail/assets/6998914/9130f60d-49a3-4df4-a4c7-dbfa75add74a)

**Please complete the following information:**
- Browser: Firefox 124.0.2 64-Bit MacOS 14.4.1
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 
root@myserver:~# docker exec -it nextcloud-app-1 bash
root@e42fdcae03f6:/var/www/html# php -v
PHP 8.2.17 (cli) (built: Mar 16 2024 01:08:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.17, Copyright (c), by Zend Technologies

- SnappyMail Version: 2.36.0
- Mode: docker (latest) 28.0.4-apache

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
see above

**Additional context**

**Comment by the-djmaze** [comment]
The problem is not the hardening.
Thw problem is that Apache or Nginx can't find/open the file.

Check if it exists and check the Apache error log

**Comment by the-djmaze** [comment]
You can see why using `https://example.com/apps/snappymail/app/snappymail/v/2.36.0/static/js/min/libs.min.js`

**Comment by Patt92** [comment]
ok, I got it sorted. Snappymail doesn't checks for a custom_apps folder for additonal apps. I have moved it from custom_apps to apps. Now it works. Maybe a good point to support alternative app folders as it is a native feature and configured in config.php
