### ISSUE TITLE
Snappy on Nextcloud has lost configuration

### ISSUE THREAD

**Issue by ruedigerkupper** [the-djmaze/snappymail#1548]
Our installation of snappy suddenly seems to have lost all its configuration. Site language switched to arabic, I cannot log in and I cannot reach the admin panel. I always get redirected to the nextcloud start page.

**Comment by ruedigerkupper** [comment]
Where is the configuration stored?

**Comment by the-djmaze** [comment]
Look in Nextcloud `/data/appdata_snappymail`

**Comment by ruedigerkupper** [comment]
Thank you, I could restore our configuration! The .ini file was completely messed up, trying to find out how that happened
