### ISSUE TITLE
Links via Nextcloud button not working

### ISSUE THREAD

**Issue by M-tp** [the-djmaze/snappymail#1549]
**Describe the bug**
When inserting a link via the Nextcloud button, the link is inserted correctly but it breaks and does not work when clicking on the activated link in the sent eMail.

**Comment by the-djmaze** [comment]
File sharing must be enabled in Nextcloud correctly.
1. Public links are like `https://example.com/nextcloud/s/xXgMo9bsRoz6Tiz`
2. Private links are like `https://example.com/nextcloud/f/19`
