### ISSUE TITLE
messagelist can not be displayed in 2.8.0 with certain mail providers

### ISSUE THREAD

**Issue by m-i-k-e-y** [the-djmaze/snappymail#155]
**Describe the bug**
After upgrade to version 2.8.0, using a gmx.net or outlook.com account the messagelist cannot be displayed. Neither in Inbox / Sent / Trash, etc. Interestingly though, snappy can detect that I have unread messages (see screenshot), which is correct. gmail.com accounts or accounts on my own server running dovecot are not affected.

In nginx I can find the following error logged when a folders messagelist shall be retrieved:

`
2021/10/29 16:00:41 [error] 326854#326854: *4026 FastCGI sent in stderr: "PHP message: CantGetMessageList[201]PHP message:      MailSo-Base-Exceptions-InvalidArgumentException (ImapClient.php ~ 780) @ /var/www/snappymail/snappymail/v/2.8.0/app/libraries/MailSo/Imap/ImapClient.php#780" while reading response header from upstream, client: redacted, server: redacted, request: "GET /?/Json/&q[]=/0/MessageList/&q[]=/NjMzZjU4OTVjOGIzNTkzYzA0YjFiMjRiNjk0NjY2NDIANzk1MWU4ODA2ODc5NDA2OTNjNTcxZjlmN2MzNjNjNDEASU5CT1gAMAAyMAAAADAAMAA HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "redacted"
`

**To Reproduce**
1. Login with a gmx.net or outlook.com account
2. switch between folders - every folder displays the same error message

**Expected behavior**
Folders should display their messagelist.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29158512/139450379-17151f9b-b1fc-4a86-a13f-744ac39353e0.png)

**Desktop (please complete the following information):**
 - Firefox 93.0 64bit in Windows 10
 - SnappyMail 2.8.0

**Additional context**
Reinstalling the previous version of Snappymail, 2.7.3, solves the issue.

**Comment by the-djmaze** [comment]
In application.ini you can turn `on` the debug setting.
A log in the `_data_` folder will show more info.

**Comment by the-djmaze** [comment]
Yep, changes regarding a bugfix for https://github.com/the-djmaze/snappymail/commit/3230a653d3480f5fbb5b40c4f6e8f6e95ade2f30 broke very old non-update IMAP servers.
FolderUnSelect() also breaks Outlook in a weird state.

The above mentioned commit just ignores the bugfix when ESEARCH is not supported and does not call FolderUnSelect()

**Comment by m-i-k-e-y** [comment]
Good morning!

I went ahead and applied your change on top of version 2.8.0 - it works like a charm! I can now access both, outlook.com and gmx.net accounts, again.

Thanks a lot for your fast response @the-djmaze !
