### ISSUE TITLE
Multiple Accounts leading to "open_basedir restriction in effect"

### ISSUE THREAD

**Issue by Terael76** [the-djmaze/snappymail#1555]
**Describe the bug**
i am new to snappymail and i like it. before i am a happy rainloop User. 
After i set all up there is a problem after setting up multiple accounts.
When i change the account it leads to "Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/gpg) is not within the allowed path(s): (/var/www/vhosts/XXX/YYY/:/tmp/:/var/lib/php/sessions:/var/www/vhosts/XXX/tmp) in /var/www/vhosts/XXX/YYY/mail/snappymail/v/2.36.0/app/libraries/snappymail/gpg/base.php on line 487"

login with single accounts did work well.

**To Reproduce**
1. login
2. Click top right on account icon
3. click on another account to change
4. then i see the error "Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/gpg) is not within the allowed path(s):
 (/var/www/vhosts/XXX/YYY/:/tmp/:/var/lib/php/sessions:/var/www/vhosts/XXX/tmp) in /var/www/vhosts/XXX/YYY/mail/snappymail/v/2.36.0/app/libraries/snappymail/gpg/base.php on line 487"
An error occurred.
Please refresh the page and try again.
SyntaxError: Unexpected token '<', "<br /> <b>"... is not valid JSON

**Expected behavior**
it should change the mail account i use to login. 

**Screenshots**
no screenshot. 

**Please complete the following information:**
- Browser: MS Edge - Version 123.0.2420.97 
- IMAP daemon: don't know
- PHP version: 8.1.28
- SnappyMail Version: 2.36.0
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] - standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[log-2024-04-20.txt](https://github.com/the-djmaze/snappymail/files/15049565/log-2024-04-20.txt)

**Additional context**
n/a

**Comment by the-djmaze** [comment]
Admin -> Security -> Crypto: disable GnuPG
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/9bc0f767-fd63-457f-9151-5a49a83431eb)

**Comment by Terael76** [comment]
I had already tried this unsuccessfully.
This setting is already deactivated

**Comment by the-djmaze** [comment]
Changed for next release to ignore the issue and force disable GnuPG
