### ISSUE TITLE
Issue with Override SMTP Credentials

### ISSUE THREAD

**Issue by DawnWakening** [the-djmaze/snappymail#1556]
There appears to be an issue whereby the Override SMTP Credentials extension is not over-riding SMTP credentials. 

I am trying to use Amazon SES as the SMTP server, and have tried multiple different configurations. 

I don't have any issues sending mail from the same server as IMAP, it just appears the issue is when using the SMTP override extension. It still continues to send mail through the server defined per-domain. 

I can confirm the same SMTP credentials work everywhere else. 
I can confirm I have tried different ports, and protocols, in accordance with those accepted by Amazon SES. 

https://s1.uhost.me/24/04/b017e2f0-bec9-4bc0-856c-0439e7ccb654/Xp9Fdk.png

I've tried all sorts of different configurations for the "Override users" field, to no avail. 

I have also tried setting the SMTP server in the domain as the actual domain being used, just incase the SMTP override extension was looking to override the SMTP server by domain, to no avail. 

https://s1.uhost.me/24/04/1f7d6d93-637f-4cef-ab3a-81ff3306a818/GVBe04.png

Checking the error logs, and enabling debug mode, appears that the SMTP Override extension is not overriding, where it should. There are no useful or meaningful debug logs, as it's not using or even attempting at using the Override SMTP credentials.

We are using NextCloud, PHP 8.3, and the latest version of SnappyMail.

**Comment by the-djmaze** [comment]
Correct, due to a change for a different SMTP issue the conflict for credentials came apparent.
I'm working on it so that all will work again.

**Comment by the-djmaze** [comment]
Works with latest release?

**Comment by WhyTea78** [comment]
No sorry. 
It don't work with Nextcloud 29 and Snappymail 2.36.1

**Comment by the-djmaze** [comment]
Your log should say in debug mode:
```
[2024-04-30 00:59:58.787][2f9bfa08] SMTP Override[DEBUG]: djmaze@example.com.au matched *@example.com.au
```
