### ISSUE TITLE
Snappymail Login with OIDC not working

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#1558]
**Describe the bug**
I am using OIDC app to login using keycloak sso and everything working smoothly but when i click on Mail it is not autologin the user with SSO.

**Expected behavior**
Its should autologin the user.

**Comment by avinash-0007** [comment]
@the-djmaze Issue i am getting is:

```
```
Next MailSo\Imap\Exceptions\LoginBadCredentialsException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/MailSo/Imap/ImapClient.php:229
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/MailSo/Imap/ImapClient.php(134): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/RainLoop/Model/Account.php(256): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/RainLoop/Model/Account.php(198): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/RainLoop/Actions/UserAuth.php(416): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.0/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#5 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(113): RainLoop\Actions->LoginProcess('avinashrecovery...', Object(SnappyMail\SensitiveString))
#6 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(26): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->index()
#8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'index')
#9 /var/www/html/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'index')
#10 /var/www/html/lib/private/Route/Router.php(315): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 /var/www/html/lib/base.php(1068): OC\Route\Router->match('/apps/snappymai...')
#12 /var/www/html/index.php(38): OC::handleRequest()
#13 {main}
[2024-04-22 18:56:57.132][a2da95ce] Nextcloud[ERROR]: AuthError[102]
```

**Comment by the-djmaze** [comment]
OIDC not working, there were too many conflicts.

Please post your snappymail debug log

**Comment by avinash-0007** [comment]
@the-djmaze i posted the log in above comment.

**Comment by avinash-0007** [comment]
@the-djmaze new logs

```
[2024-04-25 14:50:14.207][796635ce] [INFO]: Memory peak usage: 6MB
[2024-04-25 14:50:14.207][796635ce] [INFO]: Time delta: 0.065716028213501
[2024-04-25 14:50:14.436][c0250057] [INFO]: [SM:2.36.1][IP:122.161.77.8][PID:3155][nginx/1.24.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://dev.eeo.one/apps/snappymail/?/Css/0/User/-/Default/-/1714056614148/Hash/-/Json/]
[2024-04-25 14:50:14.437][c0250057] Nextcloud[DEBUG]: integrated
[2024-04-25 14:50:14.440][c0250057] IMAP[INFO]: Start connection to "tcp://localhost:143"
[2024-04-25 14:50:14.440][c0250057] IMAP[INFO]: Connect (failed)
[2024-04-25 14:50:14.440][c0250057] IMAP[NOTICE]: Socket: [2] stream_socket_client(): Unable to connect to tcp://localhost:143 (Cannot assign requested address)
[2024-04-25 14:50:14.440][c0250057] IMAP[NOTICE]: MailSo\Net\Exceptions\SocketCanNotConnectToHostException: Can't connect to host "tcp://localhost:143" in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.1/app/libraries/MailSo/Net/NetClient.php:138
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.1/app/libraries/MailSo/Imap/ImapClient.php(72): MailSo\Net\NetClient->Connect(Object(MailSo\Imap\Settings))
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.1/app/libraries/RainLoop/Model/Account.php(202): MailSo\Imap\ImapClient->Connect(Object(MailSo\Imap\Settings))
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.1/app/libraries/RainLoop/Actions/UserAuth.php(441): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))

**Comment by avinash-0007** [comment]
@the-djmaze any update on this?

**Comment by the-djmaze** [comment]
Not yet

**Comment by the-djmaze** [comment]
Keep track of #1569
akhil1508 is doing amazing things there

**Comment by avinash-0007** [comment]
@the-djmaze Is there anyway if access token is expired and we have sign me token enabled so we want user to logout. I checked the code, i was thinking to check if access token is valid in Helper but that will not work as app calls in snappy is api call with json response.So is there any listener which get called in app api call where we can check if access token is valid or not if not we can redirect user to oidc page?
