### ISSUE TITLE
improve UI to aid command discovery and use

### ISSUE THREAD

**Issue by jhnc** [the-djmaze/snappymail#1559]
I recently asked how to copy a message because I could not find the command in the menus, nor any keyboard shortcuts listed in the keyboard shortcuts help listings.

1) Please add Copy (and any other  commands?) to the dropdown menus.

2) Please add all currently unlisted commands to the keyboard shortcuts help listing.

I was told that pressing `Ctrl` would bring up Copy. This isn't practical on a mobile device with no physical keyboard.

3) Please make all commands usable on touch devices. Implementing (1) above would accomplish this.

On my desktop computer with firefox, I see that holding down `Ctrl` causes the "Move to" button's normal folder icon to change to two overlapping pieces of paper. However the hover tooltip still reads "Move to", making it hard to tell that something different will happen if the button is clicked. And after clicking, the same message is displayed with or without `Ctrl`: "Click folder name in the left panel to select the destination".

4) Please make hover tooltips update to correspond to the action that will be performed. 

4) Please adjust the message displayed after clicking a button so that it is clear what action is being performed. For example, by adding a header like "Move message" or "Copy message" as appropriate.

**Comment by the-djmaze** [comment]
I've changed the code to expose "copy to" in the menu's

**Comment by jhnc** [comment]
If the shortcut still works for desktop users after your changes, I don't see that there's a need to stop it from working there, if that's what you mean. (And I imagine people who knew about it and were using it would be sad.)
