### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by jonmoesli** [the-djmaze/snappymail#156]
First of all, thank you for this great product!

As in [Rainloop issue](https://github.com/RainLoop/rainloop-webmail/issues/1680), it'd be very nice to have theme support (even with paid support or with other options).
The engine is really cool but the UX of Roundcube (Elastic engine) is superior IMHO, very sad of it :-(

Thank you again!

**Comment by the-djmaze** [comment]
RainLoop and SnappyMail do support custom themes.

The code can be found here:
https://github.com/the-djmaze/snappymail/blob/d4117dc72398f5a7f12da3e7997cc2e44a910a80/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Themes.php#L57

The place where the theme should be is `APP_INDEX_ROOT_PATH . 'themes'`

So if you have some something like `/home/webmail/public_html/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Themes.php`
The custom themes should be in `/home/webmail/public_html/themes/`.

**Comment by jonmoesli** [comment]
Thank you, I'll try!

Is there a plan to "modernize" the default theme in future?

**Comment by the-djmaze** [comment]
> Is there a plan to "modernize" the default theme in future?

Define "modernize" ?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Custom-Themes
