### ISSUE TITLE
Cannot add new imap Account - "Account already exists"

### ISSUE THREAD

**Issue by a-schn** [the-djmaze/snappymail#1561]
**Describe the bug**
When I want to create an eMail-Account, the following message appears: "The Account already exists", but it doesn't.
The domain is added correctly.

![2024-04-25 (1)](https://github.com/the-djmaze/snappymail/assets/168131269/23d8a2fb-d8ee-46e9-9edc-f05c8426c14d)

**Expected behavior**
Add the Account

**Please complete the following information:**
- Browser: tried with chrome, edge and brave
- IMAP 
- SnappyMail Version: 2.36.1
- Mode:  nextcloud, 28.0.5

**Comment by aukfood** [comment]
Hello, same problem with Nextcloud 27.1.9

**Comment by corincorvus** [comment]
same

**Comment by DawnWakening** [comment]
A temporary work around for now is to change line 96 in /app/snappymail/v/2.36.1/app/libraries/RainLoop/Actions/Accounts.php from: 

`if ($oMainAccount->Email() === $sEmail || isset($aAccounts[$sEmail])) {`

To:

`if ($oMainAccount->Email() === $sEmail) {`

Proceed with caution, however, as this is only a temporary work-around.

**Comment by corincorvus** [comment]
> A temporary work around for now is to change line 96 in /app/snappymail/v/2.36.1/app/libraries/RainLoop/Actions/Accounts.php from:

Hey, i cant find the path or the app. 
In the Nextcloud Folder i only find "apps" or "custom_apps". In "custom_apps" is "snappymail". In "snappymail" is no folder like anyone in your path. "Accounts.php" i didnt find in nextcloud/apps, nextcloud/custom_apps or nextcloud/data/appdata_snappymail

Where the File is located in Nextcloud AIO?

Thanks.

**Comment by a-schn** [comment]
Hope there will be an update soon. 
I can't see the code/data of my nextcloud installation.

**Comment by simonquasar** [comment]
I had the same issue with Nextcloud Hub 8 (29.0.0) on Ubuntu Linux 22.04.4 with Apache / PHP 8.1.2

The temporary patch @DawnWakening suggested in https://github.com/the-djmaze/snappymail/issues/1561#issuecomment-2079388917_ 
works for my setup. Many thanks!

> Where the File is located in Nextcloud AIO?

/cloudfolder**/apps/snappymail/**app/snappymail/v/2.36.1/app/libraries/RainLoop/Actions/Accounts.php

**Comment by corincorvus** [comment]
> **/cloudfolder/apps/snappymail/app/snappymail/v/** 2.36.1/app/libraries/RainLoop/Actions/Accounts.php

Nope
```
b19e805897f9:/var/www/html# ls
3rdparty  apps           config       cron.php     dist        lib  ocs-provider       public.php  robots.txt  updater
AUTHORS   composer.json  console.php  custom_apps  index.html  occ  package-lock.json  remote.php  status.php  version.php
COPYING   composer.lock  core         data         index.php   ocs  package.json       resources   themes
b19e805897f9:/var/www/html# cd apps/
b19e805897f9:/var/www/html/apps# ls
activity              dashboard             files_pdfviewer  lookup_server_connector  privacy            support                twofactor_totp
admin_audit           dav                   files_reminders  nextcloud-aio            provisioning_api   survey_client          user_ldap
bruteforcesettings    encryption            files_sharing    nextcloud_announcements  recommendations    suspicious_login       user_status
circles               federatedfilesharing  files_trashbin   notifications            related_resources  systemtags             viewer
cloud_federation_api  federation            files_versions   oauth2                   serverinfo         text                   weather_status
comments              files                 firstrunwizard   password_policy          settings           theming                workflowengine
contactsinteraction   files_external        logreader        photos                   sharebymail        twofactor_backupcodes
b19e805897f9:/var/www/html/apps# 
```

Snappymail is installed:
![image](https://github.com/the-djmaze/snappymail/assets/21257329/7de25290-54e1-4e6e-95a7-afe281b52b86)

**Comment by warumwirleben** [comment]
Why is this closed. Is there any update?

PUSH
Same problem here, Snappymail Version 2.36.1

I love snappymail, but this is a big problem at the moment. New accounts can add one adress - any second adress was not possible (account already exists).

Thanks for your great work, hope you can fix it fast and push the solution for the update.

**Comment by cedvan** [comment]
Same problem with v2.36.1 and nextcloud version 28.0.2

**Comment by diroots** [comment]
> Why is this closed. Is there any update?

yes, with https://github.com/the-djmaze/snappymail/commit/9ec8ac8bbab56af13187fef5b7cda0f3eb88f9ff (not yet released, but can be used as patch)

> closed this as [completed](https://github.com/the-djmaze/snappymail/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/the-djmaze/snappymail/commit/9ec8ac8bbab56af13187fef5b7cda0f3eb88f9ff 2 weeks ago

**Comment by the-djmaze** [comment]
I had a small sabbatical and do some other things.
Expect a release this week.

**Comment by pscriptos** [comment]
I'm currently facing the same problem. 
I'm in the process of switching from rainloop to Snappymail and got the same error when setting it up. 
I am very much looking forward to this release. 

In case it will take a few more days, does anyone know how to install a patch via Docker in this case? 

I thank you for your time and energy that you put into this project, @the-djmaze! :)

**Comment by warumwirleben** [comment]
Thanks for the release ♥

**Comment by warumwirleben** [comment]
Now there is a message: Authentication failed. :(
I can not login.

**Comment by warumwirleben** [comment]
I deactivated SnappyMail until this is fixed. There is only one account possible at the moment. This is not what I want.
