### ISSUE TITLE
Need to have Nextcloud Contact Groups available as recipient data

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1564]
When the Nextcloud user creates a Group in the Contacts app, there is a shortcut to send to the group even as a BCC from that page.  It can open the Compose window in SnappyMail but the BCC is blank.  If I want to type the group in the email fields, it doesn't connect to anything.  It would be great to have this ability for user's personal groups.

**Comment by the-djmaze** [comment]
Duplicate #797
