### ISSUE TITLE
mkdir(): Permission denied at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.36.1/setup.php#27

### ISSUE THREAD

**Issue by njscop** [the-djmaze/snappymail#1565]
**Describe the bug**
Nextcloud - v29.0.0.19 fresh install.
PHP - 8.3.6
NGINX - 1.25.5

**To Reproduce**
1. Fresh Install Nextcloud
2. Log into interface
3. Install APP
4. Get PHP error : mkdir(): Permission denied at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.36.1/setup.php#27

**Expected behavior**
Application installs

**Screenshots**
-

**Please complete the following information:**
- Browser: Chrome Version 124.0.6367.61 (Official Build) (64-bit)
- -
- PHP - 8.3.6
- SnappyMail Version: 2.36.1
- Mode: nextcloud / standalone (no docker)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
 error : PHP mkdir(): Permission denied at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.36.1/setup.php#27

**Additional context**
Nothing to add.

Steps tried:
Nextcloud Config : add 'tempdirectory' => '/tmp/nextcloudtemp', + add permissions

The same error.

**Comment by njscop** [comment]
Other apps installed without issue such as: Callendar, Talk, Colabora etc.

**Comment by the-djmaze** [comment]
APP_DATA_FOLDER_PATH can't be created.

Check permissions on your nextcloud/`data` directory.
