### ISSUE TITLE
Account already exists 

### ISSUE THREAD

**Issue by syhgzyxgs39** [the-djmaze/snappymail#1571]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Accounts'
3. Click on 'Add an Account'
4. After filling in the account information, click Add 
5. Show account already exists

**Expected behavior**
Accounts should be added correctly

**Screenshots**
![无标题](https://github.com/the-djmaze/snappymail/assets/139859362/3f3994ce-2972-41b1-9713-801897e407a3)

**Please complete the following information:**
- Browser: Google Chrome 123.0.6312.122 PC
- IMAP daemon: none
- PHP version: 8.2.16
- SnappyMail Version: 2.36.1
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[log-2024-05-02.txt](https://github.com/the-djmaze/snappymail/files/15184434/log-2024-05-02.txt)

**Comment by simonbuehler** [comment]
same here, added the domain in the admin but can't add an account as a user for it

**Comment by simonbuehler** [comment]
https://github.com/the-djmaze/snappymail/commit/9ec8ac8bbab56af13187fef5b7cda0f3eb88f9ff is related
