### ISSUE TITLE
Sorting / threads not supported for default imap capabilities

### ISSUE THREAD

**Issue by simonbuehler** [the-djmaze/snappymail#1574]
Hi,

when trying to connect to the ionos IMAP server, I get this listing of capabilities:
```json
. capability
* CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN APPENDLIMIT=140000000
. OK CAPABILITY completed
```

![grafik](https://github.com/the-djmaze/snappymail/assets/78061/60c05970-e8b7-48ab-bf48-03420aa55fed)

see the ` THREAD=ORDEREDSUBJECT` definition - I unchecked the "Threads" options but still, now in the settings tab i get this view:

![grafik](https://github.com/the-djmaze/snappymail/assets/78061/1fdb464c-3286-45d2-9de1-3b8958be3ccd)

![grafik](https://github.com/the-djmaze/snappymail/assets/78061/f43a98de-9d11-4eef-9bcd-e1969764d7f6)

is the provider really that limited, or did I configure something wrong?

**Comment by the-djmaze** [comment]
I will look into it as the new feature conflicts with some old THREAD behavior.
