### ISSUE TITLE
"Unknown Error" with s/mime wildcard

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#1576]
**Describe the bug**
"Unknown Error" when signing mail using a wildcard s/mime.

**To Reproduce**
1. Generate a "wildcard" s/mime cert and key with OpenSSL
2. Import the cert and key into Snappymail
3. Compose new email
4. Ensure "sign" option is selected and available
5. Observe unknown error when sending

**Expected behavior**
The email should send and be signed using the wildcard cert

**Screenshots**
![https://cdn.thecutefoxxy.com/jgZv9P.png](https://cdn.thecutefoxxy.com/jgZv9P.png)

**Please complete the following information:**
- Browser: Firefox 125.0.3
- IMAP daemon: dovecot
- PHP version: 8.1.27
- SnappyMail Version: 2.36.1
- Mode: Nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
- [Log File](https://vault.tcf.ventures/#/send/KDPGCRV-SM2e-5A5Z9_K0w/2pKc4Cm8KJFp-fVrhXg_tQ)

**Additional context**
None

**Comment by TheCuteFoxxy** [comment]
Unless I missed it somewhere, Snappymail doesn't automatically send the public keys along with encrypted or signed mails. So without the user physically providing every single person the key, then signatures can't be verified and encryption can't be decrypted.

If 5 people need to verify their emails between each other, than each person has to give the other 4 people the public key manually.

A wildcard prevents this problem when its being used across the same domain since everyone has the same keys for that domain, but other domains (such as gmail) doesn't, which is fine.

**Comment by TheCuteFoxxy** [comment]
@the-djmaze ^

**Comment by the-djmaze** [comment]
Attaching your public key is a better option, like you ask in  #1587
