### ISSUE TITLE
Snappymail in Nextcloud Dashboard Icon Broken

### ISSUE THREAD

**Issue by SinisterCrayon** [the-djmaze/snappymail#1577]
After recent updates to Nextcloud, the email icon at the top of the screen no longer redirects to "/apps/snappymail" but rather "/apps/dashboard". I have tried removing and completely reinstalling Snappymail into Nextcloud but it continues to have the wrong link information.

**Comment by the-djmaze** [comment]
Which Nextcloud version?

**Comment by SinisterCrayon** [comment]
Nextcloud Hub 8 (29.0.0)

**Comment by SinisterCrayon** [comment]
Follow up; I seem to have resolved it.

I was tracing back another problem with Cron jobs not running properly and as part of troubleshooting (that worked) disabled FullTextSearch. That resolved my other problem, but also seems to have resolved this issue with the Snappymail dashboard icon. I don't know... weird interactions I guess?

Hopefully the FTS guys will get an update out soon.

**Comment by the-djmaze** [comment]
https://github.com/nextcloud/server/issues/43910
https://github.com/nextcloud/fulltextsearch/issues/842
