### ISSUE TITLE
Prioritize Reply All vs Reply

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1579]
Hello !

I've read #496 and #834, and I've also noticed the `MsgDefaultAction` setting in the per-user setting file.
Would it be possible to have an `application.ini` similar setting that would set a default behavior for the entire installation ?

Thanks 
Michel

**Comment by the-djmaze** [comment]
> Our `language` value is `fr_FR` : is that causing an issue ?

I've tested and yes it does.
`Message: Unable to process binding "if: function(){return options }"
Message: Unable to process binding "value: function(){return value }"
Message: value , must be observable`

**Comment by mmallejac** [comment]
Thanks. Is this something you can correct within Snappy or should I change
the value ?

I've tried to change the value in the application.ini file (nothing / fr /
fr_CH / line commented out) but none of these allows access to Snappymail
main config.
Actually it is worse than before since it was only the Configuration tabs
that was not working and now any access to Snappy main config page resets
to the Nextcloud welcome page !

Here are the log I have in the debug file :

[2024-05-28 12:04:48.265][c22d60e2] [INFO]:
[SM:2.36.3][IP:185.71.12.177][PID:2958][Apache/2.4.59
(Debian)][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET
https://cloud.4next.ch/apps/snappymail/?admin]
[2024-05-28 12:04:48.265][c22d60e2] [INFO]:
[SM:2.36.3][IP:185.71.12.177][PID:2958][Apache/2.4.59
(Debian)][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET
https://cloud.4next.ch/apps/snappymail/?admin]
[2024-05-28 12:04:48.310][c22d60e2] [INFO]: Memory peak usage: 10MB
[2024-05-28 12:04:48.310][c22d60e2] [INFO]: Time delta: 0.08375883102417
[2024-05-28 12:04:49.271][dbbfa05b] [INFO]:
[SM:2.36.3][IP:185.71.12.177][PID:2958][Apache/2.4.59
(Debian)][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET
https://cloud.4next.ch/apps/snappymail/?/AdminAppData/0/6480697963405204/]
[2024-05-28 12:04:49.273][dbbfa05b] Nextcloud[DEBUG]: snappymail-nc-uid
mismatch '' != 'mmallejac'
[2024-05-28 12:04:49.275][dbbfa05b] APPDATA[INFO]:
{"Auth":false,"title":"4Next webmail 📫","loadingDescription":"4Next
webmail
📫","Plugins":[],"System":{"version":"2.36.3","token":"2b8ab9d74c52696f2da751873f628398ffa3a958","languages":["ar","be","bg","cs","da","de","el","en","eo","es","et","eu","fa","fi","fr","hu","id","is","it","ja","ko","lt","lv","nb","nl","pl","pt","pt-BR","ro","ru","sk","sl","sv","tr","uk","vi","zh","zh-TW"],"webPath":"\/custom_apps\/snappymail\/app\/","webVersionPath":"\/custom_apps\/snappymail\/app\/snappymail\/v\/2.36.3\/"},"allowLanguagesOnLogin":false,"Admin":{"host":false,"path":"admin","allowed":false},"Theme":"NextcloudV25+","language":"fr","clientLanguage":"fr","PluginsLink":"","StaticLibsJs":"\/custom_apps\/snappymail\/app\/snappymail\/v\/2.36.3\/static\/js\/libs.js"}
[2024-05-28 12:04:49.275][dbbfa05b] [INFO]: Memory peak usage: 6MB
[2024-05-28 12:04:49.275][dbbfa05b] [INFO]: Time delta: 0.035590887069702

Especially this one ??
Nextcloud[DEBUG]: snappymail-nc-uid mismatch '' != 'mmallejac'
