### ISSUE TITLE
Cant get message list v2.8.0

### ISSUE THREAD

**Issue by lamphankhoi** [the-djmaze/snappymail#158]
I am using snappy 2.7.3 for checking email no prolem at all when checking email However, today when I tried to upgrade it to version 2.8.0, I cannot check email. When I click on each folder such as inbox, sent, etc. I get "Can't get message list". Please advise and help me what I did wrong or what I should do to correct those. I am really appreciate your great help.

**Comment by the-djmaze** [comment]
Issue is already reported and fixed in #155

Soon i will release a 2.8.1 with more fixes.

**Comment by lamphankhoi** [comment]
Thanks for your quick reponse and great help. I will close this.
