### ISSUE TITLE
Snooze mail

### ISSUE THREAD

**Issue by UNICodehORN** [the-djmaze/snappymail#1583]
**Is your feature request related to a problem? Please describe.**
I loose overview on emails I need to keep in the inbox, while waiting on an answer or smiliar.

**Describe the solution you'd like**
Snoozing mails like on Gmail.
1. Click button snooze
2. Select date and time from calendar picker
3. Move snoozed mail to a specific folder "snoozed mails"
4. When date and time is reached, move mail back to inbox marked as unread and display ribbon (or similar) "was snoozed until...."

**Describe alternatives you've considered**
GMail

**Additional context**
![Screenshot from 2024-05-16 11-08-27](https://github.com/the-djmaze/snappymail/assets/35925904/5355080a-1e97-4a81-8f20-302fb15de6da)
![Screenshot from 2024-05-16 11-08-42](https://github.com/the-djmaze/snappymail/assets/35925904/624541ac-dd85-41d1-94c8-0f5e118d83a5)
![Screenshot from 2024-05-16 11-10-17](https://github.com/the-djmaze/snappymail/assets/35925904/55987402-75f3-4d37-bd3a-cb82d8c9c48b)

**Comment by the-djmaze** [comment]
Not possible as SnappyMail has no "calendar"
