### ISSUE TITLE
x-face support

### ISSUE THREAD

**Issue by OrcVole** [the-djmaze/snappymail#1585]
**Is your feature request related to a problem? Please describe.**
SnappyMail should show x-face images when they arrive, and have an option to create and assign an x-face header

**Describe the solution you'd like**
We see x-face headers as images in our inbox. We have a tool to create and include a personal x-face header

**Describe alternatives you've considered**
living without this

**Additional context**
https://www.dairiki.org/xface/xface.php
(https://onlinepngtools.com/create-monochrome-png#tool)
https://userbase.kde.org/Kmail/Configuring_Kmail/Identities

**Comment by the-djmaze** [comment]
Browsers do not support it and there is no JavaScript code to convert them.
Therefore it is not possible.
