### ISSUE TITLE
Nextcloud Log Error

### ISSUE THREAD

**Issue by Luncheon3462** [the-djmaze/snappymail#1586]
I keep getting this error in my nextcloud log.  Do you know why?

"preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.36.1/app/libraries/MailSo/Base/Http.php#246",

**Comment by prismopensource** [comment]
Same problem over here, running on version 2.36.1 on PHP 8.2 with Nextcloud 28.0.5 with these extensions enabled:

- Contacts suggestions (IMAP folder)
- Nextcloud

**Comment by the-djmaze** [comment]
Already fixed at https://github.com/the-djmaze/snappymail/commit/f4e81a183ef7ed6e03f4561603c17ae9a3262afc

**Comment by Luncheon3462** [comment]
@the-djmaze how do we get the fix from f4e81a1?
