### ISSUE TITLE
Improve Advanced Search by enabling the following features: Choice of folder, More filter options, Allow the use of combined filters, ...

### ISSUE THREAD

**Issue by fabiodepin** [the-djmaze/snappymail#1592]
Improve Advanced Search by enabling the following features:
- Choice of folder;
- Allow searching in all folders;
- Allow searching in the folder and its subfolders;
- More filter options;
- Allow the use of combined filters;

How it is currently:
![Screenshot from 2024-05-23 15-38-05](https://github.com/the-djmaze/snappymail/assets/1088516/e7105dfb-dd2c-4073-a427-2d49d743634e)

What would the proposed idea look like:
![Screenshot from 2024-05-23 15-36-25](https://github.com/the-djmaze/snappymail/assets/1088516/b2cde37e-34e3-43d4-867b-33516bfaa734)

**Comment by the-djmaze** [comment]
Not possible due to how IMAP works.
Read the other closed issues that are similar to your request why IMAP can't.

**Comment by fabiodepin** [comment]
hello,

I know that Imap servers like dovecot do not have the capacity for a single search to search all folders or subfolders.

but this is indeed possible, if the search is carried out in each folder, then sorted and then paged, then the data from these emails is retrieved and returned.

I already have this ready, I just need to adjust the front and the templates.
As soon as it's finished, I'll send you a working PR for you to evaluate.

If possible, I ask you to keep this task open for now.

thank you very much

**Comment by the-djmaze** [comment]
Ok, looking forward to it.

Do you take into account that some people have 100+ or even 1000+ folders/mailboxes?
Will there be a limit as the browser also has request timeout that we can't control (we do have a pipe that will work in some setups).
