### ISSUE TITLE
Can't swap between email accounts

### ISSUE THREAD

**Issue by Anonym69** [the-djmaze/snappymail#1594]
**Describe the bug**
I can no longer swap between email accounts. This was possible before.

**To Reproduce**
1. Go to SnappyMail
2. Click on The dropdown menu to the right to choose email account
3. A popup saying "Switch to account <some@email.com> failed"
4. Then it asks for login credentials but that doesn't work despite being correct

**Expected behavior**
I was able to swap between email accounts before. No more.

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/4282174/5f59b134-60fd-4425-935d-8bbeb496f29a)

**Please complete the following information:**
- Browser: FF 126.0, Chrome Version 120.0.6099.217 (Official Build) (64-bit)
- IMAP daemon: N/A
- PHP version: 8.2
- SnappyMail Version: 2.36.1
- Mode: NextCloud

**Comment by Anonym69** [comment]
> I experienced something similar. To solve this I had to remove the file ..storage/domain.com/user/.cryptkey

Thanks! Unfortunately it didn't work for me.

Any other hints?

**Comment by the-djmaze** [comment]
Remove the account and add it again?

**Comment by Anonym69** [comment]
I tried that before I filed the issue - doesn't work.
