### ISSUE TITLE
Change sub account but From still Master account

### ISSUE THREAD

**Issue by lamphankhoi** [the-djmaze/snappymail#160]
**Describe the bug**
Version 2.9.1. I just upgraded today. I found out that when I switched to sub accounts, but FROM still showing the master account

**To Reproduce**
Switch to sub account, click on New message

**Expected behavior**
The FROM should be sub account which switched to

**Comment by the-djmaze** [comment]
Yes i noticed this and that additional identities also failed for sub accounts.

This is fixed for next release.

**Comment by lamphankhoi** [comment]
Thanks for your quick response and great help. I will close this issue now.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.9.2
