### ISSUE TITLE
There is only one account possible at the moment. 

### ISSUE THREAD

**Issue by warumwirleben** [the-djmaze/snappymail#1601]
Version 2.6.2 in Nextcloud

The last update destroyed the usability of SnappyMail in Nextcloud.

1
There is only one account possible at the moment. 
Very bad. This was the best feature of SnappyMail.

2
The configuration is reset. (Vertical Layout and more)

3
The admin-Link is broken 

Please fix this very quickly. SnappyMail is great, but it doesn't work at the moment.

**Comment by warumwirleben** [comment]
This is a very big problem. SnappyMail is not usable at the moment, if you have configured more than one email.

**Comment by warumwirleben** [comment]
Version 2.6.3 in Nextcloud

All problems still same
- Admin Link is broken
- only one Account is possible (no other identities or mail-accounts possible)
- configuration seems to be purged

**Comment by Bloodsoul** [comment]
I had the same problem. Some of the configurations vanished.
For now I fixed it by reactivating the admin panel by changing `allow_admin_panel` back to `True` in `data/appdata_snappymail/_data_/_default_/configs/application.ini` and configuring the missing stuff back in.

**Comment by warumwirleben** [comment]
@Bloodsoul
Thanks for your great tipp :) It works again.
Thanks for anyone working on this project..

As mentioned by Bloodsoul in the file
/appdata_snappymail/_data_/_default_/configs/application.ini
I changed
allow_additional_accounts = On
allow_additional_identities = On
and
allow_admin_panel = On

Seems to work..

!!! THANK YOU, Bloodsoul !!!

**Comment by daffydock** [comment]
I cannot switch accounts, either. All settings on application.ini seem fine.

**Comment by mmallejac** [comment]
In our case, the `application.ini` was totally broken : lot of settings were reset to Off, in particular the one mentioned in this issue by @warumwirleben but also `attachment_size_limit` was set to 0, `attachment_size_limit` to off...
See #1618 , I had to revert to 2.36.1

I'd say half of the settings were out, and most of them are settings that we do not modify !
@the-djmaze : I can PM you the file before and after if necessary.
