### ISSUE TITLE
Authentication Failed @ Nextloud 2.36.2

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#1602]
**Describe the bug**
Unable to login after updating Snappymail - Nextcloud to 2.36.2

**To Reproduce**
1. Update to 2.36.2 from a prior version.
2. Attempt to login using confirmed correct credentials
3. Observe unable to authenticate error

**Expected behavior**
Snappymail returns an unable to authenticate error

**Screenshots**
![https://cdn.thecutefoxxy.com/WwNuuA.png](https://cdn.thecutefoxxy.com/WwNuuA.png)

**Please complete the following information:**
- Browser: Firefox 126
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.36.2
- Mode: Nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
`Undefined variable $aTokenData at /usr/share/nginx/nextcloud/apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php#345`

**Additional context**
Appears to be similar to other issues reported and we have no clear way to rollback with Nextcloud like we can on a standalone or cpanel instance.

**Comment by majick** [comment]
Note that manually applying df1e592 has not actually fixed this for me; the error in your log is a red herring as best I can tell — whatever is broken with this new update may be more than that.

**Comment by schmidt1024** [comment]
Confirm issue on Nextcloud Hub 8 (29.0.1) with SnappyMail 2.36.2 - Same debug info (see above)

**Comment by schmidt1024** [comment]
Related https://github.com/the-djmaze/snappymail/issues/1598

**Comment by HenkVirtual** [comment]
the same here, from what i can see, it strips the domain-part from the loginname

**Comment by the-djmaze** [comment]
Found the problem!

Go to Nextcloud -> Admin -> Additional Settings -> SnappyMail Admin -> Extensions.
Then update the Nextcloud extension to 2.36.1

Uri like: `/nextcloud/apps/snappymail/?admin#/packages`

When only 2.36 is available, clear the cache at `nextcloud/data/appdata_snappymail/_data_/_default_/cache/`

**Comment by ToBeHH** [comment]
Still does not work for me.
In my mailserver logfile, I see the auth is being tried with just the `username`. However, my mailserver requires `username@domain`. The `@domain` is removed by SnappyMail. I know there are certain options in the admin panel, but they have no effect. Problem only occurred since 2.36.2, has been working flawlessly since yesterday.

**Comment by extobi** [comment]
My Extension is the Version 2.36.1 and it don't work. and the latest version 2.36.3 don't resolve the problem.

**Comment by dmitrystu** [comment]
By the way, the domain test works well.

**Comment by HeldvonKosmos** [comment]
There is a new version uploaded [2.36.3](https://snappymail.eu/repository/nextcloud/snappymail-2.36.3-nextcloud.tar.gz). I will try it, when it will be available for my nextcloud instance.

**Comment by dmitrystu** [comment]
Same issue with v2.36.3

**Comment by cwm77** [comment]
> Same issue with v2.36.3

Same here.

**Comment by Piefje01** [comment]
Done upgrade to new snappy, but still cannot login.  Nc29.* 

<html>
<body>

Undefined variable $sEmail at /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.36.3/app/libraries/RainLoop/Actions/AdminDomains.php#74
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Bloodsoul** [comment]
> Found the problem!
> 
> Go to Nextcloud -> Admin -> Additional Settings -> SnappyMail Admin -> Extensions. Then update the Nextcloud extension to 2.36.1
> 
> Uri like: `/nextcloud/apps/snappymail/?admin#/packages`
> 
> When only 2.36 is available, clear the cache at `nextcloud/data/appdata_snappymail/_data_/_default_/cache/`

I tried to follow this after accessing the admin site before and could not reach it anymore. I always get redirected to the nextcloud dashboard. Anyhow, the mail login worked afterwards. But I still cannot acces the admin site anymore.

**Comment by Piefje01** [comment]
How do it this in AIO version?

**Comment by martintm86** [comment]
Same Problem here.

**Comment by Bloodsoul** [comment]
> Uninstalling the nextcloud integration plugin in `/nextcloud/apps/snappymail/?admin#/packages` helped for the time being. It was @2.36.1 before I removed it. Special case here: Users do not use any of their nextcloud credentials to log into mail, so any integration that would be provided by the plugin on that side was not useful for me. If you depend on that, uninstalling the plugin might break login. YMMV

Thats it! The plugin vanished too. That's why I was able to log in again :)

**Comment by the-djmaze** [comment]
I'm working on this.

The integration became very complex due to all the different Nextcloud setups and user preferences.

I'm going to test the following:
- `nextcloud/settings/user` Email address set and use for IMAP/SMTP login
- `nextcloud/settings/user` Email address set and NOT use for IMAP/SMTP login
- Nextcloud login use for IMAP/SMTP login
- Don't use Nextcloud login at all

And set priorities:
1. user-defined credentials
2. Nextcloud (username or email) + pass (or OIDC)

**Comment by Piefje01** [comment]
Uninstall Snappy, install again
Server bericht: AUTHENTICATE failed
Unbox Extensions
<html>
<body>

InvalidArgumentExceptionProvider snappymail is unknown
--



</body>
</html>

<html>
<body>

InvalidArgumentExceptionProvider snappymail is unknown
--



</body>
</html>

**Comment by extobi** [comment]
> Uninstalling the nextcloud integration plugin in `/nextcloud/apps/snappymail/?admin#/packages` helped for the time being. It was @2.36.1 before I removed it. Special case here: Users do not use any of their nextcloud credentials to log into mail, so any integration that would be provided by the plugin on that side was not useful for me. If you depend on that, uninstalling the plugin might break login. YMMV

yes this works, thanks :)

**Comment by the-djmaze** [comment]
I've tested and removed some changes that were made by other requests.
It should be the old behavior again now with v2.36.2 of the extension.

**Comment by juliadin** [comment]
I can confirm that with 2.36.3 of the nextcloud extension and 2.36.2 of the snappymail nextcloud integration extension I can login again normally. Thank you for your swift action! <3

**Comment by croulibri** [comment]
Thanks also for your quick reaction, everything is working again on my side also.
Just to contribute: in my case, I don't use Nextcloud login at all but I do appreciate Nextcloud addressbook integration into Snappymail (very useful for me).
Good luck and many thanks in advance for future evolution of Snappymail 🤗

**Comment by Piefje01** [comment]
I dont see 2.36.3

**Comment by daniu-de** [comment]
I still cannot login with 2.36.3

**Comment by majick** [comment]
The updated 2.36.3 Nextcloud "App" does resolves my issue, and the unchecked "Use 'short' login" setting is now being obeyed when that setting should be disabled. This causes Dovecot to actually receive the correct (full) username now.

**Comment by dagtk05** [comment]
> The updated 2.36.3 Nextcloud "App" does resolves my issue, and the unchecked "Use 'short' login" setting is now being obeyed when that setting should be disabled. This causes Dovecot to actually receive the correct (full) username now.

Thanks friend, it helped me too.

**Comment by Piefje01** [comment]
I dont see 2.36.3

**Comment by HeldvonKosmos** [comment]
For me the 2.36.3 update solved it.

**Comment by Piefje01** [comment]
I think its related to 

{"reqId":"eQ6zCuQjxaluqo6gOmzm","level":3,"time":"2024-05-27T16:25:03+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 158, arguments: null)","userAgent":"--","version":"29.0.1.1","exception":{"Exception":"TypeError","Message":"OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\FileInfo given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":92,"function":"getVersionFolderForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":81,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":60,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":78,"message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 158, arguments: null)","exception":[],"CustomMessage":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 158, arguments: null)"},"id":"6654a4cb725a7"}

**Comment by Piefje01** [comment]
Oke i got it, go to personal settings and set the password for snappy mail

**Comment by HenkVirtual** [comment]
2.36.3 solved the problem on the frontend, but now I cannot get to the snappymail webadmin panel. I see the adminpanel starting but then it opens the nextcloud dashboard. In the meanwhile I managed to set the setting manually in the application.ini but it would be nice to get the webadminpanel going again.

**Comment by Bloodsoul** [comment]
> 2.36.3 solved the problem on the frontend, but now I cannot get to the snappymail webadmin panel. I see the adminpanel starting but then it opens the nextcloud dashboard. In the meanwhile I managed to set the setting manually in the application.ini but it would be nice to get the webadminpanel going again.

There is a way to activate it again. https://github.com/the-djmaze/snappymail/issues/1601

**Comment by cm-schl** [comment]
> Hi, not fully sure if it is related. I updated to 2.36.3 and I will seemingly get hit with a password prompt which sometimes it will take, sometimes it won't. Also, if I want to check my folder or if I want to change to switch to a different address, it will either hang forever, or I will the following error:
> 
> "Your login passphrase has changed. Please fill in your old login passphrase to decrypt data"
> 
> It really does matter if I enter the current, or previous password. It will maybe go away for a few seconds and then it will pop up again. I am not able to switch accounts. However, if I press cancel on the prompt, it will let me access the folder of the account Snappymail defaults open to. As per OP, on 2.36.2, I was being prompted by a password and despite entering it, it would simply not take.

Not sure what is the source of your problem and how you're using SnappyMail but you could try this: https://github.com/the-djmaze/snappymail/issues/1570 . **But** keep in mind that deleting the .cryptkey file deletes all passwords of all your mailboxes and your gpg keys. So it depends on your situation if you can try this without loosing data.

**Comment by daffydock** [comment]
> > Hi, not fully sure if it is related. I updated to 2.36.3 and I will seemingly get hit with a password prompt which sometimes it will take, sometimes it won't. Also, if I want to check my folder or if I want to change to switch to a different address, it will either hang forever, or I will the following error:
> > "Your login passphrase has changed. Please fill in your old login passphrase to decrypt data"
> > It really does matter if I enter the current, or previous password. It will maybe go away for a few seconds and then it will pop up again. I am not able to switch accounts. However, if I press cancel on the prompt, it will let me access the folder of the account Snappymail defaults open to. As per OP, on 2.36.2, I was being prompted by a password and despite entering it, it would simply not take.
> 
> Not sure what is the source of your problem and how you're using SnappyMail but you could try this: #1570 . **But** keep in mind that deleting the .cryptkey file deletes all passwords of all your mailboxes and your gpg keys. So it depends on your situation if you can try this without loosing data.

I have no certain idea why this started happening. With my admin account having issues with switching email IDs while the user ID I use for my own stuff worked without issues, until the last 2 updates. This is why I changed the password on one of the ID's, which I believe made the issue more obtuse. Nevertheless, I tried the fix on #1570 and while less than optimal to input all the passwords back, it seems to be working now. I am now able to log on and switch accounts without issues or any prompts.

**Comment by Piefje01** [comment]
Still the icon is nog good, you must click next to the mail icon to go to snappy. Otherwise it opens a different menu

**Comment by daniu-de** [comment]
> I still cannot login with 2.36.3

sorry - no idea why but after trying again it did work for me ...

**Comment by nmk-freelance** [comment]
After updating to 2.36.3, it did not work for me. But only recently, I came across the Nextcloud extension which you may find under Extensions in the admin panel. It says it could be updated to 2.36.2. The extension was 2.36.1. So I downloaded the updated and tried to log in again and it just worked.

**Comment by mmallejac** [comment]
On a server we have also experienced this issue, since a user had to add an email account to his own.

So we did:
- 2.36.1 -> 2.36.3 update (without 2.36.2 step)
- unable to login again
- cleared the `cache` folder as suggested by @the-djmaze has resolved this, BUT we had to put another time the main mail password in the Snappymail login page even though it was set in the Nextcloud settings
- found `Crypt[WARNING]: Decrypt() invalid $data or $key` in the logs

**Comment by elhananjair** [comment]
@the-djmaze I have the same issue here, 
 I have set up IMAP and SMTP correctly and tested them, and it shows successful but when I try to add an account on snappymail, the "Authentication Failed" Error shows up. 
 
 
![image](https://github.com/user-attachments/assets/e8661f97-2bca-4cf2-9cd4-d079ad9bf70f)
