### ISSUE TITLE
How to view ICS file?

### ISSUE THREAD

**Issue by koffienl** [the-djmaze/snappymail#1603]
I've been using Snappymail for a long time now, but one thing never has worked for me: how do I view an ICS file?
Currently I'm running version 2.36.1 (on Chrome if that matters) and have enabled the plugin 'View ICS' (version 2.1), but that makes no difference.
When a mail has an ICS attached it will only download the file.

It surely should be an option to just view an ICS so you know a date and time for that invitation?

**Comment by the-djmaze** [comment]
The extension creates HTML after the attachments location.
And when an attachment with mime `text/calendar` is found it shows it like this:
![image](https://github.com/the-djmaze/snappymail/assets/3752035/d5c7f8c1-d88c-4083-8892-1dc8ac53b345)

**Comment by koffienl** [comment]
Just tested by sending a teams meeting from my work outlook to my private mail. As always, I only see an attached ICS file.
What am I doing wrong here?

![image](https://github.com/the-djmaze/snappymail/assets/6832264/2bd595b4-9cf0-48a6-b9ce-110961df63b0)
![image](https://github.com/the-djmaze/snappymail/assets/6832264/35b3667f-2f55-49e8-b20f-41de780934dc)

**Comment by the-djmaze** [comment]
Maybe Outlook is not using `text/calendar`?
View the source of the email, it should be something like:

```
--nextPart5703665.DvuYhMxLoT
Content-Disposition: attachment; filename="sample.ics"
Content-Transfer-Encoding: 7Bit
Content-Type: text/calendar; charset="utf-8"; name="sample.ics"

BEGIN:VCALENDAR
```

**Comment by koffienl** [comment]
Looks OK in the source to me?

```--_000_AS2PR10MB715546E44DB0E513B2A6B37FCCF02AS2PR10MB7155EURP_
Content-Type: text/calendar; charset="utf-8"; method=REQUEST
Content-Transfer-Encoding: base64```

**Comment by the-djmaze** [comment]
You can send me the email as attachment to issue-1603@snappymail.eu and i can take a look

**Comment by the-djmaze** [comment]
`Uncaught (in promise) RangeError: invalid time zone in DateTimeFormat(): W. Europe Standard Time`

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
	TZID:W. Europe Standard Time
	BEGIN:STANDARD
		DTSTART:16010101T030000
		TZOFFSETFROM:+0200
		TZOFFSETTO:+0100
		RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
	END:STANDARD
	BEGIN:DAYLIGHT
		DTSTART:16010101T020000
		TZOFFSETFROM:+0100
		TZOFFSETTO:+0200
		RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
	END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
	DTSTART;TZID=W. Europe Standard Time:20240528T093000
	DTEND;TZID=W. Europe Standard Time:20240528T100000
END:VEVENT
END:VCALENDAR
```

I will create a VTIMEZONE handler

**Comment by the-djmaze** [comment]
I've added a mapping from Windows timezones to the global IANA registered timezones.
