### ISSUE TITLE
invalid radix64 character 2D skipped / read_block: read error: Invalid packet

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#1608]
**Describe the bug**

JavaScript `alert()` pop-up with errors when replying to an email : 

```
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
invalid radix64 character 2D skipped.
[don't know]: invalid packet (ctb=04).
read_block: read error: Invalid packet
```

**To Reproduce**

1. Just reply to the specific email.

Let me know if you need specific header or content from this email to reproduce.

In fact, I don't know how to reproduce because if I try to reply again to the email, it works. Related to network error ?

**Expected behavior**

No pop-up and the error is handled !

**Screenshots**

**Please complete the following information:**

- Browser: Firefox
- SnappyMail Version: 2.36.3
- Mode: standalone

**Comment by the-djmaze** [comment]
Sounds like a problem with PGP/GPG as if the it can't import keys or decrypt message or verify signed message.

So do you use encryption?

**Comment by Massedil** [comment]
> So do you use encryption?

No.

**Comment by Massedil** [comment]
> > So do you use encryption?
>
> No.

At least I don't remember having done anything to activate it, but may be some default options are activated. But I don't have a pgp key configured for my account. But I sometimes receive pgp signed emails. Maybe I opened a signed email before trying to reply to another and got this error.

**Comment by the-djmaze** [comment]
The problem is the Autocrypt header of the email.
When you reply, the Autocrypt header is parsed and the PGP key is imported on the server and in OpenPGP.js

https://github.com/the-djmaze/snappymail/blob/614c7ace445074ff20f7a8d3f6afbb8eba151f73/dev/View/Popup/Compose.js#L914-L921

So something is wrong with the Autocrypt header.
Can you forward such email to me?
To issue-1608@snappymail.eu is fine

**Comment by Massedil** [comment]
> Can you forward such email to me?

I sent by email the problematic Autocrypt header to you. Let me know !

**Comment by the-djmaze** [comment]
Could you send the whole message and not just the Autocrypt header?

**Comment by Massedil** [comment]
I just sent you a whole message that triggers the problem described here. Let me know !

**Comment by the-djmaze** [comment]
The Autocrypt header ends with `nrzCXopEosI=`
But the javascript code `.split('=')` and `.split('=', 2)`  dropped the last `=` and failed.
