### ISSUE TITLE
v2.9.2 - upgrade problem

### ISSUE THREAD

**Issue by tomasz-c** [the-djmaze/snappymail#161]
**SnappyMail version, browser, browser version:**
v2.9.2, upgrade from v2.9.0
Chrome v96, Linux

**Server:**
PHP 8.0.12 (fpm) + Nginx

**Expected behavior and actual behavior:**
When trying to log in, the page freezes and does not load.

**Steps to reproduce the problem:**
Update snappymail and try to log in

**Logs or screenshots:**
`2021/11/17 18:31:24 [error] 123855#123855: *30 FastCGI sent in stderr: "PHP message: Call to protected method RainLoop\Actions::SetAccounts() from scope SnappyMail\Upgrade" while reading response header from upstream, client: 192.168.1.1, server: test.localhost, request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "test.localhost"
2021/11/17 18:31:51 [error] 123855#123855: *30 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.1, server: test.localhost, request: "GET /?/Json/&q[]=/0/Message/&q[]=/... HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "test.localhost"
2021/11/17 18:32:06 [error] 124137#124137: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to protected method RainLoop\Actions::setContactsSyncData() from scope SnappyMail\Upgrade in ./webmail/snappymail/v/2.9.2/app/libraries/snappymail/upgrade.php:101
Stack trace:
#0 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Actions/Contacts.php(281): SnappyMail\Upgrade::ConvertInsecureContactsSync()
#1 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Actions.php(895): RainLoop\Actions->getContactsSyncData()
#2 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/ServiceActions.php(842): RainLoop\Actions->AppData()
#3 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/ServiceActions.php(596): RainLoop\ServiceActions->localAppData()
#4 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Service.php(136): RainLoop\ServiceActions->ServiceAppData()
#5 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->R" while reading response header from upstream, client: 192.168.1.1, server: test.localhost, request: "GET /?/AppData/0/3117326216992631/ HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "test.localhost"
`

**Comment by the-djmaze** [comment]
Thanks for reporting!
I've fixed the issue

**Comment by tomasz-c** [comment]
Thank you for the fix!
I encountered one more error, it only occurs if the option is enabled:
```
[contacts]
; Enable contacts
enable = On
allow_sync = On
```

Then again the page freeze when trying to log in. If `allow_sync` is disabled this error does not occur and the update runs fine and everything seems to work well.

Log:
```
2021/11/18 00:52:38 [error] 135551#135551: *66 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method RainLoop\Model\AdditionalAccount::CryptKey() in ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Actions/Contacts.php:245
Stack trace:
#0 ./webmail/snappymail/v/2.9.2/app/libraries/snappymail/upgrade.php(101): RainLoop\Actions->setContactsSyncData()
#1 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Actions/Contacts.php(281): SnappyMail\Upgrade::ConvertInsecureContactsSync()
#2 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Actions.php(895): RainLoop\Actions->getContactsSyncData()
#3 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/ServiceActions.php(842): RainLoop\Actions->AppData()
#4 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/ServiceActions.php(596): RainLoop\ServiceActions->localAppData()
#5 ./webmail/snappymail/v/2.9.2/app/libraries/RainLoop/Service.php(136): RainLoop\ServiceAction" while reading response header from upstream, client: 192.168.1.1, server: test.localhost, request: "GET /?/AppData/0/9980990375878018/ HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "test.localhost"
```
