### ISSUE TITLE
Add new account - Your login passphrase has changed. Please fill in your old login passphrase to decrypt data

### ISSUE THREAD

**Issue by warumwirleben** [the-djmaze/snappymail#1613]
**Describe the bug**
If I try to add a new mailbox, the message "Your login passphrase has changed. Please fill in your old login passphrase to decrypt data" appears. After entering the username and password there is a loop - nothing happens.

**To Reproduce**
1. Go to Add Account (or however it is called)
2. Enter eMail, Password and Name
3. Click Add

**Expected behavior**
Please add my account.

**Screenshots**
not needed

**Please complete the following information:**
- Browser: Chrome
- SnappyMail Version: 2.36.3
- Mode: nextcloud

**Comment by warumwirleben** [comment]
https://github.com/the-djmaze/snappymail/issues/1613

**Comment by the-djmaze** [comment]
And what kind of Nextcloud login do you use?

Because login passphrases don't change unless you use OIDC or something else that changed the passphrase.

**Comment by the-djmaze** [comment]
> What could I do if I do not have the old password?

Delete all configured additional accounts and backup PGP keys.
Also delete the `.cryptkey` file on the filesystem.

**Comment by warumwirleben** [comment]
Thank you - SOLVED :)

**Comment by chsleemsi** [comment]
I have the same problem.  Where can I find the .cryptkey file?
