### ISSUE TITLE
Add account button has gone away / other acccounts are no longer accessible

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1614]
Also since 2.36.1 -> 2.36.2 -> 2.36.3 upgrade, we no longer see :
- the add account button is no longer visible
- the other accounts already configured, only the main one

Now the menu looks like this:

![image](https://github.com/the-djmaze/snappymail/assets/11666281/c1ffb1ed-808e-4a91-a9be-02919d7896b7)

I've tried to downgrade from 2.36.3 to 2.36.1 but Nextcloud does not allow this :-\

**Comment by the-djmaze** [comment]
`nextcloud/apps/snappymail/?admin#/general`
Is `Allow additional accounts` on?

**Comment by mmallejac** [comment]
It is off !
How come ? Is this a newly created parameter that is off by default ?

**Comment by the-djmaze** [comment]
> How come ?

I have no idea.

> Is this a newly created parameter that is off by default ?

No, it even exists in RainLoop

**Comment by mmallejac** [comment]
Ok, thanks !

I am trying to figure out what would be the best way to handle the modifications done on `application.ini` version after version, along with the settings we want to have in it.

I've tried to find the vanilla file within the github repo, but it seems that the file is generated ?

So far what I've done is a script using `crudini` that is being run after each `docker compose up`. This script sets the value of the settings we modify from the default value. We do that since we maintain many Nextcloud + Snappymail instances.

Now I realize that we should maybe set all values to be sure not to loose stuff like `allow_additional_accounts` ?

How is the file modified when Snappymail is being updated ?

Thanks for your help !
