### ISSUE TITLE
“Unseen” checkbox “forgets” status when browser tab closes or alternate account is selected

### ISSUE THREAD

**Issue by truthsword** [the-djmaze/snappymail#1615]
**Describe the bug**
“Unseen” checkbox “forgets” status when browser tab closes or alternate account is selected

**To Reproduce**
1. Tick Unseen checkbox
2. Change view to alternate email2 account (or close browser tab)
3. Return to original email1 view
4. Unseen checkbox is unticked

**Expected behavior**
 Unseen checkbox remains ticked unless manually unticked.

**Please complete the following information:**
- Browser: Librefox 126.0-1
- docker container

**Comment by the-djmaze** [comment]
Correct, it "forgets" because there is no code to remember it.
It was implemented for #1427

**Comment by truthsword** [comment]
Got it.Thanks!
