### ISSUE TITLE
SSO example

### ISSUE THREAD

**Issue by wojtekschoen** [the-djmaze/snappymail#1616]
Hi, I'm trying to use the Login External SSO plugin, but with no success.
Rainloop has a beautiful example of SSO logging.
https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example

Can I please have a similar example for SnappyMail?

**Comment by the-djmaze** [comment]
Take a look here https://github.com/the-djmaze/snappymail/blob/master/test/sso.php

**Comment by wojtekschoen** [comment]
Thank you :)

**Comment by mixsmscentral** [comment]
@wojtekschoen Can  you please confirm how did you get this worked (SSO login)? I tried but failed. I want to use this with directadmin interface. I have installed this already but everything working fine but I want to access this with SSO through user panel's email interface.
