### ISSUE TITLE
Snappymail sending notifications while nextcloud user status is DND (Do not disturb)

### ISSUE THREAD

**Issue by lufer22** [the-djmaze/snappymail#1617]
Hello!

**Describe the bug**
I'm receiving desktop notifications while nextcloud user status is DND.
It seems snappymail does not have this integration with nextcloud.

**To Reproduce**
1. Change your status to 'DND' on nextcloud
2. Open Snappmail
3. Send an email to yourself
4. See the notification appear

**Expected behavior**
Snappymail shouldn't send the notification while the nextcloud user status is DND.

**Please complete the following information:**
- Browser: Chrome  122.0.6261.57
- IMAP daemon: dovecot
- PHP version: 8.3
- SnappyMail Version: 2.36.1
- Mode: Nextcloud

**Comment by the-djmaze** [comment]
Correct, there can't be an integration because Nextcloud has no JavaScript API for it.
