### ISSUE TITLE
Search bar default to "text=%s"

### ISSUE THREAD

**Issue by truthsword** [the-djmaze/snappymail#1619]
When using the search bar (without the Advanced Search dropdown) entering text does not "find" related mails.

For example entering `docker` returns no results, whereas entering `text=docker` returns emails containing the word docker.

Since it's likely the unadvanced search is most likely to be used for basic word, or phrase search (IMO), it would be desirable that the search entry box work for `docker` for basic searching.

In addition, it appears that quoted phrases cannot be searched for, in order to locate adjacent words... For example `"docker container"`. Instead, only `text=docker+container` is available.

Thank you!

**Comment by the-djmaze** [comment]
Whic IMAP software is running on the mailserver?

**Comment by truthsword** [comment]
> Whic IMAP software is running on the mailserver?

How would I detect that? This occurs with Gmail.

![](https://i.imgur.com/zXtCGzs.png)
![](https://i.imgur.com/G8IfuoP.png)

**Comment by the-djmaze** [comment]
`application.ini` disable `message_list_fast_simple_search`

**Comment by truthsword** [comment]
Thanks. That worked. The issue was specific to Gmail. Other IMAP servers had no issue with "fast_simple_search"
