### ISSUE TITLE
Spam Score shows wrong tool tip text "Not Spam: 7.3/5"

### ISSUE THREAD

**Issue by realsimix** [the-djmaze/snappymail#162]
**Describe the bug**
Looking at a Spam message, when moving the mouse to the red bar, the tool tip always shows "Not Spam" even in case it is Spam.

**To Reproduce**
The screenshot shows what the issue is, it says "Not Spam: 7.3/5" which clearly means it is Spam:

**Expected behavior**
The tool tip should show something like "Spam: 7.3/5"

**Screenshots**
![Screenshot_2021-11-18_09-14-08](https://user-images.githubusercontent.com/31847983/142378680-bc092fa8-4944-423b-ac20-928f5a076d34.png)

**Desktop (please complete the following information):**
 - Browser [firefox 91.3.0esr]
 - SnappyMail Version [2.9.2]

**Additional info**
The header was generated by SpamAssassin:
```
X-Spam-Flag: YES
X-Spam-Level: *******
X-Spam-Status: Yes, score=7.3 required=5.0 tests=BAYES_00,DKIM_ADSP_NXDOMAIN,
	HTML_IMAGE_ONLY_16,HTML_MESSAGE,HTML_MIME_NO_HTML_TAG,...
```

Thanks,
Simon

**Comment by realsimix** [comment]
Sorry, that doesn't really fix it because now it shows non Spam mails also as "Spam".

**Comment by the-djmaze** [comment]
Does this second change solve it?

**Comment by the-djmaze** [comment]
Examples i found:
```
X-Spam-Status: No, score=2.0
X-Spam-Score: 20
X-Spam-Bar: ++
```
```
X-Spam-Status: No, score=-3.1
X-Spam-Score: -30
X-Spam-Bar: ---
```
```
X-Spam-Status: Yes, score=8.6
X-Spam-Score: 86
X-Spam-Bar: ++++++++
X-Spam-Report: Spam detection software, running on the system "example.com",
 has identified this incoming email as possible spam.  The original
```

**Comment by realsimix** [comment]
Well, Spamassassin can be configured to add all kind of headers but maybe it's good to make sure things work with the default configuration of Spamassasin. From the SA docs:

_Here are some examples (these are the defaults, note that Checker-Version can not be changed or removed):_
```
  add_header spam Flag _YESNOCAPS_
  add_header all Status _YESNO_, score=_SCORE_ required=_REQD_ tests=_TESTS_ autolearn=_AUTOLEARN_ version=_VERSION_
  add_header all Level _STARS(*)_
  add_header all Checker-Version SpamAssassin _VERSION_ (_SUBVERSION_) on _HOSTNAME_
```
So as you can see the example I've shown is what Spasassasin uses by default:
```
X-Spam-Flag: YES
X-Spam-Level: *******
X-Spam-Status: Yes, score=7.3 required=5.0 tests=BAYES_00,DKIM_ADSP_NXDOMAIN,
	HTML_IMAGE_ONLY_16,HTML_MESSAGE,HTML_MIME_NO_HTML_TAG,...
```
The examples you have shown above are NOT from a default Spamassassin installation.

Regards,
Simon

**Comment by the-djmaze** [comment]
You are right, but the check should be 'X-Spam-Status: Yes' to mark is as potential spam.
So the last change should do that

**Comment by realsimix** [comment]
I can confirm it works nicely now.

Thanks!

**Comment by the-djmaze** [comment]
You're welcome
