### ISSUE TITLE
Server message: Can't connect to host "ssl://localhost:993

### ISSUE THREAD

**Issue by mxsmarcos** [the-djmaze/snappymail#1621]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:8.0
- SnappyMail Version:
- Mode: cyberpanel

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)

**Additional context**
Quando tento conectar no webmail aparece essa mensagem, eu estou usando ele via Cyberpanel, já instalei o ssl, e fiz toda a configuração no DNS mais não consigo resolver isso 
![Screenshot_15](https://github.com/the-djmaze/snappymail/assets/61959323/0d304362-a38a-4f3e-9ab1-e1c8ceec943e)

**Comment by the-djmaze** [comment]
Please read https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#menu-domains
