### ISSUE TITLE
Possibility to form email threads from Inbox and Sent folders, possibly Archive too

### ISSUE THREAD

**Issue by CapSel** [the-djmaze/snappymail#1624]
**Is your feature request related to a problem? Please describe.**
A possibility to show email threads with messages from Inbox and Sent. So I could see what was the reply.

**Describe the solution you'd like**
Ability to show all messages from chosen folders would help in situations when email threads take a long time and a lot of messages. Adding "Archive" and "Sent" folder would make it gmail like ;)

**Describe alternatives you've considered**
kmail uses "unified folder" for such things - so the Inbox is left as it is and a virtual folder is created that shows messages from linked folders.

**Comment by the-djmaze** [comment]
This is asked before and not possible.
But... if you control the mailserver you could configure a virtual "all" mailbox.
See other issues here related to your question and the Dovecot manual.
