### ISSUE TITLE
Filter not working as expected.

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#1626]
**Describe the bug**
I added a filter to reject email from specific domain let say gmail.com but i still recieving mail from gmail

**To Reproduce**
1. Go to snappy. mail
2. Click on Settings
3. click on Filters
4. click on rainloop.user
5. Add filter
6. 
![ssssss](https://github.com/the-djmaze/snappymail/assets/21700809/a7b6cf43-7e2d-411e-ad38-9c574b850152)

```
require ["reject"];

# This is SnappyMail sieve script.
# Please don't change anything here.
# RAINLOOP:SIEVE

if header :contains ["From"] "gmail.com"
{
    reject "Not needed";
    stop;
}

/* END:FILTER */

```

**Comment by the-djmaze** [comment]
Is the script active?

**Comment by avinash-0007** [comment]
@the-djmaze its fixed. thanks
