### ISSUE TITLE
Can't login with new QNAP users

### ISSUE THREAD

**Issue by fabioxavi** [the-djmaze/snappymail#1627]
**Describe the bug**
When I login with users previously created in QNAP, it goes straight to the mailbox.
If I try to login with a new user, it opens the login page again with the user and password files cleared.
![image](https://github.com/the-djmaze/snappymail/assets/171922944/2f272c08-fd7a-4863-bed7-56876fbd53b5)

If I fill the password with a wrong password on purpose, at least it gives me an error:
![image](https://github.com/the-djmaze/snappymail/assets/171922944/7cfe17cf-e27b-449f-a57b-2c599570372c)

**To Reproduce**
1. Go to 'http://server:51322/'
2. Fill user and password
3. Click on 'Login'
4. It returns to login page and the fields are empty

![image](https://github.com/the-djmaze/snappymail/assets/171922944/2f272c08-fd7a-4863-bed7-56876fbd53b5)

**Expected behavior**
It is expected to enter the Mailbox as usual

**Please complete the following information:**
- Browser: [chrome and firefox]
- IMAP daemon: [dovecot]
- PHP version: 8.3.4
- SnappyMail Version: 2.36.3
- Mode: [QNAP]

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)

**Comment by the-djmaze** [comment]
You forgot to add the logs

**Comment by fabioxavi** [comment]
[2024-06-21 11:12:47.486][5561d3c2] IMAP[ERROR]: Stream Meta: Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.3
            [cipher_name] => TLS_AES_256_GCM_SHA384
            [cipher_bits] => 256
            [cipher_version] => TLSv1.3
        )

    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
    [uri] => tcp://nas1:143
)

[2024-06-21 11:12:47.486][5561d3c2] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException in /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Net/NetClient.php:275
Stack trace:
#0 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch()
#2 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/ImapClient.php(499): MailSo\Imap\ImapClient->partialParseResponse()
#3 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/ImapClient.php(443): MailSo\Imap\ImapClient->getResponse()
#4 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/ImapClient.php(249): MailSo\Imap\ImapClient->SendRequestGetResponse()
#5 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Net/NetClient.php(182): MailSo\Imap\ImapClient->Logout()
#6 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Net/NetClient.php(45): MailSo\Net\NetClient->Disconnect()
#7 [internal function]: MailSo\Net\NetClient->__destruct()
#8 {main}
[2024-06-21 11:12:47.528][111460e7] IMAP[ERROR]: Stream Meta: Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.3
            [cipher_name] => TLS_AES_256_GCM_SHA384
            [cipher_bits] => 256
            [cipher_version] => TLSv1.3
        )

    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
    [uri] => tcp://nas1:143
)

[2024-06-21 11:12:47.529][111460e7] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException in /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Net/NetClient.php:275
Stack trace:
#0 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch()
#2 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/ImapClient.php(547): MailSo\Imap\ImapClient->partialParseResponse()
#3 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Commands/Folders.php(514): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#4 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Commands/Folders.php(614): MailSo\Imap\ImapClient->FolderList()
#5 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Mail/MailClient.php(906): MailSo\Imap\ImapClient->FolderStatusList()
#6 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Actions/Folders.php(57): MailSo\Mail\MailClient->Folders()
#7 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoFolders()
#8 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#9 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#10 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/include.php(136): RainLoop\Service::Handle()
#11 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/index.php(11): include('...')
#12 {main}
[2024-06-21 11:12:47.529][111460e7] SERVICE[WARNING]: 
#0 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch()
#2 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/ImapClient.php(547): MailSo\Imap\ImapClient->partialParseResponse()
#3 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Commands/Folders.php(514): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#4 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Imap/Commands/Folders.php(614): MailSo\Imap\ImapClient->FolderList()
#5 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/MailSo/Mail/MailClient.php(906): MailSo\Imap\ImapClient->FolderStatusList()
#6 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Actions/Folders.php(57): MailSo\Mail\MailClient->Folders()
#7 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoFolders()
#8 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#9 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#10 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/snappymail/v/2.36.3/include.php(136): RainLoop\Service::Handle()
#11 /share/CACHEDEV1_DATA/.qpkg/Snappy83/www/index.php(11): include('...')
#12 {main}

**Comment by fabioxavi** [comment]
[log-2024-06-21.txt](https://github.com/user-attachments/files/15926787/log-2024-06-21.txt)

**Comment by fabioxavi** [comment]
> You forgot to add the logs

Sorry.

Log is now uploaded

**Comment by fabioxavi** [comment]
[log-2024-06-21.txt](https://github.com/user-attachments/files/15926823/log-2024-06-21.txt)

This log has 3 attempts to login:

1st - An user that was previously configured and had already logged in the past - The issue happened;
2nd -  An user that was previously configured and had already logged in the past - Logged in normally
3rd - A new user - The issue happened

**Comment by fabioxavi** [comment]
[log-2024-06-21.txt](https://github.com/user-attachments/files/15927158/log-2024-06-21.txt)

Here is the log in 7 - debug mode

**Comment by the-djmaze** [comment]
Your server has issues. it says:
```
< * BYE Internal error occurred. Refer to server log for more information.\r\n
```

So check why the QNAP IMAP server is failing.
