### ISSUE TITLE
CardDAV settings are not saved -> CardDAV sync broken

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#163]
When I set my CardDAV configuration (URL, user, password), it disappears after logout/login
When I try to do a CardDAV sync, I get a sync error popup, the log file doesn't show any reference to the sync URL

v2.5.2 with same configuration worked fine.

1. Set a CardDAV sync configuration
2. Test sync => don't work
3. Logout / login => the CardDAV configuration has not been set

**Expected behavior**
CardDAV configuration should be saved and sync should work.

**Desktop (please complete the following information):**
 - Firefox 91.3 ESR
 - SnappyMail Version 2.9.3

**Additional context**
I was thinking about config file permission but my "settings" file is modified when I change the number of messages per page (22 in this example) : 
{"Language":"fr-FR","MPP":22}
However, when I go to General config, the message per page displayed is the default one (20)

**Comment by m-i-k-e-y** [comment]
I think this is a more general issue than just CardDav sync. 

With the latest version of Snappymail I noticed that none of the settings that I change for an account is applied after login (for example: horizontal vs. vertical view mode, seconds after which a message is marked as read, should images be displayed, etc.). I have to change the settings every time I log in into an account. 

Just as @Mer0me I can see that the settings file (in `data/_data_/_default_/storage/<domain>/<account>)` for the account is updated when I change a setting and the changed setting is applied, but only as long as as stay logged in. As soon as I log out and log in again, the settings are not applied although the settings file is still there with the changed values from the last time (timestamp of the file does not change until I change the values again).

**Comment by the-djmaze** [comment]
I will check carddav.
Settings lost is fixed in https://github.com/the-djmaze/snappymail/commit/e6145249fa34fec88ed491c24391ee58b31765e9

Issue is caused by new login system that doesn't need reload of all assets.
RainLoop did a forced reload/f5/refresh which caused additional server requests to ask everything again.
I was testing this until i discovered the security vulnerability.

Will do some more testing because next release also fully supports UTF8 IMAP servers like Courier.

**Comment by phsc84** [comment]
Would also be happy to test as soon as a new release is ready. :-)

**Comment by the-djmaze** [comment]
v2.9.4 released. you could test if it works

**Comment by m-i-k-e-y** [comment]
Thumbs up, settings are working again!

I will test card-dav sync later today.

Thanks a lot @the-djmaze

**Comment by m-i-k-e-y** [comment]
CardDav sync doesn't work for me. I get an error in the UI when I hit the synchronize button and I found these errors in the logfile of nginx:

`2021/12/02 15:18:24 [error] 1196901#1196901: *10655 FastCGI sent in stderr: "PHP message: Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in /var/www/snappymail/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Contacts.php on line 30" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/02 15:18:32 [error] 1196901#1196901: *10655 FastCGI sent in stderr: "PHP message: Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in /var/www/snappymail/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Contacts.php on line 30" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/02 15:18:36 [error] 1196901#1196901: *10655 FastCGI sent in stderr: "PHP message: Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in /var/www/snappymail/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Contacts.php on line 30" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/02 15:18:47 [error] 1196901#1196901: *10655 FastCGI sent in stderr: "PHP message: Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in /var/www/snappymail/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Contacts.php on line 30" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/02 15:19:25 [error] 1196901#1196901: *10655 FastCGI sent in stderr: "PHP message: ContactsSyncError[140]" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
`

**Comment by m-i-k-e-y** [comment]
@the-djmaze:

I applied your latest commit, the error messages I posted previously are gone but I have these now in the nginx logs:

`2021/12/05 12:04:58 [error] 1677434#1677434: *1 FastCGI sent in stderr: "PHP message: Cannot use object of type stdClass as array" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/05 12:05:02 [error] 1677434#1677434: *1 FastCGI sent in stderr: "PHP message: Cannot use object of type stdClass as array" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
2021/12/05 12:05:05 [error] 1677434#1677434: *1 FastCGI sent in stderr: "PHP message: Cannot use object of type stdClass as array" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"`

Server is running Debian 11 (Bullseye) with nginx 1.18.0 and php(-fpm) 7.4 if that makes any difference.

**Comment by the-djmaze** [comment]
Could you try with v2.9.6?
https://github.com/the-djmaze/snappymail/releases/tag/v2.9.6

**Comment by m-i-k-e-y** [comment]
I tried v2.9.6 and CardDav sync seems to be working again, no errors found in the logfile on nginx.

Thanks @the-djmaze

**Comment by Mer0me** [comment]
CardDav sync works here too with 2.9.6. I close this one too. Thanks !
