### ISSUE TITLE
Gravatar GDPR thingy

### ISSUE THREAD

**Issue by MrKeiKun** [the-djmaze/snappymail#164]
**Is your feature request related to a problem? Please describe.**
Like my server and I aren't part of the GDPR. Can you make a setting allowing gravatar work for likes of me?

**Comment by the-djmaze** [comment]
Als a Gravatar breach https://haveibeenpwned.com/PwnedWebsites#Gravatar

**Comment by the-djmaze** [comment]
Late, but after more debate and ideas, it is added as extension/plugin
