### ISSUE TITLE
Feature request for Microsoft Exchange OAuth2

### ISSUE THREAD

**Issue by chascode** [the-djmaze/snappymail#1645]
Microsoft are dropping support for app passwords in September.

With an extension similar to "GMail OAuth2" (where I enter my client id/secret provided by Microsoft) I can still use snappymail after September.

I've considered using DavMail (available in debian's default repositories) as a gateway between snappymail and Microsoft's exchange servers.

**Comment by the-djmaze** [comment]
I was looking at it a few weeks ago, but had some trouble with it due to other changes Microsoft is making.

Will document my draft code and see what can be done.

**Comment by the-djmaze** [comment]
I've added my draft code.
Microsoft requires an Azure account that has an active subscription.
I'm not going to pay, so feel free to get the code working yourself.

**Comment by the-djmaze** [comment]
TODO issue:
```
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
```

**Comment by the-djmaze** [comment]
For experimental usage with SnappyMail v2.36.5+:
https://github.com/the-djmaze/snappymail/tree/master/plugins/login-o365

**Comment by GregThib** [comment]
Hi!

This workaround seem to introduce a new failure: under Apache 2.4+, without mod_access_compat, giving a 500 error when trying to connect.
The Allow directive is obsolete and should not be employed now.

Maybe, a fix is to test the presence of mod_access_compat, and if not, use Require instead?

**Comment by the-djmaze** [comment]
@GregThib sorry, my bad. That rule shouldn't be in and i removed it.

**Comment by GregThib** [comment]
> @GregThib sorry, my bad. That rule shouldn't be in and i removed it.

No problem, I use the in-dev version via git fetch, so these kinds of "bugs" are normal outside tagged versions.
I just wanted to prevent, in case the faulty code remain later.

**Comment by the-djmaze** [comment]
Ok, back to the drawing board.
It killed the Nextcloud integration #1703
