### ISSUE TITLE
Avaters plugin: Favicon avater is displayed with message not DKIM signed

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1656]
Mail system of my home network is configured so only messages sent to external public network are DKIM signed. So messages deliverd inside the network aren't signed. But Avaters plugin displays favicon avater with such messages.

Environment is:

* FreeBSD 14.1-RELEASE amd64
* Dovecot 2.3.21
* Apache HTTP server 2.4.61
* PHP 8.3.8
* SnappyMail 2.36.4
* Avaters plugin 1.18

The issue happens with all of Google Chrome, Microsoft Edge and Mozilla Firefox. So it seems to have nothing to do with web browser.

**Comment by the-djmaze** [comment]
Can you show screenshot of the issue?
