### ISSUE TITLE
How to Import Mails of extension .MBOX or .MIML

### ISSUE THREAD

**Issue by serververs** [the-djmaze/snappymail#1659]
Actually I'm Thinking to transfer my whole mails from Hostinger Mail to Snappymail in Cyberpanel. If it is Possible please let me Know!

**Comment by the-djmaze** [comment]
You can try with [imapsync.php](https://github.com/the-djmaze/snappymail/wiki/imapsync.php)

**Comment by serververs** [comment]
Okay Let me Try
