### ISSUE TITLE
Can't change Mailbox

### ISSUE THREAD

**Issue by Psychi1** [the-djmaze/snappymail#166]
**Describe the bug**
After upgrade snappymail from 2.6.0 to 2.9.4 changing the mailbox fails. NGINX throws the following error-message:

```
2021/12/04 11:35:16 [error] 465#465: *35 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index:
 HideUnsubscribed in /var/www/snappy.yyyyy.tld/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Accounts.php on line 
144PHP message: PHP Notice:  Undefined index: UseThreads in /var/www/snappy.yyyyy.tld/snappymail/v/2.9.4/app/libraries
/RainLoop/Actions/Accounts.php on line 145PHP message: PHP Notice:  Undefined index: ReplySameFolder in /var/www
/snappy.yyyyy.tld/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Accounts.php on line 146" while reading response header 
from upstream, client: www.xxx.yyy.zzz, server: snappy.bieling.org, request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: 
"fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "snappy.bieling.org"
```
Used upgrade procedure:

1. download tar.gz release
2. extract tar.gz to folder /var/www/snappy.yyyyy.tld
3. reset permissions ```find /var/www/snappy.yyyyy.tld -type d -exec chmod 755 {} \;
find /var/www/snappy.yyyyy.tld -type f -exec chmod 644 {} \;
chown -R www-data:www-data /var/www/snappy.yyyyy.tld```

**To Reproduce**
1. Login to the account 
2. Click on differnt mailbox
3. See error

**Expected behavior**
I expect the inbox of the selected mailbox, however it remains on the inbox of the login-mailbox.

**Desktop (please complete the following information):**
 - Browser Firefox 94.0
 - SnappyMail Version 2.9.4
 - PHP 7.4
 - Nginx 1.20.2

**Comment by Psychi1** [comment]
I will give more information.

After changing to php 8 an additional error is shown: 

```
2021/12/04 11:52:02 [error] 1276#1276: *175 FastCGI sent in stderr: "PHP message: PHP Notice:  
SnappyMail\Crypt::Decrypt() invalid $data in /var/www/snappy.yyyy.tld/snappymail/v/2.9.4/app/libraries/snappymail/crypt.php on line 64
PHP message: PHP Warning:  Undefined array key "HideUnsubscribed" in /var/www/snappy.yyyy.tld/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Accounts.php on line 144
PHP message: PHP Warning:  Undefined array key "UseThreads" in /var/www/snappy.yyyy.tld/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Accounts.php on line 145
PHP message: PHP Warning:  Undefined array key "ReplySameFolder" in /var/www/snappy.yyyy.tld/snappymail/v/2.9.4/app/libraries/RainLoop/Actions/Accounts.php on line 146" while reading response header from upstream, client: www.xxx.yyy.zzz, server: snappy.yyyy.tld, request: "POST /?/Json/&q[]=/0/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "snappy.yyyy.tld"
```

If I try to access the domain setup from the admin panel, a window tries to open, but nothing is shown. Only a darker screen (the background of the orginal window) appears. The front-windows never appears. (Same for PHP 7.4 and 8.o)

**Comment by the-djmaze** [comment]
Account switch issue is caused by removing the ParentEmail param as it is obsolete by the new secure system.
It worked for me but one of my customers had the same issue as you with 1 account, but not the other.
The following fixed solved it
https://github.com/the-djmaze/snappymail/commit/64e77de10307b7af9d0c419f0124cf54d2ec2d38

**Comment by the-djmaze** [comment]
Could you try with v2.9.6?
https://github.com/the-djmaze/snappymail/releases/tag/v2.9.6

**Comment by Psychi1** [comment]
v2.9.6 is working. So i close this issue.
