### ISSUE TITLE
Google OAuth not possible with nextcloud

### ISSUE THREAD

**Issue by ZambeiCloud** [the-djmaze/snappymail#1663]
**Describe the bug**
I can't login to my gmail account with the OAuth plugin. After the OAuth process, I'm redirected to the redirectUrl which then redirects to /custom_apps/snappymail/app/. The browser here displays "Not inside Nextcloud".

**To Reproduce**
1. Install Google OAuth plugin
2. Click on GMail button on the login screen
3. Click through the OAuth process

**Expected behavior**
I can login with my gmail account through OAuth

**Screenshots**
<img width="513" alt="image" src="https://github.com/the-djmaze/snappymail/assets/170914159/deb8e571-6977-42fd-a6ed-affb7c6f59fe">

**Please complete the following information:**
- Browser: all current browsers
- SnappyMail Version: 2.36.4
- Mode: nextcloud

**Comment by the-djmaze** [comment]
Redirect url of SnappyMail should be `https://...your.domain.../custom_apps/snappymail/?LoginGMail`
Because you access it through `https://...your.domain.../custom_apps/snappymail/`

So check your settings.

**Comment by ZambeiCloud** [comment]
Hi, thanks for your answer. 
It doesn't seem to be an issue with the redirect url. I access snappy mail inside nextcloud through `https://...your.domain.../apps/snappymail`
For testing,  i changed the redirect url in the googe api settings to `https://...your.domain.../custom_apps/snappymail/?LoginGMail` and got the redirect_uri_mismatch error from google. 
<img width="279" alt="image" src="https://github.com/user-attachments/assets/a69af586-fc4e-47ad-b449-19b7949ef3b5">

With `https://...your.domain.../apps/snappymail` after the OAUTH process it's coming back to the correct URL but is immediately redirected to /custom_apps/snappy_mail/app
<img width="862" alt="image" src="https://github.com/user-attachments/assets/691aa874-b341-4244-adee-5f2ca7b9c102">

Thank you for your help!

**Comment by the-djmaze** [comment]
The issue is SnappyMail application.ini `app_path`.
So the change i made might work.
