### ISSUE TITLE
Link of Snappymail Icon points to wrong nextcloud app

### ISSUE THREAD

**Issue by Reis-A** [the-djmaze/snappymail#1671]
**Describe the bug**
After upgrade nc29 (with custom menu app)  and with snappy 2.36.4 
->  problems with the login like many others 
 sometime we would get into snappymail, sometimes we would be stuck on the same page where we pressed the link from. Because of the recent login problems I switched to manual login and saved some of the passwords.

Yesterday I noticed, that whenever I could not get into snappymail, that the tooltip or link when u hover the mouse over the snappy icon on the menubar shows the wrong app! 

Instead of snappy it showed the current active app (most of the time dashboard).
As a workaround I then entered the address https://mynextcloud.com/apps/snappymail directly in the browser. And this worked, I could get  into snappymail this! I am making now an external link to this address as workaround but it would be great if we could find the reason for this weird behavior...

**To Reproduce**
It is hard to reproduce since randomly the original link in the menu bar works, and sometimes it doesn't.
Not sure what plays into that... ( cache / cronjob???)

**Expected behavior**
The icon of the snappymail app in the menu bar should always point to https://mynectcloud.com/apps/snappymail
and nowhere else.

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile] any
- IMAP daemon: [e.g. courier, dovecot] groupies
- PHP version: 8.1
- SnappyMail Version: 2.36.4
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] nextcloud

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
This is a know issue of the latest Nextcloud and is already reported here.
We have no clue why it happens.
