### ISSUE TITLE
Cleaner Filter process for end user

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1675]
It would be nice to have a way to control the Filter page in settings so that the Inactive and Managesieve options could be hidden.  It would even be better if the rainloop.user option could be automatically triggered when clicking on the Filters menu.  That way the Edit Script: Rainloop.user window could just be the contents of the Filter page.  That would make that so much easier for end.users to navigate and for them to not mess anything up in their settings.

**Comment by the-djmaze** [comment]
I understand as this has been requested before.
But this will not happen for many reasons i mentioned before.

**Comment by BiglifeMatt** [comment]
What about the title rainloop.user?  Could that at least be replaced with something more directional even like Active Filters, or something more informative to the typical end user?  And perhaps the Managesieve could say "(Advanced)" beside it or something like that?  Just trying to make it easier for my users to feel confident with it.

**Comment by the-djmaze** [comment]
But it already says simple and advanced.
So i don't see the problem.
![Screenshot_2024-07-24-03-29-43-697_org mozilla focus-edit](https://github.com/user-attachments/assets/b5193f68-b90d-4c13-8b66-5843a6afea4c)

**Comment by BiglifeMatt** [comment]
rainloop.user just doesn't make sense to the end user so a user friendly term there would make that a lot more helpful.  Especially since rainloop is an old name the users know nothing about.  Just trying to make things user friendly that is all.

**Comment by the-djmaze** [comment]
Ok, we can fake the script name for it.

**Comment by BiglifeMatt** [comment]
Could just labeling it something like Edit Filter work?
