### ISSUE TITLE
When adding a new email account with a different 'domain' I cannot click on 'Test' button

### ISSUE THREAD

**Issue by freebrowser1** [the-djmaze/snappymail#1676]
**Describe the bug**
When adding a new email account with a different 'domain' I cannot click on 'Test' button

**To Reproduce**
I put 'domain' between quotes as it is not a real domain.
1. Add a domain (what is this in this context ?) *
2. Add an SMTP and IMAP server, click on 'Test', fill in correct credentials and then on 'Save'
3. Login to the configured email address, that works OK.
4. As it is not possible to add another IMAP / SMTP server to the first '*' domain, add a new 'domain'
5. There again an SMTP and IMAP server.
6. The 'test' button is not clickable.

**Expected behavior**
1. It should be possible to add multiple IMAP / SMTP servers per 'domain'.
2. It should be possible to click on the 'test' button when a new 'domain' is added and IMAP is filled in.

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: ?
- PHP version: 8.3, Apache 2.4.60
- SnappyMail Version: 2.364
- Mode: standalone on 'localhost'

**Comment by the-djmaze** [comment]
Test button only works when IMAP and SMTP are both configured

**Comment by freebrowser1** [comment]
That was right, but after configuring and successfully testing, I could not login.
I used a new domain and added my gmail account to it because I was unable to add new SMTP and IMAP to the existing 'domain' with other SMTP and IMAP (which does login).

**Comment by the-djmaze** [comment]
Gmail will not work
