### ISSUE TITLE
Change minimum new mail check interval

### ISSUE THREAD

**Issue by smsoft-ru** [the-djmaze/snappymail#1678]
Snappymail doesn't allow to automatically check new mail more often than once per 5 minutes. I see it is too restrictive and suggest to decrease it to 1 minute. Yes, it may lead to extra load to mail server, we may warn user in documentation, but let user decide is it acceptable or not.
I prepared a patch which implements this change.
[snappymail_checkmailinterval.patch](https://github.com/user-attachments/files/16322700/snappymail_checkmailinterval.patch)

**Comment by the-djmaze** [comment]
See #1477
It has a huge impact to let SnappyMail check every minute.
I think an admin setting to allow this is required, because only server admins should only allow this when the server is capable to handle that much load.

**Comment by smsoft-ru** [comment]
I disagree that impact is huge. The time passes, server power is growing. Most mail clients don't have this restriction, and not all of them implement permanent IMAP connection. And what impact do you mean: to IMAP server or to Http server?
But I agree that admin setting "minimum allowed check interval" may be solution. But not always Snappymail admin is Web server admin, and even less often the same person is IMAP server admin.

Btw, UI setting for check interval is not good now. The user can input any value to this field ant it will be saved. Only tooltip reminds allowed interval of values. I think some kind if verification is required.

**Comment by smsoft-ru** [comment]
Yes, it does say this in tooltip. But the user can ignore it and enter 1 or 120 for example. And this value will be saved. Upper limit (what for is it?) nowhere applied, but there is another part of code which restricts interval to be not shorter than 5 minutes. But the user will see in settings entered value even if it shorter then 5 minutes and will expect that this interval applied.
