### ISSUE TITLE
large message UID not listed

### ISSUE THREAD

**Issue by zakharov257** [the-djmaze/snappymail#1679]
**Describe the bug**
From some months now, mails more recent than a certain date in INBOX mails aren't show. They are if I use an other client (imapfilter, roundcube, fairmail), or if they are moved to an other folder.

**To Reproduce**
have a massage UID greater than 100101, (let say 2206236850) and check if it is listed

**Expected behavior**
All other clients doesn't have a worry to get information

**Please complete the following information:**
- Browser: tested on Firefox (mobile, Linux, Windows), Edge (Windows), Chrome (Windows)
- IMAP daemon: dovecot but not sure
- PHP version: 7.4.33 (cli) (built: Jun  9 2023 16:51:37) ( NTS ) (on a raspberry pi3)
- SnappyMail Version: 2.36.4 from 2.36.0, but issue happened between 2.36.0 and 2.36.1
- Mode: standalone

**Debug/logging information**
```
[2024-07-21 10:34:10.542][8407ec2e] IMAP[INFO]: < * SORT 2206238881 2206238879 <...> 2206236851 2206236850 100101 100097 100094
[2024-07-21 10:34:10.549][8407ec2e] IMAP[INFO]: < TAG4 OK Sort completed (1.404 + 0.000 + 1.403 secs).\r\n

```
while getting header from imapfilter I find that message with UID 100101 is the last one listed in snappymail client, the one with UID 2206236850 isn't listed in SM.

**Additional context**
My mail provider is an associative one (lautre.net), I haven't yet asked why the UIDs dropped from the date of April 4th from 100000 to something like 2,206,236,850. I'll ask but as the official client is roundcube, and it works perfectly as well with other mails clients I know the answer in advance :)
Other thing, I don't really know IMAP background, but when I move message from INBOX to another folder the UID is modified back to more "normal" UID

I don't know if the UID is the bottleneck here, but I guess the large number may have reached a limit somewhere. No warning nor error in logs. Grepping on code show me some files where I should have a look especially snappymail/dev/View/User/MailBox/MessageList.js
but as far as I know JS I can't find a reason for this limit.

Thanks a  lot for the great work on snappymail, and for the interest about this issue

**Comment by the-djmaze** [comment]
Are you using PHP in 32bit mode?

**Comment by zakharov257** [comment]
Hello,

I deserve to be snapped around my face with a wet fish...
```
php -r 'echo PHP_INT_MAX;'
2147483647
```
Obviously this is 32bits version, and I didn't take the time to upgrade from Raspian 32bits to RPI OS 64bits

I'm going to try something in order to lower the UIDs less than `2147483647` by moving the recent mails on another folder, and then I'll get the nextuid of INBOX. I hope it will lower to something more 32-bits compliant, then I'll move back the mails.

Thanks a lot the-djmaze, I don't think it is useful to change something in the snappymail code, even if a [workaround](https://www.percona.com/blog/integers-in-php-running-with-scissors-and-portability/) seems to exists.
Anyway, maybe in documentation a sentence could be added like "on 32bits systems be aware that message UID can be greater than 2147483647 and lead to messages not being listed", or so with a better English language than mine :)

Best regards,
zakh

**Comment by the-djmaze** [comment]
SnappyMail did have a check to only allow 64bit PHP, but was removed for #852 
More info can be found there and in a link.
