### ISSUE TITLE
Mail server does not support sorting

### ISSUE THREAD

**Issue by uubbbb** [the-djmaze/snappymail#1680]
Hello,
I installed it using Docker, https://github.com/the-djmaze/snappymail/blob/master/examples/docker/docker-compose.mysql.yml

No response when I clicked sort, and DevTools showed "Mail server does not support sorting". I used Gmail, Outlook, QQMail, and NetEase Email, and they were all the same, as shown in the picture
![屏幕截图 2024-07-22 215712](https://github.com/user-attachments/assets/cf63564d-21b4-4953-9d0e-af585f7bbd68)

I see your demo site is OK, https://snappymail.eu/demo/
![QQ截图20240722214310](https://github.com/user-attachments/assets/5ecab4bf-17ae-4d84-9f98-971d0aec5bc8)

So is this a bug? So many mainstream mailboxes do not support it.

Thank you.

**Comment by kiv57** [comment]
Same here with gmail.

For the record, filtering works with Infomaniak account.

**Comment by the-djmaze** [comment]
> So is this a bug?

No

> So many mainstream mailboxes do not support it.

Annoying it is, and there's no way to workaround it.

**Comment by abrahamneben** [comment]
RoundCube lets you sort messages independent of the IMAP sort, so why can't snappy just sort messages for the UI like that?

**Comment by the-djmaze** [comment]
> RoundCube lets you sort messages independent of the IMAP sort, so why can't snappy just sort messages for the UI like that?

Because RoundCube stores a copy of all your messages in a database.
SnappyMail never stores (a copy) and always fetches them from the IMAP server.
So when your server is hacked, SnappyMail has no data breach (where RoundCube does have).

**Comment by trojkat** [comment]
I've migrated from RainLoop, where sorting worked for threads. Now, for long-running threads (newsletter), I need to switch to the 15th page each time to find the latest email. Does this mean that RainLoop was also making copies?
