### ISSUE TITLE
Replace default editor with Quill

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1684]
Since the default text editor of the webmail has minimal features and has major weaknesses in supporting RTL languages as mentioned in issue #1389, I decided to replace it with the quill text editor. I have done the initial work of this replacement and the necessary items We added it to Gulp and performed the initial tests, which were successful. This editor has rich features and fully meets the requirements of RTL languages such as Persian language or copying the Excel table directly from clipboard. The editor is different from the previous editor and it has been successfully tested. Quill editor screenshots has been shown below.
Also features such as text alignment are not available in the Squire editor.
But at the time of build with Gulp, the following warning was displayed, which needs your review because it is imported into the HtmlEditor.js file.

![image](https://github.com/user-attachments/assets/3a6f6cc4-5f0d-4a26-b4ce-a9336c68eda1)

**Comment by rezaei92** [comment]
Gulp warning:
![image](https://github.com/user-attachments/assets/f8984122-d9e4-4c1e-923f-8a1e5b051cae)

**Comment by the-djmaze** [comment]
Add it to `globals` in https://github.com/the-djmaze/snappymail/blob/master/.eslintrc.js

**Comment by the-djmaze** [comment]
Also there are some important things you should implement:
- plain/text edit/convert
- identity signatures
- inline images (like `<img src="data:...">`)

**Comment by rezaei92** [comment]
Yes, you are right. The Squire editor is more suitable for webmail applications than the Quill editor. And it is better to improve it instead of changing it.

I'll do it and send you the PR.
Thank you.
