### ISSUE TITLE
Wanted: Invoke "Update Identity" pop up right after login

### ISSUE THREAD

**Issue by v20z** [the-djmaze/snappymail#1689]
Hello Gentlemen.

Need help, advice or direction. Looking for a plugin or way to bring pop up window (`Settings/General/Update Identity`) in order to force user to complete initial survey every time just after login to enter his full name while it is empty.

Thank You.

**Comment by the-djmaze** [comment]
I've added this in a way, that when main identity does not exist yet (edit -> save), it will open the popup.

**Comment by truthsword** [comment]
Why is this turned on be default. I cannot get rid of this nuisance. I decline and another edit identity window appears.

> Can be disabled in application.ini `popup_identity`

Where? Is there an environmental variable I can invoke?

**Comment by the-djmaze** [comment]
> Why is this turned on be default.

Because it makes the most sense to me.
Previous i always had to go to identity editor, and people asked where to edit it.
Now it asks and you just hit "save" and done.
