### ISSUE TITLE
v2.9.4 admin panel is unusable with Firefox and interface is broken in Chromium ?

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#169]
**Describe the bug**
Trying a fresh install of 2.9.4, nothing can be configured on admin panel from Firefox, popups are not shown and seems to appear somewhere behind the viewport. On Chromium, popup are shown bottom left of the screen, not centered.

**To Reproduce**
1. Install 2.9.4 following the Wiki recommandations
2. Go to the admin panel, using the generated password
3. Try to change the language or add a domain
4. Interface is greyed, and nothing can be done 

**Expected behavior**
Admin panel should work like previous versions

**Screenshots**
On Firefox
![image](https://user-images.githubusercontent.com/6248852/144737648-9ee26384-ea13-4cef-8156-aa1eaa5f1b7f.png)

On Chromium
![image](https://user-images.githubusercontent.com/6248852/144737738-020924b5-0846-49d2-a99e-495f6e122f63.png)
![image](https://user-images.githubusercontent.com/6248852/144737836-3f0325f0-0408-4ce7-811e-a20a9ec87af7.png)

**Desktop (please complete the following information):**
 - Firefox 94
 - SnappyMail 2.9.4

**Comment by Psychi1** [comment]
Hi, 

that's the problem I mentioned in https://github.com/the-djmaze/snappymail/issues/166#issuecomment-986011715.

So I can confirm that.

**Comment by the-djmaze** [comment]
While releasing 2.9.4 i focused on fixing some issues in Safari on my old Mac.
But i forgot to test the fix `position:sticky` in Firefox and Chromium. This caused the issues you see, and is fixed in
https://github.com/the-djmaze/snappymail/commit/617dd995b5b39f4b384524aad3d11573201050df

Now the bug is back in Safari but is less an issues as it only shows the dialogs left aligned instead of centered.

**Comment by the-djmaze** [comment]
Could you try with v2.9.6?
https://github.com/the-djmaze/snappymail/releases/tag/v2.9.6

**Comment by Mer0me** [comment]
Uh? It's probably me, but I can't install 2.9.6 properly. Following https://github.com/the-djmaze/snappymail/wiki/Installation-instructions I cannot get the admin page, here is the console : 

![image](https://user-images.githubusercontent.com/6248852/146178893-0a8c1c95-1c4d-4b67-a66e-041d5ba44617.png)

**Comment by the-djmaze** [comment]
Strange, as if parts of the boot.js are not loaded
Clear cache folder helps?

**Comment by Mer0me** [comment]
I've just retried from scratch, on the folder served by my apache server : 
rm -rf snappymail
wget https://github.com/the-djmaze/snappymail/archive/refs/tags/v2.9.6.zip
unzip v2.9.6.zip
mv snappymail-2.9.6/ snappymail
find snappymail/ -type d -exec chmod 755 {} \;
find snappymail/ -type f -exec chmod 644 {} \;
chown -R www-data:www-data snappymail/

opening the admin URL in a private browsing windows to avoid cache issue, or in a browser that I never use => same behaviour, only "SnappyMail" text on a white page and console saying what I've posted earlier...

The old version 2.5.2 is online and working on another folder next to it...

**Comment by the-djmaze** [comment]
Hmm, i will try the zip.
I use new computer with i5-12600k and required openSUSE to get it up and running.
Maybe something wrong with it.

**Comment by m-i-k-e-y** [comment]
Admin panel is working for me with v2.9.6. 

The only things is: every time I log out, have this one line in the logfile of nginx:

`2021/12/16 18:48:57 [error] 1742518#1742518: *7225 FastCGI sent in stderr: "PHP message: PHP Notice:  SnappyMail\Crypt::Decrypt() invalid $data in /var/www/snappymail/snappymail/v/2.9.6/app/libraries/snappymail/crypt.php on line 64" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/AdminAppData/0/01015701583955786/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"`

**Comment by Mer0me** [comment]
Ok, finally it works here too with 2.9.6. I was confused by the folder structure when decompressing, but now it's ok. My bad.

I close this issue.
