### ISSUE TITLE
Keyboard shortcut for "Swap default (background) color"

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#1690]
**Is your feature request related to a problem? Please describe.**
I use a dark layout and often get emails where the text and the background color are both white so the email seems to be "empty". Thanks to the "Swap default (background) color" feature introduced a while ago this issue can be solved quickly. Unfortunately I have to use the mouse and have to click two times to make the email "readable".

**Describe the solution you'd like**
I really would love to have a keyboard shortcut for switching this functionality. Maybe `x` for `eXchange background color` as `b` and `c` are already assigned.

**Describe alternatives you've considered**
None.

**Comment by the-djmaze** [comment]
X is mostly used for undo and others.
Maybe ctrl+b?

**Comment by codiflow** [comment]
I'm fine with whatever combination fits best 😎

So CTRL + B would be fine too.

**Comment by the-djmaze** [comment]
CTRL + B used by browser for bookmarks. Now using Shift + B
