### ISSUE TITLE
Langauge Du is not supported in snappymail same is supported in Nextcloud

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#1692]
**Describe the bug**
Language code Du is not supported in snappymail where as same is supported in nextcloud

**To Reproduce**
1. Go to  nextcloud settings
2. select `du` in lanugae
3. now click on snappymail app
4. You will see snappymail is still in english where is whole nextcloud is in du

**Expected behavior**
Snappy should be transalted to du as well

**Screenshots**
**Nextcloud:**
![Screenshot 2024-07-30 at 11 10 51 AM](https://github.com/user-attachments/assets/ca6e972e-39a2-4704-bef2-be24f2b8372c)

**Snappymail**
![screenshot-2024 07 30-10_57_55](https://github.com/user-attachments/assets/ba9d5800-388d-4b76-9fda-4d92d3a0bc26)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker]

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
`du` is not a valid language.
`de` and `de_DE` are in Nextcloud.
So how did you obtain that strange language?

**Comment by the-djmaze** [comment]
Oh i see in the Nextcloud internals that they made it very weird and incorrect.
`de` uses informal Du
`de_DE` uses formal Sie

While they both should be the same.
It would be better to have things like:
`de-DE-formal`
`de-CH-formal`

This is not only with the German language, but also with Dutch, French, etc. etc.

Short info: https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/localization/README
