### ISSUE TITLE
Send email issuewhile SMTP test succeeds

### ISSUE THREAD

**Issue by freebrowser1** [the-djmaze/snappymail#1697]
**Describe the bug**
When sending a mail I get this message while I can login into the webmail.
Looks like #1664, but I am enable to login, but cannot send an email.

**To Reproduce**
Prerequisites:
* A valid IMAP and SMTP should be tested and configured in the ?admin screen resulting in a green Test! button.

1. Login into webmail
2. Send an email
3. See error

**Expected behavior**
The email will be sent.

**Please complete the following information:**
- Browser: any (I used firefox)
- IMAP daemon: ?
- PHP version: 8.3
- SnappyMail Version: 4.36
- Mode: standalone under Apache 2.4 web server

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ X] I've placed them here (few lines) or as attachments (many lines)
[log-2024-08-08.txt](https://github.com/user-attachments/files/16547835/log-2024-08-08.txt)

**Comment by the-djmaze** [comment]
> 530 5.7.0 User not authenticated

This means there is no login active for SMTP.
Make sure `Use authentication` is active.
![afbeelding](https://github.com/user-attachments/assets/07a31a27-c4e8-49e5-b2a5-37747b3596d5)

**Comment by freebrowser1** [comment]
Indeed, that works. I did not know that that should be checked, I assumed that authentication is always enabled.
Thanks.
