### ISSUE TITLE
HTML editor shows text and background color as black

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#17]
**RainLoop version, browser, OS:**
SnappyMail v2.0.0-rc1
Firefox 80.0.1
Fedora 32 (Workstation Edition)

**Expected behavior and actual behavior:**
If they both show black, I expect black text on a black background. But I guess I just want it to show the black text on white (or no?) background as this is what it actually defaults to. 
 
**Steps to reproduce the problem:**
Log in, create new email, observe.

**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/4435930/94374649-03366b00-010e-11eb-95b9-71267186a1b4.png)

**Comment by the-djmaze** [comment]
Correct, this is the HTML5 `<input type="color">` widget which works nice everywhere and on mobile devices.
The problem is indeed the color and lack of visual feedback.
I am on to something as solution and will be added later.

**Comment by ervee** [comment]
Confirmed working now

![image](https://user-images.githubusercontent.com/4435930/95621357-d5d4b000-0a71-11eb-91b1-2df4610142ea.png)
