### ISSUE TITLE
How to consolidate _data_ directories?

### ISSUE THREAD

**Issue by randolf** [the-djmaze/snappymail#1700]
**SnappyMail version, browser, browser version:**
SnappyMail v2.36.4
Opera v112.0.5197.53 (Linux)

**Expected behavior and actual behavior:**
User data should all be stored under the _data_/server-hostname/ directory, but a wide variety of sub-directories are being created now, and users' settings are going back to defaults.  One of the biggest problems is that users can't send eMail until I go in and replace their application.ini file, and I can't seem to find a default template for this file anywhere.

**Steps to reproduce the problem:**
Login as users from different domains.

**Logs or screenshots:**
None / N/A.

How can I get all my users consolidate under the same directory again so that global defaults will work properly for everyone?  Thanks.

**Comment by the-djmaze** [comment]
I don't understand you, because that's not how SnappyMail works.


See the root `_include.php` and enable `MULTIDOMAIN` in there.
Then you get `/_data_/hostname/` instead of `/_data_/_default_/`

**Comment by randolf** [comment]
Thanks!  I need to disable MULTIDOMAIN then.

My previous configuration was going through an Apache HTTPd proxy, which was causing SnappyMail to detect only one domain name.  Now our proxy configuration is different (since switching to a new server), and SnappyMail is detecting the actual domain names that users are connecting with (over HTTP).

It looks like I'll have a lot of work to do to get this cleaned up (I can just automate most of this with a Perl script).
