### ISSUE TITLE
support RSPAMD

### ISSUE THREAD

**Issue by sir-andreas** [the-djmaze/snappymail#1701]
**Describe the solution you'd like**
I would like to display the spam score field while my mail server is using Rspamd as spam filtering system

Rspamd signs emails with the following fields
`
X-Spam-Flag: YES

X-Rspamd-Bar: ++++++++++++

X-Rspamd-Report: MANY_INVISIBLE_PARTS(0.05) HAS_LIST_UNSUB(-0.01) MIME_HTML_ONLY(0.2) BAD_REP_POLICIES(0.1) FORGED_RECIPIENTS(2) SPAM_FLAG(5) ZERO_FONT(0.1) FORGED_SENDER(0.3) BAYES_SPAM(5.1)

X-Rspamd-Score: 12.839999
`

As Snappymail only supports the following fields
X_SPAMD_RESULT
X_BOGOSITY
X_SPAM_STATUS
X_SPAM_FLAG
(also see https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/MailSo/Mail/Message.php#L229)
the Spam Score field is not shown.

Could you either add the addittional Rspamd fields or at least react also on X-Spam-Flag and not only on X_SPAM_FLAG? (minus instead of underscore)

Thank you for providing this wonderful software BTW.

**Comment by the-djmaze** [comment]
To stay consistent between all different spam systems, it will stay like this:
![afbeelding](https://github.com/user-attachments/assets/f25f8a29-0813-42b9-8aaf-c8eb2aff4c3e)


However, you could write a plugin especially for your RSpamd needs.
