### ISSUE TITLE
SnappyMail.eu Website is offline - automatic app installation in NextCloud not working anymore

### ISSUE THREAD

**Issue by holzerseb** [the-djmaze/snappymail#1702]
**Describe the bug**
Snappymail.eu website doesnt load (server not responding). Subsequently, app installation via nextcloud store is not possible, because the tar.gz cannot be downloaded.

**To Reproduce**
Visit snappymail.eu or download the app in Nextcloud

**Expected behavior**
Website responding

**Screenshots**
no screenshot required for a "server not responding" error

**Please complete the following information:**
- Browser: any https request doesnt go through
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] Docker NextCloud AIO. But also Firefox on my host.

**Comment by holzerseb** [comment]
Thanks for SnappyMail btw! It's a fantastic app, unfortunately I had to setup my server from scratch and couldn't get the app to install due to the server not responding :(

**Comment by the-djmaze** [comment]
SnappyMail website has a firewall to ban IP's based on their behavior.
It could be possible that your server IP is within a banned range.

**Comment by holzerseb** [comment]
Thanks, I wasn't using a VPN and it looks like the server is responding properly again, so maybe it was just a temporary issue or my IP was unbanned. I was able to download snappymail. Keep up the amazing work!

**Comment by pietricello** [comment]
Same issue here but just after yesterday update. Situation: Snappymail working till yesterday 13/08/2024 on my Nextcloud 29.0.4 instance configured running on Oracle Cloud. After being noticed of available update i did it. It seemed to me everything was ok but now when i try to access snappymail i receive this error "An error occurred.Please refresh the page and try again.SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON" . I tried to uninstall and reinstall app with no results. Nextcloud log report "InvalidArgumentExceptionProvider snappymail is unknown". So what's going on? Any ideas to fix this issue or i have to give up with snappymail?

**Comment by the-djmaze** [comment]
`www.snappymail.eu` did not exist.
I've made a redirect to snappymail.eu

**Comment by pietricello** [comment]
Thank you for the info, and sorry for mystake. Well https://snappymail.eu as webpage works by my side , also from Oracle instance mail server any idea bout how come just after update it does not works? Also notice nothing else was updated/upgraded on the meantime so the same php8.3 version, nginx all as before the update.

**Comment by the-djmaze** [comment]
> any idea bout how come just after update it does not works?

Yes, see https://github.com/the-djmaze/snappymail/releases/tag/v2.37.2

**Comment by pietricello** [comment]
Thank you. The new version fix the issue but (just to know) : 1) it comes correctly as update in Nextcloud but clicking update it stucked for minutes leaving the Nextcloud in maintenance mode and offline. I had to manually disable maintenance mode then "start update" compared on browser and update procedure started. 2) despite no errors in updating process i had to re-insert name/label for each of configured email accounts. On top of this all seems working good.

**Comment by the-djmaze** [comment]
> but clicking update it stucked for minutes leaving the Nextcloud in maintenance mode and offline. I had to manually disable maintenance mode then "start update" compared on browser and update procedure started.

This is a known problem for some Nextcloud instances (i can't reproduce, it always works here).

> 2) despite no errors in updating process i had to re-insert name/label for each of configured email accounts.

Yes, this is new feature #1689
