### ISSUE TITLE
nextcloud snappymail does not load after upgrade to 2.37.0

### ISSUE THREAD

**Issue by HenkVirtual** [the-djmaze/snappymail#1703]
error as below

Please refresh the page and try again.SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by JonTabor** [comment]
I just ran across this as well.  I can't seem to come up with anything useful when enabling debug logging, either.

Here's the exact error I get:
_An error occurred.
Please refresh the page and try again.
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON_

So far I have been unable to track this down.  Usually I see this when something returns HTML when it was expecting JSON, but so far I haven't found anything useful.

**Comment by the-djmaze** [comment]
Nextcloud has a bad habbit of failing update tasks.
Nextcloud keeps switching between `apps` and `custom-apps` and there's only one thing you can do:

Go to `/nextcloud/settings/admin/additional`
Then go back to `/nextcloud/apps/snappymail/`

Nextcloud bugs are outside our development scope and this specific issue is already reported here several times and i can't reproduce them in my Nextcloud instances.

**Comment by the-djmaze** [comment]
> An error occurred. Please refresh the page and try again. SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON_
 
Correct!
The file does not exist on that location, see your developer tools network requests for the "404 Not Found" mess that Nextcloud creates.

**Comment by HenkVirtual** [comment]
> admin/additional

unfortunately my nc 29. is generating the same error on the snappy admin page, even after server restart;
An error occurred.
Please refresh the page and try again.SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by JonTabor** [comment]
> > An error occurred. Please refresh the page and try again. SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON_
> 
> Correct! The file does not exist on that location, see your developer tools network requests for the "404 Not Found" mess that Nextcloud creates.

Yeah, I was looking for 404s in the dev tools, but there are none.  Just a long string of 200s.  The workaround above doesn't work for me, so I'm thinking this is a different issue.

**Comment by the-djmaze** [comment]
That's because Nextcloud is serving an HTML document instead.
So Nextcloud does not serve a 404, but just throws a 200 with HTML.

And SnappyMail needs JSON.

I will modify the fetch code to detect this misbehavior.
It will not solve it, but should give more insight then.

**Comment by the-djmaze** [comment]
Also see #1663 and #1535

**Comment by the-djmaze** [comment]
I found an issue due to O365 login!

**Comment by JonTabor** [comment]
> I found an issue due to O365 login! [47d18ca#r144395031](https://github.com/the-djmaze/snappymail/commit/47d18cafa38dd526b4221c2a72d1529e4fa1d255#r144395031)
> 
> So in this case it was my fault 😱

Microsoft causing problems for people?  Color me shocked.

Nice find!  And thanks for looking into it for us!

**Comment by joshtrichards** [comment]
> Nextcloud has a bad habbit of failing update tasks.
> 
> Nextcloud keeps switching between apps and custom-apps and there's only one thing you can do:
>
> Go to /nextcloud/settings/admin/additional
> Then go back to /nextcloud/apps/snappymail/ or /nextcloud/custom_apps/snappymail/
>
> Nextcloud bugs are outside our development scope and this specific issue is already reported here several times and i can't reproduce them in my Nextcloud instances.

Hey @the-djmaze - Josh here (a member/contributor over at the Nextcloud project). I'm not clear what bug this is referencing.

Is there some situation where a URL is hard coded in Snappy or something?

In Nextcloud, the `apps_paths` are defined by config not hardcoded. Any number of apps paths are valid and admins can name them whatever they want. 

https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html#using-custom-app-directories

By convention several of the installation methods (like our micro-services and AIO Do keep images) do use `apps/` for shipped apps and `custom_apps/` for app store installed apps, but that's entirely arbitrary.

**Comment by the-djmaze** [comment]
Hi @joshtrichards somehow Nextcloud switches the path.
When you have /apps/snappymail then after upgrade it is /custom_apps/snappymail (or viceversa).

Snappymail stores the path in application.ini so after upgrade it faild.
