### ISSUE TITLE
Error: App with id snappymail has invalid signature

### ISSUE THREAD

**Issue by vincib** [the-djmaze/snappymail#1705]
**Describe the bug**

when trying to install snappymail (via OCC, but I have the same error via the web interface) on a NC 28.0.8 today, I had the following error displayed : 

cloud17@host:~$ php occ app:install snappymail
Error: App with id snappymail has invalid signature

**To Reproduce**

1. install a nextcloud 28.0.8
2. go to the root of it
3. launch php occ app:install snappymail

**Expected behavior**

I expect the app to install :) 

**Screenshots**

I straced the process, and it's clearly downloading from snappymail.eu a big .tar.gz and then open it (to check the signature I guess) and then spit out the error and stop

**Please complete the following information:**
- PHP version: 8.2.21
- SnappyMail Version: not installed but trying 2.37.2
- Mode: nextcloud app

I see that snappymail nextcloud app has been updated recently, maybe the .tar.gz has been updated AFTER that and the signature is really invalid in apps.json on nextcloud ?

**Comment by the-djmaze** [comment]
See https://github.com/the-djmaze/snappymail/wiki/FAQ#nextcloud-app-with-id-snappymail-has-invalid-signature

**Comment by vincib** [comment]
Thanks and sorry I didn't find the FAQ before <3
