### ISSUE TITLE
SnappyMail's Sieve editor does not support "index" extension, error "this.index is undefined"

### ISSUE THREAD

**Issue by lje** [the-djmaze/snappymail#1709]
**Describe the bug**
SnappyMail's Sieve editor cannot handle an :index directive in rules.

**To Reproduce**
I've created the following valid Sieve script as example:
```sieve
require ["index", "regex"];
if header :index 3 :regex "Received" "envelope-from <([^>]+)>" { keep; }
```

When trying to edit this script in SnappyMail, I get an "this.index is undefined" message

**Screenshots**
![SnappySieve](https://github.com/user-attachments/assets/e5992df1-c74c-4210-bdb8-5afc19c879bd)

**Please complete the following information:**
- Browser: Firefox 129.0.1
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: v2.37.1
- Mode: standalone

**Comment by the-djmaze** [comment]
it seems a part of RFC 5260 wasn't implemented

**Comment by lje** [comment]
The server in quesion does support the "index" extension. The script above was not freshly created in SnappyMail but fetched from the server. I created it before using [Sieve Editor](https://github.com/thsmi/sieve) and stored in to the server using the [ManageSieve](https://datatracker.ietf.org/doc/html/rfc5804) protocol.

Does the editor used in SnappyMail perform some kind of client side checking? All checking should be done by the server using the [CHECKSCRIPT command](https://datatracker.ietf.org/doc/html/rfc5804#page-27) of ManageSieve. I assume this is some kind of bug in the editor.

Extension support of the server in question:
![Screenshot 2024-08-15 084848](https://github.com/user-attachments/assets/c2701526-663e-4c90-9c72-74fefa9af9d8)

**Comment by the-djmaze** [comment]
Keep in mind that `index` is a shot in the dark.
You must be 100% certain that every email you receive has the required header on the exact index.

**Comment by lje** [comment]
Thanks, I'm aware of that. The header in question is a "Received" generated by my own email provider for every incoming mail I want to catch with that filter. The `:index` makes sure, I don't accidentially catch a "Received" header of any previous mail server along the chain.
