### ISSUE TITLE
Creating new message impossible as long as a draft exists?

### ISSUE THREAD

**Issue by lje** [the-djmaze/snappymail#1710]
**Describe the bug**
Maybe I'm missing something, but there seems to be a new "feature" in SnappyMail v2.37.1.
When I create a new message and save it as draft, the "New message" button changes color from green to orange. Whenever I press that button now, I'm forced to continue editing the draft. I cannot create a new (different) message as long as the draft has not been sent ot deleted.

Where/how do I deactivate that new feature?

**To Reproduce**
Create a new message, type something into it, save it and exit - do not send it.
Try to create a new empty message.

**Screenshots**
![SnappyDraft](https://github.com/user-attachments/assets/77a3d12f-b24e-4b79-b4ce-112c5ea3cec9)

**Please complete the following information:**
- Browser: Firefox 129.0.1
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: v2.37.1
- Mode: standalone

**Comment by the-djmaze** [comment]
Closing compose window indeed makes it orange and keeps the data.
Shift+esc shoukd not, but something is happening so i will check.

**Comment by lje** [comment]
Thanks, Shift+Esc works for now. I'd still like to get back the old behaviour (closing the window does not keep data) as default or have an configuration option to set the desired behavious.
