### ISSUE TITLE
Broken Avatar Image on Nextcloud 29.0.5 / Snappy 2.37.2

### ISSUE THREAD

**Issue by seal-82** [the-djmaze/snappymail#1718]
I've been using Snappy Mail on Nextcloud for long time already. Great to have such a piece of software :-) 

Recently, I observed that the avatar image is showing a broken image symbol if the sender is not found in any of the public avatar databases.

Looks like this when opening the mailbox:
![grafik](https://github.com/user-attachments/assets/08d70836-c0d6-4f2c-b8dd-f23d34235bc0)

After some seconds SnappyMail tries to load the avatars and then it looks like this:
![grafik](https://github.com/user-attachments/assets/938f98d2-337f-4d78-94bf-514a8d4d3fe4)

Avatars extension is 1.19. Avatars settings are:
![grafik](https://github.com/user-attachments/assets/48e13a88-f41e-4661-a161-5f74d42c3498)

Has anyone observed the same behavior? 

Cheers,

Sebastian

**Comment by the-djmaze** [comment]
Thanks for reporting. I've added error handling on the `<img>` tags.

**Comment by seal-82** [comment]
Wow! That was quick... thanks for solving the issue so fast. Looking forward to the next update.
