### ISSUE TITLE
PGP with ECDSA or curve25519

### ISSUE THREAD

**Issue by GregThib** [the-djmaze/snappymail#172]
**Bug**
Could not import my key, probably because it brings an ed25519 key-type.

**To Reproduce**
Try to import this kind of key.
See the error message:
`Error: No key packet found`

**Desktop**
 - firefox 95.0.x
 - SnappyMail 2.9.6, stock

**Additional context**
I'm coming from Rainloop, and looked for the issues overthere. And I won: the issue has been reported, [here](https://github.com/RainLoop/rainloop-webmail/issues/1149)
So, it seems that OpenPGPjs should be updated. Is it right?

Thx for the great job you made!

**Comment by the-djmaze** [comment]
Yes, also see #89

**Comment by the-djmaze** [comment]
Implemented for gnupg.
New class gpgkeygenerator will use EDDSA with ed25519 and cv25519 for signing and encrypting.

This class could be modified to also use RSA/DSA keys to be compatible with clients that do not support ECC keys.

Next would be to implement OpenPGP.js v5 to support this.

**Comment by the-djmaze** [comment]
I will close this issue as there is loads of progress in #89 and your feature request is working there.
