### ISSUE TITLE
occ command for Settings - Language

### ISSUE THREAD

**Issue by olegchensky** [the-djmaze/snappymail#1721]
Is it possible to add an occ command to setup UI Language?

**Comment by the-djmaze** [comment]
Why? It just uses the current Nextcloud language.

**Comment by olegchensky** [comment]
Unfortunately, no. User change an own Language and must change it in SM too

**Comment by the-djmaze** [comment]
Then you didn't disable `allow_languages_on_settings` in the application.ini
