### ISSUE TITLE
IMAP capabilities via IMAP Proxy

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#1725]
**Describe the bug**
When I use an IMAP Proxy (which is desirable) I can't sort emails:

![image](https://github.com/user-attachments/assets/ca6c8d4e-c3d7-4498-a71c-58f8a3b8d391)

When I change the domain configuration to connect directly to the IMAP server (with STARTTLS like the proxy does), I can:

![image](https://github.com/user-attachments/assets/91dd52fa-6e4b-4d2e-8ef5-62077821b423)

Now when I test the domain configuration using the proxy it shows me this:

![image](https://github.com/user-attachments/assets/73f53165-e2b2-46d3-9510-cb037a7ff135)

The "disable capabilities" change from 8 options when I open the domain configuration to these 14 options and the SORT option seems to be there.

When I test the domain configuration using the direct connection it shows this:

![image](https://github.com/user-attachments/assets/294b336d-36a3-442a-bd45-422e26149f90)

I _think_ this could perhaps be if SnappyMail expects post-login capabilities to be advertised by the server? When in fact the proxy does not do this. Check this out:

Via proxy:
```
* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE LITERAL+ XIMAPPROXY] Dovecot (Debian) ready.
A1 login myusername "mypassword"
A1 OK User logged in
C1 CAPABILITY
* CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA
C1 OK Capability completed (0.001 + 0.000 secs).
```

See that after login, the post-login CAPABILITIES of the server are only displayed *after* I ask for them via "C1 CAPABILITY". I think that perhaps this is where SnappyMail fails to get the capabilities if it does not specifically ask for them.

And direct (via STARTTLS):
```
. OK Pre-login capabilities listed, post-login capabilities have more.
A1 login myusername "mypassword"
* CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA
A1 OK Logged in
```

Now the server announces the capabilities automatically after login.

**To Reproduce**
Steps to reproduce the behavior: Pretty mutch the above.

**Expected behavior**
I would hope to use the IMAP server capabilities also when using a proxy.

**Screenshots**
See above.

**Please complete the following information:**
- Browser: Does not matter
- IMAP daemon: Dovecot
- PHP version: 8.1
- SnappyMail Version: Latest to date.
- Mode: Standalone

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [x] I've placed them here (few lines) or as attachments (many lines)

**Additional context**
None.

**Comment by the-djmaze** [comment]
There are several locations where the capabilities are set.

And it is handled by setCapabilities
https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/MailSo/Imap/ImapClient.php#L299

1. After Connect() (to get the connect/auth/tls capabilities)
2. When auth/login succeeded (if the auth response has them, else reset to NULL)
3. On the explicit Capability() request (when current data is NULL it does the CAPABILITY command)

And when you look in your screenshots above, it shows that both contain SORT.
Which means it should work.

The place how to know this, is to look in the browser developer tools network tab and find the `Folders` request, and look at the response JSON.
![afbeelding](https://github.com/user-attachments/assets/f4c2294f-30ab-4ae2-93e1-c72e47ef2734)

**Comment by the-djmaze** [comment]
But indeed it failed because aCapaRaw was not unset first
