### ISSUE TITLE
Save Filters as Shortcuts on Left Panel (Folders)

### ISSUE THREAD

**Issue by stef204** [the-djmaze/snappymail#1731]
**Is your feature request related to a problem? Please describe.**
On a specific email account, I receive a high quantity of emails of parts inventory, prices, etc., daily (up to 800 per day) which I need to sift through or filter quickly.

There are parts which I need to focus on more than others so need to be able to quickly filter `Today`'s email for: `Part abcd` for example (which is most of the time inside the subject of the email [sometimes in the body].)

What I do currently is the just use the search bar and filter for ` Part abcd` + `Today` and this works.  However I find it tedious to always do that several times a day, every day.

**Describe the solution you'd like**
Would be great to be able to save the filter as a "link" on the left panel in a way that I could just click on it (e.g. `Part abcd + Today` and instantly get the emails filtered which match this criteria (as opposed to having to write it out or use the drop down menu, each time.)

**Describe alternatives you've considered**
None as I do not seem to have the capability to create Virtual Folders on email server which is shared hosting.

**Comment by stef204** [comment]
Thanks, just tried it and nice work.  Not sure where to comment on this: here or on the page of the commit?  The comments won't be related to code but just user experience ones for @AbdoBnHesham, dev of the plugin.

**Comment by the-djmaze** [comment]
just create a new issue like "search filters extension wishes" or something.
then everyone can take a look at it ;)
