### ISSUE TITLE
`Messages on page` setting is not validated against 999 max

### ISSUE THREAD

**Issue by SergeyMosin** [the-djmaze/snappymail#1733]
**Describe the bug**
It is possible to set the `Messages on page` to 1000 for example, which will result in `Can't get message list` error, triggered by this check:
https://github.com/the-djmaze/snappymail/blob/0db6c6ab5f9e05c46b13ebbdaf351341710438ac/snappymail/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php#L750-L755

**To Reproduce**
1. Go to `Settings > General > Message list > Messages on page`
2. Set `Messages on page` to `1000`
3. Go back to `INBOX`
4. See the `Can't get message list` error

**Expected behavior**
Config page should not allow users to set the `Messages on page` to a value that is greater than the max in `MailClient.php`

**Screenshots**
![image](https://github.com/user-attachments/assets/e62bd28f-22be-4bca-ae10-2df9897b8364)

**Comment by the-djmaze** [comment]
I've added element.checkValidity() to KnockoutJS as feature
