### ISSUE TITLE
Adding an extra font with plugin

### ISSUE THREAD

**Issue by rezaei92** [the-djmaze/snappymail#1735]
I want to add a new font. I know it's possible to add a font to a theme. But I want to use this font for all themes.
What is the best way to add a new font to all themes without manipulation of main source code. I expect to do this with a plugin?

I wrote a new plugin and put the font in the plugin subdirectory and invoked it by @font-face, as you know it's not possible to load font from the data directory when to do this it tries to load font from (http://localhost/snappymail/v/2.36.0/themes/NextcloudV25+/test.woff). 
Also, we can't use CDN for this purpose because the font has a license, so we should load that just from our server. So what do you recommend?

![image](https://github.com/user-attachments/assets/76a11f5b-8d0d-491f-8f8f-d70b9a42c3b6)

**Comment by the-djmaze** [comment]
There are 3 types of fonts:
- serif
- Sans serif
- Mono

You can write a plugin to override the defaults.
But you only have 1 font, so you are missing the other two.
