### ISSUE TITLE
Nextcloud app does not open PDFs in browser, only offers download

### ISSUE THREAD

**Issue by ratermir** [the-djmaze/snappymail#1739]
**Describe the bug**
in the Nextcloud app, when I click on attachment of any type, only the "download" (i.e. save file) dialog is opened. There is no option to view the attachment of common typ (jpeg/png images, PDF ...) directly.
In the Nextcloud mail client it works well (but it is hardly usable)

**To Reproduce**
- open mail with any attachment
- click on the attachment

**Expected behavior**
After clicking to the attachment, it should be open in the build-in Nextcloud viewer of corresponding type (the best would be also for office files like doc(x)/odt, xls(x)/ods ... etc, but this is a wish :) ). Only unknown types should be offered to download.

**Please complete the following information:**
- Browser: Chromium / chrome / edge of many versions,  (this issue persists for long time)
- IMAP daemon: mailu 2.0
- PHP version: 8.X
- SnappyMail Version: 2.37.3 (and  some older)
- Mode: nextcloud
- Nextcloud version: 28.0.9 (and older - all 28 verrsions), Docker, corresponding PHP

**Comment by the-djmaze** [comment]
Did you click on the eye?

**Comment by the-djmaze** [comment]
Click on the icon

**Comment by ratermir** [comment]
It works :) Thank you and sorry - it is not too intuitive nor obvious if aren't chasing the mouse across the screen.

**Comment by the-djmaze** [comment]
> aren't chasing the mouse across the screen.

Get a cat? :wink:
