### ISSUE TITLE
`Received-SPF` correctly processed, when spf information is not part of `Authentication-Results` 

### ISSUE THREAD

**Issue by fw23git** [the-djmaze/snappymail#1740]
Hello,

is the Received-SPF header correctly processed and displayed when header set and spf information is **not** in addition part of the Authentication-Results header?

Thanks

**Comment by fw23git** [comment]
I guess a similar flow is required for dane information processing and display.

**Comment by the-djmaze** [comment]
No, because we don't show if SPF/DANE passes or not.
We only show DKIM for the sender.

**Comment by anzz1** [comment]
is it possible to have the Received-SPF field in the "Show Source" at least?
