### ISSUE TITLE
Attached image can only be downloaded, no preview

### ISSUE THREAD

**Issue by freebrowser1** [the-djmaze/snappymail#1741]
**Describe the bug**
In a mail with an image attached, when I click it always shows a download prompt. There is no preview possibility of the image.

**To Reproduce**
1. Open an email with an attached image
2. Click on the image link
3. It can only be downloaded.

**Expected behavior**
At least a possibilty to preview the image 
**Please complete the following information:**
- Browser: Any
- IMAP daemon: ?
- PHP version: 8.3
- SnappyMail Version:  Jul 2024
- Mode: standalone

**Comment by the-djmaze** [comment]
Did you click on the eye?
![afbeelding](https://github.com/user-attachments/assets/245a0b90-d45e-43c2-917f-50d8447430df)

**Comment by freebrowser1** [comment]
Yes, I already found it. So you can close this ticket.
