### ISSUE TITLE
Problem when decrypting GPG message

### ISSUE THREAD

**Issue by NitroStar654** [the-djmaze/snappymail#1742]
**To Reproduce**
1. Receive an encrypted message
2. Click on 'decrypt message'

**Expected behavior**
I should see the decrypted message.

**Screenshots**
![Capture d’écran (448)](https://github.com/user-attachments/assets/597e4880-465e-4fc2-8ef9-e5592021de53)

**Please complete the following information:**
- Browser: Tor Browser 13.5.3
- IMAP daemon: Don't know
- PHP version: Don't know
- SnappyMail Version: 2.37.3
- Mode: Web browser

**Debug/logging information**
[console-export-2024-9-9_19-40-12.txt](https://github.com/user-attachments/files/16934339/console-export-2024-9-9_19-40-12.txt)
- [x] I've placed them here (few lines) or as attachments (many lines)

**Comment by the-djmaze** [comment]
Thanks for the log.
In this case we need the Client side log (Javascript).
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by NitroStar654** [comment]
I use Tor Browser and it's not the same console. I can only get that : [console-export-2024-9-13_23-25-52.txt](https://github.com/user-attachments/files/16999535/console-export-2024-9-13_23-25-52.txt)

**Comment by the-djmaze** [comment]
There's not much we can do with your logs.
We really need the correct browser developer tools log.

**Comment by edoardomrch** [comment]
Please Can you delete thé issue please it's important
