### ISSUE TITLE
Provide favicon locally instead of URL

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1747]
**Is your feature request related to a problem? Please describe.**
I'm asked for a URL when trying to replace my favicon, so I have to find another server/domain to host the icon which I don't have.

**Describe the solution you'd like**
Provide the favicon in the local folder/docker data folder

**Describe alternatives you've considered**
Tried looking in the _data_ folder to see if there are icons there that I can replace

**Additional context**
No

**Comment by bilogic** [comment]
Specifically, I want to replace this
![image](https://github.com/user-attachments/assets/c6e4358f-d129-438f-85ea-abe3dae318cf)

**Comment by the-djmaze** [comment]
No really. You can just use `/favicon.ico`

**Comment by bilogic** [comment]
Thanks, if I were to specify `/myicon.ico`, which folder should I store myicon.ico?

**Comment by bilogic** [comment]
Ok, I found what I was looking for `/snappymail/snappymail/v/2.37.3/static`
