### ISSUE TITLE
Is Gmail API supported when IMAP support by Google stops ?

### ISSUE THREAD

**Issue by freebrowser1** [the-djmaze/snappymail#1748]
**Is your feature request related to a problem? Please describe.**
Soon, Google is going to stop support for IMAP.
Does snappymail support the Google OAUTH API ?

**Describe the solution you'd like**
That Gmails can still be accessed via Snappymail.

**Comment by the-djmaze** [comment]
Please read https://github.com/the-djmaze/snappymail/wiki/FAQ#oauth2--oauthbearer
