### ISSUE TITLE
Threads completely broken?

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#175]
**SnappyMail version, browser, browser version:**

SM v2.9.6 (at least 2.9.4 was already broken if I remember correctly)
Firefox 95.0 on Windows 10 21H2

**Expected behavior and actual behavior:**

With threads option enabled, find email conversation with at least 2 mail in Inbox. Should show only once with a clickable thread counter to snow all mails in the thread (could use sent items too, but that's a feature request I think :))

**Steps to reproduce the problem:**

Enable "Threads" in settings.
Go to inbox
Find email conversation with at least 2 mail in Inbox
Shows all mails in conversation instead of 1 time with a thread counter.

**Logs or screenshots:**

![image](https://user-images.githubusercontent.com/4435930/146825318-574063b4-a5fe-42ca-aee2-99b6fef63f3b.png)

![image](https://user-images.githubusercontent.com/4435930/146825192-3fc13d65-d052-4af1-94fe-af50e22e7d10.png)

**Comment by jdaviescoates** [comment]
I've just started using SnappyMail. I'm on SnappyMail 2.17.2 and threads don't appear to be working at all. Are they supposed to be?

**Comment by jdaviescoates** [comment]
Oh, my bad, I just hadn't worked out the UI yet. 

I hadn't spotted the little number one has to click on over on the right (e.g. the 5, 2, and 2 show here):

![Screenshot from 2022-08-17 17-45-13](https://user-images.githubusercontent.com/2113743/185196446-dcee4185-074b-4c5e-94d7-7f585a9de2e3.png)

**Comment by jdaviescoates** [comment]
> I hadn't spotted the little number one has to click on over on the right (e.g. the 5>, 2>, 2> and 2> shown here):

But clicking on those now doesn't work at all, so I guess threads are currently completely broken? :-/

**Comment by the-djmaze** [comment]
> > I hadn't spotted the little number one has to click on over on the right (e.g. the 5>, 2>, 2> and 2> shown here):
> 
> But clicking on those now doesn't work at all, so I guess threads are currently completely broken? :-/

#512 😉

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.18.0

**Comment by jdaviescoates** [comment]
working again, thanks! :pray:
