### ISSUE TITLE
Tables in emails are not displayed correctly.

### ISSUE THREAD

**Issue by Belovk-RARUS** [the-djmaze/snappymail#1751]
Tables in emails are not displayed correctly.

1. Open the email with the table.
2. The table is either not displayed at all or partially.

**Expected behavior**
Tables in emails are displayed correctly.
![изображение](https://github.com/user-attachments/assets/2200eee8-9f7f-4247-9733-382201417dda)
![изображение](https://github.com/user-attachments/assets/1be0e980-a6d8-4532-b72d-3a4ffa26ea3e)

HTML Table
<table cellspacing="0" cellpadding="0" dir="ltr" border="1" style="table-layout: fixed; font-size: 10pt; font-family: Arial; width: 0px; border-collapse: collapse; border: medium;"><colgroup><col style="width: 100%; max-width: 156px;"><col style="width: 100%; max-width: 152px;"><col style="width: 100%; max-width: 195px;"><col style="width: 100%; max-width: 146px;"></colgroup><tbody><tr style="max-height: 21px;"><td style="border-width: 1px; border-style: solid; border-color: rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-top: 1px solid rgb(0, 0, 0); border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-top: 1px solid rgb(0, 0, 0); border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-top: 1px solid rgb(0, 0, 0); border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr><tr style="max-height: 21px;"><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr><tr style="max-height: 21px;"><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr><tr style="max-height: 21px;"><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr><tr style="max-height: 21px;"><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr><tr style="max-height: 21px;"><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test1<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test2<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test3<br></td><td style="border-right: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); overflow: hidden; padding: 2px 3px; vertical-align: bottom;">Test_Test_Test_Test4<br></td></tr></tbody></table>

**Please complete the following information:**
- Browser: firefox 130
- IMAP daemon: dovecot
- PHP version: 8.2
- SnappyMail Version: 2.37.3
- Mode: nextcloud

**Comment by the-djmaze** [comment]
Your table says `width: 0px`.
So it is obvious you don't see it.
