### ISSUE TITLE
Network response error: 403

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#1755]
**Describe the bug**
A user gets a "Network response error: 403" error (see screenshot below) when replying to a specific message. New email is not an issue and as far as I could tell most reply email goes fine.

I have standard logging enabled in SnappyMail config application.ini but the logfile only shows some errors not during time of sending the email. I can't find any error in the webserver log (as 403 seems to indicate?) and no error in the smtp (sendmail) logs. Not even attempts to a connection from the webmail server. Very strange!

The user is able to reproduce the error on the specific email. How do you think we should go forward with troubleshooting? Would server side debugging enabled be usefull? I can't ask this user to get client side javascript logging if that's even possible with Safari on Mac?

**To Reproduce**
1. Reply to a specific email that behaves like this.

**Expected behavior**
Send the email.

**Screenshots**
![image](https://github.com/user-attachments/assets/03fe2680-d82f-4e13-a8ce-d45b5176b0ef)

**Please complete the following information:**
- Browser: Safari
- IMAP daemon: Dovecot
- PHP version: 8.1
- SnappyMail Version: 2.33 and 2.38
- Mode: Standalone

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [] I've placed them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
HTTP 403 Forbidden can only happen:
1. secfetch_allow configuration fails
2. access disabled admin panel `allow_admin_panel = off`

**Comment by ervee** [comment]
I don't like to admit, but yes, the WAF broke this because it found some crap in the message body. I'll try to configure a bypass for that field.
