### ISSUE TITLE
Unable to load Admin page

### ISSUE THREAD

**Issue by uncled1023** [the-djmaze/snappymail#176]
**Describe the bug**
When trying to get to the admin page, it just spins continuously and the logs throw an error

```
PHP Notice:  SnappyMail\Crypt::Decrypt() invalid $data in <my path>\SnappyMail\snappymail\v\2.9.6\app\libraries\snappymail\crypt.php on line 64
```

**Desktop (please complete the following information):**
 - Browser Firefox and Chrome, cleared cache
 - SnappyMail Version 2.9.6

**Comment by Zero3K** [comment]
Has this been fixed thanks to https://github.com/the-djmaze/snappymail/commit/6ea42d317132a063eb9ea75edf33205f3e599621?

**Comment by phsc84** [comment]
Works perfectly fine for me in SnappyMail 2.10.0.

**Comment by uncled1023** [comment]
Looks to work now.  Closing as fixed.
