### ISSUE TITLE
Unread count on folders not showing

### ISSUE THREAD

**Issue by jkaberg** [the-djmaze/snappymail#1760]
**Describe the bug**
Pretty much the title, on login or refresh there is no unread count on folders - but there is when you open the one folder.

**To Reproduce**
1. Login
2. Look at folders

**Expected behavior**
See the unread count next to the folder name

**Screenshots**
I have none I'd like to share (private content), but if necessary I can create an separate account and do it

**Please complete the following information:**
- Browser: See [here](https://www.whatismybrowser.com/w/ZBMF3F6)
- IMAP daemon: Stalwart 0.9.4
- PHP version: 8.2.22
- SnappyMail Version: 2.38.0
- Mode: Docker

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)

**Additional context**
Let me know how to proceed here, I'm a bit unsure.

**Comment by the-djmaze** [comment]
1. Login or refresh
2. Wait N minutes (default is 15 for `Check mail interval`)
3. If the `unread count` comes in, it works as expected

See https://github.com/the-djmaze/snappymail/wiki/Improve-performance#disable-folders-list-status
This is probably not supported by Stalwart

**Comment by the-djmaze** [comment]
1. Go to SnappyMail ?admin
2. Open the domain settings
3. Test the domain with login credentials
4. See the list of `disable capabilities` being updated and longer
5. Check if LIST-STATUS is in there and unchecked
6. Check below if `limit` is set to 0

**Comment by jkaberg** [comment]
This is how it looks after an successful test, and yes Limits messages is 0 - still not loading any unread counts on entering Snappymail (ref OP)

![image](https://github.com/user-attachments/assets/90a50e2f-c3da-49aa-b3ed-d5991dd18825)

**Comment by the-djmaze** [comment]
I don't see `LIST-STATUS` in your list, that's why it is not working.

**Comment by jkaberg** [comment]
@the-djmaze just wanted to let you know `LIST-STATUS` has been added and snappymail now works as it should 🎆 

https://github.com/stalwartlabs/mail-server/releases/tag/v0.10.2
