### ISSUE TITLE
vCard FN property not updated when modifying contact details

### ISSUE THREAD

**Issue by mstolf** [the-djmaze/snappymail#1761]
**Describe the bug**
When updating a contact's information (name and surname), the changes are reflected correctly in the database fields first_name and last_name, but the vCard property associated with the contact is not updated accordingly. This leads to inconsistencies between the database and the vCard data.

**To Reproduce**
1. Update a contact’s first name or last name.
2. Check the database, and confirm that the first_name and last_name fields are updated.
3. Check the vCard property – it remains unchanged.

**Expected behavior**
When updating contact details (e.g., name or surname), the vCard property should be updated to reflect the changes.

**Screenshots**

**Please complete the following information:**
- Browser: Chrome 129.0.6668.59 (Version oficial) 64 bits
- IMAP daemon: Dovecot
- PHP version: 8.3
- SnappyMail Version: 2.36.1
- Mode: Nextcloud

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
Here is the payload sent when updating the contact. In this case, I updated the contact from "Nome" to "Nome 2". It can be seen that the N property was updated, but the FN property was not:

`{"uid":"11","jCard":"[\"vcard\",[[\"version\",{},\"text\",\"4.0\"],[\"n\",{},\"text\",[\"\",\"Nome 2\",\"\",\"\",\"\"]],[\"org\",[],\"text\",[\"\",\"\"]],[\"x-crypto\",{\"allowed\":\"PGP/INLINE,PGP/MIME,S/MIME,S/MIMEOpaque\",\"signpref\":\"Ask\",\"encryptpref\":\"Ask\"},\"x-crypto\",\"\"],[\"rev\",[],\"timestamp\",\"2024-09-18T13:59:44Z\"],[\"uid\",[],\"text\",\"0b99ea2e-9e37-4619-b41d-21dd1770746e\"],[\"fn\",[],\"text\",\"Nome\"],[\"prodid\",[],\"text\",\"SnappyMail-2.36.1\"]]]","showToast":true,"Action":"ContactSave"}
`

**Comment by the-djmaze** [comment]
Correct. Currently the code to update FN is disabled.
https://github.com/the-djmaze/snappymail/blob/16cc17af002445ec939beae527a90c4d0d6bc759/dev/Model/Contact.js#L248

This is because N consists of 5 fields, and below i show which SnappyMail currently can edit:
[x] surName
[x] givenName
[ ] middleName
[ ] namePrefix
[ ] nameSuffix

So when all 5 can be edited the FN can be activated.

**Comment by mstolf** [comment]
Of course, I'm interested in making this correction, can I insert these fields to record the middle name, first name suffix and first name prefix?

**Comment by mstolf** [comment]
OK, I'm interested in developing this fix

So to update the FN property we will need to: 
- [ ] Add the fields middle name, first name prefix, and first name suffix to the Contacts screen
- [ ] Persist property data N as per example in the property table with prop_type 251: Example 
`["n",{},"text",["surName","givenName","middleName","namePrefix","nameSuffix" ]]`

Should I create a record for each of these properties? If yes, which one to use for each of them?

**Comment by the-djmaze** [comment]
There's no need to modify the database.
SnappyMail only uses the old database fields for old RainLoop code.

**Comment by mstolf** [comment]
Could you please reopen this issue? I am submitting a pull request to fix the translations of the fields added for the pt-BR language.
