### ISSUE TITLE
Snappy Mail Admin Account

### ISSUE THREAD

**Issue by dzevadfazlic** [the-djmaze/snappymail#1764]
What's Snappy mail admin password?
I searched all over internet i could not find it.
I downloaded zip sile. Unziped. 

I found this docs.
https://snappymail.eu/documentation/admin-configuration
But there is no file /*/data/_data_/_default_/admin_password.txt, else use your own credentials.
Thank you.

**Comment by phsc84** [comment]
It is only created during installation: https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#now-access-the-admin-page
