### ISSUE TITLE
UI indicator of which pane has focus

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1765]
![image](https://github.com/user-attachments/assets/2d01197b-6641-408b-aed4-a18c06619bbe)

**Is your feature request related to a problem? Please describe.**
The keyboard shortcuts are great, but it is not clear to me where my keyboard focus currently is

**Describe the solution you'd like**
Add a 1 line bar at the top of each pane to indicate where we are currently focus

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by the-djmaze** [comment]
Normally the current active pane has a colored border.
Is it missing?
