### ISSUE TITLE
`Page up` and `Page down` should also paginate

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1766]
**Is your feature request related to a problem? Please describe.**
`Up`/`Down` keys currently can paginate when they reach the first or last message in the message list, however `Page up` and `Page down` only stays on the page.

**Describe the solution you'd like**
`Page up` and `Page down` should also paginate for faster scrolling, e.g. when searching for a nearby date

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by the-djmaze** [comment]
Correct, it depends on the focus.
https://github.com/the-djmaze/snappymail/blob/a4299c5f1cef1c2646ef7f91280424597e6dbb40/dev/Common/Selector.js#L271-L312

**Comment by bilogic** [comment]
Sorry, don't quite follow.

Focus is purely on `Message List`, up/down arrow keys will auto paginate, but page up/down will only stay on the current page. I'm suggesting that page up/down should also auto paginate.

**Comment by the-djmaze** [comment]
This changes the behavior in a way that is not expected by most users.
I will not implement it due to lack of time.
