### ISSUE TITLE
Snappy mail doesnt consume  an existing Maildir hierarchy when connecting to dovecot  

### ISSUE THREAD

**Issue by ivanbishop** [the-djmaze/snappymail#1772]
**Describe the bug**
I have a working install of postfix and dovecot on Ubuntu 22.

I am using virtual mailboxes in Dovecot

When I send mail from the internet postfix intercepts and delivers to Maildir e.g. to

![image](https://github.com/user-attachments/assets/c745d6bc-5829-4083-9bfe-d8b0aab90306)

New messages arrive into directory "new"

However, when I point snappymail to the server l it authenticates OK, but does N OT read the existing maildir structure. Instead it creates  series of empty folder.

 
![image](https://github.com/user-attachments/assets/ad5ae050-5162-43f6-88e5-c54bbbdd0e5f)

Why does snappymail not consume import the Maildir structure ?

Thanks
Ivan

Ubuntu 22.o04 LTS latest
Dovecot 1:2.3.16
Chrome or Firefox latest

**Comment by the-djmaze** [comment]
What does Thunderbird say?
I think something is wrong with your postfix/dovecot setup.

**Comment by ivanbishop** [comment]
I'll give that a try tomorrow :) , thanks.

**Comment by ivanbishop** [comment]
Thunderbird just finds the Inbox etc set up by Snappymail.

**A question**: Does Snappymail support virtual mailboxes as defined by Dovecot e.g.
https://doc.dovecot.org/2.3/configuration_manual/howto/simple_virtual_install/

My folder structure under virtual malboxes looks like this. cur/new/tmp directories hold the mail as delivered from postfix
![new](https://github.com/user-attachments/assets/c5e32a31-b636-48ed-b9bf-4f39e4950484)

**Comment by the-djmaze** [comment]
SnappyMail can handle virtual and shared mailboxes (see the demo where they are as example).

But looking at your directory structure, something is wrong on the server.
The folders are missing cur, new and tmp

**Comment by ivanbishop** [comment]
I'm going to wipe and re-install from scratch, something is amiss in the structure, you're correct 
I'll update later 
Thanks 
Ivan
