### ISSUE TITLE
When a TFA code isn't provided, yet TFA has been enabled error should be more clear

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#1773]
**Describe the bug**
Logging in to an account with two factor auth enabled, but failing to enter the TFA code results in this error:

AuthError[102]

It should instead say something like "Incorrect two factor authentication code"

**To Reproduce**
1. Enable TFA on an account
2. Log out
3. Log back in, but do not enter anything as the TFA code
4. You will get AuthError[102]

**Expected behavior**

It is expected that the provided error will be more informative so as to indicate to the user "oh yeah, I need to enter my TFA code"

**Please complete the following information:**
- Browser: Firefox 130.0.1 (also reproduced on Safari for macOS)
- IMAP daemon: Dovecot
- PHP version: 8.1
- SnappyMail Version: 2.38.0
- Mode: standalone

**Debug/logging information**
```
[2024-09-24 02:02:27.490][44830b41] PLUGIN[INFO]: Hook: login.success                                                                                                                                             
[2024-09-24 02:02:27.536][44830b41] [INFO]: TFA: Code required for EMAIL_ADDRESS                                                                                                             
[2024-09-24 02:02:28.403][44830b41] SERVICE[WARNING]: AuthError[102]                                                                                                                                              
/data/_data_/_default_/plugins/two-factor-auth/index.php#69                                                                                                                   
#0 /snappymail/v/2.38.0/app/libraries/RainLoop/Plugins/Manager.php(312): TwoFactorAuthPlugin->DoLogin()                                                                       
#1 /snappymail/v/2.38.0/app/libraries/RainLoop/Actions/UserAuth.php(176): RainLoop\Plugins\Manager->RunHook()                                                                 
#2 /snappymail/v/2.38.0/app/libraries/RainLoop/Actions/User.php(41): RainLoop\Actions->LoginProcess()                                                                         
#3 /snappymail/v/2.38.0/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoLogin()                                                                           
#4 /snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()                                                                       
#5 /snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()                                                                                 
#6 /snappymail/v/2.38.0/include.php(137): RainLoop\Service::Handle()                                                                                                          
#7 /index.php(11): include('...')      
```

**Comment by the-djmaze** [comment]
It will just be "Authentication failed" error.
We don't want obscure people to guess the right password.
Because when it says "TFA error" they know the password is correct.
And then they can use any other application to connect with IMAP or SMTP and do evil stuff...

**Comment by the-djmaze** [comment]
Some users do block imap/smtp/sieve external for internal use only.
They do profit the enforcement of the TOTP extension.

Others use fail2ban (which SnappyMail can) on the server to protect against brute force attacks.

All makes sense when webmail users can ask an administrator why their login fails or when they are banned by fail2ban.

My hosting customers can login on a website and query for the info.
They can also see the mail history via spam protection.

**Comment by jas8522** [comment]
> All makes sense when webmail users can ask an administrator why their login fails or when they are banned by fail2ban.

Mail admins are just going to see a successful login to the MTA and wonder why it's showing an auth failure. That's what happened to me... then I went to snappymail logs and saw nothing... I had to enable debug logging just to find out it was a TFA issue. Perhaps TFA failures should be in the regular logs.

**Comment by the-djmaze** [comment]
Yes i can change that 👍
