### ISSUE TITLE
List identifiers are being cut off on messages

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1775]
**Describe the bug**
When I view an email that includes a list, the numbers are being cut out to the left.  This occurs with messages I receive, or those I view in sent mail.  I thought this was previously resolved but I could be wrong.

**To Reproduce**
1. Compose a new message.
2. Include an ordered list.  It should show fine in the Compose window. Send the message.
3. View the sent message in the Sent folder.
4. See that the list is trimmed off on the left.

**Screenshots**
![Screenshot 2024-09-24 140705](https://github.com/user-attachments/assets/a7ea056f-abd1-4aea-bc59-c8b776541ac0)

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: dovecot
- PHP version: 8.1.2
- SnappyMail Version: 2.38.0
- Mode: nextcloud

**Comment by the-djmaze** [comment]
Yes this was resolved. I will look into it.

**Comment by the-djmaze** [comment]
Works fine here without any issues.
Maybe it is a problem inside the received email and you allow css/styles?

**Comment by BiglifeMatt** [comment]
FYI, It did seem to be only while using the Nextcloud 25+ theme in SnappyMail.

**Comment by the-djmaze** [comment]
Yes i figured it out. It was a problem in that theme.
