### ISSUE TITLE
snappymail -can't send

### ISSUE THREAD

**Issue by evritchie** [the-djmaze/snappymail#178]
Hello,
   I opened an issue earlier about STARTTLS support for SMTP, after your suggestion, I switched to SMTP over SSL and that worked. However, I'm having a strange issue where I cannot send at all. I tried SSL and none, I upgraded to 2.10.0 and tried STARTTLS, SSL and none but nothing works. I checked the snappymail logs and postfix logs but find nothing useful. This was working but started to fail a few days ago.
Can you give me some ideas to increase logging or debug output to help resolve. When I try to send an email, I just get the red "Can't send message" error.
Thanks
Eric

**Comment by Psychi1** [comment]
Hi,

are there any infommation in the logs? 

https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

Sometimes I face the problem with false formated e-mail adresses.

**Comment by evritchie** [comment]
This turned out to be a proxy issue. Thanks for your help, using the browser console I was able to see the exact error.
Eric

**Comment by evritchie** [comment]
Can you help me with 1 more issue. Using SnappyMail, users from address is set to ***@***.***, where hostname is the web server. I would like the from address to be ***@***.***

Thanks
Eric


From: ***@***.***>
Sent: Wednesday, January 5, 2022 5:26 AM
To: ***@***.***>
Cc: Eric ***@***.***>; ***@***.***>
Subject: [EXTERNAL] Re: [the-djmaze/snappymail] snappymail -can't send (Issue #178)


Closed #178<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthe-djmaze%2Fsnappymail%2Fissues%2F178&data=04%7C01%7Ceritchie%40interactivebrokers.com%7C696d603a394d4e4acfce08d9d035da02%7C7abd04ef837d48e69ba869d84f65a110%7C0%7C0%7C637769752005888023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4jzGLafkBbjDESQ0q%2BS1IPVVG5GQSVN1VtDSzBKnWJI%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthe-djmaze%2Fsnappymail%2Fissues%2F178%23event-5845529215&data=04%7C01%7Ceritchie%40interactivebrokers.com%7C696d603a394d4e4acfce08d9d035da02%7C7abd04ef837d48e69ba869d84f65a110%7C0%7C0%7C637769752005888023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P1HBNAfhBP6vhMBX%2FBWXoxTN1t%2F8rmNZKfEskDVxV28%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW6ZXIXPHJGU5DRH2IIOMTLUUQMFBANCNFSM5LABX2EQ&data=04%7C01%7Ceritchie%40interactivebrokers.com%7C696d603a394d4e4acfce08d9d035da02%7C7abd04ef837d48e69ba869d84f65a110%7C0%7C0%7C637769752005897984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=flZ7KVxaQXyB7DCAkEz85JSnTG9P9Wh7bPOWsAn2A50%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ceritchie%40interactivebrokers.com%7C696d603a394d4e4acfce08d9d035da02%7C7abd04ef837d48e69ba869d84f65a110%7C0%7C0%7C637769752005897984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GSd0CZWzRr30wnRIgvkw1B1lCn1Bh2r5AoySAFx2sOc%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ceritchie%40interactivebrokers.com%7C696d603a394d4e4acfce08d9d035da02%7C7abd04ef837d48e69ba869d84f65a110%7C0%7C0%7C637769752005907936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RVsDkecBAk9HtxDAdO8PWoROCntzMLRYSdJpKPpWk%2BA%3D&reserved=0>.

**Comment by tobkra** [comment]
@evritchie while I am too unfamiliar with snappymail/rainloop to know if it supports this functionality, I accomplish [outgoing sender remapping through postfix](http://www.postfix.org/ADDRESS_REWRITING_README.html#generic), which is my mail transport agent (MTA).

**Comment by the-djmaze** [comment]
This totally depends on your SMTP setup.

For example i can login as `djmaze`
Then my from address is `djmaze@mail.example.com`

However, in Settings -> Accounts i can add new Identities.
URI: `/#/settings/accounts`

My Postfix is configured in a way that `djmaze` can send from any domain that is attached to his account.
This means that if `djmaze` has domain `example.org` he can send e-mails as `djmaze@example.org`, `noreply@example.org`, etc. etc.
But not `djmaze@example.net` because `example.net` is not attached to his account.

When you have a login as `evritchie@example.net` then the From header should be the same.

**Comment by evritchie** [comment]
Hi,
   Yes, postfix is already setup to allow this email to be delivered. However, its not the preferred method. For example, when a user logs into snappymail, they see user@webserver in the top right, instead of user@mail. I tried setting an identity but that didn't work. I did notice if that I log in with user@mail, instead of just user, it works.

Thanks
Eric
