### ISSUE TITLE
 Search Filter Issue with Capital "B"

### ISSUE THREAD

**Issue by menached** [the-djmaze/snappymail#1780]
**Describe the bug**
In SnappyMail, the search filter does not recognize the capital letter "B" when entered. This issue occurs only in the SnappyMail app; the key works correctly in other applications and browser tabs.

**To Reproduce**
1. Open SnappyMail in Nextcloud.
2. Attempt to search using a capital "B".
3. Observe that the search filter will not allow entering the letter "B".  Other letters can be entered without issue.

**Expected behavior**
The search filter should accept capital "B" and return relevant results.

**Screenshots**

**Please complete the following information:**
- Browser: Checked in Chrome and Firefox
- IMAP daemon: dovecot
- PHP version: 8.2
- SnappyMail Version: 2.38.0
- Mode: Nextcloud 

I dont see anything in the console log reported.
![CantTypeB](https://github.com/user-attachments/assets/7876ca99-05fe-4fc3-8963-7722a5f71151)

**Comment by the-djmaze** [comment]
This is caused by #1690
