### ISSUE TITLE
Allow users to choose how to open messages on double-click

### ISSUE THREAD

**Issue by eriksid** [the-djmaze/snappymail#1791]
**Is your feature request related to a problem? Please describe.**

Yes, the current behavior of double-clicking opens the system in full screen, which might not be the desired action for all users. This lack of flexibility can be frustrating for users who prefer different behaviors.

**Describe the solution you'd like**

I propose adding a configuration option to customize the double-click behavior. This would allow users to choose from several options:

* **Default:** Does nothing on double click.
* **Open without split:** Opens the message in the reading pane without splitting the screen. It should include functionalities for replying and labeling, exactly  how the existing reading panel experience.
* **Open in a new tab:** Opens the message in a new tab, allowing users to keep the message list visible. Similar to "Open without split," it should have options to reply and label.
* **Open in full screen:** Maintains the current behavior (introduced in commit [68045f5](https://github.com/the-djmaze/snappymail/commit/68045f50f627b5a25b05fb0e777caaae0f1ecae7)) of opening the message in full screen.

**Describe alternatives you've considered**

N/A (This section is best used if there were other potential solutions considered but ultimately rejected)

**Additional context**

This feature would improve user experience by providing flexibility and customization for how users interact with messages. 

Here are mockups to illustrate the proposed "Open without split" and "Open in a new tab" functionalities:

* **Open without split mockup:** 
![image](https://github.com/user-attachments/assets/3ca40ec6-ce65-4002-87b6-5eb84dc864c1)
* **Open in a new tab mockup:** 
![image](https://github.com/user-attachments/assets/3b422687-6bd8-415b-81bc-d5d857339418)

I am enthusiastic about this feature and would be happy to develop and submit a Pull Request for its implementation if there's interest from the development team.

**Comment by the-djmaze** [comment]
There are someissues with your request.

1. Current behavior
- When a message is part of a thread, double click opens the thread.
- When a message is NOT part of a thread, double click opens it full-screen due to #1787

2. Open without split is not possible due to the layout setting 
![afbeelding](https://github.com/user-attachments/assets/6544e367-3852-40e2-ba1b-ee71d9d58925)
3. Options have no effect in mobile view
4. Open in a new tab not possible as it has no interaction options

**Comment by the-djmaze** [comment]
Too complex for a simple webmail viewer
