### ISSUE TITLE
Reading attached `.eml`

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1792]
![image](https://github.com/user-attachments/assets/ac2ff700-f62b-4f1f-a2b0-5689bf76022e)

**Is your feature request related to a problem? Please describe.**
Details of the error (which I need to fix the problem) are in the attached `.eml` file and I can't read them in the browser

**Describe the solution you'd like**
Parse and display embedded `.eml` files

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by the-djmaze** [comment]
Did you try clicking the icon?

**Comment by bilogic** [comment]
I did, it downloads

**Comment by bilogic** [comment]
Ok, I tried again, I clicked the name and it downloaded, if I hover over the icon and click the eye, it opens in a new tab (which is what I expected)

Thank you.
