### ISSUE TITLE
Place message of new thread in `Inbox`

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1793]
**Is your feature request related to a problem? Please describe.**
I checked `Place replies in the folder of the message being replied to` so that all mails are kept in `Inbox`.
However, when it is a new message, they are placed in `Sent`.

**Describe the solution you'd like**
Have an option to move all messages in `Sent` to `Inbox`.

**Describe alternatives you've considered**
Manually moving `Sent` messages to `Inbox`

**Additional context**
N/A

**Comment by the-djmaze** [comment]
This sounds like a problem of your mail server and not SnappyMail.
As it works fine here.

**Comment by bilogic** [comment]
So, if you click on "New message" and send your first ever email to me, it goes into your INBOX and not SENT? How do I make it go to another folder other than INBOX then?

**Comment by the-djmaze** [comment]
"New message" is not the same as "replies".
Now you are asking something totally different.

**Comment by bilogic** [comment]
Thanks, I get it now. Perhaps it would be user friendly to add a hint at `Place replies in the folder of the message being replied to`.

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/22546993-307c-4e7b-832d-e33a06a5f940)

I'm not able to set my INBOX as the Sent folder (It's greyed out)

**Comment by the-djmaze** [comment]
Ah yes, i see what is happening here.
Will see if the restriction can be removed.
But keep in mind that other applications may not allow what you want.
I know that KMail of KDE in GNU/Linux OS can do what you want.

**Comment by bilogic** [comment]
well, i'm going all in on snappymail.. very unconcerned with other clients :) thanks!

**Comment by bilogic** [comment]
Sure, as long as it files to the INBOX without me having to move it constantly. Thanks!

**Comment by the-djmaze** [comment]
This is not perfect yet, but if you have some JavaScript skills you can modify the code of the plugin i just created.
Keep in mind that it will only work with the upcoming release v2.38.1

![afbeelding](https://github.com/user-attachments/assets/050a82d8-ceb5-4168-a8ce-100002ec0767)

**Comment by the-djmaze** [comment]
Admin -> Extensions -> "Send Save In"

**Comment by bilogic** [comment]
![image](https://github.com/user-attachments/assets/6193a5eb-1d18-4488-9f17-38204e0b6c10)

I propose adding some remarks for `Place replies in the folder of the message being replied to` as well. Will try a PR if you are ok. Let me know thanks!

**Comment by the-djmaze** [comment]
Sure go ahead!
