### ISSUE TITLE
JS/KO error '$index is not defined' in Settings > Accounts 

### ISSUE THREAD

**Issue by SergeyMosin** [the-djmaze/snappymail#1797]
**Describe the bug**
Clicking on the `Accounts` tab in the `Settings` does not work on the first try in `v2.38.1`

**Details**
Browser console error:
```
Uncaught ReferenceError: Unable to process binding "template: () => ({ name: RoutedSettingsViewModel.template })"
Message: Unable to process binding "foreach: ()=>(identities)"
Message: Unable to process binding "visible: ()=>(0 === $index())"
Message: $index is not defined
```

This is most like a regression from https://github.com/the-djmaze/snappymail/commit/c14bbab945705457e088eaffb49cc81d8b53889c 

Possible fix is to replace this:
https://github.com/the-djmaze/snappymail/blob/ececfae31ae64fb5f617183dfb029e809879903a/snappymail/v/0.0.0/app/templates/Views/User/SettingsAccounts.html#L62
with something like this:
```html
<span class="identity-default" data-bind="visible: id() === ''" data-i18n="GLOBAL/DEFAULT"></span>
```
_only secondary identities have `id`s_

**Comment by the-djmaze** [comment]
I had the same error once and never again.
Will try to replicate and see what causes it.

**Comment by the-djmaze** [comment]
Although it is fixed, i might have a better approach for the deprecated `with` statement.
It also make the template bindings much more secure.

I have to test this change how much it will impact the speed.
https://github.com/the-djmaze/snappymail/commit/904a353bffd0aced84c6058041ca6648069187c2
