### ISSUE TITLE
Disable indentation when replying

### ISSUE THREAD

**Issue by bilogic** [the-djmaze/snappymail#1801]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/4a54cd99-f22d-4708-9ec3-988bdd4fc944)

Yes, there are only a finite number of lines we can draw before the whole conversation becomes unreadable. A more sustainable approach is to avoid indenting.

**Describe the solution you'd like**
Have an option in settings to not indent when replying

**Describe alternatives you've considered**
It takes about 10-20 lines (replies) before half the screen is occupied by it, before someone says why so many replies? We can check up many replies there are on some github issues.

**Additional context**
No

**Comment by the-djmaze** [comment]
You can set "Maximum visible quoted text levels".
And can delete replies.

Indentation has a purpose and it will stay.
You could develop a theme that kills it for your own purpose.

**Comment by bilogic** [comment]
I understand indentation is your perogative, but just another example of how UI readability is affected by indentation IRL. I will take a look at the CSS. Thanks.

![image](https://github.com/user-attachments/assets/9e5760eb-0388-4171-a91a-8da5a31ae8c7)

**Comment by the-djmaze** [comment]
> I understand indentation is your perogative, but just another example of how UI readability is affected by indentation IRL.

Correct. If there is no indentation, you will not know which email is replied to in the tree.
![afbeelding](https://github.com/user-attachments/assets/6c7eaa53-c5d3-4662-a024-7ad0aa20b25f)


> I will take a look at the CSS. Thanks.

Good luck! If you need help with that, [start a discussion](https://github.com/the-djmaze/snappymail/discussions)

**Comment by bilogic** [comment]
Yes, this indentation does helps prevent what I call an email multiverse (where participants have completely different understanding of the facts/situation), but I can't recall another client that does this for message lists. It also makes it impossible to have messages lined up according to time.

I always see github issues as the best reference model for good and clear communication, i.e. only 1 conversation taking place at a time, if a conversation requires a sub-conversation, it probably deserves its own space in another conversation.

Anyway, thanks.
