### ISSUE TITLE
Update sabre-io libraries

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#1806]
Snappymail 2.38.2 uses:
- sabre/vobject 4.5.4
- sabre/xml 4.0.5

Meanwhile newer versions have been released:
- https://github.com/sabre-io/vobject/releases/tag/4.5.6
- https://github.com/sabre-io/xml/releases/tag/4.0.6

Therefore an update should be considered.

**Comment by the-djmaze** [comment]
Updated:
https://github.com/the-djmaze/sabre-xml
https://github.com/the-djmaze/sabre-vobject
