### ISSUE TITLE
SnappyMail upgrade to 2.38.2 resulted in leaving Nextcloud in maintenance mode

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1808]
**Describe the bug**
Upgrade 2.38.1 to 2.38.2 and Nextcloud will hand in maintenance mode until manually overridden.

**Comment by the-djmaze** [comment]
This has been reported a lot (even by you).
But we stil have no clue why Nextcloud does that.

Only detailed logs might help.
