### ISSUE TITLE
Cannot reply to an email selecting a different from email address

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#1812]
**Describe the bug**

**To Reproduce**

More then one account configured in Snappy Mail.
An email is received on the account A and I want reply with the email B but the from address has no drop down menu.
Also if I type the email address manually the signature is not updated.

**Expected behavior**

A drop down in the from email address allow to select the from email address

**Please complete the following information:**
- Browser: Firerfox 131.0.3
- IMAP daemon: dovecot
- PHP version: 8.3
- SnappyMail Version: latest one. There is a screen in snappymail with the version? 2.38.2
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] github manual install

**Comment by the-djmaze** [comment]
Correct, this is currently not supported.
If your SMTP allows it, you can just manually edit the from.

**Comment by PeopleInside** [comment]
I remember this was working in the past. Has been removed?

**Comment by the-djmaze** [comment]
You are talking about accounts.
The other is about identities.

**Comment by PeopleInside** [comment]
No, I'm not talking about swiching account but reply from account A and select a different from address.
I remember to be able to do this with snappymail like Thunderbird allow to.

The issue linked show a composing email opened then selected a different from email address.
I remember this function was present.

**Comment by PeopleInside** [comment]
Oh maybe is because I have just a single identity in one account so if so you are right.
In the settings there is a identity page where you can set different identities.

OK so if I have address A and receive an email but I want reply with the address B and signature B I need go in the settings of the account A and add identity and signature of the account B.

I dont tested this, my server never allow send from an address not authenticated but now I understood why in the past I have this.
