### ISSUE TITLE
[Squire] Switch between HTML <-> Source changes mail body

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#1815]
**Describe the bug**
The button "HTML <-> Source" should just switch the view but not delete elements from the mail body.

**To Reproduce**
1. Open any mail.
2. Click reply or reply all.
3. Click on the "HTML <-> Source" button to get to the HTML source.
4. The mail starts with: `<div><br><br></div><p>October 17, 2024...`
5. Click twice on the "HTML <-> Source" button to get back to the formatted view and forth to the HTML source.
6. The mail starts with: `<div><br></div><p>October 17, 2024`
7. Again, click twice on the "HTML <-> Source" button to get back to the formatted view and forth to the HTML source.
8. The mail starts with: `<p>October 17, 2024`

After this procedure you can click on the "HTML <-> Source" button as much as you want, but nothing will change anymore.

**Expected behavior**
The "HTML <-> Source" button should not change anything in the HTML source.

**Screenshots**

**Please complete the following information:**
- Browser: Chrome 129
- SnappyMail Version: 2.38.2
- Mode: standalone

**Comment by phsc84** [comment]
Something very similar also happens when you paste something:
1. Open any mail.
2. Click reply or reply all.
3. The mail starts with: `<div><br><br></div><p>October 17, 2024...`
4. Paste something (e.g. "test", it does not matter if some text or a link) into the mail answer.
5. One line disappears and the mail starts with: `<div>test<br></div><p>October 17, 2024...`

**Comment by the-djmaze** [comment]
Actually this is a side effect of bugs in browsers.
I explain here: https://github.com/the-djmaze/snappymail/issues/1389#issuecomment-2389686226

Maybe Squire should just always add the `<br>` at html mode or not remove the br at export.

But it will also be an issue on save as draft and edit again.

This has to be thought out big time how to solve.

**Comment by phsc84** [comment]
@the-djmaze
How about a new release? Would love to test this as well!

**Comment by the-djmaze** [comment]
Soon, had some other priorities
