### ISSUE TITLE
outlook connection error

### ISSUE THREAD

**Issue by gpopesc** [the-djmaze/snappymail#1818]
**Describe the bug**
I used automatic configuration from  snappy mail, also manual setting with server:   imap-mail.outlook.com
![Screenshot from 2024-10-22 00-14-18](https://github.com/user-attachments/assets/2ee78a50-93f5-4771-964e-9fa9129cc503)

In the past, it used to work with snappy  mail. I don't know if it is a microsoft error or snappy mail error.
in the test version

I use snappy in nextcloud version 30, together with firefox or avant browser.

Here it is bellow full error:

![Screenshot from 2024-10-22 00-18-16](https://github.com/user-attachments/assets/f01bbd0c-1f4f-4deb-927a-a118b79dc69b)

[2024-10-21 21:05:48.510][59fefcc5] [INFO]: [SM:2.38.2][IP:192.168.1.100][PID:4408][Apache/2.4.62 (Debian)][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://nc.ubx.ro/apps/snappymail/run/?/Json/&q[]=/0/]
[2024-10-21 21:05:48.511][59fefcc5] Nextcloud[DEBUG]: integrated
[2024-10-21 21:05:48.515][59fefcc5] JSON[INFO]: Action: DoAccountSetup
[2024-10-21 21:05:48.515][59fefcc5] POST[INFO]: {"email":"*******@outlook.com","password":"*******","name":"fgsdfg","new":"1","Action":"AccountSetup"}
[2024-10-21 21:05:48.517][59fefcc5] PHP[CRITICAL]: Caught SIGCHLD {"signo":17,"errno":0,"code":1,"status":1,"utime":0,"stime":0,"pid":4424,"uid":33}
[2024-10-21 21:05:48.519][59fefcc5] IMAP[INFO]: Start connection to "ssl://outlook.office365.com:993"
[2024-10-21 21:05:48.625][59fefcc5] IMAP[INFO]: Connect (success)
[2024-10-21 21:05:48.625][59fefcc5] IMAP[DEBUG]: 0.1062159538269 (raw connection)
[2024-10-21 21:05:48.654][59fefcc5] IMAP[INFO]: < * OK The Microsoft Exchange IMAP4 service is ready. [VgBJADEAUABSADAAOABDAEEAMAAyADUAMAAuAGUAdQByAHAAcgBkADAAOAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]\r\n
[2024-10-21 21:05:48.654][59fefcc5] IMAP[DEBUG]: 0.13554310798645 (*)
[2024-10-21 21:05:48.654][59fefcc5] PLUGIN[INFO]: Hook: imap.before-login
[2024-10-21 21:05:48.655][59fefcc5] IMAP[INFO]: > TAG1 CAPABILITY\r\n
[2024-10-21 21:05:48.685][59fefcc5] IMAP[INFO]: < * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+\r\n
[2024-10-21 21:05:48.685][59fefcc5] IMAP[INFO]: < TAG1 OK CAPABILITY completed.\r\n
[2024-10-21 21:05:48.685][59fefcc5] IMAP[DEBUG]: 0.030441045761108 (TAG1)
[2024-10-21 21:05:48.685][59fefcc5] IMAP[INFO]: > TAG2 AUTHENTICATE PLAIN *******\r\n
[2024-10-21 21:05:49.127][59fefcc5] IMAP[INFO]: < TAG2 NO AUTHENTICATE failed.\r\n
[2024-10-21 21:05:49.127][59fefcc5] IMAP[DEBUG]: 0.4417839050293 (TAG2)
[2024-10-21 21:05:49.128][59fefcc5] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException:  AUTHENTICATE failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(529): MailSo\Imap\ResponseCollection->validate()
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(276): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(218): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(451): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#14 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#15 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#17 /var/www/html/index.php(24): OC::handleRequest()
#18 {main}
[2024-10-21 21:05:49.128][59fefcc5] IMAP[NOTICE]: MailSo\Imap\Exceptions\NegativeResponseException:  AUTHENTICATE failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(529): MailSo\Imap\ResponseCollection->validate()
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(276): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(218): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(451): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#14 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#15 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#17 /var/www/html/index.php(24): OC::handleRequest()
#18 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException:  AUTHENTICATE failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php:232
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(276): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(218): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(451): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#9 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#12 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#13 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#15 /var/www/html/index.php(24): OC::handleRequest()
#16 {main}
[2024-10-21 21:05:49.129][59fefcc5] SERVICE[WARNING]: AuthError[102] ( AUTHENTICATE failed.)
/var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php#462
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#6 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#9 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#10 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#12 /var/www/html/index.php(24): OC::handleRequest()
#13 {main}
[2024-10-21 21:05:49.129][59fefcc5] SERVICE[WARNING]: - MailSo\Imap\Exceptions\NegativeResponseException:  AUTHENTICATE failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(529): MailSo\Imap\ResponseCollection->validate()
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(276): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(218): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(451): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#14 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#15 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#17 /var/www/html/index.php(24): OC::handleRequest()
#18 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException:  AUTHENTICATE failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/MailSo/Imap/ImapClient.php:232
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(276): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Model/Account.php(218): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(451): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#9 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#12 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#13 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#15 /var/www/html/index.php(24): OC::handleRequest()
#16 {main}
[2024-10-21 21:05:49.129][59fefcc5] [ERROR]: AuthError[102] ( AUTHENTICATE failed.)
/var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php#462
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(172): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Accounts.php(89): RainLoop\Actions->LoginProcess('gpopesc@outlook...', Object(SnappyMail\SensitiveString), false)
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoAccountSetup()
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(116): RainLoop\Service::Handle()
#6 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(106): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\SnappyMail\Controller\PageController->appPost()
#8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#9 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'appPost')
#10 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('PageController', 'appPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/apps/snappymai...')
#12 /var/www/html/index.php(24): OC::handleRequest()
#13 {main}
[2024-10-21 21:05:49.129][59fefcc5] JSON[INFO]: {"Action":"AccountSetup","Result":false,"code":102,"message":"AuthError[102]","messageAdditional":" AUTHENTICATE failed.","ExceptionCode":0,"epoch":1729544749}
[2024-10-21 21:05:49.129][59fefcc5] [INFO]: Memory peak usage: 6MB
[2024-10-21 21:05:49.129][59fefcc5] [INFO]: Time delta: 0.67709493637085
[2024-10-21 21:05:49.130][59fefcc5] IMAP[INFO]: Disconnected from "ssl://outlook.office365.com:993" (success)
[2024-10-21 21:05:49.130][59fefcc5] IMAP[DEBUG]: 0.61072397232056 (net session)

**Comment by ccci-code** [comment]
Microsoft will no longer allow you to login using username and password so you need to make some changes to the code to use XOAUTH2.  You'll also need to configure Microsoft with the correct redirect URL in the Microsoft Entra admin center and set up your credentials there.

I added my notes on how to get Snappymail to work with Microsoft work accounts:

https://github.com/the-djmaze/snappymail/issues/1777#issuecomment-2392156538

You have to use the scopes "offline_access https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send" instead of using to "https://graph.microsoft.com/" scopes authenticate with the Microsoft IMAP server.  The incorrect scopes are in plugins/login-o365/LoginOAuth2.js.

Somewhat working fork
https://github.com/ccci-code/snappymail

**Comment by the-djmaze** [comment]
Correct, you need the extension.
See #1645
