### ISSUE TITLE
Snappymail not syncing to carDAV server

### ISSUE THREAD

**Issue by BeeFox-sys** [the-djmaze/snappymail#1821]
I have a cardav server, running via etesync-dav. I have correctly added the syncronization to my account, however when i click sync no requests are recieved by nginx, other software such as etesync-web correctly connects to the account, however not snappymail. all the connection settings are the same, it seems that snappymail just isn't sending the requests?

**Comment by the-djmaze** [comment]
Without logs we can't do anything
