### ISSUE TITLE
TOTP - Call to protected method RainLoop\Actions::LoggerAuthHelper()

### ISSUE THREAD

**Issue by dborg89** [the-djmaze/snappymail#1825]
**Describe the bug**
Trying to log in as either admin or a imap user, however I am getting errors from the TOTP on login.
Unknown error
Server message: Call to protected method RainLoop\Actions::LoggerAuthHelper() from scope TwoFactorAuthPlugin

**To Reproduce**
1. Go to Webmail Login page
2. Enter user/email address
3. Enter password
4. Enter TOTP
5. Click Sign In
8. See error

**Expected behavior**
Page should load you to the desired "Home" page (eg: admin portal or mailbox).

**Screenshots**
NA

**Please complete the following information:**
- Browser: Version 130.0.6723.70 (Official Build) (64-bit)
- IMAP daemon: dovecot
- PHP version: 8.3 (FPM)
- Web server; nginx
- SnappyMail Version: 2.38.2
- Mode: standalone

**Debug/logging information**
[2024-10-30 04:31:26.117][ab2349c0] SERVICE[WARNING]: Error: Call to protected method RainLoop\Actions::LoggerAuthHelper() from scope TwoFactorAuthPlugin in /var/www/webmail/snappymail-data/_data_/_default_/plugins/two-factor-auth/index.php:82
Stack trace:
#0 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/Plugins/Manager.php(337): TwoFactorAuthPlugin->DoLogin()
#1 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php(178): RainLoop\Plugins\Manager->RunHook()
#2 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess()
#3 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoLogin()
#4 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#5 /var/www/webmail/html/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#6 /var/www/webmail/html/snappymail/v/2.38.2/include.php(137): RainLoop\Service::Handle()
#7 /var/www/webmail/html/index.php(11): include('...')
#8 {main}

**Additional context**
I was on an older version when the error first occurred 2.37.3, so thought while I try to resolve this I would upgrade.
Issue still present on current version.

**Comment by myuseraccount** [comment]
I suddenly (starting today) began having this problem, also running 2.38.2, on shared hosting.  I even tried making the code change in the linked commit, but then it just changes to the following error.

```
Authentication failed

Server message: AuthError[102]
```
It also gives this error if I leave the verification code box blank, and regardless of whether I check the box to Remember Me.
