### ISSUE TITLE
 After login frustratingly land on Edit Identity pop-up instead of in the inbox 

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#1827]
**Describe the bug**
 After login one lands on Edit Identity pop-up instead of in the inbox as expected

**To Reproduce**
1. Login to Snappymail
2. Instead of landing in the inbox, land on Edit identity pop-up instead
3. Get mildly annoyed, close Edit identity box. Then confirm I actually want to close it (also annoying)

**Expected behavior**
I want to land in the inbox like has always been the case until a relatively recent update introduced this weird & frustrating current behaviour. Why would anyone want to edit their identity every single time they login? :thinking: 

**Screenshots**

![image](https://github.com/user-attachments/assets/d3be98a4-caf9-4f1d-a758-890d6db4cc77)

**Please complete the following information:**
- Browser: pretty sure it happens in latest Firefox and Chrome on Ubuntu
- IMAP daemon: Dovecot
- PHP version: Not sure - but it happens on the demo too
- SnappyMail Version: whatever is running on the demo
- Mode: Cloudron app, but exact same behaviour can be seen on https://snappymail.eu/demo/

**Comment by jdaviescoates** [comment]
Just testing on the demo it seems that if you enter something into the Name and Label fields and save then it doesn't happen on the next login. It's still sub-optimal at present though.

**Comment by the-djmaze** [comment]
See #1689 why it is changed
