### ISSUE TITLE
Snappymail - logs out automatically way too fast

### ISSUE THREAD

**Issue by stef204** [the-djmaze/snappymail#1831]
Version 2.38.2
Docker

Snappymail - Docker logs out automatically way too fast

Not sure if token expires too quickly, is that configurable?  Or is it session cookies which expire too soon?

But result is that it logs itself out periodically, quite often.  

I'd like to be able to control that or eliminate it all together, and only log out when I choose to manually.

**Comment by the-djmaze** [comment]
Settings -> Security -> Auto Logout
![afbeelding](https://github.com/user-attachments/assets/a0ad11d4-056a-4bff-9e73-4b714ce5f629)
