### ISSUE TITLE
Search for keyword yields “message list not available”

### ISSUE THREAD

**Issue by ruedigerkupper** [the-djmaze/snappymail#1832]
**Describe the bug**
Clicking the arrow field to the right of the search field shows an advanced dialog where you can specify search options. They all work as expected, except searching for keywords. The search always yields “This message list is not available”.

**To Reproduce**
Attach a keyword (label) of your choice to any message. Try to search for it using the advanced search dialog. Observe it does not work.

**Expected behavior**
The message list should show the messages with the respective keyword.

**Screenshots**
![IMG_0349](https://github.com/user-attachments/assets/cf532db1-92b6-4d04-8532-10f78ade1725)

**Please complete the following information:**
- Browser: any
- IMAP daemon: cyrus
- PHP version: 8.3.12
- SnappyMail Version: 2.38.2
- Mode: nextcloud

**Additional Information**
Keyword search works as expected using the standard Nextcloud mail app. The problem must hence be in snappy mail, not the IMAP server.

**Comment by the-djmaze** [comment]
It works on my Dovecot instances perfectly.

Please provide debug info with good examples why your Cyrus fails.

**Comment by ruedigerkupper** [comment]
Example: see above, I have added keyword "Test" in another IMAP-Client (Nextxloud's standard mail app) and Snappy fails to find it, displaying an error message that should never be shown to the user.
Other IMAP-Clients operate as expected.

**Comment by ruedigerkupper** [comment]
> It works on my Dovecot instances perfectly.

Have you tested interaction with other IMAP clients (setting new keywords in other clients ans then searching for them in Snappy?

**Comment by the-djmaze** [comment]
> I have added keyword "Test" in another IMAP-Client (Nextcloud's standard mail app)

But that app is broken. See my report https://github.com/nextcloud/mail/issues/10159
