### ISSUE TITLE
Old versions inside the release public/snappymail/v/ and space usage

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#1836]
During backup I discovered that any new release contains all all versions in` public/snappymail/v/`
i.e.

```
ls public/snappymail/v/
2.12.2  2.13.4  2.15.1  2.17.0  2.18.0  2.18.6  2.20.2  2.22.3  2.25.1  2.26.1  2.27.3  2.29.1  2.32.0  2.35.0  2.36.1  2.37.2
2.13.1  2.14.1  2.16.1  2.17.1  2.18.1  2.19.2  2.20.6  2.22.7  2.25.3  2.26.4  2.28.1  2.29.2  2.33.0  2.35.3  2.36.3  2.37.3
2.13.2  2.15.0  2.16.3  2.17.2  2.18.2  2.19.4  2.22.2  2.24.4  2.26.0  2.27.2  2.28.4  2.31.0  2.34.2  2.36.0  2.36.4
```

`625M	public/snappymail/v/`

Is this really required? Tarball downloaded from:

https://github.com/the-djmaze/snappymail/releases/download/v{{ new_ver }}/snappymail-{{ new_ver }}.tar.gz

TIA
Alessandro

**Comment by peterkeist** [comment]
Only the latest version is required. All others can be deleted manually if you don't want to go back to an older version.
