### ISSUE TITLE
When sending attachments, SnappyMail incorrectly calculates the maximum size and returns an error.

### ISSUE THREAD

**Issue by lvarnava** [the-djmaze/snappymail#1840]
Nextcloud 27-29
Debian 12
Browser Chrome
Posfix 3.7.11
Dovecot 2.3.19
SnappyMail 2.38.2

I send 21 MB, mail server limit is 30 MB.

The result is on the screenshot.

postfix main.cf:

```
message_size_limit = 31457280
mailbox_size_limit = 0
virtual_mailbox_limit = 0
```
Nginx: client_max_body_size 5120M;
PHP:  upload_max_filesize = 5G

![Screen_shot2](https://github.com/user-attachments/assets/031c6b29-a093-4cbf-98b0-8d86818753d2)

![Screen_shot](https://github.com/user-attachments/assets/e1ae3b75-a05e-4a39-ad42-e982e789f822)

**Comment by the-djmaze** [comment]
31457280 is reported by SMTP `SIZE`, as set by your Postfix setup.

40153212 is due to the fact that attachments are converted from binary to base64.
Base64 has a 33–37% overhead and that's why your message is 40MB

**Comment by lvarnava** [comment]
I set 50 MB in postfix. It says that the limit is 30 MB.

`message_size_limit = 52428800`

Why don't other clients have this problem?

![Screen](https://github.com/user-attachments/assets/aae83fd4-7e73-40b1-8fcc-83b33fa6f96f)

Then how does it relate to global settings of Snappymail:

![screen2](https://github.com/user-attachments/assets/214eadc1-b57c-4248-bd17-53a14fe1dcff)

**Comment by lvarnava** [comment]
Thank you.
