### ISSUE TITLE
Attach nextcloud files "public" link, "internal" link don't work.

### ISSUE THREAD

**Issue by lvarnava** [the-djmaze/snappymail#1841]
Nextcloud 27-29
Debian 12
Browser Chrome
Posfix 3.7.11
Dovecot 2.3.19
SnappyMail 2.38.2

I choose, I press.
"No attachments here."

**Comment by the-djmaze** [comment]
Because it is not an attachment but a link in the html/text message

**Comment by lvarnava** [comment]
Got it. It's only added if the editor is html, but not added in plain text mode, which is not obvious to users.
Thank you.
