### ISSUE TITLE
Permissions-Policy and content_security_policy

### ISSUE THREAD

**Issue by sonnyka** [the-djmaze/snappymail#1847]
**Describe the bug**
When using Snappymail in an iFrame environment with content_security_policy set, the policy is ignored. After trying to login a "HTTP Token Error" occurs.

After some reseach I learned that "Feature-Policy" got renamed/changed to "Permissions-Policy" in the HTTP header. As in Snappymail I can only set the variable content_security_policy in the application.ini file, it seems to me that I can not correctly set the new experimental [Permissions-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy).

**Please complete the following information:**
- Browser: 131.0.6778.70
- SnappyMail Version: 2.38.2
- Mode: Docker

**Debug/logging information**
Browser Console:
Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.

application.ini Snippet:
content_security_policy = frame-ancestors 'self' https://*.mydomain.tld

mydomain.tld is depicted here only for anonymity

**Comment by the-djmaze** [comment]
I have no idea how and why, as it works on the same domain.
https://snappymail.eu/tests/iframe.html

**Comment by sonnyka** [comment]
Retried just now - it started working again. I am really confused now.
I beg your padon, maze, sorry for bothering you.

**Comment by the-djmaze** [comment]
no problem
