### ISSUE TITLE
Snappymail double encrypts encrypted drafts if edit is pressed before decrypt

### ISSUE THREAD

**Issue by BeeFox-sys** [the-djmaze/snappymail#1849]
**Describe the bug**
When viewing an encrypted draft, even if the save button is not pressed, if you press edit without decrypting it first it will show the encrypted data, which when closing the composition window will automatically save over the draft encrypting it again.

This is easily reproduceable, but sometimes causes corruption to the encrypted email which prevents decrypting. This latter part of the issue i have not been able to replicate

**To Reproduce**
1. Create an email
2. Enable pgp encryption to the sender
3. Save email as draft
5. Refresh the page to clear your encryption key password, if necessary
6. See that the draft is encrypted
7. Press the edit button without decyrpting the email
8. The draft is now encrypted twice
9. Pressing decrypt will now only decrypt the first layer, with no option to decrypt the second, so you must then manually decrypt the second layer. 

**Expected behavior**
Either the draft should automatically try to decrypt, or the composer shouldn't save a new draft and instead display a save warning, that the user can then choose to save anyway.

**Screenshots**
![Screenshot_20241121_134519](https://github.com/user-attachments/assets/ab8808da-d1e0-42a8-bdcb-5872e79ec771)
![Screenshot_20241121_134511](https://github.com/user-attachments/assets/ae2ea5e7-f5e6-4b35-997c-fd6ad5a4dce1)
![Screenshot_20241121_134545](https://github.com/user-attachments/assets/f9ba145a-f643-49fb-9814-82d22c6e8ba5)
![Screenshot_20241121_134611](https://github.com/user-attachments/assets/bf89a9f1-c71e-43bb-b8bc-db49b2feeccd)
![Screenshot_20241121_134602](https://github.com/user-attachments/assets/eb2e042d-4760-42d6-96ae-be11d71a54f1)

**Please complete the following information:**
- Browser: Firefox 132.0 
- IMAP daemon: unknown
- PHP version: 8.2.24
- SnappyMail Version: 2.38.2
- Mode: Stand Alone

**Comment by the-djmaze** [comment]
I've also done this for reply and forward message
