### ISSUE TITLE
SnappyMail doesn't work with PHP 8.4

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1850]
PHP 8.4.1 is released.

https://www.php.net/archive/2024.php#2024-11-21-4

I tried to run SnappyMail with PHP 8.4.1 under following environment.

* FreeBSD 14.1-RELEASE amd64
* Dovecot 2.3.21
* Apache HTTP server 2.4.64
* PHP 8.4.1
* SnappyMail 2.38.2

But it failed as following.

<img width="1531" alt="SnappyMail PHP8 4 20241124" src="https://github.com/user-attachments/assets/70ee7090-0fb2-4cc0-951b-89cc791e9fb6">

**Comment by freebrowser1** [comment]
Closed ?
You mean changing the files described in https://github.com/the-djmaze/snappymail/commit/cd3398db20a314d8700f25b4ec62ff87301736e1 fix the issue ?

**Comment by the-djmaze** [comment]
Yes

**Comment by yasuhirokimura** [comment]
I applied cd3398db2 to 2.38.2 and confirmed it works fine with PHP 8.4.1.
Thanks for quick fix!.

**Comment by freebrowser1** [comment]
How can I apply this ?
Because there is no release for it. I see still the release of Oct 9 (2.382) and when I download the zip in the page with code I see that all files are changed and the version is 0.0.0.

**Comment by the-djmaze** [comment]
Release will be soon. Personal live had some priorities
