### ISSUE TITLE
Your email address in commit is different to your github account

### ISSUE THREAD

**Issue by Neustradamus** [the-djmaze/snappymail#186]
@the-djmaze: Your email address in commits is different to your GitHub account, can you look your settings:
- https://github.com/settings/emails

You can look your git configuration too:
- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

It will be better, really.

Thanks in advance.

**Comment by the-djmaze** [comment]
Changed `djmaze` to `the-djmaze`

**Comment by Neustradamus** [comment]
Always same :/

**Comment by Zero3K** [comment]
Some people just want to not let strangers know their email address.

**Comment by Neustradamus** [comment]
@Zero3K: GitHub has a secure system here: https://github.com/settings/emails

- Keep my email addresses private
```
We’ll remove your public profile email and use XXXX@users.noreply.github.com when performing web-based Git operations (e.g. edits and merges) and sending email on your behalf. If you want command line Git operations to use your private email you must set your email in Git.

Commits pushed to GitHub using this email will still be associated with your account.
```

- Block command line pushes that expose my email
```
When you push to GitHub, we’ll check the most recent commit. If the author email on that commit is a private email on your GitHub account, we will block the push and warn you about exposing your private email.
```
