### ISSUE TITLE
Wrong 'From' address when replying to messages located in the 'Sent' folder

### ISSUE THREAD

**Issue by SergeyMosin** [the-djmaze/snappymail#1865]
**Describe the bug**
When replying to message located in the `Sent` folder the `From` address field in the compose popup is pre-filled with wrong email address.
Example of a message in the `Sent` folder:
```
From: my.identity@my-domain.tld
To: some.user@remote.tld
```
when replying to this message, the composer prefills this:
```
From: some.user@remote.tld
To: some.user@remote.tld
```
expected compose state:
```
From: my.identity@my-domain.tld
To: some.user@remote.tld
```

**To Reproduce**
1. Sent a message to some address
2. Navigate to the `Sent` folder
3. Select the message that was sent in Step 1
4. Click `Reply`
5. The composer `From` field will have the `To` address that was used in Step 1 instead of your identity's `From` address :bug: 

Possibly a related to https://github.com/the-djmaze/snappymail/commit/534b71e5a485688764a7af04be45032f777b8e34

**Comment by the-djmaze** [comment]
I already thought this would happen due to #1805

Although you notice it in Sent, it could be in any mailbox/folder (as you can move messages around).

An improved approach could be to check all email addresses (from, to, cc, bcc) to match an identity and, if found, use that.
