### ISSUE TITLE
Issue with Amazon shipment notification, etc. emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#187]
The Amazon shipment notification emails and others like them are not letting me click on Track package, etc. Here's a screenshot of the part of its source code that mentions the button's text:

![Screenshot_20220112-102109](https://user-images.githubusercontent.com/6194332/149168991-aed3b595-530d-4312-bb4c-0b3548199bb4.png)

**Comment by the-djmaze** [comment]
Could you:
1. View mail
2. Right click on link
3. Context menu -> inspect element
4. Screenshot the browser debug toolbar

Because source HtML is different then viewer.

**Comment by Zero3K** [comment]
![image](https://user-images.githubusercontent.com/6194332/149230330-2d2d3c14-921b-42e0-9c42-2a97bca320e9.png)

**Comment by the-djmaze** [comment]
Great!
When you look carefully someone at Amazon screwed up big time.
The `<a>` element is there and properly placed above the `<table>` element.

However, in your first image, the table is inside the A element. This is forbidden in HTML.

So someone at Amazon must fix their emails.
There's nothing we can do.

**Comment by Zero3K** [comment]
Here's the weird thing. It works properly when using https://products.conholdate.app/viewer/eml. Here's a screenshot of the browser source when inspecting the Track package button that is shown via it:

![image](https://user-images.githubusercontent.com/6194332/149243620-e5836e81-a8f3-4e27-bb4f-ee80ab2c5d45.png)

**Comment by the-djmaze** [comment]
That's because that product fixes things.

So to try and fix the screw ups of terrible HTML developers, I've made 2 changes in to core to try:
1. it tries to remove the outer `<a>` when there's one inside
2. If [tidy](https://www.php.net/tidy) is installed, use that in the hope it fixes things

**Comment by Zero3K** [comment]
I will let you know if number 1 works when a new version is released and uncled1023 upgrades to it.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.11.0

**Comment by Zero3K** [comment]
That did not fix the issue.

**Comment by the-djmaze** [comment]
Can you upload the raw .eml (with your email address replaced as @example.com)?

This allows for real debugging as i can only guess without fixing.

**Comment by Zero3K** [comment]
Here you go:

[Your Amazon.com order #112-7747555-6349053 has shipped.txt](https://github.com/the-djmaze/snappymail/files/7901081/Your.Amazon.com.order.112-7747555-6349053.has.shipped.txt)

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by the-djmaze** [comment]
I made changes for upcoming release v2.12

**Comment by the-djmaze** [comment]
Found the real bug.
In PHP there was a cleanComments() regular expression.
However, the mail contains comments inside comments and that broke it.

Thanks to the move of all PHP code to JavaScript i was able to solve this easy.
