### ISSUE TITLE
Admin => Config: changes not saved

### ISSUE THREAD

**Issue by albsch** [the-djmaze/snappymail#189]
**Describe the bug**

I'm trying to get the threading feature to work. During setup, I noticed that changing any value field in the admin panel `Config` section does nothing. 

Changing to any other panel and back to `Config` resets the values to what they were before.

I made sure that the app has write access to the `ini` file. I can confirm that, e.g., changing `Enable extensions` in the `Extensions` panel changes a value in the `ini` file instantly. Enabling/disabling plugins in the `Extensions` panel also changes the appropriate value in the `Config` panel.

**To Reproduce**

1. Setup nginx and php-fpm as per wiki, with slight modifications for the nginx config
2. Install mandatory and optional php extensions, unpack snappy mail release
3. Login to admin panel, select `Config`
4. Try to click any unchecked box, it becomes checked
5. Go to `Extensions` and back to `Config`
6. The checked box resets to be unchecked again, the `ini` file has not changed

**Expected behavior**

6. The `ini` file was changed and the box reflects the changed value

**Desktop**
 -  Firefox `96.0.1`, Chromium `97.0.4692.61` (private windows)
 - SnappyMail Version `2.11.0` (have this problem at least since `2.6.0`)

**Additional context**

PHP info:
[phpinfo.txt](https://github.com/the-djmaze/snappymail/files/7882435/phpinfo.txt)

Using default `php.ini-production` configuration.

nginx config:
[default.conf.txt](https://github.com/the-djmaze/snappymail/files/7882426/default.conf.txt)

**Comment by the-djmaze** [comment]
Correct.
Currently the `Admin => Config => application.ini` is read-only.
It is a new admin page i created, that is NOT in RainLoop.
For now it's just an easy overview what the values in application.ini are.

In future it might become interactive with a [save settings] button at the bottom.

**Comment by albsch** [comment]
Oh, that explains everything. Maybe forbidding editing the text values until it is implemented prevents confusion. For some reason I assumed that I did that a few weeks ago, i.e. that changes did persist and now it stopped working. Thanks!

**Comment by the-djmaze** [comment]
> Maybe forbidding editing the text values until it is implemented prevents confusion. 

Done ;)
