### ISSUE TITLE
Small glitch bottom right of the left pane

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#19]
**RainLoop version, browser, OS:**
SnappyMail v2.0.0-rc1
Firefox 80.0.1
Fedora 32 (Workstation Edition)

**Expected behavior and actual behavior:**
The bottom right of the left pane doesn't look as it should.
I does not matter which theme I choose.

**Steps to reproduce the problem:**
Login and look bottom left :) See screenshot below.

**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/4435930/94374916-f7e43f00-010f-11eb-8cfc-c27db529044f.png)

**Comment by ervee** [comment]
Just tested this in Windows 10 with Firefox 80 and here is shows just fine:

![image](https://user-images.githubusercontent.com/4435930/94398399-c26a4080-0165-11eb-8cc5-552f2fd81146.png)

So perhaps a problem in the Linux version of Firefox or some incompatibility in the SnappyMail code...

**Comment by the-djmaze** [comment]
SnappyMail uses the CSS resize feature to resize elements (where RainLoop uses a lot of jQuery script abracadabra for mouse-only events).

In my Firefox on Fedora i have a black corner image (KDE with dark theme, but Firefox uses Gnome/GTK so i have a breeze-dark that merges with KDE theme).
So yes, that corner image is from the OS-UI itself.

So NO: i can't change the size and shape of that control (even not with overlays).

**Comment by ervee** [comment]
Okay. I just checked in my other RainLoop-latest install and there no corner image at all:

![image](https://user-images.githubusercontent.com/4435930/94426465-e6da1300-018d-11eb-8478-fdb56b5f2946.png)

Perhaps you can make the corner invisible via CSS I don't know. If it is unfixable then so be it. It is just a minor GUI issue.

**Comment by the-djmaze** [comment]
Correct, RainLoop doesn't use the CSS resize property.
I can remove that property and use JavaScript, but then we need more JavaScript then just a single CSS line.
However, both are in the code now so one can be removed.

**Comment by derStephan** [comment]
>I can remove that property and use JavaScript, but then we need more JavaScript then just a single CSS line.

You should stick to the CSS solution. Less complexity means less problems.

**Comment by ervee** [comment]
Let's just close this. Functionality is not affected and it only shows a small UI error in some OS/Browser combo's.
