### ISSUE TITLE
Docker-compose: completely borked.

### ISSUE THREAD

**Issue by ikidd** [the-djmaze/snappymail#192]
git cloned the repo and tried to build and bring up. So far here are my stumbling blocks.

1. Submitted [PR](https://github.com/the-djmaze/snappymail/pull/191) to fix php:7.4fpm build issue because it fails on "configure: error: unrecognized options: --with-freetype-dir, --with-jpeg-dir"

2.  When executing `docker-compose up -d` the db and php containers start and stay running, nginx stops with a message about the missing ssl certs.

Shelling into the nginx container using 

`# docker-compose run nginx sh`

and execute

`# sh /var/www/.docker/dev/nginx/ssl.sh` 

builds the certs and allows you to start.  I'm guessing there should be something in docker-entrypoint.sh to check for their existence and run this if necessary.

3. get chown error when opening website:

shell into nginx container again and run the chmod and chown commands against /var/www (not /var/www/webmail as in the instructions, presumably given how the volume attachment in docker-compose.yml is given without the webmail folder).

4. now have errors that reference files in /var/www/snappymail/v/0.0.0/static where there is no static folder that exists in there.

So that's where I'm stumped since as far as I can see, this is not usable as it sits.

**Comment by albsch** [comment]
[This](https://github.com/albsch/snappymail-docker) is my current setup which I use behind a reverse proxy (`nginx` + `certgen`). Maybe it will help you to fix things.
It works with the latest `nginx` container and `php 8`.

**Comment by ikidd** [comment]
Thank you, that works like well.  Had to change the compose version to 3.5 and apply the permissions fixes to the app folder, but then it worked like a charm.

What's the implication of using the UID+GID env variable that you have in your `docker-compose up` command?

**Comment by albsch** [comment]
It's to set the correct user for the `docker-compose.yml` file without needing to fix the permissions manually in the app folder.

**Comment by ikidd** [comment]
Didn't seem to work, as I had to do that manually before it would go to the login page.

But all good, it's working fine.  Thank you.
