### ISSUE TITLE
Search all folders

### ISSUE THREAD

**Issue by necrevistonnezr** [the-djmaze/snappymail#196]
Sorry if I’m doing this wrong but I saw https://github.com/the-djmaze/snappymail/issues/154 - is this on your roadmap - either searching multiple folders or a virtual „all“ folder?

**Comment by the-djmaze** [comment]
The virtual folder must be configured in Dovecot and not through SnappyMail.
The other is implemented and hopefully works when mailserver supports it.

There is no other option as searching in multiple folders through php requires many calls to imap server and then results must be combined.
Maybe in a future version with caching it might be done.

**Comment by gramakri** [comment]
@the-djmaze We have implemented the virtual all mails folder on Cloudron side . But the search input box does not search email body by default. One has to put in `text=search this` . Is it possible to also search BODY by default?

**Comment by jdaviescoates** [comment]
> Is it possible to also search BODY by default?

Yes please!
