### ISSUE TITLE
UI Issue With "Marking as Read"

### ISSUE THREAD

**Issue by mitchellurgero** [the-djmaze/snappymail#197]
**Describe the bug**
UI claims I cannot Mark folder as read - but it allows me to anyway (option greyed out, do not enter sign for mouse on hover)

**To Reproduce**
1. Login
2. Select folder
3. Try to use the greyed out "Mark folder as read" option

**Expected behavior**
NOT mark folder as read since option is greyed out.

**Screenshots**
![image](https://user-images.githubusercontent.com/4168998/151293318-cb4bd0f1-0ea3-49ca-b45b-8328397b6274.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chromium 89, firefox 86, safari 14]
 - SnappyMail Version [e.g. 2.3.4]

**Additional context**
This _might_ be specific to Cloudron, if so, link to bug report on the [Cloudron Forums here](https://forum.cloudron.io/topic/6396/ui-issue)

**Comment by the-djmaze** [comment]
I confirm this bug is in the javascript code.

Will solve it later as i'm busy with issue 89 regarding PGP
