### ISSUE TITLE
[Feature Request] Unified Inbox for Multiple Accounts

### ISSUE THREAD

**Issue by tomershvueli** [the-djmaze/snappymail#199]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
After having added multiple accounts, it'd be great if there a single unified inbox view which combines all accounts together. 

**Describe alternatives you've considered**
Don't think there exists an alternative within SnappyMail. Would have to look elsewhere unfortunately. 

**Additional context**
None. Just wondering if this is possible with the current architecture and something that is in the roadmap.

**Comment by the-djmaze** [comment]
Combining multiple IMAP accounts requires several things:

1. fetch mail list needs to be executed for each account.
2. searching needs to be executed for each account.
3. results must be merged in the correct sort order (data/size/subject/from ascending/descending)

Depending on remote servers speed this could take 1 second to minutes (gmail/outlook imap not that fast).

And then there is a major IMAP capability issue: some IMAP servers don't allow sorting.

Why? SnappyMail doesn't store e-mails locally, it is all directly fetched from IMAP servers.

So if you really require this feature, you should look elsewhere (RoundCube maybe as it does use local storage?).

Or as alternative, you could use Fetchmail.
This is already requested at https://github.com/the-djmaze/snappymail/issues/194

**Comment by MarkWieczorek** [comment]
I really would like to see a unified inbox as well with Snappymail. This is a common feature of all modern email clients.

**Comment by skug67** [comment]
I have a related but much simpler feature request.  Dovecot creates the ability to create virtual folders that can in fact combine multiple accounts.  Is there some way to create a user-configurable option which causes Snappymail to open in that folder by default?
