### ISSUE TITLE
seing double with Snappymail v2.11.0 

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#200]
Hello,

I started using snappymail v2.11.0  and I am quite satisfied with it, as replacement of rainloop.

There is something strange, some mails get their content printed on screen twice.

**Here is the source content as shown in ?/Raw/&q[]=/0/ViewAsPlain/&**

X-Sieve-Mark: Sysadmin
X-Mx: moe
Return-Path: <root@moe.XXX.XX>
Delivered-To: ZZZ@XXX.XX
Received: from Debian-exim by mx1.XXX.XX with spamslayed-spamd (Exim 4.94.2)
	(envelope-from <root@moe.XXX.XX>)
	id 1nDt3X-0008Ng-0R
	for ZZZ@XXX.XX; Sat, 29 Jan 2022 20:06:40 +0100
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on mx.XXX.XX
X-Spam-Level: 
X-Spam-Status: No, score=-0.1 required=3.4 tests=BAYES_00,MISSING_SUBJECT,
	NO_RELAYS,T_SCC_BODY_TEXT_LINE autolearn=no autolearn_force=no
	version=3.4.6
Received: from Debian-exim by mx1.XXX.XX with spamslayed-bogofilter (Exim 4.94.2)
	(envelope-from <root@moe.XXX.XX>)
	id 1nDt3W-0008NW-P1
	for ZZZ@XXX.XX; Sat, 29 Jan 2022 20:06:38 +0100
To: root@XXX.XX
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit
Message-Id: <E1nDt3V-0002zj-IC@moe.XXX.XXi>
From: root <root@moe.XXX.XX>
Date: Sat, 29 Jan 2022 20:06:37 +0100
X-Bogosity: Ham, tests=bogofilter, spamicity=0.002464, version=1.2.5

[banstring]

enabled	= true
filter  = saslroot
port    = all
maxretry = 1
logpath = /servus/mx/rootfs/var/log/exim4/mainlog
	  /servus/mx/rootfs/var/log/exim4/rejectlog

**On screen:**
![image](https://user-images.githubusercontent.com/1160681/151674499-44f2c8f5-7e47-4c1c-b026-e1a0a7a0c630.png)

If I reply, it is still doubled.

It does not happen with all the mails but I was not able to identify any specific differences between the case it occurs and the one it does not.
No error in logs.
No plugins.

**Comment by Zero3K** [comment]
Its already been fixed. Please wait for v2.12.0.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/issues/190
