### ISSUE TITLE
ability to easily change From: email address without creating an extra identity

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#202]
Hello,

Thunderbird allow to edit the From field completely, in addition to switch from one identity to another.
It is especially convenient when you use antispam/filtering aliases like thisuser+thistopic@domain, when you reply with an address you almost never use.

I understand some admins might not want to provide users this kind of freedom. But, using the identities as they are implemented, you can already send mail with any address, so it would not change anything at this point.

It would be a nice plus. 

Regards,

**Comment by yeupou** [comment]
Hi, 

I noticed the changelog "Ability to easily change From: email address without creating an extra identity", thanks!
However, I do not see how to actually change the From. How does it work?

**Comment by the-djmaze** [comment]
1. https://snappymail.eu/demo/
2. Compose new message
3. You are free to type in the "From" field

And on the right there is the ▼ so you can still choose an identity.

**Comment by yeupou** [comment]
It's perfect. 

However it is not live on my 2.12.2 instances. Is there a configuration parameter to allow it? I thought it was included in 2.12.2 (as in the changelog it was mentioned "Ability to easily change From: email address without creating an extra identity") but maybe it is for the next release.

**Comment by the-djmaze** [comment]
It's in 202. Maybe you have the wrong template files?

**Comment by yeupou** [comment]
My bad, I was actually running the 2.12.0 on this server!
