### ISSUE TITLE
v2.11.0: default identity ignored when replying, if no identity match the To:

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#203]
Default identity is ignored when replying, if no identity match the To: of the mail being replied to

**To Reproduce**
- Have an account name like thisname@domain and an extra identity mainaddress@domain set as default
- Receive a mail sent to another address than the two configured, for instance mainaddress+thisextrastring@domain
- Reply, the sender will be set to thisname@domain and not the default mainaddress@domain, while failing to find related identity.

There was no such problem on rainloop so something must have changed

Regards

**Comment by the-djmaze** [comment]
What you actually want is that SnappyMail has an option to handle the [postfix recipient_delimiter](https://www.postfix.org/postconf.5.html#recipient_delimiter).

This could be addressed at the same time when #202 gets implemented

**Comment by yeupou** [comment]
Hi,

I think my original post is confusing.
My issue here is really that:
  - I have thisaddress@domain set as default
  - it is not the accountname@domain used to log in
  - when replying to a message sent to anotheraddress@domain, it is accountname@domain instead of thisaddress@domain used to reply; the default setting is ignored

**Comment by the-djmaze** [comment]
So:
1. login with accountname@domain
2. open message that has `To: anotheraddress@domain`
3. click reply
4. `anotheraddress@domain` has no identity, system should choose "default" not `accountname@domain`

Is that correct?

**Comment by yeupou** [comment]
Exactly.
