### ISSUE TITLE
Fixing \/ in the subject of an email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#204]
It would be nice if it could fix \/ in email subjects by removing the \. So that way "and\/or" becomes "and\or".

**Comment by the-djmaze** [comment]
I really have no idea what you mean.

**Comment by the-djmaze** [comment]
Can you:
1. view source
2. Find: `Subject:`
3. Post result here

**Comment by Zero3K** [comment]
Subject: You received an answer to your question, "Does it support a
 blocklist and\/or allowlist?"

Okay. What about the other Amazon issue?

**Comment by Zero3K** [comment]
Heh, It gets fixed by Github.

**Comment by Zero3K** [comment]
I don't think Customer Service will help get it fixed.

**Comment by the-djmaze** [comment]
> I don't think Customer Service will help get it fixed.

Hey we can move mountains, but it's not allowed to hack Amazon and fix their $#%$#% 😉

**Comment by Zero3K** [comment]
Well, maybe they will. The guy told me he will get it rectified.
