### ISSUE TITLE
Problems with git master not working 

### ISSUE THREAD

**Issue by gene-git** [the-djmaze/snappymail#208]
Couple items:

1) During build of package on linux I get a warning:
warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

Is this a linux or  MacOS only thing?

2) When trying to use snappymail,  the login screen shows spinner and never presents the login / password form.
The log shows:

"PHP message: PHP Warning:  is_executable(): open_basedir restriction in effect. File(/sw/bin/gpg) is not within the allowed path(s): ...
Which is true - /sw doesn't exist. Not even /usr/bin is allowed in open_basedir.

Suggestions how to make this work again?

thanks much!

**Comment by gene-git** [comment]
If it's a pain to sort out, Id be fine with a way to turn off openpgp completely as well. Thanks!

**Comment by gene-git** [comment]
Thank you.

Now error log is quiet and I  get login form but after logging in I get only the background with nothing else on screen. No index no buttons just the gray bubble background.
Thoughts?

The access log last 4 entries are :
...

.. "GET /xxx/snappymail/v/2.11.0/static/css/fonts/snappymail.woff2 HTTP/2.0" ...
.. "POST /xxx/?/Json/&q[]=/0/ HTTP/2.0" 200 3001 "-" ...
.. "GET /xxx/?/Css/0/User/-/Default/-/[hashthinghere]/Hash/-/Json/ HTTP/2.0" ...
.. "POST /xxx/?/Json/&q[]=/0/ HTTP/2.0" 200 ...

**Comment by the-djmaze** [comment]
Now the login fails (One of the post commands).

I have no open_basedir so that i can test all GPG calls.

Maybe something is shown in the browser debugger?

**Comment by gene-git** [comment]
browser shows 
can't access property "flowId", this.activeSection is undefined 9 [FormAutofillContent.jsm:906](resource://autofill/FormAutofillContent.jsm)
    onPopupOpened resource://autofill/FormAutofillContent.jsm:906
    popupStateChanged resource://autofill/FormAutofillChild.jsm:85
    notifyListeners resource://gre/actors/AutoCompleteChild.jsm:92
    receiveMessage resource://gre/actors/AutoCompleteChild.jsm:68

May or may not help you.

**Comment by the-djmaze** [comment]
That's not SnappyMail code, you should see something like this in Firefox:

![afbeelding](https://user-images.githubusercontent.com/3752035/152441540-15658a60-15a9-4253-9a19-ebef2772697b.png)

**Comment by gene-git** [comment]
nothing looks helpful in console - i filtered on snappymail - 
Erros none
Warnings none
Logs none
Info None
Debug None
CSS None
XHR Non

only one showing anything is the 'Requests' tab which has  just things like:
GET /xxx/snappymail/v/2.11.0/themes/Default/images/background.jpg
which works (200)

Above that I see
xxx/snappymail/v/2.11.0/static/js/min/app.min.js
and request headers showing: 

content-security-policy | default-src  'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src  'self' 'unsafe-inline'; img-src 'self'; media-src 'self'; font-src  'self' ; frame-src 'self'; connect-src 'self'; frame-ancestors 'self';  base-uri 'self'; form-action 'self'; object-src 'none'

**Comment by gene-git** [comment]
I may be missing something but best I can tell the imap server is not getting anything at all after i click login - nothing seems to be sent out to imap server.

**Comment by gene-git** [comment]
With commit 384230f7bf250b3968291494a011724e3f194482
I no longer get login form again - just the b/g image and the 3 dot animation again.
php 8.1.2
nginx-mainline web server

thanks

**Comment by the-djmaze** [comment]
Do you use `use_app_debug_js = On` in application.ini?

**Comment by gene-git** [comment]
I don't use docker and i don't see that file in my install package.  I use the release.php script to build.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by gene-git** [comment]
Thanks and sorry I missed that.
This is going to sound odd but here's what happens.

Turning on use_app_debug_js = On and now I can login and everything works as normal.
When I turn this back off and try logging in then I get same b/g only problem!

To confirm - I changed it back to On again and sure enough everything works again.

Hope that makes some sense to you.

**Comment by the-djmaze** [comment]
Yes that makes sense. Clear the cache at `…/data/_data_/_default_/cache` and try again

**Comment by gene-git** [comment]
I use release.php and it generates 2.11.0 for git master (not 0,0.0).
I cleared cache and turned off app_debug_js and as you predicted it works fine.
I can make the package clear the old cache at install time for git master - is there a better way you think?
thanks!

**Comment by the-djmaze** [comment]
Don't use master, use a release tag checkout unless you want buggy developmnet code.

**Comment by gene-git** [comment]
Thanks I  do - i was also in habit of testing git master but happy to skip that part  :)
Thanks for all work you do - its very much appreciated.
