### ISSUE TITLE
APP_DATA_FOLDER_PATH defined inside _include.php seems not have effect

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#214]
**Describe the bug**
inside _include.php you can set
APP_DATA_FOLDER_PATH in several way, but seems not have effect
snappymail that still use default [root]/data path (and re-create it if not present )

**To Reproduce**
1. set absolute path using APP_DATA_FOLDER_PATH in _include.ph
2. move current "data" from [root]/data to another path defined above
3. snappymail create [root]/data and ignore APP_DATA_FOLDER_PATH 

**Expected behavior**
snappymail use data defined in APP_DATA_FOLDER_PATH 

Alessandro

**Comment by the-djmaze** [comment]
Rename to `include.php`

**Comment by lota** [comment]
I renamed file to include.php (as described), but problem still remain on my system.
I also tried remove ./data/_data_/_default_/cache/*

Alessandro

**Comment by the-djmaze** [comment]
It should, as i have no issues whatsoever on the demo website.

Does your custom data folder exists?
