### ISSUE TITLE
Options not showed on Advanced Search modal windows field Date 

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#216]
**Describe the bug**
In advanced Search modal windows, options of Date filed not showed (probably not match translation), I tested English and Italian

**To Reproduce**
1. Login in webmail as user
2. Open advanced search

**Screenshots**
![label_search](https://user-images.githubusercontent.com/956392/152690037-b9c741ff-f262-45ef-8b8c-07be64f119c3.png)

HTH
Alessandro

**Comment by the-djmaze** [comment]
Already fixed for next release
https://github.com/the-djmaze/snappymail/commit/7de00cd05c7ac128760abc494c0d57c20366d6c5
