### ISSUE TITLE
Shortcut/Help screen doesn't appear 

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#22]
**SnappyMail version, browser, OS:**
SnappyMail v2.0.0-rc1
Firefox 80.0.1 on Fedora 32 (Workstation Edition)
Firefox 81.0 on Windows 10 build 2004

**Expected behaviour and actual behaviour:**
When typing the question mark ? (SHIFT-/), the shortcut/help screen should pop-up, but it doesn't.

**Steps to reproduce the problem:**
Login and press ? (SHIFT-/)

**Screenshot from RainLoop:**
![image](https://user-images.githubusercontent.com/4435930/95123561-72394280-0752-11eb-9db0-4c628497eb83.png)

**Comment by the-djmaze** [comment]
Although i'm a huge Linux user, i do use a Microsoft Natural Ergonomic Keyboard 4000.
It has an F-lock facility where the F keys are for mail handling with key codes like: Help, Undo, Redo, New, Open, MailSend, MailReply, MailSend and Save.
Thanks to the new shortcuts handler that uses the new KeyboardEvent.key  we actually use these :)

Based on your report i made changes and enhancements that differ from RainLoop:
* **Replaced [?]/[Shift + /] for [F1] and [Help] key**
* [Undo] in Squire HTML Editor
* [Redo] in Squire HTML Editor
* [New] opens compose new mail window
* [Open] opens mail full-screen
* [Close] close/minimize mail (full-screen)
* [Shift] + [Close] close/cancel new mail
* [Reply] Replay
* [Shift]+[Reply] Replay all
* [Fwd] Forward
* [Shift] + [Fwd] Forward as attachment(s)
* [Send] sends the compose mail
* [Save] saves the compose mail

When tested you will see a close of this issue

**Comment by the-djmaze** [comment]
Because the '`' backtick shortcut (open a menu) is broken as well.

I had to change other things: https://github.com/the-djmaze/snappymail/commit/4177467f81428aff5afe70d86836f40e313fd14c

This means that:
* [M] is now "open menu"
* [M] can't be "move message". [Insert] it is (like: insert into folder)
* [Insert] does not work anymore in the messages list (this was weird anyway)

I've also reported it to RainLoop that the shortcuts are bad.
https://github.com/RainLoop/rainloop-webmail/issues/2035

**Comment by ervee** [comment]
Okay the F1 key works. I don't have such keyboard so I can't test all the hotkeys :)
The ``` ` ``` is indeed not working and the change to ```M``` is not in rc2 so I can't test that.

**Comment by the-djmaze** [comment]
I've added https://snappymail.eu/demo/ so you can test.

**Comment by ervee** [comment]
Nice! When I use '''M''' the menu oens but I can't navigate it with the arrow keys :)

**Comment by the-djmaze** [comment]
> but I can't navigate it with the arrow keys :)

I think i didn't implement that feature.
Probably because tab/shift+tab should work.
Will check it.
