### ISSUE TITLE
Apache2 virtual host

### ISSUE THREAD

**Issue by eibex** [the-djmaze/snappymail#220]
Hello,

I have been trying to run snappymail on an Ubuntu 20.04 system running Apache2 and PHP7.4-fpm. 

I can see from the virtual host in the installation page of the wiki that the macro created listens on port 2096 and the installation directory is inside "snappymail" user directory. 

I tried following it (also tried to change ports and document root) but I was always met with errors. 

I am familiar with NGINX, but I am forced to use Apache2 on this server (Apache2 is bound to port 80 and 443, I cannot put NGINX in front of it). 

Is there any chance you could release an apache vhost similar to the NGINX one that adheres to the instructions that precede it? (`/var/www/webmail` document root etc.)

**Comment by the-djmaze** [comment]
The Apache example is a very advanced to accomodate shared hosting.
And uses port 2096 if you want to replace cPanel setups (as they became very expensive).

You just need to pick the parts you need and remove others.
Then replace strings to accomodate your setup as each setup differs.

For example php-fpm alone can be configured in many ways, so you need the right user/group name and the Apache user needs access permissions to the php socket.

Let alone the security layers of each specific distro.

You really need to dive in or let an expert configure it for you.

**Comment by eibex** [comment]
Thank you, I managed in the end.

Had to comment out the proxypass lines.
