### ISSUE TITLE
Activate fail2ban also for the admin page. No log are generated if login fail on the snappymail admin page

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#227]
**Is your feature request related to a problem? Please describe.**

I don't know if it's only me but, after activating logs for wrong credentials I see this works for UI email access:
the log file is created and after xx number of wrong fail, fail2ban will ban the IP.

Seems the admin page of snappymail is not protected: on wrong admin login there is no log written so there is no fail2ban protection.

**Describe the solution you'd like**

Have a error log generated also for the admin page for wrong attempts to login so fail2ban should work also on this page (I have to test) if many try to login are done.

**Comment by the-djmaze** [comment]
This should work as
`Admin Auth failed: ip={request:ip} user={username}`

You must have `auth_logging = On` in application.ini

**Comment by PeopleInside** [comment]
It works
