### ISSUE TITLE
Bug with files attachment

### ISSUE THREAD

**Issue by lamphankhoi** [the-djmaze/snappymail#228]
**Describe the bug**
There will be some mails received with files, they will show no files. This error occurs with the version 2.12.0. With the version 2.10.3, the mail with the attachments will be displayed correctly. I did check that symptom with rainloop 1.16 there is no such error with that. This error happened mostly with forwarded mails in the version 2.12.0

**Expected behavior**
The mail with the attachments should be displayed correctly.

**Screenshots**
Errors with 2.12.0
![image](https://user-images.githubusercontent.com/80112759/153712925-c258e133-e21e-4d89-8bfc-663548fef843.png)

No error with 2.10.3

![image](https://user-images.githubusercontent.com/80112759/153712834-75f0b198-deb3-4bac-95eb-6b98fed7f837.png)

**Comment by the-djmaze** [comment]
Can you view source of the mail.
Remove email adresses and other personal data.
Then upload the source here as .eml so i can investigate the issue?

Problem is that i can' reproduce the issue and need to know the MIME structure and application which forwarded the message.

**Comment by lamphankhoi** [comment]
I tried uploading .eml file but github is not allowed that extension. So I saved it under .txt files. Please rename the files according to your need.
[2.10.3.txt](https://github.com/the-djmaze/snappymail/files/8054641/2.10.3.txt)
[2.12.0.txt](https://github.com/the-djmaze/snappymail/files/8054643/2.12.0.txt)

**Comment by the-djmaze** [comment]
I've updated your comment with the MIME structure of the files you uploaded.
I shall investigate this structure.

**Comment by m-i-k-e-y** [comment]
I'm facing the same issue. If you need more samples, please let me know.

**Comment by the-djmaze** [comment]
Solved. Issue was text/plain not toggle hasAttachments and text/html does.
Missed it while building the pgp decrypt to find attachmentd

**Comment by m-i-k-e-y** [comment]
Just installed release 2.12.1, and the issue is just partially resolved for me. I still have some emails (dmarc report from google for example) which do not show the attachment. These mails do not have any message body, just the attachment. The Content-* Headers look like this in these mails : 

[google_dmarc_report_content_headers.txt](https://github.com/the-djmaze/snappymail/files/8062607/google_dmarc_report_content_headers.txt)

If needed, I could provide the source of such an email.

**Comment by the-djmaze** [comment]
> If needed, I could provide the source of such an email.

I've got plenty :)
And fixed it.

**Comment by m-i-k-e-y** [comment]
Thanks a lot, working now in v2.12.2!
