### ISSUE TITLE
Discord notification mails not displayed correctly in v2.12.0

### ISSUE THREAD

**Issue by m-i-k-e-y** [the-djmaze/snappymail#230]
**Describe the bug**
Discord notification mails are not being displayed properly in v2.12.0. Only images are displayed, but not text:

![v_2 12 0_discord_not_working](https://user-images.githubusercontent.com/29158512/153751621-4eef32af-ae7f-4490-a82b-153574575cde.png)

**To Reproduce**
1. select a notification mail from Discord

**Expected behavior**
The text of the notification should be visible (this is the same notification viewed on an instance running v2.10.2):

![v_2 10 2_discord_working](https://user-images.githubusercontent.com/29158512/153751703-e9dca0fb-d162-482b-9c83-e66344ac204d.png)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Firefox 97 64bit on Windows 10
 - Firefox 96 64bit on Ubuntu 20.04
 - SnappyMail Version 2.12.0

**Additional context**
If you need the source of the mail, let me know.

**Comment by m-i-k-e-y** [comment]
Tried it both ways - with the setting on (to remove colors) and off - there is no difference.

**Comment by the-djmaze** [comment]
Ok, can you post the source of the text/html part do i can have a look?

**Comment by m-i-k-e-y** [comment]
Here you go (I've redacted some personal informations):

[discord_notification_mail.txt](https://github.com/the-djmaze/snappymail/files/8058144/discord_notification_mail.txt)

**Comment by m-i-k-e-y** [comment]
Thanks for the quick fix, this is resolved in the release v2.12.1.
