### ISSUE TITLE
gpg.php throwing warnings in v.2.12.0

### ISSUE THREAD

**Issue by m-i-k-e-y** [the-djmaze/snappymail#231]
**Describe the bug**
I randomly see the following warning in the error logfile of nginx:

> 2022/02/13 13:04:07 [error] 643547#643547: *14945 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): File exists in /var/www/snappymail/snappymail/v/2.12.0/app/libraries/snappymail/pgp/gpg.php on line 90" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"

Since the file/directory already exists, it does not seem to be a real problem. It just pops up in the logfile every now and then.

**To Reproduce**
Not sure, haven't been able to pinpoint, what action triggers the message.

**Expected behavior**
The warning should not occur.

**Desktop (please complete the following information):**
 - Browser Firefox 97 64bit on Windows 10
 - Browser Firefox 96 64bit on Ubuntu 20.04
 - SnappyMail Version 2.12.0 on Debian 11 Bullseye

**Comment by the-djmaze** [comment]
Could be because of missing`clearstatcache`
Will look for a solution with php filesystem caching.

**Comment by m-i-k-e-y** [comment]
Unfortunately, this is not resolved, still happening in release 2.12.1:

> 2022/02/14 17:51:57 [error] 1226318#1226318: *412 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): File exists in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/snappymail/pgp/gpg.php on line 91" while reading response header from upstream, client: [redacted], server: [redacted], request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"

**Comment by the-djmaze** [comment]
Oh maybe it is a link.
Can you change the line in
```if ($homedir && !(\is_dir($homedir) || \is_link($homedir)) && !\mkdir($homedir, 0700, true)) {
```

Maybe that solves it?

**Comment by m-i-k-e-y** [comment]
Changed the line and so far, the warning did not show up anymore. 

Thanks @the-djmaze!
