### ISSUE TITLE
Cannot use `custom-login-mapping` and `override-smtp-credentials` at the same time

### ISSUE THREAD

**Issue by mwt** [the-djmaze/snappymail#233]
**Describe the bug**
If you enable the `custom-login-mapping` and `override-smtp-credentials` plugins at the same time for the same user, then only `custom-login-mapping` will apply. That is, the client will attempt to login to the SMTP server defined under "Domains" with the username set in `custom-login-mapping`. All settings from `override-smtp-credentials` are ignored.

My use case for enabling both is that you have separate passwords for IMAP and SMTP because the two are on different servers. It is not always possible to set the two passwords to be the same (eg. app passwords with 2fa).

**To Reproduce**
1. Install and enable both plugins and configure them such that both apply to the same user.
2. Login to the user account that both apply to.
3. Attempt to send an email.
4. See error: "Authentication Failed".

**Expected behavior**
When both plugins are enabled on the same user, `custom-login-mapping` applies to IMAP only and `override-smtp-credentials` applies to SMTP only.

**Desktop (please complete the following information):**
 - Browser Firefox 97.0
 - SnappyMail Version tested on 2.12 and 2.12.1

**Comment by the-djmaze** [comment]
Correct, there is no `priority` rule to execute extensions in certain order.

Either merge both into a single extension or let me create a execution order system?

**Comment by mwt** [comment]
That makes sense. Maybe the best move would be to enhance `custom-login-mapping` with the ability to specify different usernames for IMAP/SMTP and provide an optional SMTP password.

**Comment by the-djmaze** [comment]
Added a new plugin named "Login Override" for next v2.25.2
It has two mapping options: IMAP and SMTP

Each line in the field will be like `user@example.com:user1:password1`
* `user@example.com` the currently used email address to login with
* `user1` when set it will be used for IMAP or SMTP login
* `password1` when set it will be used for IMAP or SMTP login

`user@example.com::password1` will used the default login name
`user@example.com:user1:` will used the default login password
