### ISSUE TITLE
some mails with html content yield Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php

### ISSUE THREAD

**Issue by m-i-k-e-y** [the-djmaze/snappymail#234]
**Describe the bug**
Some mails with html content, not all, yield the following PHP notice in the error log of nginx:

> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS93dXRzY2hlcl8xMV8yMDIxL3d1dHNjaGVyX2xvZ28ucG5n HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9hcGkud3V0c2NoZXIuY29tL21lZGlhLzdkLzIxLzU4LzE2Mzg3ODA4NzQvYThjNmRkOTgyMDEwZmNlODcwMWNlMWFlZjhhMmQ0MGEuanBn HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9hcGkud3V0c2NoZXIuY29tL21lZGlhLzJkLzRlLzZhLzE2MzI0MzA3MzEvM2RjNDg3NmYzZjA4MjAxYzdjNzZjYjcxZmExZGE0MzkuanBn HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS9tZF8yOTExNC5qcGc HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9hcGkud3V0c2NoZXIuY29tL21lZGlhL2Y3LzNmLzA1LzE2Mzg3ODA5MzkvMjExOGQ4YTFiNzAwNGVkNWJhZjUzNDdhNGY5OWY1MDIuanBn HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9hcGkud3V0c2NoZXIuY29tL21lZGlhLzMxL2UyLzFlLzE2MzI0MzA4MjYvMTliYzkxNjEwOGZjNjkzOGY1MmNiOTZmN2UwODc5NDEuanBn HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS9tZF8zMDg5Ny5qcGc HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS9tZF8yMzEwMi5qcGc HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS93dXRzY2hlcl8xMV8yMDIxL3NvY2lhbC1mYi5qcGc HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS93dXRzY2hlcl8xMV8yMDIxL3NvY2lhbC1pbnN0YS5qcGc HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9jdXN0bG9hZHMvMTAwNTM1MzA3OS93dXRzY2hlcl8xMV8yMDIxL3NvY2lhbC15b3V0dWJlLmpwZw HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"
> 2022/02/15 06:23:15 [error] 1226318#1226318: *985 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: sContentType in /var/www/snappymail/snappymail/v/2.12.1/app/libraries/RainLoop/ServiceActions.php on line 360" while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /?/ProxyExternal/aHR0cHM6Ly9saW5rLnNlaGVuLnd1dHNjaGVyLmNvbS9tby9iRlJtZk81Z2t2XzEwMDUzNTMwNzlfMzYwMjBfMjM3NDhfMzE5NzguZ2lm HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "[redacted]"

These are from viewing the following newsletter: 

[newsletter.txt](https://github.com/the-djmaze/snappymail/files/8066124/newsletter.txt)

Additionally, these mails are not displayed correctly, some parts are not displayed at all (some pictures) and some parts seem to be misaligned (but that might be caused by the missing elements).

This is the online version of above newsletter: [online version](https://link.sehen.wutscher.com/u/gm.php?prm=bFRmfO5gkv_1005353079_36020_23748&_esuh=_11_695fe4a015571b0c75159fc0a0c5ada635c4f604c9dc96dc4cfddee340786f66)

Interestingly enough, the notices only show up the first time I view such a mail. If I swithc to another mail, and switch back, the notices are not logged again. Guess some sort of caching is in place.

**To Reproduce**
1. select a mail with html content
2. see/check for error in webserver logfile

**Expected behavior**
No error should be logged and mail should be displayed correctly.

**Desktop (please complete the following information):**
 - Firefox 97 64bit on Windows 10
 - SnappyMail Version 2.12.1
 - nginx 1.18.0-6.1 on Debian Bullseye
 - php.fpm 7.4.25-1+deb11u1 on Debian Bullseye

**Comment by m-i-k-e-y** [comment]
Thanks, that was quick.

I applied your fix, the messages no longer appear in the logfile, however the missing images in this sample mail are s till not being displayed. I cleared the cache in the browser, cleared the cache directory of snappymail on the server (data/_data_/_default_/cache)  and restarted nginx. Is there anything else I need to reset/clear?

**Comment by the-djmaze** [comment]
I get a 404 on some images, so it seems the mail is broken

**Comment by m-i-k-e-y** [comment]
That's strange. Just tried the webversion of googlemail, the app Bluemail on Android and Thunderbird on Windows and Linux - all of them display the missing images (the ones missing compared to the online version of the newsletter).

**Comment by the-djmaze** [comment]
This is what i get:
![afbeelding](https://user-images.githubusercontent.com/3752035/154040090-902ddefd-9d64-48c9-b11f-edb2162d8d0a.png)

There's a trick in the browser debugger to investigate the proxy.
When you click an item you will find in the response headers `x-content-location` that contains the original URL the proxy is requesting.

And then when i follow that location in browser, it does indeed succeed.
Investigating this approach and proxy reveals that the proxy never follows redirects.
So i've modified this to allow a maximum of 2 location redirects.

**Comment by m-i-k-e-y** [comment]
Thanks, looks better now with v2.12.2. The alignment is ok.

I'm not getting 404 errors and the browser seems to load the images, but they are not visible:

![grafik](https://user-images.githubusercontent.com/29158512/154065039-c71e0db0-c0b6-44ca-a5c5-60e755defb1d.png)

This sun glass should be displayed to the left of the text Emporio Armani.

Don't get me wrong, I appreciate your hard work. I'm just trying to understand what's happening.

**Comment by the-djmaze** [comment]
> This sun glass should be displayed to the left of the text Emporio Armani.

Just found out and solved it for next release
