### ISSUE TITLE
Wiki/docs upgrade instruction

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#235]
I suppose are simple, but can you add upgrade instruction?
ie. upgrade from to v2.11.0 to v2.12.2

seems is not enough upload code inside:
snappymail/v/ directory?

TIA
Alessandro

**Comment by Massedil** [comment]
Something like this works for me :

```
unzip -o $SNAPPYMAIL_ZIP -d $SNAPPYMAIL_DIR
rm $SNAPPYMAIL_ZIP
find $SNAPPYMAIL_DIR -type d -exec chmod 755 {} \;
find $SNAPPYMAIL_DIR -type f -exec chmod 644 {} \;
chown -R $SNAPPYMAIL_USER:$SNAPPYMAIL_USER $SNAPPYMAIL_DIR
```

I hope it helps you.

**Comment by the-djmaze** [comment]
> seems is not enough upload code inside: snappymail/v/ directory?

Correct, you forgot the root index.php that includes the version id

**Comment by lota** [comment]
Ok, done, all seems works.

My approach is:

* load inside snappymail/v/ new version (i.e. snappymail/v/2.12.2)
* change APP_VERSION in main index.php

preserve include.php README.md serviceworker.js and "data" directory

could be a good idea add "Upgrade" instruction on wiki?

Alessandro

**Comment by eibex** [comment]
I simply unpack the file in the snappymail directory. The older versions (and if applicable data/include) are preserved and any changes in index.php and the likes are overwritten while the new version directory is created under `v`

**Comment by eibex** [comment]
I will add that if the upgrade script proposed in #229 does not make it into the repository it could be a good start for a potential upgrade wiki section.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#upgrade
