### ISSUE TITLE
User TOTP broken

### ISSUE THREAD

**Issue by geoghegan** [the-djmaze/snappymail#236]
**Describe the bug**
SnappyMail does not allow a user to set up TOTP / 2 factor auth in version 2.12.2. The QR code is also not generated for the user's authenticator app to scan, you cannot enable TOTP as a user, and you cannot test the TOTP code generated.

**To Reproduce**
1. Login as user
2. Click cog symbol
3. 2 Step Verification
4. Activate

**Expected behavior**
A QR code generated, the ability to test and save the TOTP seed, the ability to login using TOTP.

**Desktop (please complete the following information):**
 - Browser Chrome 98
 - SnappyMail Version 2.12.2

**Additional context**
Is it possible for the user to supply a TOTP seed? It would also be great if the main login page only shows the TOTP text box on login if applicable to the user - such as in RainLoop

Great work btw, nice to see someone forking RainLoop to address those security issues

**Comment by the-djmaze** [comment]
Sorry, i forgot to release new plugin version with v2.12

As for the QR code: yes there is none, only the codes are shown.
You want to see a QR code as well?

**Comment by the-djmaze** [comment]
You can use this latest commit to get a QR code.
Look carefully as you need the \SnappyMail\QRCode class

**Comment by Parodontitis** [comment]
Problems with 2-Step verification

1. I can't mark the backup codes for c&p
2. I can't mark the secret for c&p
3. Nothing happens on click on the test link. Developer tools means:
    Uncaught TypeError: rl.showPluginPopup is not a function
    testTwoFactor https://<domain.com>/?/Plugins/0/User/6f0ad853263782883a24931b99ade/:142
    init https://<domain.com>/snappymail/v/2.12.2/static/js/min/libs.min.js:1

The way to create TOTP for admin is a little unusual but works fine for me.

Thank you.

**Comment by the-djmaze** [comment]
v2.13
