### ISSUE TITLE
Compose message window and CC

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#239]
After a default installation compose message window show TO field and a BCC button (black carbon copy) only to add new BCC field.
I suggest add CC (Carbon copy) button.
![cc_snappymail](https://user-images.githubusercontent.com/956392/154733059-d7d30c27-806b-4dc1-bd5a-2efcf2a69d65.png)

Of course is possible add CC using the other button, but it is not immediate.

HTH
Alessandro

**Comment by the-djmaze** [comment]
> Of course is possible add CC using the other button, but it is not immediate.

The reason behind this, is that in Europe there are strict privacy rules (GDPR).
A lot of people are digital illiterate and send e-mails to a group of people without their knowledge.
I've seen this happen many times and this must be reported to authorities.

So, i've made CC hidden, in the hope that people don't use it without real purpose.

I know other mail applications don't, but that is their (and mostly a user) problem.

**Comment by lota** [comment]
you choice have sense

anyway use BCC produces another unwanted effect if recipient (in BCC) relpy to mail: recipient in TO discovers someone else read preview mail

in short: snappymail cannot solve GDPR incorrect use of application (only IQ can...)

I suggest add both "CC" and "BCC" or remove both

this is only my opinion
Alessandro

**Comment by ervee** [comment]
Is the regular option of adding both CC and BCC still an option via setting in application.ini ?

**Comment by the-djmaze** [comment]
I will add the [CC] button back for non-mobile view (else there is not enough space)
