### ISSUE TITLE
Automate CardDAV synchronization

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#24]
**RainLoop version, browser, OS:**
2.0.0-rc2, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
CardDAV is currently only synchronized, if you manually click on "Contacts" and then "Synchronization (CardDAV)". To make this more user friendly it would be great, if SnappyMail could automatically trigger a CardDAV synchronization.
Suggestions, when a CardDAV synchronization could be triggered automatically:
1) By clicking on the "New message" button. This would be my preferred solution, because this ensures, that you have the latest contacts addressbook, when you want to write an email.
2) On every login.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
n/a

**Comment by the-djmaze** [comment]
Good idea.

Personally i like cron jobs on the server. For example sync every hour on the background. This way the user keeps the snappy experience without synchronization delays.

I will look into the code which options are possible.

**Comment by phsc84** [comment]
Ok, I understand your argument. A cron job would also be fine.
If you let me know, what script has to be executed in the cron job, I will gladly extend the FAQ.

**Comment by ervee** [comment]
I don't prefer cron jobs. They would consume resources for say every hour, 24 hours a day. Consider syncing CardDAV for 500 users every hour... It would be sweet if the code could run a background sync when the user log in and then if possible something like every one hour for as long as the user is logged in.

**Comment by the-djmaze** [comment]
Cron doesn't have to be every hour.
It can be every hour between 8:00 and 18:00 or just once or twice a day.
The cron could even have sleep between syncs to have only one user per minute.

Ofcourse a sync can be done per login, but that could mean once every 30 minutes on the default auto-logout.

Developing more optional sync solutions allows the best setup per user/server.

**Comment by phsc84** [comment]
Tested it. This works perfectly fine. So nothing open from my point of view.
