### ISSUE TITLE
Logout from "sub-email account" doesn't work - takes you back to login email address

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#241]
SnappyMail 2.12.2

I log in as testing@example1.com, where I have also setup other email accounts on different domains, like testing@example2.com, testing@example3.com and testing@example4.com
If I log out while I'm on testing@example4.com [or any of the other "sub-email accounts"], I'm taken back to testing@example1.com instead of being taken out of the applicaition. Only if I log out while on testing@example1.com I'm litterally logged out of the application.

Is this an expected behaviour?

**Comment by the-djmaze** [comment]
> Is this an expected behaviour?

It was testing behavior. So i've disabled it.
