### ISSUE TITLE
Moving from one email address to another - "Inbox" folder issue

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#242]
SnappyMail 2.12.2

If I move from testing@example1.com to testing@example2.com I'm only shown the "Inbox" folder and its messages if I was on the "Inbox" when selecting the other email address.
If I was on [e.g.] "Trash", then I'm shwon an "Empty list" [see screenshot] and I need to click on "inbox" to see the messages.
SnappyMail should automatically default to "Inbox" when moving from one email address to another [Rainloop used to do it].

![Screenshot 2022-02-23 at 09 48 08](https://user-images.githubusercontent.com/35845319/155295589-7b44bb79-cbfd-490e-bcd6-d7dfba43fbae.jpg)

**Comment by phsc84** [comment]
This is already the case since some releases, e.g. on 2.10.2 it is the same behaviour. But I would also like Snappymail to always default to "Inbox".
