### ISSUE TITLE
2.12.2: folder "mark all as read" ineffective

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#247]
Hello,

I have an issue with the folder mark all as read feature, it seems to be effective but when reloading the folder, messages are once again unread.
There is no problem with thunderbird so it is not an issue of the IMAP server.

**To Reproduce**
(see screenshot below)
1. Go to a folder with unread messages
2. Used "mark all as read", they are no visibly read
3. Go to another folder
4. Come back, all the messages previously unread are back to unread status

Notice also that:
5. Click on any of these messages so it is read (after the configured timeout: in my case, instantly),
6. Go to another folder
7. Come back: his message read status is, on the contrary, kept

**Expected behavior**
Mark all as read, change folder and come back: all these messages stays as read.

**Screenshots**
![firefox_noG76D0srx](https://user-images.githubusercontent.com/1160681/155876823-686b86f1-8297-4e87-a043-4c2139aa9ab8.gif)

**Desktop (please complete the following information):**
 - Browser Firefox 97.0.1
 - SnappyMail Version 2.12.2

**Additional context**
IMAP server is Dovecot on Devuan stable

**Comment by Yoda-BZH** [comment]
Same behaviour here.
Debian Stable, dovecot, interface in english, Google Chrome, snappymail 2.12.2.

**Comment by Yoda-BZH** [comment]
Thank you !
