### ISSUE TITLE
View eml attachments

### ISSUE THREAD

**Issue by albsch** [the-djmaze/snappymail#248]
**Is your feature request related to a problem? Please describe.**

Some company is sending me `.eml` files as attachment. So far, I need a separate client because I don't know how to view them otherwise (in SnappyMail).

![image](https://user-images.githubusercontent.com/38429047/155994234-2cdaed5d-490d-42bd-afb0-3736bc6e4d4f.png)

This has absolutely no priority, I'm getting emails like this once a year. Still, I would like to use only SnappyMail instead of multiple mail clients.

**Describe the solution you'd like**
I don't know what a good solution would be. A popup on click showing the content maybe? Or importing the `.eml` as a proper separate mail into the inbox?

**Describe alternatives you've considered**
Download the attachment via SnappyMail and use another client to display the `.eml` file.

**Comment by the-djmaze** [comment]
SnappyMail now has a MIME parser in JavaScript.
So yes, the best way could be a new browser window with the content OR load the .eml into the message viewer itself
