### ISSUE TITLE
From v2.12.2 to v2.13.0 - menu colour scheme

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#249]
I've just upgraded from v2.12.2 to v2.13.0 and some writing that used to be in white is now in black, and not easy to read.
See screenshots [SnappyMail at login and menu on the left]:

![Screenshot 2022-02-28 at 14 54 42](https://user-images.githubusercontent.com/35845319/155996054-ae0d1b67-1371-4b0e-9ead-b7111fe2f739.jpg)

![Screenshot 2022-02-28 at 14 55 28](https://user-images.githubusercontent.com/35845319/155996083-da71d9f0-2094-4ce3-9c9d-e0db31554c25.jpg)

Is anyone else experiencing that issue?
If intentional, then it would be good to be able to personalise that, because it doesn't work with dark themes.

**Comment by Parodontitis** [comment]
Same here.

![grafik](https://user-images.githubusercontent.com/41056353/155999855-b9685033-053a-49e9-adca-9ba660fbe03b.png)

**Comment by the-djmaze** [comment]
Sorry, i deactivated LESS parser when there are is no LESS data to parse.
It seems the theme css files were incorrect CSS

**Comment by the-djmaze** [comment]
Quick new release: https://github.com/the-djmaze/snappymail/releases/tag/v2.13.1

**Comment by eibex** [comment]
How can I rerun minify CSS? I fixed my custom CSS files now, but even after deleting `static` and re-unpacking 2.13.1 (and reclearing cache) I still get the wrong minified CSS.
