### ISSUE TITLE
 From v2.12.2 to v2.13.0 - settings are blank, but OK under "Config"

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#250]
After upgrading from v2.12.2 to v2.13.0 a lot of the settings sections show blank entries.
Eg. Branding or Contacts sections.
At the same time, they are still properly congigured under the Config sections and work as expected.

![Screenshot 2022-02-28 at 15 06 41](https://user-images.githubusercontent.com/35845319/155996908-7c3b54db-cec3-4610-a373-b28d644ac154.jpg)

![Screenshot 2022-02-28 at 14 52 30](https://user-images.githubusercontent.com/35845319/155997037-5221414a-d859-4621-bb0f-fc6f2de61da1.jpg)

Is anyone else experiencing the same issue?

**Comment by the-djmaze** [comment]
Quick new release: https://github.com/the-djmaze/snappymail/releases/tag/v2.13.1
