### ISSUE TITLE
Still problmes with TOTP v2.13

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#251]
**Describe the bug**
Still Problems with 2-Step verification:

-     Nothing happens on click on the test link. Developer tools means:

    Uncaught TypeError: rl.showPluginPopup is not a function
    testTwoFactor https://<domain.com>/?/Plugins/0/User/6f0ad85326378323232329ade/:142
    init https://<domain.com>/snappymail/v/2.13.0/static/js/min/libs.min.js:1
-        I can't mark the backup codes for c&p 
-        I can't mark the secret for c&p

The way to create TOTP for admin is a little unusual but works fine for me.

Thank you.

**Desktop (please complete the following information):**
 - Browser firefox 97.0.1 and Chrome 98.0.4758.102 (Official Build) (64-bit)
 - SnappyMail Version 2.13

That's the last reason why I don't use snappmail for production reasons.

**Comment by the-djmaze** [comment]
You have plugin version 2.13?

**Comment by Parodontitis** [comment]
SnappyMail Version 2.13
TOTP 2FA Plugin Version: 2.4

**Comment by the-djmaze** [comment]
You need TOTP 2FA Plugin Version: 2.13

**Comment by the-djmaze** [comment]
Ah repo had 2 versions inside.
Fixed that and now it should work.

Clear cache first.

**Comment by Parodontitis** [comment]
1. Cache cleared
2. Plugin version 2.13 installed
3. After installation there is no improvement. Clicking the "Test" link still gives the same error message.

Can anyone confirm this?

@the-djmaze - sorry for this. How can I help you to fix the error?

**Comment by the-djmaze** [comment]
Found the issue. Plugins cache hash was incorrect.

**Comment by Parodontitis** [comment]
@the-djmaze - Yes! Now the plugin works correctly. Thanks!
