### ISSUE TITLE
TOTP still broken in 2.13.1

### ISSUE THREAD

**Issue by geoghegan** [the-djmaze/snappymail#254]
**Describe the bug**
Unable to activate 2SV / TOTP

**To Reproduce**
1. Enable TOTP in admin console
2. Login as user 
3. Cog Symbol
4. 2 Step Verification
5. Attempt to activate 

**Expected behavior**
1. No QR code is generated
2. Unable to test configuration
3. Unable to save configuration
4. Unable to copy/paste TOTP seed
5. Unable to copy/paste backup codes

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome 98
 - SnappyMail Version 2.13.1
 - Plugin version 2.13

**Additional context**
Recurrence of #236

**Comment by Parodontitis** [comment]
@geoghegan the https://github.com/the-djmaze/snappymail/commit/fd90949e15ccddf44246efec7a1a3bca131e12e7 patch is not jet in the 2.13.1 Version. You have to patch manually or wait for the next version.

**Comment by geoghegan** [comment]
Thanks for releasing 2.13.2 @the-djmaze !

Ironically it looks like TOTP is still acting strange on both v2.13.2 of snappy and 2.13.2 of the TOTP plugin. When you attempt to activate in the user's panel the email address vanishes and you're not able to activate TOTP!

![Screenshot 2022-03-04 at 10 28 22](https://user-images.githubusercontent.com/937427/156746645-96ad29f6-97e7-48a8-b37d-4ddefcf3fc99.png)

**Comment by the-djmaze** [comment]
Yes i broke it again :(
See #263 so i fixed it and updated the repository

**Comment by Parodontitis** [comment]
Can be closed?

**Comment by geoghegan** [comment]
Looks like it's still ongoing :-(

**Comment by fs1** [comment]
I am using snappymail 2.15 and TOTP 2.13.3 and it is working.
Sometimes it doesn't show the english [translation](https://github.com/the-djmaze/snappymail/blob/fd28741cb8b860a76ae5aed986d1e077104cea32/plugins/two-factor-auth/langs/en.ini), instead it displays `LABEL_ENABLE_TWO_FACTOR` for example. But thats's just a minor error and I was not able to reproduce this behaviour on demand.

**Comment by the-djmaze** [comment]
Still with latest release and latest plugin using Chrome 100?

**Comment by geoghegan** [comment]
@the-djmaze : It works now! 

Chrome 101
TOTP plugin version 2.15.1
Snappy version 2.16.1

Thank you so much!
