### ISSUE TITLE
Contact database and synchronization is not working

### ISSUE THREAD

**Issue by SiopySh** [the-djmaze/snappymail#255]
**Describe the bug**

When I want to synchronize my Nextcloud contacts with Snappymail, it doesn't work.

I first configure the contacts database from ?admin#/contacts, during the test the following error is returned in the console: 

"Uncaught TypeError: this.contactsPdo is not a function". The test is not successful. 

When I log in as a user and want to synchronize the contacts, the network request returns the following error:

Post request https://xxx.com/snappy/?/Json/&q[]=/0/ : 

```
Action "ContactsSync"
Result false
ErrorCode 140
ErrorMessage ""
ErrorMessageAdditional ""
Time 1675 
```

User contacts configuration (CardDav) #/settings/contacts : 

```
https://cloud.com/remote.php/dav/addressbooks/users/xxx/contacts/
username
password
```

**To Reproduce**
1. Go to '?admin#/contacts'
2. Add your database credentials
3. Click on 'test' button
4. See error in the console
5. Log in as user
6.  Go to "#/settings/contacts" and add your carddav credentials
7. Back to the home page
8. Click on the contact button
9. Click on the hamburger button (button on the right)
10.  Click on the synchronization button 

**Desktop :**
 - Firefox 91.3.0esr
 - SnappyMail Version 2.13.1

Thanks.

**Comment by eibex** [comment]
I am syncing with Nextcloud just fine. Make sure to use an app-password with you have 2FA setup on your NC account, else your login password will not work. 

Can Snappymail connect to the database you created with the given user? (and does said user have enough permissions on the target db?)

**Comment by Parodontitis** [comment]
Syncing working fine. But the data will be not show correctly: 

![grafik](https://user-images.githubusercontent.com/41056353/157022119-5e5de8dd-2fc2-4078-9fad-3cf59dfb926f.png)

This contact was created in Nexcloud ans imported via CardDAV to snappymail.

**Comment by eibex** [comment]
I can see the first name and surname fields being displayed correctly on both the sidebar and the detail view. Are they set to those fields or some others? 

(v2.13.1)

**Comment by Parodontitis** [comment]
@eibex did you created the contact in nextcloud?
![grafik](https://user-images.githubusercontent.com/41056353/157050144-b707fc8d-a4f7-4986-9920-53b862c5afba.png)

**Comment by eibex** [comment]
I can see what you meant now.
The issue is with Nextcloud contacts app not allowing you to set proper First name and Last name fields, not with Snappymail.
If you generate the contact with, for example, a phone synced to Nextcloud then Snappymail will display it correctly.

**Comment by Parodontitis** [comment]
It was a surprise for me, that this based on two different fields. But I'll test this with my cellphone. Thank you.

**Comment by SiopySh** [comment]
> I am syncing with Nextcloud just fine. Make sure to use an app-password with you have 2FA setup on your NC account, else your login password will not work.
> 
> Can Snappymail connect to the database you created with the given user? (and does said user have enough permissions on the target db?)

Thank you eibex, I had 2FA activated on my account.
