### ISSUE TITLE
high severity Security Issue from SonarSource

### ISSUE THREAD

**Issue by privnote42** [the-djmaze/snappymail#256]
Hi,

did the SnappyMail team already contact SonarSource about the high-severity security vulnerability that Simon Scannell from SonarSource found?
It is reported for Rainloop, but as a fork there is a not small chance that it could also affect Snappymail

In a few days he will make public all the details about it

https://github.com/RainLoop/rainloop-webmail/issues/2142

**Comment by the-djmaze** [comment]
I've noticed the report but never contacted him.
Also @simon-scannell-sonarsource did not e-mail me or reported it here.

Since this source is also heavily modified and has security changes, we just have to wait what the problem is.

**Comment by simon-scannell-sonarsource** [comment]
Hi @the-djmaze ,

Let me know what your email address is and I can forward the advisory to you. You can also contact me at
simon.scannell at sonarsource.com

Best,
SImon

**Comment by the-djmaze** [comment]
Hi @simon-scannell-sonarsource ,

you can send an encrypted e-mail.
I've uploaded the missing SECURITY.md with the details at
https://github.com/the-djmaze/snappymail/security/policy

**Comment by the-djmaze** [comment]
@privnote42 i've received the report and since v2.12 it's not an issue.
And before v2.12 the Content Security Policy prevents the issue.

**Comment by the-djmaze** [comment]
Here is Simon his blog post:
https://blog.sonarsource.com/rainloop-emails-at-risk-due-to-code-flaw
