### ISSUE TITLE
Please bring back Rainloop's "sieve_allow_raw_script" option

### ISSUE THREAD

**Issue by veitw** [the-djmaze/snappymail#257]
Hi,

I just installed Snappymail to replace Rainloop in the future and gave some of my users access to it. Many of the non-technical users were really confused by the new multi-script capable filter editor, esp. when they were drawn into the sieve code editor.

Rainloop has the option `sieve_allow_raw_script = Off` to cope with this problem, giving users only access to the visual filter editor, and I would be glad to see it back in snappymail.

I'd propose the following behaviour if `sieve_allow_raw_script` is set to `Off`:
- In Settings, when clicking on "Filters", do not open the script manager, but instead open the visual filter editor for the script `rainloop.user`.
- In the visual filter editor, hide the "user defined script" button and replace the "Edit Script: rainloop.user" title with "Edit Filters".
- When saving filters, automatically set `rainloop.user` active.

Thank you very much in advance!

Best regards,
// Veit

**Comment by the-djmaze** [comment]
I understand why your customers are confused.
But no, i will not put that option back.

Why? Well, many customers also use Sieve in their other apps (kmail, thunderbird, roundcube, etc.).
By hiding the scripts list they never know which script is the active one.

Instead there's already a feature request to have a better GUI for any of the (complex) scripts.

Read #80

**Comment by veitw** [comment]
Hi @the-djmaze,

thank you for your answer.

I understand your point, also my intention was not to prevent users from using the full functionality, but to hide unnecessary complexity from technically non-experienced users, and having that option back was the most simple to implement way I was able to think of.

Therefore I'd like to change my proposal, to match both your and my points:
- Have a button in Settings -> Filters to switch between Expert mode and Basic mode.
- Expert mode corresponds to the current implementation.
- Basic mode only shows the visual ruleset editor for rainloop.user and removes the "Edit Sieve source code" button, and the rainloop.user script is enabled on save.
- If there is at least one script that is not rainloop.user, or rainloop.user is not active, the user is put into expert mode automatically and trying to enable Basic mode shows a message that the script status prevents this.
- An option in application.ini defines whether (new) users are put into Basic or Expert mode by default.

I will also put this in #80 to have it on track for the new Filters editor, but I leave it here as I hope this is still simple enough to implement it out of track before the Filters editor gets completely revamped. :)

Thank you and best regards,
// Veit

**Comment by the-djmaze** [comment]
Yes that would be a much better approach

**Comment by veitw** [comment]
Sorry for changing the title, I did not recognise the `wontfix` tag. I close this under the old title in favour of the my proposal which is also in #80 now.
