### ISSUE TITLE
Support for S/MIME

### ISSUE THREAD

**Issue by jonmoesli** [the-djmaze/snappymail#259]
Sadly no open source (active) webmail supports decently S/MIME standard, very used in big companies/gov.
Is there a plan to support it? Thank you!

**Comment by the-djmaze** [comment]
I could, but the problem is that certificate and private key must be on server.
You really must trust the server with this.

I haven't found a solution yet to do this client-side.

**Comment by the-djmaze** [comment]
SnappyMail can now generate private keys and certificates with the self-signed root certificate snappymail.crt

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.35.0

**Comment by necrevistonnezr** [comment]
S/Mime certificates do expire and will need to be replaced multiple times over the lifetime of an email address. 
The current settings only seem to hold a single certificate. Which means once you rotate your certificate, you no longer can easily access old encrypted mail - correct?

**Comment by the-djmaze** [comment]
@necrevistonnezr you are correct.
In the future this and more are getting solved.

**Comment by the-djmaze** [comment]
> Which means once you rotate your certificate, you no longer can easily access old encrypted mail - correct?

@necrevistonnezr you are NOT correct. The private key is used for decryption.

The problem with the current "generate self-signed" setup, is that it rotates the private key.
This will be solved in v2.35.1

**Comment by JoKai66** [comment]
How is it possible to write/send an s/mime-encrypted email?
Therefore additionally to your own certificate and key the certificate of the rececpient is necessary. But where is this stored in snappy/nextcloud? Even when you got an encrypted email you CAN NOT answer with an encrypted email - only "sign" is possible - even all necessary information is existing in the received email I'm trying to answer!?
Also if I try to create a new email (have my certificate & key stored in snappy) first there are both options (encrypt and sign) available - bat as soon as I enter a receipient, the enctypt-option disappears! Only sign is still available. This is quite clear as therefore only MY s/mime-information is necessary.
So the central question is, how can s/mime-emails be written? Currently I see no way to do it with snappy - even the announcement from Feb 2024 says it sould be possible?!
