### ISSUE TITLE
Cannot save or send email in some circustances

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#260]
**Describe the bug**

Today I receved an email with a security vulnerability report about a server I manage.
I fixed the vulnerability than I tried to reply to that email receved.

I used snappymail latest version 2.13.1 but I cannot reply to this specific email.
If I copy the email text and paste it in a new mail window on snappymail again I cannot save or send the email.

I cannot share here the text because is a private email.
How can I help you to understand what is wrong and hope to obtain a fix?

Should I share by email the private email content?

**To Reproduce**

Paste: 

> Scan data:

in a new email body than try to save or send.

**Expected behavior**

Be able to save the email

**Screenshots**

I get error cannot save or cannot send

**Desktop (please complete the following information):**
 - Browser Firefox 97.01
 - SnappyMail Version [e.g. 2.13.1]

**Comment by PeopleInside** [comment]
5. [HTTP/2 403 Forbidden] XHRPOST https://webmail.domain.ext/?/Json/&q[]=/0/
This is what I see from the web console.
In the server error logs at the moment I don't see anything of partivular related to this.

**Comment by the-djmaze** [comment]
There must be something wrong with your server configuration.
SnappyMail only sends a 403 with content `Disallowed Sec-Fetch...`

Check you Apache/Nginx/etc. configuration why POST commands could fail.

**Comment by PeopleInside** [comment]
The strange thing is that I can send email, save.
I have the error just if I insert in the email body **Scan data:**

Are you unable to reproduce on your side by pasting **Scan data:** in the body?
Can you please give a try?

![snappyerror](https://user-images.githubusercontent.com/5006150/156733100-54ed6834-d822-4b9a-a5e5-1187f3459ef1.gif)

Thanks for the help.

**Comment by the-djmaze** [comment]
You can try at https://snappymail.eu/demo/
It allows to send emails to itself `demo@snappymail.eu`

**Comment by PeopleInside** [comment]
OK thanks, unable to reproduce.
Strange issue, thanks.
Closing as this seems to be only mine issue.
