### ISSUE TITLE
Picture Resize

### ISSUE THREAD

**Issue by Darkxaser** [the-djmaze/snappymail#262]
in the original Rainloop there is the possibility to include images directly into the email and to change the size. Will you add this feature again?  That would be great

![picture](https://user-images.githubusercontent.com/100842056/156744069-d9519259-fbb4-45bc-b2b8-fe3e695b0073.png)

**Comment by the-djmaze** [comment]
Actually: RainLoop does not resize the picture.
It's a feature of CKEditor and the only thing that happens is that what you see is "smaller".
The image can still be 10MiB and 4000x4000 pixels.

In ?admin go to extensions and install CKEditor. It might work for you.

**Comment by Darkxaser** [comment]
thank you for the quick reply. when I activate the feature, I have a white field in the email. But no other editing options are displayed.  Also the drag and drop does not work with all images.

thanks for the support

![cmyk](https://user-images.githubusercontent.com/100842056/156766526-a5fcd5e5-54c8-4d22-aa19-6c8249576d3b.png)
![cmyk2](https://user-images.githubusercontent.com/100842056/156766544-485ff766-76e4-4bdb-a6c3-01c6d2dd6b51.png)

**Comment by Darkxaser** [comment]
I have tested this again. The window for editing the resolution appears behind the e-mail.  When does the email minimize to get to the editor window. This error happens only in Brave browser in Firefox this does not happen. But in all browsers you have a white border under the email. As I have already tried to show in the screenshot above.

![cmyk3](https://user-images.githubusercontent.com/100842056/157403515-de22998d-ae4d-4392-8265-88aa9a2e2517.png)

**Comment by yeupou** [comment]
I would like to support the idea of an actual resize of the attached files as option. These days, with most cameras, photos are way bigger than what is accepted by most mail servers. At most you can attach 2 or 3 before reaching a 10MB limit.

It would be great if automatic resize was an option.

**Comment by the-djmaze** [comment]
@yeupou indeed!
But that requires a `<canvas>` element.
So, when embedding an image,
* don't use `<img>`, use `<canvas>`
* resize canvas
* on submit convert canvas to `<img src="canvas.toDataURL()">`

**Comment by Darkxaser** [comment]
Hi, would like to replace rainloop completely with snappy. Do you think you can get rid of the error I showed above?

Would be really nice

**Comment by the-djmaze** [comment]
For now all images that are pasted will get resized to max 1024px
