### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by jonmoesli** [the-djmaze/snappymail#264]
Maybe could be nice to have support for PWA.

Roundcube has a very primitive [plugin](https://git.kolab.org/diffusion/RPK/browse/dev%252Fpwa/plugins/pwa/).

Very nice project, thank you! :-)

**Comment by the-djmaze** [comment]
It already should work.
Here's the manifest: https://github.com/the-djmaze/snappymail/blob/master/assets/manifest.json

**Comment by jonmoesli** [comment]
It'd be nice to extend with notification support, caching, etc. Too much? :-)
(Sadly iOS seems to have limited support, I'm not very expert)

**Comment by the-djmaze** [comment]
PWA will not be extended due to phone push service complications
