### ISSUE TITLE
Search filed

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#265]
**Describe the bug**
Wrong reaction while typing search phrase in search field.

**To Reproduce**
1. select an email
2. click in search field
3. type the letter r

**Expected behavior**
the letter r appears in the search box but replay form will be open.

**Desktop (please complete the following information):**
 - SnappyMail Version 2.13.3

**Comment by the-djmaze** [comment]
Right, that's due to the changes of the shortcuts system.
It was a mess, but seems that is still a mess :smile: 

Will improve the shortcuts further.

**Comment by the-djmaze** [comment]
See #252 why it was changed (but now broken the other way round)

**Comment by gnilebein** [comment]
This also happens with other combinations. Shift + F in the search field forwards the current message as an attachment. This should be examined again which combinations  are still there.
