### ISSUE TITLE
2.13.2: "t"/"delete" not being typed in search field

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#266]
Typing "t" or "delete" in search field has no effect, the letter T does not appear and delete does not remove text

**To Reproduce**
1. Go to top search field in message list
2. Type t : no effect
3. Type abc, select it and type del: abc is still there

**Desktop (please complete the following information):**
 - Firefox 96.0.3
 - SnappyMail Version 2.13.2

**Comment by the-djmaze** [comment]
Yes, same issue as #265
