### ISSUE TITLE
Bug: User drop-down menu shows account switcher although multi-account is disabled, and error message when clicked

### ISSUE THREAD

**Issue by veitw** [the-djmaze/snappymail#268]
**Describe the bug**
The user drop-down menu shows the account switcher with the logged-in user, even when `allow_additional_accounts = Off`.
Clicking on the user then shows an error message, as account switching is not allowed.

**To Reproduce**
1. Set `allow_additional_accounts = Off` in `application.ini`.
3. Log in to Snappymail.
4. Click on the user menu.
5. Click on the account of the currently logged-in user.
6. Error message 'Unknown error' appears.

**Expected behavior**
The list of accounts/account switcher should not be displayed in the user menu when `allow_additional_accounts = Off` is set.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16285895/156904249-bd2e1256-6a49-459b-99f3-ec7775d8ec09.png)
![grafik](https://user-images.githubusercontent.com/16285895/156904279-b402a375-7f1f-4671-9169-a7a6f922558a.png)

**Desktop (please complete the following information):**
 - Firefox 97.0.1
 - SnappyMail 2.13.2

**Comment by veitw** [comment]
Hi @the-djmaze,

I can confirm that the error message is no longer pop up in 2.13.3, but the account switcher is still shown in the user menu.

This is how it looks:
![grafik](https://user-images.githubusercontent.com/16285895/157332297-4cda1db2-ac58-47a2-bd3c-0929dc51b695.png)

And this is how I propose it shall look with `allow_additional_accounts = Off` (here enforced using CSS):
![grafik](https://user-images.githubusercontent.com/16285895/157332766-5db0e81d-506f-4ab0-8f4f-1178ef207584.png)

Thanks and best regards,
// Veit

**Comment by the-djmaze** [comment]
Could you open separate issue for your proposal?

**Comment by veitw** [comment]
Sure, here it is:  #280
