### ISSUE TITLE
Migration instructions from Rainloop.

### ISSUE THREAD

**Issue by craftxbox** [the-djmaze/snappymail#271]
**Is your feature request related to a problem? Please describe.**
There is no guide or FAQ about migrating an existing rainloop instance to snappymail.

**Describe the solution you'd like**
I would like to see a guide or small write-up on how to properly migrate an existing Rainloop install to Snappymail, As right now It is problematic to not know what to do.

**Additional context**
In attempting to just 'drop in' replace rainloop, My test install became broken and the control panel inaccessible, Complaining of problems with a custom ChangePasswordSQL plugin that I had wrote.

**Comment by the-djmaze** [comment]
> Complaining of problems with a custom ChangePasswordSQL plugin that I had wrote.

Correct, the plugins system has changes.
Read https://github.com/the-djmaze/snappymail/tree/master/plugins#readme



> I am being asked for a TOTP code for ?admin login, something that Rainloop did not have and as a result I don't have

You can leave the field empty. You can set it later.
Read here for info: https://github.com/the-djmaze/snappymail/issues/84#issuecomment-896095488

**Comment by craftxbox** [comment]
Possibly off-topic for this issue, I assume there is no plans to re-add support for external oauth providers like Google's Oauth? I used it pretty heavily, Any materials of where/how I could do this myself if not planned would be appreciated.

**Comment by the-djmaze** [comment]
> I assume there is no plans to re-add support for external oauth providers like Google's Oauth?

There's some draft code here:
https://github.com/the-djmaze/snappymail/tree/master/plugins/login-oauth2

**Comment by jas8522** [comment]
I think this got derailed with specific issues. The original question was: "I would like to see a guide or small write-up on how to properly migrate an existing Rainloop install to Snappymail, As right now It is problematic to not know what to do."

And I, too, am curious as to what the best migration path is. The rough version I'm thinking goes like this:

1. Clone RainLoop data folder and database to a staging area
2. Drop snappymail over top of staging area
3. Resolve plugin incompatibilities manually (replacing rainloop plugins with snappymail equivalents where available)
4. Re-complete steps on live, with updated plugins folder and configuration files.

Does that work? Is there a better way?

**Comment by the-djmaze** [comment]
> Does that work? Is there a better way?

That should probably it.
However, some plugins are not available (converted).

**Comment by jas8522** [comment]
Those steps worked well with these alterations/notes:
- First thing noticed after step 2 was errors about plugin incompatibilities (not surprised). I disabled them and replaced them later on with no issues. I only had a couple plugins activated previously, so this was fairly easy.
- After attempting admin login I received this error attempting admin login: `0 - Call to private method RainLoop\\Actions::getAdditionalLogParamsByUserLogin() from context 'RainLoop\\ActionsAdmin'` -- the solution was to reset the admin password by commenting out admin_password in application.ini then logging in with the new one it created for me (and changing it, of course)

Question: is the 2fa functionality in RainLoop compatibile with the 2fa plugin for SnappyMail such that if users have already set up 2fa in RainLoop, they'll be able to continue to login after the transition to Snappy, or will the admin need to reset those 2fa codes for them?

**Comment by jas8522** [comment]
I've added my findings / steps above to the wiki: https://github.com/the-djmaze/snappymail/wiki/Installation-instructions

**Comment by the-djmaze** [comment]
> I've added my findings / steps above to the wiki

Thanks!
