### ISSUE TITLE
Bug: Plugin change-password: Empty screen after successfully changing password

### ISSUE THREAD

**Issue by veitw** [the-djmaze/snappymail#272]
**Describe the bug**
When using the change-password plugin, after successfully changing the password, the Snappymail screen turns empty, showing only the background image.

**To Reproduce**
1. Go to 'Settings' -> 'Password'
2. Enter current password, new password and confirm new password.
3. Click on 'Set New Password'
4. See the screen is empty.

**Expected behavior**
Password dialog being shown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16285895/157125106-ace40f7f-070f-412f-9b32-6c64c74fd5b5.png)

**Desktop (please complete the following information):**
 - Firefox 97
 - SnappyMail 2.13.2

**Comment by the-djmaze** [comment]
Could you show me the browser debug console output for any errors?

**Comment by veitw** [comment]
A TypeError exception is thrown, though I do not know whether this output is actually very meaningful due to minified source:

![grafik](https://user-images.githubusercontent.com/16285895/157471439-95d2ad4a-3f09-4dc1-baf9-d9746a042395.png)

**Comment by the-djmaze** [comment]
Right it's not.
When you enable js debug it is better.
You can enable that in application.ini

**Comment by veitw** [comment]
This is the trace with
```
[debug]
enable = On
```

![image](https://user-images.githubusercontent.com/16285895/157501429-a60dd244-d8be-46ba-a18c-7387322d666f.png)

**Comment by the-djmaze** [comment]
Sorry, i needed to be more detailed.
The setting is `use_app_debug_js = On`

**Comment by veitw** [comment]
Ah, that looks **much** better. :D

![grafik](https://user-images.githubusercontent.com/16285895/157659551-7dbd16b7-2922-4a69-b96f-d46489698fbc.png)

**Comment by veitw** [comment]
Just updated to 2.13.4, and the `TypeError elementById(...) is null` error message itself is now gone, but the problem persists, so still empty screen after successfully changing the password.

**Comment by the-djmaze** [comment]
I made a change. Can you check if that works?

**Comment by veitw** [comment]
> I made a change. Can you check if that works?

I installed 2.15.1 and the problem persists.

Had this change been included in version 2.15.1?

**Comment by veitw** [comment]
Updated to 2.15.3, the problem persists.

**Comment by the-djmaze** [comment]
Ok will further investigate it

**Comment by the-djmaze** [comment]
I think i found the issue.
The build process to create the package did not only include the `change-password` directory, but also any other directory that started with `change-password`.
So it uncluded:
* change-password-ispconfig
* change-password-poppassd

And that resulted in issues.

**Comment by veitw** [comment]
Nice. :)
I will test for this issue again on the next release.

**Comment by the-djmaze** [comment]
New plugin versions are released. Just go to your ?admin and update them.

**Comment by veitw** [comment]
The plugin has been updated to 2.16:
![grafik](https://user-images.githubusercontent.com/16285895/169477184-47cfd4f8-9510-4ce2-838e-907cf8a42157.png)

Unfortunately, now the "Password" (in German: "Passwort") item has disappeared from webmail's settings menu:
![grafik](https://user-images.githubusercontent.com/16285895/169477426-1d1e7ac8-5538-4e7c-84ef-ed2d6f5c76d4.png)

The PHP error log does not show any errors, only lots of GPG DEBUG messages as usual.

**Comment by the-djmaze** [comment]
Found error in the JavaScript. Re-install ;)

**Comment by veitw** [comment]
@the-djmaze : It works now just as expected, thank you very much!
