### ISSUE TITLE
HTML messages from Outlook 2010 are not displayed correctly

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#274]
**Describe the bug**
A simple HTML message with an image copy/pasted within is not displayed correctly in SnappyMail. Same message is correctly displayed in Thundebird, Outlook, K9Mail, ...

**To Reproduce**
1. Compose a HTML mail with Outlook, copy/paste an image in it.
2. Send message to a SnappyMail user
3. Display the message on SnappyMail
4. The image isn't there, even if you check the box to always display images in mail

**Expected behavior**
The message should be displayed correctly

**Screenshots**

Outlook 2010 compose window : 
![OutlookComposeWindow](https://user-images.githubusercontent.com/6248852/157220347-5309cce1-7c7c-4787-b7d9-6d44ea1b2685.jpg)

How SnappyMail renders the Outlook message :
![HowSnappyMailRenderOutlookMessage](https://user-images.githubusercontent.com/6248852/157220448-565c2622-0c48-4df8-bab1-7ba45321dc3e.JPG)

How Thunderbird renders the same message :
![HowTBRenderOutlookMessage](https://user-images.githubusercontent.com/6248852/157220701-b51cf331-de22-4a5e-a0c0-994ca37b14f7.JPG)

When the message is composed with TB in the same way (HTML, copy/paste the image), it is displayed correctly in SnappyMail : 

![HowSnappyMailRenderTBMessage](https://user-images.githubusercontent.com/6248852/157221436-91f7b9ff-ad3e-464a-968f-f5958bb69b74.JPG)

**Desktop (please complete the following information):**
 - Firefox 91.6 ESR
 - SnappyMail Version 2.13.1

**Additional context**
Source of the messages (from outlook and from TB) as seen by snappymail :
[SourceOutlookMessage.txt](https://github.com/the-djmaze/snappymail/files/8205337/SourceOutlookMessage.txt)
[SourceTBMessage.txt](https://github.com/the-djmaze/snappymail/files/8205391/SourceTBMessage.txt)

**Comment by the-djmaze** [comment]
Are you sure that the attached source is correct?

Because SourceOutlookMessage.txt contains a serious error that can't be solved.
The `boundary` of the image is not the same as the main `bounday`.

**Comment by Mer0me** [comment]
Maybe I've corrupted the file obfuscating the personal datas ? 
Can I send you the mail for test somewhere ?

Even if Outlook 2010 is outdated, there are number of old messages in mailboxes that were sent by this software and SnappyMail should display them as Thunderbird and other software do, no ?

**Comment by Mer0me** [comment]
I think the problem is reproductible even without using Outlook 210. If I forward the problematic email from Thunderbird, Snappy doesn't display it better. All other mail apps are displaying it well. Something is wrong with HTML parsing or rendering...

**Comment by Mer0me** [comment]
Yep, I screwed up the source file obfuscating, my bad.
I've sent the email to demo@snappymail.eu

**Comment by Mer0me** [comment]
Greylisted ?

Mar  8 14:41:23 gw-smtp postfix-out/smtp[24959]: 70B0D61757: to=<demo@snappymail                                                                  .eu>, relay=snappymail.eu[84.22.110.35]:25, delay=0.63, delays=0.01/0/0.49/0.13,                                                                   dsn=4.2.0, status=deferred (host snappymail.eu[84.22.110.35] said: 450 4.2.0 <d                                                                  emo@snappymail.eu>: Recipient address rejected: Greylisted for 60 seconds (in re                                                                  ply to RCPT TO command))

**Comment by Mer0me** [comment]
Hmm, it seems to work on the demo. What could go wrong on my instance ?

**Comment by Mer0me** [comment]
It works with latest version. Sorry for the inconvenience, I close the ticket.
