### ISSUE TITLE
Cannot create sieve script

### ISSUE THREAD

**Issue by raspbeguy** [the-djmaze/snappymail#276]
**Describe the bug**
I am not able to create a new sieve script. On the new script dialog, when I click on Save, I have this weird red banner with an exclamation mark and nothing in it (see the screenshot). I don't know what it means. Is my sieve code wrong? is there an error on the mail server?

I am able to manage my first script, that was created with Rainloop. I still can push and delete rules.

**To Reproduce**

- Go to your settings and choose Filters.
- Click on Add a script
- Enter a script, then click on Save

**Expected behavior**
My new script should be created.

**Screenshots**

![image](https://user-images.githubusercontent.com/1781287/157279667-8cce9d91-81cf-4579-b10b-568a46054cc8.png)

**Desktop:**
 - Firefox 97.0.2
 - SnappyMail Version 2.13.3

**Additional context**
I installed snappymail over rainloop.

**Comment by the-djmaze** [comment]
> **Expected behavior**
> My new script should be created.

Actually your script contains an error but the error is not shown.
I fixed showing the error message.
