### ISSUE TITLE
Control-a in search input selects emails instead of text

### ISSUE THREAD

**Issue by terribleplan** [the-djmaze/snappymail#277]
**Describe the bug**
When editing the search field (input is the active element) pressing Control+a selects all emails instead of the text in the field.

**To Reproduce**
1. Type something into the search field
2. Press Control+a
3. See that email are selected instead of text in search field

**Expected behavior**
The text in the search field is selected

**Screenshots**

**Desktop (please complete the following information):**
 - Firefox 97
 - SnappyMail 2.13.3

**Additional context**
Possibly related to the underlying cause of #265, but was seemingly not fixed when that was.

**Comment by the-djmaze** [comment]
> Possibly related to the underlying cause of #265, but was seemingly not fixed when that was.

Correct, i missed that one

**Comment by terribleplan** [comment]
@the-djmaze I think there's the same issue for the space bar as well. If a mail is open it selects the checkbox for it, or does nothing.

I wonder if it would be possible to just prevent the key events from propagating beyond the input or disable shortcuts/commands while the input is focused.

**Comment by the-djmaze** [comment]
@terribleplan thanks for finding that one.

I know these bugs suck, but eventually we get there the right way :)
