### ISSUE TITLE
Support for custom login/logout url

### ISSUE THREAD

**Issue by Diman0** [the-djmaze/snappymail#278]
I'm looking into migrating from Rainloop to SnappyMail.

Currently we use Rainloop with sso. It is documented here
https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example

In Applications.ini we set a custom login and logout link
https://github.com/Mailu/Mailu/blob/fe7397bedf2dd3d611f9f2837a1253133aa0b4f2/webmails/rainloop/defaults/application.ini#L11
```
custom_login_link='sso.php'
custom_logout_link='/sso/logout'
```
This functionality appears to be missing in SnappyMail. I could not locate it in https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/RainLoop/Config/Application.php. Is there an alternative for this in Snappymail?

I already found out that GetUserSsoHash is renamed to CreateUserSsoHash in SnappyMail. This functionality works as expected. I only miss how to configure a custom login/logout page in SnappyMail.

**Comment by the-djmaze** [comment]
Solved. Also the example should be different. Like:
```php
<?php

// Enable SnappyMail Api and include index file
$_ENV['SNAPPYMAIL_INCLUDE_AS_API'] = true;
require 'index.php';

//
// Get sso hash
//
// @param string $email
// @param string $password
// @return string
//
$ssoHash = \RainLoop\Api::CreateUserSsoHash('user@yourdomain.com', 'password');

// redirect to webmail sso url
\header('Location: https://yourdomain.com/?sso&hash='.$ssoHash);
```

**Comment by the-djmaze** [comment]
P.S. Why the change?
https://github.com/Mailu/Mailu/pull/1796#issuecomment-967133128 was closed after i made several attempts to integrate it (but i failed).

**Comment by Diman0** [comment]
Due to maintenance overhead we only wanted 2 webmails at maximum. 
Recently it came to light (at least for us), that Rainloop has multiple security related bugs that have not been fixed for a long time. For this reason we are replacing Rainloop with something else.

SnappyMail is more focused on addressing security issues. It is also very similar to Rainloop. For this reason we are looking into replacing Rainloop with SnappyMail.

**Comment by the-djmaze** [comment]
> Recently it came to light (at least for us), that Rainloop has multiple security related bugs that have not been fixed for a long time.

I understand. That's why i forked RainLoop.

> SnappyMail is more focused on addressing security issues. It is also very similar to Rainloop. For this reason we are looking into replacing Rainloop with SnappyMail.

I understand, but under the hood a lot is changing (and not only security).
So if you have more issues or questions, just create a new issue.

For now you can test this issue in v2.13.4
https://github.com/the-djmaze/snappymail/releases/tag/v2.13.4

**Comment by Diman0** [comment]
It is working brilliantly! I will close the issue.
