### ISSUE TITLE
Replying to a mail looses empty lines

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#28]
**RainLoop version, browser, OS:**
latest SnappyMail (https://snappymail.eu/demo/), Windows 10, Google Chrome 86.0.4240.111 (64-bit)

**Expected behavior and actual behavior:**
1) Reply to a mail
2) The existing mail looses all empty lines

Empty lines should not get lost. The formatting should be kept as good as possible.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
**_Original text:_**
Welcome,

this is the demo inbox of SnappyMail.eu
You can view this message in the SnappyMail and RainLoop demo's.

Best regards,

SnappyMail

**_Replied text:_**
Welcome,
this is the demo inbox of SnappyMail.eu
You can view this message in the SnappyMail and RainLoop demo's.
Best regards,
SnappyMail

**Comment by the-djmaze** [comment]
I see!
This doesn't happen in Firefox.

Look at the source, Chrome removes the <br> that is in the "empty-line" <div>.
This bug could be caused by the solution of https://github.com/the-djmaze/snappymail/issues/12
Will look what is happening here.
