### ISSUE TITLE
2.13.4: code copied-pasted removed from drafts

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#283]
**Describe the bug**
If I copy paste text that will be interpreted as code (for instance: source headers of a mail) and save the mail as draft, when I reopen the draft, the pasted text is missing, there is only pre pre in place.  

**To Reproduce**
1.  copy headers from a mail in view source
2. write new mail, past headers, save as draft
3. open draft

**Desktop (please complete the following information):**
 - Browser  firefox 96.0.3
 - SnappyMail Version 2.13.4

**Comment by the-djmaze** [comment]
The real issue was the removal of line endings when sending HTML.
Then the javascript cleanHTML.

Fixed both
