### ISSUE TITLE
Another issue with Amazon Emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#286]
You can see the issue in the attached screenshot. I am also attaching the redacted email.

![image](https://user-images.githubusercontent.com/6194332/158613427-8a5a0ba7-4bf7-4c27-8d01-67c2a05d3273.png)
[Re：Product details inquiry from Amazon customer Bryan Kirk.txt](https://github.com/the-djmaze/snappymail/files/8263144/Re.Product.details.inquiry.from.Amazon.customer.Bryan.Kirk.txt)

**Comment by the-djmaze** [comment]
This is solved with #283
The issue was incorrect parsing of `<pre>` elements.
