### ISSUE TITLE
Identities - default account change not saved

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#287]
When changing the default account on an email address with multiple entities, the change is only temporarely effective, but not kept after you change email address you are logged into [top right drop down], or log out and log back in of the application.

![Screenshot 2022-03-17 at 09 14 39](https://user-images.githubusercontent.com/35845319/158778299-2ceaa856-630b-4683-a7bf-479d67340d94.jpg)

**Comment by the-djmaze** [comment]
Works here as expected.

Which version are you using?
