### ISSUE TITLE
Support for SMTP BURL extension (RFC 4468)

### ISSUE THREAD

**Issue by jonmoesli** [the-djmaze/snappymail#288]
Dovecot 2.3 supports BURL/URLAUTH. It'd nice a nice addition!

**Comment by the-djmaze** [comment]
https://datatracker.ietf.org/doc/html/rfc4467
https://datatracker.ietf.org/doc/html/rfc4468

**Comment by the-djmaze** [comment]
This will not be worked on. It has not meaningful purpose
