### ISSUE TITLE
Built-in spam filtering

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#289]
It would be nice if it offered that or had ways to easily integrate with the popular spam filters.

**Comment by the-djmaze** [comment]
It does integrate, but that depends on server configuration.

For example: you move message from INBOX to Spam.
A correct configured Dovecot could report it to Rspamd and then Rspamd learns from it.
Same in reverse for "not spam"

**Comment by Zero3K** [comment]
What about a way that works under Windows?

**Comment by the-djmaze** [comment]
> What about a way that works under Windows?

Hmailserver?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Spam-or-Virus
