### ISSUE TITLE
Space to select emails does not work

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#29]
**SnappyMail version, browser, OS:**
SnappyMail 2.0.0-rc2
Firefox 81.0.1
Windows 10 x64 2004

**Expected behavior and actual behavior:**
I can select multiple emails with the mouse (I have checkboxes enabled) and then for instance delete all selected emails. I used to be able to do this in RainLoop with the cursor keys and the space bar, but not with SnappyMail.

**Steps to reproduce the problem:**
Enable "Display checkboxes in list" in settings. Use arrow keys to navigate email list, use space to select email. But that does not work.

**Logs or screenshots:**

**Comment by the-djmaze** [comment]
Tested on GNU/Linux with Chromium 84.0.4147.89, Firefox 83.0b5 and Firefox 56.0.2 it works with latest development source.
Will make an RC3 ;)

**Comment by phsc84** [comment]
Works perfectly fine in Google Chrome Version 86.0.4240.111 (64-bit) on Windows 10.

**Comment by ervee** [comment]
Yes it works in rc3!
