### ISSUE TITLE
Add old video-on-login-screen Rainloop plugin

### ISSUE THREAD

**Issue by TheGor1lla** [the-djmaze/snappymail#290]
Thank you for the work on getting a better Rainloop. Is there a chance this plugin

https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/video-on-login-screen

will be supported later or a reason not to?

**Comment by the-djmaze** [comment]
The problem with the plugin is the current Content Security Policy.
And a second issue is the size of a video for mobile visitors.
The third is the obsolote support for jQuery.

So, if you want it, you have to write a plugin that accomodates the issues.
Can you do it yourself?

**Comment by TheGor1lla** [comment]
I'm not well versed with JS/JQ, but I might find some time to work into it.
