### ISSUE TITLE
String replace before output to client

### ISSUE THREAD

**Issue by chrisrex** [the-djmaze/snappymail#291]
Hi,
how can I replace several strings before everything is output to the client?
for example I want to mark all **[String 1]** with `<span style="background-color:yellow;">[String 1]</span>`
like a kind of output filter
In which file of snappymail can I change something to do this?
Best regards
Christoph

**Comment by the-djmaze** [comment]
You could write a plugin that hooks to `filter.result-message` and modify the HTML.
This will not work for plain-text messages.

**Comment by chrisrex** [comment]
thank you for your answer.
Best regards
Christoph

**Comment by chrisrex** [comment]
Where can I find documentation on how to create plugins. Where exactly is the plugin saved?

**Comment by the-djmaze** [comment]
You can start here: https://github.com/the-djmaze/snappymail/tree/master/plugins

They are stored in your `/_data_/_default_/plugins` directory

**Comment by chrisrex** [comment]
Thank you for your answer.
