### ISSUE TITLE
Size filter for mailbox search not working for M sizes

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#295]
**Describe the bug**
When searching mailbox using filter `size=2M` to get messages larger than 2MB, we appear to get results for messages larger than 2KB instead.

**To Reproduce**
1. Go to a mailbox with messages greater than 2MB in size
2. Search the mailbox for `size=2M`
3. Notice that search results show messages that are smaller than 2M

Note: if you do a search like 10M you'll get a better indicator that it's showing results for 10K instead. Or at least I'm fairly certain that's the case.

**Expected behavior**
The mailbox search results in messages >= the size entered.

**Desktop (please complete the following information):**
- Browser: Firefox 98.0.1 on macOS 12.3
- SnappyMail Version 2.13.4

Solution: in SearchCriterias.php, modify line 319 from:

```
318                         case 'M':
319                                 $iResult *= 1024;
```

To:
 ```
318                         case 'M':
319                                 $iResult *= 1048576; //1024*1024
```

**Related UI Complication**
Threaded message results show the total size of what appears to be the *latest* message in the thread, yet if any message in that thread matches the search criteria, the search results will include it (which is good). This often results in a search result indicating a message size of some much smaller value like 300KiB after searching for a larger value like 3M. Once you click through to the thread, you can easily find the correct message.

A possible solution to this would be to hide the message size from the mailbox list view for threaded messages until you click on the threaded message count to see the list of messages in the thread.

**Comment by the-djmaze** [comment]
Your solution is incorrect.
```
			case 'K':
				$iResult *= 1024;
			case 'M':
				$iResult *= 1024;
```
As you can see it's a fall-through and should already multiply twice.
But the order is incorrect, it should be 
```
			case 'M':
				$iResult *= 1024;
			case 'K':
				$iResult *= 1024;
```

**Comment by jas8522** [comment]
Oh, any comments on the threaded message size display? It seemed a bit confusing to me to see sizes in the results that were less than my specified minimum size until I realized why. I'm not sure all users would come to that same realization.

**Comment by the-djmaze** [comment]
I don't like the current threads view, it's too misleading when you don't see the small box with number.

A tree view would be nicer (but not possible yet).
