### ISSUE TITLE
Documentation : Add the process to remove the very old versions when upgrading

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#297]
The upgrade process works very well.
But I found today that I kept 12 versions in snappymail/v/ directory.
It can be cool to explain in the documentation how we can remove the very old ones. Is it sufficient to only remove the very old directory ? Is there something else to be done ?

**Comment by the-djmaze** [comment]
Added to the documentation at

https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#upgrade
as:

`When the everything works, you may remove any old version that resides in /snappymail/v/.`
