### ISSUE TITLE
 Wrong language in non primary account

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#299]
**Describe the bug**
Selected language works only for primary account. English will be used for non primary account.

**To Reproduce**
1. Go to settings
2. Set language to "Deutsch"
3. switch to other account

**Expected behavior**
other accounts will be use German as Language

**Desktop (please complete the following information):**
 - SnappyMail Version2.14.0

**Comment by Parodontitis** [comment]
OK. I have to set the language to each account separately. Even if the settings suggest that "Deutsch" is already selected, you have to select an another language and then switch back to "Deutsch". Then "Deutsch" remains as selected language for the account.

**Comment by the-djmaze** [comment]
Reopen because it is an issue caused by solution for #287
RainLoop had a strange mix of class instances to do the same, but on different locations.
