### ISSUE TITLE
Contacts error

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#30]
**RainLoop version, browser, OS:**
SnappyMail 2.0.0-rc3, Version 86.0.4240.111 (64-Bit), Windows 10

**Expected behavior and actual behavior:**
Click on the contacts icon. It should open the contacts window, where you can sync or add your contacts. But nothing happens (see log below).
![image](https://user-images.githubusercontent.com/2138442/97629263-24042000-1a2e-11eb-8429-0f993ac40c13.png)

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
UtilsUser.js:366 Uncaught TypeError: koPageCount is not a function
    at UtilsUser.js:366
    at Function.xc (libs.js:1204)
    at Function.yc (libs.js:1203)
    at Function.U (libs.js:1203)
    at Object.a.i (libs.js:1200)
    at ko.js:272
    at Array.forEach (<anonymous>)
    at Object.ko.addComputablesTo (ko.js:272)
    at ContactsPopupView.addComputables (AbstractViewNext.js:65)
    at new ContactsPopupView (Contacts.js:123)

**Comment by phsc84** [comment]
The funny thing is, that the synchronisation seems to work in the background, because SnappyMail magically knows all my email contacts.
Does this mean, that #24 is resolved?

**Comment by the-djmaze** [comment]
I've setup a snappymail with contacts to test this.
Damn, my memory management improvements killed the Contacts view completely.
It took me a view hours to find out why that screen has so much trouble.
For now i made improvements, but had to drop some memory improvements 
It could be possible that memory leaks are present now.

#24 should always have worked (as i mentioned a small commit change there).
However, it could be possible the memory garbage collector fixed it and it's now broken again.

I've recompiled the code so you can check
https://github.com/the-djmaze/snappymail/releases/tag/v2.0.0-rc3

**Comment by phsc84** [comment]
Now it works perfectly fine. Thanks!

**Comment by ervee** [comment]
Works for me in rc3 too.
