### ISSUE TITLE
PDF file opening in SnappyMail window

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#301]
SnappyMail 2.14.1 + Firefox 98.0.1

When clicking on an attached .pdf file, the file opens on the same window SnappyMail is loaded.
I presume the same would happen with other files, if e.g. you have .jpeg files to be opened by the browser
[in my case I get the pop up window asking me where i want to save the file, that is correct].
Ideally we should have the file opening in a new tab in any situation where the broweser is the default application handling that type of file.

**Comment by the-djmaze** [comment]
In Firefox i get a popup that has 3 options:
1. Open with Firefox
2. Open with...
3. Save

It could be my browser configuration. But if you give more details, we might solve this.

**Comment by ivnmad** [comment]
That is because you have "Always ask" in your Firefox preferences for PDF files [see first screenshot below].
In my case I have "Open in Firefox", and that is why instead of getting the popup, the file is automatically opened when clicking on it [see second screenshot below - showing file in SnappyMail].
When on other websites/applications accessed via Firefox, the file is opened in a separate tab when clicked on, but with SnappyMail it opens in the same window.
I presume there might be a way to tell Firefox [or any other browser] to open the file in a different tab.
You could have other files where the "Open in Firefox" is selected [e.g. image files], so it could be useful for other people too and we shouldn't limit the functionality to just PDF files.

![Screenshot 2022-03-23 at 10 41 14](https://user-images.githubusercontent.com/35845319/159681736-c6eddd11-664a-44b2-bc81-232d6f89b46c.jpg)

![Screenshot 2022-03-23 at 10 41 52](https://user-images.githubusercontent.com/35845319/159682449-8003c963-1c96-43db-b0b7-c9b38fc0e2ff.jpg)

**Comment by the-djmaze** [comment]
> That is because you have "Always ask" in your Firefox preferences for PDF files [see first screenshot below].

Nope, i have the same setting as you for PDF

**Comment by ivnmad** [comment]
I'm testing on desktop, not mobile..

I've just tested it on another computer, still with Firefox, and same behaviour.
As soon as I click on the file name, the file opens in the same window, because of the "Open in Firefox" setting.

I also tested with Google Chrome, and in this case if I click on the name of the file, Chrome downloads the file, but when I go over the file name, and "eye" icon appears, and if I click on that icon the file opens in the browser in a seperate tab. 
No "eye" icon is visible in Firefox.

![Screenshot 2022-03-23 at 13 08 12](https://user-images.githubusercontent.com/35845319/159708076-0b56ebd3-7984-4779-bdc7-a59f42887a89.jpg)

I did try to change the setting in Firefox to "Always ask" and if I click on the file, I get the usual popup asking what to do with the file, so not sure why you are getting the popup with "Open in Firefox" as a setting:

![Screenshot 2022-03-23 at 13 16 00](https://user-images.githubusercontent.com/35845319/159708537-2dedc974-8262-4f92-982a-2528ba0df037.jpg)

**Comment by the-djmaze** [comment]
Firefox 98 did a big change in the downloads management/handling.
I will check if i'm still on <98 if that might cause it.

**Comment by ivnmad** [comment]
FYI, my earlier tests had been run on MacOS and Windows, and I got the same results with both operating systems.
I've just done a test on Linux, and everything works fine with Chrome [as in MacOS and Windows), but with Firefox I get a popup asking me where to save the file, even if have  "Open in Firefox" as a setting.

I tried to click on a PDF file from another website, and it opened in Firefox in a separate tab, as expected.
I had done the same test on MacOS and Windows, and the file opened in Firefox in a separate tab too.

**Comment by ivnmad** [comment]
I run one more test with a JPEG image [I hadn't had a chance to do it earlier].
Images do get an "eye" icon, and if you click on them, they open in a separate window.
If you click on the file name, Firefox asks you where you want to save it.
That is the behaviour we would expect [that is what we get in Google Chrome for both PDF and JPEG].

![Screenshot 2022-03-24 at 08 47 27](https://user-images.githubusercontent.com/35845319/159878709-7e2dfe8c-80a9-4f55-98e5-4d94ec0aee25.jpg)

The issue seems to be only with PDF files

.

**Comment by the-djmaze** [comment]
I just updated my Firefox from 97 to 98 and now have the same issue!
So it's definitely something Firefox screwed up with the new download manager in 98

**Comment by the-djmaze** [comment]
After some testing i found a workaround to open it in a new tab/window.
It's not the best solution, but better then nothing.

**Comment by ivnmad** [comment]
Great, thank you for that.
I've set Firefox to "Alwasy ask" for the time being, since when you select "Open with Firefox" in that window, it does open the file in a separate tab. I will test your workaround as soon as you push the next release.
