### ISSUE TITLE
Upgrade Sabre/VObject

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#304]
SnappyMail still uses Sabre/VObject 3.1.3, which dates back to 2013:
https://github.com/sabre-io/vobject/blob/master/CHANGELOG.md#313-2013-10-02

For security and compatibility reasons, Sabre/VObject should be upgraded to the current version.
https://github.com/sabre-io/vobject/releases

**Comment by the-djmaze** [comment]
Not tested, but it might work in https://github.com/the-djmaze/snappymail/releases/tag/v2.14.2

**Comment by phsc84** [comment]
Works perfectly in SnappyMail 2.14.3. Thank you!
