### ISSUE TITLE
inline images are suddenly no longer displayed

### ISSUE THREAD

**Issue by chrisrex** [the-djmaze/snappymail#305]
hi,
Received emails that have an embedded image are displayed when first opened. Everything is fine there. For example, if I want to look at this e-mail again the next day, the embedded image is no longer displayed.
When I look at the same email in another email program, I can see the embedded image.
What does not work with the embedded images?

It may have something to do with this setting: **Use threads**
If I activate this option, the embedded images are displayed for some emails. If I deactivate this option, then other embedded images are displayed again. But I can't get all embedded images to be displayed.

Best regards
Christoph

**Comment by the-djmaze** [comment]
What are the errors in you browser console?

**Comment by the-djmaze** [comment]
Sorry, I ment the network requests log in the console.
Could you check that one?

**Comment by chrisrex** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/66015535/161948225-bfe166ab-eb95-4259-9945-fe082b232adf.png)

**Comment by the-djmaze** [comment]
Yes. but i don't see any image requests in there.
This means that it seems there are no images in the messages you view.

**Comment by chrisrex** [comment]
I have send a new email to me and it looks like this
![image](https://user-images.githubusercontent.com/66015535/161955422-6d658b54-fc7e-4eac-b36e-8d3837d30f8b.png)
I can see the Image. But when I look the next day, the image is gone.

My first screenshot shows an email with broken embedded images links

**Comment by jas8522** [comment]
I have a user experiencing this as well. the URLs look like this for the image requests:
```
?/Raw/&q[]=/0/View/&q[]=/c29kaXVt.QvogSkw38jw4u86TjFNqHLFqbljlA9cz.eB9CDNaaHjBW61zIcW8daAJng4ryJlbGFCUDewdQDdHAAskgDc4uz31qTAVRQW-9p334k3QIUR1Zx2uIkiiuc-s3f0j_AKSBjjV3Mnz-vcsRy1R5Z74Sr1inzP3SyOpIsoAPWcGf5uV0mjqd8uOIHBjHDlQrTrXAo0YnD3QkLT134ybZNeHXxPoxrQEJDY3UebfsKKCjYeMZw_yt9DNgTZf81gRd4EgetVD9LcqurDQG-gWYM_xRSyjY5K918WA0loegvcGXH9B9IDu4
```
The HTTP status code is 200, but the file size is 0b.

Web server logs see the same, where it thinks all is fine:

```
  | GET   /?/Raw/&q[]=/0/View/&q[]=/c29kaXVt.WltnkHo1Ml6yPpPmcYmnw948G8mgM9Gd.CaCImOS97LjdkArqbRQnUxfRAoxHKc3l_qzRw_sqeQqWe_JLK0USA6FwBrQQyykqtHBZe8Bvz5UVnqttd0gwAmUFnsB8h4msT7WLImbFMSgvietHK3sPDvCKUbZfD53JDMQ897xkfIf820BH3Vr7Wy-QYuCY8bQhGpN31-rIXXbH-5vXV3uTY-emPgE9IWV6c3ihU8BUinyA1gOFskIt_P_X26kCrEQl36DvNODZAyzLK0xXiucR-m1xjzmV0Xf6IMYSRNHdWE7SM_KG  HTTP/1.0
-- | --
```

Snappymail logs show this:

```
INFO[NOTICE]: improper image header `/tmp/magick-33481CmAbHxW8mwC' @ error/png.c/ReadPNGImage/4104
```

Contrary to @chrisrex last comment, this has been reproduced on Firefox 99.0.1 macOS 12.3.1 with SnappyMail 2.14.3.

I compiled the latest dev version and updated to that, no difference.

If I use the option to download the message as .eml file, then open that on my computer, it display the image fine.

Seems like perhaps the ImageMagick processing is the issue?

**Comment by the-djmaze** [comment]
I've made some changes to detect issues.

However, does it solve when `detect_image_exif_orientation` is off in the application.ini?

**Comment by jas8522** [comment]
> However, does it solve when detect_image_exif_orientation is off in the application.ini?

Yup! Having that turned off, clearing browser cache, results in the images displaying.

**Comment by the-djmaze** [comment]
RainLoop has that on by default.
When i discovered that, i turned it off by default.
But everyone who updates still has it turned on.

The feature is nice to have, but why overload the server when it's 99% not needed?

I shall rethink the feature and maybe remove it.

**Comment by jas8522** [comment]
I've added this to the [RainLoop upgrade instructions](https://github.com/the-djmaze/snappymail/wiki/Installation-instructions).

I'm thinking if the setting is off by default for new installs, and now RainLoop upgrades will be directed to turn that setting off, plus those that find this issue can reference the workaround, perhaps this is all that's necessary for now. 

And yeah you can always remove it or re-write it later, but I doubt that many people are going to care if image orientation isn't right; they can always download the image and rotate it themselves.

**Comment by the-djmaze** [comment]
> I doubt that many people are going to care if image orientation isn't right; they can always download the image and rotate it themselves.

Right, that was my thinking for removing it :)

**Comment by the-djmaze** [comment]
Renamed `detect_image_exif_orientation` to `image_exif_auto_rotate`.
This way it will always be off by default, at first.
Also it will only work for JPEG (i've disabled PNG and WEBP)
