### ISSUE TITLE
How to add a javascript library in snappy

### ISSUE THREAD

**Issue by Siopsec** [the-djmaze/snappymail#307]
Hi,

I have a project to add a filepicker linked to Nextcloud. 

https://www.npmjs.com/package/nextcloud-webdav-filepicker

I can't add the library in my code. I installed the library which is available in /node_modules/nextcloud-webdav-filepicker/js/filePickerWrapper.js but I don't know how to make it available in PopupCompose.html (\snappymail-master\snappymail\v\0.0.0\appapplicationtemplates\Views\User\PopupsCompose.html)

Do you have any ideas? 

Thanks

**Comment by the-djmaze** [comment]
Take a look at https://github.com/the-djmaze/snappymail/blob/master/plugins/login-oauth2/LoginOAuth2.js
You see there's a hook, when a view is created, so that you can inject your own features.
In this case you want the `PopupsCompose`.

Then you can load anything you want into it.
