### ISSUE TITLE
admin password file (as described in your manual) does not exist in current release version 2.14.1

### ISSUE THREAD

**Issue by jayjupdhig** [the-djmaze/snappymail#310]
![image](https://user-images.githubusercontent.com/42765391/160613541-2e8125e8-e259-4abd-9c8f-e5075dbc77fd.png)

Why and how to solve...?

**Comment by jayjupdhig** [comment]
Got it from HERE: https://github.com/the-djmaze/snappymail/wiki/Installation-instructions

**Comment by jayjupdhig** [comment]
And when i upload it to mymail.mydomain.com , i just get a message '[105] Missing version directory'... 

Why?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#admin-password

**Comment by jayjupdhig** [comment]
Now it seems to work, maybe plesk was not 100% finished with creating mymail.mydomain.com or something like that...? 

![image](https://user-images.githubusercontent.com/42765391/160807036-175a7ad0-70fe-46e5-8c4b-f024bba1fcb0.png)

**Comment by jayjupdhig** [comment]
Problem solved, thx.
