### ISSUE TITLE
Reading 'bootstart'

### ISSUE THREAD

**Issue by voigtman** [the-djmaze/snappymail#314]
### **Describe the bug**
I am 99% sure this is me doing something wrong.
I am trying to use snappymail with OpenLightSpeed (& CyberPanel) [Freshly installed].

If I'm successful I will be doing this to another established server
I have multiple domains hosted on my machine, so I thought I could install snappymail in a mail subdirectory for each domain. How terribly unsafe is this?

**Currently**: when I navigate to snappymail after this fresh install I see a blank grey page displaying:
_An error occurred.
Please refresh the page and try again. Cannot read properties of undefined (reading 'bootstart')_

### **To Reproduce**
1. Ask a total dufus to install snappymail on a cyberpanel machine with multiple domains
2. laugh at their failure
3. Make them go to snappymail github and beg for mercy and help from experts

### **Expected behavior**
I hoped it would show me something more useful... I searched google and through the various files and directories for a clue and found nothing to help me.

### **Desktop (please complete the following information):**
 - Browser: Chrome, Version 100.0.4896.60 (Official Build) (x86_64)
 - SnappyMail Version: 2.14.1

### **Additional context**
 - installed on machine using Cyberpanel + openlightspeed
 - installed in subdirectory (mail.domain.com)
 - php 7.4
 - Ubuntu 20.04.4 LTS

**Comment by the-djmaze** [comment]
Please try with https://github.com/the-djmaze/snappymail/releases/tag/v2.14.2
