### ISSUE TITLE
2.14.2 no login page

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#316]
Just upgrated from 2.14.1 to 2.14.2, but SnappyMail gets stuck here:

![Screenshot 2022-04-05 at 10 19 25](https://user-images.githubusercontent.com/35845319/161722697-4a8d5acc-1f43-49cb-bdfb-853c05908096.jpg)

Same issue if I try to access the "admin" login page.
Everything works fine as soon as I revert back to ﻿2.14.1

**Comment by PeopleInside** [comment]
Same for me version 2.14.2 is broken.
Is not loading, I'm reverting back also to 2.14.1

**Comment by the-djmaze** [comment]
Yes i noticed. Working on it!
Somehow my test failed due to a change for #314

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.14.3
