### ISSUE TITLE
Autoupdater from admin interface

### ISSUE THREAD

**Issue by derStephan** [the-djmaze/snappymail#318]
**Is your feature request related to a problem? Please describe.**
Keeping up with the pace of releases is hard for me, especially as the updates involve multiple manual steps. 

**Describe the solution you'd like**
A button in Admin backend to automatically download automatically the current version to the server, unpack it on the server und deploy the new files. 

**Describe alternatives you've considered**
none

**Additional context**
There was such functionality in rainloop. I am willig to do some coding myself but I have no clue where to start.

**Comment by the-djmaze** [comment]
I've added some base draft code in PHP as a start for this.
It also has a backup feature to backup the `_data_` folder

**Comment by the-djmaze** [comment]
It's not working yet. It's draft code that i'm working on

**Comment by derStephan** [comment]
Wow, you are quick!! Thanks a lot.

**Comment by the-djmaze** [comment]
You're welcome.
It's easy these days with https://www.php.net/phardata

And can be extended in the future with OpenSSL signatures.
You can read info here https://dragonflycms.org/Wiki/id=153.html
