### ISSUE TITLE
Add option for Calendar, Tasklist and File storage integration.

### ISSUE THREAD

**Issue by c11a** [the-djmaze/snappymail#319]
**Is your feature request related to a problem? Please describe.**

Add an option (plugin?) for Calendar, Tasklist and File storage integration, 
Like it is now in Afterlogic WebMail Pro PHP see: https://afterlogic.com/images/products/wmp8/screens/message-list.png

Does anybody have a suggestion?

**Comment by the-djmaze** [comment]
Read #152

**Comment by the-djmaze** [comment]
Integration with Nextcloud is now possible.
