### ISSUE TITLE
2.14.3: spam score item visible but no color

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#320]
**Describe the bug**
reading issue #162 it looks like the spam score element should be colored.

in my case no matter the spam score, it looks like this:
(version 2.14.3, rspamd headers)

![image](https://user-images.githubusercontent.com/1160681/162594433-8fea4663-29e9-4c9a-aab3-aaa00e4007c1.png)
in this case with such headers:

```
X-Spam-Score: 12.7
X-Spam-Status: Yes
X-Spam-Bar: ++++++++++++

```
It looks it it correctly identify the relevant headers, as it does not show the spam score item when the score is actually negative. But I was under the impression that it would be a visual indicator similar to spam bar.

Or it is expecting SpamAssassin headers with score=XX required=XX fields?

Regards,

**Comment by the-djmaze** [comment]
> Or it is expecting SpamAssassin headers with score=XX required=XX fields?

Correct, else it doesn't know the amount of points to reach the `100% definitely spam` mark.

I made a small change to at least have it 100% when `IsSpam` is `true`
