### ISSUE TITLE
Unable to attach docx files using WebKit browsers on Windows

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#322]
**Describe the bug**
When attaching docx files to a new message, if using any WebKit browser on Windows only (works fine on Mac and Linux), they never attach. There's no console logging in the browser, and the web inspector's Network tab shows no ajax activity when attempting to attach a docx file. 

PDFs and images attach fine with this request being successful:

```
{
    "Action": "Upload",
    "Result": {
        "Attachment": {
            "Name": "Sponsorship_Package.pdf",
            "TempName": "upload-post-42d0a644baa21fb4d719d1ad71f52572",
            "MimeType": "application/pdf",
            "Size": 821608
        }
    }
}
```

But no such request appears at all when trying a docx file. Seems like maybe javascript is blocking it prior to even attempting the attach. 

This has been reproduced on Windows 11 for sure, and I think Win 10 (it's a user that's hard to get information from).

**To Reproduce**
1. On a Win 11 machine, log into snappy using Edge, Chrome, or Opera
2. Create a new message
3. Attempt to attach a .docx file, or .doc file (both extensions were tested and confirmed not working).
4. It will get as far as opening the Windows File Explorer and allowing you to select the file, but after you select, you're returned to the new message editor with no file attached. It's as if the attachment attempt never happened.

**Expected behavior**
.docx files are attached to the message.

**Desktop (please complete the following information):**
 - Windows 11 with Chrome, Opera, or Edge (latest release of each; they were freshly downloaded/installed for testing).
 - SnappyMail Version 2.14.3. Originally reproduced on 2.14.1, then updated to see if issue still exists - it does.
 
**Additional**
We tried attaching a .txt file and it was successful. We then renamed the file to .doc and then tried .docx and neither were successfully attached.

**Comment by the-djmaze** [comment]
This is very strange. Nothing in SnappyMail should prevent this.
Maybe an anti-virus system that prevents this?

When you save the doc/docx as odt (openoffice format), does that work?

I only have an old laptop laying around with a bare old Windows 10 that i could boot for testing.
But i don't think that would be of any use as nobody reported it before.

Another test:
1. Select file in a File Explorer
2. Drag it into the browser window
3. Check if it is uploaded


Another test (next release, as i found bug in Jua uploader):
1. Hit the "add attachment" button in compose window
2. Select multiple files in the File Explorer popup (.docx and .txt)
3. Check if the .txt does upload

**Comment by the-djmaze** [comment]
Ok, i will try with a VM from https://developer.microsoft.com/nl-nl/windows/downloads/virtual-machines/

**Comment by the-djmaze** [comment]
Found it!

`type` is empty.
![afbeelding](https://user-images.githubusercontent.com/3752035/163275040-e6544bf6-6135-4330-b7f0-55977d5ebe61.png)
