### ISSUE TITLE
ExternalProxy not displaying certain images.

### ISSUE THREAD

**Issue by mandusm** [the-djmaze/snappymail#326]
**Describe the bug**
When I have "use local proxy for images" enabled, some images do not display. 

**To Reproduce**
1. Go to 'Inbox'
2. Click on 'any email'
3. See unloaded images.

**Expected behavior**
Expecting proxy to load images.

**Screenshots**

**Desktop (please complete the following information):**
- Snappy Version 2.14.3
 - All Browsers. Confirmed on Edge and Firefox.

**Mobile (please complete the following information):**
not tested on mobile, but since this is a php error, I am sure it will be the same. 

**Additional context**
This is strange because images from that same domain, in the same email displays, but two of them don't. It looks like this might be a type mismatch thing. I don't think the proxy handles the png/gif redirect change very well.

```
Fatal error: Uncaught RuntimeException: Error 3: for http://mi.onepeloton.com/p/rp/5bb5a16e5e3a9d8d.png?mi_instructor1=Sam Yo&mi_instructor2=Bradley Rose&mi_instructor3=&mi_location=US&instructor= in /web/rainloop/snappymail/v/2.14.3/app/libraries/snappymail/http/request/curl.php:88 Stack trace: #0 /web/rainloop/snappymail/v/2.14.3/app/libraries/snappymail/http/request.php(133): SnappyMail\HTTP\Request\CURL->__doRequest('GET', 'http://mi.onepe...', NULL, Array) #1 /web/rainloop/snappymail/v/2.14.3/app/libraries/RainLoop/ServiceActions.php(355): SnappyMail\HTTP\Request->doRequest('GET', 'http://mi.onepe...') #2 /web/rainloop/snappymail/v/2.14.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceProxyExternal('') #3 /web/rainloop/snappymail/v/2.14.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult() #4 /web/rainloop/snappymail/v/2.14.3/include.php(169): RainLoop\Service::Handle() #5 /web/rainloop/index.php(11): include('/web/rainloop/s...') #6 {main} thrown in /web/rainloop/snappymail/v/2.14.3/app/libraries/snappymail/http/request/curl.php on line 88
```

I have been researching this issue and I believe it's related to https://github.com/the-djmaze/snappymail/issues/16

**Comment by mandusm** [comment]
Ahh, okay. Looking into the code and understanding the error better. 
We are reporting a CURL Error 3 here. 

We are making the `https://curl.se/libcurl/c/CURLINFO_RESPONSE_CODE.html` call to get the response code, but because the URL is malformed, we are getting an exception 3. https://curl.se/libcurl/c/libcurl-errors.html

Looking at the request URL it's clearly not url encoded. Will see if can make the changes myself then do a pull request.

**Comment by the-djmaze** [comment]
> * SnappyMail Version [e.g. 2.3.4]

Could you try with 2.14.3?
https://github.com/the-djmaze/snappymail/releases/tag/v2.14.3

**Comment by mandusm** [comment]
Oh, this is my fault. I missed updating the versions in the ticket. I am on 2.14.3

**Comment by mandusm** [comment]
Also, Just for more clarity. The images that are trying to be resolved and failing are being redirected. 

Original URL: `http://mi.onepeloton.com/p/rp/5bb5a16e5e3a9d8d.png?mi_instructor1=Sam%20Yo&mi_instructor2=Bradley%20Rose&mi_instructor3=&mi_location=US&instructor`

This returns the following relevant location header:
```
Location: //assets.movableink-templates.com/6909/60e3ed1a-b2b6-4065-8c9f-740771757fc8/85e4a7d2-91b8-4112-9455-a2f60cdbf0d1.gif?mi_instructor1=Sam%20Yo&mi_instructor2=Bradley%20Rose&mi_instructor3=&mi_location=US&instructor=

**Comment by the-djmaze** [comment]
I made some changes, you can try with https://github.com/the-djmaze/snappymail/releases/tag/v2.15.0

**Comment by mandusm** [comment]
Brilliant. 2.15.0 Solved this. 
Thank you!

**Comment by the-djmaze** [comment]
Your welcome!
