### ISSUE TITLE
GnuPG section doesn't refresh after adding a key

### ISSUE THREAD

**Issue by fs1** [the-djmaze/snappymail#327]
**Describe the bug**
When adding a key in the Security/OpenPGP tab, the key will show up immediately in the OpenPGP.js section but not in the GnuPG section. You have to reload the website (e.g., using Ctrl + R) to let the key appear in the GnuPG section .

**To Reproduce**
1. Make sure "allow OpenGPG" is activated in admin panel
2. as user: Go to 'Settings/Security'
3. Click on 'Import Key' and insert the public key
4. Make sure the box 'Store on server in GnuPG' is ticked and click import.
5. Key shows up under OpenPGP.js/Public, but not under GnuPG/Public
6. Refresh the page
7. The key is now available in both sections

**Expected behavior**
After adding a key also the GnuPG section should _reload_ in some way to show the current keyring content.

**Desktop (please complete the following information):**
 - Browser Chrome 100.0.4896.127
 - SnappyMail Version 2.14.3

**Additional context**
Follow-Up ticket from #325.

**Comment by the-djmaze** [comment]
I already fixed this for next release in the following commit:
https://github.com/the-djmaze/snappymail/commit/20e391cf1c7f6d83307ae7a7f7fbf4a83be8096b
