### ISSUE TITLE
Check signature files released

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#329]
**Describe the bug**
Where I can find public key to verify files under releases?

**To Reproduce**
```
gpg --verify-files snappymail-2.15.0.tar.gz.asc 
gpg: assuming signed data in 'snappymail-2.15.0.tar.gz'
gpg: Signature made Tue Apr 19 10:30:17 2022 CEST
gpg:                using EDDSA key 1016E47079145542F8BA133548208BA13290F3EB
gpg: Can't check signature: No public key
```

and

```
curl https://github.com/the-djmaze.gpg

-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: This user hasn't uploaded any GPG keys.


=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

TIA
Alessandro

**Comment by the-djmaze** [comment]
It's at several places:
* https://keyserver.ubuntu.com Hockeypuck OpenPGP keyserver
* https://snappymail.eu/repository/deb/48208BA13290F3EB.asc
* https://github.com/the-djmaze/snappymail/blob/master/build/SnappyMail.asc

**Comment by the-djmaze** [comment]
Added to wiki
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#gpg-verify
