### ISSUE TITLE
Sieve : removing filter : confirmation popup not seen

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#330]
**Describe the bug**
When you want to remove a sieve filter, a red confirmation popup raised to confirm the deletion. But it doesn't show anything and you must click on it to delete really the filter

**To Reproduce**
1. Go to 'Filters management'
2. Create a filter and save the result
3. Go back in 'Filters management' to see the new filter
4. Click on 'Trash' to delete it
5. You see a red part, without anything

**Expected behavior**
Should be a valid "Confirmation" box

**Desktop (please complete the following information):**
 - Browser Firefox 91.8
 - SnappyMail Version 2.15.0

**Comment by the-djmaze** [comment]
Aha! This only happens after adding.
When you close the filters screen completely (see all scripts) and then op the screen, the red button does contain text.

This is a translate issue.

**Comment by dominiquefournier** [comment]
Snappy is in French if it change something.
