### ISSUE TITLE
Disable update checker

### ISSUE THREAD

**Issue by nebulade** [the-djmaze/snappymail#337]
Hi, I am maintaining the snappymail package for [Cloudron](https://cloudron.io) and since snappy mail now has an update checker, I would like to know, if it could be disabled. We are updating the app package usually within 1 day anyways, but due to the way Cloudron handles app code, both update mechanisms will compete and we can't really test the upstream one easily. Also it is obviously not in sync with app instance backups, which allow a proper rollback, in case the update for some reason fails.

I am happy to contribute such a config flag, if I have overlooked that and if there is a chance, that it might get merged. 

For reference, this was reported by one of our users at https://forum.cloudron.io/topic/6842/disable-updater

**Comment by the-djmaze** [comment]
It was added because of #318
I already thought this would become an issue.

What solution would you like:
1. when file 'LOCKED' is in place, it's disabled?
2. application.ini entry?
3. $_ENV['NO_UPDATE'] = true?

What would be the easiest for you?

**Comment by fs1** [comment]
I'd vote for an application.ini entry.

**Comment by the-djmaze** [comment]
> I'd vote for an application.ini entry.

Added. For now the default is `Off` so you must explicitly enable the update feature.

This is an additional check, as there were already 2 checks in place:
* \is_writable('/snappymail/v')
* \is_writable('/index.php')

**Comment by nebulade** [comment]
That's fantastic, thanks for the quick fix. Given the default to be `off` we just have to publish a new package version then once a new release is tagged here and we are good. Perfect :-)
