### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by Dual-0** [the-djmaze/snappymail#338]
Hello,
when I browse through my folders I've got the an "invalid token" message.
I can reproduce this with one "big folder".

<img width="299" alt="image" src="https://user-images.githubusercontent.com/37346547/164232343-7340b98c-f2d4-402e-a017-b092986a5d82.png">

Error Message in nginx error.log
```
2022/04/20 12:30:26 [warn] 91944#91944: *1066 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000018, client: 1.2.3.4, server: webmail.webserver.tld, request: "POST /?/Json/&q[]=/0/ HTTP/2.0", host: "webmail.webserver.tld"
2022/04/20 12:30:26 [error] 91944#91944: *1066 FastCGI sent in stderr: "PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0PHP message: SERVICE WARNING: InvalidToken[101]" while reading response header from upstream, client: 1.2.3.4, server: webmail.webserver.tld, request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "webmail.webserver.tld"
2022/04/20 12:30:30 [error] 91944#91944: *1066 FastCGI sent in stderr: "PHP message: GPG DEBUG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:PHP message: GPG DEBUG: /usr/bin/gpg --status-fd 3 --command-fd 4 --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --pinentry-mode cancel --ignore-time-conflict --ignore-valid-from --homedir '/var/www/webmail/2.15.0/data/_data_/_default_/storage/mydomain.tld/myname/.gnupg' --with-colons --with-fingerprint --with-fingerprint --fixed-list-mode --list-public-keysPHP message: GPG DEBUG: BEGIN PROCESSINGPHP message: GPG DEBUG: selecting streamsPHP message: GPG DEBUG: => got 1PHP message: GPG DEBUG: GPG output stream ready for readingPHP message: GPG DEBUG: => about to read 65536 bytes from GPG outputPHP message: GPG DEBUG: => read 18 bytesPHP message: GPG DEBUG: selecting streamsPHP message: GPG DEBUG: => got 3PHP message: GPG DEBUG: GPG output stream ready for readingPHP message: GPG DEBUG: => about to read 65536 bytes from GPG outputPHP message: GPG DEBUG: => read 0 bytesPHP message: GPG DEBUG: GPG error stream ready for readingPHP message: GPG DEBUG: => about to read 65536 bytes from GPG errorPHP message: GPG DEBUG: GPG status stream ready for readingPHP message: GPG DEBUG: => about to read 65536 bytes from GPG statusPHP message: GPG DEBUG: END PROCESSINGPHP message: GPG DEBUG: CLOSING GPG SUBPROCESSPHP message: GPG DEBUG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:PHP message: GPG DEBUG: /usr/bin/gpg --status-fd 3 --command-fd 4 --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --pinentry-mode cancel --ignore-time-conflict --ignore-valid-from --homedir '/var/www/webmail/2.15.0/data/_data_/_default_/storage/mydomain.tld/myname/.gnupg' --with-colons --with-fingerprint --with-fingerprint --fixed-list-mode --list-secret-keysPHP message: GPG DEBUG: BEGIN PROCESSINGPHP message: GPG DEBUG: selecting stream
```

**Comment by mandusm** [comment]
It looks like the amount of parameters passed to the API for query in that folder exceeds your PHP installations limits.
```
max_input_vars int
How many [input variables](https://www.php.net/manual/en/language.variables.external.php) may be accepted (limit is applied to $_GET, $_POST and $_COOKIE superglobal separately). Use of this directive mitigates the possibility of denial of service attacks which use hash collisions. If there are more input variables than specified by this directive, an E_WARNING is issued, and further input variables are truncated from the request.
```

This seems to be a problem related to your PHP installation `change max_input_vars in php.ini` and you should be able to work around this temporarily by increasing that number. 

Could you also open your browsers network inspector and copy the URL request that causes this error? I am querios as to which additional parameters is being passed to hit this limit.
Usually the MessageList API Query gets passed as a single Base64 encoded string which gets decoded to something like this.
```
{
  "Offset": 0,
  "Limit": 500,
  "Search": "",
  "Sort": "",
  "Hash": "<redacted>",
  "Folder": "INBOX/Updates",
  "ThreadUid": 0,
  "UseThreads": 1
}
```

**Comment by the-djmaze** [comment]
@mandusm 
> This seems to be a problem related to your PHP installation

Although you found the correct issue, the solution isn't good.
1. it actually means the program should reduce the amount of POST variables
2. not everyone can modify php.ini

So the above commit works around this issue by posting the data JSON.
This is something which i already wanted to do anyway, as could have been seen in the commented line
```
//			init.body = JSON.stringify(Object.fromEntries(postData));
```

**Comment by mandusm** [comment]
Nice!

Yeah, agreed, needing to edit the php.ini isn't the best option. I only suggested it as a temporary workaround while the input var overflow was fixed. 

I am very impressed by your knowledge of this codebase and for being so responsive to tickets! Hope to be able to help you out with some of this in the near future! Snappy is now my daily driver webmail.

**Comment by the-djmaze** [comment]
> I am very impressed by your knowledge of this codebase

Thanks! Somehow i'm a codemachine. Give me something and 2 weeks later i know my way around.
Hack, i even made an impressive iOS app using Swift in 2 weeks with 0 knowledge.
It's just something i'm good at. Side-effect is that i can be an asshole to colleagues.

> Hope to be able to help you out with some of this in the near future!

That would be great!
My main headache is still the issues with GPG/GnuPG.

**Comment by the-djmaze** [comment]
You can try with v2.15.1
