### ISSUE TITLE
Empty admin page on first install

### ISSUE THREAD

**Issue by yannfill** [the-djmaze/snappymail#340]
**Describe the bug**
I just installed the latest version (2.15) and when I go to the /?admin page and enter admin user and password from data/\_data\_/\_default\_/admin_password.txt all I see after (apparently) successful login is the default background image. No menu, no text at all. In the log, the only request sent is
```
"POST /?admin/Json/&q[]=/0/ HTTP/2.0"
```

In the error log I got
```
FastCGI sent in stderr: "PHP message: TOKENS DEBUG: New SESSION_TOKEN" while reading response header from upstream, client: xx.xx.xx.xx, server: webmail.example.com, request: "POST /?admin/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:"
```
The error appear twice, but not after multiple tries.

If I try to login as regular user (conf copied from rainloop domains directory) I got a JS popup saying "invalid token". The error log show
```
FastCGI sent in stderr: "PHP message: SERVICE WARNING: InvalidToken[101]" while reading response header from upstream, client: xx.xx.xx.xx, server: webmail.example.com, request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:"
```
This doesn't seem related to #338 

The server use the nginx conf found in the wiki.

I use latest firefox on linux.

I installed snappymail - which I discoverd today - aside rainloop which is perfectly working.

**Comment by the-djmaze** [comment]
I only have Apache + FPM instances and none produce this error.

Is it possible that you investigate this issue yourself?
