### ISSUE TITLE
Debian package installs in /usr/share with "login user" as the owner

### ISSUE THREAD

**Issue by module0x90** [the-djmaze/snappymail#341]
**Describe the bug**

**To Reproduce**
1. Login to the server non-privileged
2. sudo su - to root
3. Add "deb https://snappymail.eu/repository/deb ./" to sources.list on a Debian Buster
4. aptitude install snappymail
4. Check /usr/share/snappymail, on my system the ownership was my login user, not the user I ran aptitude as

**Expected behavior**
Permissions should be www-data:www-data for /usr/share/snappymail most likely.

**Desktop (please complete the following information):**
 - SnappyMail Version 1.15.0
 - Server: Debian Buster, up2date

**Comment by the-djmaze** [comment]
The only option of dpkg is `--root-owner-group` which sets all files to root user.

A post installation script could set www-data as user, but not every system has that user.

I don't have debian based system, so someone should provide the best approach here.

**Comment by jsonoctopus** [comment]
>     * Server: Debian Buster, up2date
On Debian /usr/share/ has system files and /var/lib/ has data and config files. Looking at how the RainLoop debian package installs it shows that the /usr/share/snappymail/ would have to have root:root and /var/lib/snappymail/ would have www-data:www-data. The /var/lib/ part is already done right by the SnappyMail deb package, the /usr/share/ part needs root:root

**Comment by the-djmaze** [comment]
You can test now with v2.15.1

**Comment by module0x90** [comment]
Works for me, I am using the deb repo and I have just upgraded just fine.
In fact, this email is written with 2.15.1.
Ownership was also ok, root:root.


Thanks!
