### ISSUE TITLE
Autocrypt support

### ISSUE THREAD

**Issue by muppeth** [the-djmaze/snappymail#342]
Hi there, 
First of, thanks for the great mail client.
Are there any plans for implementing Autocrypt into snappymail? Autocrypt is interesting approach to auto key exchange which makes the adaptation of gpg easier for regular folks. Additionally, it would make snappymail compatible with deltachat (end to end encrypted chat working on imap/smtp) and number of other mail clients making the mail encryption first class citizen. 

https://autocrypt.org/
https://delta.chat/en/

**Comment by the-djmaze** [comment]
> Are there any plans for implementing Autocrypt into snappymail?

Not at the moment.

Looking at the documentation, the header doesn't seem to be valid.
`Autocrypt` should be `X-Autocrypt` as it is not IANA registered.

Nevertheless, i've added the base code for it.
When used, the data should be in the browser console in the fetch message response JSON.

**Comment by the-djmaze** [comment]
Now the Autocrypt public keys are automatically added to your keystore(s).
And when encrypting a message, the Autocrypt header is added.

Also read #89
