### ISSUE TITLE
smtp can't connect to smtp server

### ISSUE THREAD

**Issue by think-nice-things** [the-djmaze/snappymail#347]
This is maybe not a bug but more a help request.
I'm trying to set up snappymail with different providers, one of them being disroot.org.
(I'm _not_ using disroot's webmail setup but an own installation of snappymail).

For smtp I unfortunately I get a

`stream_socket_client(): unable to connect to tcp://disroot.org:587 (Connection timed out)`

The smtp information used (disroot.org, port 587) works perfectly with other clients.
I also tried SSL/TLS, port 465 and PHS's mail() function, no success either.

This is the latest snappymail snappymail-2.15.0.

**Any ideas how to solve this problem?**

![image](https://user-images.githubusercontent.com/4885370/164967355-939803d8-9651-40a2-84ef-e2b0f5c65ebb.png)

and here's some information about my server configuration

![image](https://user-images.githubusercontent.com/4885370/164968967-c1f64c54-f83b-4a64-8bb9-7832685f9957.png)

**Comment by the-djmaze** [comment]
Can you login using SSH?
If so, try: `openssl s_client -starttls smtp -connect disroot.org:587`

Seems like the server blocks outgoing port 587 or remote server blocking your IP.

**Comment by think-nice-things** [comment]
thanks. No unfortunately I've sftp access only.
Probably you're right that my server blocks outgoing 587 and 465 (which I tried too).

**Comment by the-djmaze** [comment]
And port 25 with starttls?

**Comment by derStephan** [comment]
I had the same problem with my hoster blocking outgoing SMTP ports. Try and open a support ticket there and explain that you need that port open for you. My provider did that without problem.

**Comment by stef157** [comment]
Hi, same issue.
When I try in terminal : openssl s_client -starttls smtp -connect domain.ltd:993 (or 587), I get "CONNECTED(00000005)".

On SnappyMail, same issue as mentioned unable to connect (tcp and ssl).

When I change the domain.tld to 127.0.0.1, it's working.
The webmail is on the same server that host my emails.
