### ISSUE TITLE
Attachment is displayed in wrong mail

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#35]
**RainLoop version, browser, OS:**
SnappyMail 2.0.0-rc3, Version 86.0.4240.111 (64-Bit), Windows 10

**Expected behavior and actual behavior:**
This is really a weird one.
1) Click on a mail without an attachment in the inbox. The mail is correctly displayed.
2) Click on another mail with an attachment in the inbox. The mail is correctly displayed with the attachment on top of the mail body.
3) Again click on another mail without an attachment. The mail is displayed WITH the attachment from step 2. In fact every mail without an attachment, you select from now on, is displayed WITH the attachment from step 2. As soon as you select another mail with an attachment, this attachment will be shown from now on.

The same problem also occurs for signed mails with a p7s attachment.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
The browser log is empty. The server log is unobtrusive.
[log-2020-11-04.txt](https://github.com/the-djmaze/snappymail/files/5490392/log-2020-11-04.txt)

**Comment by the-djmaze** [comment]
Yes, i just found out with testing as well and fixed in https://github.com/the-djmaze/snappymail/commit/cc04e42444304df5bad395a6b6c27adc7fe07cc3
