### ISSUE TITLE
Bad support for Polish special characters

### ISSUE THREAD

**Issue by tomasz-c** [the-djmaze/snappymail#350]
**Describe the bug**
Message editor (HTML and text) incorrectly supports Polish special characters (contained in UTF-8)

**To Reproduce**
1. Create a new message with content that contains all Polish special characters:
>Zażółć gęślą jaźń
2. Save the message without sending it and preview it or reopen it for editing.
3. See that the letter 'ą' (U+0105) has gone, interestingly enough the uppercase letter 'Ą' (U+0104) will not be lost.

**Desktop:**
 - Chromium 100, Firefox,
 - SnappyMail Version v2.15.0

**Mobile:**
 - Browser: Bromite 100
 - SnappyMail Version v2.15.0

On https://snappymail.eu/demo/ and two my own instances on PHP 8.0 and 8.1

**Additional context**
This probably worked fine in the past, but I can't tell from which version it stopped working.

**Comment by the-djmaze** [comment]
When trying PGP encrypt, i get an InvalidCharacterError.
So there's more wrong with it.

Needs more investigation.
