### ISSUE TITLE
`poppassd` for password change

### ISSUE THREAD

**Issue by DerDanilo** [the-djmaze/snappymail#351]
**Is your feature request related to a problem? Please describe.**
Cannot change the password via webmailer on some systems without complex and constantly to mantain custom plugins. 

**Describe the solution you'd like**
Shared hosting systems like Plesk or cPanel already offer `poppassd`.  Please support this as rainloop did.

**Describe alternatives you've considered**
Using any of the given options in the password change plugin is not usable in these cases.

**Additional context**
Rainloop had a simple plugin for that.
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/poppassd-change-password

Thanks!

**Comment by the-djmaze** [comment]
You can test the plugin now

**Comment by DerDanilo** [comment]
<img width="856" alt="grafik" src="https://user-images.githubusercontent.com/12999938/166116123-dee02649-ca12-4777-bfbb-807a6271469b.png">

```
AH01071: Got error 'PHP message: PHP Warning:  Undefined variable $sLogin in /var/www/vhosts/.../.../data/_data_.../_default_/plugins/change-password-poppassd/driver.php on line 57PHP message: PHP Notice:  ChangePasswordpoppassdDriver failed: UnknownNotification[130] in /var/www/vhosts/.../.../data/_data_.../_default_/plugins/change-password/index.php on line 183PHP message: PHP Notice:  ChangePassword failed in /var/www/vhosts/.../.../data/_data_.../_default_/plugins/change-password/index.php on line 194PHP message: SERVICE WARNING: UnknownNotification[130]' |   |   |   | Apache-Fehler
```

- Nginx: Frontend
- Apache: Backend
- PHP 8.1.5

**Comment by the-djmaze** [comment]
> Wouldn't it make more sense to just integrate it into the password change plugin?

Yes and no.
It's currently there on purpose so that people know how to easily create their own change-password driver.
If they upload their own driver to `/change-password/drivers/` it would be gone with every plugin update.
