### ISSUE TITLE
Error on loading in SeaMonkey browser.

### ISSUE THREAD

**Issue by Joe1962** [the-djmaze/snappymail#352]
**Describe the bug**
When loading a Snappymail site on SeaMonkey browser, it simply shows the theme background and an error message:
"An error occurred.
Please refresh the page and try again. rl.app is undefined"

**To Reproduce**
1. Simply open a self-hosted SnappyMail site or the online demo in SeaMonkey browser.

**Expected behavior**
It should open normally.

**Desktop (please complete the following information):**
 - Browser: SeaMonkey 2.53.9.1 
 - SnappyMail Version: 2.15.0

**Comment by Joe1962** [comment]
Also confirmed on SeaMonkey 2.53.11.1.

**Comment by the-djmaze** [comment]
The real error is: `SyntaxError: invalid regular expression flag s`
This means that SeaMonkey does not support ECMAScript 2018.
This is a bug that should be reported at SeaMonkey, not here.


ECMAScript 2018 includes new features:
* the spread operator and rest parameters (...) for object literals
* asynchronous iteration,
* Promise.prototype.finally
* additions to RegExp

SnappyMail relies on them and is mentioned in the README

**Comment by the-djmaze** [comment]
As a side-note: you shoud not use SeaMonkey browser.
It is based on the old Firefox 68 ESR (68.12 released 2020-08-25).
Currently Firefox is at 91.8.0 ESR.

**Comment by yeupou** [comment]
For the record, I had the same issue yesterday using an old firefox, version 71.0 (as shipped by previous debian stable, so not up to date but not decades old).

**Comment by the-djmaze** [comment]
> I had the same issue yesterday using an old firefox, version 71.0

Correct, seems only Firefox 78+ has this implemented
