### ISSUE TITLE
Authentication failed repeats twice and then once again angrily

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#353]
**Describe the bug**
When logging in to an email account with the wrong password, an authentication failed message appears... 3 times like this:

Authentication failed
AUTHENTICATIONFAILED Authentication failed.

**To Reproduce**
1. Go to snappymail login
2. Enter an email address and wrong password
3. Proceed to sign in
4. Authentication failed message appears (great!) but it says the words three times (weird).

**Expected behavior**
Snappymail doesn't behave like it's a frantic boomer talking to a millennial: it should stop yelling and repeating itself.

**Screenshots**
<img width="738" alt="snappymail-boomer-auth-failed-alot" src="https://user-images.githubusercontent.com/326966/165617601-b7aaabe3-bb2c-4108-bc76-3a8bdcae834f.png">

**Desktop (please complete the following information):**
 - Firefox 99.0.1 on macOS 12.3.1
 - SnappyMail Version 2.15.0

**Mobile (please complete the following information):**
 - Didn't test it.

**Additional context**
I realize it's not actually a boomer talking to a millennial, and is likely just a localization string lookup/output issue.

**Comment by the-djmaze** [comment]
Correct!

The first is the error generated by SnappyMail.
The additional message is generated by IMAP server.
In this case you're looking cross-eyed, but this totally depends on the kind of error.

**Comment by jas8522** [comment]
Haha yeah, that'd be a bit more clear, or 'server response:' -- maybe change up the font for the server response to be monospaced or something to make a visual difference. An alternative could be to have the server response logged to the javascript console and only show Authentication failed once on-screen, maybe with a tooltip that indicates to check the javascript console for more details.
