### ISSUE TITLE
HTML mail line spacing

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#356]
**Describe the bug**
1. Write a new HTML mail. The line spacing is as expected.
<img width="749" alt="test01" src="https://user-images.githubusercontent.com/2138442/166048759-5fbb101a-413d-4875-a4ef-9979bae3698a.png">

Code:
```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8"></head><body>


<div>first line</div>
<div>second line</div>
<div class=3D"rl-signature"></div>

</body></html>
```

2. Answer to an HTML mail. The first line has a bigger line spacing before and after. But it should behave the same way as the use case writing a new HTML mail.
<img width="748" alt="166049640-7ccb7b40-3720-4e50-bc5f-b64fea762323" src="https://user-images.githubusercontent.com/2138442/166068705-9eb02f80-20b2-4d60-93ef-00d27ace1648.png">

Code:
```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8"></head><body>


<div>
<p>first line</p>
<div>second line</div>
<div>third line</div>
<div><br></div>
<div>April 29, 2022, 9:10 PM, "..." &lt;<a href=3D"mailt=
o:...@...?to=3D%%%C3%%22%20%3C....=
...%3E" target=3D"_blank" tabindex=3D"-1">...@...</a>&gt; wrote:=
</div>
<blockquote>
<div>
<div>first line</div>
<div>second line</div>
<div><br></div>
</div>
</blockquote>
</div>
<div class=3D"rl-signature"></div>

</body></html>
```

**Desktop**
 - Google Chrome 100.0.4896.127
 - SnappyMail 2.15.0

**Comment by the-djmaze** [comment]
Thanks. Changed it.
