### ISSUE TITLE
Draft mail - Edit button wrong position

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#357]
**Describe the bug**
1. Create a new mail
2. Save the mail
3. Go to drafts
4. Open the saved mail

There is an arrow, that should not be there and the green "Edit" button should be aligned to the right.
<img width="1042" alt="test03" src="https://user-images.githubusercontent.com/2138442/166058404-513b8bfd-6151-407b-aa7e-7e8f458f8aee.png">

Code:
<img width="960" alt="test04" src="https://user-images.githubusercontent.com/2138442/166058618-b8b1fc4f-85ea-4504-ac37-d849db872d82.png">

When you click on the burger icon, there is an entry above "Delete" missing. Probably the arrow should pop up there.
<img width="173" alt="test05" src="https://user-images.githubusercontent.com/2138442/166058947-6bac5c38-8d41-43df-83ee-650c0088e001.png">

**Desktop**
Google Chrome 100.0.4896.127
SnappyMail 2.15.0

**Comment by the-djmaze** [comment]
Thanks! Fixed it
