### ISSUE TITLE
2FA extension/plugin not updating

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#359]
Snappymail v.2.15.1

When trying to update the 2FA extension I get an error message [see screenshot]:

![Screenshot from 2022-04-30 16-35-21](https://user-images.githubusercontent.com/35845319/166112495-9223c530-08e4-4a8e-a8bb-4a4476ecdd4a.png)

**Comment by the-djmaze** [comment]
Fixed!
