### ISSUE TITLE
Documentation: Detailed explanation about optional PHP extensions.

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#362]
In the "Requirements" section of "Installation instructions" page on Wiki, 15 php extensions are listed as "Optional extensions". But it isn't necessarily clear what additional feature or functionality is enabled by installing each of them. And it makes it difficult for user to decide whether or not he installs each of them. So would you please add information of what becames possible by installing each of them?

**Comment by the-djmaze** [comment]
> what additional feature or functionality is enabled by installing each of them

Mostly there is none.
For some it's a complex case.

**EXIF** is used to detect image orientation.
So when GD and Exif is installed AND `image_exif_auto_rotate` is on in application.ini the system is slow but rotates images.
BUT: when gmagick or imagick is installed, the exif extension is not required.

**intl** is used for IDN domain names, when not installed a PHP version is used.

**iconv** is only used for `iconv_mime_encode` but not really needed either.

**ldap** for the address book
**mysql** for the address book
**pgsql** for the address book
**sqlite** for the address book

**xxtea** to be faster then xxtea.php
**OpenSSL** for better encryption then XXTEA
**Sodium** for even better encryption then XXTEA and OpenSSL

**uuid** to generate real uuid's, else there's a PHP fallback

**zip** to download mail attachments as zip

That's it.

**Comment by the-djmaze** [comment]
Updated https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#requirements
