### ISSUE TITLE
Make emailaddresses-datalist bigger when using contacts suggestions

### ISSUE THREAD

**Issue by ZephOne** [the-djmaze/snappymail#368]
**Is your feature request related to a problem? Please describe.**
When a contact's address is a bit long, the emailaddresses-datalist is not wide enough to totally display the suggested address.

**Describe the solution you'd like**
Would it be possible make emailaddresses-datalist element as wide as the `To` field as it it was with RainLoop for instance ?

**Describe alternatives you've considered**

**Additional context**

**Comment by the-djmaze** [comment]
Your request looks relative to your screen size.
Could you make a screenshot so that i understand what ypu mean?

**Comment by ZephOne** [comment]
Yep, here are shome screenshots:
* With Chromium on a 14" screen
![snappymail_suggestion_list_chromium_14_inches_screen](https://user-images.githubusercontent.com/25317904/167387915-d00314ef-5822-4eec-8212-83e460f70695.png)

* With firefox on a 14" screen:
![snappymail_suggestion_list_firefox_14_inches_screen](https://user-images.githubusercontent.com/25317904/167388010-564b1681-2b1d-44b2-9c4c-123290b30dea.png)

* With Android/Chrome on a 6.3"" screen:
![snappymail_suggestion_list_android_chrome](https://user-images.githubusercontent.com/25317904/167388207-9c035cdd-4195-4757-b622-1bc9ba9691bb.png)

It seems to be only good with Android/Chrome.

**Comment by the-djmaze** [comment]
Ah yes, the Firefox bug.
Something changed in Firefox so that `option` elements can't have CSS anymore.
This is also an issue in the selectbox on the "create folder" screen where the depth indent for existing folders is gone.

Will search the internet if there are solutions.

**Comment by the-djmaze** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1106946

**Comment by ZephOne** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1106946

Indeed
