### ISSUE TITLE
Snappymail demo site is being spammed with racist comments

### ISSUE THREAD

**Issue by DerekMarshall** [the-djmaze/snappymail#371]
Steps to reproduce:

1. Go to: https://snappymail.eu/demo/

2. View the sidebar on the left

3. View the miserable hate and stupidity.

**Comment by the-djmaze** [comment]
Yes, again! Same as #363
Someone in Russia seems not to be happy with SnappyMail: 178.205.196.83

**Comment by the-djmaze** [comment]
> But would probably try again using different IP...

Yep, now using Zenmate VPN or Cyber Ghost VPN on the M247 network.
Spam costs the person 7 minutes of live.
Reset of the mail demo: 5 seconds

**Comment by the-djmaze** [comment]
Seems to be quiet now

**Comment by the-djmaze** [comment]
Was active again at 01:00 UTC from 178.204.132.230
