### ISSUE TITLE
Gmail Auth

### ISSUE THREAD

**Issue by yomiury** [the-djmaze/snappymail#372]
Hi Guys,

i am using snappymail 2.15.1 and i can't connect to gmail server.

`Server message: Can't connect to host "ssl://imap.gmail.com:993"`

I know that google announces that snappymail will not work properly with plain user/credentials auth after mai '30  [Less secure apps & your Google Account](https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cupdate-your-app-or-operating-system%2Cuse-more-secure-apps%2Cuse-an-app-password).

I already  setup an App Passwords for the account and that's works for some time. But now the error returns.

how can we avoid service interruption?

thanks in advance

**Comment by nisegami** [comment]
I get this error trying to log into my Gmail account with those settings. However, my gsuite account works once I set up my domain as an alias for gmail. Anyone got any ideas?

![image](https://user-images.githubusercontent.com/2251723/167191887-7600fdc1-d666-4a2b-becf-21e765206429.png)

**Comment by hguilbert** [comment]
With app password

![Capture d’écran du 2022-05-08 14-03-50](https://user-images.githubusercontent.com/51283484/167295308-f5f2a4fa-997e-457b-8b5b-98f3414159a2.png)
![Capture d’écran du 2022-05-08 14-04-05](https://user-images.githubusercontent.com/51283484/167295310-53873e8f-0f13-4b83-97a7-e56daf311466.png)
