### ISSUE TITLE
Pressing <Tab> in the To: field

### ISSUE THREAD

**Issue by Pumpino** [the-djmaze/snappymail#376]
As is the case in Rainloop, SnappyMail produces a possible match from the address book when you begin to type a person's name in the To: field. Once there's a match, you can press the down arrow key and <Enter> to select the recipient.

In Rainloop, one can simply press <Tab>, which selects the suggested recipient and moves the cursor to the Subject field in one key press.

In comparison, to do this in SnappyMail requires three key presses - the down arrow to select the recipient, <Enter> and <Tab> to move to the Subject field.

I realise it's only a difference of two key presses, but when you compose dozens of emails daily, it's a change in behaviour that I've noticed in SnappyMail.

Would it be easy to change this back? Thanks.

**Comment by phsc84** [comment]
In my opinion it should be as follows:
1) Start typing a name. SnappyMail suggests a recipient. Select the recipient by clicking enter (without the need to press the down arrow).
2) Snappymail stays in the "To:" field, so you can add more recipients if needed.
3) If you want to switch to the "Subject" field, you have to press the tab button.

**Comment by the-djmaze** [comment]
Firefox:
1. start to type
2. arrow down to select recipient
3. [Tab] selects + jumps to next input

So that's one key press

**Comment by Pumpino** [comment]
> 3. [Tab] selects + jumps to next input

I can confirm that's how it works in Firefox.

However, in Chrome, pressing [Tab] without pressing [Enter] first doesn't actually choose the recipient. It leaves the text that I typed in the To: field but it hasn't actually entered the recipient. Therefore, arrow down, [Enter] and [Tab] are required.
