### ISSUE TITLE
Performance for large folders

### ISSUE THREAD

**Issue by edlerd** [the-djmaze/snappymail#377]
**Describe the bug**
Switch to a folder with >1k mails takes 7 seconds to load. Searching in the folder takes >11 seconds. I just migrated from rainloop, where both actions took less than 1s on the same backend.
I use dovecot as a backend with solr as a search core, see also https://doc.dovecot.org/configuration_manual/fts/solr/#fts-backend-solr 

**To Reproduce**
1. Go to Inbox
2. Click on a large folder i.e. Archive
3. Takes 7s to display first 20 emails. (I guess fetching the total count for pagination is taking too long?)

**Expected behavior**
Large folder switch and search should be fast and snappy, as in snappymail :)

**Desktop (please complete the following information):**
 - Firefox 100.0
 - SnappyMail 2.15.1

**Comment by the-djmaze** [comment]
I have:
```
MessageCount | 577
Time | 137
```

So we need more info about your setup to find out why it's slow.

**Comment by edlerd** [comment]
What do you need, I can provide any info.

**Comment by edlerd** [comment]
I did a fresh install, and it performs very well in less than 1s. So it was something left due to the upgrade, but I can't point out the actual problem.

**Comment by edlerd** [comment]
It happens as soon as the "Threaded View" is enabled on large folders (>30k mails).

I did some profiling, and it turns out there are >3k calls to array_diff, which make the php process use 100% CPU time for 7 seconds. The calls originate in https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php#L906
