### ISSUE TITLE
Web resources absolute path

### ISSUE THREAD

**Issue by FWest98** [the-djmaze/snappymail#379]
I have my snappymail instance loaded behind an nginx reverse proxy that maps requests to `domain.com/webmail/` to `/` in the Docker container. I recently updated to v2.5.1, and since then it turns out something changed with the HTML generation, and now the CSS/JS resources are an absolute path (`/snappymail/...`) instead of a relative one (`snappymail`). Consequently, my browser tries to load the resources from `domain.com/snappymail/...` instead of `domain.com/webmail/snappymail/...`.

I believe this leading slash is generated here: https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/RainLoop/Utils.php#L154

Is there any setting I can define to change this behaviour? Does this need to be fixed in the code? Can it be? Or do I need to give up hosting snappymail in a path, and instead transfer everything to a subdomain?

**Comment by the-djmaze** [comment]
Is the above commit a solution to your problem?

It uses a new option from application.ini

**Comment by FWest98** [comment]
That would be _a_ solution, but I think a better/more general solution would be to always use relative paths, if that is possible within the application. I would also rename the setting to `relative_path` and document its functionality somewhere.

**Comment by the-djmaze** [comment]
> a better/more general solution would be to always use relative paths

This is not possible.

One good example of issue is CSS
```css
--main-bg-image: url("./snappymail/v/0.0.0/themes/SquaresDark/images/background.jpg");
```
Is used by `/snappymail/v/0.0.0/static/css/app.min.css`
Result is: `/snappymail/v/0.0.0/static/css/snappymail/v/0.0.0/themes/SquaresDark/images/background.jpg`

**Comment by FWest98** [comment]
But that would then also still be a problem with your proposed config setting... Since this CSS is generated by gulp, isn't it possible to use relative paths in these definitions as well (so `../../themes/SquaresDark/images/background.jpg` or some other way to make these all relative to the current folder)?

**Comment by the-djmaze** [comment]
That would make it very buggy for many setups (just like yours).
The new application.ini setting will fix it for your proxy use.

**Comment by FWest98** [comment]
I think there is not one way to make it work for all cases, so let's see how far we get with the setting!

**Comment by bonanza123** [comment]
@FWest98  I have the same issue as the first poster and I am running 2.16.1
How can I fix that issue given the new options in application.ini?

**Comment by bonanza123** [comment]
@the-djmaze  I have the same issue as the first poster and I am running 2.16.1
How can I fix that issue given the new options in application.ini?

**Comment by the-djmaze** [comment]
@bonanza123 the issue is proxy.

When you setup http server  virtualhost as webmail.domain.example it works.
When you setup httpd server alias as domain.example/webmail it works.

The problem is a proxy for any them that redirects to something else.

I use the cPanel approach by using custom port number.
Because the servers i manage used to have cPanel and due to license costs cPanel was dropped and nginx and apache are configured to host webmail on port 2096

**Comment by bonanza123** [comment]
@the-djmaze  thanks for your reply.
I use nginx with the following config
```
        location /mail/ {
                proxy_pass http://127.0.0.1:8094/;
                proxy_redirect          off;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto https;
        }
```
where on port 8094, I have a docker running that is built directly from https://github.com/the-djmaze/snappymail/blob/master/.docker/release/Dockerfile (just with port redirection from 8888 => 8094).
What am I doing wrong?

**Comment by the-djmaze** [comment]
Like i said, you redirect `/mail/` to `/` so SnappyMail thinks it is `/`.
You can test the new setting in application.ini by setting it to `/mail`

**Comment by msimerson** [comment]
Thanks for this! I run webmails inside VMs with php-fcgi and nginx. These isolated microservices run behind haproxy which does the SSL termination and URL manipulation for a slew of services. HTTP requests are proxied to the snappymail instance via a haproxy declaration:

````
backend www_snappymail
    server snappymail 172.16.15.60:80 send-proxy-v2
    http-request replace-path /snappymail/(.*) /\1
````

This setup mercifully don't require a scad of web servers to each be configured and reloaded every time new TLS certifications are issued. It also means some services can't work out the correct URI path. Setting `app_path = "/snappymail"` in configs/application.ini does the needful.
