### ISSUE TITLE
Upgrade from RainLoop

### ISSUE THREAD

**Issue by derStephan** [the-djmaze/snappymail#38]
Hi there,

first of all, I would like to say thank you for taking up the development. I am using RainLoop for  couple of years now. I think, the software is worth to be improved. And getting rid of complexity and libraries is highly appreciated. 

Is there a way to upgrade from RainLoop 1.13.0 to Snappymail 2.0.0? Just drop in the files and configuration will be kept? Or should I do a fresh start?

**Comment by the-djmaze** [comment]
It should be possible to drop in.
However, the application.ini could be missing things or admin login fails.
So, if switching to snappymail fails, you could backup application.ini run admin and compare the differences.

**Comment by derStephan** [comment]
Okay, I won't do that. I just wanted to save a few keystrokes. Better to start all over. Thanks for the quick reply.
