### ISSUE TITLE
Gmail does not seem to work

### ISSUE THREAD

**Issue by kosuodhmwa** [the-djmaze/snappymail#384]
Get that message:

![image](https://user-images.githubusercontent.com/24782840/168029954-96fe2a2e-727c-4e71-a285-73be4c5a9c89.png)

...after login with brower i've seen that red warning dialog that another IP (must be the IP that my virtual plesk servers uses) has tried to login in. And i confirmed that dialog in web browser - so the login message told me.

After confirmation, still the same...

![image](https://user-images.githubusercontent.com/24782840/168030241-8512edec-b554-4709-b7e3-14166b2fd3ef.png)

why?

**Comment by kosuodhmwa** [comment]
Maybe i need to set up a SOCKS proxy on that server and use, for example, SocksCap64, to start the browser with google login on my local computer - but under the network context / ip from my server...?

That's Google's security paranoid - maybe i'm right with that!?

**Comment by the-djmaze** [comment]
> Access for less secure apps is also turned on

And are you using the app password then?

**Comment by kosuodhmwa** [comment]
Thank you very very much, will look on it asap. (Maybe you can remove it from the "Bug" section?)

**Comment by kosuodhmwa** [comment]
Thank you very much! :-)
