### ISSUE TITLE
Documentation: How to use Debian repository

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#386]
According to the releases page, Debian repository of SnappyMail is avairable with https://snappymail.eu/repository/deb/.
I checked wiki but can't fild how to use it.
After some trials and errors, I succeeded to install snappymail from the repository with following steps.
1. `mkdir /etc/apt/keyrings/`
2. `wget -O- https://snappymail.eu/repository/deb/48208BA13290F3EB.asc | gpg --dearmor > /etc/apt/keyrings/snappymail.gpg`
3. Create `cat /etc/apt/sources.list.d/snappymail.list` with following line.
```
deb [signed-by=/etc/apt/keyrings/snappymail.gpg] https://snappymail.eu/repository/deb ./
```
4. `apt update`
5. `apt install snappymail`

I'm not sure if this is correct. But if it is, please add it Installation instructions page of wiki.

**Comment by the-djmaze** [comment]
That is an option.
Importing the key is also possible with
```
gpg --keyserver keyserver.ubuntu.com --recv-keys   48208BA13290F3EB
gpg -a --export 48208BA13290F3EB | apt-key add -
```

But which method is best?

**Comment by yasuhirokimura** [comment]
According to the result of web search, `apt-key` is deprecated since Debian 11 and Ubuntu 22.04 (https://techviewleo.com/apt-key-is-deprecated-manage-keyring-files-in-trusted-gpg-dot-d/).  So the latter way should be avoided.

As for other 2 ways, I'm not sure which is better.
I used `wget` simply because it is used in following example.
https://www.rspamd.com/downloads.html

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#debian--devuan
