### ISSUE TITLE
Failed to install extension: 0 - Class 'PharData' not found 

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#392]
I installed SnappyMail 2.15.2 on FreeBSD 13.0-RELEASE amd64 host with following steps.

1. Install PHP and extensions
    - Version is 7.4.29
    - Following extensions are installed
       - curl
       - dom
       - gd
       - iconv
       - intl
       - json
       - mbstring
       - openssl
       - sodium
       - tidy
       - libxml
       - zip
       - zlib
       - pdo_sqlite
    - Installed by using FreeBSD Ports Collection (https://www.freebsd.org/ports/)
2. Extract snappymail-2.15.2.tar.gz
    - Owner/group of all files and directories are root(0)/wheel(0)
    - Permission of all files is 0644, that of all directories is 0755
3. Use out-of-tree data directory
    1. `mkdir -p /some/where/snappymail/data`
    2. `chown www:www /some/where/snappymail/data`
    3. `chmod 700 /some/where/snappymail/data`
    4.  `cp _include.php include.php`
    5. Change line 31 of include.php as following
```
define('APP_DATA_FOLDER_PATH', '/some/where/snappymail/data/');
```
4. Configure web server (Apache 2.4.53 + php-fpm)

Basic functionality seems to work fine but there is one problem.
If I try to install any extension from admin panel, it failed and following error message is displayed.

> Failed to install extension: 0 - Class 'PharData' not found

As I wrote other issue report I also installed SnappyMail 2.15.2 on Debian by using SnappyMail .deb repository.
And on debian instance I can install extensions successfully. 
So I think something is wrong with my installation on FreeBSD host.
Is there any possible cause of the error?

**Comment by the-djmaze** [comment]
Although Phar is enabled by default (since PHP 5.3), someone has configured the PHP builder with `--disable-phar`
In this case you must install plugins manually.

Just upload a folder of https://github.com/the-djmaze/snappymail/tree/master/plugins to `/data/_data_/_default_/plugins/`

It is cumbersome, so if you can compile PHP without `--disable-phar` in the `./configure`, it would be better.

**Comment by yasuhirokimura** [comment]
@the-djmaze Thanks for quick reply.
In FreeBSD Ports Collection phar is provided as one of PHP extensions.
So I installed it and confirmed I can install extensions from admin panel successfully.
