### ISSUE TITLE
Unable to save or send html message

### ISSUE THREAD

**Issue by oonet** [the-djmaze/snappymail#393]
SnappyMail 2.15.2
Xubuntu 22.04
Firefox 100.0

Unable to save or send html format message.

Compose new message (defaults to html)
Hit Save — error "Can't save message"
Hit "HTML <-> TEXT" button (switch to text format)
Hit Save — message saves, as expected

Error appears in server logs as "Typed property DOMElement::$tagName must not be accessed before initialization"

**Comment by the-djmaze** [comment]
> "Typed property DOMElement::$tagName must not be accessed before initialization"

Seems to be a bug in your PHP.
Can you tell which version you are using?

As the problem can only be at https://github.com/the-djmaze/snappymail/blob/2b22c06b3499fef8b00e54386a7a86f15fbe0614/snappymail/v/0.0.0/app/libraries/MailSo/Base/HtmlUtils.php#L113

And somehow the DOMElement is incorrect.

**Comment by oonet** [comment]
PHP 8.1

**Comment by oonet** [comment]
PHP Version 2:8.1+92ubuntu1

**Comment by the-djmaze** [comment]
Strange.

Does it work when modifying that line into:
```php
$sTagNameLower = \strtolower($oElement->nodeName);
```

**Comment by oonet** [comment]
Yes!
