### ISSUE TITLE
How to use it with Confixx...

### ISSUE THREAD

**Issue by kosuodhmwa** [the-djmaze/snappymail#398]
...which generates mail account usernames like web[X]p[Y] and NOT "usual" ones where the mail address is equivalent to the username?

That does not match with the "allowed domain" list that i configured in SnappyMail admin web GUI so i think, because SnappyMail looks on the substring part on the e-mail address that the SnappyMail users needs to log in .....[@my-configured-domain.com]

When i want to connect a Confixx mail account e.g. to M$ Outlook, i need to use that connection parameters.

mail.myprovider.com (myprovider.com does not the the e-mail-addresse[s] they will be used i poll over mail.myprovider.com... but i can create, for example, a DNS CNAME like mail.mydomain.com -> mail.myprovider.com ... the hosting is a "shared hosting" - not a [virtual] root server or a "managed" server)

Thank you very much for your feedback(s).

With best regards, Jan

**Comment by kosuodhmwa** [comment]
Thank you very much for your feedback.

**QUESTION:** When i add '*' in admin GUI and then enter the plesk mail username webXpY - where does snappymail knows which IMAP server should be connected...?

**Comment by the-djmaze** [comment]
> where does snappymail knows which IMAP server should be connected...?

Just configure it
![afbeelding](https://user-images.githubusercontent.com/3752035/168752732-50969610-7c2c-4fae-a470-be91d74a9b38.png)

**Comment by the-djmaze** [comment]
Oh wait, i think i understand what you want.

1. login with web[X]p[Y]
2. connect with `localhost`

Then use:
![afbeelding](https://user-images.githubusercontent.com/3752035/168754736-0592aab6-1a51-4f60-9069-3b19ef905039.png)


If you want to connect with different server for a specific user, then you must write a plugin that modifies the connection parameters.
https://github.com/the-djmaze/snappymail/tree/master/plugins#imap

**Comment by kosuodhmwa** [comment]
Oh - sure!! ;-)

But in that case, i have to run the SnappyMail script on the same server as confixx with its webYpY mail account usernames.. ;-)

**Comment by the-djmaze** [comment]
> on same server as confixx

No, just replace `localhost` with 1 server that allows login with webXpY

**Comment by kosuodhmwa** [comment]
And then, what happens in background? Will SnappyMail try to log in on every server that is in the list in the admin GUI - try and error while it crashes until one (1) server is found in the server list where authentication with 'webXpY' does not fail..?

Currently, i don't really understand the logic behind that concept...

**Comment by kosuodhmwa** [comment]
I always thinked it's multiple domain compatible and it will "cut" the string begind the '@'-character to get the domain substring and looks that is matches with the (allowed) domains i've configuted in SnappyMail Admin Web GUI...

**Comment by the-djmaze** [comment]
That's not possible.
I think you didn't provide enough information to handle your use case.

Say:
web1p1 = web1.mail.server user 1
web1p2 = web1.mail.server user 2
web2p3 = web2.mail.server user 3

Then you have a totally different usage, like:
web1p1 = web1p1@web1.mail.server
web1p2 = web1p2@web1.mail.server
web2p3 = web2p3@web2.mail.server

It's all possible, you just need to provide your full description.

**Comment by kosuodhmwa** [comment]
Thank you very much, will look on it ASAP as soon i have some time... :-)

**Comment by derStephan** [comment]
There already is a plugin available for exactly that.
https://github.com/the-djmaze/snappymail/tree/master/plugins/custom-login-mapping

There you can define pairs of eMailaddresses to credentials:
web1p1@web1.mail.server:web1p1

Works for me like a charm.

**Comment by kosuodhmwa** [comment]
Thank you very much, will look on it ASAP! :-)
