### ISSUE TITLE
Login window with TOTP : Tab doesn't work if something is present in login/password

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#399]
**Describe the bug**
If you type a login, press the Tab key to go in password, type it, then press Tab key to go in TOTP, the Cursor go in the Submit form but not in the TOTP field.
If the login and password fields are empty, the tab works as expected : Login <tab> Password <tab> TOTP <tab> Submit

**To Reproduce**
1. On login window
2. Type something in Login field and password field
3. Hit the "Tab" key to go in TOTP
4. The active object is not the TOTP field, it is the submit button

 - SnappyMail Version 2.15.3

**Comment by the-djmaze** [comment]
Yes, the problem is `tabindex`.
There is no real solution for this, unless we remove the "hide submit button" feature.

My point of view is to remove the feature, but it was in RainLoop so removing it would loose it for some.

**Comment by dominiquefournier** [comment]
I am sorry, but I don't see any tabindex in the login/password/TOTP fields. You may add them to force the order ? I just try to set them temporaly in the Developper Console : tabindex=1 for email, tabindex=2 for password, tabindex=3 for totp_code, tabindex=4 for submit, tabindex=5 for signMe (instead of 0), tabindex=6 for selectLanguage (instead of -1) .
It works. 
If the TOTP is not displayed, the browser just skip the associated tabindex and go correctely on the submit button

**Comment by the-djmaze** [comment]
What if TOTP input does not exists?
What if you also have others, like hCaptcha?

My Firefox goes whack and skips inputs with incorrect tabindex order.
If i only set the button to tabindex=10 firefox thinks it is -1.
🤬

**Comment by dominiquefournier** [comment]
I just try, it was working. But, you may remove all the existing tabindex, to not force the order ?

**Comment by the-djmaze** [comment]
I removed the feature.
As i also found:

https://news.ycombinator.com/item?id=31258678
`missing/hidden login button ain't very user friendly, I even clicked on language icon first thinking it's maybe login button`

https://news.ycombinator.com/item?id=31258368
`it does not have a login button, so when autofilling my login, I have to touch an input field and press enter on the keyboard`
