### ISSUE TITLE
Compose window should allow to add `Reply-To` header

### ISSUE THREAD

**Issue by tkasch** [the-djmaze/snappymail#401]
**Is your feature request related to a problem? Please describe.**
As of SnappyMail 2.15.3 it does not seem to be possible to add an individual `Reply-To` header when composing a message. People having used RainLoop in the past might miss this feature.

**Describe the solution you'd like**
The message compose window allows to add `Cc` and `Bcc` header fields via buttons at the top. It would be nice to have a `Reply-To` header button there as well.

**Comment by the-djmaze** [comment]
It's in the menu:
![afbeelding](https://user-images.githubusercontent.com/3752035/168591505-8c075407-24e0-451d-b16c-71e76cdd3dcb.png)

Also read #239

**Comment by tkasch** [comment]
Ok, point taken.
