### ISSUE TITLE
Make (all) links clickable

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#402]
**Is your feature request related to a problem? Please describe.**
http links in some emails from Outlook 2010 are not clickable

**Describe the solution you'd like**
All strings beginning by http(s):// should be clickable

**Additional context**
Outlook 2010 seems to do ugly HTML code on some emails causing SnappyMail and Thunderbird not to be able to detect the link.
Copy-pasting the link into the browser bar works but if a human (and Outlook !) can recognize and copy the link, the mail client should be able to do it, I guess ?

Outlook screenshot :
![image](https://user-images.githubusercontent.com/6248852/168846663-b1e9e717-87f8-464b-815a-53cd42ce00b7.png)

Thunderbird screenshot :
![image](https://user-images.githubusercontent.com/6248852/168846942-7a8c57e0-20d3-4d10-aba7-8f3e21a32f1e.png)

SnappyMail screenshot :
![image](https://user-images.githubusercontent.com/6248852/168847129-95a3a5a2-a367-4f6f-a2f1-90b4ebc1bd69.png)

The source code of the mail (private datas obfuscated)  is attached

[source.txt](https://github.com/the-djmaze/snappymail/files/8709547/source.txt)

**Comment by Mer0me** [comment]
I understand the argument.
But when I send a plain text mail without any kind of HTML markup showing where is a link, the link is correctly parsed by Thunderbird and SnappyMail. Why it isn't possible (or why it could be dangerous) to recognize the plain text link into a malformed and crappy html markup from Outlook 2010 ?

SnappyMail screenshot of a plaintext mail containing a link :
![image](https://user-images.githubusercontent.com/6248852/169035919-c36bc5db-464d-4cc2-bc10-981c04f1b689.png)

**Comment by kouinkouin** [comment]
For curiosity, what are the sources of a mail from Outlook 2010 and another clients?
It's not to patch it, but to see the difference between regular mail clients and old MS clients (bodies, headers, ...).

**Comment by the-djmaze** [comment]
> the link is correctly parsed by Thunderbird and SnappyMail

Well... not always
Say you have this text message:
```
Go to https://example.com/.
```
Is the last dot part of the url or not?
The dot is valid in urls, but in this case it might be the end of a sentence...
So if we make a rule "end at dot", what would happen here:
```
Read https://example.com/document.pdf
```
Ok, new rule: if dot is last then stop.

Easy for text, but now comes HTML...
This is way more complicated and we first need to convert all URL text to HTML.
Outlook:
```html
<p class=MsoNormal><a href="https://foo.dummy.com/index.php/f/660436">https://foo.dummy.com/index.php/f/660436</a><o:p></o:p></p>
```
Valid HTML browsers:
```html
<a href="https://foo.dummy.com/index.php/f/660436"><a href="https://foo.dummy.com/index.php/f/660436">https://foo.dummy.com/index.php/f/660436</a></a>
```
Or even more complex:
```html
<a href="https://foo.dummy.com/index.php/f/660436"><span color="#F00"><a href="https://foo.dummy.com/index.php/f/660436">https://foo.dummy.com/index.php/f/660436</a><span></a>
```
Now we must remove the `<a>` that is inside the `<a>` = bad idea

Ok, new approach:
1. Walk through all HTML elements
2. If no child elements and no A as parent, fetch text
3. replace url in text to `<a>`

Every time you want to read a message, this makes it slow.
For very large emails it makes it very slow.

**Comment by the-djmaze** [comment]
> For curiosity, what are the sources of a mail from Outlook 2010 and another clients?

Well, you can easily recognize crappy Outlook.
All HTML attributes have no (single)quotes around the values.
Say:
```html
<p class=MsoNormal>
```
vs
```html
<p class="MsoNormal">
```

Secondly, because Outlook is not using a real HTML engine (just Word).
It has a lot of workarounds inside the HTML to "fix" Word.
To give a simple one: namespaces
```html
<html
	xmlns:v="urn:schemas-microsoft-com:vml"
	xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:w="urn:schemas-microsoft-com:office:word"
	xmlns:x="urn:schemas-microsoft-com:office:excel"
	xmlns:p="urn:schemas-microsoft-com:office:powerpoint"
	xmlns:a="urn:schemas-microsoft-com:office:access"
	xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
	xmlns:s="uuid:BDC6E3F0-6DA3-11d1-A2A3-00AA00C14882"
	xmlns:rs="urn:schemas-microsoft-com:rowset"
	xmlns:z="#RowsetSchema"
	xmlns:b="urn:schemas-microsoft-com:office:publisher"
	xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
	xmlns:c="urn:schemas-microsoft-com:office:component:spreadsheet"
	xmlns:odc="urn:schemas-microsoft-com:office:odc"
	xmlns:oa="urn:schemas-microsoft-com:office:activation"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:q="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:rtc="http://microsoft.com/officenet/conferencing"
	xmlns:D="DAV:"
	xmlns:Repl="http://schemas.microsoft.com/repl/"
	xmlns:mt="http://schemas.microsoft.com/sharepoint/soap/meetings/"
	xmlns:x2="http://schemas.microsoft.com/office/excel/2003/xml"
	xmlns:ppda="http://www.passport.com/NameSpace.xsd"
	xmlns:ois="http://schemas.microsoft.com/sharepoint/soap/ois/"
	xmlns:dir="http://schemas.microsoft.com/sharepoint/soap/directory/"
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:dsp="http://schemas.microsoft.com/sharepoint/dsp"
	xmlns:udc="http://schemas.microsoft.com/data/udc"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:sub="http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/"
	xmlns:ec="http://www.w3.org/2001/04/xmlenc#"
	xmlns:sp="http://schemas.microsoft.com/sharepoint/"
	xmlns:sps="http://schemas.microsoft.com/sharepoint/soap/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:udcs="http://schemas.microsoft.com/data/udc/soap"
	xmlns:udcxf="http://schemas.microsoft.com/data/udc/xmlfile"
	xmlns:udcp2p="http://schemas.microsoft.com/data/udc/parttopart"
	xmlns:wf="http://schemas.microsoft.com/sharepoint/soap/workflow/"
	xmlns:dsss="http://schemas.microsoft.com/office/2006/digsig-setup"
	xmlns:dssi="http://schemas.microsoft.com/office/2006/digsig"
	xmlns:mdssi="http://schemas.openxmlformats.org/package/2006/digital-signature"
	xmlns:mver="http://schemas.openxmlformats.org/markup-compatibility/2006"
	xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
	xmlns:mrels="http://schemas.openxmlformats.org/package/2006/relationships"
	xmlns:spwp="http://microsoft.com/sharepoint/webpartpages"
	xmlns:ex12t="http://schemas.microsoft.com/exchange/services/2006/types"
	xmlns:ex12m="http://schemas.microsoft.com/exchange/services/2006/messages"
	xmlns:pptsl="http://schemas.microsoft.com/sharepoint/soap/SlideLibrary/"
	xmlns:spsl="http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService"
	xmlns:Z="urn:schemas-microsoft-com:"
	xmlns:tax="http://schemas.microsoft.com/sharepoint/taxonomy/soap/"
	xmlns:tns="http://schemas.microsoft.com/sharepoint/soap/recordsrepository/"
	xmlns:spsup="http://microsoft.com/webservices/SharePointPortalServer/UserProfileService"
	xmlns:mml="http://www.w3.org/1998/Math/MathML"
	xmlns:st="&#1;"
	xmlns="http://www.w3.org/TR/REC-html40">
```

**Comment by Mer0me** [comment]
I agree, there are many problematic cases, but what about escaping all HTML markup of the source mail and parse the resulting as if it was a plain text in order to detect most of the links ?
But you're probably right : it's a lot of work for an obsolete mail client...
I close the ticket.

**Comment by the-djmaze** [comment]
If any newer Outlook (or other client) does the same, we could put some effort into it :wink:
