### ISSUE TITLE
Email search does not work properly

### ISSUE THREAD

**Issue by saroumane38** [the-djmaze/snappymail#403]
Hello
Sorry, this is my 1st bug report, so if you need more information, don't hesitate 

The mail search does not work properly.
For example, it is impossible to search on a part of the sender's address.
e.g.: mail=nomprenom@domaine.fr
searching on "**domaine.fr**" or **@domaine.fr** does not return any results, not even searching on "**nomprenom**".
On the other hand the search on the whole sender (**nomprenom@domaine.fr**) works well.

**Desktop (please complete the following information):**
 - Browser [e.g. chromium 89, firefox 86, safari 14]
 - SnappyMail Version 2.15.3

**Comment by the-djmaze** [comment]
Which mailserver software?

As i see no issues with this in Dovecot.

**Comment by saroumane38** [comment]
> 

Hello
I'm not sure I understand the question
I use 2 different IMAP mailboxes, collected with SnappyMail.
The first one is managed by zoho.com the second one by mailo.com, but I don't know which servers they use.

Neither of the 2 find the search results on a part of the sender address.
Thanks for your answer

**Comment by the-djmaze** [comment]
> e.g.: `mail=nomprenom@domaine.fr`

Aha! Use things like:
* `email=domaine.fr` (search in: from, to, cc)
* `from=domaine.fr` (search in: from)
* `to=domaine.fr` (search in: to, cc)

**Comment by the-djmaze** [comment]
I've just registered at mailo.com and tested it.
This is definitely broken at mailo.com and not something we can fix.

**Comment by saroumane38** [comment]
Thanks for the research.
What info can I give to mailo.com to help them solve the problem?
Have a nice day

**Comment by the-djmaze** [comment]
> What info can I give to mailo.com to help them solve the problem?

1. connect mail.mailo.com:993
2. login
3. run IMAP command `UID SEARCH FROM "mailo" UNDELETED`
Expected result N matches
Actual result: 0 matches
