### ISSUE TITLE
Cannot save `rainloop.user` Sieve script containing `vacation` actions

### ISSUE THREAD

**Issue by tkasch** [the-djmaze/snappymail#407]
**Describe the bug**
It is not possible to store a Sieve script containing a `vacation` action on our IMAP server via the simple/GUI editor.

**To Reproduce**
1. Open existing `rainloop.user` script
2. Click on `Add a Filter` and create a vacation filter similar to the one shown in the first screenshot below
3. Click on 'Done'
4. In the `Edit Script` window, click on `Save`
5. Nothing happens, no error message appears and no clue can be found in SnappyMail's logs or in Apache and PHP logs
6. Closing the window via the `X` button and clicking on `rainloop.user` again gives me a spinning busy indicator in the `Save` button as shown in the 2nd screenshot below. Clicking on the button does not seem to have any effect.
7. Closing, reopening the user settings, and reloading the `rainloop.user` script shows the script unmodified as it was in step 1
8. It is possible to successfully save `rainloop.user` when adding a `moveto` action instead of `vacation`. But if I had an unsuccessful attempt saving a vacation filter in the same SnappyMail session, I have to log out and in again to make saving a script work again.

**Expected behavior**
It should be possible to successfully save the `rainloop.user` script containing `vacation` actions.

**Screenshots**
![snappy-vacation-1](https://user-images.githubusercontent.com/5294914/169255397-929d523e-dead-4e67-97a7-d0fd478ea170.png)
![snappy-vacation-3](https://user-images.githubusercontent.com/5294914/169256991-4a9b654b-f2a7-418b-a23b-89ba1251c09f.png)

**Desktop (please complete the following information):**
 - Browser Firefox 98.0 on Ubuntu 20.04
 - SnappyMail master-branch as of 2022-05-18
 - IMAP-Server: Cyrus 3.0.13 as shipped with Ubuntu 20.04

**Comment by perler** [comment]
so, is this closed or a bug? I experience the same when creating a simple forward in rainloop.user. (I use cloudron, which uses this git repo as far as I know)

**Comment by tkasch** [comment]
As of SnappyMail 2.16.3, storing a vacation rule works for me as expected...
