### ISSUE TITLE
2.16.0: No login due to PHP fatal in Providers/AddressBook/PdoAddressBook.php:495

### ISSUE THREAD

**Issue by veitw** [the-djmaze/snappymail#409]
**Actual behavior:**
After upgrading 2.15.3 to 2.16.0, logging in into admin panel is no longer possible, webmail does not work if contacts feature is enabled. PHP throws fatal and httpd returns HTTP 500. See log below.

**Expected behavior:**
Snappymail not dying.

**SnappyMail version, browser, browser version:**
Snappymail 2.16.0, Firefox 101, tried both PHP 8.0 and 7.4

**Steps to reproduce the problem:**
Upgaded existing 2.15.3 installation to 2.16.0.
The problem also still appeared after starting over with a fresh `application.ini` for the admin panel login, and also returned for webmail login again after contacts feature had been re-enabled in `application.ini`.

**Logs or screenshots:**
```
PHP Fatal error:  Declaration of RainLoop\Providers\AddressBook\PdoAddressBook::DeleteAllContacts(): bool must be compatible with RainLoop\Providers\AddressBook\AddressBookInterface::DeleteAllContacts(string $sEmail): bool in /var/www/webmail/public/snappymail/v/2.16.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php on line 495
```

**Comment by veitw** [comment]
#408 seems to describe the same problem, but from the client side.

**Comment by tkasch** [comment]
It's most likely not the correct fix, but simply adding a string parameter to the declaration of `function DeleteAllContacts()` makes the login work again for now...
