### ISSUE TITLE
Inconsistent labelling: "Identities" vs. "Accounts"

### ISSUE THREAD

**Issue by tkasch** [the-djmaze/snappymail#410]
**Describe the bug**
On the user's settings page there is a section labelled `Accounts`. Selecting it reveals a section with the heading `Identities`.

**To Reproduce**
1. Go to the user's settings
2. Click on `Accounts` on the left
3. See the section with the heading `Identities` and a button labelled `Add an Identity`

**Expected behavior**
The section `Accounts` should renamed to `Identities` since this would would match the wording found in other MUAs like RainLoop and Thunderbird.

**Desktop (please complete the following information):**
 - Browser Firefox 98.0 on Ubuntu 20.04
 - SnappyMail 2.16.0

**Comment by the-djmaze** [comment]
Depends how you look at it.

I also use Kmail/Kontact and that has:
![afbeelding](https://user-images.githubusercontent.com/3752035/169315116-eb41e29b-b58d-473a-8617-61c6159836c7.png)

In SnappyMail ?admin you have this:
![afbeelding](https://user-images.githubusercontent.com/3752035/169315406-f66b4d77-06a0-4d80-b5b9-57a63da2cde9.png)

When `Allow additional accounts` is `On` the user settings page has:
![afbeelding](https://user-images.githubusercontent.com/3752035/169315677-74d498b7-9b98-4b06-ab31-6c11e6c471bf.png)

When `Allow multiple identities` is `On` the user settings page has:
![afbeelding](https://user-images.githubusercontent.com/3752035/169315872-045bb44d-149a-410c-91f7-d5f036bc2eff.png)

So there is no real inconsistent labeling, its just confusing in one case:
* `Allow additional accounts` is `Off` and
* `Allow multiple identities` is `On`

**Comment by tkasch** [comment]
Ok, I see. I wasn't aware that the labels were dynamic. In our RainLoop installation (on which our current SnappyMail config is based upon) this did not seem to be the case?

> So there is no real inconsistent labeling, its just confusing in one case:
>     * `Allow additional accounts` is `Off` and
>     * `Allow multiple identities` is `On`

This is exactly our setup since we want to provide access to our own mail service only for our users.

**Comment by the-djmaze** [comment]
I made a change that in your case the label is `Identities`

**Comment by tkasch** [comment]
Great! Thanks a lot!
