### ISSUE TITLE
Reopen "Lost spaces in formated text after save and reopen"

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#414]
Describe the bug:
Still like: #364 but 
A space inserted after formatted text get last after save and re-open/edit the message.

To Reproduce

    Insert
    1 2 3
    to message body. One space-char between the numbers.
    Set "2" to bold
    Save and close the message.
    Open and edit the message

Expected behavior
Message body is: 1 2 3
but is: 1 23

The space-char between 2 and 3 is vanished.

![grafik](https://user-images.githubusercontent.com/41056353/169337743-a0aea783-7f35-40ba-8a64-b89b9d0ebf6c.png)
First line: before save and re-open
Second line: after.

Desktop (please complete the following information):

    Browser Firefox: 100.0.1
    SnappyMail Version 2.15.3

**Comment by the-djmaze** [comment]
I have no issue with Firefox 98, i will update and try again

**Comment by Parodontitis** [comment]
Same issue with 
- Firefox 100.0.2 (windows) and 
- Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by phsc84** [comment]
Can confirm this issue in Chrome 101.0.4951.67. To reproduce it, you have to set one number to bold and only the space after the bold number is lost. Interestingly you have to open the mail into the edit window to get the issue. In the preview on the right pane, the text is correctly displayed.

**Comment by the-djmaze** [comment]
I've added the issue to the demo, but somehow i can't reproduce it.
So maybe test there?
https://snappymail.eu/demo/#/mailbox/Drafts

**Comment by Parodontitis** [comment]
> So maybe test there? https://snappymail.eu/demo/#/mailbox/Drafts

I can't reproduce the problems on the demo environment. So the problem is to be found in the environment configuration. I'll post my PHP configuration later. Thank you.

**Comment by the-djmaze** [comment]
@Parodontitis could it be you have PHP Tidy extension?

**Comment by Parodontitis** [comment]
Bug is fixed now.
