### ISSUE TITLE
RFE: verification code should be requested only from users who have set up 2FA

### ISSUE THREAD

**Issue by tkasch** [the-djmaze/snappymail#415]
**Is your feature request related to a problem? Please describe.**
If the `Two Factor Authentication` extension is enabled, the login screen always shows the input field for the TOTP code along with those for e-mail an password. Since it's up to the users if they enable 2FA for their account or not, it would be if only users who have actually set it up are prompted for the verification code.

**Describe the solution you'd like**
Requesting the verification code should be delayed until the user has entered his/her credentials so it's possible to suppress it completely if 2FA has not been set up.

**Comment by the-djmaze** [comment]
In an ideal world that would be the case (just like here on github).
However, 2FA is a false sense of security in mail app because:
1. attempt to login (brute force) to find password
2. when found, ignore 2fa and use other application

So, asking 2FA immediately will prevent hackers to find valid password to use anywhere else.

**Comment by the-djmaze** [comment]
Also read #84

**Comment by tkasch** [comment]
Understood. But brute force attempts can (and should) be mitigated by other means like deploying tools like `fail2ban`.

**Comment by the-djmaze** [comment]
True, but how to instruct everyone to secure their instances while they have no clue how to use fail2ban?
There are always worse case scenarios and we need to figure out how to solve them.

Showing TOTP  in separate window after login might be possible.
But then hitting F5 you will be logged in and can access without the 2FA.
Needs more thought how to solve this.
After that, the plugin admin settings could have an option: Show TOTP input at login or after.

**Comment by tkasch** [comment]
The longer I think about it, the more I come to the conclusion that it's probably best to leave the 2FA login as it is right now. It's only a matter of providing adequate documentation for the users after all...

Anyway, thanks a lot for your great work on this project! I'm really happy to see how SnappyMail has evolved since I learned about it just a few weeks ago!
