### ISSUE TITLE
Ability to view and edit configured filters

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#416]
It would be nice if the ability to view and edit configured filters was added to it.

**Comment by the-djmaze** [comment]
Please explain

**Comment by Zero3K** [comment]
I have filters that were set up in a different webmail UI which I cannot change/remove at the moment.

**Comment by the-djmaze** [comment]
It is probably due to an error in the Sieve parser/verify script.
As i currently have no such errors, it would be nice if you can provide the error.

**Comment by Zero3K** [comment]
I do not have access to the error / source. I sent a link of this issue to uncled1023 a while ago. You will need to contact him.

**Comment by Zero3K** [comment]
Why was this closed as completed?

**Comment by the-djmaze** [comment]
Didn't you check if it still fails?

**Comment by Zero3K** [comment]
He didn't update to the latest version yet.

**Comment by the-djmaze** [comment]
Ok, when he does. Then report if still is an issue.
