### ISSUE TITLE
From input when making new mail

### ISSUE THREAD

**Issue by Furrypaw** [the-djmaze/snappymail#420]
I have started moving process from rainloop to snappymail and it seems like snappymail allows to edit the FROM when creating a email. Is there a way to disable the ability and just leave the current user email address there. (Like in rainloop)

**Comment by the-djmaze** [comment]
Please read  #202

**Comment by Furrypaw** [comment]
> Please read #202

Thanks for point out the #202 I see that the future is enabled from version 2.12.2 however I dont really see there a way to disable it.

**Comment by the-djmaze** [comment]
Currently it is not possible to disable (because it's always possible outside SnappyMail unless server admin disabled it in the SMTP server).

So, do you want to disable as admin or as user?

**Comment by Furrypaw** [comment]
Wanted to disable as admin on snappymail installation wide. I have already disabled the ability on SMTP level so sending mails with anything but own email fails. But I would prefer if users had no ability to change the from field to begin with.

**Comment by the-djmaze** [comment]
I thought about this and the best way to solve your request is to disable it when identities is disabled.
Because when identities is enabled, it is still possible to modify the sender.

**Comment by Furrypaw** [comment]
I have now set allow_additional_identities = Off, however the From is still being rendered as active input.

**Comment by the-djmaze** [comment]
> From is still being rendered as active input.

Correct, as it was not implemented.
I just made the change.
