### ISSUE TITLE
missing plugins in admin interface

### ISSUE THREAD

**Issue by derStephan** [the-djmaze/snappymail#424]
**Describe the bug**
In the update interface, the following plugins are shown: 

![grafik](https://user-images.githubusercontent.com/7764931/171002752-5271c635-f82a-4dbf-a258-40f3e921ffe7.png)

In plugin folder there are a lot more plugins available.

**Desktop (please complete the following information):**
 - Browser firefox 100.2
 - SnappyMail Version 2.16.1

Why are these plugins missing? Does the list in admin interface update itself?

**Comment by the-djmaze** [comment]
It's true that not all plugins are visible in admin.
It's because not all plugins are converted yet.

**Comment by derStephan** [comment]
I see. So this is on purpose and not a bug. Thanks.
