### ISSUE TITLE
PGP signing issue "Key packet is already decrypted"

### ISSUE THREAD

**Issue by Dual-0** [the-djmaze/snappymail#429]
Hello,

I recently added my OpenPGP-key for signing. When I check the signing checkbox in the new mail dialog and send the mail, snappymail ask me for an password. The OpenPGP-key has no password so I leave it blank. This results in the error message:
`Error: Error decrypting private key: Key packet is already decrypted`

Expected behavior:
Add PGP-Keys with or without passwords

Screenshot:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/37346547/172048171-ade8777b-b4a4-4615-a47e-abf2661deb9c.png">

thanks in advance

**Comment by the-djmaze** [comment]
System was only tested with keys that have a password.
This, because storing the key on the server without encryption makes it easier for non-authorized people to sign and decrypt your personal messages.

I will think about it, where/how to allow unencrypted private keys (without password).

**Comment by the-djmaze** [comment]
Added to #89 as TODO point
