### ISSUE TITLE
Install plugins via command line? 

### ISSUE THREAD

**Issue by jaapmarcus** [the-djmaze/snappymail#430]
**Is your feature request related to a problem? Please describe.**

I am currently working on a replacement for Rainloop in HestiaCP

I want to enable a few "Modules" by default after a user installs Snappymail over command line

Setting default config is possible via:

```
<?php
$_ENV['SNAPPYMAIL_INCLUDE_AS_API'] = true;
include '/var/lib/snappymail/index.php';

use \RainLoop\Config\Config;
use \RainLoop\Config\Config\Application;

$oConfig = \RainLoop\Api::Config();
    
// Change default login data / key
$oConfig->Set('security', 'admin_login', $argv[1]);
$oConfig->Set('security', 'admin_panel_key', $argv[1]);
$oConfig->SetPassword($argv[2]);
// Allow Contacts to be saved in database
$oConfig->Set('contacts', 'enable', 'On');
$oConfig->Set('contacts', 'allow_sync', 'On');
$oConfig->Set('contacts', 'type', 'mysql');
$oConfig->Set('contacts', 'pdo_dsn', 'mysql:host=127.0.0.1;port=3306;dbname=snappymail');
$oConfig->Set('contacts', 'pdo_user', 'snappymail');
$oConfig->Set('contacts', 'pdo_password', $argv[3]);
```

If I want to install install a plugin I can use:

```
use \Snappymail\Repository;
\Snappymail\Repository::installPackage('plugin','add-x-originating-ip-header','plugins/add-x-originating-ip-header-2.0.tgz');
```

How that doesn't work due to the HTTP_HOST not present and even by "Fakeing" it runs still in:

PHP Fatal error:  Uncaught RainLoop\Exceptions\ClientException: AuthError[102] in /var/lib/rainloop/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Admin.php:27

**Describe the solution you'd like**

The ability to run certain admin commands via command  would be great. 

**Describe alternatives you've considered**

Offcourse I can download the "files" directly from https://snappymail.eu/repository/v2/ ...  and unzip and only enable the plugin via command line 

**Additional context**

Any suggestions how to "Solve" it ?

**Comment by the-djmaze** [comment]
Does the above change solve your problem?

**Comment by the-djmaze** [comment]
Also with `getPackagesList()` so you can install the right version of plugins?

**Comment by jaapmarcus** [comment]
> getPackagesList

Yes it does.

```
array(3) {
  ["Real"]=>
  bool(true)
  ["List"]=>
  array(15) {
    [0]=>
    array(11) {
      ["type"]=>
      string(6) "plugin"
      ["id"]=>
      string(27) "add-x-originating-ip-header"
      ["name"]=>
      string(16) "X-Originating-IP"
      ["installed"]=>
      string(0) ""
      ["enabled"]=>
      bool(true)
      ["version"]=>
      string(3) "2.0"
      ["file"]=>
      string(43) "plugins/add-x-originating-ip-header-2.0.tgz"
      ["release"]=>
      string(10) "2020-11-01"
      ["desc"]=>
      string(81) "Adds X-Originating-IP header to outgoing message, containing sender's IP address."
      ["canBeDeleted"]=>
      bool(false)
      ["canBeUpdated"]=>
      bool(true)
    }
    [1]=>
...
```


Is it possible to search on plugin name instead providing

"plugin", reporul

**Comment by jaapmarcus** [comment]
Even better 👍🏼

**Comment by the-djmaze** [comment]
> Any idea when the next version gets released including the new plugins?

Depends. I'm waiting on feedback for #419
