### ISSUE TITLE
Gmail login? 

### ISSUE THREAD

**Issue by Augustinus-Altovadensis** [the-djmaze/snappymail#433]
Hi, after Google deactivated the legacy login option to the Gmail Account, I tried installing SnappyMail. I have set it up, other mail services work just fine, but an attempt to connect to Gmail results in following message: 
```
Can't connect to server
Can't connect to host "tcp://localhost:143"
```
This is what I saw before setting up the Domains in the admin panel, but the Google Domain is set up with correct data.

Is there something wrong with my setup, or it just doesn't work and I can stop trying? 

Thanks for the answer!

**Comment by the-djmaze** [comment]
Does the following work for you?
https://github.com/the-djmaze/snappymail/issues/372#issuecomment-1119587132

**Comment by Augustinus-Altovadensis** [comment]
> Does the following work for you? [#372 (comment)](https://github.com/the-djmaze/snappymail/issues/372#issuecomment-1119587132)

Well, I have the same settings as in the comment, the Test button says everything works, but then, when I enter the credentials (right or wrong), the above mentioned message pops up. Which is strange. Also it seems that the problem is on localhost, in the comment, the problem is at Google's side. 

It might have something to do with Google banning username+password login, that's also why I asked, whether it works at all...

**Comment by Augustinus-Altovadensis** [comment]
> Less secure applications are banned by Google since end of May (https://support.google.com/accounts/answer/6010255?hl=en) AFAIK you can generate App password and use it (https://support.google.com/mail/answer/185833?hl=en)

Thanks, that works! Well, sort of. The good news is that I can log in again, the bad news is, that only in the old RainLoop, in Snappy, it only shows the same message. Strange. But thanks for that suggestion, it solved the bigger part of my problem!

**Comment by the-djmaze** [comment]
As of v2.17.1 you can test login credentiels in admin => domains => domain
If that works the issue is not Gmail but probably something else.

**Comment by elhananjair** [comment]
Hello, @the-djmaze I am having this issue even when I use app password. Everything is fine when I test it from admin

![Screenshot from 2022-10-25 21-39-10](https://user-images.githubusercontent.com/69236638/197855874-2af751b0-90b0-4a94-b96b-afb75fc72787.png)
---
![Screenshot from 2022-10-25 21-40-01](https://user-images.githubusercontent.com/69236638/197857407-55a0f3d4-c799-4b6a-831d-0a7d7b780f32.png)

**Comment by the-djmaze** [comment]
@elhananjair domain should be `gmail.com` not `imap.gmail.com`

**Comment by elhananjair** [comment]
hello @the-djmaze it doesn't pass the test with `gmail.com` but it does with imap.gmail.com as I attached the attachment above.
![image](https://user-images.githubusercontent.com/69236638/199090360-91919c2e-96ad-46c3-affd-66daa2576620.png)

**Comment by the-djmaze** [comment]
@elhananjair read from here:
https://github.com/the-djmaze/snappymail/issues/372#issuecomment-1119587132

**Comment by elhananjair** [comment]
@the-djmaze Sorry but I have tried everything I can and still have not succeeded in signing in to my Gmail account. The test passes when I try it with my email and app password, but when I try to add an account or try to log in it still shows me the same error. 

![image](https://user-images.githubusercontent.com/69236638/199838925-9ba38f36-1288-45fa-a610-318437ce00dd.png)
---
![image](https://user-images.githubusercontent.com/69236638/199838943-bf593eef-6d2d-4c07-929f-db23c43b9199.png)
---
![image](https://user-images.githubusercontent.com/69236638/199838990-5b66cd0b-d255-448d-9702-3f7177fdb16f.png)
