### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by hiensarahly** [the-djmaze/snappymail#435]
Hey guys,

Pls consider adding the Vietnamese language to the webmail. Or how may I contribute to the translation, if that option’s available?

Just started using SnappyMail, loving it.

Thanks!

Hien

**Comment by the-djmaze** [comment]
You can clone the project, add the files, then do a pull request.
But if that is difficult, you can just attach your modified files here in a zip.

For both you do:
1. copy `snappymail/v/0.0.0/app/localization/en` to `snappymail/v/0.0.0/app/localization/vi-VN`
2. now translate

**Comment by hiensarahly** [comment]
pls see:

[vi-VN.zip](https://github.com/the-djmaze/snappymail/files/8883722/vi-VN.zip)

Thanks man!

**Comment by the-djmaze** [comment]
Thanks, i've added it
