### ISSUE TITLE
message thread sorting choice 

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#445]
Message thread seem to be always sorted from oldest to newest.
This is inconsistent with the message list sorting. And if you read newest from oldest and get very long thread, getting to latest update might be not convenient. 

**To Reproduce**
In messages thread, change the sorting order, notice it has no effect while it works perfectly the on the usual message list. 

**Desktop (please complete the following information):**
 - Browser  Firefox 101
 - SnappyMail 2.6.13

Regards,
(thanks again for this great piece of software)

**Comment by yeupou** [comment]
Hi,

Very nice addition, MessageList now grouped/split per day in #737

However, it makes even more annoying the issue with the inability to sort anything within a message thread view: now within message thread, the list appears unchronological (so the dates printed makes it very strange).

**Comment by jas8522** [comment]
> However, it makes even more annoying the issue with the inability to sort anything within a message thread view: now within message thread, the list appears unchronological (so the dates printed makes it very strange).

Same issue here :(

With "List messages per day" enabled (which it is by default now), it shows the days in the correct order - Today, Yesterday, etc. However messages within each day are sorted from morning to night (oldest to newest) even when the sorting is specifically configured as "Date Descending" (though changing those sort options does nothing at all in this view).

It might be best for this feature to not be enabled by default until this can be sorted out (hah).

**Comment by the-djmaze** [comment]
I will look at the thread code and possibilities of IMAP.
If not i will use the threads UID cache for a workaround.

**Comment by jas8522** [comment]
The issue I'm referring to doesn't apply strictly to threaded messages. It's just with regular single emails when the group by day option is enabled. 

If I look at a mailbox with more than one message per day, it will have TODAY at the top, then within that will be messages sorted oldest to newest. And the sorting button in the toolbar does nothing - click on it and select any sort option and the message order never changes.

**Comment by the-djmaze** [comment]
Improved the threaded view
![afbeelding](https://user-images.githubusercontent.com/3752035/209659612-82b490d2-871c-4eaf-bc7d-c9fa2b24a8cb.png)

**Comment by jdaviescoates** [comment]
#843 would also help with this

**Comment by yeupou** [comment]
Regard thread view, when the list of message is very long, scrolling down makes the small arrow to stay where they were rendered first, no matter how much we scroll. Not blocker but odd.

**Comment by trojkat** [comment]
I've migrated from RainLoop, where sorting worked for threads. Now, for long-running threads (newsletter), I need to switch to the 15th page each time to find the latest email. Does this mean that RainLoop was also making copies?
