### ISSUE TITLE
Quick unread filter

### ISSUE THREAD

**Issue by soda-pop-ice-cream** [the-djmaze/snappymail#447]
Hello!
Is it possible to add 1 click unread filter?

![librewolf_7uK3hGuRif](https://user-images.githubusercontent.com/80998901/176078138-d83b9181-3f10-4456-96d9-fb99fa7132d3.png)

In my opinion when you clicking on "Inbox" it should take you to inbox directory itself, but when you click on unread count (number 5 on my screenshot) it should take you to directory + apply "unseen" filter.

**Comment by the-djmaze** [comment]
Currently this is not possible because the "unseen" counter is not an HTML element.

**Comment by the-djmaze** [comment]
Added by using a ClientRec area of 25 pixels
