### ISSUE TITLE
No access to extensions [solved]

### ISSUE THREAD

**Issue by emos321** [the-djmaze/snappymail#449]
After upgrading from rainloop to snappymail, everything works except extensions view. I have enabled js logging and I have such an error
![Screenshot_19](https://user-images.githubusercontent.com/33941097/176422185-ac1006c5-952a-442b-9d46-c2365319db2f.png)

**Comment by emos321** [comment]
thanks, it works!

![Screenshot_20](https://user-images.githubusercontent.com/33941097/176432228-8986d10a-4720-45d0-bdf4-9b8fc3c194b5.png)

Now I have a problem because I don't see the recaptcha plugin and it is visible on github as available 

![Screenshot_21](https://user-images.githubusercontent.com/33941097/176432301-38349390-3864-430f-96fb-ea91ac3b5a9a.png)

**Comment by kouinkouin** [comment]
Idem on my instance, but I don't know the cause, sorry.
I guess you use the last version?

**Comment by emos321** [comment]
I don't have the latest version installed
I downloaded recaptcha from github and unpacked it in plugins and it works too.

Thanks again for your help
