### ISSUE TITLE
sieve edit issue

### ISSUE THREAD

**Issue by liedekef** [the-djmaze/snappymail#45]
**RainLoop version 2.1.0, firefox 79 on fedora 33, server ubuntu 20LTS:**

**Expected behavior and actual behavior:**
When editing a sieve rule, the filter being shown ( in my case I filtered on recipient containing a string) is being reset to a from-filter containing nothing. The sieve-file on the server is ok when saved, so I assume this has something to do with reading/parsing the sieve rules.

**Comment by the-djmaze** [comment]
I've found the problem i created by converting to an easier JSON serialization.
The Sieve script also stores JSON and that was overlooked and therefore it fails.
To stay compatible with RainLoop a change is reversed.

**Comment by the-djmaze** [comment]
Here's the release: https://github.com/the-djmaze/snappymail/releases/tag/v2.1.1
