### ISSUE TITLE
RFC: using composer to manage certain third-party libraries

### ISSUE THREAD

**Issue by Westie** [the-djmaze/snappymail#450]
Hi @the-djmaze, I'm in the process of rewriting the OIDC functionality in order to work with providers that aren't Google and I've noticed that it's slightly uncomfortable to bundle in additional files.

Looking at the sample OIDC code that is there at present, it merely exists and I can't see it actually working due to missing library files.

Therefore, what are your thoughts on managing certain dependencies via Composer? Can't see this being too big an issue as at present there's a build script that will build everything and all the third party libraries can be bundled without too much of a hassle

**Comment by the-djmaze** [comment]
RainLoop was bundled with an outdated [PHP-OAuth2](https://github.com/adoy/PHP-OAuth2).
OIDC uses also other things that are not part of OAuth2.

That's why it's not working and i haven't looked at a solution as of yet.

**Comment by the-djmaze** [comment]
I've added the old library inside the plugin so you know how to use it with your own spl_autoload_register() and/or set_include_path()
