### ISSUE TITLE
RFC: how to handle cookie sizes larger than 4kb? can't log in!

### ISSUE THREAD

**Issue by Westie** [the-djmaze/snappymail#451]
I've come across a very quirky bug that's to do with cookie sizes on browsers - if the account object is serialized to a cookie, and the cookie is larger than 4kb (because there is a bearer token within it), you're left not able to log in.

The only thing I can think of is split up cookie data within the `Utils::GetCookie` and `Utils::SetCookie` but this seems a rather silly idea.

Snappymail/Rainloop appears to not use PHP sessions so if anyone has any better suggestions (that does not involve magic such as local file storage) I would be welcome to hear them!

**Comment by Westie** [comment]
Here is what I have so far and it allows me to connect via XOAUTH2 at the moment - can't get OAUTHBEARER working because the dovecot is being stupid

![](https://ss.westie.sh/iwDNo)
![](https://ss.westie.sh/dl55p)

**Comment by the-djmaze** [comment]
I understand what you are saying.
Although RFC 2965, the document that defines how cookies work, specifies that there should be no maximum length of a cookie's key or value size. browsers do seem to have a limit you hit.

There are several cookies:
```
$AUTH_ADMIN_TOKEN_KEY = 'smadmin';

AUTH_MAILTO_TOKEN_KEY = 'smmailtoauth';
AUTH_SIGN_ME_TOKEN_KEY = 'smremember';
AUTH_SPEC_TOKEN_KEY = 'smaccount';
AUTH_ADDITIONAL_TOKEN_KEY = 'smadditional';
AUTH_SPEC_LOGOUT_TOKEN_KEY = 'smspeclogout';
AUTH_SPEC_LOGOUT_CUSTOM_MSG_KEY = 'smspeclogoutcmk';

CONNECTION_TOKEN = 'smtoken',
SESSION_TOKEN = 'smsession';
```

I will look into each if there should be a general solution because there´s also a maximum amount of cookies (50 on Android).

**Comment by Westie** [comment]
Turns out that when I was looking at setting up the OAuth tokens, I didn't use the `openid` scope

The size of the token almost doubled from 4k chars to like, 10k characters? 🙈 

I've only found this to be an issue with `AUTH_SPEC_TOKEN_KEY` - presumably it would be an issue with `AUTH_ADDITIONAL_TOKEN_KEY` but they're both secret keys so that's covered by the changes.

I can't see this change needing to occur on the non-secret cookies.

**Comment by Westie** [comment]
> One solution might be gzip, but that would not be enough i think.

Nowhere near unfortunately, I've tried that!

**Comment by the-djmaze** [comment]
PHP sessions could be an option but that would mean the data and decryption key are both on the server (which makes it less secure).

Thinking the other way round could be: (de/en)crypt key is the cookie and data on server

**Comment by Westie** [comment]
I had avoided introducing sessions into the mix as I thought that there unwritten security reasons why sessions weren't a thing

**Comment by the-djmaze** [comment]
Right, sessions could be a thing (especially with the less secure XXTEA).
I will also tinker with some options, but for now yours looks the best.

**Comment by Westie** [comment]
Very nice!
