### ISSUE TITLE
Spam Score is always there and red....

### ISSUE THREAD

**Issue by nomadturk** [the-djmaze/snappymail#456]
I can see the spam score always inside all my emails.
It's RED color is frightening and confusing to users.

Also, when you click on "i" all mails have 100% spam score for some reason

1
![Screenshot_20220717_141440](https://user-images.githubusercontent.com/10355660/179395673-2e11a698-f374-45d7-841b-6dea2a68be8d.png)

2
![Screenshot_20220717_141449](https://user-images.githubusercontent.com/10355660/179395674-19f3a1db-46ff-4a1c-9d4f-5820e143e212.png)

3
![Screenshot_20220717_141814](https://user-images.githubusercontent.com/10355660/179395676-4cead3ac-5cd0-4319-b657-89352d1615f9.png)

**Comment by nomadturk** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/10355660/187088661-14682d2b-3fb9-4490-bc40-5061f3fb10f6.png">

This issue still continues with some of the emails.

**Comment by the-djmaze** [comment]
Could you show the mail source lines that set the bogosity?

**Comment by the-djmaze** [comment]
Strange, as the changes i made should only analyze `X-Bogosity: Ham, spamicity=0.006306` as not being spam.

Could you check the "fetch messages" JSON repsonse?
![afbeelding](https://user-images.githubusercontent.com/3752035/187180459-10436d21-1d68-47d6-ba3a-e6b89dc2610d.png)
