### ISSUE TITLE
Empty lines disappear after formatting

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#462]
**To Reproduce**
1. Write a new mail with some empty lines between the sentences.
2. Format the text, e.g. set it to bold or italic. Everything looks ok in the compose window.
3. Send the mail.
4. Open the sent mail. The empty lines between the sentences disappeared.

**Expected behavior**
Formatting some text should not affect line breaks or empty lines.

**Desktop (please complete the following information):**
 - Chrome 103
 - SnappyMail 2.16.3

**Comment by the-djmaze** [comment]
Does this commit change solve your issue?

**Comment by phsc84** [comment]
No, unfortunately it is still the same behaviour after applying this patch.

**Comment by the-djmaze** [comment]
Yes, it's hard to test as you need to compile the javascript.

The demo on snappymail.eu has the changes

**Comment by phsc84** [comment]
Unfortunately it still does not work on the demo site. You can check the mail with the subject "test".

**Comment by the-djmaze** [comment]
Great!
I see the source to work with:

```
<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8"></head><body><div><b>test</b></div><div><b><br=
></b></div><div><b>test</b></div></body></html>
```

I can work with that.

**Comment by phsc84** [comment]
Are the previous changes still ok or should they be reverted?

https://github.com/the-djmaze/snappymail/commit/4238834cb5fdc9b7387813e62bb9296834ff2f09
=> this one is probably ok

https://github.com/the-djmaze/snappymail/commit/f7555abed7afa7f9551d9687779beed71c0c8634
=> shouldn't this be reverted as it only commented some code?
