### ISSUE TITLE
Multiple empty lines are replaced by only one after saving as draft

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#463]
**Describe the bug**

Create a new message in text mode only and put this content : 

```
LINE 1


LINE 4





LINE 10
```

Save it, so that the email is stored in Draft folder.

Go into the Draft folder and display the draft : the draft is well saved.

Now, edit the draft to continue to write you email, the multiple empty line are now only one line : 

```
LINE 1

LINE 4

LINE 10
```

**Expected behavior**

The empty line are preserved.

**Desktop (please complete the following information):**
 - Browser Firefox 102 Ubuntu
 - SnappyMail Version 2.17.0

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/commit/4238834cb5fdc9b7387813e62bb9296834ff2f09
