### ISSUE TITLE
Confusing date format

### ISSUE THREAD

**Issue by chascode** [the-djmaze/snappymail#465]
**Describe the bug**
The date displayed in the email list shows the month before the day, which is confusing when the day looks like a year.  For example: "Jul 20" looks like I received the email on July 2020 when in fact I received it the other day.

**To Reproduce**
Look at the date displayed next to each email's subject.

**Expected behavior**
The day of month displayed before the month itself.

**Screenshots**
The following screenshot shows emails received on the 22nd of July, but displayed as Jul 22:

![Screenshot_2022-07-24_23-42-45](https://user-images.githubusercontent.com/52451714/180668816-51d57ef3-1fe1-40fa-a424-18087a3b7035.png)

**Comment by the-djmaze** [comment]
The format relies on the internationalization settings of your browser.
Which language is your OS?
Which language is your browser?
Which language in SnappyMail?

**Comment by phsc84** [comment]
It is the same for me. I have set "English".
![image001](https://user-images.githubusercontent.com/2138442/180712913-bc311f25-3967-4371-9273-8d5d6bf04934.png)

**Comment by the-djmaze** [comment]
The ordinal suffix is not shown with JavaScript Intl.
Normally, in English, it should be like: "Oct 12th".

> **Expected behavior**
> The day of month displayed before the month itself.

When you are not a native English speaker and your format is like "12 Oct", i understand that the format is a bit confusing.
When you set SnappyMail to your native language, it's should not be confusing.

**Comment by chascode** [comment]
Thanks for the reply.

> The format relies on the internationalization settings of your browser. Which language is your OS? Which language is your browser? Which language in SnappyMail?

OS: English (UK)
Browser: English (UK)
SnappyMail: English

**Comment by the-djmaze** [comment]
Ah, right!
I will ad `en-GB` as current `en` is US format

**Comment by chascode** [comment]
> Ah, right! I will ad `en-GB` as current `en` is US format. But will check if `en-US` would be better based on Javascript Intl tests.

Thanks, Rainloop has an option for "English (UK)" if that helps?

**Comment by the-djmaze** [comment]
I've added `en-GB` and  the day format is correct in my Firefox.
So it seems `en` defaults to US format.

**Comment by chascode** [comment]
I manually applied the changes of the commit (overwrote "v/2.16.3/app/localization/en-US/user.json" and added "v/2.16.3/app/localization/en-GB/user.json") and everything works perfectly.

Thanks.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.17.1
