### ISSUE TITLE
Invalid Attachments (PDF)

### ISSUE THREAD

**Issue by albsch** [the-djmaze/snappymail#466]
Recently attachments stopped working properly. Neither preview, nor downloading a PDF works. I can confirm that using another IMAP client the same attachment opens and downloads properly. 

Here is a diff for a PDF which was once downloaded with Snappymail (`error.pdf`) and once with another mail client (`valid.pdf`). It seems that for the corrupt PDF something is missing at the end of the file.

```shell
❯ ls
error.pdf  valid.pdf
❯ xxd error.pdf > d1
❯ xxd valid.pdf > d2
❯ diff d1 d2
29184c29184,29187
< 00071ff0: 3868 0494 bdc6 dc3e 89fc                 8h.....>..
---
> 00071ff0: 3868 0494 bdc6 dc3e 89fc 0115 832c 5d0a  8h.....>.....,].
> 00072000: 656e 6473 7472 6561 6d0a 656e 646f 626a  endstream.endobj
> 00072010: 0a73 7461 7274 7872 6566 0a34 3636 3631  .startxref.46661
> 00072020: 340a 2525 454f 460a                      4.%%EOF.
```

Affects at least versions `2.15.x` and `2.17.x`.

**Comment by ner00** [comment]
This has to be very specific, it's working fine for me.

**Comment by the-djmaze** [comment]
To know why your IMAP server is not transferring the whole file, we need some debug info.
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

Also clear the `/_data_/_default_/cache` folder.

**Comment by kurti500** [comment]
I seem to have a similar issue recently: preview not working for some pdfs, downloading the pdf attachment results in a 0kb file.

**Comment by the-djmaze** [comment]
I found the above MailSo bug at AfterLogic, maybe it solves it.

**Comment by albsch** [comment]
Updating from `2.17` to `2.18.5` fixed the issue, I think. I'll reopen if I encounter it again.

**Comment by albsch** [comment]
Still happening. A recent PDF with size `185kb` is downloaded as size `181kb` and corrupted.

**Comment by the-djmaze** [comment]
Is there a way you can place the EML here so i can take a look?

**Comment by simonbuehler** [comment]
fwiw: with nextcloud i get `Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").` when trying to view a pdf attachement , works with rainloop 

url is like `https://cloud.x.de/apps/snappymail/run/?/Raw/&q[]=/0/Download/&q[]=/b3BlbnNzbA.euPIkNeIOTvTqX9X-H-lhQ.ITRU-LTSTmriBjkHByALfQ9yZ3OT_AngUGYHEV-N2hKNoGSWu4qA6e-ul8hooe4FQi9xhwG-OjWTGMtIJbyh_5fuIX0pKUpy2uvK4K3BsySHNVfR35e9I8jK3VT9fJGkVxNCv7O-3sIUOmCC-SRyrcBkY0CS3_HCvSjxjM_KYmWrk6F5eTAim6fGonqB4kd0_1quRPehsHYpzyEuXlpPyY1FSQTR0WeL8PKie_eq1uEBvWtS31oqWsK5RdVHsQBHzvMf3drsuuUDoOO-374K-yh64-RknRlePwSXqvtfQ1A`

**Comment by the-djmaze** [comment]
@simonbuehler your comment is not related to this issue.
It's related to issue #566

**Comment by the-djmaze** [comment]
I've found a code flow that breaks attachment.
It is partially solved but i need to analyse a few more things regarding the message caching.

**Comment by Pit-Storm** [comment]
Hi @the-djmaze!
Thanks for that amaizing project! I really enjoy it and the NC community really deserved a successor of the "original" rainloop plugin 🎉

I'm also encountering some issues with attachments. I could only test it with PDF-files. If I try to open them (just click on the attachment in the UI), a new browser tab is opened, but it just shows a blank page. If I try to download the attachment as zip-file the same, a blank page. If I choose "Save in Nextcloud" the file is properly stored to the selected folder in NC and I can perfectly display it.
But, I guess, this is not how it's like to work. Could it be related to the PDF issue discribed here?

NC and server config is as follows (The keys of the config names have been translated from german, so not sure about there native naming...):
## PHP
Version: 8.0
Storagelimit: 1 GB
Max. runtime threshold: 10800
Max. upload size: (WebDAV): 10 GB
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, smbclient, sodium, zip, libsmbclient, Zend OPcache

## Database
Type: mysql
version: 10.5

## Nextcloud
Version: 24.0.5
Type: Managed (Hetzner Storage Share)

**Comment by the-djmaze** [comment]
Found it. The values in the link are encrypted with the session token.
Since the token expired all links failed (while message is fetched with 304 Not Modified)
