### ISSUE TITLE
Installing snappymail doesn't create data/ files (OpenBSD 7.1/httpd/chroot )

### ISSUE THREAD

**Issue by ffuentese** [the-djmaze/snappymail#468]
**SnappyMail version, OS,, webserver** 2.17.0, OpenBSD 7.1, httpd

**Expected behavior and actual behavior:**

I tried to install snappymail on top of rainloop (the commercial one, I don't know if that matters) and it never created the admin_password so then I remembered that httpd or nginx in OpenBSD are chrooted (and I don't really wanna compromise my security)  .  At the end I deleted everything and tried to install snappymail from scratch but it didn't create the admin password either. What I also noticed was that the .htaccess looks like it's intended for Apache which is not installed in my machine nor do I intend to.

The log error I could get was this one:

```
PHP message: SERVICE WARNING: AuthError[102]
#0 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\ActionsAdmin->DoAdminLogin()
#1 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#2 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /htdocs/webmail/snappymail/v/2.17.0/include.php(169): RainLoop\Service::Handle()
#4 /htdocs/webmail/index.php(11): include('/htdocs/webmail...')
#5 {main}
```

After that, I had no choice but to reinstall rainloop until I get what I might have done wrong but if there's any incompatibility with chrooted environments or non apache servers  I'd also like to know it.

**Comment by the-djmaze** [comment]
SnappyMail doesn't require Apache. It also works with other HTTP daemons.
When `application.ini` contains a admin password, it will not generate a new one and therefore the `admin_password` does not exist.

The main question is where and how the `data` directory is setup.
Did you try https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#secure-data-folder ?

**Comment by ffuentese** [comment]
Maybe I didn't do that step first and then after that log into the admin panel? I just don't wanna break it again!!

**Comment by ffuentese** [comment]
... and it happened again!
