### ISSUE TITLE
I want to see a timeout error.

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#471]
**SnappyMail version, browser, browser version:**
2.17.0

**Expected behavior and actual behavior:**
I'm using a shared rental server. When I use the email address here, I have to press the receive button several times. This is the same with Rainloop. It is more likely to occur if a user has more than about 800MB of email stored in their account. The connection failure rate is very high when users enable the threaded view option. Regardless of email usage.

In SnappyMail, automatic reception of mail starts after logging in, but then the process ends with the list empty as if nothing happened.
I would like to see a "timeout error" error message. Rainloop shows an error.

**Steps to reproduce the problem:**
Log in to SnappyMail

**Comment by the-djmaze** [comment]
Speed of IMAP depends on the server specifications.
And then there's the speed of SnappyMail itself which also relies on server specifications.

Sometimes it can be fixed in SnappyMail as @edlerd did with #377
But to know exactly what is wrong, you need to dig in your server why things are slow.

**Comment by Bables55** [comment]
His fix seems to have been applied in 2.17.0. I have always disabled the thread display option in the past.

It is difficult to know if SnappyMail is processing incoming mail. In other words, it is inconvenient that there is no change in the receiving list even though SnappyMail's actual receiving process is failing due to timeout error. Users unfamiliar with these tools may be concerned that their data has been lost. So it is more reassuring to see an "error" displayed.
