### ISSUE TITLE
May not be able to draft or send email

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#472]
**Describe the bug**
The user composes the mail as usual. He then sends the email or saves a draft.
Then even a simple plain text email may not be able to be sent or saved.
What I know is that it is more likely to occur if I write "---" (the so-called signature separator).
There are other triggers as well, but I have not been able to figure them out.

**To Reproduce**
1. Click "New message" or "Reply"
2. Enter letters.
3. Send or Save drafts

**Expected behavior**
The email is sent or saved.

**Additional context**
This also occurs in Rainloop.

**Comment by the-djmaze** [comment]
Works using Dovecot.
What mail server are you using that prohibits you to do things?

**Comment by Bables55** [comment]
Sorry for the late response. Thanks for the development.
I'm using Postfix and can't reproduce this problem with Ver. 2.18.0 or later. It seems to have improved a lot.

Thanks.
