### ISSUE TITLE
Quick filter box for folders to easily move emails

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#474]
**Is your feature request related to a problem? Please describe.**
I have lots of folders and I'm moving relevant mails to some of them manually. Now it happens nearly every day that I have to scroll down very much to move an email from my inbox to one of the respective folders. This takes time and is sometimes frustrating. And yes, with less folders this problem would not exist – but unfortunately currently its not possible to reduce the number of folders.

**Describe the solution you'd like**
It would be very helpful to have a function above the folders making it easy to filter the displayed folders on the left hand side in real time so moving could take less time.

**Describe alternatives you've considered**
Reducing the number of folders unfortunately does not work in my situation.

**Additional context**
This is how the function could look like:
![image](https://user-images.githubusercontent.com/43847817/182378352-50826a2f-aeda-4471-875f-24956b2406df.png)

Additionally I want to say a big **THANK YOU** for creating and maintaining Snappymail ❤❤❤

**Comment by the-djmaze** [comment]
I will look into it.

> Additionally I want to say a big **THANK YOU** for creating and maintaining Snappymail ❤❤❤

Thanks!

**Comment by the-djmaze** [comment]
Added for next release.
Currently i have configured the input field to be only visible when you have more then 10 folders.

**Comment by codiflow** [comment]
At first I want to shout out a **BIG thank you**? The feature is absolutely great and it helps me a lot 🥳 Works like a charm!
Is there a way how I can give you something back? Some kind of appreciation in form of a donation or related?

**Comment by the-djmaze** [comment]
> Is there a way how I can give you something back? Some kind of appreciation in form of a donation or related?

Sure! It's not much, but read https://snappymail.eu/donate
