### ISSUE TITLE
Email filters

### ISSUE THREAD

**Issue by CapBlackShot** [the-djmaze/snappymail#475]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would love to see email filters working in SnappyMail. I couldn't find a tool like that within the software. Does it exist already?

**Describe alternatives you've considered**
None. But, if I remember well, Rainloop used to have them.

**Additional context**
There's no additional context to provide at this moment.

**Comment by the-djmaze** [comment]
It exists. You just have to setup Sieve properly.
If the mail server does not support Sieve, then it will not work.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/FAQ#enable-filters

**Comment by CapBlackShot** [comment]
@the-djmaze awesome, it seems to be working now. However, when I click "Filters", I see a "rainloop.user" and nothing else shows up. I'm migrating from Rainloop. Is there anything I need to delete besides its old plugins folder?

**Comment by CapBlackShot** [comment]
Ok, if I click "rainloop.user", I have the option to add a filter. Is it possible to restore the default filters page though? Without having to go through rainloop.user?

**Comment by the-djmaze** [comment]
The filters system of SnappyMail is more advanced as you can add additional filter scripts.
Because of that, it's not possible to restore the old behaviour.

**Comment by CapBlackShot** [comment]
> The filters system of SnappyMail is more advanced as you can add additional filter scripts. Because of that, it's not possible to restore the old behaviour.

Thanks!
