### ISSUE TITLE
quick install Sieve from admin panel/Default setup

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#476]
Hello.

I believe there should be a "quick" way of setting up Sieve through the admin panel instead of having to edit files manually, including the settings file.

Perhaps a "reset all configs to default" button would also be a good idea, incase ports get blocked by SnappyMail config files like dovocot edits.

**Comment by the-djmaze** [comment]
Which settings are you missing here?
![image](https://user-images.githubusercontent.com/3752035/182705303-ce9aa960-4cce-452f-bc4a-1a6803c9e6a8.png)

**Comment by master3395** [comment]
> Which settings are you missing here? ![image](https://user-images.githubusercontent.com/3752035/182705303-ce9aa960-4cce-452f-bc4a-1a6803c9e6a8.png)

"Quick setup".
If I hit the "Allow sieve script" it does not work, because the sieve script isn't set up to activate.
Sieve is missing from the dovecot file and postfix.
I use the web panel "CyberPanel", and they don't include sieve in the SnappyMail integration.
You have to set that up yourself.

![bilde](https://user-images.githubusercontent.com/4199669/182779024-d362064f-9d84-4768-ad5c-f695d8f5f8b7.png)
![bilde](https://user-images.githubusercontent.com/4199669/182779063-e46dd3e7-c8f0-4ba3-a3df-e403c40f1e5c.png)

**Comment by m-i-k-e-y** [comment]
@master3395 

This is not an issue with SnappyMail, but rather a server setup problem. SnappyMail does not install sieve, it lets you manage sieve rules if sieve is enabled and accessible on your mailserver.

1. Is SnappyMail hosted on the same server as your mailserver? If not, you can not use `localhost` as server.
2. Is sieve actually up and running? Did you verify with `netstat -tunlp | grep ":4190"` (this is one of the steps from the link of your post)?
3. Is a firewall in place blocking tcp connections to port 4190?
4. Last but not least: did you check the logfiles of dovecot to see why it might be refusing the connection to sieve?

I dont't use cyberpanel, so I don't how it is supposed to work. So if anything I wrote above doesn't apply don't kill the messenger. ;)

**Comment by the-djmaze** [comment]
> Sieve is missing from the dovecot file and postfix.
> I use the web panel "CyberPanel", and they don't include sieve.
> You have to set that up yourself, sadly their tutorial do not work.

@m-i-k-e-y is correct.
You must install Sieve on the server and integrate it with Dovecot.
Just stay in touch with the CyberPanel community and eventually someone might have the solution for you.
There's nothing we can do about that.
