### ISSUE TITLE
Authentication failed when domain name isn't valid : fixed but may need improvment

### ISSUE THREAD

**Issue by Nono-m0le** [the-djmaze/snappymail#477]
**Describe the bug**
It's quite a long shot, but here it is.
When I setup my SnappyMail (migrated from Rainloop) I had, on the admin section two domains setup : domain1 & domain2.tld
I don't know why, but on the admin section > Domains I created : 
`domain1` (with the correct SMTP./IMAP settings) **without the .tld**
and
`domain2.tld `(with the correct SMTP/IMAP settings)
Until recently (I really don't know since when/which version) everything worked like a charm.

Suddenly, when I wanted to send an email from one account from domain1.tld I faced an "Authentication failed" message.
After few debugging, I realize that this was caused by the admin > domains settings.
I had to re-create a new domain (with domain1.tld this time) with the exact same settings to make it works.

It seems to me that, since a quite recent version, the name of the domain is now checked when it wasn't the case before.

**To Reproduce**
1. Go to the admin section
2. Set "domain" (without the TLD) as a name of the domain
3. enter all the settings => Test will succeed
4. try to send an email from this domain.tld
5. Getting "Authentication failed" as "domain" isn't "domain.tld"

**Expected behavior**
It makes sense (now) especially since I had to recreate the domain, that it must be valid. 
the following ribbon help a lot here: 

> This domain configuration will allow you to work
> with *@domain email addresses.

But I guess this could be a left-over from a previous rainloop version when the name of the domain wasn't really checked

**Solution**
I found the solution => I recreate the domain with a valid address (`domain.tld` instead of just `domain`)

**Suggestion**
I guess that, as this name is now used to check the validity of the domain itself, it could make sense to warn either the user or the admin that a domain added isn't valid. (domain vs domain.tld).

I'm on 2.16.3 btw.

**Comment by the-djmaze** [comment]
Correct, there is a bug in RainLoop that only checked `domain` must exist inside string.
For example you have `example` then the following are valid:
* example.com
* example.co.uk
* example.org
And probably also (out of my mind, didn't check):
* examples.com
* another-example.com
* example-foo.bar

A check could be made, but what if the domain is just a fake entry for intranets or other?
Say you have a server and use the `short login`.

**Comment by Nono-m0le** [comment]
As the ribbon is quite explicite on the admin side (even though, maybe a warning sign to say "hey, this isn't "default" or "localhost" are you sure ?)
I would rather add something on the user side, something like :
Authentication failed (is the domain name valid and/or whitelisted ?)
This would be more like a heads-up for the user to give to the admin (especially in case of migration).
what do you think ?

**Comment by the-djmaze** [comment]
Hmm that suggests the domain is invalid/disallowed, but does not say if the password is wrong.

I am more thinking like:
`Authentication failed. If you need help, report code XYZ09 to admin for investigation.`
Then the log entries have code XYZ09

**Comment by Nono-m0le** [comment]
I leave that to you but, IMO:
1) If the password is wrong, that would have been seen on the admin page, during the "test" (can you even validate a domain, if the settings are wrong ?)
2) Authenication failed is for me a bit misleading. What happens here is more that the domain isn't authorized. I don't see the link with an authentication per say.
3) Adding a code is indeed better. I already feel quite lost with another error code (#344) where no details what's so ever was given. So big :+1:  on this idea !
4) I didn't check the source code, but would it be that complicated to cleary state the error ? Like "domain name is different that the value XXX".
Having `domain1.tld isn't on the authorized list of domain` would have been more helpful than a simple `Authentifcation failed`

But again, I'm just bringing an issue that I had, so it's really up to you.
Thanks anyway for listening & answering so openly :)
