### ISSUE TITLE
Identities don't work in 2.17.1

### ISSUE THREAD

**Issue by Pumpino** [the-djmaze/snappymail#479]
When composing or clicking reply in 2.17.1, it is no longer possible to select registered identities in the From field. This bug was not present in 2.17. I'm using Chrome. I confirmed that the identity is still registered in settings.

**Comment by the-djmaze** [comment]
Confirmed.
Was accidentally removed by commit
https://github.com/the-djmaze/snappymail/commit/62d13a12d1c9a6edc42898d00bb994944c7b8eac
