### ISSUE TITLE
Sign up page?

### ISSUE THREAD

**Issue by alejo9010** [the-djmaze/snappymail#481]
Hi want to know if there is a way to enable a signup page directly in the snappymail page?

**Comment by the-djmaze** [comment]
You could add a signup link on the login page.
Therefore you need the `login register` extension.

**Comment by alejo9010** [comment]
> 

hi, where do i get the extension ?

**Comment by the-djmaze** [comment]
Admin => extensions

**Comment by alejo9010** [comment]
sorry to bother again these might be silly questions but im really bad at php/javascript, but how do i access the admin panel, i dont see any way to access it from my login page

**Comment by alejo9010** [comment]
nvm i managed to do this on my own now!, but its asking me for register link and forgot link, this is what i dont know how to get now

**Comment by the-djmaze** [comment]
If you want a complete registration system, then you need to build one.
SnappyMail is only for accessing accounts, it can't create accounts.
