### ISSUE TITLE
Incomplete message list

### ISSUE THREAD

**Issue by ner00** [the-djmaze/snappymail#482]
**Describe the bug**
The message list is incomplete, e-mails are missing for no apparent reason.

**To Reproduce**
Stumbled on this issue after moving a few messages from one folder to another, but other clients show the list correctly (although Rainloop also isn't showing every e-mail, but Snappy is showing less).

**Expected behavior**
To not miss any e-mail in the listing

**Screenshots**

**SnappyMail**
![chrome_wNImGsvtfP](https://user-images.githubusercontent.com/2269603/183395265-fb789868-e6fd-422e-a1bf-3a57fa869b20.png)

**RainLoop**
![chrome_2SZddk5Kps](https://user-images.githubusercontent.com/2269603/183395193-2eafec60-a2e0-4d86-86e5-e9aa9f06b97f.png)

**Roundcube**
![chrome_WyKZPrH3Qv](https://user-images.githubusercontent.com/2269603/183395082-3aa1cebf-a10e-483b-9acd-5231f4efa02b.png)

**Please complete the following information:**
- Tried with both Chrome and Firefox, latest versions to date, Windows x64
- IMAP daemon: hMailServer
- PHP version: 7.3.10
- SnappyMail Version: 2.17.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[log-2022-08-08.txt](https://github.com/the-djmaze/snappymail/files/9280833/log-2022-08-08.txt)

**Comment by the-djmaze** [comment]
I found a bug in the "hide messages marked for deletion" which caused weird results.
So i've released v2.17.2 and you should check if that solves this issue as well.

**Comment by ner00** [comment]
Perfect, no more issues with the message list, and [the setting to hide/show the ones flagged for deletion is also now working properly](https://github.com/the-djmaze/snappymail/issues/470#issuecomment-1207891703). Thanks a lot!
