### ISSUE TITLE
Cannot connect to SnappyMail with Windows Mail (the default mail app on windows)

### ISSUE THREAD

**Issue by Xemorr** [the-djmaze/snappymail#483]
**Describe the bug**
I cannot for the life of me connect via Windows Mail, but have been able to connect to IMAP on Thunderbird and POP on Office365 Outlook.

**To Reproduce**
Open windows mail
Click settings
Manage accounts
Add account
Type in the details
![image](https://user-images.githubusercontent.com/31805746/183526702-09859d12-f028-4adc-b922-1acbd26d1236.png)

**Expected behavior**
I expect it to successfully log into my mail account

**Please complete the following information:**
- Browser: N/A Using windows mail
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.17.2

**Comment by the-djmaze** [comment]
You can't use Windows Mail to browse SnappyMail.
Only up-to-date http browsers can be used (see README for supported browsers).
