### ISSUE TITLE
Cpanel Change Password Plugin

### ISSUE THREAD

**Issue by aredean** [the-djmaze/snappymail#485]
**Is your feature request related to a problem? Please describe.**
Thank you for making rainloop more modern and optimized. I want to asking about one plugin that exist in rainloop. 

The cpanel change password plugin in rainloop is often used using shared cpanel hosting. Are there any plans for a cpanel change password plugin to be created? Or is it actually already made?

**Describe the solution you'd like**
Maybe make a cpanel change password plugin that is compatible with snappymail?

**Describe alternatives you've considered**
I don't have a solution for now.

**Additional context**
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/cpanel-change-password

**Comment by the-djmaze** [comment]
The RainLoop plugin should be dead as XMLAPI is deprecated/removed.
Shall check the current UAPI and WHM API
