### ISSUE TITLE
Is the refresh frequency of the inbox adjustable?

### ISSUE THREAD

**Issue by Pumpino** [the-djmaze/snappymail#486]
Is there a setting that sets the frequency at which the inbox is checked for new messages? I'd like to increase the frequency of checks, if possible. If that's not possible, how often is the inbox refreshed? Thanks.

**Comment by the-djmaze** [comment]
Every mailbox gets refreshed every 5 minutes.
https://github.com/the-djmaze/snappymail/blob/master/dev/Common/Folders.js#L130

This is currently not adjustable.

**Comment by Pumpino** [comment]
Thanks.

That's not very frequent. Wouldn't every 2 minutes be reasonable, given that people could wait an extra 5 minutes to see a new email compared to using Thunderbird or Outlook?

**Comment by the-djmaze** [comment]
You could click the reload button yourself if you can't wait.

More frequent requests has more strain on server and data transfers.
I prefer 15 minutes or more as mail interrupts my current work (this is scientific tested in many forms, not just mail or phone calls).

For example: your phone does "ping!"
Can you wait 1 hour before checking, or do you grab your phone to see what message you've got? 😉

**Comment by Massedil** [comment]
Can't we have "IMAP PUSH" for real time alert and no server stress ?

**Comment by the-djmaze** [comment]
@Massedil not possible because that would need a persistent connection between SnappyMail client -> Server -> IMAP server.
And the only way that is doable is through a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API).
