### ISSUE TITLE
Request Timed Out

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#487]
Currently using v2.17.2, but this has been happening at least since v2.17.
When changing folder I often get a "Request Timed Out" error message.
Nothing has changed on the webserver SnappyMail is installed on [apart from regular updates and updating SnappyMail].
After re-clicking on the folder everything works fine.

![Screenshot 2022-08-18 at 10 24 52](https://user-images.githubusercontent.com/35845319/185361650-e9653255-9fdb-4383-a338-0953d799b8ca.jpg)

**Comment by phsc84** [comment]
I've also encountered this behaviour after upgrading to 2.17.2 (coming from 2.15.1). Try Ctrl+Shift+r. At least this has helped for me.

**Comment by the-djmaze** [comment]
Sometimes loading all message id's of a mailbox is slow (when there are many, or server itself slow).
And the current timeout should be around 60 seconds, but PHP/HTTPD could be set to 30 seconds timeout.

That's why you see timeouts.
Smaller mailboxes or faster server should solve the issue.

This is different then RainLoop because SnappyMail allows sorting of messages and that requires reading all messages (when the IMAP daemon doesn't support indexing).

**Comment by ivnmad** [comment]
I use SnappyMail with multiple email servers, including Gmail, GMX, etc.
I'm having the same issue with all of them, normally when I click on the Trash folder, and not when loading the Inbox or Setn folders. The Trash folders never contains more than 10 emails, since I clear them often.
It normally only happens the first time I click on it, and then it is fine for the rest of the session, it doesn't matter what folder I click on.
As mentioned this has only started happening recently, and it wasn't an issue before.
It isn't a major issue, but something must have changed.

**Comment by bk-king1** [comment]
I too am seeing this randomly. Only since 2.17.2. There has been no change in user profile(mailbox sizes etc) nor the system load.

I cannot find a way to replicate it as it happens so intermittently. Usually, just clicking back on the INBOX brings things back to normal

**Comment by the-djmaze** [comment]
I've seen this issue once in a weird way.
It showed the error and below that the list of messages.

Eventually i will figure out what happens and why it fails ;)

**Comment by ivnmad** [comment]
@the-djmaze I can confirm that I've also experienced that [error message with all emails listed below], apart from just seeing the error message like in my screenshot. Luckily it isn't a major issue, so we can keep using SnappyMail in the meantime.
Thank you for all your work.

**Comment by ivnmad** [comment]
I think commit [ab0b2b1] did the trick. I haven't experienced this issue with the latest releases.

**Comment by the-djmaze** [comment]
Good to know, will keep it in mind when accidentally enabling it again.
