### ISSUE TITLE
custom wallpaper does not cover entire screen

### ISSUE THREAD

**Issue by distresscode** [the-djmaze/snappymail#488]
--------Snappymail on Cloudron--------
This is also posted on the CR forum here: https://forum.cloudron.io/topic/7529/wallpaper-does-not-cover-entire-screen

I uploaded my own wallpaper and made sure it's 1920x1080 (that's what is being used for Snow Dark v1) and tried all the different themes but the wallpaper does not extend all the way like it does with Snow Dark v1. Is this by design or a bug?
![dd0ac907-53a4-42ed-86c7-3546b9e86c6b-image](https://user-images.githubusercontent.com/2686608/185414542-abb50c70-8fb6-4efb-a579-a76fb84b4c94.png)

**Comment by the-djmaze** [comment]
Design was "contain" so that the whole image is shown.
I've changed it to be "cover" to cover the whole screen.
