### ISSUE TITLE
Issue to setup Fail2Ban on Plesk

### ISSUE THREAD

**Issue by PeopleInside** [the-djmaze/snappymail#489]
**Describe the bug**
Here user can find the guide to configure snappymail Fail2Ban:
https://github.com/the-djmaze/snappymail/tree/master/fail2ban

Im running 
Ubuntu 22.04.1 LTS with Plesk Obsidian Version 18.0.44

**To Reproduce**
Following the Fail2Ban guide

1. on /etc/fail2ban/jail.d I upload the two files located here: https://github.com/the-djmaze/snappymail/tree/master/fail2ban/jail.d
2. on /etc/fail2ban/filter.d I upload the two files located here: https://github.com/the-djmaze/snappymail/tree/master/fail2ban/filter.d
3. I customize the logpath in https://github.com/the-djmaze/snappymail/blob/master/fail2ban/jail.d/snappymail-log.conf

Now as in the guide:

Modify your /etc/fail2ban/jail.local with:

[snappymail-fpm-journal]
enabled = true

Modify the path in /jail.d/snappymail-log.conf

Upload the following to /etc/fail2ban/*

/filter.d/snappymail-log.conf
/jail.d/snappymail-log.conf
Modify your /etc/fail2ban/jail.local with:

[snappymail-log]
enabled = true

**Expected behavior**

The ban never works.
Fail2Ban never restart. Goes into errors.

**Please complete the following information:**
- Browser: Vivaldi (Chrome badesed)
- SnappyMail Version: 2.17.2

Will be useful understand more easily how activate with success fail2ban on Plesk as the guide seems generate errors.

I see the two Jail active but IF I try to deactivate I get

```
Unable to switch on the selected jails: f2bmng failed: 2022-08-18 16:14:11,826 fail2ban.configreader [129340]: WARNING 'action' not defined in 'snappymail-fpm-journal'. Using default one: ''
2022-08-18 16:14:11,826 fail2ban.jailreader [129340]: WARNING No actions were defined for snappymail-fpm-journal
2022-08-18 16:14:11,829 fail2ban [129340]: ERROR NOK: ("Failed to initialize any backend for Jail 'snappymail-fpm-journal'",)
ERROR:__main__:Command '['/usr/bin/fail2ban-client', 'reload', '--if-exists', 'snappymail-fpm-journal']' returned non-zero exit status 255.
2022-08-18 16:14:11,892 fail2ban.configreader [129341]: WARNING 'action' not defined in 'snappymail-log'. Using default one: ''
2022-08-18 16:14:11,892 fail2ban.jailreader [129341]: WARNING No actions were defined for snappymail-log
ERROR:__main__:Failed to reload following jails due to errors in configuration: snappymail-fpm-journal.
```

**Comment by PeopleInside** [comment]
Maybe I have to do all from the Plesk Panel but I get errors also here.

![image](https://user-images.githubusercontent.com/5006150/185419470-29c50b5e-ea61-445e-b366-514df20df7b7.png)

**Comment by the-djmaze** [comment]
Why "snappymail-fpm-journ", did Plesk put limits on things while it should not?

And where can you add the filter https://github.com/the-djmaze/snappymail/blob/master/fail2ban/filter.d/snappymail-fpm-journal.conf

Can't Plesk help? https://support.plesk.com/

**Comment by PeopleInside** [comment]
Maybe a guide to configure Fail2Ban on Plesk is needed.

For now I resolved in this way:

On Plesk:

- **Tools & Settings**
- **IP Address Banning (Fail2Ban)**

Here filter must be created first by going on **Jails** and then the gray button **Manage Filters**

- Add Filter
 - Name: snappymail-fpm-journal
 - Content:
   [code][INCLUDES]
before = common.conf

[Definition]
failregex = Auth failed: ip=<HOST> user=.*$
ignoreregex = 
_daemon = php-fpm
journalmatch = _SYSTEMD_UNIT=php-fpm.service SYSLOG_FACILITY=10  [/code]
quindi premere OK

- Add Filter
 - Name: snappymail-log
 - Content: 
    [code][Definition]
failregex = Auth failed: ip=<HOST> user=.* host=.* port=.*$
ignoreregex = [/code]

Quindi premere OK per salvare.

Ora creare le Jails su Jails

- Add Jails
  - Name: **snappymail-fpm-journ**
   - Filter: snappymail-log (selezionare dal menù a tendina)
   - Action: 

`iptables-allports[chain="INPUT", name="snappymail-fpm-journ", port="ssh", protocol="tcp", returntype="RETURN", lockingopt="-w"]`

 - Log path: `/snappy/data/_data_/_default_/logs/fail2ban/customlogsfilename.log`
 - IP Ban: 3600
 - Max number fail login attempts: 3

- Add Jails
 - Name: **snappymail-log**
 - Filter: snappymail-log (select from dropdown menù)
 - Content: iptables-allports[name="snappymail-log"]
 - Log path: `/snappymail/data/_data_/_default_/logs/fail2ban/logcustomname.log`
 - IP Ban 3600
 - Max number fail login attempts: 3

Modify /PATH-TO-RAINLOOP-DATA/_data_/_default_/configs/application.ini as follow

```
[logs]
auth_logging = On
auth_logging_filename = "fail2ban/auth-fail.log"
auth_logging_format = "[{date:Y-m-d H:i:s T}] Auth failed: ip={request:ip} user={imap:login} host={imap:host} port={imap:port}"
```

Go on Jails and enable the two rules and test.

**Comment by PeopleInside** [comment]
This issue still exist, today I am trying to configure Plesk and fail2ban for snappy email but follow my previous instructions doesn't work.

I suppose the content of 

```
Upload the following to /etc/fail2ban/*

    /filter.d/snappymail-fpm-journal.conf
    /jail.d/snappymail-fpm-journal.conf
```

Are not good for Plesk.
Why?

Because this content can be created from the UI of Plesk directly and is not accepted so you can maybe force manually by editing manually files by SFTP but you will have always issue as as soon Plesk detect error fail2ban will stop to work and your email system are unprotected.

**Comment by the-djmaze** [comment]
> Error: Unable to get the list of jails: f2bmng failed: ERROR:**main**:No option 'logpath' in section: 'snappymail-fpm-journal'.

Correct. It uses `journalmatch` so there is no `logpath`

Did you ask at Plesk why `journalmatch` can't be used?

**Comment by PeopleInside** [comment]
https://talk.plesk.com/threads/unable-to-configure-fail2ban-for-snappymail-on-plesk.367836/

asked now

**Comment by PeopleInside** [comment]
@the-djmaze I was inserting the wrong log patch in Plesk, need insert the Plesk log patch for fail2ban
Now the issue is that the log is not created.

In the folder data/_data_/_default_/logs/fail2ban no log file are created on wrong credentials.
A log is created in the folder /httpdocs/peopleinside.it/web-mail/data/_data_/_default_/logs with a data and time name but this is not the log I need.

In the application.ini I have:
```
[logs]
; Enable logging
enable = On

level = 4

; Logs entire request only if error occured (php required)
write_on_error_only = Off

; Logs entire request only if php error occured
write_on_php_error_only = Off

; Logs entire request only if request timeout (in seconds) occured.
write_on_timeout_only = 0

; Required for development purposes only.
; Disabling this option is not recommended.
hide_passwords = On
time_zone = "UTC"
session_filter = ""

; Enable auth logging in a separate file (for fail2ban)
auth_logging = On
auth_logging_filename = "/fail2ban/logfilename.log"
auth_logging_format = "[{date:Y-m-d H:i:s}] Auth failed: ip={request:ip} user={imap:login} host={imap:host} port={imap:port}"
```

Any idea why the log is not created?

**Comment by PeopleInside** [comment]
The question now is: what can be the cause of the log file not created inside the folder fail2ban?

**Comment by the-djmaze** [comment]
Try `auth_logging_filename = "fail2ban/logfilename.log"`

**Comment by PeopleInside** [comment]
> Try `auth_logging_filename = "fail2ban/logfilename.log"`

This I have just to set only in the application.ini under data/_data_/_default_/configs , correct?

If yes I saved, tested a wrong login and the issue is the same:
- no logs file in fail2ban folder in snappymail and a file of log created on /data/_data_/_default_/logs (log-2023-01-09.txt)

**Comment by PeopleInside** [comment]
I am using PHP 8.2 but dont think the problem is that, I hope.

I really dont know why in the past I was able to see this working and now no.
The two Jails are now active on Plesk but the log is never generated.

**Comment by the-djmaze** [comment]
Due to a change in the log handling, the log level was incorrect.
I've changed it so that logging to file works again.

**Comment by PeopleInside** [comment]
> Due to a change in the log handling, the log level was incorrect. I've changed it so that logging to file works again.

Great, this solve all my issue related to fail2ban. Thanks.

**Comment by Lawkss** [comment]
I found that I had to add 

`backend = auto `

to the jail before it would start to work with the logging file method. Just for info if someone comes across issues. Worked on Alma 9.5
