### ISSUE TITLE
html editor not working

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#490]
If i click source on the image below and copy that into a new email.
All HTML is gone.
If I straight up copy the first image, without clicking source, I can copy it into a new email.
But I do wish to save the HTML, to re-use it later on.
I believe that the source button should contain the HTML, if not, have a separate button to do so.

Snappymail 2.17.0 (Within CyberPanel)

How it should look.
![image](https://user-images.githubusercontent.com/4199669/185462356-58ee9d1c-a61a-45f8-bd79-110c4ed8c6fa.png)

How it looks when I click "Source", it's missing the HTML.
![image](https://user-images.githubusercontent.com/4199669/185462533-5812072f-10e2-4079-8596-0eddba8806cf.png)

How the outcome looks if I copy the source box into a new email?
![image](https://user-images.githubusercontent.com/4199669/185462453-960b2455-3b20-4f7d-a2db-655d9541425d.png)

**Comment by the-djmaze** [comment]
It's not a `source` button.
It is a toggle between plain text and html email.

So you can either a plain text message or an HTML message to someone.

**Comment by master3395** [comment]
Ugh, then there should be a source option, to get the source of the HTML email.
