### ISSUE TITLE
Images are not being displayed in "reply" or "reply all" emails

### ISSUE THREAD

**Issue by mattyau75** [the-djmaze/snappymail#491]
When replying to emails (using "Reply" or "Reply All") that have an image embedded in message, it is not including the images from the original email - just the text content.
However when I "forward" the email, the original content of the email, including images is displayed correctly

- SnappyMail Version: 2.17.2 (latest version)
- PHP Version: PHP 75 (ea-php74)

Am I the only one experiencing this issue or is there a setting that I need to look at either in the application.ini file or on my email server or is it a bug?

**Comment by the-djmaze** [comment]
You are not the only one. It's default behavior.
https://github.com/the-djmaze/snappymail/blob/d91fbaa2c04e1db366002e8726dab094678fd28b/dev/View/Popup/Compose.js#L1042

**Comment by mattyau75** [comment]
@the-djmaze so what do I need to do to change the "default" so that I can view original images in my reply
Where is this compose.js file actually located?
I only extracted and uploaded the contents of [snappymail-2.17.2.zip] (https://github.com/the-djmaze/snappymail/releases/download/v2.17.2/snappymail-2.17.2.zip) on to my web server.

**Comment by the-djmaze** [comment]
Well, actually the bug is that "forward" allows images while it should not.

There are many reasons why forward/reply embedded images is not working.
1. "Always display external images in message body" is off
2. Images proxy is used (like `<img alt="PayPal" data-x-src="./?/ProxyExternal/BASE64CODE"`
3. hidden tracking pixels
4. etc.

The system needs a new feature where the composer has a bar/button "embed images" to achieve what you want.

**Comment by mattyau75** [comment]
I am just amazed that the original embedded image by "default" is not being displayed in all reply / forward emails. Embedded images are usually included in emails for specific purposes or email referencing, such as logo's, product images, error screenshots etc etc. Having them included in future responses makes it easier to viewing referenced images in the same email thread / discussion - regardless of who actually initiated the embedded image.

As it stands, I would say the "Forward" email logical should be default and the current "Reply / Reply All" email is the bug.

Is there any manual code that I can replace in any of the application files / scripts that will replicate Reply Emails to function exactly how Forward emails is working now?

**Comment by the-djmaze** [comment]
> Is there any manual code that I can replace in any of the application files / scripts that will replicate Reply Emails to function exactly how Forward emails is working now?

Yes and no. I said the current "Forward" behavior is wrong due to mentioned issues.

If you don't care about that, you must edit the JavaScript files and remove the mentioned code.

To solve the issues i mentioned the system requires improvements.
