### ISSUE TITLE
Hitting the reply button on an email in Sent shouldn't send an email to myself

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#497]
**Describe the bug**
Replying to a sent message sends an email to myself.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to sent folder
2. Open a sent message
3. Click on reply button
4. Attempt to send another message to whoever the Sent message was originally sent to
5. Realised I've just emailed myself.

**Expected behavior**

Clicking reply on a sent message shouldn't send email to myself,

It should send another message to whoever I first emailed.  Basically like what happens when you click reply-all should happen when you click reply.

This is the UX in Gmail and most other places too (e.g. Roundcube)

**Comment by jdaviescoates** [comment]
Awesome, thanks! 

Guessing this will be included in the next 2.17.3 release?

**Comment by the-djmaze** [comment]
Yes
