### ISSUE TITLE
There should be a source option, to get the source of the HTML email.

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#498]
Instead of only getting the source of plain text from HTML.
There should be a way to get the HTML as well.
Ref this issue: https://github.com/the-djmaze/snappymail/issues/490

**Comment by PeopleInside** [comment]
@the-djmaze how it work the new fix?
I still see issues:

https://www.screencast.com/t/MbndyRBb7Q4

As you can see once I see the source I loose the HTML format

**Comment by PeopleInside** [comment]
I see, the issue is caused by the red button and the new fix is the new button that I selected in green.
There is a way I can completely disabled the button in red?
![immagine](https://user-images.githubusercontent.com/5006150/192096996-d59c4056-c2d2-4857-855f-cb3740a1f738.png)

**Comment by the-djmaze** [comment]
Completely disable that button is not an option.
However, i am thinking about a cleaner way to "send message as ..." so you can choose between Plain text or HTML.
