### ISSUE TITLE
Image html not displaying right after sent

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#499]
After you have sent an email.
And go into the "sent" box, some if not all images will be blank.
It shows that the link to the images is from my internal IP, on both the working images and the broken images.

It seems that this issue came after I upgraded from 2.15.x to 2.17.0

![image](https://user-images.githubusercontent.com/4199669/187044408-b2ba5a60-9ddc-4648-a248-f555ee0f6da1.png)
![image](https://user-images.githubusercontent.com/4199669/187044465-2069bb04-153a-49fd-b457-9fac85bf019f.png)

**Comment by the-djmaze** [comment]
Check the source of the email to identify what goes wrong

**Comment by master3395** [comment]
It shows this page if i open the image in a new window.
Each of the images is coming from my PC, by using the "upload image" button.
Perhaps it only supports URL images.
Also maybe it needs to have a way to resize the images on the edit button.
One of my uploads was too big.

If I only use the external image, it works fine, but internal image upload makes images sent invalid.
![image](https://user-images.githubusercontent.com/4199669/192055413-31d87575-02f6-43d3-b0af-e76d5e554454.png)

**Comment by the-djmaze** [comment]
ProxyExternal means that SnappyMail tries to download a remote URI.
You should check which URI that is (can be found in HTML source of e-mail).

**Comment by master3395** [comment]
Url was going to imgur, the url works fine.
I also tried to check if it was "not view able by non logged in users" but it was.

I only replaced the URL with my own folder inside of my own domain now it works.
