### ISSUE TITLE
Pagination does not work (regression)

### ISSUE THREAD

**Issue by tomasz-c** [the-djmaze/snappymail#50]
**RainLoop version, browser, OS:**
SnappyMail version v2.3.0, PHP 8.0, desktop and mobile browsers, (Chromium, Bromite)

**Expected behavior and actual behavior:**
Pagination stopped working after updating v2.2.2 to v2.3.0. Clicking on a page number enters the page number into the search box, but does not switch the page.

**Steps to reproduce the problem:**
Try to switch the page.

Additional question:
Is it possible to somehow set the background scaling in the custom theme in v2.3.0?
I tried to add: `--main-bg-size: auto;`
but that didn't work, if the background is higher resolution than the screen, only the upper left part is visible.

**Comment by grawlinson** [comment]
Can confirm this regression on my side.

Clicking on "2" enters "p2" into the search box along with "No messages matched your search."

**Comment by the-djmaze** [comment]
Yes i noticed the bug after bugfixing the hash routing.
It is solved in 2.3.1

**Comment by tomasz-c** [comment]
Could I ask you to answer my additional question? (about scaling backgroud).
Thank you in advance.

**Comment by the-djmaze** [comment]
> Is it possible to somehow set the background scaling in the custom theme in v2.3.0?
> I tried to add: `--main-bg-size: auto;`
> but that didn't work, if the background is higher resolution than the screen, only the upper left part is visible.

Use `--main-bg-size: contain` or `--main-bg-size: cover`

**Comment by tomasz-c** [comment]
@the-djmaze 
> Use `--main-bg-size: contain` or `--main-bg-size: cover`
> Read https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

None of these work. I tested on version 2.3.1.
Before version 2.3.0, `styles.less` had `@main-background-size: cover;` and that worked.
Could you please verify this?

**Comment by the-djmaze** [comment]
@tomasz-c i can't verify at the moment.
However, did you clear the cache after making your modifications?

**Comment by the-djmaze** [comment]
@tomasz-c the upcomming release has one theme changed.
The system will have a real dark mode by removing background/text colors from the messages.

Here's the changed style for the next release:
https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/themes/SquaresDark/styles.less

**Comment by tomasz-c** [comment]
@the-djmaze 
Currently it works, but in versions v2.3.0 and v2.3.1 it did not work.
