### ISSUE TITLE
Focus on textarea when creating a new plain text email

### ISSUE THREAD

**Issue by bohwaz** [the-djmaze/snappymail#501]
On the demo, when you create a new HTML email, by default the text input for the message is focused, so you can start typing right away. But that's not the case when writing a plain text email.

It should be the case for plain text email, that the textarea gets a focus when new mail pseudo-window is opened.

Another detail is that if you put the caret somewhere in HTML mode, and switch to plain text mode, the caret position is now at the start, if you move and switch back to HTML, the caret gets back to the beginning in HTML mode, but going back (again) to plaintext, the caret didn't move. So yeah the caret position is not synced between HTML and text mode, but not sure if that detail is really important, as you are not going to switch back and forth between text and HTML.

**Comment by the-djmaze** [comment]
> by default the text input for the message is focused

Actually, it should not do that.

When `To` is empty, it should focus that
When `To` is not empty and `Subject` is empty, it should focus `Subject` (but instead it focuses the message area)
When `To` and `Subject` are empty, it should focus the message area.
