### ISSUE TITLE
No keyboard shortcut to enter a thread message list

### ISSUE THREAD

**Issue by bohwaz** [the-djmaze/snappymail#502]
When in the message list, you can use arrows to move between messages, but when you used thread grouping there is no way (well it seems?) to go to the list of messages of the thread. If I press space, then the message is selected, if I press Enter the current message is display in full-screen (not sure why though).

Looking at https://github.com/the-djmaze/snappymail/blob/master/dev/View/User/MailBox/MessageList.js I don't see a shortcut for that.

Also, not sure what Alt-Left/Alt-Right is supposed to do, if it's supposed to cycle mail boxes, it doesn't follow any logical order.

Thanks :)

**Comment by the-djmaze** [comment]
Correct, there is no shortcut.
Now the question is: which shortcut should it get? for example: `+`

> Also, not sure what Alt-Left/Alt-Right is supposed to do, if it's supposed to cycle mail boxes, it doesn't follow any logical order.

There is no such shortcut. Only Ctrl+Left/Ctrl+Right and they also move between messages.
This is a leftover of RainLoop
https://github.com/RainLoop/rainloop-webmail/blob/13d05dc2ff06ce06a689a7e33a5163ecf3b6c27e/dev/View/User/MailBox/MessageView.js#L795-L803
Shall i remove them?

**Comment by bohwaz** [comment]
> Correct, there is no shortcut. Now the question is: which shortcut should it get? for example: `+`

For me the most obvious would be to have Enter go to the thread view when you are on a threaded message, then you can get the fullscreen view by pressing Enter when in the threaded view. This way you keep the fullscreen feature, you just have to press Enter again when the message is actually a thread.

To get back to the list of messages then you could use Escape.

> > Also, not sure what Alt-Left/Alt-Right is supposed to do, if it's supposed to cycle mail boxes, it doesn't follow any logical order.
> 
> There is no such shortcut. Only Ctrl+Left/Ctrl+Right and they also move between messages. https://github.com/the-djmaze/snappymail/blob/master/dev/View/User/MailBox/MessageList.js#L795-L796 This is a leftover of RainLoop https://github.com/RainLoop/rainloop-webmail/blob/13d05dc2ff06ce06a689a7e33a5163ecf3b6c27e/dev/View/User/MailBox/MessageView.js#L795-L803 Shall i remove them?

Hum that's weird yesterday when I used Alt-Left and Alt-Right it moved between mailboxes but in a random order. Doesn't happen today, not sure what happened, it doesn't matter then :)

**Comment by the-djmaze** [comment]
> Hum that's weird yesterday when I used Alt-Left and Alt-Right it moved between mailboxes but in a random order.

Ah, it's your browser shortcut for backward/forward ;)

**Comment by bohwaz** [comment]
Ahah yes but yesterday it didn't work, that's what is weird.

**Comment by the-djmaze** [comment]
> when you used thread grouping there is no way (well it seems?) to go to the list of messages of the thread.

Yes there is: T

**Comment by bohwaz** [comment]
Oh nice! Yeah I didn't even identify it in the code, so it's missing some doc :) Thanks!

**Comment by the-djmaze** [comment]
It's in the help page wirh shortcuts

**Comment by bohwaz** [comment]
There's a help page! Ah found it! Took me a while, thanks :)
