### ISSUE TITLE
Please sign plugin archives as well

### ISSUE THREAD

**Issue by Alphix** [the-djmaze/snappymail#503]
The releases are already GPG-signed and posted together with detached signatures.

It would be nice if the plugins (https://snappymail.eu/repository/v2/plugins/) could also be accompanied by detached (`.asc`) signatures, like the main releases (https://github.com/the-djmaze/snappymail/releases/).

The background here is that I'm writing an Ansible role for installing/configuring SnappyMail, and it'd be nice to be able to verify the authenticity of the plugins in the same manner as the SnappyMail release itself.

**Comment by Alphix** [comment]
> Actually, i was thinking to release them as signed Phar files. I've mentioned it here: GPG signed releases #131

Yeah, I remember that. I was kind of hoping that you could GPG sign the plugins _in addition_?

1. Checking the GPG signatures is easy when the steps are already in place to check the signatures for the release
2. Implementing GPG signatures for the plugins would be a tiny change in your release scripts (I assume)
3. ``.phar`` files do seem to have some shortcomings (e.g. the Deserialization Vulnerability, haven't studied it in detail though)
4. Implementing ``.phar`` support will likely be a bigger undertaking...

**Comment by the-djmaze** [comment]
Also added to the json as `pgp_sig`
https://snappymail.eu/repository/v2/packages.json

> 4\. Implementing `.phar` support will likely be a bigger undertaking...
Not really, it already works but has no signature checks yet.
