### ISSUE TITLE
any auto reply option

### ISSUE THREAD

**Issue by karthikindia** [the-djmaze/snappymail#504]
need to know if snappy mail have any automatic reply option, in settings i dont see any

**Comment by the-djmaze** [comment]
yes.
1. your server must support Sieve
2. you've setup Sieve in SnappyMail
3. create Sieve filter rule to reply

**Comment by karthikindia** [comment]
How to install and cofigure sieve

**Comment by the-djmaze** [comment]
You should follow instructions of your mailserver to do that.
This is not something SnappyMail can do for you.
