### ISSUE TITLE
Plugins back ?

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#51]
Hi 
First, thanks to take this software up.
Do you think that the plugins will be back ? I am interesting by the change password feature and I see in the Wiki that actually it is disabled. I confirm that I can put the plugin but I am able to configure it (the network request for the configuration parameters is done, but the admin panel configurator is not displayed, nor the enabled plugin in the main window).
Thanks a lot !

**Comment by the-djmaze** [comment]
Correct, none of the "change password" plugins will work.
There are security issues involved with such a plugin and therefore it would be wiser to do that through your server control panel like: Plesk, cPanel, ApisCP, RunCloud, DirectAdmin, Froxlor, etc. etc.

Mainly: if someone knows your mail password he could change it and lock you out.
RainLoop and SnappyMail have no ISO/GDPR certified log system, nor a safety service with third party email address (like protonmail, gmail and outlook provide).
Therefore, it would be hard to detect and prevent misuse of such feature (which control panels do).

SnappyMail does send "failed login" attempts to the system log so that fail2ban (or others) can protect webmail attacks.

**Comment by dominiquefournier** [comment]
There is no problem with this type of plugins : you need to type the old password before setting a new one, like Zimbra or Exchange does. You can add a fail2ban if there is too much errors if you want. You are right, there is no external mail address to solve if you loose your password, but it is not the objective of these plugins. In my company, we don't use the server control panel as it is overkill. We create the user mail by extraction from the people management system and let it change the password in the Webmail.
If someone has my password, it can always kick me out. You may add a second factor if you want, but it is the responsability of the plugin to do that. 
In fact it is exactly the objective of a plugin : use it if you understand what it does. It may not fit your requirements, but fit mines.

So is it possible to reactivate them ?

**Comment by the-djmaze** [comment]
Valid point that it's up to the system admin.
I will look into it.

**Comment by the-djmaze** [comment]
After i put it back as core feature like it was in RainLoop, i've dived into the plugins system and moved the whole thing to be a plugin.
This way it's not part of the core, but you can install it as plugin.

After all this is much better because the change-password was broken anyway, if you wanted to update 2 areas (like separate IMAP and SMTP).

I will change all current drivers into the plugin with a solution to enable multiple.

**Comment by dominiquefournier** [comment]
I don't know if multiple backends support is needed, but if it is not too hard to implement, it could be fun !

**Comment by the-djmaze** [comment]
Not hard. It works now.
Which driver do you need, or you write your own?
See https://github.com/the-djmaze/snappymail/tree/master/plugins/change-password/drivers

**Comment by dominiquefournier** [comment]
PDO is what I need. If you want, you can change the LDAP in class name for example. You may create a LDAP driver if you have time, to be compliant with most of user backends

**Comment by the-djmaze** [comment]
Here you go
https://github.com/the-djmaze/snappymail/releases/tag/v2.3.4

**Comment by dominiquefournier** [comment]
I have a bug, sorry ! When I try to open the Packages tab in Admin menu, I have an error "Cannot access the repository at the moment.". When I look at the JS queries I see : ?/Json/=&q[]=/0/
`{"Action":"AdminPackagesList","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Class name must be a valid object or a string","ErrorMessageAdditional":"","Time":233}`
So I am not able to enable the plugins.
Try to change of browser but same error

In the Nginx error log : 
`2021/03/03 20:11:08 [error] 26191#26191: *298210 FastCGI sent in stderr: "PHP message: Class name must be a valid object or a string" while reading response header from upstream, client: 2a01:e0a:::197, server: mail.x.fr, request: "POST /snappymail/?/Json/&q[]=/0/ HTTP/1.0", upstream: "fastcgi://unix:/run/php/mail-fpm.sock:", host: "mail.x.fr"`
Is there something to do after extract the package content and do the chown ?
I am in PHP7.3 if it change something

**Comment by the-djmaze** [comment]
@dominiquefournier  thanks for reporting!
I've found the bugs that caused this issue:
1. the plugins builder in release.php had a wrong regex in buildFromDirectory that caused install of an invalid additional folder
2. the plugin manager reads the invalid folder and crashes

Solved it by repackaging the plugin and catch the plugin manager error.


You can solve it to go into your /_data_/_default_/plugins/ folder and delete the folder named 'password'.

**Comment by dominiquefournier** [comment]
Much better !
I can configure the plugin in admin part and the menu appears on the user part.
But I found two problems : 
- When I try to change the password, it failed with the error in logs : 
`"PHP message: PHP Notice:  Undefined variable: oAccount in /data/home/mail/snappymail/data/_data_/_default_/plugins/change-password/index.php on line 79PHP message: Call to a member function Email() on null" `
- I use PDO, but you prepare the LDAP backend. You should create a select list to choose the configurator associated

**Comment by the-djmaze** [comment]
Thank you for testing!
1. fixed the bug
2. yes this will be done in the future with own admin settings page instead of the simple popup

**Comment by dominiquefournier** [comment]
I don't have any log in the server, but now there is logs in Snappymail ;-) :
`Error: Call to undefined method MailSo\Base\Utils::PasswordWeaknessCheck() in /data/home/mail/snappymail/data/_data_/_default_/plugins/change-password/index.php:98`
If I remove the WeaknessCheck, an other error appears : 
` ArgumentCountError: Too few arguments to function RainLoop\Plugins\Helper::ValidateWildcardValues(), 2 passed in /data/home/mail/snappymail/data/_data_/_default_/plugins/change-password/index.php on line 105 and exactly 3 expected in /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Plugins/Helper.php:7`

May I suggest to define the minimum length of password by configuration too ? 10 chars may be too long for some installations

**Comment by the-djmaze** [comment]
Changed ;)

**Comment by dominiquefournier** [comment]
In PasswordWeaknessCheck, you must change the !! to ! or it doesn't works.

**Comment by the-djmaze** [comment]
Added a visual password strength meter

**Comment by dominiquefournier** [comment]
I can't test the meter as I don't recompile all the project. But I appreciate !
On PHP, there is again an error : 
```
PHP[NOTICE]: /data/home/mail/snappymail/data/_data_/_default_/plugins/change-password/index.php [line:151, code:8]^M
[2021-03-04 13:47:49.694][1b04bc5b] PHP[NOTICE]: Error: Undefined property: ChangePasswordPlugin::$oLogger^M
[2021-03-04 13:47:49.700][1b04bc5b] INFO[NOTICE]: RainLoop\Exceptions\ClientException: UnknownError[999] in /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/ServiceActions.php:156
Stack trace:
#0 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#1 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#2 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#3 /data/home/mail/snappymail/snappymail/v/2.3.4/app/handle.php(57): RainLoop\Service::Handle()
#4 /data/home/mail/snappymail/snappymail/v/2.3.4/include.php(227): include('/data/home/mail...')
#5 /data/home/mail/snappymail/index.php(12): include('/data/home/mail...')
#6 {main}^M
```

**Comment by the-djmaze** [comment]
You don't need to recompile the whole project.

Anyway, i've fixed the oLogger bug.

Thanks for testing as i don't have such environment overhere!

**Comment by dominiquefournier** [comment]
Sorry, the password is now correctely changed, but I have an error : 
`2021-03-07 19:29:59.301][cb27042e] INFO[NOTICE]: RainLoop\Exceptions\ClientException: UnknownError[999] in /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/ServiceActions.php:156
Stack trace:
#0 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#1 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#2 /data/home/mail/snappymail/snappymail/v/2.3.4/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#3 /data/home/mail/snappymail/snappymail/v/2.3.4/app/handle.php(57): RainLoop\Service::Handle()
#4 /data/home/mail/snappymail/snappymail/v/2.3.4/include.php(227): include('/data/home/mail...')
#5 /data/home/mail/snappymail/index.php(12): include('/data/home/mail...')
#6 {main}^M
[2021-03-07 19:29:59.302][cb27042e] JSON[DATA]: {"Action":"PluginChangePassword","Result":false,"ErrorCode":999,"ErrorMessage":"","ErrorMessageAdditional":"","Time":3543}`
Do you have an idea to solve this ?

**Comment by the-djmaze** [comment]
Problem solved!
RainLoop has properties like $aData and $mData where $a = array and $m = mixed
I've ran a script for SnappyMail to convert those parameters to "array $aData" and there lays the problem.
It should NOT be $aData, it should be $mData and that caused the troubles.

**Comment by dominiquefournier** [comment]
Well done !

**Comment by feng84302** [comment]
Hello, I am using maddy and snappymail  to build my own email system,

In the change password plugin of snappymail, select Enable PDO.  Is DSN using the sqlite used by maddy? For example:  "sqlite: data/credentials.db",  and what is the Statement?

**Comment by the-djmaze** [comment]
> Is DSN using the sqlite used by maddy? For example: "sqlite: data/credentials.db"

`sqlite:/database_file_path_here.db`

> and what is the Statement?

Therefore you should look at the Maddy documentation and/or look in the db
