### ISSUE TITLE
Checkbox to select all message doesn't work.

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#510]
After updating to v2.17.4, checkbox to select all message doesn't work. Even if I click it, no message is selected.

![SnappyMail checkbox](https://user-images.githubusercontent.com/5249848/188174989-1fd0dcd0-46b8-4904-b0b9-48c8aea26431.png)

- Browser
  - Windows
    - Google Chrome 105.0.5195.54
    - Microsoft Edge 105.0.1343.25
    - Mozilla Firefox 104.0.1
  - Android
    - Google Chrome 104.0.5112.97
    - Microsoft Edge 104.0.1293.70
    - Mozilla Firefox 104.1.0
- IMAP daemon
  - Dovecot 2.3.19 (FreeBSD)
  - Dovecot 2.3.13 (Debian)
- PHP version:
  - PHP 8.0.22 (FreeBSD)
  - PHP 7.4.30 (Debian)

**Comment by the-djmaze** [comment]
I know, i accidentally put in a bad change.
Already fixed for next release https://github.com/the-djmaze/snappymail/commit/d9bc435e2c8cbf9e182b010020651216154a1368

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.18.0
