### ISSUE TITLE
open mail thread fails on current version

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#511]
Hi there,

Since current upgrade (today, 1.17.4), you cannot open mail threads by clicking on the number showing the amount of new messages.

It works with previous version.

**Comment by the-djmaze** [comment]
I know, i accidentally put in a bad change.
Already fixed for next release https://github.com/the-djmaze/snappymail/commit/d9bc435e2c8cbf9e182b010020651216154a1368

**Comment by yeupou** [comment]
Great! Thanks again for your work.

**Comment by fs1** [comment]
It's no longer possible to flag (star) an email, if I click on the small star icon next to the time in the message list. Is it the same error, or should I file a new issue?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.18.0
