### ISSUE TITLE
Page navigation in the mail list is not working.

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#512]
**SnappyMail version, browser, browser version:**
2.17.4
**Expected behavior and actual behavior:**
The navigation at the bottom of the mail list page does not work.
I click on any page number and Snappymail is unresponsive.
Firefox(Win), Chrome(Win), Safari(iOS)

**Steps to reproduce the problem:**
Just log in.

**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/30524004/188367863-0bf7b781-1cd2-4e96-bdc8-215c16be1f10.png)

**Comment by xgbstar1** [comment]
Confirming this. Additionally, the checkbox for select all fails as well. It looks like a one-line ordering problem in the resultant app.min.js file.

In comparison to the Snappymail v2.17.4 [demo site](https://snappymail.eu/demo/#/mailbox/INBOX), it appears that the the Snappymail v2.17.4 GitHub release file behavior differs in that the latter exhibits these issues whereas the former does not.

Here are steps to verify the difference:
1. Download the v2.17.4 [zip release file](https://github.com/the-djmaze/snappymail/releases/download/v2.17.4/snappymail-2.17.4.zip)
2. Extract the file and run `md5sum snappymail/v/2.17.4/static/js/min/app.min.js` and verify the result is `f40fb4be4002c42b01f51050e8f30aff`
3. Download the `app.min.js` file from the v2.17.4 demo site and run md5sum, e.g. `curl https://snappymail.eu/demo/snappymail/v/2.17.4/static/js/min/app.min.js | md5sum` and verify that the result is `b383371453f458bf77505a7d55d0727d`
4. Note that the md5sums differ

I'm not sure how this has transpired and would note one way that may be helpful to prevent such issues is to run the build and demo deploys using GitHub Actions and I'm happy to help with this process if needed/wanted.

My workaround for the moment is the following 
```
cp ./snappymail/v/2.17.4/static/js/min/app.min.js ./snappymail/v/2.17.4/static/js/min/app.min.js.bak
curl -o ./snappymail/v/2.17.4/static/js/min/app.min.js https://snappymail.eu/demo/snappymail/v/2.17.4/static/js/min/app.min.js
```

Thanks for all the volunteer work and hope we can resolve this.

**Comment by the-djmaze** [comment]
@xgbstar1 correct, the demo was built later with the fix, that is why the md5sum is different.

Currently i'm testing the new AddressBook system which should integrate much better with vCard/jCard as it does not rely on the old RainLoop database structure.
Instead it just stores the whole vCard in the database.
This should solve many synchronization bugs and allow SnappyMail to extend the contacts system with all vCard supported fields.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.18.0
