### ISSUE TITLE
Starring a message does not work anymore since last release 2.17.4

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#514]
**Describe the bug**
Clicking on the star icon near a message neither adds nor removes the star. Instead a error message is shown in the browsers console.

**To Reproduce**
Click on the star icon near a message

**Expected behavior**
It should add / remove the star

**Screenshots**
-

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: -
- PHP version: -
- SnappyMail Version: 2.17.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Browser console error message:
```
Uncaught ReferenceError: can't access lexical declaration 'i' before initialization
    click https://mail.sweetba.se/snappymail/v/2.17.4/static/js/min/app.min.js:1
11 app.min.js:1:129035
```

**Additional context**
-

**Comment by ivnmad** [comment]
I can confirm I'm experiencing the same issue since upgrading to 2.17.4

**Comment by the-djmaze** [comment]
Same issue as #511 and #512

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.18.0
