### ISSUE TITLE
"Request is aborted" message is often diplayed

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#518]
**Describe the bug**

When normally using snappymail and moving from folder to folder, I now often see a red message : 

![](https://user-images.githubusercontent.com/20357783/189945307-73a07d89-ca01-4aa9-85d1-b261b0377a37.png)

I think this behavior is recent : since I have updated from snappymail 2.17.0 to snappymail 2.17.4 and then 2.18.0.

**To Reproduce**

- Move (more or less quickly) between folders. 
OR
- Search in a folder and do another search (when, I imagine, the first one is not terminated).

**Expected behavior**

The message is not displayed, except if there is really a problem.

Because, most of the time : 
- if I move from a folder to another, I'm not interested to know that the last leaved folder is not well updated
- if I have done a new search, I'm not interested to know that the last obsolete one is not completed

**Please complete the following information:**
- Browser: Firefox 104
- IMAP daemon: dovecot
- PHP version: PHP 7.3.31-1~deb10u1
- SnappyMail Version: 2.18.0

**Comment by the-djmaze** [comment]
This issue is similar to #487

While the system is fast, sometimes race conditions occur where it is loading the messages of box X and you go to box Y.
While switching it aborts previous call and shows the message.

I will make it more user friendly
