### ISSUE TITLE
Carddav sync error : data too long for colum prop_value

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#519]
**Describe the bug**
Syncing addressbook with Nextcloud sometimes causes error

**To Reproduce**
1. Configure carddav sync with proper Nextcloud URL
2. Click on sync option
3. See the "unexpected error"

**Expected behavior**
The sync should work or give a relevant error

**Please complete the following information:**
- Browser: Firefox 104.0.2
- IMAP daemon: dovecot
- PHP version: 7.4.30
- SnappyMail Version: 2.18.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
This error is throwed in the debug log : 
[2022-09-15 12:08:30.119][de2bf97e] JSON[DATA]: {"Action":"ContactsSync","Result":false,"ErrorCode":999,"ErrorMessage":"22001 - SQLSTATE[22001]: String data, right truncated: 1406 
Data too long for column 'prop_value' at row 1","ErrorMessageAdditional":"","Time":1720}

**Additional context**
I've got error 3 times in a row, but now there is no more error. Sync is going on with some other problem that I will describe in another bug.

**Comment by the-djmaze** [comment]
SnappyMail now stores the whole vCard in the database.

**database prop_value**
sqlite: text = variable 2GB length
pgsql: text = variable unlimited length
mysql: text = 65535 bytes

Will change that to MEDIUMTEXT (16,777,215 bytes)

**Comment by phsc84** [comment]
Why not LONGTEXT (4GB)? This would match better with sqlite and pgsql than MEDIUMTEXT (16MB).

**Comment by Mer0me** [comment]
On Nextcloud database, it seems to be stored as longblob

**Comment by the-djmaze** [comment]
> Why not LONGTEXT (4GB)? This would match better with sqlite and pgsql than MEDIUMTEXT (16MB).

True, but i wonder who has a single vCard larger then 16 MiB.
That's why i've set it to MEDIUMTEXT

**Comment by the-djmaze** [comment]
Solved with v2.18.2?

**Comment by Mer0me** [comment]
I'm afraid I won't be able to help you anymore, we have switched to the Nextcloud official webmail here.
Thank you for your efforts and long life to Snappymail.

**Comment by phsc84** [comment]
Just tested CardDAV sync on my installation with 2.18.3. It worked perfectly fine for me.
