### ISSUE TITLE
Links in emails should automatically be clickable links

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#521]
**Describe the bug**
I just opened an email that has a link to both a URL and an email, but neither of them are clickable.

**To Reproduce**
1. Go to an email that contain strings that begin with https:// and x@x.x 
2. Note I can't click on them
3. See that I can click on them in FairMail
4. Wish I could click on them in SnappyMail too

**Expected behavior**
I'd like it if all links (even if they are plain text) were automatically transformed into links like is common in most email clients these days (although I note that whilst the links are shown as links in my FairMail app Android email client - by far the best email client I've ever used - the links do not display in Roundcube either)

**Comment by the-djmaze** [comment]
Related to  #402 where Outlook is involved and an explanation why Thunderbird and SnappyMail don't automagically create links of text.

**Comment by jdaviescoates** [comment]
Just fyi this was a plain text email from AirTable, but fair enough, I guess.

**Comment by the-djmaze** [comment]
The system does try and find 3 types of URI to convert:
1. http: and https:
2. mailto:
3. tel:

There are some rules to find a match and all must start at beginning of line or have a space prepended.
If it fails, we need to find out why.

Could you provide an example?

**Comment by jdaviescoates** [comment]
How best to provide an example? Shall I forward you the email from AirTable where I noticed this? What's the best email address to use? :)

**Comment by the-djmaze** [comment]
You could add the message body here as attachment/code or test yourself at places like https://regex101.com/

**Comment by the-djmaze** [comment]
v2.18.4 has some improvements regarding links in plain text mails.
Does your issue still occur?

**Comment by ivnmad** [comment]
I tried to send myself an email with a plain link via Outlook, but the link isn't clickable in SnappyMail [v2.18.5]
I think and hope that's the feedback you were looking for.

![Screenshot 2022-10-10 at 14 19 31](https://user-images.githubusercontent.com/35845319/194876244-3c93e17a-ceb2-4f65-805b-3fbd270d8bc3.jpg)

**Comment by the-djmaze** [comment]
@ivnmad 
> Outlook

Take a look at the source of that e-mail and verify it's 100% text/plain
Then paste the eml source here.

**Comment by ivnmad** [comment]
I can try via Thunderbird later, but I only have Outlook on this computer.

This is taken from Outlook:
[Outlook_MessageSource_2022-10-10.txt](https://github.com/the-djmaze/snappymail/files/9746537/Outlook_MessageSource_2022-10-10.txt)



This is taken from SnappyMail:
[SnappyMail plain link test.txt](https://github.com/the-djmaze/snappymail/files/9746519/SnappyMail.plain.link.test.txt)

Please let me know if that helps, or if you need anything else.

**Comment by ivnmad** [comment]
SnappyMail recognises the link fine if I send the email from Thunderbird.

Thunderbird email source:

`From - Mon, 10 Oct 2022 17:11:46 GMT
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00800000
Message-ID: 
Date: Mon, 10 Oct 2022 18:11:44 +0100
MIME-Version: 1.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101
 Thunderbird/102.3.1
Content-Language: en-GB
To: 
From: 
Subject: SnappyMail text plain link test..
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

https://www.example.com
`
SnappyMail received message source:

[SnappyMail text plain link test.txt](https://github.com/the-djmaze/snappymail/files/9747834/SnappyMail.text.plain.link.test.txt)

**Comment by the-djmaze** [comment]
> This is taken from Outlook: [Outlook_MessageSource_2022-10-10.txt](https://github.com/the-djmaze/snappymail/files/9746537/Outlook_MessageSource_2022-10-10.txt)

That source has:
```html
<div class=3D"WordSection1">
<p class=3D"MsoNormal">https://www.google.com<o:p></o:p></p>
</div>
```

As you can see Outlook uses HTML without A tags. And that's why it is not a link in SnappyMail.

Open message menu and select option "View plain text message" and then the links should work.

So for best results always check that you are viewing in "plain text" mode and not some sort of crappy Outlook HTML.
