### ISSUE TITLE
Custom Theme not available

### ISSUE THREAD

**Issue by olpo24** [the-djmaze/snappymail#522]
Hi,
Custom theme is not available in theme selection.

Regarding to the docs: https://github.com/the-djmaze/snappymail/wiki/Custom-Themes I created folder and style.css in this structure:
[root]/themes/[themename]/styles.css

I cleared the cache also rm -rf /home/webmail/public_html/data/_data_/_default_/cache, but can't reload the apache config (shared webspace).

I can't choose my theme in drop down. I is not showing.

Can you help to debug this and find the issue?

Kind regards,
Ole

**Comment by the-djmaze** [comment]
I've just tested this by adding a custom theme named "rainbow" at https://snappymail.eu/demo/#/settings/themes
It works as expected so we need more info why yours is not working.

**Comment by olpo24** [comment]
@the-djmaze I would love to provide more info.
What do you need?

**Comment by the-djmaze** [comment]
And which name does your theme have?

**Comment by olpo24** [comment]
> And which name does your theme have?

/home/webmail/public_html/themes/**olpo**/styles.css

**Comment by the-djmaze** [comment]
Strange that it doesn't work then.
I've tested it on the demo website AND the new Nextcloud integration and they both work as expected.

Therefore, i will see if i can write some debug code for you to log any issues.

**Comment by the-djmaze** [comment]
Any luck yet?
