### ISSUE TITLE
Forwarding some Krautreporter emails results in a Javascript TypeError while sending/saving

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#524]
**Describe the bug**
Forwarding an email from Krautreporter (example attached below) results in a Javascript error which prevents saving / sending the email.

**To Reproduce**
1. Open an email from Krautreporter (they are using Mailchimp for sending their newsletters but only some of their emails are causing this issue)
2. Click "Forward"
3. Click on "Save" or enter recipient and click von "Send"
5. Error `TypeError: s.parentNode.closest is not a function`

**Expected behavior**
The email should be saved / sent without an error.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43847817/190864817-fa775891-3244-4ec5-a390-46ff41abf569.png)

**Please complete the following information:**
- Browser: Mozilla Firefox
- IMAP daemon: mailcow
- SnappyMail Version: 2.18.0

**Additional context**
The problem does not exist with other emails or when forwarding it as an attachment.
It also does not happen for every Krautreporter newsletter but only some (mostly the new ones). I think the problem is caused by something within their emails DOM. Unfortunately I don't know if it works to import this email to SnappyMail like it is or sending it to yourself to reproduce the error.

If this doesn't work maybe you can easily subscribe to one of the Krautreporter newsletters and try it yourself: https://krautreporter.de/newsletter

I can also try to forward the email to the developer as an attachment to easily reproduce the error or help with debugging this further.

**Newsletter which causes the error**
[email.eml.zip](https://github.com/the-djmaze/snappymail/files/9592062/email.eml.zip)

**Comment by m-i-k-e-y** [comment]
Seems to be the same as issue #516

**Comment by codiflow** [comment]
Problem unfortunately still exists with 2.18.2 – it seems to have something to do with newsletters sent using Mailchimp.
If I can help debugging this further please tell me.

**Comment by codiflow** [comment]
Can confirm that the bug is not present anymore within 2.18.5 (I think it was already fixed in 2.18.3)
