### ISSUE TITLE
Contacts not working: RainLoop\Common\PdoAbstract::getVersion(): Return value must be of type ?int, string returned

### ISSUE THREAD

**Issue by lje** [the-djmaze/snappymail#527]
**Describe the bug**
Contacts cannot be enabled in the admin panel of Snappymail 2.18.1

**To Reproduce**
Go into the admin panel, try to enable contacts. When testing database, you will get error message "RainLoop\Common\PdoAbstract::getVersion(): Return value must be of type ?int, string returned". I tested with MySQL (using MariaDB) as well as SQLite.

**Expected behavior**
Contacts working

**Screenshots**
![SnappyMail-Contacts](https://user-images.githubusercontent.com/357743/191994378-a6906fa0-c1b9-435a-aade-2c6ff4676668.png)

**Please complete the following information:**
- Browser: firefox 105
- IMAP daemon: dovecot
- PHP version: 8.1 (tested with 8.0 as well)
- SnappyMail Version: 2.18.1

**Comment by olivier-monaco** [comment]
Problem comes from this commit: https://github.com/the-djmaze/snappymail/commit/6ee514910f87c412a1305a5bb00352868a1aada8

The function argument $bReturnIntValue was removed but it was not removed from line 262.

As a workaround, you can edit the file snappymail/v/2.18.1/app/libraries/RainLoop/Common/PdoAbstract.php, go to line 262 and replace:
```php
return $bReturnIntValue ? (int) $mRow[0]['value_int'] : (string) $mRow[0]['value_int']; 
```
by:
```php
return (int) $mRow[0]['value_int']; 
```

Then, edit line 265 and replace:
```php
return $bReturnIntValue ? 0 : '';
```
by:
```php
return 0;
```

**Comment by lje** [comment]
I did, unfortunately that only changes the error message to "Unknown database error".
![SnappyMail-Contacts](https://user-images.githubusercontent.com/357743/192087568-6897ac2b-5360-482e-9dd6-fbdea4674602.png)

I reverted to 2.18.0 for now, which works just fine.

**Comment by the-djmaze** [comment]
Yes, i already fixed.
I thought i've tested it, but didn't :(
