### ISSUE TITLE
Unified username/login independent from server name and email identities

### ISSUE THREAD

**Issue by realsimix** [the-djmaze/snappymail#53]
**Is your feature request related to a problem? Please describe.**
We have unified usernames/logins which are independent from server name and email identities and domains. See below:

```
Name:           "James Bond"
Username/Login: "jabon"
Imapserver:     "imap.corp.xxxxxx.com"
Emailaddress1:  "james.bond@aaaaaaa.com"   <--(main/primary address)
Emailaddress2:  "jb@bbbbbbb.org"
Emailaddress3:  "jbond@ccccccc.com"
```
I didn't find a clean way to implement this with RainLoop and while searching, I found out about SnappyMail and decided to check it out. Unfortunately I also didn't find out how to do it and I'm wondering, am I missing the obvious?

**Describe the solution you'd like**
To me it seems the current logic is done to work easily with public providers like gmail, hotmail or whatever. It would be nice to be able to simply configure accounts with a username, servername and primary identity. Then the user can add more identities as required.

**Describe alternatives you've considered**
I've looked at the custom-login-mapping but that's not really what I need.

**Additional context**
I know what this issue came up in RainLoops issues again and again so I'm wondering if it's all there but I just didn't find our how to configure for my use case?

Thanks and kind regards,
Simon

**Comment by the-djmaze** [comment]
RainLoop and SnappyMail support several options:

1. /?admin domains configure a domain with "Use short login"
2. Login with "jabon" and password (the short login)
3. Go to: Settings -> Accounts then:
a. Add accounts (with their own login credentials) OR
b. Add identities (that use the primary SMTP)

Send mail with one of the accounts as "From"

**Comment by realsimix** [comment]
OK thanks, that's almost what I did. What I didn't like is that by default, sending mail would use jabon@something but I would like to have the main identity to be a different "From" address. I try it again then.

**Comment by realsimix** [comment]
When you say "_Send mail with one of the accounts as "From"._", that's what I liked to get rid of. I always get "jabon@something" as (default) identity, but I'd like to get rid of this default and use one of the additional accounts (the real accounts) as default.

Is this possible somehow?

**Comment by the-djmaze** [comment]
Drag the identity up for higher priority.
See:
![account-priority](https://user-images.githubusercontent.com/3752035/110007639-32838080-7d1b-11eb-8ba8-61827c584339.png)

**Comment by realsimix** [comment]
Thanks for your help, I really missed this completely.

**Comment by realsimix** [comment]
Thanks a lot @ervee, I'll check it out ASAP!

**Comment by ervee** [comment]
Log in to the admin page > Packages > Install "Custom Login Mapping". Then go to Plugins and click the plugin name for a configuration pop-up. Enter something like ```james.bond@aaaaaaa.com:jabon```.

**Comment by realsimix** [comment]
Hm, okay, I don't see any plugins. I guess that's because I'm behind a http proxy then?

**Comment by ervee** [comment]
Did you install the package first? See my previous comment.

**Comment by realsimix** [comment]
No, the only thing I see is `Cannot access the repository at the moment.`
