### ISSUE TITLE
Can't copy an e-mail to another folder

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#532]
**Describe the bug**

Before, it was possible to copy an e-mail by maintaining `Ctrl` + `drag & drop` to a folder.

Now, the mouse icon change to an `arrow` and a `+`, but the e-mail is moved instead of copied.

**Expected behavior**

- The e-mail can be copied by moving it with `Ctrl`
- There is a button near "Move to a folder" that permit to "Copy to a folder'

**Please complete the following information:**
- Browser: Firefox 104
- SnappyMail Version: 2.18.2

**Comment by the-djmaze** [comment]
Could you be more specific as i just tried on the demo website and it works there.
![copy-drag-n-drop](https://user-images.githubusercontent.com/3752035/192457916-bf8719af-1431-411e-bd43-883a953e6835.gif)

**Comment by Massedil** [comment]
I can reproduce it on the demo website, at least like it :

1. Click
2. Move mouse
3. Press `Ctrl`
4. Continue to move mouse to a folder
5. Release the click
6. Release `Ctrl`

But sometimes, I feel like it is impossible to copy, whatever I do.

I think I do a move that beak the copy possibility until I reload Snappymail.

https://user-images.githubusercontent.com/20357783/192527515-1b7b2ff8-87bc-4a84-aadd-126fb49bb53b.mp4

**Comment by Massedil** [comment]
It seems like doing this works : 

1. Press `Ctrl`
2. Click and move
3. Release Click
4. Release `Ctrl`

May be I always pressed control after moving the mouse.

So I think the problem occurs when `Ctrl` is not pressed before everything.

**Comment by Massedil** [comment]
There is also something confusing between the "blue selected zone" at the left of an email, the checkbox and the count that appears when moving. What is really selected ?

![1](https://user-images.githubusercontent.com/20357783/192530979-c3d21cd7-5639-4137-b13d-b5b0ba1ca0e8.png)

Also, why 2 different blue color ? Why sometimes grey and sometimes dark ?

![2](https://user-images.githubusercontent.com/20357783/192531411-154557c8-de76-4c50-8d6a-fdc9f1854c6b.png)

Can't we have always a perfect corresponding ? Like this :
- if checked, zone is blue
- if not checked, zone is grey
- only one blue color
- only dark or grey

As always : thanks for your work ! :)


https://user-images.githubusercontent.com/20357783/192532672-9706663b-3cd6-4d53-bd54-c3ef2372f88c.mp4

**Comment by the-djmaze** [comment]
> It seems like doing this works :
> 
>     1. Press `Ctrl`
>     2. Click and move
>     3. Release Click
>     4. Release `Ctrl`
> 
> May be I always pressed control after moving the mouse.
> So I think the problem occurs when `Ctrl` is not pressed before everything.

This could be right, in the past i somewhere removed the constant listening for keyboard `Ctrl` as something went wrong with the drag image while switching.
1. When start dragging the icon is an envelope
2. When start dragging while `Ctrl` is pressed, the icon is a copy icon
3. When start dragging. then press `Ctrl`, the icon is an envelope

When the dragimage can be changed, it could be solved.
See `dragstart` at https://github.com/the-djmaze/snappymail/blob/0200bf1674c04671fafdf7111b3979693e31ac3a/dev/External/User/ko.js#L96

**Comment by the-djmaze** [comment]
I've made a solution for this:
1. Drop the visual copy/move icon feedback.
2. Use dropEffect to change the mouse cursor in a copy or move cursor.

Now you can just toggle `Ctrl` key any time you want and the effect is this:
https://user-images.githubusercontent.com/3752035/192717455-082e8549-9b6d-4eee-94dd-4aa22fe75ec3.mp4
