### ISSUE TITLE
++ Apologize, a question - not a bug ++

### ISSUE THREAD

**Issue by kangaroo72** [the-djmaze/snappymail#535]
Dear all,

I tried to use this repo in my docker-compose setup, but it didn't work.
I'm using Traefik & docker-compose.

After a lot of investigation, my setup works with the docker-image from "kouinkouin"
Link: https://hub.docker.com/r/kouinkouin/snappymail

Sadly, I'm unable to login as admin. Usually I request the password within the docker-container, but the file admin_password.txt wasn't created.
I'm unable to contact kouinkouin directly. That's, why I'm posting here....
Has anyone contact to the dev of this image or can someone tell me, which options I have to login as admin?

Thx, and apologize again, to use that post as an issue.

-Tom-

**Comment by kangaroo72** [comment]
Already solved - was a problem with my cat-command.

**Comment by kouinkouin** [comment]
> I'm unable to contact kouinkouin directly. That's, why I'm posting here....

Hi :-) ,
I will see later to make an overview not empty...

**Comment by kangaroo72** [comment]
> > I'm unable to contact kouinkouin directly. That's, why I'm posting here....
> 
> Hi :-) , I will see later to make an overview not empty...

Hi and big thx for your reply. As written, I'm using Traefik and docker-compose (also a separate maria-db-container), and the setup works now. Overview should be cool anyway. And thx for the quick update regarding the contacts-issue ;-)
Cheers

**Comment by kangaroo72** [comment]
@kouinkouin looks great - actually I'm working, but will share my section later.
Cheers, Tom

**Comment by kangaroo72** [comment]
@kouinkouin see my config here...

https://paste.escher.cc/?396cd1399074bf84#2x1CbFDhdNtkn4Lk4p9yRgDYjvDHBqvTG8K9Mc1S67Go
