### ISSUE TITLE
use_app_debug_css crashes SnappyMail

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#538]
**Describe the bug**
As soon as I set "use_app_debug_css = On" in application.ini, SnappyMail crashes and does not even load the login page. Instead it just shows the spinner.

In the browser console, I see the following error (please also see screenshot):
Uncaught SyntaxError: Unexpected end of input (at (index):1:131716)

**Screenshots**
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2138442/193356912-1f0bdf98-85a9-4222-9ad7-fa04f947a556.png">

**Please complete the following information:**
- Browser: Google Chrome 105
- PHP version: 8.0.23
- SnappyMail version: 2.18.3

**Comment by the-djmaze** [comment]
Solution is not right.
The real problem is here:
https://github.com/the-djmaze/snappymail/blob/e623351d24a37e4c7b6e4888f533ee22b4628ec2/snappymail/v/0.0.0/app/libraries/RainLoop/Service.php#L215

Will fix that later
