### ISSUE TITLE
Visual glitches in compose window

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#539]
**Describe the bug**
Some visual glitches could be improved in the compose window.
1) The scroll bar is not needed.
2) The "from" field should have the same length as the other fields.

**Screenshots**
<img width="759" alt="image" src="https://user-images.githubusercontent.com/2138442/193358008-2066fec7-ee32-4693-b55b-c0e879f634a2.png">

**Please complete the following information:**
- Browser: Google Chrome 105
- PHP version: 8.0.23
- SnappyMail version: 2.18.3

**Comment by ivnmad** [comment]
Regarding the "From" filed, if you have multiple identities, that is the space used to show an arrow down.
I don't experience the other issue with Firefox or Google Chrome.

![Screenshot from 2022-09-30 22-52-42](https://user-images.githubusercontent.com/35845319/193361308-346444fb-9a32-49bf-b2cc-c89217079529.png)

**Comment by phsc84** [comment]
@ivnmad 
Thanks for the hint regarding the identities. That makes sense. Didn't notice this previously... ;)

Regarding the scroll bar: Maybe it helps to have the source inspection of Chrome.
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/2138442/193407971-bfe60806-0ad7-4be8-9a6c-e9a709db6ce2.png">

**Comment by ivnmad** [comment]
> Regarding the "From" field, if you have multiple identities, that is the space used to show an arrow down. I don't experience the other issue with Firefox or Google Chrome.

I hadn't tested/noticed this, but I can see the formatting bar issue when replying to a message.
Already taken care of by @the-djmaze , but I just wanted to correct my initial statement.
No issues on a new message, but I'll test the solutions when the next release goes live.

**Comment by the-djmaze** [comment]
The scrollbar issue is still there but on a different screen size now :)

The bootstrap buttons had 13px padding and i just made it 12px so that it fits.
That the buttons are now 2px smaller are hardly noticeable.
