### ISSUE TITLE
Attachments are discarded | Not all attachments have been uploaded | Uncaught TypeError: this.isPlainEditor is not a function

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#541]
**Describe the bug**
Replying to an email which has attachments (and adding new ones) removes them and prevents sending. I cannot send it because it says "Not all attachments have been uploaded" (in German: Es wurden noch nicht alle Anhänge hochgeladen) and after saving and reopening the email the attachments were removed. It also show the error `Uncaught TypeError: this.isPlainEditor is not a function` in the browsers log.

![grafik](https://user-images.githubusercontent.com/43847817/193404689-f969441f-f4f4-403e-ad2a-6c19ea703e8d.png)

**To Reproduce**
Answer an email which already has attachments in it (like inline graphics from the signature):
![grafik](https://user-images.githubusercontent.com/43847817/193404783-207643a9-ed76-492d-a6e5-2282524af9b6.png)

After adding another attachment (see the size of it) and pasting two inline images into the email:
![grafik](https://user-images.githubusercontent.com/43847817/193404822-bc6d26c2-2388-4991-9fca-8ca162f8a814.png)

It prevents sending:
![grafik](https://user-images.githubusercontent.com/43847817/193404980-8110727e-55b9-4ff2-9ae4-3d5815b7f949.png)

Now I click on Save and close the compose window. Looking at the email in the drafts folder I see the following now (attachment is present, pasted images not):
![grafik](https://user-images.githubusercontent.com/43847817/193405010-643b7a6f-2749-4d6b-88a7-c78d8d6c0613.png)

After reopening the email "As new email" from the Drafts folder it shows me all attachments as follows:
![grafik](https://user-images.githubusercontent.com/43847817/193405047-88e153dd-b689-43d8-a9a8-cd7b29449821.png)

The two pasted graphics and the video are present in the email, the four other images have been removed without notice.
Sending still doesn't work:
![grafik](https://user-images.githubusercontent.com/43847817/193405111-9bf11109-9dad-4b26-ac58-54b26539d349.png)

After saving the email again and closing the window, all attachments are gone:
![grafik](https://user-images.githubusercontent.com/43847817/193405133-fd19c052-56dc-4f15-ae6b-dab6a8c708a8.png)
![grafik](https://user-images.githubusercontent.com/43847817/193405140-6d5aca74-8ae2-499a-8ad1-4e5b0ca7ef99.png)

**Expected behavior**
The attachments stay attached and the mail is sent.

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: mailcow
- PHP version: -
- SnappyMail Version: 2.18.3

**Comment by the-djmaze** [comment]
Solved with https://github.com/the-djmaze/snappymail/releases/tag/v2.18.4 ?

**Comment by codiflow** [comment]
Can confirm the bug has been solved with 2.18.5 (I think it was already fixed in 2.18.4)
