### ISSUE TITLE
Contacts suggestion IMAP folder enhancement not working anymore?

### ISSUE THREAD

**Issue by kurti500** [the-djmaze/snappymail#545]
**Describe the bug**
I have the above enhancement active, but since update to 2.18.4/5 its without function
![image](https://user-images.githubusercontent.com/82444848/194846557-ecd3b5e2-5f52-42f5-a1af-132d923dd031.png)

**To Reproduce**
1. enable IMAP contacts enhancement 
2. open new email
3. in "to:" field start typing the name/email-address of a person you have recently received an email

**Expected behavior**
email address determined and offered for completion from IMAP inbox folder

**Screenshots**
![image](https://user-images.githubusercontent.com/82444848/194847235-eb98c9c9-5945-452b-8c04-df7856a12e4e.png)

**Please complete the following information:**
- Browser: Chrome Version 106.0.5249.103 (Official Build) (64-bit)
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 7.4.30
- SnappyMail Version: 2.18.5

**Comment by the-djmaze** [comment]
You are right, the error was `Call to private method MailSo\Imap\SearchCriterias::escapeSearchString()`
