### ISSUE TITLE
LDAP contact synchronisation

### ISSUE THREAD

**Issue by FabulousGee** [the-djmaze/snappymail#548]
**Describe the bug**
LDAP contact synchronisation does not seem to work (plugin).

**To Reproduce**
I downloaded, configured and activated the provided plugin "ldap-contacts-suggestions" but it does not seem to work. An error is written in the error log instead.

**Expected behavior**
n.A.

**Screenshots**
n.A.

**Please complete the following information:**
- Browser: Chromium 106 (64-bit)
- IMAP daemon: hmailserver
- PHP version: 8.1
- SnappyMail Version: current (2.18.5)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
2022/10/11 18:10:22 [error] 4956#5256: *26114 FastCGI sent in stderr: "SERVICE WARNING: Call to private method MailSo\Imap\SearchCriterias::escapeSearchString() from scope ImapContactsSuggestions
#0 D:\apps\mail\htdocs\snappymail\v\2.18.5\app\libraries\RainLoop\Providers\Suggestions.php(37): ImapContactsSuggestions->Process()
#1 D:\apps\mail\htdocs\snappymail\v\2.18.5\app\libraries\RainLoop\Actions\User.php(437): RainLoop\Providers\Suggestions->Process()
#2 D:\apps\mail\htdocs\snappymail\v\2.18.5\app\libraries\RainLoop\ServiceActions.php(155): RainLoop\Actions->DoSuggestions()
#3 D:\apps\mail\htdocs\snappymail\v\2.18.5\app\libraries\RainLoop\Service.php(130): RainLoop\ServiceActions->ServiceJson()
#4 D:\apps\mail\htdocs\snappymail\v\2.18.5\app\libraries\RainLoop\Service.php(15): RainLoop\Service::RunResult()
#5 D:\apps\mail\htdocs\snappymail\v\2.18.5\include.php(169): RainLoop\Service::Handle()
#6 D:\apps\mail\htdocs\index.php(11): include('...')
#7 {main}" while reading response header from upstream, client: xxxx, server: xxxx, request: "POST /?/Json/&q[]=/0/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx"
```

**Additional context**
LDAP connection does work with other programs like LDAPAdmin

Hope I provided all necessary information - if not, feel free to ask.

**Comment by the-djmaze** [comment]
Same issue as #545 and already resolved ;)
