### ISSUE TITLE
"Call to undefined function parse_ini_file()

### ISSUE THREAD

**Issue by cscholz** [the-djmaze/snappymail#549]
**Describe the bug**
Error occured in NC25 RC 4 with  snappymail [v2.18.6](https://github.com/the-djmaze/snappymail/releases/tag/v2.18.6) when accessing the admin panel.

**To Reproduce**
1. Go to 'NC25 RC installed'
2. Click on 'snappymail [v2.18.6](https://github.com/the-djmaze/snappymail/releases/tag/v2.18.6) extracted to apps folder'
3. Set right webserver ownership of the files
4. Enable app as admin
5. Access snappymail admin page

**Expected behavior**
Access to admin page without this error

**Log message**
`{"reqId":"u1IgqdYDhQpBJhMJryEu","level":3,"time":"October 14, 2022 10:30:33","remoteAddr":"XX.XX.XX.XX","user":"ruth","app":"index","method":"GET","url":"/apps/snappymail/run/?admin","message":"{\"Exception\":\"Exception\",\"Message\":\"Call to undefined function parse_ini_file() in file 'NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/AbstractConfig.php' line 189\",\"Code\":0,\"Trace\":[{\"file\":\"NEXTCLOUD/lib/private/AppFramework/App.php\",\"line\":172,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\SnappyMail\\\\Controller\\\\PageController\"},\"appGet\"]},{\"file\":\"NEXTCLOUD/lib/private/Route/Router.php\",\"line\":298,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"PageController\",\"appGet\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},[\"snappymail.page.appGet\"]]},{\"file\":\"NEXTCLOUD/lib/base.php\",\"line\":1047,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/apps/snappymail/run/\"]},{\"file\":\"NEXTCLOUD/index.php\",\"line\":36,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]}],\"File\":\"NEXTCLOUD/lib/private/AppFramework/Http/Dispatcher.php\",\"Line\":165,\"Previous\":{\"Exception\":\"Error\",\"Message\":\"Call to undefined function parse_ini_file()\",\"Code\":0,\"Trace\":[{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/Application.php\",\"line\":19,\"function\":\"Load\",\"class\":\"RainLoop\\\\Config\\\\AbstractConfig\",\"type\":\"->\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Api.php\",\"line\":36,\"function\":\"Load\",\"class\":\"RainLoop\\\\Config\\\\Application\",\"type\":\"->\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/snappymail/crypt.php\",\"line\":198,\"function\":\"Config\",\"class\":\"RainLoop\\\\Api\",\"type\":\"::\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/lib/Util/SnappyMailHelper.php\",\"line\":17,\"args\":[\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/snappymail/crypt.php\"],\"function\":\"include_once\"},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/Application.php\",\"line\":119,\"function\":\"OCA\\\\SnappyMail\\\\Util\\\\{closure}\",\"class\":\"OCA\\\\SnappyMail\\\\Util\\\\SnappyMailHelper\",\"type\":\"::\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/AbstractConfig.php\",\"line\":45,\"function\":\"defaultValues\",\"class\":\"RainLoop\\\\Config\\\\Application\",\"type\":\"->\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/Application.php\",\"line\":14,\"function\":\"__construct\",\"class\":\"RainLoop\\\\Config\\\\AbstractConfig\",\"type\":\"->\",\"args\":[\"application.ini\",\"; SnappyMail configuration file\\n; Please don't add custom parameters here, those will be overwritten\",\"\"]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Api.php\",\"line\":35,\"function\":\"__construct\",\"class\":\"RainLoop\\\\Config\\\\Application\",\"type\":\"->\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Api.php\",\"line\":54,\"function\":\"Config\",\"class\":\"RainLoop\\\\Api\",\"type\":\"::\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Api.php\",\"line\":13,\"function\":\"SetupDefaultMailSoConfig\",\"class\":\"RainLoop\\\\Api\",\"type\":\"::\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/include.php\",\"line\":166,\"function\":\"Handle\",\"class\":\"RainLoop\\\\Api\",\"type\":\"::\",\"args\":[]},{\"file\":\"NEXTCLOUD/apps/snappymail/app/index.php\",\"line\":11,\"args\":[\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/include.php\"],\"function\":\"include\"},{\"file\":\"NEXTCLOUD/apps/snappymail/lib/Util/SnappyMailHelper.php\",\"line\":25,\"args\":[\"NEXTCLOUD/apps/snappymail/app/index.php\"],\"function\":\"require_once\"},{\"file\":\"NEXTCLOUD/apps/snappymail/lib/Controller/PageController.php\",\"line\":69,\"function\":\"startApp\",\"class\":\"OCA\\\\SnappyMail\\\\Util\\\\SnappyMailHelper\",\"type\":\"::\",\"args\":[]},{\"file\":\"NEXTCLOUD/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":225,\"function\":\"appGet\",\"class\":\"OCA\\\\SnappyMail\\\\Controller\\\\PageController\",\"type\":\"->\",\"args\":[]},{\"file\":\"NEXTCLOUD/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":133,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\SnappyMail\\\\Controller\\\\PageController\"},\"appGet\"]},{\"file\":\"NEXTCLOUD/lib/private/AppFramework/App.php\",\"line\":172,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\SnappyMail\\\\Controller\\\\PageController\"},\"appGet\"]},{\"file\":\"NEXTCLOUD/lib/private/Route/Router.php\",\"line\":298,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"PageController\",\"appGet\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},[\"snappymail.page.appGet\"]]},{\"file\":\"NEXTCLOUD/lib/base.php\",\"line\":1047,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/apps/snappymail/run/\"]},{\"file\":\"NEXTCLOUD/index.php\",\"line\":36,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]}],\"File\":\"NEXTCLOUD/apps/snappymail/app/snappymail/v/2.18.6/app/libraries/RainLoop/Config/AbstractConfig.php\",\"Line\":189},\"CustomMessage\":\"--\"}","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42","version":"25.0.0.16"}
`

**Please complete the following information:**
- Browser: Edge106.0.1370.42
- PHP version: 8.1
- SnappyMail Version: v2.18.6

**Comment by the-djmaze** [comment]
Please check your PHP configuration.
It seems you have disabled functions that should not be disabled as parse_ini_file is part of the PHP core.
