### ISSUE TITLE
Loading Description is being used as login title instead of page title

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#550]
**Describe the bug**
The configured loading description is being used as title on top of the login box instead of the page title.

**To Reproduce**
1. Configure a custom loading description in the admin panel
2. Open the regular login page

**Expected behavior**
The page should use the configured "page title" as a title for the login box, not the "loading description".

**Please complete the following information:**
- Browser: Google Chrome 106.0.5249.103 (Official Build) (64-bit)
- IMAP daemon: hMailServer
- PHP version: 7.4.32
- SnappyMail Version: 2.18.6

**Comment by the-djmaze** [comment]
The current behavior is as expected.
Branding -> Page Title = the browser title (see top bar of your browser)
Branding -> Loading Description = the text shown at loading and login

**Comment by setoy** [comment]
This... does not make any sense at all. But okay.
