### ISSUE TITLE
Log level specified in application.ini is not respected

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#552]
**Describe the bug**
After enabling logging and setting the log level to 3 (Error), the log still outputs debug and info logs.

**To Reproduce**
1. Enable logging in `application.ini` (`enable = On`)
2. Specify a high log level (for example `level = 3` 

**Expected behavior**
The application should only log levels 3 and higher, but it still logs informational messages (level 6).

**Screenshots**
![image](https://user-images.githubusercontent.com/6497266/195878157-d2a4c756-c787-4986-b028-141ede4f65f1.png)

**Please complete the following information:**
- Browser: Google Chrome Version 106.0.5249.103 (Official Build) (64-bit)
- IMAP daemon: hMailServer
- PHP version: 7.4.32
- SnappyMail Version: 2.18.6

**Comment by setoy** [comment]
Quick feedback: Even with the changes it still logs some informational entries. Dunno if that's intended tho:

![image](https://user-images.githubusercontent.com/6497266/195911031-73b72e1d-f12b-425e-ae56-c0ef55476040.png)

**Comment by the-djmaze** [comment]
I will reopen this ticket for a complete redesign of the logging.
As there are currently two loggers with different approaches.

It always nagged me, so i will use this issue for it
