### ISSUE TITLE
[Nextcloud] Embed without iframe has broken styles

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#558]
**Describe the bug**
Enabling the (experimental) button "Embed without iframe" breaks the design (mentioned here https://github.com/the-djmaze/snappymail/issues/96#issuecomment-1277236142).
As if the style sheet could not be loaded. For example, the background image is not displayed.

Looking at the network traffic, all css files are loaded except for:
`/extra-apps/snappymail/css/style.css?v=180d33cd`
which isnt loaded in embed mode.

Though that shouldn't make a difference since the file is empty anyway.

**Please complete the following information:**
- Browser: Firefox 105
- IMAP daemon: –
- PHP version: –
- SnappyMail Version: 2.19.1

PS.: make the text in the About section selectable so that we can copy the version number 😉

**Comment by the-djmaze** [comment]
My default Nextcloud has no issues. Maybe you use a different theme that has a background?

You should modify the embed.css file and see if something helps:
https://github.com/the-djmaze/snappymail/blob/master/integrations/nextcloud/snappymail/css/embed.css

Or check the Nextcloud theme:
https://github.com/the-djmaze/snappymail/blob/f53dab1baa716e0476c54fef7a9751c808c9a927/integrations/nextcloud/snappymail/app/themes/Nextcloud/styles.css#L50

**Comment by relikd** [comment]
I havent changed any Nextcloud styling. The background I am referring to is the Rainloop Default theme background.

With iframe:
![1](https://user-images.githubusercontent.com/1321720/196680754-13ef6f58-7a37-4d86-9817-3dea1dae3320.jpg)

With embed:
![2](https://user-images.githubusercontent.com/1321720/196680764-ae6614d8-bff4-4999-8249-a5159971dd5f.jpg)

**Comment by the-djmaze** [comment]
Ah yes, try the Nextcloud theme

**Comment by the-djmaze** [comment]
Got the background working in Nextcloud.
It was bound to the `<body>` and now not anymore
