### ISSUE TITLE
Option to adjust font-size

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#562]
**Is your feature request related to a problem? Please describe.**
I am currently comparing Rainloop and SnappyMail side-by-side and noticed that the new font in SnappyMail is larger than the "old". This results in less content on the screen (especially small screens).

**Describe the solution you'd like**
I would love to customize the font-size and/or the font-family.

**Describe alternatives you've considered**
I have not tested using the user-custom css but assume this could be fixed with a stylesheet. If there is a user-editable custom css that is. I have not found an easy way to edit the css from the admin panel.

**Comment by the-djmaze** [comment]
The font is 13px instead of 12.
The main reason is that Apple has a minimum of 11px so if you want something `<small>` the difference between 11px and 12px is hardly visible.
11px vs 13px is a bit better and still not too big.

**Comment by the-djmaze** [comment]
That could be the font the browser choose from the list of fonts.

The defaults of SnappyMail are here:
https://github.com/the-djmaze/snappymail/blob/master/dev/Styles/%40Boot.css

And you can change them in your own theme or browser css.

**Comment by relikd** [comment]
Perfect. Setting it to "Helvetica Neue" is more to my liking. Is there an easy way to adjust an existing theme instead of create a new theme? More specifically, I'd like to avoid working on the server filesystem and instead tweak the theme via admin UI.

Probably the easiest way: add a menu entry "Custom Style/Theme" to the theme dropdown and then a multi-line text field appears where you can paste your CSS.

Or: add a multi-line text field of CSS that is applied regardless of selected theme.

PS. you mentioned in the other issue that the Nextcloud theme (?) supports dark mode? ... That does not work for me.

**Comment by the-djmaze** [comment]
I've added something for users in the Theme's settings ;)

**Comment by relikd** [comment]
Thank you :) I will try it once the NC version is updated.

> See

Is not triggered for me. There is a hint on `#rl-popups dialog` but I couldnt find any reference. If I replace `#V-PopupsCompose` with `body` (for testing purposes) then the colors are indeed inverted. I assume it has something to do with the popups dialog mentioned.

**Comment by the-djmaze** [comment]
SnappyMail now uses Nextcloud font and hampoelz is making new theme.
So i will close this
