### ISSUE TITLE
missing Root-Account

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#565]
**Describe the bug**
The name of my root-account is disappear.

![grafik](https://user-images.githubusercontent.com/41056353/196728801-ecfbbe61-2da5-455a-93da-d434dd6b4244.png)

I can switch to other accounts but not back to the first one. After logging out and logging in, I can see all emails from the root account and work as usual. But changing from the second account back to the first does not work.

![grafik](https://user-images.githubusercontent.com/41056353/196731003-5bd6a36c-de21-4061-b450-ad95cd42d58a.png)

**Please complete the following information:**
- Browser: firefox & chrome
- PHP version: 7.4
- SnappyMail Version: 2.18.6

**Comment by the-djmaze** [comment]
Are you sure it is 2.18.6?

Because it was reported earlier #543 and fixed in 2.18.5

**Comment by Parodontitis** [comment]
yes:
`<?php

if (!defined('APP_VERSION'))
{
        define('APP_VERSION', '2.18.6');
        define('APP_INDEX_ROOT_PATH', __DIR__ . DIRECTORY_SEPARATOR);
}

if (file_exists(APP_INDEX_ROOT_PATH.'snappymail/v/'.APP_VERSION.'/include.php'))
{
        include APP_INDEX_ROOT_PATH.'snappymail/v/'.APP_VERSION.'/include.php';
}
else
{
        echo '[105] Missing version directory';
        exit(105);
}
`

**Comment by the-djmaze** [comment]
What does your ?admin on the "About" page say?

**Comment by Parodontitis** [comment]
You're right
![grafik](https://user-images.githubusercontent.com/41056353/196876558-124670a7-0060-4039-8a35-ffeb827927e8.png)

What do I have to do other than tar xfvz ... to upgrade my current version? I always did this way.

**Comment by m-i-k-e-y** [comment]
You can add the following to your application.ini (/path_to_snappymail/data/_data_/_default_/configs/application.ini)

> [admin_panel]
allow_update = On

and then you can update from your admin page. Maybe you have to logout and login again for the change to take effect.

Updating from there works like a charm.

**Comment by Parodontitis** [comment]
Ok. Thanks!
