### ISSUE TITLE
Attached inline image not loading

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#566]
**Describe the bug**
An inline image attachement is not displayed properly / not at all:

![screen](https://user-images.githubusercontent.com/1321720/196805398-3b40d071-b387-4d7a-8780-43568f5f3ee1.jpg)

For comparison, the same email is displayed fine in Rainloop.

But this issue gets tricky. The image above is after I impersonated a different person (Nextcloud), using the email account of the other person. When I open the same email account from my SnappyMail tab, I see the following:

![screen2](https://user-images.githubusercontent.com/1321720/196806494-2e3205d1-276e-4c75-aa26-122352ae0547.jpg)

As you can see, at least the attachement indicator is shown. However, clicking the image does not open the preview. Instead a blank page loads: `/apps/snappymail/run/?/Raw/&q[]=/0/Download/&q[]=/b...`. Similarly, the zip download fails and opens another blank URL.

I have not marked this issue with the Nextcloud tag, as I dont know if this is an issue of the impersonate plugin. This could very well be an issue of admin vs. non-admin user.

**Expected behavior**

The image should actually load inline and be immediatelly visible to the user.

**Please complete the following information:**
- Browser: Firefox 105
- SnappyMail Version: 2.19.1

**Comment by relikd** [comment]
... all of the attachements seem to be broken :(

**Comment by the-djmaze** [comment]
Issue was caused due to a change in secure filenames to store in Nextcloud.
But will also affect standalone releases.

Seems i missed one to fix.

**Comment by simonbuehler** [comment]
great its working with the fix, thanks!

**Comment by relikd** [comment]
Some improvement but still broken with 2.19.2. Now I can download the file, but the preview button still does not work / redirects to the empty page. And the inline image is still not loaded / displayed. Text stays "Image.jpeg"

**Comment by relikd** [comment]
And the attachement preview button also does not work yet (the two images above). Comparing admin user vs. non-admin

**Comment by the-djmaze** [comment]
1. when there is a chain after the attachment size, it has no preview.
Because it is inline and chained to the message content and shown there.
Click on it and a new browser tab opens with the image.
2. it works when snappymail cache is emptied and your browser cache

**Comment by simonbuehler** [comment]
> ok, for some attachemnts i still get
> 
> ```
> [2022-10-20 14:40:32.317][1514f651] [ERROR]: MailSo-Base-Exceptions-InvalidArgumentException (Folders.php ~ 303)
> [2022-10-20 14:40:32.317][1514f651] PATHS[ERROR]: Array
> (
>     [0] => Raw
>     [1] => 0
>     [2] => View
>     [3] => b3BlbnNzbA.euPIkNeIOTvTqX9X-H-lhQ.ITRU-LTSTmriBjkHByALfQ9yZ3OT_AngUGYHEV-N2hKNoGSWu4qA6e-ul8hooe4FQi9xhwG-OjWTGMtIJbyh_5fuIX0pKUpy2uvK4K3BsySHNVfR35e9I8jK3VT9fJGkVxNCv7O-3sIUOmCC-SRyrcBkY0CS3_HCvSjxjM_KYmWrk6F5eTAim6fGonqB4kd0_1quRPehsHYpzyEuXlpPyY1FSQTR0WeL8PKie_eq1uEBvWtS31oqWsK5RdVHsQBHzvMf3drsuuUDoOO-374K-yh64-RknRlePwSXqvtfQ1A
> )
> ```

is this another issue?
