### ISSUE TITLE
Number of unread messages isn't shown with Spam folder

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#567]
If there are unread messages in Spam folder, previously the number of the message was shown at the right of folder name. But it isn't shown any more now. Is it intended change?

- Browser
  - Windows
    - Google Chrome 106.0.5249.119
    - Microsoft Edge 106.0.1370.47
    - Mozilla Firefox 106.0
  - Android
    - Google Chrome 106.0.5249.126
    - Microsoft Edge 105.0.1343.50
    - Mozilla Firefox 105.2.0
- IMAP daemon
  - Dovecot 2.3.19
  - Gmail
- PHP version:
  - 8.1.11
- SnappyMail
  - 2.18.6

**Comment by the-djmaze** [comment]
Hahaha i knew this question would pop up!

Someone requested to don't show it #457
So i did this: https://github.com/the-djmaze/snappymail/commit/ec23e3d0caea3ca4dd12ad8bc202ab15785ac1b2

I will make option for it ;)

**Comment by yasuhirokimura** [comment]
> I will make option for it ;)

Please add it.

I need to check spam folder periodically as there is often false positive of spam filter.
And for such purpose it is convenient for me that number of unread mai in spam folder is reported.
