### ISSUE TITLE
[Nextcloud] - Settings UI (user) Security - Behaving Oddly

### ISSUE THREAD

**Issue by HeyVern** [the-djmaze/snappymail#570]
**Describe the bug**
When viewing the per user settings [General, Accounts, Security, Folders, Themes], clicking on Security does not change the view on first click.   Settings defaults to Folders, click Security and nothing happens.  Selecting another selection, then clicking on Security takes one to the security page; however, after that Import Key does not do anything either.

**To Reproduce**
1. Go to 'Settings (user)'
2. Click on 'Security'
3. Click on somthing else, then click Security again.
4. Try to import a key

**Expected behavior**
I have a docker running with snappymail 2.18.6 and it behaves as expected.  The Nextcloud version is 2.19.1 and it's users settings Security is behaving oddly.

Snappymail Nextcloud is PHP version 8.0.24
Snappymail Docker is PHP version 8.1.11

First let me tell you HOW PUMPED I am to have Snappymail inside of Nextcloud.  It is going to be awesome.  They seem like a perfect match and I bet there are going to be MANY people who agree.

**Comment by brtwrst** [comment]
I have the same problem.
The first time you press the Security Button this error appears in the chrome devtools console:
```
Uncaught ReferenceError: Unable to process binding "template: ()=>({name:i.__rlSettingsData.template})"
Message: Unable to process binding "component: function(){return { name:'Select',params:{ inline:true,options:autoLogoutOptions,value:autoLogout,trigger:autoLogoutTrigger,optionsText:'name',optionsValue:'id'}} }"
Message: autoLogoutTrigger is not defined
    at component (eval at bc (libs.min.js:1:30776), <anonymous>:3:157)
    at f.s.o [as Nb] (libs.min.js:1:34424)
    at Function.ac (libs.min.js:1:25373)
    at Function.U (libs.min.js:1:25206)
    at f.s (libs.min.js:1:24140)
    at init (libs.min.js:1:34404)
    at libs.min.js:1:15075
    at Object.S (libs.min.js:1:20220)
    at libs.min.js:1:15061
    at Array.forEach (<anonymous>)
```

**Comment by the-djmaze** [comment]
> Message: autoLogoutTrigger is not defined

There must be something wrong as AutoLogout is always available.
In RainLoop it was optional.

**Comment by brtwrst** [comment]
looking forward to testing it
thanks a lot

**Comment by the-djmaze** [comment]
I just looked a bit deeper and found it!
I was searching for `AutoLogout` case-sensitive but the problem was in the plugin with `AUTOLOGOUT`

So update through SnappyMail Admin -> Extensions to 2.8 and it should be fine
