### ISSUE TITLE
Allowing the default identity to show in the top right corner

### ISSUE THREAD

**Issue by jmrapin81** [the-djmaze/snappymail#571]
**Is your feature request related to a problem? Please describe.**
At the moment the account name is shown next to the user drop down. As sometimes the account username does not mean anything for the user it is quite difficult to know which username relates to which account. 
I use different usernames and email address to provide more security when login into the imap/smtp mail system.
See below in my case. 
![image](https://user-images.githubusercontent.com/116327393/197102174-51790968-d1f6-450b-85c2-ad62a558a78b.png)

![image](https://user-images.githubusercontent.com/116327393/197102401-06b8b56e-e48b-4000-8be0-c21e89d23bb6.png)

**Describe the solution you'd like**
 I would like to opportunity to choose what name is displayed there and in the drop down when switching. Of course the name displayed and the one in the drop down to switch account should be the same.
Alternatively it could be the default identity for this account. You can set the default identity in the list of identities in the settings. That solution would be good enough for me and satisfy the current users as the default identity is the same as the user account login in your current implementation.

**Describe alternatives you've considered**
I had a look through the option in the admin panel and there is nothing that would help here. Unless I have missed something please advise. 

**Additional context**
In the "other" mail app, the user email address is shown and the account email address is shown instead. In my case the user email address makes more sense than the account login username. 

Let me know if what i am suggesting is not clear.

**Comment by cm-schl** [comment]
Hi,
I'm not completely sure I if understood you right: in your case you are seeing the nextcloud username besides the ![grafik](https://user-images.githubusercontent.com/63400209/198209164-7190e2a3-c2f8-4f2e-af0f-07644a5cb4f6.png) button?

Or does your Nextcloud users use mail addresses to log in (and this address is shown there) but are having different "real" mail addresses?

**Comment by the-djmaze** [comment]
I understand what you want but there is no "name" for accounts.

So this is a feature request that you want each account to have a "label" and show the label instead of the email address (when configured).

**Comment by the-djmaze** [comment]
Next release it will be like:

![afbeelding](https://user-images.githubusercontent.com/3752035/200630119-b2183b13-6c31-43c9-bbb7-d4abd758dbe4.png)


![afbeelding](https://user-images.githubusercontent.com/3752035/200629802-a92d27fa-cc23-45be-a3dd-39ae80445fbc.png)

**Comment by jmrapin81** [comment]
@the-djmaze sorry about the late reply. But yes, that will answer my request!
Thank you for looking into that!
