### ISSUE TITLE
Read messages are not showing up as read

### ISSUE THREAD

**Issue by Disco1** [the-djmaze/snappymail#572]
**Describe the bug**
When I click on a message (bolded) that is unread, then read it, it does not revert to "read" (unbolded). 

**To Reproduce**
1. Click unread message
2. View it
3. Click X
4. Refresh

**Expected behavior**
Message shows as read

**Screenshots**

**Please complete the following information:**
- Brave
- IMAP daemon: Don't know
- PHP version: 7.4.30
- SnappyMail Version: Most recent (downloaded today)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
In user settings you can set read timer to delay.
When opening message you should eventualy see the change in the list.
What is your setting?
