### ISSUE TITLE
CKEditor doesn't work

### ISSUE THREAD

**Issue by Disco1** [the-djmaze/snappymail#573]
**Describe the bug**
Adding CKEditor to extensions doesn't do anything

**To Reproduce**
1. Add CKEditor to extensions
2. Regular editor appears

**Expected behavior**
A different editor appears

**Screenshots**

**Please complete the following information:**
- Browser: Brave
- IMAP daemon: Don't know
- PHP version: 7.4.3
- SnappyMail Version: Most recent (downloaded today)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Yes it's an old version 4.6.2 from Jan 12/2017
It was just copy/paste from RainLoop and it seems RainLoop never update it.

You can try and put the latest version in the extension directory and hope that it works?

**Comment by Disco1** [comment]
Where's the extension directory?

**Comment by the-djmaze** [comment]
It is in `_data_/_default_`

**Comment by Bolli84** [comment]
Can someone explain how to update to the latest CKeditor?

**Comment by the-djmaze** [comment]
Version 5 is required but uses webpack.

All plugin code needs to be modified.

Removing CSP is currently the only option, but SnappyMail has no option for that.

**Comment by the-djmaze** [comment]
Because CKeditor 4 will never work, i've removed it.
You may open a feature request if you require CKeditor 5
