### ISSUE TITLE
Spellchecker issue with firefox

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#574]
**Describe the bug**
Spellchecker in editor window is inactive. Only for Firefox  (106.0.1)

**To Reproduce**
Works fine in "To:" field.
![grafik](https://user-images.githubusercontent.com/41056353/197165359-99d2d532-0d59-4697-b9e3-cb5a0a8d8dff.png)

But not in the main editor:
![grafik](https://user-images.githubusercontent.com/41056353/197165715-8beb3fc9-2638-41e0-b26e-e30ac062a879.png)

In Chrome works fine
![grafik](https://user-images.githubusercontent.com/41056353/197166513-cc1773b9-896f-4da7-98ee-5b4154e1f905.png)

Works on github in firefox:
![grafik](https://user-images.githubusercontent.com/41056353/197167267-1ee52358-bcdd-4221-89bc-044ddeb41f6f.png)

**Please complete the following information:**
- Browser:Firefox 106.0.1
- PHP version: 7.4
- SnappyMail Version: 2.18.6

**Comment by the-djmaze** [comment]
Actually, spellcheck should be disabled everywhere by default (since v2.18.1).
So why it works on the "To" field is a mystery to me.

Why i disabled spellcheck everywhere?
This is due to Chrome and Edge sending all data you enter to their servers.
This could include:
- passwords
- email addresses
- encryption keys
- personal/medical data
- etc. etc.

**Comment by Parodontitis** [comment]
Ok. Thank you for your answer. I'm happy to hear that security issues like this will be considered. 

Is there an option to enable the spellchecker?  I'm use firefox only.

**Comment by the-djmaze** [comment]
> Is there an option to enable the spellchecker?

Not yet, as you are the first who notices it :)

**Comment by Parodontitis** [comment]
> Not yet, as you are the first who notices it :)

You must see my creative spelling when i'm not using the spellchecker! :facepalm:

**Comment by the-djmaze** [comment]
Added for next release ;)
