### ISSUE TITLE
Differences in release packages zip and tar.gz of version 2.19.2

### ISSUE THREAD

**Issue by helpy** [the-djmaze/snappymail#575]
**Describe the bug**
The content of the 2.19.2 release packages **snappymail-2.19.2.tar.gz** and **snappymail-2.19.2.zip** is different.
The zip package contains two more files:
![snappymail-2 19 2--package-compare](https://user-images.githubusercontent.com/109762/197275352-29c8d141-636a-40e4-9d96-62325db1fcc6.png)

**To Reproduce**
1. Download both release packages
2. Compare content (I used Beyond Compare)
4. See differences

**Expected behavior**
Identical content.

**Comment by the-djmaze** [comment]
There must be something wrong with your system as the packages are valid.
![afbeelding](https://user-images.githubusercontent.com/3752035/197292416-b3422a80-79df-4bc5-871d-f8cc6a454045.png)

**Comment by helpy** [comment]
You are right!
Obviously the software I use for comparisons has problems reading tar archives.
I'm sorry for the trouble.

I will close this ticket.
