### ISSUE TITLE
Password file does not get generated

### ISSUE THREAD

**Issue by TheNerdFather** [the-djmaze/snappymail#584]
**Describe the bug**
According to the docs, after install, a password file should be available in the data directory to get into the admin panel. 

**To Reproduce**
1. Install the app via the Nextcloud Apps page

**Expected behavior**
A password file should be available at [nextcloud-data]/app_snappymail/_data_/_default_/admin_password.txt

**Screenshots**
N/A

**Please complete the following information:**
- Browser: Vivaldi 5.5.2805.38 (Stable channel) 
- IMAP daemon: (didn't get that far yet)
- PHP version: (Dockerized Nextcloud:latest)
- SnappyMail Version: 2.19.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
Used to have Rainloop working which disappeared yesterday (but still installed)

**Comment by the-djmaze** [comment]
Currently when you access Nextcloud -> Settings -> Administration -> Additional
SnappyMail will try to copy all RainLoop data and settings to itself.
Therefore you should be able to login with your RainLoop login credentials.

**Comment by TheNerdFather** [comment]
Yes this works as expected. A 2FA code field is present (as my NC has 2FA enabled) but I ignored it and used previous credentials. Works. Tx
