### ISSUE TITLE
ExternalSso

### ISSUE THREAD

**Issue by michalcharvat** [the-djmaze/snappymail#585]
Do you plan restore ServiceExternalSso() or is there any similar service how to login user from external app and return the hash that will forwarded to ?Sso&hash= ? 

https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/libraries/RainLoop/ServiceActions.php#L1127

**Comment by michalcharvat** [comment]
It is related to https://github.com/the-djmaze/snappymail/issues/278 however I am not able add or change anything else than app configuration. So the best would be restore ExternalSSO action if possible

**Comment by michalcharvat** [comment]
Perhaps you can return the hash in ExternalLogin method response?

**Comment by the-djmaze** [comment]
The ExternalSso has several security issues.

If you can't use the ServiceSso i will write a secure version of it.

**Comment by michalcharvat** [comment]
@the-djmaze Tell you truth I don't know if it possible extend cloudron version of snappymail with custom script. Sso endpoint is my second step in user authentication process. In first step I would like to receive hash or any other single use token which I could use in GET request that will be open in iframe container in the crm. In RainLoop I called ExternalSso and hash from response was used in iframe with ?Sso&hash=xxx However user wasn't authenticated in iframe for some reason - not sure why - headers were set correctly. That is one of the many other reasons why I would like to switch to snappymail.

**Comment by the-djmaze** [comment]
Did you try the Sso hash of SnappYmail?

**Comment by michalcharvat** [comment]
@the-djmaze not yet. I am missing endpoint where I can get the hash for Sso =) Any hint? Without custom script

**Comment by the-djmaze** [comment]
> Without custom script

Sorry, not possible. You must always write a script to get everything working.

**Comment by michalcharvat** [comment]
@the-djmaze Why? In Rainloop it was possible authorized user just via that two endpoints -> one ExternalSso - that returns hash and second - Sso which was used in frame. I would like to use solution which is mentioned in other issues however I guess I have no option write to the Cloudron snappymail container - especially I have to count with option the mail container could be updated automatically. So if hash could not be returned in ExternalLogin, is possible implement new method similar to ExternalSSO?

**Comment by michalcharvat** [comment]
@the-djmaze Why? In Rainloop it was possible authorized user just via that two endpoints -> one ExternalSso - that returns hash and second - Sso which was used in frame. I would like to use solution which is mentioned in other issues however I guess I have no option write to the Cloudron snappymail container - especially I have to count with option the mail container could be updated automatically. So if hash could not be returned in ExternalLogin, is possible implement new method similar to ExternalSSO?

**Comment by the-djmaze** [comment]
ExternalSso was like:
```html
<form action="http://example.tld/?/ExternalSso">
<input type="hidden" name="SsoKey" value=".....">
<input name="Email">
<input name="Password">
```

This way is not possible due to the Content Security Policy.

However, you can write a script like `http://example.tld/mysso.php` that does the same.
```php
<?php

// Enable SnappyMail Api and include index file
$_ENV['SNAPPYMAIL_INCLUDE_AS_API'] = true;
require 'index.php';

echo \RainLoop\Api::CreateUserSsoHash(
	$_POST['Email'],
	$_POST['Password']
);
```

This is still insecure and you must write additional code to prevent abuse of it.

Summary:
1. It's the same insecure script as ExternalSso
2. It's your decision how secure you make it
3. SnappyMail core stays secure

If i write one, then just POST will not work and you must use Encryption.
Because just sending a username and passphrase over http/https without TLS Certificate validation is just a bad idea.

**Comment by the-djmaze** [comment]
> If I am able to login via ExternalLogin endpoint, whats the difference?

ExternalLogin should only work on same domain.
If not, the CSP is not properly checked/configured.
Someone asked for it and in deed can't get it working and is using the Sso now.
https://github.com/the-djmaze/snappymail/issues/321

And it works like:
1. Browser opens domain.tld/login.php
2. Browser posts to domain.tld/webmail/

ExternalSso is different:
1. Browser opens domain1.tld/login.php
2. Browser posts to domain1.tld/login.php
3. domain1.tld/login.php posts the data to domain2.tld
4. domain1.tld/login.php receives SSO hash
5. domain1.tld/login.php redirects to domain2.tld/Sso&hash=....

The problem here is that RainLoop ExternalSso sends the SsoKey which can be read using MitM.
A better approach:
```php
$data['payload'] = json_encode([
	'email' => 'value',
	'password' => 'value'
]);
$data['hmac'] = hash_hmac(
	'sha256',
	$data['payload'],
	'shared_key_secret'
);

'POST' $data
```
But then the MitM can still read credentials.

**Comment by michalcharvat** [comment]
> The problem here is that RainLoop ExternalSso sends the SsoKey which can be read using MitM.
I don't think this is the real issue - solution for MiTM in this case is valid SSL certificate. However when you have already set SsoKey in configuration, why don't you just use symmetric encryption so there won't be any key or credentials in the http request? Also you can use one-time hash to authorize user. So none of the sensitive data will be visible anywhere...

However it is just an idea. Just let me know if you see any way in this case or shall I search for any alternative to solve our issue.

**Comment by the-djmaze** [comment]
Ok, i've added it to v2.19.3 and you may try it.

**Comment by michalcharvat** [comment]
Thanks I see changes in code, in cloudron app however I am not able get token via this service. When I check the code in PHPStorm I see the error: Method 'GetRequest' not found in \MailSo\Base\Http. When I check the Http class there isnt GetRequest method + also I dont see any magic that could load the param from POST request. Also when I check the ExternalLogin method, the params are loaded directly from _POST variable.

**Comment by the-djmaze** [comment]
Ah yes. I've GetRequest() and made all code use $_GET or $_POST because then it is clear if something must GET or POST.

And while putting back this functionality i forgot to check that.

**Comment by michalcharvat** [comment]
Ok the endpoint works well, however I have problem authorize user. 

Do you have any hint?

https://snappymail/index.php?Sso&hash=<hash> redirect me in new tab to the login page. 

When I try login user via iframe I get an following error: "Disallowed Sec-Fetch Dest: iframe Mode: navigate Site: cross-site User: true"  CSP is correctly set. In Cloudron I am not able modify any snappymail files or web server headers. I am able to change config file but nothing else.

**Comment by the-djmaze** [comment]
SnappyMail is secure and an iframe is something else then ExternalSso.

Are you sure you are doing it the right way?
Why the iframe?

More info about Sec-Fetch is here:
https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/libraries/snappymail/http/secfetch.php

**Comment by michalcharvat** [comment]
Simply because the customer does not want create own email client in CRM and wanted replace RoundCube with light and modern client. Mail is displayed in module dialog so it looks like part of CRM. It is basically running on same domain, in some cases (stage and dev environment) on system domain (however it is mostly configurable via CSP in Cloudron or in app configs). In RainLoop there was an option change config to run app in iframe, not sure if it still possible in snappymail without any other modification. The main mind was user will manage passwords in CRM via cloudron API - so user should be logged in to mail without any login page or password prompt. Currently it almost looks like the easiest solution would be simple mail client integrated directly in CRM because it almost looks like there is no light email client with SSO. RC also needs external script to authorize user.

**Comment by michalcharvat** [comment]
Btw I fully understand difference between iframe and ExternalSSO but I don't understand why I cannot login with generated hash. The main problem is snappymail is accessible with read only filesystem only so I cant debug errors directly in the code.

**Comment by michalcharvat** [comment]
@the-djmaze do you see any solution for my usecase?

**Comment by the-djmaze** [comment]
Yes, but need to figure out a few things for this special use-case.

**Comment by the-djmaze** [comment]
Yes, but need to figure out a few things for this special use-case.

Maybe there is also a way to integrate with Cloudron/CRM better, just as with Nextcloud.

**Comment by michalcharvat** [comment]
Question is what do you need to know. When I am thinking about it in general, OAuth or any similar authentication method would be the best. However SSO for IMAPS etc is solved via Kerberos and common users needs much easier solution. For me current SSO method solution is enough. One endpoint where you should send your credentials - via post or simply encrypted via SSO key that will be stored inside config options will gives you hash you can use to authorize user. After successfull login single-use token visible in URL will be dropped - replaced with something else - and user will be insdie the frame redirected to the root. So I guess the only what should be configurable are snappy mail security options. CSP is configurable via Cloudron however I have update also snappy/rainloop configuration options. From my point of view we have to solve option how to allow open snappymail directly in iframe (of course with additional security options). This way will open snappy mail integration into any app where you do not want to create your own email client.

**Comment by the-djmaze** [comment]
I understand that, but CSP and Sec-Fetch are tricky depending on browser.
I noticed this by using different browsers.

So a detailed security configuration in admin and application.ini is required.

**Comment by the-djmaze** [comment]
I've added a new `application.ini` option `secfetch_allow`.
Here you can configure additional allowed rules for the Sec-Fetch check.

In your case of ` "Disallowed Sec-Fetch Dest: iframe Mode: navigate Site: cross-site User: true"` you can set it to:

`dest=iframe,mode=navigate,site=cross-site`

To put the iframe on the same (sub)domain would be wiser as cross-site could also be `potentially-evil.com`

Then the rule would be:

`dest=iframe,mode=navigate,site=same-site`

**Comment by michalcharvat** [comment]
I just tested it however looks like it does not work as descibed. When I try access page via https://smail/index.php?Sso&hash=<hash> I get the same error... i am sorry however I can debug in the code because snappy mail is mounted with RO filesystem
<img width="540" alt="image" src="https://user-images.githubusercontent.com/8058273/201088213-f1e3f3aa-dbcb-4fb9-a60c-18a4107750d2.png">
