### ISSUE TITLE
No access to Nextcloud Additional Settings after enabling Snappymail

### ISSUE THREAD

**Issue by samps** [the-djmaze/snappymail#586]
When trying to access my Nextcloud instance's 'Additional Settings' to set up Snappymail I am presented with a white page with only the text:

[105] Missing version directory

Removing Snappymail (or just disabling tit) restores the settings page for all the other apps that use 'Additional Settings'

1. Go to 'Nextcloud Apps...'
2. Search for Snappymail and click on its install button...'
3. Then go to 'Additional settings....'

I was expecting to be presented with a link to the Snappymail admin section, a login and a temporary password

**Please complete the following information:**
- Browser: Firefox 105, 64-bit and Chrome 106.0.5249.119 (Official Build) (64-bit)
- Nextcloud version: 25.0.0
- SnappyMail Version: 2.19.2

**Comment by the-djmaze** [comment]
Does `nextcloud/apps/snappymail/app/snappymail/v/2.19.2/` exist?

**Comment by samps** [comment]
Yes. In /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.19.2
October 26, 2022 5:12 PM, "the-djmaze" ***@***.*** ***@***.******@***.***>)> wrote:
	Does nextcloud/apps/snappymail/app/snappymail/v/2.19.2/ exist?

**Comment by samps** [comment]
Thanks for that.

I installed v2.19.3 and it displays the exact same error and behaviour.

I also noticed that the same error is thrown if I just click the Snapppymail icon in the main menu.

**Comment by the-djmaze** [comment]
> I installed v2.19.3 and it displays the exact same error and behaviour.

That's not possible because i modified the error message.

**Comment by samps** [comment]
Sorry, my bad. Didn't realise that I had to restart my Nextcloud server to make the changes work.

Snappymail now seems to work as intended.

Thanks for fixing it

**Comment by the-djmaze** [comment]
> restart my Nextcloud server

I think your PHP Opcache thinks the files never changed.
You can't just restart/reload PHP/PHP-FPM or clear the Opcache?

**Comment by samps** [comment]
Probably! But I didn't think of it.
On the upside...  I only have to alert three other users about the 15 seconds of outage that a complete restart causes...

thanks again for your help
