### ISSUE TITLE
Unable to add an account

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#587]
**Describe the bug**
When I try to add an account with a different domain it says "domain not allowed" and won't let me add it.

**To Reproduce**
1. The SnappyMail administrator sets up each domain.
2. Run a test in each domain and confirm that it passed.
3. User performs an account addition operation.

**Expected behavior**
An account will be added.

**Please complete the following information:**
- PHP version: 8.1
- SnappyMail Version: 2.19.2

**Additional context**
I don't understand what the whitelist tab means, but entering the relevant domain there does not change the situation.
Can SnappyMail add another domain?

**Comment by the-djmaze** [comment]
Your message is unclear.
Please write all steps (screenshots) and we might can help.

**Comment by Bables55** [comment]
When I try to add another account from the right menu or settings, I get the attached image and cannot add it.
![image](https://user-images.githubusercontent.com/30524004/197989918-e0599f1c-8430-4ef2-b8d8-84b66f3dcc22.png)

**Comment by the-djmaze** [comment]
Show a screenshot of your Admin -> Domains -> Domain settings
Mostly the problem is there.

A good example is this post where someone accidentally named the domain `imap.gmail.com`
https://github.com/the-djmaze/snappymail/issues/433#issuecomment-1290999836

**Comment by Bables55** [comment]
I'm very sorry. I see that the name field _Name (wildcard supported)_ is important. I have treated this place like a nickname.
I was able to add a domain by entering a domain that included a subdomain after @ symbol.

**Comment by the-djmaze** [comment]
There's also an application.ini setting for default domain.
So you can login with only your name.
For example set it to `gmail.com` then login as `bables55` with password will be converted to `bables55@gmail.com`

This is mostly usefull for system users.
Say your server is named `server1.example.com` and then the login becomes `bables55@server1.example.com`

Then in Admin domains add domain `server1.example.com` with the right configuration.
