### ISSUE TITLE
Improve UI to let user understand which filter is active

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#590]
**Is your feature request related to a problem? Please describe.**
From a user perspective the setting dialog for sieve filters does not seem clear to me when there is only the default filter "rainloop.user" as there is only one radio button that can be clicked AND has to be clicked once again to disable the filter.

I think there are multiple points connected:
* if there is only one radio button it could also be interpreted as a simple bullet. So the don't click on it to activate the filter.
* users could not understand that the filter could be disabled by clicking again on the radio button as this is not possible everywhere (for example in many windows programs).
* the users gets no message / feedback that the filter has been activated when he clicks on the radio button
* thinking about the prior point it seems also a bit incoherent that the "edit script" dialog has a "Save" button in it, but other settings in SnappyMail are saved directly.

**Describe the solution you'd like**
As I'm no designer it's a bit hard to describe a solution but I think:
* the user should directly see if a filter is active
* ... and which filter is active

so maybe something similar to the "Edit Domain" dialog in the admin panel could work?
![grafik](https://user-images.githubusercontent.com/63400209/198335226-b098307a-5d89-43a7-b277-45111b8eff2e.png)

The symbol before "Simple filter" would be intended to make visible which filter is active (and if there is one) - maybe in some other color? 

This is just an idea, surly there are better approaches 🙂

**Comment by the-djmaze** [comment]
I understand, but a checkbox is confusing.
Only 1 can be active and with checkbox people think they can activate multiple.

With a radio button you know only 1 can be selected.

So what you are missing is an extra option: `none active`

**Comment by cm-schl** [comment]
You're right, also a checkbox could confuse the user.
Damn, your solution with the additional option is so simple and should work perfectly 🤦‍♂️😁
