### ISSUE TITLE
No page numbers at the bottom of message list area

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#591]
Listing messages in my Trash folder with 2.19.2. There are page numbers (1 2 3 4 5 ... 227) at the bottom of message list area.

![SnappyMail PageNumbers 2 19 2](https://user-images.githubusercontent.com/5249848/198405770-4753d2e5-584d-41ba-845b-e468662e4d42.png)

Same with 2.19.3. Now There aren't page numbers at the bottom of message list area.

![SnappyMail PageNumbers 2 19 3](https://user-images.githubusercontent.com/5249848/198405814-181bc5dd-e81b-47de-969b-acfa66e535d2.png)

- Browser
  - Windows
    - Google Chrome 107.0.5304.88
    - Microsoft Edge 107.0.1418.24
    - Mozilla Firefox 106.0.2
  - Android
    - Google Chrome 107.0.5304.54
    - Microsoft Edge 106.0.1370.47
    - Mozilla Firefox 106.1.0
- IMAP daemon
  - Dovecot 2.3.19
- PHP version:
  - 8.1.11
- SnappyMail
  - 2.19.3

**Comment by the-djmaze** [comment]
Sorry! Was caused by changes for #579
