### ISSUE TITLE
Show calendar content if .ics file is within attachments

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#592]
The putICS is already a good solution, but the information for the calendar content is missing.
It would be good to create a little box in the mail content, which is showing the calendar content (Title, Timezone, Date Time) to see this content.

The box and how to render it within nextcloud is already included in: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/152#issue-613532704

![cal](https://user-images.githubusercontent.com/37924972/198524697-be90459d-f699-4e28-8403-b6d04a77f91e.png)

**Comment by the-djmaze** [comment]
The code in that post is hardly readable.
Can you use 3 backticks to properly code it?

Like:
```javascript
var windowHtml = `<title>Add to Calendar</title>
<script>
var allOptions = "";
var optionString = 'option';
`;
```

**Comment by the-djmaze** [comment]
You may also modify the code, test it and then create a pull request.

See the code at https://github.com/the-djmaze/snappymail/blob/master/plugins/nextcloud/
And especially
https://github.com/the-djmaze/snappymail/blob/master/plugins/nextcloud/js/message.js

**Comment by Bolli84** [comment]
/*Holt sich die Dateinamen und Links aller Anhänge*/
function getFileInfo(){
    var rainloopFrame = document.getElementById("rliframe");
    var items = rainloopFrame.contentDocument.getElementsByClassName("attachmentItem");
    var names = [];
    var links = [];
    for(let i=0; i<items.length; i++){
        if (items[i].title.endsWith(".ics")){
            names.push(items[i].title);
            links.push(items[i].getElementsByTagName("a")[0].href);
          break
        }
    }
    return [names, links];
}
function getNamesString(names){
    var full="";
    for(let i=0; i<names.length; i++){
        full += names[i];
    }
    return full;
}
//duplicate to make freebusy working
function getFileInfo2() {
    var rainloopFrame = document.getElementById("rliframe");
    var items = rainloopFrame.contentDocument.getElementsByClassName("attachmentItem");
    var links = [];
    for (let i = 0; i < items.length; i++) {
        if (items[i].title.endsWith(".ics")) {
            links.push(items[i].getElementsByTagName("a")[0].href);
        }
    }
    return links;
}



//xmlhttpget but synchrone not async
function httpsyncGet(theUrl) {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", theUrl, false); // false for synchronous request XXYY
    xmlHttp.send(null);
    return xmlHttp.responseText;
}



/*Funktion für GET-Anfragen*/
function httpGet(theUrl)
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false); // false for synchronous request XXYY
    xmlHttp.send( null );
    return xmlHttp.responseText;
}
/*Parsen der ICS-Datei*/
function getTitle(textToParse){
    let lines = textToParse.split("\n")
    let eventCode = false;
    for(let i = 0; i < lines.length; i++){
        if(lines[i].indexOf("BEGIN:VEVENT")>-1){
            eventCode=true;
        }
        if(eventCode){
            if(lines[i].indexOf("SUMMARY")>-1){
                return lines[i].substring(lines[i].indexOf(":")+1, lines[i].length);
            }
        }
    }
}
function getEXStart(textToParse){
    var lines = textToParse.split("\n");
    var eventCode = false;
    for(let i = 0; i < lines.length; i++){
        if(lines[i].indexOf("BEGIN:VEVENT")>-1){
            eventCode=true;
        }
        if(eventCode){
            if (lines[i].indexOf("EXDATE") > -1) {
                return gettime(getTextUntilEnd(i, textToParse));
                //return gettime(lines[i]);
            }
        }
    }
}
function isReoccouring(textToParse){
    if(textToParse.indexOf("SEQUENCE:1")>-1){
        return true;
    }
    return false;
}
function getStatus(textToParse){
    let lines = textToParse.split("\n")
    let eventCode = false;
    for(let i = 0; i < lines.length; i++){
        if(lines[i].indexOf("BEGIN:VEVENT")>-1){
            eventCode=true;
            // console.log(`the event code is ${eventCode}`)

        }
        if(eventCode){
            if(lines[i].indexOf("STATUS")>-1){
                console.log(lines[i]);
                console.log(`the status is code is ${lines[i].replace("STATUS", "").replace(":", "").replace(";", "")}`)
                return lines[i].replace("STATUS", "").replace(":", "").replace(";", "");

            }
        }
    }
    return "CONFIRMED";
}
function getStart(textToParse){
    let lines = textToParse.split("\n");
    let eventCode = false;
    for(let i = 0; i < lines.length; i++){
        if(lines[i].indexOf("BEGIN:VEVENT")>-1){
            eventCode=true;
        }
        if(eventCode){
            if (lines[i].indexOf("DTSTART") > -1) {
                return gettime(getTextUntilEnd(i, textToParse));
                //return gettime(lines[i]);
            }
        }
    }
}
function getEnd(textToParse){
    let lines = textToParse.split("\n");
    let eventCode = false;
    for(let i = 0; i < lines.length; i++){
        if(lines[i].indexOf("BEGIN:VEVENT")>-1){
            eventCode=true;
        }
        if(eventCode){
            if (lines[i].indexOf("DTEND") > -1) {
                return gettime(getTextUntilEnd(i, textToParse));
                //return gettime(lines[i]);
            }
        }
    }
}

function getTextUntilEnd(lineNum, fulltext) {
    let lines = fulltext.split("\n");
    var text = lines[lineNum];
    //console.log(text);
    var i = 1;

    while (true) {
        var nextLineText = lines[lineNum + i];
        i += 1;
        if (nextLineText.startsWith(' ') || nextLineText.startsWith('\t')) {
            text += nextLineText.substring(1, nextLineText.length);
        }
        else {
            break;
        }
    }
    //console.log("Return:" + text);
    return text;
}


function gettime(textToParse) {
    var pos = Math.max(textToParse.lastIndexOf(':'), textToParse.lastIndexOf(';'));
    var dateText = textToParse.substring(pos + 1, textToParse.length);
    //console.log(dateText);
    return dateText;
}
function gettimezone(textToParse) {
    let lines = textToParse.split("\n");
    let eventCode = false;
    var TZText = "UTC";
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].indexOf("BEGIN:VCALENDAR") > -1) {
            eventCode = true;
        }
        if (eventCode) {
            if (lines[i].indexOf("DTSTART") > -1) {
                if (lines[i].includes("TZ")) {
                    TZText = lines[i].split('=').pop().split(':')[0];
                    //TZText = TZText.slice(1, -1); //TZText = TZText.slice(1, -1);
                }
            }
            //if (lines[i].indexOf("TZID") > -1) {
            //    console.log(lines[i]);
            //    var pos = Math.max(lines[i].lastIndexOf('='), lines[i].length);
            //    TZText = lines[i].substring(pos + 1, lines[i].length);
            //    console.log(lines[i]);
            //}
        }
    }
    console.log(`the timezone is ${TZText}`)
    return TZText;
}
function timeString(line){
	try{
        let numbers = "";
        for(let i=line.length-1; i>=0; i--){
            if(!isNaN(line[i]) && line[i]!="\n" && line[i] !="\r"){
                numbers += line[i];
            }
            if(numbers.length>=14){
                break;
            }
        }
        let buffer = "";
        for(let i = numbers.length; i < 14; i++){
            buffer = buffer + "0";
        }
        numbers = buffer + numbers;
        let sec   = parseInt(numbers[1]+numbers[0]);
        let min   = parseInt(numbers[3]+numbers[2]);
        let hour  = parseInt(numbers[5]+numbers[4]);
        let day   = parseInt(numbers[7]+numbers[6]);
        let month = parseInt(numbers[9]+numbers[8]) - 1;
        let year  = parseInt(numbers[13]+numbers[12]+numbers[11]+numbers[10]);
        let date  = new Date(year, month, day, hour, min, sec);
		
		//timezone from calendar is not taken into account, it just is used as simple date and time
		//1: Get the calendar timezone
		//2: compare against broswer timezone
		//3: console.log() the adjusted timezone with the difference

		return date;
    }
    catch(e){
        return line;
    }
}

function convertTZ(date, tzString) {
    dateObj = new Date(typeof date === "string" ? new Date(date) : date)
    console.log(dateObj.toLocaleString("en-US", {timeZone: tzString}))
    return new Date((typeof date === "string" ? new Date(date) : date).toLocaleString("en-US", {timeZone: tzString}));   
}

function getTimeString(date){ 
    return date.getDate()+"."+(date.getMonth()+1)+"."+date.getFullYear()+" at: "+date.getHours()+":"+date.getMinutes()+" ("+date.getSeconds()+")"; 
}


const daysOfWeek = {
  "SU": 0,
  "MO": 1,
  "TU": 2,
  "WE": 3,
  "TH": 4,
  "FR": 5,
  "SA": 6,
}

function lastWeekday(year, month, weekday, order_ = -1) {
  const order = parseInt(order_)
  if (order < 0) {
    let date = new Date(year, month + 1, 1, 12)
    let myday = date.getDay()
    let mydiff = myday - weekday
    let dayDiff = (mydiff <= 0) ? (mydiff + 7) : mydiff
    date.setDate(date.getDate() - (dayDiff - 7 * (order + 1)))
    return date
  }
  else if (order > 0) {
    let date = new Date(year, month, 1, 12)
    let myday = date.getDay()
    date.setDate(date.getDate() - 1)
    let mydiff = myday - weekday
    let dayDiff = (mydiff < 0) ? (mydiff + 7) : mydiff
    date.setDate(date.getDate() - (dayDiff - 7 * (order)))
    return date
  }
}


function TZCreator(myDate, UTCOffset) {

  const UTCTimeMSec = new Date(new Date(myDate).getTime() - myDate.getTimezoneOffset() * 60 * 1000).getTime()

  if (UTCOffset === "Z") {
    return new Date(UTCTimeMSec)
  }
  const offsetRegexp = /(?<sign>[+-]):?(?<hour>\d?\d):?(?<min>\d\d)/
  const { sign, hour, min } = UTCOffset.match(offsetRegexp).groups
  // obtain local UTC offset and convert to msec
  const localOffsetMSec = 1000 * (hour * 60 * 60 + min * 60)
  // obtain UTC time in msec
  return new Date(UTCTimeMSec - (Number(`${sign}${localOffsetMSec}`)))
}


const parseIcsSection = (ics, section) =>
  ics.split(`BEGIN:${section}`)[1]?.split(`END:${section}`)[0]


function icsSectionToObject(icsSection) {
  if (!icsSection) {
    return
  }

  let icsFieldsAsArray = icsSection.split(/\r?\n/).reduce(function (previousValue, currentValue) {
    if (currentValue.startsWith(' ') || currentValue.startsWith('\t')) {
      previousValue.push(previousValue.pop() + currentValue)
    }
    else {
      previousValue.push(currentValue)
    }
    return previousValue
  }, [])

  let object = {}
  for (const icsField of icsFieldsAsArray) {
    let [prop, ...value] = icsField.split(/[:;]/)
    value = value.join(";")
    object = { ...object, [prop]: value }
  }
  return object
}


const parseTZChangeDate = (year, rrule) => {
  const rruleFields = rrule.split(";")

  let RRULE = {}
  for (const item of rruleFields) {
    let [prop, value] = item.split("=")
    RRULE = { ...RRULE, [prop]: value }
  }

  const month = RRULE["BYMONTH"]
  const byDay = RRULE["BYDAY"].match(/(?<order>-?\d+)(?<weekday>[a-zA-Z]+)/).groups
  let mydate = lastWeekday(year, month - 1, daysOfWeek[byDay.weekday], byDay.order)
  return mydate
}


function calculateTZFromInfo(date_, ics) {
  const date = new Date(date_)
  const daylightTZSection = icsSectionToObject(parseIcsSection(ics, "DAYLIGHT"))
  const standardTZSection = icsSectionToObject(parseIcsSection(ics, "STANDARD"))

  if (standardTZSection["RRULE"]) {
    const stdDate = parseTZChangeDate(date.getFullYear(), standardTZSection["RRULE"])
    const daylightDate = parseTZChangeDate(date.getFullYear(), daylightTZSection["RRULE"])

    const isDstObserved = (date_) => {
      return date_.getTime() < stdDate.getTime() && date_.getTime() >= daylightDate.getTime()
    }
    const TZ = isDstObserved(date) ? daylightTZSection["TZOFFSETTO"] : standardTZSection["TZOFFSETTO"]
    return TZ
  } else {
    return null
  }
}


function parseDates(ics) {
  const vevent = icsSectionToObject(parseIcsSection(ics, "VEVENT"))

  const parseDatefromISO = (isoDateString) => {
    const ISO_8601_FULL = /(?<year>\d{4})-?(?<month>\d\d)-?(?<day>\d\d)T(?<hour>\d\d):?(?<min>\d\d):?(?<sec>\d\d)\.?(?<msec>\d+)?(?<tz>(?:[+-]\d\d:?\d\d)|Z)?/
    return isoDateString.match(ISO_8601_FULL).groups
  }
  const parsedInitDateInfo = parseDatefromISO(vevent["DTSTART"])
  const parsedEndDateInfo = parseDatefromISO(vevent["DTEND"])

  const createDate = (obj) =>
    new Date(obj.year, obj.month - 1, obj.day, obj.hour, obj.min, obj.sec)

  const initDateTemp = createDate(parsedInitDateInfo)
  const endDateTemp = createDate(parsedEndDateInfo)

  const tz = parsedInitDateInfo.tz ?? calculateTZFromInfo(initDateTemp, ics)

  if (tz) {
    const initDate = TZCreator(initDateTemp, tz)
    const endDate = TZCreator(endDateTemp, tz)
    return { initDate, endDate, tz }
  } else {
    const initDate = TZCreator(initDateTemp, "Z")
    const endDate = TZCreator(endDateTemp, "Z")
    return { initDate, endDate, tz: null }
  }
}

/**
* date: Date = date object
* locales: string | [] = 'en-us' | []
* type: string = 'short' | 'long'
**/
function getTimeZoneName(date, locales, type) {
  return new Intl.DateTimeFormat(locales, { timeZoneName: type })
    .formatToParts(date)
    .find(part => part.type == "timeZoneName")
    .value
}


function dateStr(mydate, tz) {
  const options = {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: 'numeric', minute: 'numeric', second: 'numeric',
    weekday: 'short', hour12: false
  }

  console.log(tz)

  if (!tz) {
    let dateString = mydate.toLocaleString('default', { ...options, timeZone: 'UTC' });
    return `${dateString} No Timezone detected. Using UTC`
  }

  let dateString = mydate.toLocaleString('en-US', options);
  let shortTimeZone = getTimeZoneName(mydate, [], 'short');
  let longTimeZone = getTimeZoneName(mydate, [], 'long');
  let timeZoneStr = `${shortTimeZone} ${longTimeZone}`
  const dateStr = `${dateString} ${timeZoneStr}`
  return dateStr
}


/*HTML der Vorschautabelle*/
var tableStyle = '<style>\
.calth {\
text-align: left;\
}\
.calth, .caltd {\
padding: 15px;\
}\
.caltable, .calth, .caltd {\
border: 1px solid black;\
border-collapse: collapse;\
}\
</style>'

var tableHtml = '<table class="caltable", style="width: 80%; margin-left: 10%; background-color:#E9E9E9">\
<tr>\
<th class="calth" bgcolor=#C3C3C3>__icon__Title</th><th class="calth">__title__</th>\
</tr>\
<tr>\
<td class="caltd" bgcolor=#C3C3C3>Start</td><td class="caltd">__stime__</td>\
</tr>\
<tr>\
<td class="caltd" bgcolor=#C3C3C3>End</td><td class="caltd">__etime__</td>\
</tr>\
</table>\'

var deletedIconHtml = '<img style="display:block;float:left;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAQCAYAAADwMZRfAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABpElEQVQ4ja2Uv2sTcRjG31dwcvD+Axe3JIfXdhBJTFfJJqhwRgdxqeBYie7+ASIZ3MUScSs69wpupxUL0qZ4p/YCQc1d7sxVPa98HGxtmx+C1Ree6X35fB+e9+WrgPxrHRERye43yK9XGKwsH44ISD5rsD2j/KgaJC8cAPkbCSCDVpNsWsmmle9Vg8Hj5kTQVqtJfslkBAJIsrRIetYgnVLSKSVpHQTFgc/WHZt8RkmHegdeSVyH+NwJYkuJLaW/Mxy7DulFk69Vgy9PH464HLHb7/iEF0xCSwktJbptk1hKUjHou+PzmhhWr2Hz6ZT+VjQBAPxa8XBFL5fJVp5LhuzpyYM/38n++nivQXptVvLuB9GTJTl6865sHzsu354tSLdxefwd7VqKOu/YvFrBKyleSQlu1IgCH0B6roN/xsAzleCWPT7Yz65D+7TBWlFZKyrvxwz21l/hnzfZKCmbQ30BpF0vs1pQVguKPz8K2FXY8fHmarwpKm+vlAl3nAog3aVF1usVgoXJl7pf3rzN64LSrpf3IIdR8KjJxlwNQJT/8BX8BOHOQWNSNO6iAAAAAElFTkSuQmCC">'
var reloadIconHtml = '<img style="display:block;float:left;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAABHElEQVQ4jaXTsSuFURzG8c9FMhgNLNcdFOmmyGJwJ8mgWJhJiSKDv8GqkEIUKxaSKyODiZSU+Q53MksG1/CeN2+ve0n3qdOpc37fp9/p+Z1MpVJRj5pgeHQiedaFFYwjhxIeUMQ+PrFwe322Aw0pwyU8hz2HRzRjEru4xzQ2YiBpMI8tvGMWjehHBzpxiD4cBdPvJyAb4DKGQttJlTCHQeSTF3EHq8F1sQocay0NJzsoBPC8BgwnYVU16MHVLzBREj+UTuHfig1eMFCPwaUoiZE/6lvVSGEbHzhAew04izvRMBXSBmUsh6InjKXgmQDnsY6b+KIpUbSHFtGYFvEqirY3nJcwhdNqT4i1KRrfY7yhDRehu+40DJl6v/MXlA86LTXMv9MAAAAASUVORK5CYII=">'
var normalIconHtml = '<img style="display:block;float:left;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAhUlEQVQ4jaWT0Q2AIAxED+IGjoIzwUwwk4ziDPijkeKJJdxXobnHQYoppWBGy12EBEnKWS6reo/OvAAAEH29cvTELUiwVeXsSCQI4Tv2PyBn+NjEPq7W+mwl9RWImYkDlGYO6JnJo1jRGzTTBD0zYwjAqJkmGDH3AQoz0ExiOyQamdnvfAI+yCsdMn6vFAAAAABJRU5ErkJggg==">'



setInterval(addButtons, 1000);

function RainLoopFormHelper(sID, sAjaxFile, fCallback)
{
    try
    {
        var
            oForm = $(sID),
            oSubmit = $('#rainloop-save-button', oForm),
            sSubmitValue = oSubmit.val(),
            oDesc = oForm.find('.rainloop-result-desc')
        ;

        oSubmit.click(function (oEvent) {

            var oDefAjax = null;

            oEvent.preventDefault();

            oForm
                .addClass('rainloop-ajax')
                .removeClass('rainloop-error')
                .removeClass('rainloop-success')
            ;

            oDesc.text('');
            oSubmit.val('...');

            oDefAjax = $.ajax({
                'type': 'POST',
                'async': true,
                'url': OC.filePath('rainloop', 'ajax', sAjaxFile),
                'data': oForm.serialize(),
                'dataType': 'json',
                'global': true
            });

            oDefAjax.always(function (oData) {

                var bResult = false;

                oForm.removeClass('rainloop-ajax');
                oSubmit.val(sSubmitValue);

                if (oData)
                {
                    bResult = 'success' === oData['status'];
                    if (oData['Message'])
                    {
                        oDesc.text(t('rainloop', oData['Message']));
                    }
                }

                if (bResult)
                {
                    oForm.addClass('rainloop-success');
                }
                else
                {
                    oForm.addClass('rainloop-error');
                    if ('' === oDesc.text())
                    {
                        oDesc.text(t('rainloop', 'Error'));
                    }
                }

                if (fCallback)
                {
                    fCallback(bResult, oData);
                }
            });

            return false;
        });
    }
    catch(e) {}
}


function readyFunc(filename, fileLink, remove) {
  let username = getUserName();
  if (remove) {
    try {
      const [result, calendar] = removeEvent(username, "password", fileLink);
        console.log(result);
        if (result.toString().match(/^20*/)){
            alert(`Successfully removed from the calendar ${calendar}`)
        } else {
       alert("Not removed. Please check if it was already deleted")
        }
    } catch (e) {
      console.log("Network error, while removing event from Calendar. Retry.");
      console.log(e);
      return;
    }
  } else {
    try {
      const [result, calendar] = putIcsFile(username, "password", fileLink);
      console.log(result);
        if (result.toString().match(/^20*/)){
            alert(`Successfully added to the calendar ${calendar}`)
        }
    } catch (e) {
      console.log("Network error, while uploading ics file to Calendar. Retry.");
      console.log(e);
      alert(e);
      return;
    }
  }
//  if (document.getElementById("jump").checked) {
//    window.open("https://" + hostname + "/index.php/apps/calendar/dayGridMonth/now");
//  }
//  if (document.getElementById("response").checked) {
//    alert("Respond by mail not yet working :-( ");
//    window.open("mailto:__mailrespond__?subject=CalendarAccept&body=Accepted!");
//  };
}

function getUID(textToParse) {
  let lines = textToParse.split("\n");
  let eventCode = false;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].indexOf("UID") > -1) {
      return getTextUntilEnd(i, textToParse).replace("UID", "").replace(":", "").replace(";", "").replace("\n", "").replace("\t", "").replace("\r", "").replace("\r\n", "");
    }
  }
}
// --------------------------------------------------------------------------------
// This parts focuses on uploading microsof office file attchments
function onclick(info) {
  let username = getUserName();
  httpGetDocx(username, "password", info.title, info.dataset.link);
}

function putdocxFiles(username, password, content, filename) {
  let hostname = OC.getHostName();
  var rainloopFrame = document.getElementById("rliframe");
  try {
    let xmlHttp = new XMLHttpRequest();
    xmlHttp.open(
      "PUT",
      "https://" +
        hostname +
        "/remote.php/dav/files/" +
        username +
        "/" +
        filename,
      true
    );
    xmlHttp.onreadystatechange = function () {
      if (xmlHttp.readyState == XMLHttpRequest.DONE) {
        var myHeader = xmlHttp.getResponseHeader("OC-FileId");
        var OCid = myHeader.substring(2, 8);
        let OOurl =
          "https://####localhost###/index.php/apps/onlyoffice/" + OCid;
        console.log(OCid);
        window.open(OOurl, filename);
      }
    };
    let mimeType =
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    xmlHttp.setRequestHeader("Content-Type", mimeType);
    xmlHttp.setRequestHeader(
      "Authorization",
      "Bearer " + btoa(username + ":" + password)
    );
    xmlHttp.send(content);
    xmlHttp.onload = function (e) {
      if (xmlHttp.status == 200) {
        // everything is OK
        // console.log(xmlHttp.responseText);
      } else {
        // alert(xmlHttp.status + " " + xmlHttp.responseText);
        // console.log(xmlHttp.responseText);
      }
    };
  } catch (e) {
    alert("Something went wrong: " + e);
  }
}
function getDocxInfo() {
  if (window.location.href.includes("/rainloop/") == true) {
    var rainloopFrame = document.getElementById("rliframe");
    var items =
      rainloopFrame.contentDocument.getElementsByClassName("attachmentItem");

    for (let item of items) {
      if (
        endsWithAny(
          [
            ".docx",
            ".pptx",
            "xlsx",
            "docm",
            "ods",
            "otp",
            "ppt",
            "xls",
            "doc",
            "odp",
            "odt",
            "rtf",
          ],
          item.title
        )
      ) {
        let preview = item.querySelector(".attachmentIconParent.pull-left");
        preview.addEventListener("click", function () {
          onclick(item);
        });
        preview.setAttribute("style", "cursor: pointer;");
      }
    }
  }
}

//check if string ends with any of array suffixes
function endsWithAny(suffixes, string) {
  for (let suffix of suffixes) {
    if (string.endsWith(suffix)) return true;
  }
  return false;
}


function httpGetDocx(username, password, filename, myUrl) {
  theUrl =
    "https://####localhost###/index.php/apps/rainloop/app/" + myUrl;
  let xhr = new XMLHttpRequest();
  xhr.open("GET", theUrl, true);
  xhr.responseType = "blob";
  let mimeType =
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

  xhr.onload = function (e) {
    if (this.status == 200) {
      // Note: .response instead of .responseText
      let blob = new Blob([this.response]);
      // url = URL.createObjectURL(blob);
      // console.log(blob);
      // let file = new File([blob], filename, { type: mimeType });
      resp = putdocxFiles(username, password, blob, filename);
    }
  };

  xhr.send();
}

setInterval(getDocxInfo, 1000);

**Comment by the-djmaze** [comment]
Your code is incomplete and has loads of not related code.
Could you properly upload the related code as attachment?

**Comment by Bolli84** [comment]
I uploaded the full file, since it was hard to remove some of the unneeded lines. But i suppose they might be needed.

The attached file contains everything now.
[rainloop (18).docx](https://github.com/the-djmaze/snappymail/files/9886558/rainloop.18.docx)

**Comment by the-djmaze** [comment]
Thanks. I've looked at it and it can't be used.
That doesn't mean that it worthless because there are some good ideas in there to  write and extend/improve the current Nextcloud integration.

**Comment by Bolli84** [comment]
All right. I created and used it in Rainloop and it was pretty useful there.

**Comment by the-djmaze** [comment]
Oh yes, it works in RainLoop.

However it relies on jQuery and SnappyMail doesn't.
Also Nextcloud is slowly abandoning jQuery.

Secondly your codes requires iframe mode but SnappyMail can be run without iframe to be better integrated.

So i will use your usefull code as reference to built similar features.
