### ISSUE TITLE
Improve performance of snappy?

### ISSUE THREAD

**Issue by the-djmaze** [the-djmaze/snappymail#593]
@brendan-pike

Is there anything I can do to improve performance of snappy on nextcloud? It's better than nextcloud mail but still takes 12seconds first load snapppy, then 2.7s to load each new email.  I'm wondering if there is a mail inbox pre-fetch function so it displays instantly?

_Originally posted by @brendan-pike in https://github.com/the-djmaze/snappymail/issues/569#issuecomment-1294311272_

# Solution
1. Go to Admin -> Config
2. Find `use_list_status` in the `imap` section
3. Turn it off
4. Hit the save button at the bottom

## Explanation
RFC 5819 LIST-STATUS is a way to return a lot of info instantly from the IMAP server.
This way SnappyMail only has to do 1 request to the IMAP server to fetch all required information of all folders.
When the IMAP server is slow (for whatever reason) this kind of request can take a very long time.
With the above setting you disable the feature and SnappyMail has to do several requests on the background (depends on on the amount of folders).

Still slow? Check your IMAP server, it is slow for a reason and SnappyMail can't do much else.

**Comment by brendan-pike** [comment]
Thank you for a great response. I tried disabling use_list_status and it had no effect on individual mail load times.  I guess I am hoping for some sort of pre-fetch cronjob / cache combo.   I assume there is no caching at all since there is no time reduction in loading the same  message twice.  

If there was a caching system that was even limited to keeping the inbox that would be a great.  For our implementation we actually use snappy across multiple staff accessing the same email account. So if a cache could be universal across users that would be even better.

**Comment by the-djmaze** [comment]
There was a prefetch/cache but i removed it.
It was limited to the first 20 messages.

If opening a message takes longer then 300ms, you should investigate your mailserver.
Somehow that is very slow.

**Comment by brendan-pike** [comment]
20 messages would be useful :)  In any case I use fastmail.com which are pretty reputable, but I'll try and work out how to investigate.  Cheers

**Comment by the-djmaze** [comment]
* Turn on the debug mode
* Open SnappyMail
* Open a message
* Turn off the debug mode

Open the `_data_/_default_/logs/*.txt` and see all info.
In there are things like (filtered):
```
IMAP[INFO]: Start connection to "tcp://localhost:143"
IMAP[DEBUG]: 0.0006101131439209 (raw connection)
IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
IMAP[DEBUG]: 0.0021920204162598 (*)
IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN Base64==\r\n
IMAP[DEBUG]: 0.3008439540863 (TAG1)
IMAP[INFO]: > TAG2 APPEND "Sent" (\Seen) {731}\r\n
IMAP[DEBUG]: 0.0012345123451472167969 (TAG2)
IMAP[INFO]: > TAG3 LOGOUT\r\n
IMAP[DEBUG]: 0.00034093856811523 (TAG3)
IMAP[INFO]: Disconnected from "tcp://localhost:143" (success)
IMAP[DEBUG]: 0.67747116088867 (net session)

IMAP[INFO]: Start connection to "tcp://localhost:143"
IMAP[DEBUG]: 0.00046396255493164 (raw connection)
IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
IMAP[DEBUG]: 0.0017571449279785 (*)
IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN Base64==\r\n
IMAP[DEBUG]: 0.27842593193054 (TAG1)
IMAP[INFO]: > TAG2 STATUS "Drafts" (MESSAGES UNSEEN UIDNEXT UIDVALIDITY HIGHESTMODSEQ)\r\n
IMAP[DEBUG]: 0.00069999694824219 (TAG2)
IMAP[INFO]: > TAG3 LOGOUT\r\n
IMAP[DEBUG]: 0.00023889541625977 (TAG3)
IMAP[INFO]: Disconnected from "tcp://localhost:143" (success)
IMAP[DEBUG]: 0.28226494789123454 (net session)
```

You can see how much time the connection takes and each "TAG" command.

**Comment by brendan-pike** [comment]
Thanks! I've done that, is it safe to paste here or does it contain some senstive information?

**Comment by the-djmaze** [comment]
It indeed shows 2.5 seconds for your connection with fastmail.
```
Connect (success)
0.46138978004456 (raw connection)

IMAP[INFO]: < * OK IMAP4 ready\r\n
IMAP[DEBUG]: 0.91648292541504 (*)

IMAP[DEBUG]: 0.22771215438843 (TAG1)
IMAP[DEBUG]: 0.24178194999695 (TAG2)
IMAP[DEBUG]: 0.2290461063385 (TAG3)
IMAP[DEBUG]: 0.22930598258972 (TAG4)
IMAP[DEBUG]: 0.45552897453308 (TAG5)
IMAP[DEBUG]: 0.22764611244202 (TAG6)

IMAP[INFO]: Disconnected from "ssl://imap.fastmail.com:993" (success)
IMAP[DEBUG]: 2.5449090003967 (net session)
```

When i test from SnappyMail server
```
IMAP[INFO]: Start connection to "ssl://imap.fastmail.com:993"
IMAP[INFO]: Connect (success)
IMAP[DEBUG]: 0.16720795631409 (raw connection)
IMAP[DEBUG]: 0.37014412879944 (*)
```

As you can see, setting up connection to fastmail costs me 0.3 seconds (Gmail took me 0.03 seconds).
You on the other hand, a connection to fastmail already takes 0.9 seconds!

Therefore it is clear that the location of your SnappyMail instance has serious issues to connect with fastmail.

To know more, you should investigate the issue like:
* test with other imap servers (gmail for example)
* test with local imap server (if available)
* ping fastmail.com
* your server setup (firewall, location, routing, etc.)

Fastmail is 10 times slower then Gmail (although 0.3 vs 0.03 is hardly noticeable).
And your server is 3 times slower then mine.

**Comment by brendan-pike** [comment]
Thank you, after testing with gmail its actually worse, the raw ping is better, ie. gmail 93ms where as fastmail is 227ms so confused as to they the process of reading an email is overall worse.  So it wouldn't appear that the network is not the main underlying issue?  I notice on my gmail that I ended up with TAG7 (I assume this means 7 imap interactions, and fastmail only had TAG6, where as your superfast example only had 3.  What determines how many fetches are occurring?

Lastly, would you consider re-adding the prefetch/cache, this would make a daily use feel so much better for users. 99% of the time they are only interacting with recent arrivals in the inbox.

```
[2022-11-03 01:13:34.779][a9abb4b6] IMAP[INFO]: Start connection to "ssl://imap.gmail.com:993"
[2022-11-03 01:13:34.970][a9abb4b6] IMAP[INFO]: Connect (success)
[2022-11-03 01:13:34.971][a9abb4b6] IMAP[DEBUG]: 0.191899061203 (raw connection)
[2022-11-03 01:13:35.264][a9abb4b6] IMAP[DEBUG]: 0.48540782928467 (*)
[2022-11-03 01:13:35.556][a9abb4b6] IMAP[DEBUG]: 0.29201483726501 (TAG1)
[2022-11-03 01:13:36.687][a9abb4b6] IMAP[DEBUG]: 1.1294450759888 (TAG2)
[2022-11-03 01:13:37.080][a9abb4b6] IMAP[DEBUG]: 0.39305400848389 (TAG3)
[2022-11-03 01:13:37.490][a9abb4b6] IMAP[DEBUG]: 0.40868592262268 (TAG4)
[2022-11-03 01:13:37.894][a9abb4b6] IMAP[DEBUG]: 0.40273904800415 (TAG5)
[2022-11-03 01:13:38.321][a9abb4b6] IMAP[DEBUG]: 0.42534494400024 (TAG6)
[2022-11-03 01:13:38.719][a9abb4b6] IMAP[DEBUG]: 0.39232897758484 (TAG7)
[2022-11-03 01:13:38.719][a9abb4b6] IMAP[DEBUG]: 3.9406950473785 (net session)
```

**Comment by the-djmaze** [comment]
> Lastly, would you consider re-adding the prefetch/cache, this would make a daily use feel so much better for users.

We might could add it, but there are several things in play here:
1. prefetch drains your mobile 4G/5G data
2. Which one to prefetch? The `unread` or the `read` or both? What would a user open?
3. Should it prefetch every mailbox or only the INBOX? But what if new arrives in a different mailbox and user reads them?
4. etc. etc.

That's why i removed it, because the `hit` and `miss` of cache is like Russian roulette.

I know it sucks, but somehow your server is on a terrible location with terrible connection speeds, and i can't solve that.

Other approach is like RoundCube and Nextcloud Mail to store all e-mails in a database.
But you've noticed how that worked out ;)

There is also another approach and @yeupou has a good solution.
He is using imap synchronization where a copy of IMAP is stored locally on the server that runs SnappyMail.
Because he is using tags/labels he found out his previous solutions failed and was on a hunt for a better approach.
He is probably still using https://guilhem.org/interimap/
Discussed here: https://github.com/the-djmaze/snappymail/issues/419#issuecomment-1142682516

**Comment by brendan-pike** [comment]
Thanks again, still chipping away at this and mostly trying to get my head around it.  I've contacted fastmail support, 10 days later they esculate to tier 3 and say all is well here and ask pointless questions.

I agree pre-fetch has hairs on it, mostly though its just new arrivals in the inbox is where people spend 90% of their focus.

The imap synchronization is certainly a solution, I'm not overly keen to add new layers really but its on the table.

Can you help me understand in the debug timing what is that first (*) one, what is happening there?
```
[2022-11-10 00:39:41.193][f4db4755] IMAP[DEBUG]: 0.45807504653931 (raw connection)
[2022-11-10 00:39:41.652][f4db4755] IMAP[DEBUG]: 0.91719102859497 (*)
[2022-11-10 00:39:41.881][f4db4755] IMAP[DEBUG]: 0.22800016403198 (TAG1)
[2022-11-10 00:39:42.115][f4db4755] IMAP[DEBUG]: 0.23327302932739 (TAG2)
[2022-11-10 00:39:42.348][f4db4755] IMAP[DEBUG]: 0.23053789138794 (TAG3)
[2022-11-10 00:39:42.578][f4db4755] IMAP[DEBUG]: 0.22894811630249 (TAG4)
[2022-11-10 00:39:43.034][f4db4755] IMAP[DEBUG]: 0.45506119728088 (TAG5)
[2022-11-10 00:39:43.270][f4db4755] IMAP[DEBUG]: 0.22762203216553 (TAG6)
[2022-11-10 00:39:43.270][f4db4755] IMAP[DEBUG]: 2.5345678329468 (net session)
[2022-11-10 00:39:43.270][f4db4755] [INFO]: Memory peak usage: 10MB
[2022-11-10 00:39:43.270][f4db4755] [INFO]: Time delta: 2.6526951789856
```
Given a ping to imap.fastmail.com is 225ms I'm wondering that is happening that takes 910ms.

**Comment by the-djmaze** [comment]
When the connection is made, it will receive "welcome" dat with information about the capabilities of the imap server.

The * indicates the data is received.
