### ISSUE TITLE
[Nextcloud] SnappyMail 2.19.4 general error

### ISSUE THREAD

**Issue by nextgen-networks** [the-djmaze/snappymail#595]
**Describe the bug**
SnappyMail can't be used since update 2.19.4.
Was working with 2.19.2

**To Reproduce**
1. Klick on SnappyMail Icon
2. Get Error as in Screenshot
![2022-10-28 SnappyMail Error](https://user-images.githubusercontent.com/21206978/198539671-a95d1aae-1e15-4b89-901d-797589c6e5ef.png)

**Expected behavior**
SnappyMail should work with already provided credentials.

**Please complete the following information:**
- Browser: Edge 106.0.1370.52
- PHP version: 8.1
- SnappyMail Version: 2.19.4

**Additional context**
[2.19.4](https://snappymail.eu/repository/nextcloud/snappymail-2.19.4-nextcloud.tar.gz)

**Comment by nextgen-networks** [comment]
**Update/Workaround:**
Change SnappyMail Plugin Settings to any value in Nextcloud admin settings, save them and revert back to previous settings and save.
Right after that action SnappyMail might work again.

**Comment by blackwhitebear8** [comment]
can confirm changing something and saving indeed fixes this weird issue
