### ISSUE TITLE
File or folder name displays incorrectlly when the name contains non-ascii text

### ISSUE THREAD

**Issue by mayswind** [the-djmaze/snappymail#597]
**Describe the bug**
File or folder name in the select nextcloud files dialog displays incorrectlly when the name contains non-ascii text or name contains symbols

**To Reproduce**
1. In nextcloud files, create a file / folder with non-ascii file name or file name contains some symbol (see the below screenshot)
1. In snappy mail, Click 'New message' button
2. Then, click 'Attch Nextcloud files' and find the file or folder in step one (see the below screenshot)

**Expected behavior**
The file or folder name should display correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/2211648/198582273-a6d3754f-b7c6-4334-a21f-fcb5df675de8.png)
(the folder and 4th file contain Chinese name, the 1st/2nd/3rd file name contains symbols.

![image](https://user-images.githubusercontent.com/2211648/198583413-e2c10a03-9401-4efd-a060-9223a325672c.png)
(the file / folder name displays incorrectlly and the nextcloud webdav response data)

**Please complete the following information:**
- Browser: Edge 106.0.1370.52 
- IMAP daemon: dovecot
- PHP version: 8.1.11
- SnappyMail Version: 2.19.4

**Comment by the-djmaze** [comment]
Thanks!
