### ISSUE TITLE
ERROR: Undefined class constant 'AUTOLOGOUT' on login

### ISSUE THREAD

**Issue by Luticus** [the-djmaze/snappymail#599]
**Describe the bug**
Since last update when I go to the snappymail app I get an error "ERROR: Undefined class constant 'AUTOLOGOUT'" in a pop up and then it sits there spinning forever, never completing a login.

**To Reproduce**
1. update to new version
2. attempt auto login
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/7807109/198712313-0026690c-3304-4d73-a9e3-31287a3da5d4.png)

**Please complete the following information:**
- Browser: firefox 100
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.19.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by Disco1** [comment]
Any idea how to downgrade? I've got the same problem and can't access my email now.

**Comment by Luticus** [comment]
Interestingly I managed to get further by clearing my browser cache very thoroughly and restart the browser, now i don't see the error but when I try to log in it says "can't connect to server".

@Disco1 If you want to downgrade, old version can be found here:  https://apps.nextcloud.com/apps/snappymail/releases?platform=25#25. You should disable and uninstall the new version, then from your cloud server wget the tarball, extract to .../nextcloud/apps (wherever your nextcloud is, in my case /var/www/nextcloud/apps) and then back in your NC interface under apps you should be able to enable the old version and be careful to tell it not to update. Also don't forget to doublecheck ownership and permissions over the snappymail directory you extracted, in needs to be owned by the apache user, on Debian that's "www-data", if RHEL based "apache".

**Comment by nextgen-networks** [comment]
I sssume this is a double of https://github.com/the-djmaze/snappymail/issues/595 right?
@the-djmaze should https://github.com/the-djmaze/snappymail/issues/595 then also marked as closed?

**Comment by Luticus** [comment]
Just installed new version, snappymail can't log in still, however if i disable snappy and enable the old rainloop it does log in.
