### ISSUE TITLE
Admin login does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#6]
**RainLoop version, browser, OS:**
the-djmaze7, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
URL: www.url.com/mail?admin and login with username "admin" and password "12345" should work for a fresh installation. But instead nothing happened.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
see attachment
[log.txt](https://github.com/the-djmaze/rainloop-webmail/files/5263342/log.txt)

**Comment by the-djmaze** [comment]
When i remove my data folder the default admin login still works.
Could you check your php error logs?

**Comment by phsc84** [comment]
This issue only occurs after a fresh installation. For an existing installation, that has been upgraded to djmaze7, the admin login works as expected.
I will test again later and provide you the PHP error logs.

**Comment by phsc84** [comment]
Hm, on my office computer it works fine, but not on my private computer. I will test again later.

**Comment by the-djmaze** [comment]
Great! I will wait for your response.
At least i've fixed all the others you thankfully reported. 😀

**Comment by phsc84** [comment]
This must be kind of a security feature in Chrome. The Chrome on my private computer always returns me to the url "www.url.com/mail?admin".
It is interesting, that in the private mode it works. So therefore it is not an application problem. And because the admin UI is used rarely, this is ok. You should just mention this in the installation instructions.
