### ISSUE TITLE
Disabled filters are not displayed unchecked

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#60]
**Describe the bug**
When I disable a filter by unchecking the box before the filter name, save it on server.
Then reload the page, the filter is marked checked as it is activated.
On the Sieve server, the rule is correctely disabled 
`/* @Filter is disabled`

**Expected behavior**
On reload the filter must be unchecked

**Desktop (please complete the following information):**
 - Browser Firefox 78.8
 - SnappyMail Version  2.3.5

**Comment by the-djmaze** [comment]
Thanks for testing!
