### ISSUE TITLE
Update 2.19.6 Exception: Undefined constant "OCA\SnappyMail\Util\RAINLOOP_APP_LIBRARIES_PATH" in file '..../apps/snappymail/lib/Util/SnappyMailHelper.php' line 16

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#601]
After update to 2.19.6 I get an "Internal Server Error" onthe app-page as well as on the settings-page. 

"Exception: Undefined constant "OCA\SnappyMail\Util\RAINLOOP_APP_LIBRARIES_PATH" in file '......./apps/snappymail/lib/Util/SnappyMailHelper.php' line 16"

With version 2.19.5 it was no issue.

**Comment by stuffsch** [comment]
Same here.

Nextcloud Version: 25
Snappymail: 2.19.6
PHP Version: 8.0.25

`{"reqId":"3mRKb5vVyQ2uWItDNvjw","level":3,"time":"2022-10-31T17:01:02+00:00","remoteAddr":"78.54.52.198","user":"stuffsch","app":"index","method":"GET","url":"/index.php/apps/snappymail/","message":"Undefined constant \"OCA\\SnappyMail\\Util\\RAINLOOP_APP_LIBRARIES_PATH\" in file '/var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php' line 16","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.0.18","exception":{"Exception":"Exception","Message":"Undefined constant \"OCA\\SnappyMail\\Util\\RAINLOOP_APP_LIBRARIES_PATH\" in file '/var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php' line 16","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Undefined constant \"OCA\\SnappyMail\\Util\\RAINLOOP_APP_LIBRARIES_PATH\"","Code":0,"Trace":[{"function":"OCA\\SnappyMail\\Util\\{closure}","class":"OCA\\SnappyMail\\Util\\SnappyMailHelper","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/snappymail/app/snappymail/v/2.19.6/include.php","line":163,"function":"class_exists"},{"file":"/var/www/nextcloud/apps/snappymail/app/index.php","line":11,"args":["/var/www/nextcloud/apps/snappymail/app/snappymail/v/2.19.6/include.php"],"function":"include"},{"file":"/var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php","line":25,"args":["/var/www/nextcloud/apps/snappymail/app/index.php"],"function":"require_once"},{"file":"/var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php","line":81,"function":"loadApp","class":"OCA\\SnappyMail\\Util\\SnappyMailHelper","type":"::"},{"file":"/var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php","line":30,"function":"startApp","class":"OCA\\SnappyMail\\Util\\SnappyMailHelper","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\SnappyMail\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php","Line":16},"CustomMessage":"--"},"id":"63600f3a15534"}`

**Comment by spiezmaestro** [comment]
same here. 2.19.5 on 25.0.0 ok, 2.19.6 give the error

**Comment by stuffsch** [comment]
I have just commented these lines (14-26)  in /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php out and it seems to be working for now:

`                // Nextcloud the default spl_autoload_register() not working
                /*\spl_autoload_register(function($sClassName){
                        $file = RAINLOOP_APP_LIBRARIES_PATH . \strtolower(\strtr($sClassName, '\\', DIRECTORY_SEPARATOR)) . '.php';
                        if (\is_file($file)) {
                                include_once $file;
                        }
                });*/
`

**Comment by the-djmaze** [comment]
I've renamed a few things to prevent conflicts with RainLoop as some Nextcloud users load both mail apps.
Somehow i missed this change and fixed it.

New version is up at Nextcloud but it can take a few hours before you can update.

**Comment by spiezmaestro** [comment]
After manuel edit app is working fine again. Thx for the quick solution
