### ISSUE TITLE
After updating [105] Missing version directory

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#603]
Updated Snappymail on nextcloud:

going to Settings >> Additional Settings:

[105] Missing version directory

Tried to remove it and installed it again, same happens.

Other relevant information: Rainloop is installed in nextcloud.

**Comment by the-djmaze** [comment]
There must be something wrong with PHP Opcache.
Restart/reload PHP.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/FAQ#105-missing-snappymailvxxxincludephp

**Comment by the-djmaze** [comment]
Normally not, for example i have PHP-FPM with OPcache which doesn't need to.

But certain setups might need to.
And v2.19.7 now does call opcache_invalidate() for that specific file, but i have no idea what the impact will be and if it works properly.

**Comment by elhananjair** [comment]
other apps are not requiring that only snappymail does, what if I delete everything related to snappymail and delete the snappymail app and reinstall it, does that may help?

**Comment by the-djmaze** [comment]
No idea, you should test that with next release then.
