### ISSUE TITLE
Return type of MailSo\Base\StreamFilters\LineEndings::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/html/custom_apps/snappymail/app/snappymail/v/2.19.7/app/libraries/MailSo/Base/StreamFilters/LineEndings.php#7

### ISSUE THREAD

**Issue by jiriks74** [the-djmaze/snappymail#610]
**Describe the bug**

I cannot send emails from specific domain even after setting the smtp correctly. This domain works with other clients.

**To Reproduce**

1. SnappyMail admin panel
2. Add new domain `atlas.cz`
3. Set imap to use `imap.atlas.cz`, set encryption to ssl, use default port
4. Set smtp to `smtp.centrum.cz` (centrum.cz owns atlas.cz where the email is), use STARTTLS and default port (or ssl and default port)
  - Do not use short login for this one
5. Log into the email from `atlas.cz`
6. Try to send a message to anyone
7. Get `Message could not be sent` error

**Expected behavior**

Message sent

**Screenshots**

<details>

<summary>Screenshot (in Czech, sorry)</summary>

![image](https://user-images.githubusercontent.com/54378412/199388914-fe4774e1-25d0-4f6e-88b2-017ef283b170.png)

</details>

**Please complete the following information:**

- Browser: Firefox 104.0.2
- IMAP daemon: idk
- PHP version: 8.1.11
- SnappyMail Version: 2.19.7

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
<details>

<summary>Error from Nextcloud logs</summary>

```
Return type of MailSo\Base\StreamFilters\LineEndings::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/html/custom_apps/snappymail/app/snappymail/v/2.19.7/app/libraries/MailSo/Base/StreamFilters/LineEndings.php#7
```

</details>

**Comment by jiriks74** [comment]
How do i get this fix I I don't want to wait for the next release on Nextcloud? I cannot see any instructions on how to build the plugin...

**Comment by the-djmaze** [comment]
Either:
1. remove snappymail and install again (i've updated the release)
2. Or modify file `apps/snappymail/app/snappymail/v/2.19.7/app/libraries/MailSo/Base/StreamFilters/LineEndings.php`

**Comment by jiriks74** [comment]
@the-djmaze 

Sorry, but could you reopen this again, please?

I haven't sent any emails from that email for some time, but today I tried and it didn't send emails again. I'll try to get some logs once I'll be able to.

**Comment by the-djmaze** [comment]
Then please open a new issue with the exact error message.
