### ISSUE TITLE
Snappy Mail Credentials not being kept

### ISSUE THREAD

**Issue by sgutermann** [the-djmaze/snappymail#613]
**Describe the bug**
After Users enters his mail credentials and check the box "keep my credentaials" they are not kept but gone by the next login.

**To Reproduce**
setup Fresh Nextcloud. Fresh SnappyMail v.2.19.6 or 2.19.7.

Get everything konfigured.

Get User to add his mail credentials and check the "keep credentials" checkbox.

**Expected behavior**
Credentials are kept and do not need to be entered on next log in by user.

- SnappyMail Version: 2.19.6, 2.19.7

**Comment by the-djmaze** [comment]
Try with v2.20
