### ISSUE TITLE
Standard scrollbars are displayed

### ISSUE THREAD

**Issue by gnilebein** [the-djmaze/snappymail#615]
**Describe the bug**
When the folder list in Rainloop is larger than the screen, small scrollbars are displayed. However, in Snappymail, the standard scrollbars are displayed.

**To Reproduce**
Create more directories than will fit on the screen. Once the scrollbars are displayed, the default scrollbars are displayed.

**Expected behavior**
Small scrollbars should be displayed like in Rainloop.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/2871059/199750768-e3d0cdcc-0cb9-4a76-b75a-26c6ba222a6b.png)

**Please complete the following information:**
- Browser: Chrome Version 106.0.5249.119 (Offizieller Build) (64-Bit)
- PHP version: 8.0
- SnappyMail Version: 2.19.7

**Comment by the-djmaze** [comment]
Did you try the embed mode?

**Comment by gnilebein** [comment]
> Did you try the embed mode?

In embed mode it looks better. In general fonts etc. look better.
