### ISSUE TITLE
unable to start first time in admin mode

### ISSUE THREAD

**Issue by rsuinux** [the-djmaze/snappymail#618]
Hello;
I just installed Snappymail, replacing Rainloop.
PHP works, Nginx too. Nginx's configuration has been changed for Snappymail.
At the first connection to the server I have this error:
Error: Failed loading /snappymail/2.19.4/static/js/min/libs.min.js
The directories are of course, accessible. UNIX rights are correct.
The Firefox console indicates me:
The resource at the address "https: // <my-server> /snappymail/v/2.19.4/static/css/app.min.css" was blocked due to a mime type ("text/html ») Incorrect (X-Content-Type-Options: Nosniff).
Same error for this file: snapymail/v/2.19.4/static/js/min/libs.min.js »
and that too: snapymail/v/2.19.4/static/css/app.min.css

Is this a bad configuration on my part?

Thank you for your help.
Rémi.

- Browser: firefox  102.3.0esr (64 bits) linux
- PHP version: 7.4
- SnappyMail Version: latest version, 2.19.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Open de browser debug/developer console.
Open the Network tab.
Find the request and click on it.
Then the response sourve can be viewed and analyzed.

Depending on the content we can figure out the problem.

**Comment by rsuinux** [comment]
Thank's for your reply.
In firefox, with mode debug, here are the network console traces:

```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à data: (« default-src »).
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). moz-extension:87:33
La ressource à l’adresse « https://imap.suinot.org/snappymail/v/2.19.4/static/css/app.min.css » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
imap.suinot.org
La ressource à l’adresse « https://imap.suinot.org/snappymail/v/2.19.4/static/js/min/libs.min.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
my-imap-server
Uncaught (in promise) Error: Failed loading /snappymail/v/2.19.4/static/js/min/libs.min.js
    onerror imap/:9
    i https://imap/:9
    i https://imap/:9
    initData https://imap/:9
    <anonymous> https://my-imap-server/?/AppData/0/6020812806715957/:1
imap.suinot.org:9:382
La ressource à l’adresse « https://my-imap-server/snappymail/v/2.19.4/static/css/app.min.css » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
```

are the only messages (firefox side)

**Comment by the-djmaze** [comment]
That's the Console tab, you need to check the Network tab

**Comment by the-djmaze** [comment]
Here's a screenshot of where to look:
![afbeelding](https://user-images.githubusercontent.com/3752035/200146727-4e5b39d8-051f-40cd-8800-46b9696b91d2.png)

**Comment by rsuinux** [comment]
Ok, with the network console, the result is below.
Also, for security, I disabled all firefox plugins.
I really think I forgot something, but what...

![snappymail](https://user-images.githubusercontent.com/6034197/200194872-9bfe8f3f-0117-4fcc-b762-2d19b9f95fea.png)

**Comment by rsuinux** [comment]
Precision: the working directory:

```
/home/www-data # ls -l /var/www/snappymail/snappymail/v/2.19.4/static/
total 60
-rw-r--r--    1 www-data www-data      3373 Oct 28 01:37 android-icon.png
-rw-r--r--    1 www-data www-data       992 Oct 28 01:37 apple-touch-icon.png
drwxr-xr-x    4 www-data www-data      4096 Oct 31 09:33 css
-rw-r--r--    1 www-data www-data      1150 Oct 28 01:37 favicon-light.ico
-rw-r--r--    1 www-data www-data       866 Oct 28 01:37 favicon-light.png
-rw-r--r--    1 www-data www-data       335 Oct 28 01:37 favicon.ico
-rw-r--r--    1 www-data www-data       992 Oct 28 01:37 favicon.png
drwxr-xr-x    3 www-data www-data      4096 Oct 31 09:33 js
-rw-r--r--    1 www-data www-data      9552 Oct 28 01:37 logo-512.png
-rw-r--r--    1 www-data www-data      6163 Oct 28 01:37 logo-text.png
-rw-r--r--    1 www-data www-data       537 Oct 28 01:37 manifest.json
drwxr-xr-x    2 www-data www-data      4096 Oct 31 09:33 sounds

```

**Comment by the-djmaze** [comment]
> ![snappymail](https://user-images.githubusercontent.com/6034197/200194872-9bfe8f3f-0117-4fcc-b762-2d19b9f95fea.png)

Click in that image on the `libs.min.js` then on the right the response is shown (like in mine screenshot)
