### ISSUE TITLE
Undefined variable $sEmail - FYI

### ISSUE THREAD

**Issue by jcb-tn** [the-djmaze/snappymail#619]
**SnappyMail version, browser, browser version:**
Nextcloud app 2.20.0

This message is now coming up in Nextcloud log after update to version 2.20.0

Undefined variable $sEmail at /local/app/nextcloud/data/appdata_snappymail/_data_/_default_/plugins/nextcloud/index.php#186

**Comment by the-djmaze** [comment]
Yes is fixed in the plugin but i haven't released a new version of the plugin yet.

https://github.com/the-djmaze/snappymail/commit/9f41f18d435e6996c9ec9e834762fddb983542c0
