### ISSUE TITLE
tooltips for all icons

### ISSUE THREAD

**Issue by ITwrx** [the-djmaze/snappymail#62]
**Is your feature request related to a problem? Please describe.**

if you haven't used rainloop or snappymail before it is not always clear what these icons will do. People don't want to guess what will happen with their emails if they click on some mysterious icon. I'm sure this is a legacy design decision. Would be nice to address it, imo. I haven't looked at the src yet, but feel free to indicate if you would accept a PR for this. I'm not using any webmail yet, but i'm considering it, and snappy mail.

**Describe the solution you'd like**

add tooltips to all the icons, so people can know in advance what will happen if they click.

**Describe alternatives you've considered**

icons could have text with them, but that would take up more room. i'm not necessarily opposed to that either. In general, i'm not always in favor of cleanliness _at all costs_. Some middle ground is many times preferable to me.

**Comment by the-djmaze** [comment]
Tooltips work on screens with a mouse.
Problem is that they don't work on devices using touch/pen/pointer.

There are two solutions:
* dropdown menu has same icons as the large buttons
* help screen a new tab to describe the icons

**Comment by ervee** [comment]
Drop-down already has the icons. Of you already fixed this :)
![Screenshot_20210321-165328~2](https://user-images.githubusercontent.com/4435930/111911724-fd8b6380-8a66-11eb-812d-4d33e252bad5.png)

Could not hurt to include in help. Although (on my device) this screen doesn't scale very well.

![Screenshot_20210321-165431~2](https://user-images.githubusercontent.com/4435930/111911755-1c89f580-8a67-11eb-99a7-3677b78f189c.png)

**Comment by the-djmaze** [comment]
I've made some improvements.
Go to https://snappymail.eu/demo/ and check the help screen.

**Comment by ITwrx** [comment]
@the-djmaze that's cool. i guess you will add a key for all icons? going to the help is better than nothing, but if it were me i would wrap the icon images in a span and give it a title so it acts as a tooltip when you hover over the image. Then do whatever works best for mobile.

**Comment by the-djmaze** [comment]
> but if it were me i would wrap the icon images in a span and give it a title so it acts as a tooltip.

Actually that is already in there, and a fancy CSS version using `data-rainloopErrorTip=""` HTML attribute.
If an icon is missing a title="", can you tell me which?

**Comment by ITwrx** [comment]
My firefox has some issue where showing titles gets broken and the only way to fix it is to restart the browser. I forgot about that and also forgot to inspect the source code! 

But now, when actually inspecting the source, i see that all the top left icons have a title on the a element (great!), but the bottom left (looks like settings, some folder and expansion icon) and the top right (user icon) don't have titles.

**Comment by ervee** [comment]
> 
> 
> I've made some improvements.
> Go to https://snappymail.eu/demo/ and check the help screen.

I noticed when viewing a message (no split viewing mode), then pulling up Help (F1) and then closing it (X or ESC) renders all other hotkeys unusable. Like ESC for closing a message or CTRL-Up/Down.

**Comment by the-djmaze** [comment]
@ervee please open new bug report

**Comment by ervee** [comment]
> @ervee please open new bug report

Confirmed fixed. Thank you!
