### ISSUE TITLE
Nextcloud theme is dark by defualt while the user theme is Light

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#620]
**Describe the bug**
I have a light theme applied on nextcloud, and I selected Nextcloud theme snappymail setting. By default, it is dark, but currently I am using Light theme therefore it doesn't look nice. 

**To Reproduce**
1. Go to setting
2. Click on themes
3. Select Nextcloud from the theme list
4. The dark background color appears

**Expected behavior**
Should be the same with Nextcloud applied theme

**Screenshots**
![Screenshot from 2022-11-03 23-28-38](https://user-images.githubusercontent.com/69236638/199828650-70a3c0de-8154-45ff-b148-5deb47f0f6cd.png)
**Please complete the following information:**
- Browser: Firefox 106
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.25
- SnappyMail Version:  2.20

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Are you using SnappyMail 2.20?

**Comment by the-djmaze** [comment]
SnappyMail 2.20 uses var() settings in CSS of your theme.
So your theme might have issues.

Try Nextcloud default or Breeze Dark.

Also report which Nextcloud theme you are using.

**Comment by elhananjair** [comment]
@the-djmaze as you might see in the pic am using Nextcloud theme on snappy mail and the Light theme on Nextcloud.

**Comment by the-djmaze** [comment]
Right. Where do you set the default to Dark?
Because i can't find that option in my Nextcloud

**Comment by the-djmaze** [comment]
Did you try the embed mode?

**Comment by the-djmaze** [comment]
Ah, you are using Nextcloud 25.
Because everything works fine in Nextcloud 24.

So i went and installed Nextcloud 25 and i noticed that the theme of NC25 is horrible.

You should report to Nextcloud that there is something wrong with the `:root` variables.

Because SnappyMail just maps its own variables to that of Nextcloud. Like:
```css
:root {
	--main-bg-color: var(--color-main-background)
}
```
But `--color-main-background` is black, not white in NC25

**Comment by the-djmaze** [comment]
Fixed in v2.20.1
