### ISSUE TITLE
Pictures are not loading on email signature

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#621]
**Describe the bug**
I just used some publicly available pic on my signature and its broken and is not showing. 

**To Reproduce**
1. Go to setting
2. Click on accounts
3. Scroll down to identities
4. Select the default one and try to add some publicly available pictures, the picture will not be shown

**Expected behavior**
The picture should be shown.
**NOTE**: It was fine on previous release of snappymail I just found out now that it is not working

**Screenshots**
![image](https://user-images.githubusercontent.com/69236638/199831046-0969d2aa-44f6-4104-870c-a36f7827e622.png)

**Please complete the following information:**
- Browser: Firefox 106
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.25
- SnappyMail Version: 2.20.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
![image](https://user-images.githubusercontent.com/69236638/199831238-35b09d0b-8902-455b-ac03-546d7a8ca329.png)

**Additional context**

**Comment by the-djmaze** [comment]
This is normal behaviour for privacy.
You have 2 options to make it less secure:
1. Enable the proxy
2. Loosen the CSP settings

Info can be found in the wiki

**Comment by the-djmaze** [comment]
Sorry, the wiki is missing specific issue.

1. Go to Admin -> Config
2, Find `content_security_policy`
3. Value `img-src https:`
4. Save

That allows remote images

**Comment by elhananjair** [comment]
> 

is it just `img-src https:` or something like` img-src https:https://i.imgur.com/E9K0IGf.png`

**Comment by the-djmaze** [comment]
Just `img-src https:` is sufficient to load images from any domain

**Comment by elhananjair** [comment]
@the-djmaze sorry to bother you again, but I did that and my logo is not showing up on my signature:
![image](https://user-images.githubusercontent.com/69236638/200128442-bdd00291-5e07-4384-b9db-310210ee929c.png)
---
![image](https://user-images.githubusercontent.com/69236638/200128472-feac65c2-e71c-49df-986b-f131beb480fe.png)

**Comment by elhananjair** [comment]
It worked now thank you so much.
