### ISSUE TITLE
PutinICS does is not working for all calendar events.

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#622]
Action: Calendar-Enty is sent to user by mail
Issue: Calendar is detected or sometimes not.

Console log:
Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at ?/Plugins/0/User/8308e293dc4cc8094705a127f5ae0ea9/:534:37

Refering to the following code:
`else if (line.startsWith('BEGIN:VEVENT')) {
										break;
									}
									line = line.match(/^([^:;]+)[:;](.+)$/);
									if (VALARM) {
										VALARM[line[1]] = line[2];
									} else {
										if (multiple.includes(line[1]) || 'X-' == line[1].slice(0,2)) {  ##ISSUE is marked here##
											VEVENT[line[1]] || (VEVENT[line[1]] = []);
											VEVENT[line[1]].push(line[2]);
										} else {
											VEVENT[line[1]] = line[2];
										}
									}
								} else if (line.startsWith('END:VEVENT')) {
									VEVENT = {};
								}`

Possible suspicious content might be the following, in which some "X-xxxx"Fields have no content behind the ":".

> X-MICROSOFT-CDO-APPT-SEQUENCE:0
> X-MICROSOFT-CDO-OWNERAPPTID:516077542
> X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
> X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
> X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
> X-MICROSOFT-CDO-IMPORTANCE:1
> X-MICROSOFT-CDO-INSTTYPE:0
> X-MICROSOFT-SKYPETEAMSMEETINGURL:
> X-MICROSOFT-SCHEDULINGSERVICEUPDATEURL:
> X-MICROSOFT-SKYPETEAMSPROPERTIES:
> X-MICROSOFT-ONLINEMEETINGCONFLINK:
> X-MICROSOFT-DONOTFORWARDMEETING:FALSE
> X-MICROSOFT-DISALLOW-COUNTER:FALSE
> X-MICROSOFT-LOCATIONS:[{"DisplayName":"WebEx/Teams"\,"LocationAnnotation":"
>  "\,"LocationUri":""\,"LocationStreet":""\,"LocationCity":""\,"LocationStat
>  e":""\,"LocationCountry":""\,"LocationPostalCode":""\,"LocationFullAddress
>  ":""}]

**Comment by the-djmaze** [comment]
Fixed in 2.20.1

**Comment by Bolli84** [comment]
Reopen with the following calendar:

> BEGIN:VCALENDAR
VERSION:2.0
PRODID:www.ccccc.dd
METHOD:PUBLISH
BEGIN:VEVENT
UID:20221112T093211-www.dddddddd.ed
ORGANIZER;CN=xxxxxx, xx<:MAILTO:info@cccccc
LOCATION:xxxxxx
SUMMARY:Reservierung
DESCRIPTION:Buchungs-Nr.: 1006341
 \nDatum / xxx: 13.11.2022 / 09:00
  \nloc: 12 4444444445
   \ngame 1: sadsadasdsa, w:y 
CLASS:PUBLIC
DTSTART:20221113T090000
DTEND:20221113T130000
DTSTAMP:20221112T093211
END:VEVENT
END:VCALENDAR
