### ISSUE TITLE
Snappymail 2.20.0 - Login: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by Gravity-87** [the-djmaze/snappymail#623]
**Describe the bug**
I upgraded Snappymail from v2.19.7 to v2.20.0. 
In v2.19.7 the login worked fine, in v2.20.0 it now fails. Message at login is:
"Authentification failed
Server-Message: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)"

**To Reproduce**
1. Call the login-page
2. Give in the login credentials
3. Click "Login"
4. Seeing the above error in a yellow text field above the username/password fields of the login page

**Expected behavior**
Functional login as is in v2.19.7

**Please complete the following information:**
- Browser: Firefox 106.2
- IMAP daemon: Dovecot
- PHP version: 7.3er branch (I think 7.3.31... PHP, which is delivered in default with Debian Buster/10)
- SnappyMail Version: 2.19.7 vs. 2.20.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
I have no concerning log-information from Nginx. In dovecot-log it seems, that it gets no valid login-credentials, so that the
authentification is directly closed: The log shows this event:
" dovecot: imap-login: Disconnected: Connection closed (no auth attempts in 1 secs): user=<> ...."

It's surprising that there is an authentification without problems in v2.19.7 and in the next version (2.20.0) the login is rejected.
Any hints, any ideas? Thx a lot!

**Comment by the-djmaze** [comment]
PHP 7.3 is End of life in 2021

Now i made some changes in the core code that crash in PHP 7.3 but i forgot to bump minimum version in setup.php.
https://github.com/the-djmaze/snappymail/commit/d3b65afb353e98fd754bddd9313295f3b9042cf3

Can you upgrade PHP to 7.4 or should i revert the changes?

**Comment by Gravity-87** [comment]
I'll try the upgrade to PHP 7.4! Thx for the info.

**Comment by Gravity-87** [comment]
PHP 7.4 did the trick. In my case the login now runs in correct way with Snappymail v.2.20.0 as it does with former v2.19.7.
