### ISSUE TITLE
Add more search operators (i.e. copy lots of Gmail ones)

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#625]
Like most people these days, I'm accustomed to be able to use all the [search operators available in Gmail](https://support.google.com/mail/answer/7190?hl=en).

I particularly miss:

```
has:attachment
- 
in:anywhere 
is:unread
is:read
size:
larger:
smaller:
older_than:
newer_than: 
OR
```

But I imagine others miss other Gmail search operators too, so the more of them you're able to implement, the better!

Roundcube already has [these search operators](https://docs.roundcube.net/doc/help/1.1/en_US/mail/searching.html):

    from:
    to:
    cc:
    bcc:
    subject:
    body:

And they are [implementing a bunch of the above in the forthcoming version 1.7](https://github.com/roundcube/roundcubemail/issues/8502#issuecomment-1166307808).

That's great for Roundcube users! But now I use SnappyMail, so now I'm asking for all the same search operators here too.

**Comment by the-djmaze** [comment]
I've added a few, `older_than` so you know how it works.
Now you can:
* older_than=1d
* older_than:1d

**Comment by TheNomad11** [comment]
Great! Thanks a lot @the-djmaze I am impressed by the progress, especially the Nextcloud app. Now Snappy Mail looks really good!! 

But one still can search one folder only. If you have many folders and you are as disorganized as I am and  don't remember where you put it, then you are in trouble!  Do you consider the option "search in all folders" or would it be too much work?

**Comment by the-djmaze** [comment]
Thanks.

To search all folders is an issue that popped up multiple times but SnappyMail can't by itself.

A good read canbbe found here: https://github.com/the-djmaze/snappymail/issues/154#issuecomment-999820594
