### ISSUE TITLE
After upgrade to 2.20.2 the app can't be started anymore

### ISSUE THREAD

**Issue by spiezmaestro** [the-djmaze/snappymail#628]
After upgrading from 2.20.0 to 2.20.2 I can't open the app in NC 25.0.1 anymore. Starting the app just hangs and finally the webserver is timing out.

The error message in nextcloud.log is (redacted):

{"reqId":"Y2ZeEIITA1ZX-IdNXVIuuQAAAAg","level":3,"time":"2022-11-05T13:58:57+01:00","remoteAddr":"192.168.x.x","user":"xxxx","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Undefined variable $container at /var/www/nextcloud/apps/snappymail/lib/AppInfo/Application.php#85","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.1.1","exception":{"Exception":"Error","Message":"**Undefined variable $container at /var/www/nextcloud/apps/snappymail/lib/AppInfo/Application.php#85**","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/snappymail/lib/AppInfo/Application.php","line":85,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":190,"function":"boot","class":"OCA\\SnappyMail\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":208,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":57,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6366679ebd3ba"}

**Please complete the following information:**
- Browser: tested Chrome and Firefox
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.1.7
- SnappyMail Version: 2.20.2

Thanks!

**Comment by the-djmaze** [comment]
Odd, because 2.20.2 doesn't use $container. It was fixed to use the Nextcloud 18+ $dispatcher

**Comment by spiezmaestro** [comment]
Can't replicate anymore. Will investigate further.

**Comment by spiezmaestro** [comment]
Can't really explain why those errors were written in the log, but they were. Anyway, it appeared in issue on my reverse proxy. After recycling that, the app can be started again. Sorry for the disturbance.

**Comment by the-djmaze** [comment]
Good you solved it 👍

**Comment by adnion** [comment]
I get the same error and can't solve it. How did spiezmaestro solve it?
> Error: Undefined variable: container at /data/nextcloud/apps/snappymail/lib/AppInfo/Application.php#85

and

> Exception: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::useStrictDynamic() in file '/data/nextcloud/apps/snappymail/lib/Controller/PageController.php' line 8

**Comment by spiezmaestro** [comment]
I restarted Nextcloud/Apache and Nginx reverse proxy. Afterwards it worked again for me.

**Comment by adnion** [comment]
Ok thank you, this doesn't work for me. I guess you didn't get the ContentSecurityPolicy error and the reason for my 2.20.2 not starting is different
