### ISSUE TITLE
QR Login support

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#63]
As we look to the future.
Many e-mail providers now support QR login on phones and pc.
This is something I think should be supported here.

**Comment by the-djmaze** [comment]
You can enable TOTP 2FA through admin to enable QR

**Comment by master3395** [comment]
I'm not talking about login on the website, i am talking about mobile devices and Windows desktop devices.
Such as Outlook.

**Comment by master3395** [comment]
![image](https://user-images.githubusercontent.com/4199669/111910959-ccf5fa80-8a63-11eb-87f4-ddd82bf48311.png)

**Comment by the-djmaze** [comment]
Then it's a no.
SnappyMail is not an email service, it is an email client.

**Comment by master3395** [comment]
I'm not talking about email service.
I use the snappymail as a way to read the e-mail.
And I use the outlook app to do the same using the same credentials.
But sadly I get an issue when logging it sometimes, and it would be easier to have a QR code to log into the mail using the same credentials as you use to log into an SMTP and or POP/IMAP

**Comment by the-djmaze** [comment]
SnappyMail relies on the credentials of the SMTP and IMAP servers.
This means that SnappyMail requires a login name and a password.

If you have a QR with credentials, then how the hell can a website scan that QR without a camera?

Yes, mobile phones have a camera. But scanning a QR in the browser is a terrible solution.
For example try to scan your QR at https://webqr.com/ with different phones and enter the hell of "which camera to use?".
