### ISSUE TITLE
CKeditor not working because of Content Security Policy directive

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#630]
When switching the editor to the extension "CKeditor", the editor changes visible, however it is not usable.

Snappymail-Version 2.20.2

Errors in Console:

> Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'nonce-FF4eFhJZGhNcy9LeHMxcnBzQ3F6TXZ3bUF3Q3ZPcy8vMGNlbUFHNEM1Yz06Q1hrcmJQRXBIYUtIa0tjWXhhellqb2Fkb0hSZ2lMMXBpWEZud0RMMlBxOD0=' blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

It that solvable in snappymail directly, or only in the complate NC instance?

**Comment by the-djmaze** [comment]
Same issue as  #573
It os the old CKEditor as used in RainLoop

Updating CKEditor to latest version hopefully solves it.

**Comment by the-djmaze** [comment]
Because CKeditor 4 will never work, i've removed it.
You may open a feature request if you require CKeditor 5
