### ISSUE TITLE
Does not load in mobile view in Nextcloud on a mobile phone (iPhone) - the app remains in a kind of continuous loop in the loading process

### ISSUE THREAD

**Issue by majo1989** [the-djmaze/snappymail#631]
**Describe the bug**
In the mobile view on the iPhone (iOS 16.1) in the Nextcloud 24.0.6 (self hosted), the app remains in a kind of continuous loop in the loading process. Neither the login window nor the inbox etc. are loaded. Only "Snappymail" can be read and the loading circle rotates. However, nothing is loaded. On an iPad also with iOS 16.1 this works without any problems. The mobile view is probably not used there either.

**To Reproduce**
1. Go to Nextcloud and open Snappymail on your mobile phone

**Please complete the following information:**
- Browser: mobile Safari, mobile Firefox, mobile DuckDuckGo
- PHP version: 8.0.25
- SnappyMail Version: 2.20.2

![IMG_3898](https://user-images.githubusercontent.com/82235132/200141447-c0836611-67f8-40c5-9ee9-ca3d93a99a4f.jpeg)

**Comment by the-djmaze** [comment]
There is no difference in sourcecode so something is happening in the browser.

If you have an OSX device you can debug Safari by plugging in your iPhone to the Mac and use manuals found online.

I don't own an iPhone (only old iPad and old Mac)

**Comment by daffydock** [comment]
Just FYI:

Tried it on Android, using Bromite Browser. Got in, no problem. No issue.

**Comment by majo1989** [comment]
If I set debug mode, what information is needed from it? Unfortunately I'm not really familiar with that. What I have noticed in the meantime, when I request the Nextcloud as a desktop website on the iPhone, it seems to work.

**Comment by majo1989** [comment]
Does this error message help?

Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

**Comment by the-djmaze** [comment]
Yes, i made changes to the CSP and you can try v2.20.3

**Comment by majo1989** [comment]
I just tried the new version 2.20.3. Unfortunately the error persists.

I also noticed the following entry in the nextcloud log. I don't know if that has anything to do with the problem though:

Array to string conversion at /var/www/html/custom_apps/snappymail/app/snappymail/v/2.20.3/app/libraries/snappymail/pgp/gpg.php#1038

**Comment by the-djmaze** [comment]
> Array to string conversion at /var/www/html/custom_apps/snappymail/app/snappymail/v/2.20.3/app/libraries/snappymail/pgp/gpg.php#1038

Weird, that should not be possible as proc_open() on that line requires array.
Sound like you PHP is not loading the correct files and uses old versions from cache or something.

Did you try reload/restart your Nextcloud/PHP instance?
Because there are more open/closed Nextcloud issues here caused by strange setups.

**Comment by majo1989** [comment]
I'm using the nextcloud all-in-one docker version behind nginx. (https://github.com/nextcloud/all-in-one) With this docker container, the setup is more or less completely specified. Except for a few additional apps, nothing has been changed in the settings. Even restarting the Docker container and thus the nextcloud did not bring any improvement. Until a few days ago, I think it was version 2.19.x, everything ran smoothly. The problems only really started with the update to 2.20.x.

**Comment by majo1989** [comment]
I also tested SnappyMail on my "dev instance" with version 2.20.3. The same PHP error appears.

**Comment by the-djmaze** [comment]
Sounds like same issue as with Microsoft Edge
https://github.com/the-djmaze/snappymail/issues/633#issuecomment-1306100054

**Comment by the-djmaze** [comment]
Confirmed it is a Nextcloud bug!
https://github.com/nextcloud/server/blob/0dabc6abc6fe203b5126a6f4fc33ddb55cfd41ea/lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php#L80

**Comment by the-djmaze** [comment]
Released v2.20.4 to workaround this Nextcloud bug
