### ISSUE TITLE
Does not load with Microsoft Edge Version 107.0.1418.35 

### ISSUE THREAD

**Issue by hansaushamburg** [the-djmaze/snappymail#633]
**Describe the bug**
Snappy Mail does not load using Microsoft Edge
Version 107.0.1418.35 (Official build) (64-bit) under Windows 10

**To Reproduce**
1. Open Nextcloud Dashboard
2. Try to open Snappy Mail via icon on top
3. Snappy Mail does not open ... wheel keeps spinning

**Expected behavior**
Expected to open Snappy Mail

**Screenshots**

**Please complete the following information:**
- Browser: [Microsoft Edge Version 107.0.1418.35 (Official build) (64-bit) under Windows 10
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.1.11
- SnappyMail Version: 2.20.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
Works fine under Firefox and Chrome Browser

**Comment by hansaushamburg** [comment]
Rainloop Mail App works fine

**Comment by the-djmaze** [comment]
Check you browser developer window for any errors and report them here.

**Comment by hansaushamburg** [comment]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'self' _mycloudadress.de_ blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('_mykeyword_'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by the-djmaze** [comment]
Thanks! Now i can look for the problem

**Comment by pm-pm** [comment]
Same here with Edge "Version 104.0.1293.63 (Offizielles Build) (64-Bit)" Windows 10
Can not update Edge due to "managed by organisation"
Nextcloud Version: 24.0.7

**Comment by elhananjair** [comment]
Hello @the-djmaze sorry again, does this issue by any means related to my closed issue here https://github.com/the-djmaze/snappymail/issues/621#issuecomment-1304571673? because everything was working fine before but since I don't know the recent versions I couldn't load images on specifically on signatures while images are being loaded on other inbox mail content.

**Comment by hansaushamburg** [comment]
Updated to 2.20.3 and unfortunately still not loading with MS Edge

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'self' _mycloud.de_ blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('_mykeyword_'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by the-djmaze** [comment]
Very strange because there should be a nonce in the content-security-policy.
Can you check the network request headers in Edge?

**Comment by the-djmaze** [comment]
Tested and the problem is Nextcloud.
When Nextcloud detects Microsoft Edge it totally disregards the set Content-Security-Policy at throws an invalid header to Edge.

I can't solve this so:
1. report to Nextcloud
2. use embed mode for access ?admin through /run/?admin untill Nextcloud fixes it

**Comment by the-djmaze** [comment]
Confirmed it is a Nextcloud bug!
https://github.com/nextcloud/server/blob/0dabc6abc6fe203b5126a6f4fc33ddb55cfd41ea/lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php#L80

**Comment by the-djmaze** [comment]
Released v2.20.4 to workaround this Nextcloud bug

**Comment by the-djmaze** [comment]
I've made a workaround in v2.20.5 that also works in embed mode.
SnappyMail will forcefully set the `nonce` when Nextcloud does not when `browserSupportsCspV3` returns false.

**Comment by hansaushamburg** [comment]
2.20.5 is working :-) Thank you.



Am 7. November 2022 um 23:25 schrieb "the-djmaze" ***@***.***>:
