### ISSUE TITLE
Folder Drag & Drop

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#64]
Under the folder tab, there's not a good way to move a folder unless you delete them and make a new folder.
There should be a drag and drop feature to let us move the folders without deleting them.

**Comment by the-djmaze** [comment]
I will check the possibilities regarding
https://tools.ietf.org/html/rfc3501#section-6.3.5

**Comment by the-djmaze** [comment]
@ivnmad almost right :)
