### ISSUE TITLE
Minor version number bug

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#640]
When you upgrade from 2.20.x to the latest it says 2.20.3 is the latest.
While only 2.20.2 is released.

![image](https://user-images.githubusercontent.com/4199669/200430686-81b92162-131d-488f-8c8f-2b8847563d6a.png)

**Comment by the-djmaze** [comment]
You can read here why https://github.com/the-djmaze/snappymail/releases/tag/2.20.5
