### ISSUE TITLE
How to install in cpanel?

### ISSUE THREAD

**Issue by raflisyahnur** [the-djmaze/snappymail#645]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by the-djmaze** [comment]
https://api.docs.cpanel.net/guides/quickstart-development-guide/tutorial-integrate-custom-webmail-applications/

Good luck!

**Comment by raflisyahnur** [comment]
> 

![Screenshot_20221109-012551_Chrome](https://user-images.githubusercontent.com/83658771/200645726-210bb33a-eeb8-4ed0-b3f9-801cef37010d.png)
Why?

**Comment by the-djmaze** [comment]
Which browser?

**Comment by raflisyahnur** [comment]
> Which browser?

I try with chrome and kiwi browser
Same result problem libs.min.js

**Comment by the-djmaze** [comment]
What happens when you just open that file?

**Comment by raflisyahnur** [comment]
> What happens when you just open that file?

Sorry, i dont get it u mean?

**Comment by raflisyahnur** [comment]
Sorry, i dont get it u mean?

**Comment by raflisyahnur** [comment]
> What happens when you just open that file?

![Screenshot_20221109-042429_Kiwi Browser](https://user-images.githubusercontent.com/83658771/200678609-f28c3000-0cd5-4aa2-893b-2a72d7802886.png)

**Comment by raflisyahnur** [comment]
> What happens when you just open that file?

![Screenshot_20221109-043828_Kiwi Browser](https://user-images.githubusercontent.com/83658771/200681222-8a2b3536-983b-4ddd-9033-f069e779cf3b.png)

**Comment by the-djmaze** [comment]
They all are `403 Forbidden` so that means something on your server is denying access.
Could be:
* .htaccess directives
* Apache .conf directives
* Directory read/execute forbidden

Good start is to check your Apache/Nginx error logs

**Comment by raflisyahnur** [comment]
Htaccess or directory no, i already set permission
But apache conf idk, coz i install on cpanel, not server

**Comment by raflisyahnur** [comment]
> They all are `403 Forbidden` so that means something on your server is denying access. Could be:
> 
> * .htaccess directives
> * Apache .conf directives
> * Directory read/execute forbidden
> 
> Good start is to check your Apache/Nginx error logs

Fixed, thankyou ❤️
