### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by raflisyahnur** [the-djmaze/snappymail#646]
I setting background to darkshine, but only showing pink background 
Another background same too
![Screenshot_20221109-071630_Chrome](https://user-images.githubusercontent.com/83658771/200706140-0e71a8e2-d92f-4813-93a0-8069106b2bc4.jpg)
![Screenshot_20221109-072702_Chrome](https://user-images.githubusercontent.com/83658771/200706154-fb110023-7432-47cb-a4f7-2dac1453e61d.jpg)

**Comment by the-djmaze** [comment]
When the width of the screen is less then 1000px the image is not loaded.
This is to prevent additional mobile data transfers as mostly in mobile view the image is hardly visible anyway.
