### ISSUE TITLE
I want to change from starttls to SSL in the domain ini file

### ISSUE THREAD

**Issue by the-djmaze** [the-djmaze/snappymail#648]
quick question - for some reason I can no longer login to admin panel - I want to change from starttls to SSL - (imap on 993, smtp on 465) - in the domain  ini file - i currently use "TLS"  - what do I change it to to get SSL ?

I meant the 2 settings: imap_secure nd smtp_secure
I glanced at code but wasn't obvious - i found TLS but nothing obvious like SSL

_Originally posted by @gene-git in https://github.com/the-djmaze/snappymail/issues/641#issuecomment-1308598321_

**Comment by the-djmaze** [comment]
domain ini files are obsolete. it is changed to be json files so there are two ways:

domain.ini
```ini
imap_port = 993
imap_secure = "SSL"
```

domain.json
```json
{
    "imapPort": 993,
    "imapSecure": 1,
}
```
0 = none/auto-starttls, 1=ssl, 2=force starttls

**Comment by gene-git** [comment]
aweseome thanks - i see the default json will switch over to that - will application.ini -> applciation.json as well?

**Comment by the-djmaze** [comment]
> will application.ini -> applciation.json as well?

Not at the moment as that is more complicated.

**Comment by gene-git** [comment]
I assume I name i switch from domain.com.ini to domain.com.json - or is there some other part of config that needs to change

**Comment by gene-git** [comment]
comment - the template in default.json is missing 'name" - without it stuff seems not to work.

**Comment by the-djmaze** [comment]
V2.21 is changed as it will support more control in the future.
Open domain via ?admin and save.
You will see the new structure.
