### ISSUE TITLE
Dark mode issue on admin page?

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#65]
**Describe the bug**
Just updated to latest release 2.4.1 (from 2.3.1) and went to admin page/panel. See screenshot below :) Perhaps something to do with all the dark mode changes? 

**To Reproduce**
1. Update to 2.4.1
2. Open admin config page.

**Expected behavior**
I think it should be readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/4435930/111902067-c3589c80-8a3b-11eb-97b1-4eca98e99d18.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 Workstation Edition
 - Browser: Firefox 85.0.1
 - SnappyMail Version: 2.4.1

**Mobile (please complete the following information):**
n/a

**Additional context**
Not really. Just that it worked on 2.3.1.

**Comment by the-djmaze** [comment]
You are right.
I've modified 1 theme to be 100% dark mode in frontend but not the admin.
I will improve that theme to be working in admin as well.

**Comment by the-djmaze** [comment]
Is it solved with https://github.com/the-djmaze/snappymail/releases/tag/v2.4.2 ?
