### ISSUE TITLE
 [Nextloud] Feature request: be able to have different email accounts open in different tabs

### ISSUE THREAD

**Issue by beankylla** [the-djmaze/snappymail#650]
Thanks again for making Snappymail for nextcloud a reality! You rock!
i was so annyed by Rainloop bugs that are fixed in Snappy ! And it's so more snappy! :)

**SnappyMail version, browser, browser version:**
Snappymail for Nextcloud 2.20.6, Firefox 106.0.3 

**Expected behavior and actual behavior:**
When opening several tabs being able to select a different email adress and  have it work properly
Currently there seems to be only one "active" email adress, so you can't have a tab with adress A and a tab with adress B there is some kind of mixup

**Steps to reproduce the problem:**
Open Snappymail for NC in 2 different tabs
select email A in tab A
select email B in tab B
go back to tab A and try to load a folder (send emails for example). The emails displayed will be the ones of email B
Email displayed on top right in tab A is still email A.

**Logs or screenshots:**
my emails are reaaaally boring ;)

**Comment by the-djmaze** [comment]
The reason that it is not possible is that the login credentials are not stored on the server.
They are in a (multi)cookie.

You could open two browsers like Chrome and Firefox

**Comment by beankylla** [comment]
alternative: open browser in incognito mode
would still be nice to have though, if possible :)

**Comment by the-djmaze** [comment]
> would still be nice to have though, if possible

I understand, but that would make things very complicated.
Also i don't think hosting providers like the idea that you (and many others) have 10 tabs open and they all are polling the server for new mails.
Then they would need multiple AMD EPYC 7763 processors with NVMe local storage :smile:
