### ISSUE TITLE
[Nextcloud] Session Timeout is not synced with Nextcloud

### ISSUE THREAD

**Issue by beankylla** [the-djmaze/snappymail#651]
**Describe the bug**
Open your browser and connect to Nextcloud 
Close browser
reopen browser while Session token is still valid in browser
go to Snappymail
Snappymail will ask you to connect

**To Reproduce**
1. Open your browser and connect to Nextcloud 
2. Close browser
3. reopen browser while Session token is still valid in browser (next day)
4. go to Snappymail
5. Snappymail will occasionally ask you to connect (i guess when snappymail session is invalid, but not NC?)

**Expected behavior**
I think it would make sense that Snappymail and NC have the same session validity settings, just for coherence sake :)

**Please complete the following information:**
Nextcloud 2.20.6, 
Firefox 106.0.3

**Comment by the-djmaze** [comment]
Correct and not possible.
Instead you have two options:
1. SnappyMail -> Settings -> Security -> Logout after N minutes/hours/not
2. Nextcloud -> Personal settings -> Additional (fill login credentials here for automatic login)
