### ISSUE TITLE
Detect '@' in Textfield and add to list of receipients

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#652]
Like outlook, the message editor should be able to grab an entered "@" and open the contactlist as is does in "to: CC: bcc:"
Then, if not already in the "to:" the contact found there should be populated into the list of receipients, and removed from CC/BCC if entered there.

**Comment by the-djmaze** [comment]
No, i'm not going to modify the textarea WYSIWYG to detect email adresses.
In theory SnappyMail supports multiple WYSIWYG through plugins/extensions and that makes is complicated.
