### ISSUE TITLE
401 Unauthorized : Synchronization (CardDav)

### ISSUE THREAD

**Issue by jphuguet** [the-djmaze/snappymail#653]
**Describe the bug**
I have configured the contact synchronization with my self-hosted Nexcloud.  

![2022-11-10_16-52](https://user-images.githubusercontent.com/59970612/201142454-073f608d-88bb-4da3-a474-d71f7b73c2ec.png)

The synchronization fails with a `401 Unauthorized` error on my webserver.
No errors in the Snappymail web UI.

Url, user and password are ok, they work fine in Thunderbird or DavX.

**To Reproduce**
- got to the contact view
- open the burger menu
- click on `Synchronization (CardDav)`

**Expected behavior**
The address book is synced with Nexcloud.

**Please complete the following information:**
- Browsers: 
  - Firefox 106.0.3
  - Chromium 107.0.5304.87
- PHP version: 7.4.3
- SnappyMail Version: 2.20.6

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Here are the logs of my webserver

```
192.168.10.3 - - [10/Nov/2022:16:53:47 +0100] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/jphuguet/contacts/ HTTP/2.0" 401 450 "-" "SnappyMail/2.20.6"
192.168.10.3 - jphuguet [10/Nov/2022:16:53:48 +0100] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/jphuguet/contacts/ HTTP/2.0" 207 75963 "-" "SnappyMail/2.20.6"
192.168.10.3 - - [10/Nov/2022:16:53:48 +0100] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/jphuguet/contacts/ HTTP/2.0" 401 450 "-" "SnappyMail/2.20.6"
192.168.10.3 - jphuguet [10/Nov/2022:16:53:50 +0100] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/jphuguet/contacts/ HTTP/2.0" 207 118740 "-" "SnappyMail/2.20.6"
```

**Comment by the-djmaze** [comment]
Any luck with v2.21.1?

**Comment by jphuguet** [comment]
Still no luck with `2.21.1`, same behaviour & error logs.

**Comment by the-djmaze** [comment]
Please re-enter password in the settings, maybe that helps.

**Comment by MI-KY** [comment]
@jphuguet is the log that you have sent the Nextcloud log?
Is there maybe something visible in the SnappyMail logfile when you activate the debugging of SnappyMail?

**Comment by the-djmaze** [comment]
I've tested this and made changes to the code.

It works with my Nextcloud 25 and i don't get 401 Unauthorized, so i've improved the debug logging for next release.
That should get you started why yours is failing.

**Comment by the-djmaze** [comment]
You can test with debug mode and v2.21.3
https://github.com/the-djmaze/snappymail/releases/tag/v2.21.3

**Comment by jphuguet** [comment]
Well, I had to move my nextcloud & snappy mail to k3s : no more issue since so I guess there was somtehing wrong on my side (but it worked at some time though).
Anyway, same URL, same user & password : it works.

`problem solved` I guess.
