### ISSUE TITLE
Logging in syslog

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#66]
**Description of the problem.**
Actually snappymail use files to store the logs. As the file name change each day (with the date), it is not possible to add the syslog reader on it. Syslog can send the logs to external servers with analysis to be informed when there is a problem.

**Proposed solutions**
I propose two solutions :
- Use always the log same file name (instead of date) and create (or use the system one) logrotate to have the .1 .2 .3 files. For the rotated logs you can also use the date if you prefer.
- Create a optional syslog export 
- Use both ;-) (which I prefer)

**Comment by the-djmaze** [comment]
You can use syslog:
* Open `/_data_/_default_/configs/application.ini`
* Find `[logs]`
* Find `filename = `
* Set `filename = "syslog"`

SnappyMail already logs failed login attempts to syslog so you can use things like fail2ban:
https://github.com/the-djmaze/snappymail/tree/master/fail2ban

**Comment by dominiquefournier** [comment]
Thanks to update the doc. Is there a way to define the facility ?

**Comment by the-djmaze** [comment]
https://www.php.net/manual/en/function.openlog.php

When auth_logging is on (see application.ini)
The facility is LOG_AUTHPRIV

For normal logging the facility is LOG_USER
because it is the only valid log type under Windows operating systems.

**Comment by dominiquefournier** [comment]
Perfect !
Thanks a lot
