### ISSUE TITLE
[105] missing version directory

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#660]
**Describe the bug**
This issue happens in v2.20.6 and v2.21.0. I am not sure which version I had before 20.6 but v2.19.7 worked fine.

... I just found the culprit. This bug only happens if SnappyMail and Rainloop app are both active. Not sure if there is anything you can do but this issue may be relevant for users who want to switch from Rainloop to Snappy and have both apps running simultaneously (e.g. copying the settings from one to the other).

**To Reproduce**
1. Activate both apps
2. Open SnappyMail and logout (I have autologin enabled so it automatically logs back in)
3. Click Nextcloud logout

This results in a blank page with the text above as the only content. You can go back in your browser history. As you will see, you are still logged in.

**Screenshots**
![screen](https://user-images.githubusercontent.com/1321720/201472951-e1dcca57-9fb8-41ba-88f3-9bfc9a8f2237.png)

**Please complete the following information:**
- Browser: Firefox
- SnappyMail Version: v2.21.0

**Comment by the-djmaze** [comment]
You can't run both at same time because classes used in RainLoop conflict with SnappyMail.
SnappyMail can import RainLoop data
