### ISSUE TITLE
PUTinICS calendar not recognized

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#661]
Referencing existing issue but with new calendar content:

Reopen with the following calendar:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:www.ccccc.dd
METHOD:PUBLISH
BEGIN:VEVENT
UID:20221112T093211-www.dddddddd.ed
ORGANIZER;CN=xxxxxx, xx<:MAILTO:info@cccccc
LOCATION:xxxxxx
SUMMARY:Reservierung
DESCRIPTION:Buchungs-Nr.: 1006341
 \nDatum / xxx: 13.11.2022 / 09:00
  \nloc: 12 4444444445
   \ngame 1: sadsadasdsa, w:y 
CLASS:PUBLIC
DTSTART:20221113T090000
DTEND:20221113T130000
DTSTAMP:20221112T093211
END:VEVENT
END:VCALENDAR
```

_Originally posted by @Bolli84 in https://github.com/the-djmaze/snappymail/issues/622#issuecomment-1312491016_

**Comment by the-djmaze** [comment]
That's a strange format.
Not only the `\n` but also the spaces in front of them.

Is this really correct?

**Comment by Bolli84** [comment]
Yes, it is an used format for booking into Reservations at hotels, restaurants, gamespace bookings over many simple websites. 

This is just a very abbreviated form but shows all relevant content.

**Comment by the-djmaze** [comment]
Ok, this is a Nextcloud bug.
Nextcloud Calendar requires ATTENDEE and your file has none.
https://github.com/nextcloud/calendar/issues/4684

But according to [RFC 5545 section 3.6.1](https://www.rfc-editor.org/rfc/rfc5545#section-3.6.1):
> ; The following are OPTIONAL, and MAY occur more than once.
attach / attendee / categories / comment /
contact / exdate / rstatus / related /
resources / rdate / x-prop / iana-prop

Yes your file is valid, problem is Nextcloud

**Comment by Bolli84** [comment]
Does snappymail recignize the calendar-file to be imported?

The calendar can be imported by nextcloud calendar directly quire easy. But it should be recognized first

**Comment by Bolli84** [comment]
With the PUT into the webdav calendar as well as ther direct IMPORT into the calendar by opening the Calendar and importing it with the lower left corner

**Comment by the-djmaze** [comment]
Ok, then they probably modify the ICS file to fit their needs.
I just PUT as-is

**Comment by Bolli84** [comment]
Just as I did with old rainloop. Only PUT it.

**Comment by the-djmaze** [comment]
@Bolli84 that's whatbthe code does.
Exactly the same, so something else is going on.

Maybe line endings CRLF vs LF, maybe something else.

**Comment by the-djmaze** [comment]
I've tested and tested and tested.
The problem really is Nextcloud and i can't do anything about it.

When an .ics file contains `ATTENDEE` or `ORGANIZER`, Nextcloud Calendar 4.1.0 keeps crashing on me.

When i remove all `ATTENDEE` and `ORGANIZER` properties of the .ics, the import is succeeds.

I even tried the import function of Nextcloud Calendar itself and it still keeps crashing, so it really has nothing to do with SnappyMail

**Comment by Bolli84** [comment]
My point is the following:

On many other calendars, the button: "Put in Calendar" appears in snappymail to include it. The given calendaritem does not show this in snappymail. It allows me to download it.

So, this is not even at the point to IMPORT it still for me.

**Comment by the-djmaze** [comment]
Admin -> Extensions -> Nextcloud cog wheel yo enable

**Comment by Bolli84** [comment]
No, does not work.

Can I send you my calendar-mail i got for you to try?
