### ISSUE TITLE
bad call of SnappyMail\Log::warning() in libraries/RainLoop/Config/Application.php

### ISSUE THREAD

**Issue by Viqsi** [the-djmaze/snappymail#663]
While trying to install Snappymail for the first time, I was running into some issues with being unable to configure it due to server errors. I've not pinned that down, but there is one glaringly obvious error that the server log has pointed at:

Exception: Too few arguments to function SnappyMail\Log::warning(), 1 passed in /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.21.0/app/libraries/RainLoop/Config/Application.php on line 44 and exactly 2 expected in file '/var/www/nextcloud/apps/snappymail/app/snappymail/v/2.21.0/app/libraries/snappymail/log.php' line 16

A quick grep through the plugin source suggests this is the only place where SnappyMail\Log::warning() gets only one argument. I'm not sure what the first parameter ought to be (I "patched" it locally by just putting in a first parameter of "config"), so this is a bug report rather than a pull request.

**Comment by the-djmaze** [comment]
Is fixed in https://github.com/the-djmaze/snappymail/commit/e7958fb1edc082581ebf29114bbccfb04eab7231
