### ISSUE TITLE
Divide back-end (php) from front-end (angularjs)

### ISSUE THREAD

**Issue by stepobiz** [the-djmaze/snappymail#667]
**Is your feature request related to a problem? Please describe.**
When i want assign development of new feature to front-end developer i have problem to set all enviroment

**Describe the solution you'd like**
Divide in two parts the project, back and front

**Describe alternatives you've considered**
Permit development to front-end developer without install php, and use a backend remote.

**Comment by the-djmaze** [comment]
Current front-end is in KnockoutJS, but you can write your own in Angular if you want.

Each request/response is JSON like with REST.
There is no documentation of each.
