### ISSUE TITLE
Show size of email

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#67]
**Is your feature request related to a problem? Please describe.**
Can't easily see/sort messages on size.

**Describe the solution you'd like**
I'd like (an option) to see the mail size in the message list. Perhaps even a option to ve able to sort on it.

**Describe alternatives you've considered**
The workaround with the search bar (size:1M) etc. like in https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6335200-display-size-of-email

**Additional context**
Not really.

**Comment by the-djmaze** [comment]
On small phones the space is limited.
But on the right of the mail subject might be doable, although that space is also used for attachment icon.

**Comment by ervee** [comment]
Perhaps in place of the "star" (or a toggle between star and size). Who uses that anyway ☺️

![Screenshot_20210324-203633](https://user-images.githubusercontent.com/4435930/112373276-12732b80-8ce1-11eb-8f52-019823b33ba5.jpg)

**Comment by the-djmaze** [comment]
> Perhaps in place of the "star" (or a toggle between star and size). Who uses that anyway relaxed

Haha, but the star/flag/important mark is actually used a lot.
I also get questions why people can't have several colors to distinguish the level of importance.
I always advice: "create 4 folders in the INBOX"
* critical
* high
* medium
* low

You had a good thought ;)

**Comment by the-djmaze** [comment]
Check the demo if that is ok for next release

**Comment by the-djmaze** [comment]
> Perhaps even a option to ve able to sort on it.
Works in branch. Just need to find space to make it switch in messagelist :wink:

**Comment by ervee** [comment]
Demo looks great!

**Comment by phsc84** [comment]
Yeah, looks really great. Would love this feature too.

**Comment by the-djmaze** [comment]
This ok enough for sorting?

![sort-desktop](https://user-images.githubusercontent.com/3752035/112703435-337d7d00-8e97-11eb-9c38-22e1829472e7.png)
![sort-mobile](https://user-images.githubusercontent.com/3752035/112703436-34161380-8e97-11eb-9f3a-5743c4862363.png)

**Comment by phsc84** [comment]
For me it is perfectly fine this way.

**Comment by ervee** [comment]
I have been waiting many years for this functionality.

You are awesome! And Dutch. And therefore double awesome! :)

**Comment by the-djmaze** [comment]
Thanks!

Merged in master for next release.
https://github.com/the-djmaze/snappymail/commit/ec03999f1349e53574c9c744a64800b043d47dd7

**Comment by ervee** [comment]
I  L.O.V.E  the feature! But (there it is...) there seems to be some issue with it. When I switch from sorting date to size it looks like it is refreshing the list, but it then shows no change in the mail list itself. After some fooling around it looks like the list is only correctly displayed after I delete/move a message.

**Comment by the-djmaze** [comment]
@ervee i can't replicate the issue.
I'm using:
* dovecot 2.3.13
* server: localhost
* port: 25
* encryption: none

If debugging is hard, i will create a log option for it in
`app/libraries/RainLoop/Actions/Messages.php`
`function DoMessageList` sets the $sSort but that might fail?

**Comment by ervee** [comment]
I tried to debug this some more with some tcpdumps and I see SnappyMail connecting to Dovecot (still on Debian 9, so version 2.2.27) so it is getting the mail list, probably with the applied sorting. But the mail list in SnappyMail just does not update. When I delete a mail, BOOM! Updated list with the sorrect sorting I last selected.

**Comment by the-djmaze** [comment]
> When I delete a mail, BOOM! Updated list with the sorrect sorting I last selected.

Aha! It might be a cache thing then.
I haven't figured out all the cache options yet, but that will be something to look into.
