### ISSUE TITLE
Increase visible reading area for small screens

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#672]
I think the screenshot below summarizes what I want to say. The red area is the one visible to the user upon opening an email.
Sure, you get a little extra room when you scroll the attachment bar up, but still; the usable area is less than a third of the whole screen. Especially horizontal space is missing in my opinion.

Can we have parts of the header collapsable or scroll out of the way?

- For example, the date is always on a new line. In Rainloop it was on the same line as the sender and thus not waste an extra line.
- If the spam score is always this tiny progress bar, we could also place the email tags right after. But I dont know if there is usually text after the progress bar or not.
- For the recipients and CC there could be a "+ 3 more" button to load the full list when needed.

![screen](https://user-images.githubusercontent.com/1321720/201687852-78140292-ff0c-422b-b580-53d73753ce0b.png)

**Comment by the-djmaze** [comment]
There is a full-screen mode. Just hit the Enter key or look in the message menu (half way).

I will think further how we can increase the height

**Comment by relikd** [comment]
Thank you! I think the suggestions above will already help a lot. I have another email from an email listing that adds 8 lines because of the recipients field.

I forgot about the fullscreen mode but it has other limitations like not being able to switch between emails and accounts, or have two emails open in two tabs. Though I did not know about the Enter-Hotkey. I would add that to the menu entry (e.g., in parenthesis)

**Comment by the-djmaze** [comment]
Ok, v2.21.2 doesn't have the last commit where i closed this issue.
I just had coffee and then a light bulb :smile: 

You will see in next release
