### ISSUE TITLE
[Nextcloud] Compose window title bar is behind Nextcloud menu : cannot click on Send button

### ISSUE THREAD

**Issue by Mer0me** [the-djmaze/snappymail#673]
**Describe the bug**
When I compose a new email in SnappyMail within Nextcloud, the compose window shows up but the title bar of this window is "behind" the Nextcloud menu so I can't click the buttons or close the compose windows.

**To Reproduce**
1. On Nextcloud / SnappyMail, click on new button 
2. Try to click "send"

**Expected behavior**
Compose window should be in front of the Nextcloud interface

**Screenshots**
![image](https://user-images.githubusercontent.com/6248852/201853586-c3d44f11-245f-4554-b47a-6c76ca7ac24a.png)

**Please complete the following information:**
- Browser: Firefox 91.8.0 ESR
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.21.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
not relevant

**Additional context**
Resolution of the screen : 1920x1080

**Comment by the-djmaze** [comment]
SnappyMail uses HTMLDialogElement.
This `<dialog>` is supported by Firefox 98+ and Safari 15.1+.
For older versions it uses polyfill code to simulate the behavior.

The z-index of the dialogs start at 3000, and the Nextcloud 25 menu has z-index 2000.
In theory this should be sufficient, but somehow not with yours.

You can either:
1. upgrade Firefox to 102 ESR
2. inspect the element and tell us which z-index value solves your issue.

**Comment by Mer0me** [comment]
Z-index = 3001 => body of compose window is behind Nextcloud UI
![image](https://user-images.githubusercontent.com/6248852/201870861-2e9e463b-6389-4351-a0f0-4d0d91278d86.png)

Z-index = 3002 => body of compose window in front of Nextcloud UI but behind Nextcloud menu
![image](https://user-images.githubusercontent.com/6248852/201870986-559b5662-aae6-4ac1-aed8-4f5f258a1ad7.png)

Z-index= 3000000000000000000000000000000 => Nothing change
![image](https://user-images.githubusercontent.com/6248852/201871175-69cf2eec-430c-44cd-b81c-c22e5b03a4ba.png)

Unable to upgrade firefox here (office) but I'm sure it would solve the problem.

I confirm that the header (Nextcloud menu) has a z-index=2000 
```
#body-user #header, #body-settings #header, #body-public #header {
    display: inline-flex;
    position: absolute;
    top: 0;
    width: 100%;
    z-index: 2000;
    height: 50px;
    box-sizing: border-box;
    justify-content: space-between;
```

**Comment by the-djmaze** [comment]
Then you can do 2 additional tests:
```css
#body-user #header, #body-settings #header, #body-public #header {
    position: fixed;
```

```css
#content {
    z-index: 2001;
```

**Comment by the-djmaze** [comment]
Else the margin-top of the dialogs must become
```
dialog {
    margin-top: 50px
```
```

**Comment by Mer0me** [comment]
> Else the margin-top of the dialogs must become
> 
> ```css
> dialog {
>     margin-top: 50px
> ```

This one works. Not your first proposition.
