### ISSUE TITLE
Nextcloud passwords do not work when rainloop and snappymail are enabled at the same time

### ISSUE THREAD

**Issue by schengawegga** [the-djmaze/snappymail#675]
**Describe the bug**
When Nextcloud Rainloop and Snappymail are enabled at the same time, Nextcloud passwords do not work.
The error in the browser console shows: Uncaught (in promise) Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8

**To Reproduce**
1. Rainloop AND Snappymail must be enabled in the nextcloud
2. Opening Passwords show no passwords, only the loading screen is shown and litte notification with "200 - OK".

**Expected behavior**
Passwords in the Password App should be shown

**Please complete the following information:**
- Browser: Firefox 106.0.5
- PHP version: 7.4.28
- SnappyMail Version: 2.21.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
No Nextloud log available
Browser console log: Uncaught (in promise) Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8

**Additional context**
marius-wieschollek/passwords#544

**Comment by the-djmaze** [comment]
Correct. It's not possible to run both at the same time.
