### ISSUE TITLE
Wrong folder autodetected as 'Sent'

### ISSUE THREAD

**Issue by realsimix** [the-djmaze/snappymail#68]
**Describe the bug**
SnappyMail automatically detects well known folders like 'Sent'. This can go wrong if there are multiple such folders around.

**To Reproduce**
1. Go to 'Folder List' -> 'System Folders'
2. See that 'Sent' folder is moved to the right side and not aligned with the other system folders.
3. Check where the 'Sent' folder was detected.
4. Actually it is 'INBOX._old.Blabla.Sent' instead of 'INBOX.Sent'

**Expected behavior**
Would be nice if the detection mechanism was a bit smarted and tries to prefer the first match in the list of folders and not the last one at the end of the folders list.

**Additional context**
While this is not directly a bug, it seems clear that 'INBOX.Sent' is a better match than 'INBOX.old.Blabla.Sent'. Any chance this could be implemented?

Thanks,
Simon

**Comment by the-djmaze** [comment]
What kind of IMAP server do you have?
And does your IMAP server use the correct tag for the \Sent folder?

See https://tools.ietf.org/html/rfc6154#section-2

**Comment by realsimix** [comment]
This is on Cyrus-IMAPd which I guess should do the right thing.
The _old folder contains a restore from another mailbox which means the the '\Sent' annotation could also be found there, I didn't check.
But still, if two folders are named 'Sent' and also have the '\Sent' annotation set, it would still be nice if the first would be used instead of the last in the list.

Thanks,
Simon

**Comment by realsimix** [comment]
If I rename 'INBOX.old.Blabla.Sent' to SentX, then 'INBOX.Sent' is detected as System Sent Folder.

It seems that auto detection goes trough the complete folder list and remembers all system folders. That means the last occurrence of a folder wins and gets added to the system folders collection.

It would be nice to make the first match win here so that folders down in the folder tree somewhere are not used as system folders instead.

I guess this is somewhere done in `./app/libraries/RainLoop/Actions/Folders.php` but I'm unable to really find out how :-(

Any help to change this behavior would be much appreciated as it helps to make the user experience better and support happy.

Regards,
Simon

**Comment by the-djmaze** [comment]
It might be in ./libraries/RainLoop/Actions/Folders.php

Because `systemFoldersNames` is called by `recFoldersTypes`

Try to disable `$aMap = $this->systemFoldersNames($oAccount);`, and the lines below, in that file.
Maybe that will help.

**Comment by realsimix** [comment]
I tried it but it didn't help in my tests.

The way I understand it I expect the problem to be in one of the foreach() loops. It goes trough the folder list and detects system folders. The problem shows up if a folder has been found and remembered, but a folder with the same name comes again, this new one is then remembered instead of the first one.

Would it be possible to skip searching for already remembered folders by flagging them somehow or check if they are already found.

I miss to really understand the different foreach() loops but am sure there is the problem somehow.

**Comment by the-djmaze** [comment]
Good that you made some tests.
I will do some tests myself with an empty data folder.

**Comment by the-djmaze** [comment]
@realsimix i've made a test in the `private function recFoldersTypes`
Changed the line
```
$aResult[$iFolderListType] = $oFolder->FullNameRaw();
```
into
```
\error_log(' flags '. $oFolder->FullNameRaw() . ' = ' . \implode(' ', $oFolder->Flags()));
$aResult[$iFolderListType] = $oFolder->FullNameRaw();
```

My result:
```
flags Archive = \HasNoChildren \UnMarked \Archive
flags Drafts = \HasNoChildren \UnMarked \Drafts
flags INBOX = \HasChildren
flags Junk = \HasNoChildren \UnMarked \Junk
flags Sent = \HasNoChildren \UnMarked \Sent
flags Trash = \HasNoChildren \UnMarked \Trash
```

So somehow i can't find the problem

**Comment by realsimix** [comment]
But in your test, do you have a second 'Sent' folder somewhere in a sub folder? Because in my case the sub folder is used as Sent and not the upper level one.

BTW, I'm not sure about  \Sent flag in my case because my server data comes from an older Cyrus server which didn't support the rfc6154 style flags.

**Comment by the-djmaze** [comment]
> But in your test, do you have a second 'Sent' folder somewhere in a sub folder? Because in my case the sub folder is used as Sent and not the upper level one.

Yes i did create many.
Also the loops do have `!isset($aResult[$iFolderListType])` so it should only match the first in folder tree.


> BTW, I'm not sure about \Sent flag in my case because my server data comes from an older Cyrus server which didn't support the rfc6154 style flags.
Aha! then the auto-detect might be used.
In that case add the error_log line lower above
```
$aResult[$iFolderType] = $oFolder->FullNameRaw();
```

**Comment by realsimix** [comment]
Yes, that's where it gets the wrong Sent:

```
[29-Mar-2021 11:06:32 UTC]  flags2 INBOX._old.Blabla.Sent = \HasNoChildren
[29-Mar-2021 11:06:32 UTC]  flags2 INBOX.Archive = \HasNoChildren
[29-Mar-2021 11:06:32 UTC]  flags2 INBOX.Deleted Items = \HasNoChildren
[29-Mar-2021 11:06:32 UTC]  flags2 INBOX.Drafts = \HasNoChildren
[29-Mar-2021 11:06:32 UTC]  flags2 INBOX.Junk E-mail = \HasNoChildren
```

I'm also wondering if it's a problem with `$sName` and `$sFullName` being mixed up somehow.

**Comment by the-djmaze** [comment]
Great!
The problem is simple.
When fetching folders it first sees `INBOX._old.Blabla.Sent` and marks it.
Later on the `INBOX.Sent` is found but skipped.

My servers have no `INBOX.Sent`, it uses root folder `Sent`.
(that's because sent mail is in my opinion not IN-box but OUT-box related)

We could change the foreach loop to test for strlen();
But then a root folder like `old.Sent` gets higher priority (shorter length).

Therefore changes have to be made with two checks:
* is it a subfolder of INBOX?
* is it a root folder and no sub?

So something like:
```
if ((!isset($aResult[$iFolderType]) || 'INBOX.Sent' === $oFolder->FullNameRaw() || 'Sent' === $oFolder->FullNameRaw())
  && \in_array($iFolderType, array(
```

**Comment by realsimix** [comment]
OK I understand. The reason why everything is in sub folders below INBOX is because it's the old default with Cyrus. Newer versions have other defaults, and it can be configured of course.

I understand that this makes detecting system folders more complicated as you suggest above.
I've tried your suggestion and it seems to work but I guess it should be improved by using the delimiter provided by the server, like this:

`"INBOX{$sDelimiter}{$sName}" === $sFullName`

However, of course, `$sDelimiter` is not set here and I'm not sure how to implement this properly. I see in `DoFolders()` above that it calls `GetNamespace()` but how to add it best to `recFoldersTypes()`?

**Comment by the-djmaze** [comment]
See commit :wink:

**Comment by ervee** [comment]
> 	}
> 	mailbox spam {
> 		special_use = \Junk
> 		auto = no
> 	}
> 
> 	# Office365
> 	mailbox "Deleted" {
> 		special_use = \Trash
> 
> 	# Outlook
> 	mailbox "Concepten" {
> 		special_use = \Drafts
> 		auto = no
> 	}
You are missing a closing bracket for mailbox "Deleted" there.
And one at the bottom for the entire namespace configuration, but I assume that just fell off.

**Comment by the-djmaze** [comment]
@ervee correct it was some copy paste and not the whole file i use.
