### ISSUE TITLE
[Cosmetic] Text is slightly cropped in the header

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#682]
**Describe the bug**

The `line-height: 1.15;` of `#rl-app` is too small, the "g" of "github " is cropped. Works fine for me if set to `normal`.

**Please complete the following information:**
- Browser: Firefox 107 (Ubuntu)
- PHP version: 7.4
- SnappyMail Version: 2.21.3

---

![image](https://user-images.githubusercontent.com/20357783/202441545-6138fb6a-a465-4e56-9a9e-6b98f6fb5892.png)

**Comment by the-djmaze** [comment]
Would 1.2 be sufficient?

**Comment by Massedil** [comment]
> Would 1.2 be sufficient?

Nop, from 1.3 it is ok for me.

**Comment by the-djmaze** [comment]
Hmm that would be an issue with lining up the icons.

I wonder which font you are using as i don't have issues on GNU/Linux.

You can change font at Settings -> Themes

**Comment by Massedil** [comment]
Is this screenshot useful ?

![font](https://user-images.githubusercontent.com/20357783/202463207-998f448f-4f29-4a91-b7e8-4149f7551f26.png)

**Comment by the-djmaze** [comment]
Almost!
It doesn't mark the font that is actually in use.
Only the list is shown.

But you could rule out fonts by editing the CSS and find out which is responsible.

Nevertheless i should look into solutions to line-up the fontastic icons font better with the others based on line-height.

**Comment by Massedil** [comment]
I think it is Verdana.

![Capture d’écran_2022-11-17_16-35-34](https://user-images.githubusercontent.com/20357783/202489743-9c276f15-9fb0-46f6-83b7-b1d1e52af7a2.png)

**Comment by the-djmaze** [comment]
I've noticed on GNU/Linux with Firefox that also at browser/system places the text is cropped.
So this looks like a font rendering issue that is outside our control and must be a bug in Firefox.

In Chromium i couldn't find the issue anywhere

**Comment by the-djmaze** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=707508
https://support.mozilla.org/en-US/questions/1203962
https://bugzilla.mozilla.org/show_bug.cgi?id=1406552
etc. etc.

So i will close this, but will keep an eye on any viable solutions

**Comment by Massedil** [comment]
I can confirm that if I change my window resolution slowly sometimes the text is displayed normally (not cropped). 

> So i will close this, but will keep an eye on any viable solutions

Thanks !
