### ISSUE TITLE
Full `From:` email address near the contact name and other header improvements

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#683]
***Full From***

Is it possible to have the full `From:` email address near the contact name ? (Like in YahooMail and Gmail)
That is to says `"the-djmaze" <notifications@github.com>` instead of `the-djmaze`.
We already have both information (name and email) for `To:`, `Cc:`, etc.

***Reorganize all header in one zone***

Maybe we can put together in the same header zone `From:`, `To:`, `Cc:` ? Is there a reason the `From:` is alone and differently represented ?

***Buttons***

- Like Gmail : maybe we can have all the buttons at the right of the subject ? Snappymail order : "Star", "Reply", "Menu", "Cross"

![Gmail](https://user-images.githubusercontent.com/20357783/202452901-42815bae-9307-4247-8957-527b13b70d60.png)

- Like Thunderbird : maybe we can fully use the second line (at the bottom of the subject) to put buttons with labels and images. Order : "Reply", Reply to All" (only if more than one recipient), "Forward", "Archive", "Spam", "Delete", "Other" (=Menu)

![Thunderbird](https://user-images.githubusercontent.com/20357783/202451491-7c590754-e1a3-4047-b62b-a796591474ef.png)

***Tags***

- Do not display the Tag zone if there is no tag. (Like Thunderbird)
- If the tag zone is not displayed, move the tag menu button to the menu or with the other buttons displayed. (In Thunderbird, the tags are in the "Other" menu)

Thunderbird, if I add a tag, the tag section appears :

![Thunderbird-tag](https://user-images.githubusercontent.com/20357783/202451371-246aa1ba-b05d-4ef0-965b-b7fbf6ca8f2d.png)

***Date***

Also, in French, it is sounds better to say "Le 17 novembre 2022 à 12:24" or "Mercredi 17 novembre à 12:24" instead of "17 novembre 2022 à 12:24". For information :
- YahooMail : "mer. 17 nov. à 12:24"
- Gmail : "mer. 17 nov. 12:24"

Can we also have the "(il y a 39 minutes)" next to the Date in the `informationShort`, like in the the `informationFull` ?

***informationFull***

Can this toggle button be moved in the menu ? I'm not sure it is useful, if in the `informationShort` we : 
- display entire `From`
- show the "(il y a 39 minutes)" next to the Date

It stays in this section this useful information : 
- `ReplyTo:` header
- Size of the message

May be we can move it also outside of `informationFull` ?

---

![image](https://user-images.githubusercontent.com/20357783/202444498-96b9e7c5-6357-4d92-8b9d-719b23825f68.png)

**Comment by the-djmaze** [comment]
Click the big I icon on left of the star

**Comment by the-djmaze** [comment]
You want it because you have a big screen.
SnappyMail is "mobile first" which means it has to fit and be readable on small devices.

So: if your request fits in small screens it can be added.
Else just click the big `ℹ` icon on left of the star for full information (it will stay open for every e-mail)

**Comment by the-djmaze** [comment]
Here's a mobile view example using Firefox Developer tools
![afbeelding](https://user-images.githubusercontent.com/3752035/202459367-16660fd1-9c88-4b12-9b71-6b14d75cb661.png)

**Comment by Massedil** [comment]
> You want it because you have a big screen.

I don't think it is really related to the screen size :

- FullFrom : I think it is important to see the real From email, even on mobile (I know it can be forged). But we can hide it on small screen (Ok : Gmail and Yahoo effectively hide it on smartphone, I just checked)
- Reorganize all header in one zone : change nothing big screen or not
- Buttons in one line ("Gmail") : more space with big and small screens
- Long buttons ("Thunderbird") : effectively kind of useless in mobile because some of the buttons are now at the top, we can just adjust the mobile CSS to see only :  "Reply", Reply to All" (only if more than one recipient), "Forward", ~~"Archive", "Spam", "Delete",~~ "Other" (=Menu)
- Tags only if visible if set : more space with big and small screens
- Improved date : There is place for it even in mobile, no ?
- informationFull : It seems huge with big screen, and I understand it is for big screen only

> SnappyMail is "mobile first" which means it has to fit and be readable on small devices.

Okay, good thing !

> So: if your request fits in small screens it can be added.

 I can try to draw what I imagine.

**Comment by Massedil** [comment]
On small screen : 
- Subject is fully displayed
- Buttons can have `flex-grow: 1;` to use all space on mobile (here I just lazy copied them from Thunderbird)
- all "emails" headers in one section with the date (the day is added even with small screen)
- headers are on one line each and are aligned (like in a table) and are thin
- Tags disappeared because there is no tag

On large view : 
- New buttons "Archive", "Spam", "Delete" are displayed
- display a previously hidden item near the date "(il y a 39 minutes)"

About the `informationFull` / `i` button (I removed it by mistake), we can rethink it. Instead of changing all the header block `informationShort` by `informationFull`, clicking on this button "just" add new headers to the `informationShort` headers zone : 
- `ReplyTo` header
- "Size" header

If you prefer to see `From:` "Display Name" instead of `From:` "Email Address" , the click on the `informationFull` / `i` button switch the "Display Name" by the "Email Address".

Gmail mobile in Firefox does that : 
- By default you see "Display Name" 
- If you click on "Details", you see the "Email Address"

Gmail mobile in Firefox does also (but I'm not sure we want it) : 
- By default you see "(il y a 39 minutes)"
- If you click on "Details", you see "17 novembre, 12:24" (another way to display date ! ^^)

> As for the tags: if there are none, it would not mean you don't want to add them.
> How to add tags when the line is invisible, show the tags menu somewhere else?

In Thunderbird, the tag menu is always on the "Other/Menu", never near the tag zone.
So we can add it to the "Menu", I think it is sufficient. Or in the "new" button list.

**Comment by the-djmaze** [comment]
What about replacing the [Archive] icon button at the top for the [tags]  button?

Because:
1. how often "archive" people their messages
2. how often "tag" people their messages

**Another idea:**
In the message menu just have show/hide options (checkbox):
1. Show email address
2. Show tags
3. Show date
4. Show relative date (N hours/days ago) 
5. etc.

**Comment by Massedil** [comment]
> What about replacing the [Archive] icon button at the top for the [tags] button?

Personally, I heavily use the [Archive] icon button and I very rarely use the [Spam] icon button and rarely use the [Trash] icon button. But I imagine there is other use cases.

> how often "tag" people their messages

For me, the tag feature is not so much used because it comes from Thunderbird and it is not supported by major email provider (Gmail, Hotmail, Yahoo...). May be free software users uses it more than other however. Personally, I try to use it again since it is on Thunderbird and Snappymail, but it is not very useful because K9Mail does not support it. So if I'm on my mobile phone, I can't see tags... (Sorry, I rarely use Snappymail on my mobile phone ! ;))

For me, in the mobile view, it lacks the [Folder] icon button. I imagine it is hard to let it there because of the way it works to move an email to another folder...

> In the message menu just have show/hide options (checkbox):

Good idea, maybe it will make the menu heavier, so we can maybe put this in Options > General > Email Headers options to configure the `informationShort` view.

I think we can also have the `i` button that show the full Email/Name (or opposite of `informationShort` view). It can be useful sometimes to see the entire header whenever I have configured a smaller part of it for the `informationShort` view.

**Comment by MI-KY** [comment]
I would like to add that as @Massedil said having a full view of the sender mail could be important. So maybe the mail address could be shown *by default* beside the sender name (as that could and will be easier faked). If then the user changes the default setting to see only the name without the address it would be his/her decision.

**Comment by relikd** [comment]
I would rather hide the name instead of the email address but then again, I am technically able to parse that information. Others might not. ... But if I think about it, I really do use the name field regularly. I often get emails from people I never had contact with and the name field is often helpful to reply to a name if they havent written their name in the email body. So I think I would include both, name and email address.
Back to the screen size discussion, would it be ok for the mobile phone to scroll the header area? I like that the header is fixed on the desktop version because I can quickly switch between mails. But on mobile, whenever I open a new email, I will see the header first anyway. So maybe this could scroll out of the way? (I havent used Snappy on mobile so I cannot say whether that is the case already)

**Comment by the-djmaze** [comment]
I've made changes so that almost all headers scroll now (except subject and from).
From that perspective  it would become easier to show name + email as the header doesn't use fixed space anymore.

**Comment by relikd** [comment]
A small improvement. @Massedil mentioned to use a grid for the header information While this will make it much more readable, it will also waste space if there is just one long label name. For example, "Spam-Score" would push the short "CC" label way back and leave blank space instead. (you can see that already with the "Date" label in the after screenshot.
So, instead, I would propose to only indent the value-field. Currently the "<snappymail" and "<subscribed" text is aligned with the labels. It would be much better though, if they would be aligned with the beginning of the data field (after the colon). This way you see immediatelly if a line belongs to a previous label or starts with a new one.

**Comment by the-djmaze** [comment]
For now it will stay as it is with the added changes.
Other changes currently have too much impact on responsive design.

If someone has idea's and CSS that works responsive, feel free to discuss, open new issue or commit as PR.
