### ISSUE TITLE
The page does not change after batch deletion

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#684]
**SnappyMail version, browser, browser version:**
2.21.3
**Expected behavior and actual behavior:**
I have over 30 pages of emails on my mail server, with 20 emails per page.
I check all of the emails listed on the last page and do a bulk delete.
At this time, in previous versions, it would transition to the first page after the process was complete. Since I changed to this version, it sometimes stays "loading" or "blank" all the time.

This is a feature request, but when the last page is missing, I would like to be able to view the last page instead of going back to the first page. Example, I will delete all emails listed on Page 20. At this time I would like Page 19 to be displayed instead of going back to Page 1. I understand that I can reverse the sort order....

**Steps to reproduce the problem:**
1. Display the listings in multi-page view.
2. Go to the last page.
3. Check the box for all emails(on last page).
4. Click on the trash icon to delete it.

**Comment by the-djmaze** [comment]
Yes, the code was to go to page 1 and i removed that.

I will look a to make a check and jump 1 page.
