### ISSUE TITLE
Mobile View on cellphones: automatic scrolling not working near the visual keyboard

### ISSUE THREAD

**Issue by Reis-A** [the-djmaze/snappymail#686]
**Describe the bug**
When you use the next cloud snappymail mobile app and start composing an email on a mobile phone (android or iPhone) with many lines the following happens.
The compose email window doesn't scroll down the way it should once u approach the virtual keyboard.
After writing more and more lines, eventually the cursor moves under the virtual keyboard and the text you are typing is created underneath the virtual keyboard. Of course by manually scrolling down again, the text is visible again. 
It is just a little inconvenience for the end user...

**Expected behavior**
Scroll down automatically when starting a new line
**Screenshots**
![image](https://user-images.githubusercontent.com/114596917/202798824-3a1b8d1b-f734-408f-bba3-d74f4c6c9afc.png)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile] chromium
- IMAP daemon: [e.g. courier, dovecot] 
- PHP version: 8.1.9
- SnappyMail Version: 2.21.3

**Comment by the-djmaze** [comment]
I just tested with line numbers and indeed two lines are behind the keyboard (19 & 20)
![Screenshot_2022-11-18-22-58-12-729_org mozilla focus](https://user-images.githubusercontent.com/3752035/202810281-044ca970-2504-4258-b750-39d5bbff46a0.jpg)

**Comment by the-djmaze** [comment]
You can test on https://snappymail.eu/demo

**Comment by Reis-A** [comment]
Now after typing a letter it scrolls automatically. Yes!
My observation now:
If you just push the new line button without any letters the cursor stays
behind the keyboard. It scrolls up as soon a letter is typed again.
But it is definitely an improvement overall. Thanks

the-djmaze ***@***.***> schrieb am Sa., 19. Nov. 2022, 14:35:
