### ISSUE TITLE
Will there be a publicly available container image for pulling into cloud deployments?

### ISSUE THREAD

**Issue by Leopere** [the-djmaze/snappymail#687]
**Is your feature request related to a problem? Please describe.**
Building containers in a Docker Swarm context is impossible and having to build locally then distribute images is arduous and may require a private docker registry.

**Describe the solution you'd like**
It would be wonderful if, like RainLoop, there was a publicly pullable Docker repository.

**Describe alternatives you've considered**
Using CI/CD to deploy my own containers of this fork.

**Additional context**
nothing further.

**Comment by the-djmaze** [comment]
Did you read #44 ?

Also there's a big problem why i don't distribute.
There must be local storage for personal data and evreryone deploys differently so that storage is maintained when you replace the docker image.

**Comment by Leopere** [comment]
I didn't see #44 I had searched by a few key terms like container and docker but somehow 44 didn't come up.  I'll have a glance over it now and see if I can interpret a way to get this working where I don't have to build and push to my own container registry or if this just wont work in my deployment.  As it is when apps don't find a way to run these maintenance scripts simply on first boot rather than during compile time it drastically complicates deployment.

**Comment by Leopere** [comment]
Duplicate moving to #44
