### ISSUE TITLE
No more image viewer ?

### ISSUE THREAD

**Issue by augras** [the-djmaze/snappymail#688]
**Is your feature request related to a problem? Please describe.**
I just upgrade  from rainloop and now when i want to see an image join to a message it opens in a new tab or window, or can be download : the very nice viewer, style lighgallery, there is in rainloop is no more here.
Maybe there was something wrong during the update are it's normal ?

**Describe the solution you'd like**
I would like to get back the nice viewer, or an other one, and if possible the viewer works for  other files (video, pdf...)

Thank you for this great works and for your attention,

Philippe

**Comment by the-djmaze** [comment]
Correct it's gone and won't be back.

**Comment by the-djmaze** [comment]
Correct it's gone and won't be back.

Problem with things like PhotoSwipe, LightGallery, etc. is that they are hardly used in mail as most emails are not photo albums.

While SnappyMail tries to be as light as possible, this makes it doubtfully bigger.

Ok, 50KiB is not that much compared to something like OpenPGP.js.
Yet, it is not sufficient for email.
