### ISSUE TITLE
Cannot save verified "Tested" domain. "Can't connect to host "tcp://localhost:143"

### ISSUE THREAD

**Issue by CSchaefer70** [the-djmaze/snappymail#689]
**SnappyMail version, browser, browser version:** 2.21.3

**NextCloud Version.** 25.0.1

**Expected behavior and actual behavior:** 
The expected bevaviour is that after install of the app and update of the "Domain/White list" I can then access email thru the SnappyMail app on the dashboard of NextCloud.  Actual is that I cannot... always blocked with "Can't connect to host...". 

I have been using Rainloop without issue.  After update of NextCloud to 25.0.1 (separate installation on the same VPS with Ubuntu 20.4) I noted Rainloop deprecated.  So I decided to got to SnappyMail.  The install seemed normal.  I updated the configuration with new password, MySQL correction to my DB. But the Domain cannot "Save" verified imap/pop3 settings.  It verifies using the "Test" submit but when updating it does not save the SSL or StartSSL.  It does seem to save the "Whitelist".  When I attempt to use the app on the nextcloud app I always receive "Can't connect to server - Server message: "Can't connect to host "tcp://localhost:143"

![image](https://user-images.githubusercontent.com/26978180/202923106-94ada504-0bba-46d1-bf52-485dac4e6dd7.png)

Do I need a separate certificate?  If so how to install??
 

**Steps to reproduce the problem:**
Install the app
Open the admin of SnappyMail
Goto "Domain"
"add domain"
Add credentials of email service (IMAP)
Select "Test" to confirm
Select "Update"
Select the domain again to confirm... "not saved"

**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/26978180/202922807-a568a448-eea2-4118-a367-88237700e598.png)

![image](https://user-images.githubusercontent.com/26978180/202922822-fccc57e3-ab89-4f61-93ed-5c2b3f0ed49f.png)

MySQL:

Type: mysql

Version: 10.6.7

Size: 15 MB

PHP: 

Version: 8.1.12

Memory limit: 512 MB

Max execution time: 3600

Upload max size: 356 MB

Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, apache2handler, gmp, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Comment by MI-KY** [comment]
Just to be sure: you insert the imap and smtp info of your domain and after saving the security configuration in the dropdown is not saved? Or the whole imap configuration?

Do you use the autologon functionality of Nextcloud to automatically login to Snappymail? Or did you configure your login credentials under "additional settings" in your Nextcloud preferences? I'm asking because maybe SnappyMail is using the default domain config introduced by the Nextcloud integeration.

**Comment by CSchaefer70** [comment]
Hmmm... not completely following.  The Nextcloud "Additional settings" looks like this:
![image](https://user-images.githubusercontent.com/26978180/202928267-1360c704-c613-49de-b476-9f3f4498c034.png)

On the SnappyMail Admin Panel this is what I see:
![image](https://user-images.githubusercontent.com/26978180/202928362-d8d2aaac-ac63-4773-878d-b36b2b733052.png)

then I go to "Domains":
![image](https://user-images.githubusercontent.com/26978180/202928392-eb8fa8c7-46af-43ac-9f6d-405e07a06a13.png)

I select a domain I want to add... in this case "sheoki.com"
![image](https://user-images.githubusercontent.com/26978180/202928456-038d2a3f-56d7-41cc-aa70-21fe7173e5dd.png)

Now I drop the menu to SSL/TLS for the imap and  StartTLS for the smtp:
![image](https://user-images.githubusercontent.com/26978180/202928513-929a8088-3042-49bf-8416-3cad9bf2afc8.png)
![image](https://user-images.githubusercontent.com/26978180/202928530-546b5ec1-c934-42a2-bc27-dd909d50ddc5.png)

Then I "TEST":
![image](https://user-images.githubusercontent.com/26978180/202928588-49810ffd-475f-4182-ad32-8af32a9dccc1.png)

The TEST comes back POSITIVE:
![image](https://user-images.githubusercontent.com/26978180/202928609-2bde1a0b-c5d9-454b-b7ff-80f33d18c072.png)

Now I select "Update" and then select the domain "sheoki.com" again and nothing is saved:
![image](https://user-images.githubusercontent.com/26978180/202928662-7d0a60e8-a4be-47c1-b947-aa62825f3dbf.png)

So just to test I go to the "SnappyMail" app via the NextCloud instance:
![image](https://user-images.githubusercontent.com/26978180/202928766-e32947cd-2920-4de6-8857-b4b40146b644.png)

I select the app:
![image](https://user-images.githubusercontent.com/26978180/202928788-da111566-6157-4d4f-a7b7-f9bea80dd653.png)

I input my password and...
![image](https://user-images.githubusercontent.com/26978180/202928832-db10fd01-2333-4fee-bf1d-dea5dd9ca752.png)

Also... my personal profile for email...
![image](https://user-images.githubusercontent.com/26978180/202928888-2d2db08d-c480-4472-bf3a-6293c2728b92.png)


*******************
Do you think this is a conflict with another instance of NextCloud v24.x.x on the same VPS?

The Rainloop works correctly on that version.  The only difference is the DB and the Subfolder [ /var/www/html/nextcloud/  vs  /var/www/html/nc/ ]:
![image](https://user-images.githubusercontent.com/26978180/202928966-e32b6b07-df28-4f09-a7bf-d113752a9862.png)

*********************
I made a new copy of NextCloud to avoid "update" conflicts with existing apps like "apporder" and "custom menu".   I thought that would provide a clean fresh install of NextCloud Hub3 and the apps!!!

Thx for any help.  I promote Rainloop and NextCloud to anyone that listens.  I'd like to use SnappyMail as it seems faster with more options!  Also, getting great reviews.

**Comment by CSchaefer70** [comment]
if you want to play directly to review I appreciate any help.  I can send credentials NextCloud Admin credentials separately?

**Comment by MI-KY** [comment]
Personally I don't think that the other nextcloud should conflict with your NC v25 because SnappyMail saves the settings inside the data subfolder of your nextcloud... I also had a Rainloop and SnappyMail install side by side on the same Nextcloud without problems...

The fact, that the configuration of the security settings seems not to be saved is really strange and could be a bug. The only thing that makes me wonder is, that the error talks about localhost instead of your imap server ionos.com.
You seem to have two other domain configurations ("localhost" and "*"). Do you need them? Otherwise you could try to delete them just to see if SnappyMail would then try to connect to the correct server ionos.com.
But as said the thing that it's not saving the security config seems a bit strange...

**Comment by CSchaefer70** [comment]
Yes.  I agree.  I was surprised to see "localhost".  I'll try to delete, restart the VPS, login to nextcloud v25.0.1, go to the Snappy Admin and add fresh to see what happens!!!!!!!!!!

**Comment by CSchaefer70** [comment]
INTERESTING!

So I deleted all Domains within the SnappyMail Admin Panel.  Then added a completely different one "kingdomharvest.club".  I confirmed with the "Test".  All good.  However, this time I do not have an "Update" option but rather "Add".  So I select "add".  But, still, it also does not "Save".  

When I test the app within NextCloud a slightly different msg:
![image](https://user-images.githubusercontent.com/26978180/202934436-7652d5f6-367c-47c0-a887-6209f4f3334f.png)

I'll try the RainLoop within the NextCloud v25.0.1 to help isolate this issue.

Any feedback is appreciated!

**Comment by MI-KY** [comment]
Hi,
ok this makes more sens I think: the error with "localhost" could had to do with the other domain configs. There the question is, if one of the others jumps in to early before your specific domain configuration.

Lets say that now - also if you actually can't login - the situation seems normal from the domain configuration point of view. Now the "only" thing that is missing is the correct configuration of the login security... I will try the same today to see if my install is also affected. Maybe this has to do with the rework of the SSL options around 11 november and affects only new domain configurations...

**Comment by MI-KY** [comment]
Ok, can confirm this happens also to me - the-djmaze has already pushed a commit for this 😉

**Comment by the-djmaze** [comment]
I've added a domain match test on the Admin -> Domains page.
So with next release you can test there which domain matches your login username.

**Comment by CSchaefer70** [comment]
Nice!  Wow, I really am impressed at the response.  Thank you!!!  I'll look for the new release.

If you want me to test any new features I'm happy to setup a Beta NextCloud on my VPS and try your amazing stuff.

**Comment by the-djmaze** [comment]
Your welcome.

You are not the only one with this struggle, so for now it is simple.
And when people still have no clue, i will replace the simple alert() box with a full blown visible trace.
Although, that trace is already available in the logs when you enable logging 😉

**Comment by MI-KY** [comment]
Can confirm that the latest release solves the problem with the security dropdown 👍 .
For the check basing on the username: great thing but should have some text beside to let the user know what this does 😉

**Comment by CSchaefer70** [comment]
Hey! Wanted to let u know I installed the update v2.21.4 on NextCloud 25.0.1.  The install was quick and works great.  Outstanding!!!

I added several different domains without difficulty.  Also, I noticed that the load time is faster then Rainloop... on my Ubuntu 22.04 VPS with an ASUS ZenBook Win11 SnappyMail loades in less the 1/4 second. Sweet!!!!

Also, LOVE the new editor with ability to link NextCloud directly, HTML display and so much more.  Really looking great.  One comment... I would love the ability to edit with "Bullets" and "Numbering".  But I'm NOT complaining!!!!!!!!!!! Thank you again.

![image](https://user-images.githubusercontent.com/26978180/203384689-7a12efcb-8e9c-48a7-90be-4c97f3001ffc.png)

**Comment by CSchaefer70** [comment]
I do have one question on third party accounts like "Gmail".   Is there an "allow third part/self server" option?

I ask because I attempt to add a "gmail" account and although it allows in the SnappyMail Admin/Domain with a positive test, the app response is "Can't connect to server...":
![image](https://user-images.githubusercontent.com/26978180/203390780-02df3828-d698-471e-9749-d090c102bdc5.png)
![image](https://user-images.githubusercontent.com/26978180/203390837-03e18ca6-7286-4fad-9fb2-3c358df2512c.png)
![image](https://user-images.githubusercontent.com/26978180/203390960-e6164d67-6bdb-4dcb-bc2d-fb40d6ff6c1c.png)
![image](https://user-images.githubusercontent.com/26978180/203391161-b9f14617-64d6-464b-8526-03b6434ee085.png)

**Comment by CSchaefer70** [comment]
I'm trying to update and replace the RainLoop app on my older NextClodu v24:

![image](https://user-images.githubusercontent.com/26978180/203392527-d92691f0-9c61-46f2-899e-d88871998bbb.png)

Here is a webshot of the RainLoop Admin:
![image](https://user-images.githubusercontent.com/26978180/203392892-73942bc7-a166-452b-b201-a7caed4bb709.png)
![image](https://user-images.githubusercontent.com/26978180/203393034-7681fb85-f3d3-40a0-9437-6946eac59906.png)

**Comment by elhananjair** [comment]
@the-djmaze 
I am confused here, if someone does not specify the domain on snappymail settings, is it impossible to log in with different mail domains?

I just tested an email address with a domain not specified on snappymail setting, and it says it matched *, when I click on the * option, I saw localhost and port 143 is assigned there, but it is not working for me with the same error `Server message: Can't connect to host "tcp://localhost:143"`

**Comment by the-djmaze** [comment]
@elhananjair you should have an IMAP daemon running on localhost.
If not, it indeed can't connect.

**Comment by antenehket** [comment]
@the-djmaze 
I installed Dovecote Imap on my server, as you say, to elhananjiar to locate any domains that are not listed in the domain list. However, I ran into this issue.
![Capture](https://github.com/the-djmaze/snappymail/assets/79003144/9ff3a499-5671-4e42-b49f-dbae1e3573e0)
 is installing Postfix Server necessary to fix this?
