### ISSUE TITLE
Option to show all folders, subscribed or not.

### ISSUE THREAD

**Issue by realsimix** [the-djmaze/snappymail#69]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to show all folders, regardless whether they are subscribed or not.

**Describe the solution you'd like**
Simply have an option 'Show all folders'.

**Describe alternatives you've considered**
Maybe some auto subscribe feature would also work but seems more complicate.

**Additional context**
The same would be nice to have for 'check for new mail' as well but I understand that is a quite expensive thing even with IDLE support. However, just showing the folders should be doable if 'imap_folder_list_limit' is set high enough.

Thanks,
Simon

**Comment by the-djmaze** [comment]
You can disable the subscribe option.
`/_data_/_default_/configs/application.ini`
`use_imap_list_subscribe = Off`

**Comment by realsimix** [comment]
Thanks, that's nice to know. So it's there, only no option in the admin panel for it.

Thanks,
Simon

**Comment by realsimix** [comment]
BTW, I found this key is not used, maybe it could be removed?

```
diff -Nau a/app/libraries/RainLoop/Config/Application.php b/app/libraries/RainLoop/Config/Application.php
--- a/app/libraries/RainLoop/Config/Application.php	2021-03-25 13:54:51.000000000 +0100
+++ b/app/libraries/RainLoop/Config/Application.php	2021-03-26 16:45:26.839106217 +0100
@@ -306,7 +306,6 @@
 			),
 
 			'labs' => array(
-				'ignore_folders_subscription' => array(false),
 				'update_channel' => array('stable'),
 				'allow_prefetch' => array(true),
 				'allow_smart_html_links' => array(true),

```

**Comment by the-djmaze** [comment]
Yes can be removed then

**Comment by the-djmaze** [comment]
Added your feature request

**Comment by realsimix** [comment]
Thanks, very nice!

**Comment by the-djmaze** [comment]
Made a little improvement to always hide `\noselect` folders.

**Comment by realsimix** [comment]
I just found a little cosmetic error: when switching "Hide unsubscribed folders" to on, the folder list gets adjusted immediately. When switching "Hide unsubscribed folders" to off, the folder list doesn't get updated until you reload the page.

Somehow the folder refresh is missing.

**Comment by mohsensaeedi** [comment]
How we can hide unsubscribed folder for all users by default? I set many options in application.ini and none of them works for me

**Comment by the-djmaze** [comment]
They are user specific settting.

**Comment by mohsensaeedi** [comment]
I know but we enabled EXPUNGE folder to keep deleted email by user for 10 days and we want disable unsubscribe folder by default. Some users get confused when they see it. 
So i think it is necessary to have this option as global option in application.ini

**Comment by the-djmaze** [comment]
Folders do not expunge, the messages are.
And since people can use other mail applications, i see no use for bending the rules.
It will only confuse people even more.
