### ISSUE TITLE
Auto Save while Editing a Draft causes keyboard failure

### ISSUE THREAD

**Issue by bk-king1** [the-djmaze/snappymail#690]
**SnappyMail version, browser, browser version:**

Snappymail 2.21.3
Chrome: Version 107.0.5304.110 (Official Build) (arm64)
Safari: Version 16.1 (18614.2.9.1.12)

**Expected behavior and actual behavior:**

Editing a draft should not cause 'weird' keyboard behaviour

**Steps to reproduce the problem:**

Create a new message. Save it. Navigate back to inbox. Go back to drafts folder. Open the draft message and click the edit link.
Continue typing your message until the autosave kicks in. At this point, I have noticed a number of things start to fail
1: somehow it selected the entire message body and deleted it and moved the cursor to the To field. I have not been able to work out what actions on my behalf actually force this error. I think it may be as I am typing and using backspace or something.
2: Space bar does not work. Whiletypingasentencethespacesjustdontwork < Like that
3: When trying to use the arrow keys, I can see that whilst the edit draft window is still open and focused, the arrow keys are focused on the window behind - I can see the up and down arrow moving within the folder list. Left and right arrow does seem to cause focus to move between the background folderlist and focused drafts editing window - but right arrow was forcing the cursor to go 'down'

I dont know if this is just environmental but I have replicated this in 2 browsers, so would be great if you could test and see if you see the same thing.

**Comment by bk-king1** [comment]
I also see the same behaviour in 2.17.2

**Comment by the-djmaze** [comment]
Could you try the steps i've mentioned in https://github.com/the-djmaze/snappymail/issues/860#issuecomment-1386965160 ?

**Comment by bk-king1** [comment]
Just tried as you suggested - but the issue is no longer occurring. In the console I see

Shortcuts scope set to: Compose

NOTE: Since I logged this one I have moved to Ver: 2.24.6 - I seen the issue in 2.21.3 and earlier.

**Comment by the-djmaze** [comment]
Ok, then i will close this issue. Feel free to open a new one or comment to #860 when it occurs again.
