### ISSUE TITLE
Not showing the correct SSL settings when modifying domain (Nextcloud)

### ISSUE THREAD

**Issue by jiriks74** [the-djmaze/snappymail#692]
**Describe the bug**
When you modify domains in SnappyMail's admin panel the settings for SSL communication are not correctly loaded

**To Reproduce**
1. Go to Nextcloud settings and open SnappyMail's admin panel
2. Click on `Domains`
3. Open one of your domain's settings
4. Select `SSL/TLS` or `STARTTLS`
5. `Update` the settings
6. Open the domain's settings again
7. The secure field has `None` selected

**Expected behavior**
The saved encryption option should be shown

**Screenshots**
<details>
<summary>Saved settings</summary>

![image](https://user-images.githubusercontent.com/54378412/203345166-5c3e40fd-1f02-4068-a5af-8ee89712aa33.png)

</details>

<details>
<summary>Settings after reopening</summary>

![image](https://user-images.githubusercontent.com/54378412/203345331-338df356-1143-4bf5-8a1c-cc0534048031.png)

</details>

**Please complete the following information:**
- Browser: Firefox 107.0
- IMAP daemon: IDK
- PHP version: 8.1.12
- SnappyMail Version: 2.21.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
None found in Nextcloud's log even after allowing `Debug` mode

**Comment by the-djmaze** [comment]
Resolved in 2.21.4
