### ISSUE TITLE
Invalid response: VXNlcm5hbWU6CG

### ISSUE THREAD

**Issue by jiriks74** [the-djmaze/snappymail#693]
**Describe the bug**
Cannot send messages, when trying to test the smtp settings in admin panel I get `Invalid response: VXNlcm5hbWU6CG`

**To Reproduce**
1. Go to SnappyMail's admin panel
2. Click on `Domains`
3. Click `Add domain`
4. In IMAP set server address to `imap.atlas.cz` and set `Secure` to `SSL/TLS`
5. In SMTP set server address to `smtp.centrum.cz`, set `Secure` to `SSL/TLS`, verify that `Use authentification` is on and `Login as sender` is on as well
6. Test the settings with an email address registered on https://atlas.cz

**Expected behavior**
Test is successful and I can send emails.

**Screenshots**

<details>
<summary>Failed test in <code>Domains</code> settings</summary>

![image](https://user-images.githubusercontent.com/54378412/203357148-7ac31705-8024-410a-9e0d-31455b7c4718.png)

</details>

**Please complete the following information:**
- Browser: Firefox 107.0
- IMAP daemon: IDK
- PHP version: 8.1.12
- SnappyMail Version: 2.21.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
I didn't see anything in Nextcloud's logging tool even after enabling `Debug` in SnappyMail's settings

**Comment by the-djmaze** [comment]
Where is your debug/log?

**Comment by jiriks74** [comment]
Ok, I'll post the one from nextcloud, but there were no errors that are related to snappymail

**Comment by the-djmaze** [comment]
1. Nextcloud admin additional settings
2. Checkbox debug
3. Save
4. Test
5. Open `data/app_snappymail/.../logs/*`

**Comment by the-djmaze** [comment]
I've base64 decoded `VXNlcm5hbWU6CG` and i see the problem.
It says `username:[]` which is incorrect.
It should be `username` so someone screwed up the imap communication.

I can make a workaround but atlas should fix their IMAP implementation.

**Comment by the-djmaze** [comment]
I see the problem.
```php
base64_decode('VXNlcm5hbWU6CG') == 'Username:'
```
The last character is 0x08 which is `backspace` and should not be in there.
The valid code for login should be `VXNlcm5hbWU6`.

This means their implementation of `LOGIN` or `AUTHENTICATE LOGIN` is broken.

**Comment by jiriks74** [comment]
I wrote to the helpdesk and they said that they'll fix it in the upcoming week. I'll leave a comment once they do and wether it works now.
