### ISSUE TITLE
FEATURE REQUEST: Add link to Talk-Conversation or create new one

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#694]
In some mails it would be great to be able to add existing talk call links or create new calls.

1. Button "Add/create Call to message" like the add Files Button
2. A dialog for selecting or creating a new talk conversation should be visible.
3. The Dialog should be able to set the NEW conversation to "public/registered users" if needed (Checkbox)
4. After finishing the dialog, the Link should be pasted at a specified position "JOIN the Converdation: <<LINK>>"

**Comment by the-djmaze** [comment]
What is a "Talk-Conversation" ?!?

**Comment by Bolli84** [comment]
The Chats/Conversations in Nextcloud "Talk" application (former Spreed) https://apps.nextcloud.com/apps/spreed

**Comment by the-djmaze** [comment]
So it's like the free and powerfull [Jitsi Meet](https://meet.jit.si/)?

**Comment by Bolli84** [comment]
It is technically similar to Jitsi, but in nextcloud integrated

**Comment by the-djmaze** [comment]
I've figured out to get a list of all open talks:
`https://example.com/nextcloud/ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true`
```json
	{"ocs":{
		"meta":{"status":"ok","statuscode":200,"message":"OK"},
		"data":[
			{
				"id":1,
				"token":"hcmoyqug",
				"type":4,
				"name":"mhxsolut",
				"displayName":"Talk updates \u2705",
				"objectType":"",
				"objectId":"",
				"participantType":3,
				"participantFlags":0,
				"readOnly":1,
				"hasPassword":false,
				"hasCall":false,
				"canStartCall":true,
				"lastActivity":1710849663,
				"lastReadMessage":44,
				"unreadMessages":0,
				"unreadMention":false,
				"unreadMentionDirect":false,
				"isFavorite":false,
				"canLeaveConversation":true,
				"canDeleteConversation":false,
				"notificationLevel":2,
				"notificationCalls":1,
				"lobbyState":0,
				"lobbyTimer":0,
				"lastPing":0,
				"sessionId":"0",
				"lastMessage":{},
				"sipEnabled":0,
				"actorType":"users",
				"actorId":"snappymail",
				"attendeeId":1,
				"permissions":246,
				"attendeePermissions":0,
				"callPermissions":0,
				"defaultPermissions":0,
				"canEnableSIP":false,
				"attendeePin":"",
				"description":"",
				"lastCommonReadMessage":44,
				"listable":0,
				"callFlag":0,
				"messageExpiration":0
			}
		]
	}}
```

A link to a talk is:
`https://example.com/nextcloud/call/hcmoyqug`

But creating a new talk with all the features is not easy.
