### ISSUE TITLE
BUG | Sending of emails not possible anymore with 2.22.0

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#695]
**Describe the bug**
Sending of emails not possible anymore.

**To Reproduce**
Click "New email", enter recipient and click "Send".

**Expected behavior**
Mail is sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/43847817/203572800-791a7753-c0f3-45bd-944b-e4bae9cd5676.png)

**Please complete the following information:**
- Browser: Firefox 107.0
- IMAP daemon: mailcow
- PHP version: 7.4
- SnappyMail Version: 2.22.0

**Additional context**
Error in network tab of developer tools:
`{"Action":"SendMessage","Result":false,"ErrorCode":302,"ErrorMessage":"","ErrorMessageAdditional":"Invalid response: VXNlcm5hbWU6","Time":2391}`

**Comment by codiflow** [comment]
Downgrade to 2.21.2 fixed the issue.

**Comment by the-djmaze** [comment]
Ok, this is caused by workaround for #693
I will change it back and look why mailserver of #693 is so horrible.
