### ISSUE TITLE
Search filter for ALL email accounts/Unite Accounts or use NextCloud Collectives?

### ISSUE THREAD

**Issue by CSchaefer70** [the-djmaze/snappymail#702]
**Is your feature request related to a problem? Please describe.**
No not a problem just a convenience with potential reach into NextCloud.  After installing SnappyMail I added 7 email address from various domains.  They work well, but, the inability to search ALL accounts for a particular "from" or any of the excellent filters is inconvenient.

**Describe the solution you'd like**
An addition to "Search" with a search drop menu in the "Advanced" search.  The default would be the current email account open with a drop menu to "Search ALL email accounts" or a particular email account(s) [from the list of existing accounts].
![image](https://user-images.githubusercontent.com/26978180/203776258-3cf940d6-6d3c-41af-b00d-13d36a3c5689.png)

**Describe alternatives you've considered**
An option to merge all email accounts into a unified group? Example is a solution I have been using with typeapp:
![image](https://user-images.githubusercontent.com/26978180/203776937-b0f4bd6e-5510-4b8f-a8f6-8b439d7c3e73.png)
https://typeapp.com/features/

**Additional context**
Much of the reason for this is to send bulk or group msgs that have grown from one person collaboration/discussion to several with separate email accounts with separate domains.  So the ability to display a "Merged" version of all email as well as keep the email separate is often a time saver.  Essentially create email groups from different email accounts that involve users who are not on NextCLoud.
![image](https://user-images.githubusercontent.com/26978180/203777910-c48dedf4-8abb-45a0-80d2-46f52c57498e.png)

Another alternative would be a make a NextCloud Collectives within NextCloud and have a link in the address book?  Or after searching and finding multiple email address have a checkbox inline with each "found"; by checking an email would create or add to a NextCloud "Collectives"?

A different approach would be to include a "Group" option in the "ADD CONTACT" address book... which is kinda there with additional emails "+".  However, this would address the "Group" context but not just searching for information for multiple emails.
![image](https://user-images.githubusercontent.com/26978180/203779156-d654ceb7-c788-4ec1-8be8-314854060a2e.png)

**Comment by the-djmaze** [comment]
Please read #650 and #199

**Comment by MI-KY** [comment]
What would you like to do with Nextcloud Collectives? Isn't that a type of wiki inside of Nextcloud? 🤔

**Comment by CSchaefer70** [comment]
Hmmm... yes.  Perhaps just a way to engage people in a common goal and not currently within the NextCloud user base.  A great way to link NextCloud to an email solution.  Personally I'm disappointed with the NextCloud Mail app.

**Comment by MI-KY** [comment]
Sorry but the solution to have a link to Nextcloud Collectives out of SnappyMail isn't completly clear to me (i don't clearly understand your goal at the moment).

But: could it be that - although a global search isn't possible at the moment - your primary problem would be solved with the possibility to send a email to a group of persons that all are grouped inside your addressbook? 
Lets say you have ten people inside your nextcloud addressbook and you add all of them to one category. Then you would like to send a mail to all of them by choosing this category instead of inserting every single mailaddress? Is this the goal you would like to achieve?

**Comment by CSchaefer70** [comment]
This is not essential just a potential NC feature... not critical in the big picture of all you have going on!!

But, yes, it's NextCloud feature more then a SnappyMail thing.

Yes. You are correct.  Placing them into one project or category or collaboration.  The idea was to allow passive inclusion of new email clients, thus users, into NextCloud (via a collaborative project/group/circles) for those that are not part of the current NextCloud "Users" by intrinsically making them part of a "Collectives" which will require [push a new user creation] them to be a NextCloud User.

However, from the SnappyMail "Contacts" I can make a "group" by naming the contact a group-name then using the "+" to add email addresses.  Then simply include that into the NC Collectives file, but, I can't add a Collective participant without being a NC user.

So, the part missing is the necessity to create a NC User for the "NEW" user group and then using that to add to the collaborative NC "Collectives" app.

************

Loving the SnappyMail vs Rainloop.  Also, much better then the STD NC Mail.  Nice!!!
