### ISSUE TITLE
Save as .eml from Hamburger drop if email is checked.  Where is the email .eml file stored?

### ISSUE THREAD

**Issue by CSchaefer70** [the-djmaze/snappymail#704]
**Describe the bug**
Unclear where if any action on "Save as .eml in NextCloud" ONLY when using checkbox.  Cannot locate archive SaveTo location.

Save ARCHIVE to NextCloud works well with two other methods.

**To Reproduce**
1. Go to 'SnappyMail" inbox
2. Click on 'any incoming" mail checkbox
3. Select "hamburger" and engage "Save as .eml in NextCloud"
4. Click
5. Where did it go?

**Expected behavior**
By selecting one or more email messages, select Hamburger/Save as .eml in NextCloud" and an option is presented to select or create a folder.
![image](https://user-images.githubusercontent.com/26978180/203809937-215ae3d6-e0b4-412a-be04-6b1904ebb1e1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/26978180/203808383-00ca7068-287e-4d38-aaa6-2a1117ed6014.png)

**Please complete the following information:**
- Browser: Firefox 107.0 (32bit)
- IMAP daemon: dovecot
- PHP version: 8.1
- Ubuntu 22.04
- SnappyMail Version: 2.22.1
- MySQL: 10.6.11
- Server: OS: Linux 5.15.0-53-generic x86_64, CPU: Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz (2 cores), Memory: 1.90 GB

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Don't have this... but let me know what and how to get?

**Additional context**
Understanding use and method of Archiving EMAIL.  The methods I see include:

- Use Archive menu button.  This works and add to a copy of the msg to an Archive Folder:

![image](https://user-images.githubusercontent.com/26978180/203811309-e55ed275-6176-4a03-940a-ff0e74ee5fff.png)

- Select email msg (not checkbox) and then use "Hamburger drop menu" from msg body window.  This works and offers an excellent menu option:

![image](https://user-images.githubusercontent.com/26978180/203811780-a410318a-6d19-4eb2-8a0d-60f5227f7140.png)

- Select email msg checkbox and use the "Hamburger drop menu" to push to NextCloud.  This may work but where does it go?

![image](https://user-images.githubusercontent.com/26978180/203812228-101b30e0-2d42-415f-8095-1165140115a4.png)

**Comment by the-djmaze** [comment]
> * This may work but where does it go?

It didn't work due to a bug

**Comment by CSchaefer70** [comment]
Oh. OK. Thanks for the outstanding follow-up!

I see the code changes... wow, you're on top of this - great work!!!!!!
