### ISSUE TITLE
User cannot edit account in snappymail settings

### ISSUE THREAD

**Issue by as400l** [the-djmaze/snappymail#706]
I am not sure whether this problem is related only to my installation or not.

The issue is that when a user goes to "Snappymail settings" ---> "Accounts", the account cannot be edited. One can add a new "account" but not edit existing one. At the same time the "Identities" can be edited.

**Comment by the-djmaze** [comment]
Correct, the "Account" that you login with is fixed/readonly.
There is nothing to configure because an "account" is nothing more then user/password.

Should i remove the listing so you know for 100% that you can't edit it?

**Comment by as400l** [comment]
OK, that explains things.
As to your question - I'm not sure. 
And what if a user wants to enter password ? That's where my question came from.


P.S. Thanks for your work. It's just great ! So much better than the default mail app :P

**Comment by the-djmaze** [comment]
> And what if a user wants to enter password ? That's where my question came from.

Then logout and login again ;)
You should see login screen as the mainaccount settings.


> P.S. Thanks for your work. It's just great ! So much better than the default mail app :P

Thanks!

**Comment by as400l** [comment]
Oh wait, I might have not expressed myself clearly enough.

My setup is that users are in ldap. So nextcloud will not autologin them to snappymail. So I thought maybe if users were able to enter their password manually in snappymail settings that would resolve problem of autologin.

**Comment by the-djmaze** [comment]
Option 1: `Nextcloud -> Settings -> Additional settings` Save username and passphrase there.
Option 2: `Nextcloud -> Admin Settings -> Additional settings` try different login modes

**Comment by as400l** [comment]
Of course - option 1 is more than enough. Now I feel stupid...

Thanks !

**Comment by as400l** [comment]
Resolved - username password can be saved in users Nextcloud profile in "additional settings".
