### ISSUE TITLE
-- drag & drop folder expansion --

### ISSUE THREAD

**Issue by scubamuc** [the-djmaze/snappymail#707]
**drag & drop folder expansion**
a central mail user handles all incoming mails missed by *procmail sort* and "manually" drops these into inbox-folders and subfolders. When dragging an email onto an inbox-folder with subfolders, the folder should expand when hovering to display the subfolders for dropping the email.

**To Reproduce**
1. Go to ' Inbox and grab mail'
2. 'Drag mail onto inbox-folder'
3. 'Expect inbox-folder to expand, displaying subfolder'
4. 'Folder not expanding when hovering on folder'

**Expected behavior**
Subfolder expansion on hovering while drag&drop

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54933878/203962429-72d47d04-d008-4941-8114-38d0ad20efce.png).

**Please complete the following information:**
- Browser: [Firefox, Chromium, Edge, Mobile]
- Nextcloud-snap 24.0.6
- SnappyMail Version:  2.22.1

**Comment by the-djmaze** [comment]
Are you sure?

As it works in Firefox on the demo.

https://user-images.githubusercontent.com/3752035/203967694-aa7e6573-a224-4372-badb-874a8814309a.mp4

**Comment by scubamuc** [comment]
@the-djmaze yip I'm sure. It doesn't work on any of my Nextcloud instances.

**Comment by the-djmaze** [comment]
It works here fine with Nextcloud and Firefox 104.

Just move mouse over "INBOX" wait a second (don't move mouse!!!)

**Comment by scubamuc** [comment]
@the-djmaze nope, no expansion on hovering. is this configurable? i've tried with different browsers on different instances on different workstations.

**Comment by the-djmaze** [comment]
I've investigated this issue and noticed in Chrome that something odd was happening.
Constantly the drag timer was stopped and started.
So i've added a fail-safe that it only reacts on current element the mouse is on.
