### ISSUE TITLE
v2.22.3 unknown error

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#709]
![image](https://user-images.githubusercontent.com/4199669/204036656-c1364819-92d8-4fde-b617-ddf75d428c3d.png)

Using v2.22.2 works fine, but 2.22.3 does not work on login.
All i did was upgrade to 2.22.3, if I downgrade to 2.22.2 it works again.
I get no errors in console.

**Comment by the-djmaze** [comment]
Can you open application.ini and set `debug` to `on`?

**Comment by matpen** [comment]
I just installed the same version for the first time: I see the same message in UI as depicted in the OP, but additionally I do see some warning on console:
`PHP Warning:  mkdir(): Permission denied in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.22.3/app/libraries/MailSo/Cache/Drivers/File.php on line 95`

**Comment by matpen** [comment]
This is the function which causes the error, I think (with line numbers):
```php
    85		private function generateCachedFileName(string $sKey, bool $bMkDir = false) : string
    86		{
    87			$sFilePath = '';
    88			if (3 < \strlen($sKey))
    89			{
    90				$sKeyPath = \sha1($sKey);
    91				$sKeyPath = \substr($sKeyPath, 0, 2).'/'.\substr($sKeyPath, 2, 2).'/'.$sKeyPath;
    92	
    93				$sFilePath = $this->sCacheFolder.$this->sKeyPrefix.$sKeyPath;
    94				$dir = \dirname($sFilePath);
    95				if ($bMkDir && !\is_dir($dir) && !\mkdir($dir, 0700, true))
    96				{
    97					$sFilePath = '';
    98				}
    99			}
   100	
   101			return $sFilePath;
   102		}

**Comment by master3395** [comment]
> Can you open application.ini and set `debug` to `on`?

I enabled it and got the log.
I removed identification info such as IP and URL to admin place.
[log-2022-11-25.txt](https://github.com/the-djmaze/snappymail/files/10095091/log-2022-11-25.txt)

**Comment by the-djmaze** [comment]
Thanks! and fixed!

Problem occurred due to changes for supporting cPanel integration properly.

**Comment by matpen** [comment]
Thank you for working on this!
