### ISSUE TITLE
Threaded emails broken

### ISSUE THREAD

**Issue by grawlinson** [the-djmaze/snappymail#71]
**Describe the bug**
Threaded emails do not work as intended.

**To Reproduce**
1. Click on number that represents amount of emails in thread.
2. Watch nothing happen.

**Expected behavior**
1. Click on number that represents amount of emails in thread.
2. See list of emails change to that thread.

**EDIT**

It seems that clicking on the thread amount number changes the URL in the URL box ($URL/#/mailbox/INBOX~$VALUE) where  $VALUE is a 4 digit number (email ID? not sure).

**Comment by the-djmaze** [comment]
Fixed and repackaged the release with this tiny fix

**Comment by grawlinson** [comment]
`php release.php --aur` fails because the version in `package.json` still displays the previous version (2.4.3 instead of 2.4.3.1)

**Comment by the-djmaze** [comment]
Fixed that. Does it work?
