### ISSUE TITLE
2.22.3: Unable to move messages to different folder by drag and drop

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#710]
After update from 2.22.2 to 2.22.3, I'm unable to move messages to different folder by drag and drop.

- Browser
  - Google Chrome 107.0.5304.122
- IMAP daemon
  - Dovecot 2.3.19
- PHP version:
  - 8.1.13
- SnappyMail
  - 2.22.3

**Comment by the-djmaze** [comment]
Annoying! 😄 
First expanding folder failed in Chrome #707 
So i fixed that in 2.22.3
Tested that in Firefox 104 and Chromium and it worked for me.

Now i forget to test the drop in Chrome and you report this.
Now i need to figure out why...

**Comment by Bolli84** [comment]
Same here, it does not work in chrome

**Comment by Bolli84** [comment]
Works now

**Comment by ervee** [comment]
Somehow there is still something wrong. I can't drag email messages to other folders. It shows al the visual clues but the message is just not moved. If I open an email and press DEL the message is also not deleted. Firefox 107.0 (32-bit) and 107.0.1418.56 (Official build) (64-bit).
