### ISSUE TITLE
[Cosmetic] Scroll bar with the mobile version in "Advanced search" screen

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#712]
1. Scroll bar appears with `width = 360px` while there is space available in the first col :

![advanced search](https://user-images.githubusercontent.com/20357783/204099857-b910b1d6-3bb1-4640-8a6a-dd9cfbf90e56.png)

2. By the way, a lot of space is available when `width = 788px` :

![1](https://user-images.githubusercontent.com/20357783/204099920-bf647d66-520e-489f-9058-a3fe588a7a57.png)

**Comment by Massedil** [comment]
3. There is also an horizontal scroll bar if an email is too large (normal), but the scroll bar makes the header section scroll too (not normal). Expected : only the email body scroll from left to right ; not the headers.

**Comment by the-djmaze** [comment]
This is a very conflicting case.
In each language the size of text is different.
You have `Répondu` and Portuguese have `Respondidas`.
```
Répondu
Respondidas
```

Since most of the code is still based on Bootstrap.css (yes i hate it, but RainLoop choose for it and changing it is a lot of time and effort).
It is mostly `inline-block` based with fixed width (flex didn't exist or good supported by browsers).

Feel free to "fix" this if you want.

**Comment by Massedil** [comment]
> Feel free to "fix" this if you want.

For point 1 and 2, can you review this ?

```
<style>

@media screen and (max-width: 999px) {
	
	#advancedsearchform .row,
	#advancedsearchform .span4, 
	#advancedsearchform select, 
	#advancedsearchform .control-group > * {
		width: 100% ;
		margin-left:0 ;
	}
	
}

</style>
```

It looks like this for me : 

![Capture d’écran 2022-12-05 à 18 27 10](https://user-images.githubusercontent.com/20357783/205702927-28652ce0-a13c-4bbb-af51-f03bbbc61170.png)

**Comment by Massedil** [comment]
And for the point n°3, can you review this : 

```
.bodyText {
	overflow: scroll;
}
```

**Comment by the-djmaze** [comment]
You were on the right track.
I've modified it a bit so that bootstrap .row and .span4 are not used.

**Comment by Massedil** [comment]
I just updated to 2.22.7.

- I think you forgot to solve my point n°3 (`overflow: scroll` on `.bodyText` to avoid the actual scroll on `#messageItem`)

- About the two other points, you didn't wanted to use all the available space at the right ? I have this : 

![Capture d’écran 2022-12-06 à 15 44 17](https://user-images.githubusercontent.com/20357783/205944799-54a369f2-aff3-43b9-be8c-df1f51f20542.png)

![Capture d’écran 2022-12-06 à 15 44 45](https://user-images.githubusercontent.com/20357783/205944822-8a59e57a-c50f-4696-bd2b-0027fb956e71.png)

**Comment by the-djmaze** [comment]
> * About the two other points, you didn't wanted to use all the available space at the right ?

Well i had wacky jumping results with Firefox on `<select>` they didn't become `width: 100% ;` but the same width as the largest option inside.
So that needs a bit more thought.
