### ISSUE TITLE
Contact Error - object Object

### ISSUE THREAD

**Issue by stef157** [the-djmaze/snappymail#716]
**Describe the bug**
Wrong email adresse when we try to send an email to some contact.

**To Reproduce**
1. Go to 'Contacts" (top left)
2. Click on 'one or more contact(s)'
3. Click on the 'green envelope'
4. Check the email adresse

**Expected behavior**
That the email adresse is correct

**Screenshots**
It's attached 
![Screenshoot 28-11-2022 at 11 55 04](https://user-images.githubusercontent.com/1698095/204260533-2f5076ec-28f4-4259-bfe5-d06848acd40f.png)

**Please complete the following information:**
- Browser: Firefox 107.0 (64 bits) / Chrome 106.0.5249.91 / Safari 18614.2.9.1.12
- IMAP daemon: dovecot
- PHP version: 8.0
- SnappyMail Version: 2.22.3

Thanks

**Comment by the-djmaze** [comment]
1. Which contacts backend (database, ldap, nextcloud, etc.)?
2. What are the values of that specific contact (does it have 1 email address or multiple or none)?

**Comment by stef157** [comment]
Backend : Database
One address email (for both in the exemple)
