### ISSUE TITLE
ZIP Download all Attachements go where?

### ISSUE THREAD

**Issue by CSchaefer70** [the-djmaze/snappymail#717]
**Describe the bug**
?? MAYBE NOT  A BUG BUT NOT UNDERSTANDING THE PROCESS ?? 

When selecting a checkbox of one or more email msg the option via the humburger  drop menu "Download all attachments" when selected gives no error but I cannot find the download "ZIP" in expected locations like my local "downloads" folder or a new download to NextCloud or maybe a special zip archive folder within SnappyMail?

**To Reproduce**
1. Go to 'inbox SnappyMail folder'
2. Click on 'one or more email using the CHECKBOX'
3. Select HAMBURGER drop menu 'Download all Attachments'
4. No error but where is the submit location; where are the files copied?

**Expected behavior**
My expectation form the ZIP Icon in the drop menu and description is that by selecting the checkbox the ".eml" file or files will be zipped together with any attachments to a prompted folder/directory to allow saving as a ZIP File.

**Screenshots**
![image](https://user-images.githubusercontent.com/26978180/204301624-83eae4a0-7487-4acd-b32b-c07211453997.png)

**Please complete the following information:**
- Browser: Firefox 107.0 (32bit)
- IMAP daemon: dovecot
- PHP version: 8.1.6
- SnappyMail Version: 2.22.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Can get if required; explain how

**Additional context**
The ability to cleanup and simplify imap folder speeds up the email service.  This is really a great option to be able to save server email allocated space by "Archiving-ZIP" email off the server.  It also allows organising of historical email with ability of controlled initial selection of email msgs - nice!   

An option to save into NextCloud as a ZIP would be an added bonus!  But otherwise, being prompted to save to a local folder would do the same thing via the NextCloud client on the device.  An option in the prompted for location would simplify.

**Comment by the-djmaze** [comment]
It does not save the emails, only the attachments.

If you select emails that don't have an attachment, it won't work.
