### ISSUE TITLE
Folder list doesn't get updated until you reload

### ISSUE THREAD

**Issue by the-djmaze** [the-djmaze/snappymail#72]
I just found a little cosmetic error: when switching "Hide unsubscribed folders" to on, the folder list gets adjusted immediately. When switching "Hide unsubscribed folders" to off, the folder list doesn't get updated until you reload the page.

Somehow the folder refresh is missing.

_Originally posted by @realsimix in https://github.com/the-djmaze/snappymail/issues/69#issuecomment-810200232_

This is also the case, when you create a subfolder, e.g. folder "test" is created in root. It directly appears after creating it. Then you create folder "test2" with "test" as parent. The folder "test2" is not shown until you reload the page.

_Originally posted by @phsc84 in https://github.com/the-djmaze/snappymail/issues/69#issuecomment-810443474_

**Comment by Alphix** [comment]
> _Originally posted by @realsimix in [#69 (comment)](https://github.com/the-djmaze/snappymail/issues/69#issuecomment-810200232)_
> 
> This is also the case, when you create a subfolder, e.g. folder "test" is created in root. It directly appears after creating it. Then you create folder "test2" with "test" as parent. The folder "test2" is not shown until you reload the page.

It's the same behaviour when deleting folders. A top-level folder deletion will be reflected in the folder management UI straight away while a sub-folder deletion won't be.
