### ISSUE TITLE
cant't login after update to v2.22.4 [nexcloud app]

### ISSUE THREAD

**Issue by novallis66** [the-djmaze/snappymail#725]
**SnappyMail version, browser, browser version:**
v2.22.4 / [Nextcloud Hub 3 (25.0.1) / Microsoft Edge Version 107.0.1418.62 (Offizielles Build) (64-Bit)
**Expected behavior and actual behavior:**
Can't login.  I get allways error "Authentification failed"

If i use "Rainloop"  i have no problems. Password and settings are identical. Bevor the update i had no problems

**Steps to reproduce the problem:**

**Logs or screenshots:**

**Comment by the-djmaze** [comment]
1. Go Nextcloud -> Admin -> Additional settings.
2. Enable `debug` and save
3. Try login again

Look in the log at `/data/appdata_snappymail/_data_/_default_/logs` to find the issue.

**Comment by novallis66** [comment]
Unfortunately my nextcloud installation is a hosted, so I don't habe access to the Log-Files.

But I found the problem.
The Extensions made trobles, so after uncheck the Extensions, I could login and get access.

So someone have to check the extensions ...

best regards,

Ralf

**Comment by the-djmaze** [comment]
Extensions is fixed
