### ISSUE TITLE
The unseen counter doesn't dissapear when deleting all emails in a folder

### ISSUE THREAD

**Issue by roru69** [the-djmaze/snappymail#726]
When deleting all emails from a folder the "unseen" counter doesn't dissapear.

**To Reproduce**
1. check the unseen counter at the "ongewenste Email" - (Junk Folder). shows in my case 52
2. delete all emails.
3. empty recycle bin

**Partial Workaround**
1. wait until a new unseen message is placed in the mailbox.
2. Mark everything as read.
3. The unseen counter is gone

**Expected behavior**
after I have deleted all emails (including the unseen) the "unseen" counter should be gone. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9691381/204757684-5d35ed48-68fb-4c31-989c-bd6be95dbbcb.png)

**Please complete the following information:**
- Browser: Microsoft Edge 107.0.1418.62 (Official build) (64-bits)
- IMAP daemon: Zentyal 7.x
- PHP version: PHP 8.1.12 (cli) (built: Oct 28 2022 18:32:13) (NTS)
- SnappyMail Version: 2.22.4
- Nextcloud 25.0.2 RC1

**Comment by the-djmaze** [comment]
To know what is going on we need to debug this.
1. Open your browser developer tools
2. Click on the `Network` tab
3. Clear the SnappyMail folder

Now the developer tools should have three requests:
1. `FolderClear` which removes the messages
2. `MessageList` which checks the box is really empty
3. `FolderInformation` to get the folder metadata like `unreadEmails`

In my case the `unreadEmails` is 0 and `HighestModSeq` = 606

If your IMAP server does not support `HIGHESTMODSEQ` [RFC 4551](https://www.rfc-editor.org/rfc/rfc4551) then this could cause a caching trigger and it will return old `unreadEmails` value.

Could you check that?

**Comment by roru69** [comment]
Thanks for the quick reply.

After a reboot of the Mail server i can't reproduce the issue. So you can close this call. Thanks for your help anyway!

Regards, RR69
