### ISSUE TITLE
New mail notification in Nextcloud-Notificiations (bell in panel )

### ISSUE THREAD

**Issue by new-on-github** [the-djmaze/snappymail#730]
**SnappyMail version, browser, browser version:**
2.22.4

**Expected behavior and actual behavior:**
new mail comes in --> notification in panel and push notification;
actual happens nothing and I cannot find snappy mail in settings -> notifications
**Steps to reproduce the problem:**
Receive mail and check notifications;
Or did I miss anything?

Btw. Thanks for your work!

**Comment by the-djmaze** [comment]
I could not find documentation to hook into using JavaScript.
When Nextcloud can't, SnappyMail can't
