### ISSUE TITLE
Login Not Remembering Credentials

### ISSUE THREAD

**Issue by HeyVern** [the-djmaze/snappymail#731]
**Describe the bug**
Setting: Users will login manually, or define credentials in their personal settings for automatic logins.

Users login with correct credentials with "Remember Me" checked. Login successful.
User closes browser, revisits site, and is again prompted with login prompt.

Note: have tried Config: 'sign_me_auto' set to "DefaultOff" and "DefaultOn"

**To Reproduce**
1. Use SnappyMail for Nextcloud
2. Verify setting: "Users will login manually, or define credentials in their personal settings for automatic logins."
3. Specify login crendentials for SMTP with 'Remember Me' checked.
4. Close browser
5. Revisit Snappymail and see prompt again.

**Expected behavior**
Expected auto-login with rememebered credentials.

**Please complete the following information:**
- Browser: 107.0.5304.141 (Offical Build)
- PHP version: 8.0.24
- SnappyMail Version: 2.22.4
- SnappyMail Nextcloud Extension: 2.12

**Comment by the-djmaze** [comment]
Dupl8cat of #719 ?

**Comment by HeyVern** [comment]
Yes, it looks like a duplicate.  Sorry about that.

**Comment by the-djmaze** [comment]
> Sent another donation to say thanks for all your hard work @the-djmaze. Much appreciated!!

Thank you! It helps a lot for further development and making SnappyMail stable
