### ISSUE TITLE
Check if contacts credentials work

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#732]
When checking if your credentials are in order, there is no notification if everything works.
Only if your password is wrong or something similar.
There should be an option to say "works" or something.
Not sure if that is just not working or if it should have been posted as a "feature".

V2.22.4

**Comment by master3395** [comment]
This page.
Sometimes when the password is correct, a small checkmark is to the right of the password box.
But only once.
![image](https://user-images.githubusercontent.com/4199669/206879823-36789148-eb6b-4e5f-a3d5-b5a27ab98b66.png)

**Comment by the-djmaze** [comment]
> Sometimes when the password is correct, a small checkmark is to the right of the password box.

No, RainLoop uses the checkmark differently and so does SnappyMail.

The small checkmark indicates that the value is saved.
The big `[Test]` button becomes green when everything works.
