### ISSUE TITLE
How to extend user drop down view?

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#733]
**Is your feature request related to a problem? Please describe.**

currently it is not possible to extend drop down view of user. This adds limited functionality for plugin developers to add new features to drop down menu

![image](https://user-images.githubusercontent.com/16881005/205004600-7b0d5f9b-1459-4242-9707-f254eb239e92.png)

**Describe the solution you'd like**

Something similar like `addSettingsViewModel` would be interesting to have for drop down

**Describe alternatives you've considered**

Overwrite `snappymail/v/0.0.0/app/templates/Views/User/SystemDropDown.html` with custom changes

**Additional context**

**Comment by the-djmaze** [comment]
Try something like:
```js
addEventListener('rl-view-model.create', e => {
	if ('SystemDropDown' === e.detail.viewModelTemplateID) {
		let view = e.detail;
		view.customClick = () => {
			alert('customClick');
		};
		document
			.getElementById('SystemDropDown')
			.content
			.querySelector('menu')
			.append(Element.fromHTML(`<li role="presentation">
					<a href="#" tabindex="-1" data-bind="click: customClick" data-icon="⏻" data-i18n="GLOBAL/TEST"></a>
				</li>`));
	}
});
```

**Comment by Niveshkrishna** [comment]
@the-djmaze Amazing :tada: . This works as expected.

**Comment by Niveshkrishna** [comment]
It would also be interesting to allow ordering of items in the drop down

**Comment by Niveshkrishna** [comment]
I was able to achieve required positioning with this

```js
document.getElementById('SystemDropDown')
	.content
	.querySelector('menu')
	.children[4]
	.insertAdjacentElement("afterEnd", Element.fromHTML(`<li role="presentation">
	     <a href="#" tabindex="-1" data-icon="⏻" data-i18n="GLOBAL/TEST"></a>
      </li>`));
```

**Comment by the-djmaze** [comment]
`.children[4]` is risky because you can have multiple accounts and then `.children[4]` might be between the accounts.

Better to find `menu .dividerbar:nth-child(2)` to put above/below first divider
Better to find `menu .dividerbar:nth-child(2)` to put above/below second divider

**Comment by the-djmaze** [comment]
`.children[4]` is risky because you can have multiple accounts and then `.children[4]` might be between the accounts.

Better to find `menu .dividerbar` to put above/below first divider
Better to find `menu .dividerbar:nth-child(2)` to put above/below second divider

**Comment by MI-KY** [comment]
Hi @the-djmaze added this to the developer documentation inside the wiki: https://github.com/the-djmaze/snappymail/wiki/Developer-Documentation#modify-the-ui-of-snappymail-at-runtime .
Don't know if with the "documentation" label you intend to mark all the information that has to be added to the wiki :slightly_smiling_face: ?

**Comment by the-djmaze** [comment]
> Don't know if with the "documentation" label you intend to mark all the information that has to be added to the wiki 🙂

Well, that would be the best :)

**Comment by MI-KY** [comment]
:+1: . Would you like that I make a comment on the issues that have been ported to the documentation to remove the "documentation" flag or do we leave everything as it is?
