### ISSUE TITLE
Nextcloud - Unable to login on fresh install

### ISSUE THREAD

**Issue by Draecal** [the-djmaze/snappymail#734]
**Describe the bug**
Added a new Domain and can't log in with valid email / password

**To Reproduce**
1. Add a new domain
2. Test with an account (You'll get IMAP and SMTP ok) 
3. Try to log in with any user

**Expected behavior**
Log in to check the emails

**Screenshots**
![image](https://user-images.githubusercontent.com/8697000/205033911-f0bdb210-481a-45ae-b685-0dc177c6c1ac.png)
![image](https://user-images.githubusercontent.com/8697000/205034081-49b6877f-d27f-4095-8fae-b81076fae87d.png)

**Please complete the following information:**
- Browser: Microsoft Edge 107.0.1418.56
- IMAP daemon: N/A
- PHP version: 8.1
- SnappyMail Version: 2.22.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

`{"Action":"Login","Result":false,"ErrorCode":104,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1088}`

**Additional context**

**Comment by the-djmaze** [comment]
Go to admin -> domains
At the botrom is a test field.
Fill in the email address and test there as well which match it finds

**Comment by Draecal** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/8697000/205143791-4150ac77-10d1-489e-aebd-70dbce0c2223.png)

**Comment by Draecal** [comment]
Also noticed this when adding a new domain: 
![image](https://user-images.githubusercontent.com/8697000/205144167-aea949d9-0280-4f7c-b843-17bc8534080e.png)
it was expected to get ***@example.com** but instead I get **@*@example.com**. Regardless the domain, the same issue

**Comment by the-djmaze** [comment]
Do you have the domain names correct like 'gmail.com' or 'example.com'?

You can also debug:
1. Go Nextcloud -> Admin -> Additional settings.
2. Enable `debug` and save
3. Try login again

Look in the log at `/data/appdata_snappymail/_data_/_default_/logs` to find the issue.

**Comment by Draecal** [comment]
`[2022-12-01 19:35:21.447][cdeab45a] [INFO]: [SM:2.22.4][IP:172.71.134.127][PID:779176][Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/8.1.10 mod_perl/2.0.12 Perl/v5.34.1][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://cloud.theapicentral.com/index.php/apps/snappymail/?admin/Json/&q[]=/0/]
[2022-12-01 19:35:21.448][cdeab45a] JSON[INFO]: Action: DoAdminDomainMatch
[2022-12-01 19:35:21.448][cdeab45a] POST[INFO]: {"username":"admin@theapicentral.com","Action":"AdminDomainMatch","XToken":"081a58f811162005b0136a29e7e3495e327c4ef0"}
[2022-12-01 19:35:21.449][cdeab45a] JSON[INFO]: {"Action":"AdminDomainMatch","Result":{"email":"admin@theapicentral.com","login":"admin@theapicentral.com","domain":{"name":"theapicentral.com","IMAP":{"host":"imappro.zoho.com","port":993,"type":1,"shortLogin":false,"ssl":{"verify_peer":true,"verify_peer_name":true,"allow_self_signed":true,"SNI_ena...
[2022-12-01 19:35:21.449][cdeab45a] [INFO]: Memory peak usage: 10MB
[2022-12-01 19:35:21.449][cdeab45a] [INFO]: Time delta: 1.4899339675903
[2022-12-01 19:35:21.449][cdeab45a] IMAP[INFO]: Disconnected from "ssl://imappro.zoho.com:993" (success)
[2022-12-01 19:35:21.449][cdeab45a] IMAP[DEBUG]: 0.94318819046021 (net session)
[2022-12-01 22:20:19.565][2d11ed76] [INFO]: [SM:2.22.4][IP:141.101.77.24][PID:785937][Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/8.1.10 mod_perl/2.0.12 Perl/v5.34.1][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://cloud.theapicentral.com/index.php/apps/snappymail/]
[2022-12-01 22:20:19.576][2d11ed76] IMAP[INFO]: Start connection to "ssl://imappro.zoho.com:993"
[2022-12-01 22:20:20.125][2d11ed76] IMAP[INFO]: Connect (success)
[2022-12-01 22:20:20.126][2d11ed76] IMAP[DEBUG]: 0.54990077018738 (raw connection)
[2022-12-01 22:20:20.127][2d11ed76] IMAP[INFO]: < * OK svwall.zoho.com IMAP4 Server (Zoho Mail IMAP4rev1 Server version 1.0)\r\n
[2022-12-01 22:20:20.127][2d11ed76] IMAP[DEBUG]: 0.55170607566833 (*)
[2022-12-01 22:20:20.127][2d11ed76] IMAP[INFO]: > TAG1 CAPABILITY\r\n
[2022-12-01 22:20:20.300][2d11ed76] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT CHILDREN XLIST NAMESPACE IDLE MOVE ID AUTH=PLAIN SASL-IR UIDPLUS ESEARCH LIST-EXTENDED LIST-STATUS WITHIN LITERAL- ACL CONDSTORE\r\n
[2022-12-01 22:20:20.300][2d11ed76] IMAP[INFO]: < TAG1 OK CAPABILITY completed\r\n
[2022-12-01 22:20:20.300][2d11ed76] IMAP[DEBUG]: 0.17302203178406 (TAG1)
[2022-12-01 22:20:20.301][2d11ed76] IMAP[INFO]: > TAG2 AUTHENTICATE PLAIN *******\r\n
[2022-12-01 22:20:20.481][2d11ed76] IMAP[INFO]: < TAG2 NO [AUTHENTICATIONFAILED] Invalid credentials(Failure)\r\n
[2022-12-01 22:20:20.481][2d11ed76] IMAP[DEBUG]: 0.17983603477478 (TAG2)
[2022-12-01 22:20:20.481][2d11ed76] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Invalid credentials(Failure) in /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/MailSo/Imap/ImapClient.php(531): MailSo\Imap\ResponseCollection->validate()
#1 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/MailSo/Imap/ImapClient.php(449): MailSo\Imap\ImapClient->getResponse()
#2 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/MailSo/Imap/ImapClient.php(192): MailSo\Imap\ImapClient->SendRequestGetResponse('AUTHENTICATE', Array)
#3 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/RainLoop/Model/Account.php(284): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#4 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/RainLoop/Model/Account.php(232): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\Settings))
#5 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/RainLoop/Actions/UserAuth.php(452): RainLoop\Model\Account->ImapConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#6 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.4/app/libraries/RainLoop/Actions/UserAuth.php(142): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\MainAccount), true)
#7 /var/www/html/cloud/apps/snappymail/lib/Util/SnappyMailHelper.php(128): RainLoop\Actions->LoginProcess('admin@theapicen...', 'YiT48ax@pS8c7d0...', false)
#8 /var/www/html/cloud/apps/snappymail/lib/Controller/PageController.php(49): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#9 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->index()
#10 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'index')
#11 /var/www/html/cloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'index')
#12 /var/www/html/cloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 /var/www/html/cloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#14 /var/www/html/cloud/index.php(36): OC::handleRequest()` 

For sure I tested user password at my mail provider and works so no clue why is saying invalid credentials.

**Comment by the-djmaze** [comment]
It connects with ssl://imappro.zoho.com:993
But then:
```
IMAP[INFO]: > TAG2 AUTHENTICATE PLAIN *******\r\n
IMAP[INFO]: < TAG2 NO [AUTHENTICATIONFAILED] Invalid credentials(Failure)\r\n
```

Is it correct that `theapicentral` should connect with ZoHo?
If yes, then something might go wrong with the passphrase and we can figure that out.

There's a debug mode in application.ini config to unhide passwords.
Then it will also log how the AUTHENTICATE PLAIN exactly works.

But NEVER post that data here as it is sensitive information!
You must base64 decode that data yourself and then we might find the problem.
And don't forget to set that option off again and then remove the log.

**Comment by Draecal** [comment]
Checked the password wrote correctly no mistakes but is not accepting it. Tested the same password at my provider's portal and works.

**Comment by the-djmaze** [comment]
Did you try and decode like i said or is that outside your knowledge?

**Comment by Draecal** [comment]
I did, the password it's being hashed so it's not sent as plain

**Comment by the-djmaze** [comment]
It's not a hash, it is base64 and that can be decoded to find the problem.

But i think the problem is `*@domain` while it should be `domain`.
But i can't fully see in your first screenshot

**Comment by Draecal** [comment]
Switched the locale from es-ES to en, still don't work but the frontend text changed to this 
![image](https://user-images.githubusercontent.com/8697000/205436350-4548e0ff-b4d9-4bd2-aa8f-97a8857c6062.png)

**Comment by Draecal** [comment]
There should be any issue at some point on the app code. If I test the IMAP works, but the test under Domain section keeps saying `undefined matched domain`

**Comment by Draecal** [comment]
Also, the password is not being base64 encoded properly if I debug the `TAG2 AUTHENTICATE PLAIN` the decoded base64 gives mail and password, but the password returned is not the one introduced and if I consider that password as base64 and try to decode, is not a valid base64 string

**Comment by Draecal** [comment]
The app got an upgrade, the error doesn't happen anymore but was replaced for this

```
[2022-12-03 15:47:10.028][17e08908] [NOTICE]: TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Actions/Folders.php:77
Stack trace:
#0 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Actions/Folders.php(77): array_filter(NULL, Object(Closure))
#1 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoFolders()
#2 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
#3 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#4 /var/www/html/cloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#5 /var/www/html/cloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#6 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#7 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /var/www/html/cloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#9 /var/www/html/cloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 /var/www/html/cloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#11 /var/www/html/cloud/index.php(36): OC::handleRequest()
#12 {main}
[2022-12-03 15:47:10.028][17e08908] [ERROR]: TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Actions/Folders.php:77
Stack trace:
#0 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Actions/Folders.php(77): array_filter(NULL, Object(Closure))
#1 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoFolders()
#2 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
#3 /var/www/html/cloud/apps/snappymail/app/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#4 /var/www/html/cloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#5 /var/www/html/cloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#6 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#7 /var/www/html/cloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /var/www/html/cloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#9 /var/www/html/cloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 /var/www/html/cloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#11 /var/www/html/cloud/index.php(36): OC::handleRequest()
#12 {main}
[2022-12-03 15:47:10.028][17e08908] JSON[INFO]: {"Action":"Folders","Result":false,"ErrorCode":999,"ErrorMessage":"0 - array_filter(): Argument #1 ($array) must be of type array, null given","ErrorMessageAdditional":"","Time":1459}
```

**Comment by MI-KY** [comment]
Does this mean that now you're able to login but this error occurs afterwards or do jo see the same error on the gui but only in the log the error changed?

**Comment by Draecal** [comment]
Unable to log-in, no front-end error showing, the page just refreshes, and nothing happens.

**Comment by MI-KY** [comment]
Maybe we take a step back:

- So you installed SnappyMail by installing the App inside your Nextcloud using the NC web interface or occ, right?
- Have you configured one of the automatic sign on methods to log in Nextcloud users to SnappyMail?
- Have you configured multiple domains inside the "Domain" menu of the SnappyMail Admin Panel or just one?
- Could you show us a complete screenshot how you configured this domain (hiding the domainname itself would be ok)

I'm asking the last one because in your screenshot there is also missing a dot before "com" but I could imagine that this was only a error inserting the data for your example... but who knows...
> Also noticed this when adding a new domain: ![image](https://user-images.githubusercontent.com/8697000/205144167-aea949d9-0280-4f7c-b843-17bc8534080e.png) it was expected to get ***@example.com** but instead I get @*@example.com. Regardless the domain, the same issue

**Comment by Draecal** [comment]
As said, the IMAP test works after configuring the new domain. but the test outside that window and the user log-in are the ones not working. So:
- NC web
- No need as users will introduce the FQDN. Also, because the tool show that as optional.
- No just one, and don't know why would be that an issue if the tool allows multiple domains.
- Not much to show over there since the IMAP test is working.

Basic configuration was added IMAP and SMTP along with SSL/TLS method at verification.

**Comment by the-djmaze** [comment]
Can you make a screenshot of Admin -> Domains like this:
![afbeelding](https://user-images.githubusercontent.com/3752035/205613005-b5419700-24a0-4c4e-bf8a-65ae8dd18cf3.png)

Then we know why you can't login.
Because in my screenshot you can't login with `@domain.com`

**Comment by Draecal** [comment]
![image](https://user-images.githubusercontent.com/8697000/205614174-35e641c1-924e-4a1f-9611-5ac1d1e72c2c.png)
![image](https://user-images.githubusercontent.com/8697000/205614236-f3a6c196-730f-46e1-9421-1fea13675c63.png)

**Comment by the-djmaze** [comment]
Sounds like an issue with your OpenSSL.
Do you have v1 or v3 of OpenSSL?

**Comment by Draecal** [comment]
![image](https://user-images.githubusercontent.com/8697000/205619778-d34fe88d-8418-4ecb-8b32-f2a2f7b3043e.png)

**Comment by the-djmaze** [comment]
Can you install/enable the Sodium extension in PHP?

**Comment by Draecal** [comment]
Tried many times but NC fails to detect it 
![image](https://user-images.githubusercontent.com/8697000/205620645-482e7b15-77f6-492a-acd6-c17f505721ff.png)

**Comment by the-djmaze** [comment]
Oh and upgrade your OpenSSL
https://about.gitlab.com/blog/2022/11/01/new-openssl-30-vulnerabilities-what-you-need-to-know-to-find-and-fix-them/

**Comment by Draecal** [comment]
I have the latest version for Fedora 37

**Comment by the-djmaze** [comment]
> And Snappymail keeps failing integrity test

Correct, we don't ship a signature.json for that.

> but still getting the same issues

Very strange, Because base64 decode the PLAIN hash should give you very clear value:
```php
"\x00username@domain.com\x00password"
```

We are really shooting in the dark here because there are things going on that are really strange.
1. you have domain "example.com"
2. you test "login@example.com" but it says "undefined matched domain"
3. you say the hash is encrypted (which should not)

Best is to start over:
1. Nextcloud -> User -> Additional Settings empty login values
2. Remove app from Nextcloud
3. Delete /data/app_snappymail (or rename as backup)
4. Install app again
5. Nextcloud -> Admin -> Additional Settings -> Open SnappyMail Admin
6. Nextcloud -> Admin -> Additional Settings -> Enable debug
7. Domains: Add your domain
8. Domains: test "login@example.com"
9. Nextcloud -> SnappyMail try login

**Comment by the-djmaze** [comment]
> PHP[WARNING]: Undefined property: MailSo\Mail\FolderCollection::$capabilities

Thank you, so you've modified the application.ini in several areas but didn't tell us that.
Because `use_sort` is by default true/On and now it's not.

**Comment by Draecal** [comment]
That's absolutely false, that appeared with the latest update

**Comment by Draecal** [comment]
Found the option and enabled again, now I can log-in. Is somewhere at the documentation what's the use of that option. Will affect any other domain? should be always enabled?

**Comment by the-djmaze** [comment]
> Is somewhere at the documentation what's the use of that option. Will affect any other domain? should be always enabled?

It is a bug, and is solved now.
The option is to disable sorting messages and then SnappyMail can only show messages in a way that the IMAP server supplies to us.
So it is best to have it enabled anyway.
