### ISSUE TITLE
"New Message" button is not centered in NC25 Theme

### ISSUE THREAD

**Issue by gnilebein** [the-djmaze/snappymail#735]
**Describe the bug**
The "New Message" button is not centered in NC25 Theme

**To Reproduce**

**Expected behavior**
Snappymail should show centered text

**Screenshots**
![Screenshot](https://i.ibb.co/yNHqFNf/Snappy-Mail-Center-New-Message.png)

**Please complete the following information:**
- Browser: Chrone 107.0.5304.122 and Firefox
- IMAP daemon: Dovecot
- PHP version: 8.0
- SnappyMail Version: 2.22.4

**Comment by the-djmaze** [comment]
Correct it is Work in Progress and i accidentally put it in release.
It will be removed in next release until finished.

See the great progress at #629
