### ISSUE TITLE
[Cosmetic] Star icon and date can go on the second line if width is small

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#737]
A picture is worth a thousand words :
- First email is as expected
- Second has the date and star in a new line
- Third has the star in a new line
- Fourth is as expected

![2](https://user-images.githubusercontent.com/20357783/205340252-4a66395c-82b7-4e8d-829a-04d06fcd5fa6.png)

- snappymail v. 2.22.5 (bug was also here in v.2.22.4, at least)

**Comment by the-djmaze** [comment]
Looks like the problem is the date format.
For narrow screens making the format just the day/month/year could be an idea.
Or use 3 lines as now, but better aligned.

Will figure it out as most apps on phones don't show this amount of details.

**Comment by Massedil** [comment]
> For narrow screens making the format just the day/month/year could be an idea.

Maybe like k9-mail do? 

![image5](https://user-images.githubusercontent.com/20357783/205435640-3a81cfaf-50ad-4827-b171-f3b70a383483.png)

> Or use 3 lines as now, but better aligned.

Yep, also. 

> Will figure it out as most apps on phones don't show this amount of details.

My first screenshot is from the desktop view. I just reduced the mail list.

Maybe we can also use more of the available space we can see at the left of the date?

**Comment by the-djmaze** [comment]
I've made the flex a bit smaller to solve it.

However, i also have this idea (but it currently breaks the selector functionality).
![afbeelding](https://user-images.githubusercontent.com/3752035/205495490-ca3c4a72-97cb-415a-b676-235efb89a08e.png)

**Comment by the-djmaze** [comment]
v2.24 now has the split :smile:

**Comment by Massedil** [comment]
> v2.24 now has the split

I just updated to 2.24 and will test it ! Thanks !
