### ISSUE TITLE
Cannot install SnappyMail - PHP error, file does not exist

### ISSUE THREAD

**Issue by tomszilagyi** [the-djmaze/snappymail#74]
**Describe the bug**
Problem installing SnappyMail, PHP error referring to nonexistent file.

**To Reproduce**
1. Follow the installation instructions published on the wiki
2. Try to open the webmail in a browser
3. The browser displays a plain white page with the text "SnappyMail" in the upper left corner, and there is an error like this in the nginx error log:

```
2021/04/05 17:11:42 [error] 13191#0: *9 FastCGI sent in stderr: "PHP message: PHP Warning: file_get_contents(/htdocs/webmail/snappymail/v/0.0.0/static/js/min/boot.min.js): failed to open stream: No such file or directory in /htdocs/webmail/snappymail/v/0.0.0/app/libraries/RainLoop/Service.php on line 234
PHP message: PHP Warning: file_get_contents(/htdocs/webmail/snappymail/v/0.0.0/static/css/boot.min.css): failed to open stream: No such file or directory in /htdocs/webmail/snappymail/v/0.0.0/app/libraries/RainLoop/Service.php on line 237" while reading response header from upstream, client: xx.xx.xx.xx, server: webmail.example.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "webmail.example.com"
```

**Expected behavior**
Following the documented install procedure should result in a working installation.

**Desktop (please complete the following information):**
 - Browser [Firefox 78.9.0 ESR on Debian Linux]
 - SnappyMail Version [e.g. 2.4.3]

**Additional context**
I have an instance of RainLoop that works well. I am trying to upgrade it to SnappyMail and I expected this to be more or less a drop-in replacement. This is to say that I have an existing webserver setup (with php-fpm etc.) on a virtualhost that seems to work well. I have tried to simply swap the rainloop subdirectory for the snappymail subdirectory (as I have all the scaffolding, webserver config, certificates, etc. in place). After this failed, I also tried to use the exact Nginx configuration (with obvious changes to adapt the paths) published under "Webserver configuration" in the wiki.

I tested the release tarballs of both 2.4.3 and 2.4.3.1 with the same result. At first I thought I made some error with the path setup or similar, but thet I noticed that actually, there *is* *no* `boot.min.js` anywhere within my snappymail deployment, in fact there is no `static` folder at all! How can that be?

I tried to access the webmail's root as well as `/?admin`.

I am not too familiar with frontend development practices nowadays -- is there any build step required to build the minimal versions of the assets e.g. `boot.min.css` (the closest thing I can find in the tarball is `dev/boot.js`)? Not according to the documentation. Am I missing something?

Happy to provide further info as requested.

Thanks!

**Comment by the-djmaze** [comment]
`snappymail/v/0.0.0/`
You used the git repo without building a release.
Don't download the source package if you don't know how to build a release, use the 2.3.4 package instead.

**Comment by tomszilagyi** [comment]
I'm not sure why I downloaded the source tarball without mentally registering this fact, but that is exactly what I did.
Thanks :)
