### ISSUE TITLE
v2.22.6 not logging in to GMX or Mail.com

### ISSUE THREAD

**Issue by ivnmad** [the-djmaze/snappymail#746]
I've just upgraded from v2.22.5 to v2.22.6 and logging into a GMX or Mail.com email address fails.
The same happens if you are on another email domain and then select a GMX/Mail.com email address from the identity drop down menu. You are immediately logged out. Tested on Firefox and Chrome.

Everything works fine if I revert back to v2.22.5.

**Comment by the-djmaze** [comment]
v2.22.6 contains a change that if an imap server doesn't support MODCHANGE it uses UIDVALIDITY.
But somehow that is also undefined for your server.

So the above commit should try to solve this, but not 100% sure if it works properly.
