### ISSUE TITLE
cant't login to gmx.de & web.de accounts after update to v2.22.6 [nexcloud app] 

### ISSUE THREAD

**Issue by fow0ryl** [the-djmaze/snappymail#748]
After update from mybe 2.20.nn I can't login into most mail accounts. My GONEO account seems to work normal. 
There are 2 diffenert scenarios.

1. If I tried to use an account which works until update. I got an error. [Log-message](https://pastebin.com/raw/RQ7ujYZq)
2. If I try to use an account, which was never used before, I get "wrong credentials". 

Since I did not know the old version excactly, I downloaded 2.20.6.
- occ disable snappymail
- moved snappymail snappymail.backup
- unzip 2.20.6 to snappymail
- occ enable snappymail
And everything works fine again ...

**Comment by the-djmaze** [comment]
v2.22.6 contains a change that if an imap server doesn't support MODCHANGE it uses UIDVALIDITY.
But somehow that is also undefined for your server.

So the above commit should try to solve this, but not 100% sure if it works properly.

**Comment by fow0ryl** [comment]
I have replaced the 3 php files only with the patched ones in my old 2.22.6 installation. 
And ... After activation of 2.22.6 I can login again :)
Thank you for your lightning fast help.

**Comment by the-djmaze** [comment]
Good. I've made a better fix on the results of this issue.
