### ISSUE TITLE
UI regressions(?) compared to RainLoop

### ISSUE THREAD

**Issue by tomszilagyi** [the-djmaze/snappymail#75]
**Describe the bug**
Minor UI regressions coming from RainLoop: IMAP quota popup and left sizer edge

**To Reproduce**
See screenshot

**Expected behavior**
In these cases, I would prefer how RainLoop looks.

**Screenshots**
![SnappyMail_UI_regressions](https://user-images.githubusercontent.com/5454768/113723803-ffedee80-96f1-11eb-80e9-1aff32344272.png)
I see two issues:
- the IMAP quota popup, which in RainLoop shows details about mailbox storage use, displays "function () { [native code] }". I think this is a regression.
- there is a "blip" (probably not how it's called, sorry, I'm not a frontend dev) on the bottom right of the left pane (marked with the red arrow), which was not there in RainLoop. I thought this might be actually a feature to indicate that the pane is resizable, but resizing works in RainLoop the same way, I even get the cursor shape change and a highlight of the border vertical line if I hover over it with the mouse, so I think this "blip" is entirely unnecessary (I cannot really tell if it's a bug or a feature).

**Desktop (please complete the following information):**
 - Browser: Firefox 78.9.0 ESR
 - SnappyMail 2.4.3

**Additional context**
I am now running RainLoop and SnappyMail side by side with the same webserver config (testing out SnappyMail as I would like to migrate to it). The only difference is the root directory.
Happy to provide any additional details as necessary.
Thank you for your hard work on SnappyMail!

**Comment by tomszilagyi** [comment]
I should have added that the above comparison was made against RainLoop Community Edition, current latest version (v1.15.0).
Thanks!

**Comment by the-djmaze** [comment]
Regarding right bottom icon
https://github.com/the-djmaze/snappymail/issues/19

**Comment by tomszilagyi** [comment]
Thanks for the explanation on the bottom right icon, it certainly makes sense (and it's a minor issue).
Thanks even more for the fix on the quota issue, I just tested it with your new 2.5.0-rc1 and it seems to work fine!

**Comment by tomszilagyi** [comment]
It seems like there is a regression introduced somewhere between snappymail 2.7.1 and 2.9.1, the IMAP quota indicator is once again gone. It is completely gone, not just the popup, but also the percentage that was previously visible at all times.

**Comment by the-djmaze** [comment]
> It seems like there is a regression introduced somewhere between snappymail 2.7.1 and 2.9.1, the IMAP quota indicator is once again gone. It is completely gone, not just the popup, but also the percentage that was previously visible at all times.

My mail server has no quota, but when i login with my gmail account i see the gmail server supports QUOTA.
So the "Folders" action request does return my gmail quota properly.
![afbeelding](https://user-images.githubusercontent.com/3752035/142181662-5a7c1f5e-8339-47d2-a582-a220a2e07336.png)

Could you do some tests?

**Comment by tomszilagyi** [comment]
On 2.7.1 I see a separate request with Action: Quota and corresponding response, which looks good, and the quota is displayed in the UI. There is no quotaUsage and quotaLimit field in the request with Action: Folders.

On 2.9.1 this separate request is gone, but there is a quotaUsage and quotaLimit field in the request with Action: Folders, both with zero values.

**Comment by the-djmaze** [comment]
> On 2.9.1 this separate request is gone, but there is a quotaUsage and quotaLimit field in the request with Action: Folders, both with zero values.

Right, they are 0 for a reason.

Edit /snappymail/v/2.9.1/app/libraries/RainLoop/Actions/Folders.php line 24 and change in:
```php
//					$aQuota = $this->MailClient()->Quota();
					$aQuota = $this->MailClient()->QuotaRoot();
```

If that solves your issue, i will try to improve it because several systems use different ways for quota's and fetching quota for each folder could be a thing.
See:
https://github.com/RainLoop/rainloop-webmail/issues/2086

**Comment by tomszilagyi** [comment]
I can confirm that changing the call from Quota() to QuotaRoot() makes it work, quota is displayed correctly.
