### ISSUE TITLE
Redirect to login page instead of "invalid token" popup

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#752]
**Is your feature request related to a problem? Please describe.**
When returning to SnappyMail after a while, say an old tab on your laptop or browser session on your phone, You sometimes get an "Invalid Token" pop-up. Probably because you didn't logout.

**Describe the solution you'd like**
It would be nicer to just have the page redirect you back to the login screen.

**Describe alternatives you've considered**
Don't forget to logout.

**Additional context**
![image](https://user-images.githubusercontent.com/4435930/205925964-aa602a8e-19bb-4b4c-baf6-589f3441920b.png)

**Comment by the-djmaze** [comment]
Try https://github.com/the-djmaze/snappymail/releases/tag/v2.22.7

**Comment by the-djmaze** [comment]
I will look into it as the error pops up for several occasions
