### ISSUE TITLE
Dragging email to folder broken

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#755]
**Describe the bug**
Dragging an email from inbox to another folder broke some in the last couple of releases.

**To Reproduce**
1. Go to inbox. I have my setting to not show a preview pane but it does not matter.
2. Drag an email from inbox to say trash or another folder.
3. The animation of the folder (zoom in/out) is visible, sometimes not on the first try though and the folder reload icon spins and most of the time the email you dragged becomes grayed out...
4. If you refresh the page, the email is still there most of the time but also not always...

Also opening an email and then pressing delete does not delete it.

**Expected behavior**
Dragging e-mail moves it to the folder and removes it from the current folder.

**Please complete the following information:**
- Browser: Firefox 107.0.1 (32-bit) on Windows 11 but tested with other too.
- IMAP daemon: Dovecot 2.3.13
- PHP version: 7.4.33
- SnappyMail Version: 2.22.4 , also tested latest version 2.22.7

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
While debugging I did not see logs on the server, but I did see a lot of errors in the browser debug pane that seem to be related to the avatar plugin.

I disabled the avatar pluging and the problem seems to disappear.

**Comment by the-djmaze** [comment]
Oh, i missed the part about Avatars plugin.
Yes, i also noticed bug regarding JSON service handling.

Should be fixed in next release.
