### ISSUE TITLE
Nextcloud login error - could not verify token

### ISSUE THREAD

**Issue by nonplusnl** [the-djmaze/snappymail#757]
When Nextcloud-snappymail active, closing the browser, restarting the browser (e.g. the next day) and the browser tab being restored to Nextcloud, there is a login error.
The website tries to reopen Netcloud-snappymail, and displays "An error occurred. Please refresh the page and try again. Failed loading ./?/AppData/0/930......2/"
When trying to refresh or open another Nextcloud extension (e.g. Files), I am taken to the Nextcloud login screen. Trying to login however just keeps on returning to the login screen. **Login is impossible until cookies are cleared**. 

**To Reproduce**
1. Open Snappymail extension
2. Close browser
3. Next day, reopen browser, restore Snappymail tab
4. Get error msg, failure to login to Nextcloud

**Expected behavior**
On browser tab restore, see Snappymail functional.
Alternatively, be able to re-login to Nextcloud _without_ having to clear cookies.

**Please complete the following information:**
- Browser: Firefox 107
- IMAP daemon: Dovecot, Exim running on Ubuntu 22.04
- PHP version: 8.1
- SnappyMail Version: 2.22.7 (problem appears to have started just a few .x-versions ago)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Nextcloud log entry:
{"reqId":"yb1...h0J","level":3,"time":"2022-12-07T20:17:14+01:00","remoteAddr":"2a02:........","user":"--","app":"core","method":"GET","url":"/npc/apps/snappymail/?/AppData/0/93...2/","message":"Tried to log in USER but could not verify token","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0","version":"25.0.1.1","data":{"app":"core"}}

**Additional context**
When the browser closes and reopens while another Nextcloud extension was active (e.g. Files), this problem does not occur. It is specific to Snappymail.

**Additional additional context**
Absolutely love Snappymail! Reminds me of the great configurability and speed of Roundcube, but without the burdensome back-end management

**Comment by the-djmaze** [comment]
The issue seems to be Nextcloud.
https://github.com/nextcloud/server/issues/33919

I think, because SnappyMail is fast and doesn't wait on DOMContentLoaded event, the AppData request is faster then the Nextcloud login process.

> Absolutely love Snappymail! Reminds me of the great configurability of Roundcube, but without the burdensome back-end management

Thanks!

**Comment by nonplusnl** [comment]
Seems you're right indeed. Funny in a way that in my case, I only run into the issue with Snappymail, probably because it's "too" fast.
