### ISSUE TITLE
Manual setting for 12/24h clock

### ISSUE THREAD

**Issue by scarleo** [the-djmaze/snappymail#760]
Can we please have the option to manually switch between 12/24h clock? I guess it's probably derived from some other locale setting on either the nextcloud account or browser or language in Snappymail or whatever, but please let me decide for myself whether 12 or 24 h clock makes sense in my situation regardless of location or language. Thank you.

**Comment by the-djmaze** [comment]
Setting is based on browser locales for used language.

And what is 24h, there are 4 options in browser:
- h11
- h12
- h23
- h24

This is because some languages say 0am or 12am
Or 23:59 -> 24:00 vs 00:00

**Comment by scarleo** [comment]
From my point of view it is not important if it is h23 or h24, what is annoying is using am/pm style just because I want my browser in english.
