### ISSUE TITLE
Not have button "Nextcloud file"

### ISSUE THREAD

**Issue by deviceh** [the-djmaze/snappymail#761]
![ncloud](https://user-images.githubusercontent.com/48836807/206759665-ad6b0f4b-96bc-4593-a1f7-6b9bd07f0592.PNG)
Hello, dear developers and people. I`m installed this apps, and don't have 
button "attachment nextcloud". Why this button not activate?

**Comment by the-djmaze** [comment]
1. You need Nextcloud
2. Nextcloud -> Apps -> install SnappyMail
3. Nextcloud -> Admin -> Adiitional settings -> NO iframe (use embed)
4. SnappyMail -> Admin -> Extensions active

**Comment by the-djmaze** [comment]
Resolve in https://github.com/the-djmaze/snappymail/commit/9fb7cd881faf2e55241944178b353c7220a98a9b
