### ISSUE TITLE
Messages aren't listed correctly with smartphone

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#764]
Messages aren't listed correctly with smartphone as following.

![SnappyMail smartphone](https://user-images.githubusercontent.com/5249848/206875262-2929b4c6-5888-4eb8-9e4e-6d4b8b1a4a44.png)

I tried following browsers and the problem happens with all of them.

- Google Chrome for Android 108.0.5359.79
- Microsoft Edge for Android 107.0.1418.62
- Mozilla Firefox for Android 107.2.0

I have 2 instances of SnappyMail.

1. Instance A
   - OS: FreeBSD 13.1-RELEASE amd64
   - IMAP server: Dovecot 2.3.19.1
   - PHP: 8.1.13
   - SnappyMail: 2.23.0
2. Instance B
   - OS: Debian 11.5 amd64
   - IMAP server: Dovecote 2.3.13
   - PHP: 7.4.33
   - SnappyMail: 2.23.0

And the problem only happens with the former.

**Comment by the-djmaze** [comment]
Can you compare installed PHP extensions on both Admin -> About pages.
An d find differences?

**Comment by the-djmaze** [comment]
You can also save email as .eml
Anonimise with text editor
Then upload here so i can test.
Or forward as attachment to issue764@snappymail.eu

**Comment by yasuhirokimura** [comment]
> Can you compare installed PHP extensions on both Admin -> About pages.
> And find differences?

Instance A:
- PHP 8.1.13
- APCu
- cURL
- GnuPG
- GD
- iconv
- intl
- OpenSSL 1.1.1o-freebsd 3 May 2022
- pdo_sqlite
- Sodium
- Tidy
- uuid
- Zip
- Fileinfo
- Phar

Instance B:
- PHP 7.4.33
- APCu
- cURL
- GnuPG
- GD
- iconv
- intl
- OpenSSL 1.1.1n 15 Mar 2022
- pdo_sqlite
- Sodium
- Tidy
- uuid
- Zip
- Fileinfo
- Phar

The difference is version of PHP and OpenSSL

> You can also save email as .eml
> Anonimise with text editor
> Then upload here so i can test.

The problem happens not only with Inbox but any other folder.
And it also happens even if there is no message in the folder as following.

![SnappyMail smartphone 2](https://user-images.githubusercontent.com/5249848/206879339-eabb285b-f936-4016-97f6-c65277160a71.png)

So it doesn't seem the problem is related to specific message.

**Comment by the-djmaze** [comment]
Could you enable debug mode and look in the SnappyMail debug log and the PHP debug log to find issues?

**Comment by yasuhirokimura** [comment]
I noticed the problem on instance A disappears if I disable Avatars extension from admin panel.
I also noticed version of Avaters extension is 1.4 on instance A but 1.3 on instance B.
I updated the latter to 1.4 and now the problem also happens with instance B.
So there seems to be something wrong with Avaters extension 1.4.

**Comment by the-djmaze** [comment]
This could be a JavaScript cache issue as i can't reproduce the problem.
Try with Admin -> Config -> `use_app_debug_js` on

**Comment by yasuhirokimura** [comment]
The problem dissappears if I disable `Delay lookup loading` in Avaters extension settings.

> Try with Admin -> Config -> use_app_debug_js on

I enabled it but there seems to be no changes.

**Comment by the-djmaze** [comment]
> The problem dissappears if I disable `Delay lookup loading` in Avaters extension settings.

Ok, i will try it
