### ISSUE TITLE
slow-startup-of-snappymail

### ISSUE THREAD

**Issue by rabadumpf** [the-djmaze/snappymail#765]
**Describe the bug**
The start of the Snappymail app takes about 15 seconds each time until the interface appears

**To Reproduce**
1. Go to 'nextcloud'
2. Click on 'E-Mail Snappymail'
3. Wait ca. 15-20 sec

**Expected behavior**
The interfache of snappymail appears in ca. 2-3 sec

**Please complete the following information:**
- Browser: google-chrome 108.0.5359.98, firefox 107.0.1,  14, the same mobile browser
- IMAP secureimap.t-online.de 
- PHP version:8.1.13
- SnappyMail Version:2.23.0
- nextcloud Hub 3 25.0.2

**Comment by the-djmaze** [comment]
In issue #593 you can find a lot of information how to debug your connection and server speeds.

Please read and try if you can find out why it is slow.

**Comment by rabadumpf** [comment]
Hello, sorry for the late reply: I tested 4 mail accounts. Here is the result:
1. domain t-online.de takes about 15 seconds to start, even if the "use_list_status" option is switched off.
2. domain gmx.de starts immediately in about 2 seconds without any problems - super.
3. Domain gmail cannot be set up: "Alert application-specific password required: https://support.google.com/accounts/answer/185833 (Failure..)"
4. Domain vodafonemail.de cannot be set up: "stream_socket_client(): unable to connect to ssl://vodafonemail.de:993 (Connection refused)"

**Comment by the-djmaze** [comment]
Enable debug logging and try t-online again.
The log will give you enough info why it is slow.

Gmail is "ok" in speed here, so if you don't know how to setup app passphrase then ignore this one.

**Comment by rabadumpf** [comment]
Where is the debug file? 
On which path can the debug file be found?

**Comment by the-djmaze** [comment]
You can find information at https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by rabadumpf** [comment]
`[2022-12-28 15:07:46.676][dc55e01f] IMAP[INFO]: Disconnected from "ssl://secureimap.t-online.de:993" (success)
22657 [2022-12-28 15:07:46.676][dc55e01f] IMAP[DEBUG]: 0.455561876297 (net session)
22658 [2022-12-28 15:07:46.677][dc55e01f] [INFO]: Memory peak usage: 6MB
22659 [2022-12-28 15:07:46.677][dc55e01f] [INFO]: Time delta: 0.4908881187439
22660 [2022-12-28 15:07:51.053][40faa94e] [INFO]: [SM:2.24.3][IP:31.19.133.126][PID:13504][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://huerbencloud.dynv6.net/index.php/apps/snappymail/?/Json>
22661 [2022-12-28 15:07:51.055][40faa94e] JSON[INFO]: Action: DoMessage
22662 [2022-12-28 15:07:51.056][40faa94e] IMAP[INFO]: Start connection to "ssl://secureimap.t-online.de:993"
22663 [2022-12-28 15:07:51.176][40faa94e] IMAP[INFO]: Connect (success)
22664 [2022-12-28 15:07:51.177][40faa94e] IMAP[DEBUG]: 0.12091708183289 (raw connection)
22665 [2022-12-28 15:07:51.212][40faa94e] IMAP[INFO]: < * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)\r\n
22666 [2022-12-28 15:07:51.213][40faa94e] IMAP[DEBUG]: 0.1571090221405 (*)
22667 [2022-12-28 15:07:51.213][40faa94e] IMAP[INFO]: > TAG1 LOGIN "xxxxx@t-online.de" "*******"\r\n
22668 [2022-12-28 15:07:51.268][40faa94e] IMAP[INFO]: < TAG1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILD>
22669 [2022-12-28 15:07:51.269][40faa94e] IMAP[DEBUG]: 0.055311918258667 (TAG1)
22670 [2022-12-28 15:07:51.270][40faa94e] IMAP[INFO]: > TAG2 EXAMINE "INBOX"\r\n
22671 [2022-12-28 15:07:51.301][40faa94e] IMAP[INFO]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk DTAG_document DTAG_image $Forwarded $MDNSent $ReadReceipt Junk xFROMxSU5CT1g= Forwarded $label1 $HasNoAttachment $HasAttachment)>
22672 [2022-12-28 15:07:51.301][40faa94e] IMAP[INFO]: < * OK [PERMANENTFLAGS ()] Read-only mailbox.\r\n
22673 [2022-12-28 15:07:51.301][40faa94e] IMAP[INFO]: < * 25 EXISTS\r\n
22674 [2022-12-28 15:07:51.301][40faa94e] IMAP[INFO]: < * 0 RECENT\r\n
22676 [2022-12-28 15:07:51.301][40faa94e] IMAP[INFO]: < * OK [UIDVALIDITY 1428838180] UIDs valid\r\n
22677 [2022-12-28 15:07:51.302][40faa94e] IMAP[INFO]: < * OK [UIDNEXT 40849] Predicted next UID\r\n
22678 [2022-12-28 15:07:51.302][40faa94e] IMAP[INFO]: < * OK [HIGHESTMODSEQ 130042] Highest\r\n
22679 [2022-12-28 15:07:51.302][40faa94e] IMAP[INFO]: < TAG2 OK [READ-ONLY] Examine completed (0.002 + 0.000 + 0.001 secs).\r\n
22680 [2022-12-28 15:07:51.302][40faa94e] IMAP[DEBUG]: 0.032289981842041 (TAG2)
22681 [2022-12-28 15:07:51.303][40faa94e] IMAP[INFO]: > TAG3 UID FETCH 40835 (UID RFC822.SIZE BODYSTRUCTURE)\r\n
22682 [2022-12-28 15:07:51.345][40faa94e] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 BODYSTRUCTURE ((("text" "plain" ("charset" "utf-8") NIL NIL "quoted-printable" 1418 49 NIL NIL NIL NIL)("text" "html" ("charset" "utf-8") NIL NIL>
22683 [2022-12-28 15:07:51.345][40faa94e] IMAP[INFO]: < TAG3 OK Fetch completed (0.001 + 0.000 secs).\r\n
22684 [2022-12-28 15:07:51.345][40faa94e] IMAP[DEBUG]: 0.042979955673218 (TAG3)
22685 [2022-12-28 15:07:51.346][40faa94e] IMAP[INFO]: > TAG4 UID FETCH 40835 (UID RFC822.SIZE INTERNALDATE FLAGS BODY.PEEK[HEADER.FIELDS (RETURN-PATH RECEIVED MIME-VERSION MESSAGE-ID CONTENT-TYPE FROM TO CC BCC SENDER REPLY-TO DELIVERED-TO IN>
22686 [2022-12-28 15:07:51.377][40faa94e] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 INTERNALDATE "28-Dec-2022 05:54:39 +0100" FLAGS (\Seen $HasNoAttachment) BODY[HEADER.FIELDS (RETURN-PATH RECEIVED MIME-VERSION MESSAGE-ID CONTENT>
22687 [2022-12-28 15:07:51.377][40faa94e] IMAP[INFO]: <  BODY[1.1] {1418}\r\n
22688 [2022-12-28 15:07:51.378][40faa94e] IMAP[INFO]: <  BODY[1.2] {70617}\r\n
22689 [2022-12-28 15:07:51.446][40faa94e] IMAP[INFO]: < )\r\n
22690 [2022-12-28 15:07:51.446][40faa94e] IMAP[INFO]: < TAG4 OK Fetch completed (0.006 + 0.000 + 0.005 secs).\r\n
22691 [2022-12-28 15:07:51.446][40faa94e] IMAP[DEBUG]: 0.1003839969635 (TAG4)
22692 [2022-12-28 15:07:51.456][40faa94e] JSON[INFO]: {"Action":"Message","Result":{"@Object":"Object\/Message","Folder":"INBOX","Uid":40835,"subject":"DER TAG im Westallgäu | 28.12.2022","encrypted":false,"MessageId":"<n%3D5c5y5.1601s4m%2Cu%>
22693 [2022-12-28 15:07:51.456][40faa94e] IMAP[INFO]: > TAG5 LOGOUT\r\n
22694 [2022-12-28 15:07:51.486][40faa94e] IMAP[INFO]: < * BYE Logging out\r\n
[2022-12-28 15:07:51.486][40faa94e] IMAP[INFO]: < TAG5 OK Logout completed (0.001 + 0.000 secs).\r\n
22696 [2022-12-28 15:07:51.487][40faa94e] IMAP[DEBUG]: 0.030441045761108 (TAG5)
22697 [2022-12-28 15:07:51.487][40faa94e] IMAP[INFO]: Disconnected from "ssl://secureimap.t-online.de:993" (success)
22698 [2022-12-28 15:07:51.487][40faa94e] IMAP[DEBUG]: 0.43141508102417 (net session)
22699 [2022-12-28 15:07:51.488][40faa94e] [INFO]: Memory peak usage: 6MB
22700 [2022-12-28 15:07:51.488][40faa94e] [INFO]: Time delta: 0.46894598007202
22701 [2022-12-28 15:07:51.567][b2a9236c] [INFO]: [SM:2.24.3][IP:31.19.133.126][PID:13554][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://huerbencloud.dynv6.net/index.php/apps/snappymail/?/Raw/>
22702 [2022-12-28 15:07:51.570][b2a9236c] IMAP[INFO]: Start connection to "ssl://secureimap.t-online.de:993"
22703 [2022-12-28 15:07:51.717][b2a9236c] IMAP[INFO]: Connect (success)
22704 [2022-12-28 15:07:51.717][b2a9236c] IMAP[DEBUG]: 0.14744687080383 (raw connection)
22705 [2022-12-28 15:07:51.753][b2a9236c] IMAP[INFO]: < * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)\r\n
22706 [2022-12-28 15:07:51.754][b2a9236c] IMAP[DEBUG]: 0.18408703804016 (*)
22707 [2022-12-28 15:07:51.754][b2a9236c] IMAP[INFO]: > TAG1 LOGIN "xxxxxx@t-online.de" "*******"\r\n
22708 [2022-12-28 15:07:51.798][b2a9236c] IMAP[INFO]: < TAG1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILD>
22709 [2022-12-28 15:07:51.799][b2a9236c] IMAP[DEBUG]: 0.044451951980591 (TAG1)
22710 [2022-12-28 15:07:51.800][b2a9236c] IMAP[INFO]: > TAG2 EXAMINE "INBOX"\r\n
22711 [2022-12-28 15:07:51.832][b2a9236c] IMAP[INFO]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk DTAG_document DTAG_image $Forwarded $MDNSent $ReadReceipt Junk xFROMxSU5CT1g= Forwarded $label1 $HasNoAttachment $HasAttachment)>
22712 [2022-12-28 15:07:51.832][b2a9236c] IMAP[INFO]: < * OK [PERMANENTFLAGS ()] Read-only mailbox.\r\n
22713 [2022-12-28 15:07:51.832][b2a9236c] IMAP[INFO]: < * 25 EXISTS\r\n
22714 [2022-12-28 15:07:51.832][b2a9236c] IMAP[INFO]: < * 0 RECENT\r\n
 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: < * OK [UNSEEN 20] First unseen.\r\n
22716 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: < * OK [UIDVALIDITY 1428838180] UIDs valid\r\n
22717 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: < * OK [UIDNEXT 40849] Predicted next UID\r\n
22718 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: < * OK [HIGHESTMODSEQ 130042] Highest\r\n
22719 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: < TAG2 OK [READ-ONLY] Examine completed (0.001 + 0.000 secs).\r\n
22720 [2022-12-28 15:07:51.833][b2a9236c] IMAP[DEBUG]: 0.033373832702637 (TAG2)
22721 [2022-12-28 15:07:51.833][b2a9236c] IMAP[INFO]: > TAG3 UID FETCH 40835 (UID RFC822.SIZE BODY.PEEK[2.MIME])\r\n
22722 [2022-12-28 15:07:51.868][b2a9236c] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 BODY[2.MIME] {180}\r\n
22723 [2022-12-28 15:07:51.869][b2a9236c] IMAP[INFO]: < )\r\n
22724 [2022-12-28 15:07:51.869][b2a9236c] IMAP[INFO]: < TAG3 OK Fetch completed (0.004 + 0.000 + 0.003 secs).\r\n
22725 [2022-12-28 15:07:51.869][b2a9236c] IMAP[DEBUG]: 0.035835981369019 (TAG3)
22726 [2022-12-28 15:07:51.872][b2a9236c] IMAP[INFO]: > TAG4 UID FETCH 40835 (UID RFC822.SIZE BINARY.PEEK[2])\r\n
22727 [2022-12-28 15:07:51.906][b2a9236c] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 BINARY[2] ~{7216}\r\n
22728 [2022-12-28 15:07:51.906][b2a9236c] IMAP[INFO]: Start Callback for FETCH / BINARY[2] - try to read 7216 bytes.
22729 [2022-12-28 15:07:51.907][b2a9236c] IMAP[INFO]: End Callback for FETCH / BINARY[2] - feof = good
22730 [2022-12-28 15:07:51.907][b2a9236c] IMAP[INFO]: < )\r\n
22731 [2022-12-28 15:07:51.907][b2a9236c] IMAP[INFO]: < TAG4 OK Fetch completed (0.001 + 0.000 secs).\r\n
22732 [2022-12-28 15:07:51.907][b2a9236c] IMAP[DEBUG]: 0.035139083862305 (TAG4)
22733 [2022-12-28 15:07:51.907][b2a9236c] IMAP[INFO]: > TAG5 LOGOUT\r\n
22734 [2022-12-28 15:07:51.920][3567e484] [INFO]: [SM:2.24.3][IP:31.19.133.126][PID:13817][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GEThttps://huerbencloud.dynv6.net/index.php/apps/snappymail/?/Raw/>
[2022-12-28 15:07:51.925][3567e484] IMAP[INFO]: Start connection to "ssl://secureimap.t-online.de:993"
22736 [2022-12-28 15:07:51.944][b2a9236c] IMAP[INFO]: < * BYE Logging out\r\n
22737 [2022-12-28 15:07:51.944][b2a9236c] IMAP[INFO]: < TAG5 OK Logout completed (0.001 + 0.000 secs).\r\n
22738 [2022-12-28 15:07:51.944][b2a9236c] IMAP[DEBUG]: 0.037467002868652 (TAG5)
22739 [2022-12-28 15:07:51.945][b2a9236c] IMAP[INFO]: Disconnected from "ssl://secureimap.t-online.de:993" (success)
22740 [2022-12-28 15:07:51.945][b2a9236c] IMAP[DEBUG]: 0.37508797645569 (net session)
22741 [2022-12-28 15:07:51.945][b2a9236c] [INFO]: Memory peak usage: 14MB
22742 [2022-12-28 15:07:51.945][b2a9236c] [INFO]: Time delta: 0.40859603881836
22743 [2022-12-28 15:07:52.065][3567e484] IMAP[INFO]: Connect (success)
22744 [2022-12-28 15:07:52.065][3567e484] IMAP[DEBUG]: 0.13962888717651 (raw connection)
22745 [2022-12-28 15:07:52.099][3567e484] IMAP[INFO]: < * OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)\r\n
22746 [2022-12-28 15:07:52.100][3567e484] IMAP[DEBUG]: 0.17477011680603 (*)
22747 [2022-12-28 15:07:52.101][3567e484] IMAP[INFO]: > TAG1 LOGIN "xxxxxx@t-online.de" "*******"\r\n
22748 [2022-12-28 15:07:52.145][3567e484] IMAP[INFO]: < TAG1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILD>
22749 [2022-12-28 15:07:52.146][3567e484] IMAP[DEBUG]: 0.044971942901611 (TAG1)
22750 [2022-12-28 15:07:52.147][3567e484] IMAP[INFO]: > TAG2 EXAMINE "INBOX"\r\n
22751 [2022-12-28 15:07:52.178][3567e484] IMAP[INFO]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk DTAG_document DTAG_image $Forwarded $MDNSent $ReadReceipt Junk xFROMxSU5CT1g= Forwarded $label1 $HasNoAttachment $HasAttachment)>
22752 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * OK [PERMANENTFLAGS ()] Read-only mailbox.\r\n
22753 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * 25 EXISTS\r\n
22754 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * 0 RECENT\r\n
5 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * OK [UNSEEN 20] First unseen.\r\n
22756 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * OK [UIDVALIDITY 1428838180] UIDs valid\r\n
22757 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * OK [UIDNEXT 40849] Predicted next UID\r\n
22758 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < * OK [HIGHESTMODSEQ 130042] Highest\r\n
22759 [2022-12-28 15:07:52.179][3567e484] IMAP[INFO]: < TAG2 OK [READ-ONLY] Examine completed (0.002 + 0.000 + 0.001 secs).\r\n
22760 [2022-12-28 15:07:52.179][3567e484] IMAP[DEBUG]: 0.03286600112915 (TAG2)
22761 [2022-12-28 15:07:52.180][3567e484] IMAP[INFO]: > TAG3 UID FETCH 40835 (UID RFC822.SIZE BODY.PEEK[3.MIME])\r\n
22762 [2022-12-28 15:07:52.213][3567e484] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 BODY[3.MIME] {180}\r\n
22763 [2022-12-28 15:07:52.214][3567e484] IMAP[INFO]: < )\r\n
22764 [2022-12-28 15:07:52.214][3567e484] IMAP[INFO]: < TAG3 OK Fetch completed (0.006 + 0.000 + 0.005 secs).\r\n
22765 [2022-12-28 15:07:52.214][3567e484] IMAP[DEBUG]: 0.034364938735962 (TAG3)
22766 [2022-12-28 15:07:52.216][3567e484] IMAP[INFO]: > TAG4 UID FETCH 40835 (UID RFC822.SIZE BINARY.PEEK[3])\r\n
22767 [2022-12-28 15:07:52.247][3567e484] IMAP[INFO]: < * 17 FETCH (UID 40835 RFC822.SIZE 106715 BINARY[3] ~{3627}\r\n
22768 [2022-12-28 15:07:52.247][3567e484] IMAP[INFO]: Start Callback for FETCH / BINARY[3] - try to read 3627 bytes.
22769 [2022-12-28 15:07:52.248][3567e484] IMAP[INFO]: End Callback for FETCH / BINARY[3] - feof = good
22770 [2022-12-28 15:07:52.248][3567e484] IMAP[INFO]: < )\r\n
22771 [2022-12-28 15:07:52.248][3567e484] IMAP[INFO]: < TAG4 OK Fetch completed (0.001 + 0.000 secs).\r\n
22772 [2022-12-28 15:07:52.248][3567e484] IMAP[DEBUG]: 0.031944990158081 (TAG4)
22773 [2022-12-28 15:07:52.248][3567e484] IMAP[INFO]: > TAG5 LOGOUT\r\n
22774 [2022-12-28 15:07:52.286][3567e484] IMAP[INFO]: < * BYE Logging out\r\n
22775 [2022-12-28 15:07:52.286][3567e484] IMAP[INFO]: < TAG5 OK Logout completed (0.001 + 0.000 secs).\r\n
22776 [2022-12-28 15:07:52.286][3567e484] IMAP[DEBUG]: 0.038243055343628 (TAG5)
22777 [2022-12-28 15:07:52.287][3567e484] IMAP[INFO]: Disconnected from "ssl://secureimap.t-online.de:993" (success)
22778 [2022-12-28 15:07:52.287][3567e484] IMAP[DEBUG]: 0.36146402359009 (net session)
22779 [2022-12-28 15:07:52.287][3567e484] [INFO]: Memory peak usage: 6MB
22780 [2022-12-28 15:07:52.287][3567e484] [INFO]: Time delta: 0.42834711074829
22781 [2022-12-28 15:07:59.582][0d987303] [INFO]: [SM:2.24.3][IP:31.19.133.126][PID:13554][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://huerbencloud.dynv6.net/index.php/settings/admin/additio>
22782 [2022-12-28 15:07:59.598][0d987303] [INFO]: Memory peak usage: 8MB
22783 [2022-12-28 15:07:59.598][0d987303] [INFO]: Time delta: 0.060660839080811
22784 [2022-12-28 15:08:01.951][60044b5b] [INFO]: [SM:2.24.3][IP:31.19.133.126][PID:13817][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://huerbencloud.dynv6.net/index.php/apps/snappymail/fetch>
22785 [2022-12-28 15:08:01.953][60044b5b] [INFO]: Memory peak usage: 6MB
22786 [2022-12-28 15:08:01.953][60044b5b] [INFO]: Time delta: 0.043304920196533
`
can you see the error?

**Comment by rabadumpf** [comment]
Interesting:
the gmx log contains only 137 lines, which also includes AUTHENTICATE PLAIN, for example

the log from t-online.de (which takes about 20 seconds to open) contains 22755 lines. A search for AUTHENTICATE PLAIN returned no hits

**Comment by rabadumpf** [comment]
Interesting, t-online.de log : from line 47 the inbox is called, then more than 21000 follow! Enter lines with the entries /private/vendor/fun/extended-listview.... This is probably the reason for the long login. But how do I get rid of them?

....
   45 [2022-12-30 07:59:56.383][882940d7] IMAP[DEBUG]: 0.043995141983032 (TAG1)
   46 [2022-12-30 07:59:56.384][882940d7] IMAP[INFO]: > TAG2 GETMETADATA (DEPTH infinity) "*" ("/shared" "/private")\r\n
   47 [2022-12-30 07:59:56.421][882940d7] IMAP[INFO]: < * **METADATA INBOX** (/private/vendor/fun/extended-listview/00000a2829701861d1210000fae99ed3/teaser {115}\r\n
   48 [2022-12-30 07:59:56.422][882940d7] IMAP[INFO]: <  /private/vendor/fun/extended-listview/0000401f1849cf6113b900002f94d9b7/attachmentinfo/2 {92}\r\n
   49 [2022-12-30 07:59:56.422][882940d7] IMAP[INFO]: <  /private/vendor/fun/extended-listview/0000401f1849cf6113b900002f94d9b7/attachments/2 {43220}\r\n
...
...
...
22530 [2022-12-30 08:00:12.327][882940d7] IMAP[INFO]: <  /private/vendor/fun/extended
listview/ffa6f43971e886612e4a0000fae99ed3/teaser {0}\r\n
22531 [2022-12-30 08:00:12.327][882940d7] IMAP[INFO]: <  /private/vendor/fun/extended-listview/fff6c8169c67f061bd020000fae99ed3/teaser {117}\r\n
22532 [2022-12-30 08:00:12.327][882940d7] IMAP[INFO]: < )\r\n
22533 [2022-12-30 08:00:12.342][882940d7] IMAP[INFO]: < * **METADATA INBOX.Spam** (/private/specialuse {5}\r\n
22534 [2022-12-30 08:00:12.342][882940d7] IMAP[INFO]: < )\r\n
22535 [2022-12-30 08:00:12.343][882940d7] IMAP[INFO]: < * **METADATA INBOX.Trash** (/private/specialuse {6}\r\n
22536 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < )\r\n
22537 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < * **METADATA INBOX.Sent** (/private/specialuse {5}\r\n
22538 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < )\r\n
22539 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < * **METADATA INBOX.Drafts** (/private/specialuse {7}\r\n
22540 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < )\r\n
22541 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: < TAG2 OK Getmetadata completed (0.703 + 7.857 + 8.559 secs).\r\n
22542 [2022-12-30 08:00:12.344][882940d7] IMAP[DEBUG]: **15.959731817245** (TAG2)
22543 [2022-12-30 08:00:12.344][882940d7] IMAP[INFO]: > TAG3 LIST "" "*" RETURN (SUBSCRIBED SPECIAL-USE STATUS (MESSAGES UNSEEN UIDNEXT UIDVALIDITY HIGHESTMODSEQ))\r\n
22544 [2022-12-30 08:00:12.379][882940d7] IMAP[INFO]: < * LIST () "." INBOX\r\n
22545 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * LIST (\Subscribed \UnMarked \Junk) "." INBOX.Spam\r\n
22546 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * STATUS INBOX.Spam (MESSAGES 0 UIDNEXT 1 UIDVALIDITY 1428838206 UNSEEN 0 HIGHESTMODSEQ 1)\r\n
22547 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * LIST (\Subscribed \UnMarked \Trash) "." INBOX.Trash\r\n
22548 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * STATUS INBOX.Trash (MESSAGES 5 UIDNEXT 43347 UIDVALIDITY 1428838183 UNSEEN 3 HIGHESTMODSEQ 50088)\r\n
22549 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * LIST (\Subscribed \UnMarked \Sent) "." INBOX.Sent\r\n
22550 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * STATUS INBOX.Sent (MESSAGES 13 UIDNEXT 3276 UIDVALIDITY 1428838182 UNSEEN 0 HIGHESTMODSEQ 5477)\r\n
22551 [2022-12-30 08:00:12.380][882940d7] IMAP[INFO]: < * LIST (\Subscribed \UnMarked \Drafts) "." INBOX.Drafts\r\n
22552 [2022-12-30 08:00:12.381][882940d7] IMAP[INFO]: < * STATUS INBOX.Drafts (MESSAGES 7 UIDNEXT 3377 UIDVALIDITY 1428838181 UNSEEN 0 HIGHESTMODSEQ 9774)\r\n
22553 [2022-12-30 08:00:12.381][882940d7] IMAP[INFO]: < TAG3 OK List completed (0.001 + 0.000 secs).\r\n
22554 [2022-12-30 08:00:12.381][882940d7] IMAP[DEBUG]: 0.036616086959839 (TAG3)

**Comment by rabadumpf** [comment]
ok, disable "metadata" bring the solution.
You can close this thread. Thanks.

**Comment by the-djmaze** [comment]
Great find! The METADATA of t-online.de is really overloaded.

Searching online for `private/vendor/fun/extended-listview` has zero results so they probably screwed something up internally.
