### ISSUE TITLE
allowing html inside custom theme

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#767]
**Is your feature request related to a problem? Please describe.**
looking for something to change the ui of the theme.But only css is allowerd but adding  some custom design also need html code

**Describe the solution you'd like**
allowing html to fetch from theme in case of custom design. But if there is no html then take it from default html folder.

**Describe alternatives you've considered**
blocked on adding custom html design which require html not skin changes with css

**Additional context**

**Comment by the-djmaze** [comment]
What kind of custom design do you need in HTML?

**Comment by avinash-0007** [comment]
i wanted to move icons ordering and wanted to have a single top bar containing all the icons.
for e.g
![screensho11](https://user-images.githubusercontent.com/21700809/207033949-f677089b-d97d-4d5a-8325-bf6534428fb1.png)

**Comment by the-djmaze** [comment]
You can reorder icons using CSS flex or grid.

All the icons would be hard, did you try and see how much space you have in mobile view?

**Comment by avinash-0007** [comment]
for mobile i will hide some icons.

And i wanted to add a single top bar with new messgae and all other icons on it.like above design
![207033949-f677089b-d97d-4d5a-8325-bf6534428fb1](https://user-images.githubusercontent.com/21700809/207242174-69ebcde7-7e2a-4724-87c3-75d36e9e9dc9.png)

Is is possible to have something like custom html inside theme folder?

**Comment by the-djmaze** [comment]
> Is is possible to have something like custom html inside theme folder?

That is not possible due to how templates are created and your theme with crash when there are modifications in the core.

Instead, you could write a plugin/extension that modifies templates.
For example:
* the Avatars extension modifies the MessageList and Message view templates to inject graphics.
* the Nextcloud extension modifies menus and composer window.

**Comment by the-djmaze** [comment]
Now documented at https://github.com/the-djmaze/snappymail/wiki/Custom-Themes
