### ISSUE TITLE
Possible to rename constants in index.php

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#768]
**Describe the bug**

Is it possible to rename constants in [index.php](https://github.com/the-djmaze/snappymail/blob/master/index.php), as it creating a conflict when both rainloop and snappymail apps enabled in same instance. It would be better if we renamed the constants

**To Reproduce**
1. Go to a nextcloud instance
2. Enable both rainloop and snappymail apps
3. Try to logout from nextcloud app
4. See error `[105] Missing version directory`

**Expected behavior**

Successful logout

**Screenshots**

![image](https://user-images.githubusercontent.com/16881005/207110352-611501ad-d842-49d9-b6f2-e1ca47f2ad50.png)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Renaming is not an option.
You can't use both for many more complicated reasons then this simple issue.

**Comment by Niveshkrishna** [comment]
@the-djmaze Interesting, can you tell me why both apps cannot work simultaneously? The reason why I'm asking is because we are interested in doing a staged roll out of snappymail to our users who are currently using rainloop. We do not want to enable snappymail for all users, so want to understand what could be the problem here?

**Comment by Niveshkrishna** [comment]
@the-djmaze I understand, so I will probably change namespace in rainloop app and will let snappymail be as it is to continue receiving updates. Thanks for your inputs
