### ISSUE TITLE
Admin/Contacts cannot be opened

### ISSUE THREAD

**Issue by tomszilagyi** [the-djmaze/snappymail#77]
**Describe the bug**
It seems that I cannot click on Contacts on the left in the Admin page.
If I click on it, nothing happens (the other menu items work fine).
This seems like a regression in this RC.

**To Reproduce**
1. Go to ?admin
2. Click on the menu items on the left, General, Domains, etc., see that they load their respective pages
3. Observe that nothing happens when you click on Contacts

**Expected behavior**
I should be able to enable saving the contacts to database.

**Desktop (please complete the following information):**
 - Browser: Firefox 78.9.0esr
 - SnappyMail Version: 2.5.0-rc1

**Additional context**
I used SnappyMail 2.4.3 before, and it worked, so this looks like a regression.

**Comment by the-djmaze** [comment]
The Contacts addressbook system is changed to replace the old Sabre/DAV.
Will run some more tests to test it.

**Comment by the-djmaze** [comment]
It works here.
Do you have a php error log?

**Comment by tomszilagyi** [comment]
Another observation of note: on a different browser (Android Chrome 89.0) it looks slightly different. Here, if I click on Contacts, the selection highlight will not be removed from the previous menu item, and Contacts will be highlighted as well (but nothing else will happen - no requests to the server). So there will be two menu items on the left being highlighted as selected. To me this indicates that it might be JavaScript-related (or at least something on the browser side).

**Comment by the-djmaze** [comment]
I can't get this reproduced on any Firefox and Chrome.

Could you open the 'Web Developer Tools' in your Firefox and check the console for errors?

**Comment by tomszilagyi** [comment]
![SnappyMail_Admin_Contacts_console](https://user-images.githubusercontent.com/5454768/114168265-4fb9f900-9930-11eb-96c7-8c6103dfaaf9.png)

**Comment by the-djmaze** [comment]
Ah, your supportedTypes is not an array.
This is strange, because when there are no PDO drivers it should be an empty array.

Try with https://github.com/the-djmaze/snappymail/releases/tag/v2.5.0-rc.2

**Comment by tomszilagyi** [comment]
Nope, I get the exact same error:
![SnappyMail_Admin_Contacts_console_rc2](https://user-images.githubusercontent.com/5454768/114181337-ada30c80-9941-11eb-8f89-132f99306179.png)

**Comment by tomszilagyi** [comment]
If I edit the URL in the browser to point to https://webmail.example.com/?/AdminAppData/0/ then I get a bunch of plaintext output that looks like this: `rl.initData({ ... bunch of JSON ... });` so I assume that the web request itself works. The bunch of JSON part contains this: `"supportedPdoDrivers":{"1":"sqlite"}`

**Comment by the-djmaze** [comment]
> The bunch of JSON part contains this: `"supportedPdoDrivers":{"1":"sqlite"}`

Hero!
I know the issue and can solve it.

**Comment by tomszilagyi** [comment]
Many thanks for the effort!

**Comment by the-djmaze** [comment]
You can redownload RC2 with the fix to test.
https://github.com/the-djmaze/snappymail/releases/download/v2.5.0-rc.2/snappymail-2.5.0-rc.2.tar.gz

**Comment by tomszilagyi** [comment]
I can confirm that it works -- Thanks for fixing!
