### ISSUE TITLE
Snappymail doesn't warn the user about message size limits of the smtp server

### ISSUE THREAD

**Issue by tokafondo** [the-djmaze/snappymail#779]
**Describe the bug**

When I try to send a message with a size greater than the one the smtp allows to send, Snappymail just shows an error message: "cannot send message". But doesn't warn the user about "why" the message can't be sent.

It was after investigation that I found that postfix had a limit that I raised and then Snappymail was more than happy to send my message out.

**Comment by the-djmaze** [comment]
Did you try `application.ini` (or Admin -> Config) to set `smtp_show_server_errors` to `On`?
