### ISSUE TITLE
Admin UI cannot be opened: Authentication failed

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#78]
**Describe the bug**
When I try to install SnappyMail as described at https://snappymail.eu/install.html, I get "Authentication failed".

**To Reproduce**
1. Unzip and copy SnappyMail 2.5.0-RC1 to your web server
2. Open www.url.com/mail/?admin
3. Enter admin and the password from the file "/data/_data_/_default_/admin_password.txt".
4. A yellow text box with "Authentication failed" appears.

**Expected behavior**
The login to the admin UI should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/2138442/114082814-7fc0b800-98ae-11eb-9c09-14276254af8f.png)

**Desktop (please complete the following information):**
 - Browser: Google Chrome 89, 64-bit
 - SnappyMail: 2.5.0-RC1

**Additional context**
In the PHP log I get the following error message:
[Thu Apr 08 21:03:15.842229 2021] [fcgid:warn] [pid 36059] [client 10.10.10.10:8080] mod_fcgid: stderr: AuthError[102]

**Comment by the-djmaze** [comment]
Password in admin_password.txt should be 12 characters.
What do you have?

**Comment by the-djmaze** [comment]
Ah i think i get it.
You created the file? Then remove it.
SnappyMail creates it.
When SnappyMail created it, open it

**Comment by phsc84** [comment]
Ah, this way it works. Then it was my fault.
Thank you!

**Comment by the-djmaze** [comment]
I've modified the install instructions a bit.
Hopefully it's more clear now.
