### ISSUE TITLE
Schedule send

### ISSUE THREAD

**Issue by eibex** [the-djmaze/snappymail#783]
I was wondering if scheduling emails would be feasible with the addition of a cronjob ran on the server.

**Comment by the-djmaze** [comment]
SnappyMail does not store login credentials and therefore can't send messages later.

The only feasible way is when the SMTP does not use login credentials at all, but since that is like russian roulette it would not worth the time to implement.

**Comment by eibex** [comment]
I feared that was the case, thanks!
