### ISSUE TITLE
unable to set up default credentials for gandi mail servers

### ISSUE THREAD

**Issue by xpseudonym** [the-djmaze/snappymail#785]
**Describe the bug**
Following instructions here:
https://github.com/the-djmaze/snappymail/blob/master/integrations/nextcloud/snappymail/README.md#how-to-auto-connect-to-snappymail
I'm unable to set up the default config for gandi mail's servers for my domain, see attached pic
![clipboard](https://user-images.githubusercontent.com/5032475/208757512-cf451c32-863a-4d05-a9f6-91a4bf3edd9e.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install up to date snappymail: v2.23.1
2. Follow above linked instructions
3. Config fails

**Expected behaviour**
config succeeds

**Screenshots**
See above screenshot

**Please complete the following information:**
- 102.5.0esr (64-bit)
- IMAP daemon: whatever Gandi uses for its mail service (Dovecot according to [this 4 year old blog](https://news.gandi.net/en/2018/07/fun-with-sieve-rules/)
- PHP version: v8.0
- SnappyMail Version: v2.23.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
The system is hosted by Hetzner

**Additional context**
The possibly useful error messages can't be read because they print over themselves and run off the page
PS I've configured with SSL/TLS etc - but, thought to run this config attempt clean for posting here

**Comment by xpseudonym** [comment]
I've just had a bit of success - with the SMTP config, not IMAP or Sieve - and noticed I can scroll the set-up window to reveal the error, so more info:-
1. The error message is: `stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known`
2. The succeeded SMTP pic:
![clipboard3](https://user-images.githubusercontent.com/5032475/208763757-5a4cb4ca-a2ab-4291-abc0-566f6a2e35f3.png)
3. And the full IMAP error for reference:
![clipboard1](https://user-images.githubusercontent.com/5032475/208763864-0b38bc36-9901-4e24-9b00-737d5fdc637d.png)
![clipboard2](https://user-images.githubusercontent.com/5032475/208763878-646541f3-2a47-4e20-9a9a-dddf30baf120.png)

**Comment by the-djmaze** [comment]
Restart your PHP-FPM and try again.
Mostly these DNS resolve issues are miraculously gone then.

**Comment by m-i-k-e-y** [comment]
Are you sure, you entered the correct server @xpseudonym? 

For SMTP, you entered mail.gandi.**net**, which seems to work, whereas for IMAP you entered mail.gandi.**nz**, which does not seem to work.

**Comment by xpseudonym** [comment]
@m-i-k-e-y err, isn't that just the sort of thing to file a bug report about...:
![clipboard4](https://user-images.githubusercontent.com/5032475/209008317-cba3b86f-0f1b-4af2-bb25-b697709aa364.png)
Thank YOUUUU!
