### ISSUE TITLE
No contact suggestions

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#786]
When composing a new email contact suggestions stopped working.

Checked database credentials and they are ok.

Database is ok.

Using 2.23.1

How can I solve this?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by chrisdent** [comment]
This two videos is what I'm experiencing:

```
fetchError
: 
DOMException: The user aborted a request.
aborted
: 
true
reason
: 
"TimeoutError"
code
: 
20
message
: 
"The user aborted a request."
name
: 
"AbortError"
```

https://user-images.githubusercontent.com/2196272/209175826-e8edc090-2b32-4991-b138-355cf998d1a0.mov


https://user-images.githubusercontent.com/2196272/209175848-6c2bf991-401a-438a-a6b8-9f24834e1d01.mov

**Comment by the-djmaze** [comment]
At the bottom, take look on the `Network` tab. It should have new requests for contacts suggestions.
Each request there will show you what the search result is and there you find the problem.

**Comment by MI-KY** [comment]
The description and also the first video seams a bit similar to #769...
Please tell us also if you maybe have activated some extensions / plugins like "Contact suggestions (IMAP folder)" and if yes the version you use.

**Comment by chrisdent** [comment]
Thanks!

1.0. Saw that there is an update available 1.1. But unable to update: Maybe a permission problem? but it does allows to install other extensions.

https://user-images.githubusercontent.com/2196272/209188980-6bf46313-8034-48d2-9782-292213ee0f02.mov

**Comment by MI-KY** [comment]
Please try logout of the admin panel and to reenter - I'm not sure but I think I had once the same problem and at the end only a simple refresh was needed...

**Comment by chrisdent** [comment]
> Please try logout of the admin panel and to re-enter - I'm not sure but I think I had once the same problem and at the end only a simple refresh was needed...

This is so awkward and silly from my side, but how to I log out from the admin panel?

Tried to log out from nextcloud but experiencing the same.

**Comment by MI-KY** [comment]
Hi,
i think the logout from nextcloud cloud already have been enough :+1: .
Looks like there is a problem with when updating the extensions... to investigate this some more logs could help - unfortunately I can't test this at the moment on my system...

**Comment by the-djmaze** [comment]
> Looks like there is a problem with when updating the extensions...

Not only the extensions. It seems to be an issue with Opcache.
The above commit should forcefully invalidate removed files.
As plugin updates remove old plugin completely this worked commit worked for me.

**Comment by chrisdent** [comment]
After updating the extension it works as expected!! thanks!!
