### ISSUE TITLE
snappymail on nextcloud mailbox access forbidden

### ISSUE THREAD

**Issue by franconianmetal** [the-djmaze/snappymail#788]
**Describe the bug**
running nextcloud 25.0.2
if updating to snappymail **2.23.1** I am forwarded to snappymail login page with my login-user displayed.
if entering my correct password the access is forbidden

**To Reproduce**
1. Update snappymail from **2.23.0 to  2.23.1**
2. in nextcloud click on 'snappymail'

**Expected behavior**
If clicking on snappymail-icon within nextcloud immediate display of mailbox-inbox as configured.
this is the past behaviour

**Screenshots**
none

**Please complete the following information:**
- Browser: firefox,chromium
- SnappyMail Version: 2.23.0
- nextcloud: 25.0.2
- PHP version:
> 
> PHP 7.4.33 (cli) (built: Nov  8 2022 11:35:02) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

**Comment by the-djmaze** [comment]
What happens when you enable logging/debugging?
Do you notice errors in Browser Console or server logs?

**Comment by franconianmetal** [comment]
catched browser's console as attached
[browser_console.txt](https://github.com/the-djmaze/snappymail/files/10288482/browser_console.txt)

**Comment by the-djmaze** [comment]
Please fill in your passphrase manually and see if that works.
Somehow the passphrase seems to be incorrect.

**Comment by franconianmetal** [comment]
as I wrote when startung this issue:

_entering my correct password the access is forbidden_

**Comment by the-djmaze** [comment]
Ok, then:
1. go to Nextcloud -> Admin -> Additional Settings.
2. Enable the SnappyMail debug mode
3. Login attempt
4. Disable the SnappyMail debug mode
5. Look at SnappyMail log

It should give you a very detailed log why IMAP login fails.

**Comment by franconianmetal** [comment]
imap connect sucess
imap disconnect success
but snappymail does not forward me to mailbox.

[log-2022-12-22.txt](https://github.com/the-djmaze/snappymail/files/10291873/log-2022-12-22.txt)

**Comment by franconianmetal** [comment]
updating from 2.23.0 to 2.24.0:
error does not appear.
login works as expected when clicking snappy-icon in nextcloud
