### ISSUE TITLE
Attachments in mails in 2.24 not loading in reply/forward

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#789]
With version 2.24 existing attachments of older mails are not loaded during the "Reply" or "forward" and shown as red attachments.

I got few mails from persons with their signatures including some images. (i. e. Linkedin, Insta, ...) or existing attachments.
When i want to answer or forward these mails, I got an error "red attachment" from these mails during my reply/forward. 
Uploading new attachments works fine.

Same behaviour in https://snappymail.eu/demo/

**Comment by the-djmaze** [comment]
Confirmed, was caused due to wrong fix for #466

**Comment by rvgeerligs** [comment]
I have the same issue with all attachements in version 2.24.2
