### ISSUE TITLE
Can't add multiple accounts on different domains

### ISSUE THREAD

**Issue by Niemand112233** [the-djmaze/snappymail#791]
Hi,

i created as in my old rainloop client all domains I need and then added in the web GUI of snappymail the accounts of these domains. However, they don't appear in the drop down on the right side of the screen. If I try to add them again it tells me "already added".

What's wrong?

**Comment by the-djmaze** [comment]
what does your Settings -> Accounts (`/#/settings/accounts`) say?

**Comment by Disco1** [comment]
Same issue. Settings > Accounts shows both account, but the drop down won't show my second account. If I try to add my other account back, it says that it already exists.

**Comment by the-djmaze** [comment]
I've reverted change for #280 which causes it.

**Comment by Disco1** [comment]
How do I get the update? I dont' see it as an update in Nextcloud.
