### ISSUE TITLE
ExternalLogin not working

### ISSUE THREAD

**Issue by dfangys** [the-djmaze/snappymail#795]
Hello, 

I have an issue with ExternalLogin extensions, I have enabled the External login extension but the problem is when i send the postman request it is not showing anything 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/76405340/209438592-cd03010b-b65c-4771-bee1-087f564d49ac.png">

also, i tried this with rainloop it's works fine ! 

any idea ?

**Comment by the-djmaze** [comment]
It works, you probably have your CSP incorrect.
Check the browser console network requests and your SnappyMail log.

**Comment by the-djmaze** [comment]
Oh, i've just noticed you meant the JSON output
