### ISSUE TITLE
List messages per day feature is enabled by default and breaks sorting

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#796]
When "List messages per day" is enabled (which it is by default on upgrade to 2.24.1), the Sort button in the toolbar no longer functions. You can click it and select an option within, but the message view never re-arranges anything.

Expected behaviour: I can think of two ways the sorting might be expected to apply when List messages per day is enabled:

1. Perhaps the messages within each day grouping would be sorted as the user configures it (this at least works well for date/time sorting), or
2. When sorting by another other than time maybe the message list view should revert to standard display without the day-groupings. If this option is chosen, then I wonder if the checkbox to toggle between day-grouping mode  should exist within the sort drop down rather than in the general settings - it might make it more clear how everything works together.

At minimum perhaps until sorting can be fixed to work smoothly with this option, I wonder if "List messages per day" shouldn't be enabled by default.

I also suspect that the majority of users would be happy if just the date sorting option was obeyed. For example, messages are by default sorted by date descending, but when you enable day-grouping, the days are descending, but the messages within each day are ascending - if those were descending, that would likely solve most user's immediate issue with the functionality.

**Comment by the-djmaze** [comment]
Yes, while implementing i never thought about the sorting options (as i never use them).

Turning this option off would be best but also information regarding sort options would be nice.

As sorting by FROM (@) could also be added, but grouping by subject or size would be difficult.

**Comment by jas8522** [comment]
This is a great first step, in that it resolves most of the sorting menu issues, but we still have one remaining problem: 

Choosing between descending or ascending for either Date or From address doesn't change the order. 

The biggest problem our users had with the feature wasn't that they necessarily wanted to disable it (they liked the idea of it) but that they couldn't get the messages within each day grouping to sort in descending order, and that issue still remains present in 2.24.2 :(

**Comment by the-djmaze** [comment]
> that they couldn't get the messages within each day grouping to sort in descending order

True, the system still orders based on date+time and does not sort "DATE DESC + TIME ASC"

Do we need all these options?
* DATE DESC + TIME DESC
* DATE DESC + TIME ASC
* DATE ASC + TIME DESC
* DATE ASC + TIME ASC
* FROM ASC + DATETIME ASC
* FROM ASC + DATETIME DESC
* FROM DESC + DATETIME ASC
* FROM DESC + DATETIME DESC

**Comment by jas8522** [comment]
I think if someone has specified:
- Date Descending, they probably expect to see DATE DESC + TIME DESC (which might be better called "Newest First")
- Date Ascending, they probably expect to see DATE ASC + TIME ASC (which might be better called "Oldest First")
- FROM ASC, they probably expect to see FROM ASC + DATETIME DESC
- FROM DESC, they probably expect to see FROM DESC + DATETIME DESC

However the latter two I'm not as sure about as I am the first two. I'm fairly certain that a majority of people tend to use datetime DESC in general. Plus If someone really needs their DATETIME ASC, they can just switch to that view without the group by FROM part, I'd imagine.

> When you have pagination and there are 30 messages with DATE (or FROM) X and the list shows 20 messages.
Only the 20 are ordered, not the others.

Fair point. When ordered DATE DESC + TIME DESC and DATE ASC + TIME ASC that shouldn't be a problem though, I think? However it would be for FROM groupings - I have to wonder if that feature would be used enough to matter?

**Comment by the-djmaze** [comment]
The four you mention are the defaults now (i've changed FROM behavior)

> Plus If someone really needs their DATETIME ASC, they can just switch to that view without the group by FROM part, I'd imagine.

They could also:
1. DATETIME ASC
2. Search "from"

> Fair point. When ordered DATE DESC + TIME DESC and DATE ASC + TIME ASC that shouldn't be a problem though, I think?

Correct, then it is IMAP doing the sorting.

> However it would be for FROM groupings - I have to wonder if that feature would be used enough to matter?

No i mean like this:
1. IMAP SORT DATE descending
2. JavaScript reorders messages inside day from descending to ascending

But this makes it complex and indeed depends how often someone uses it.

**Comment by jas8522** [comment]
Updated to 2.24.3, made sure to manually clear the cache server side and used web inspector with disable cache checked in Firefox.

When I go to my archive mailbox (where there's lots of messages per day), it shows:

TODAY
- Message received at 3:32 AM
- Message received at 4:50 AM
- Message received at 7:00 AM
etc

When I want it to be like this:

TODAY
- Message received at 9:46 AM
- Message received at 7:05 AM
- Message received at 7:04 AM
- Message received at 7:00 AM
etc

(Where the time is currently 9:57am)

This was the only complaint from our webmail users with the new view: that the messages within each day grouping are grouped ascending when they want them descending.

Choosing the sorting options from the menu above for "Date descending" (or Date ascending) doesn't do anything with this release - doesn't change the order of days nor the order of messages within each day grouping.

Here's a screenshot to illustrate
<img width="314" alt="snappymail-day-groupings-have-messages-ascending-by-time" src="https://user-images.githubusercontent.com/326966/209839137-a50f4e43-9ca3-4213-8c49-f9c154a4aaea.png">

**Comment by the-djmaze** [comment]
That really sounds like an issue in your IMAP server.
My Dovecot is correctly showing both descending (also in demo).

Which IMAP software is in use?

**Comment by jas8522** [comment]
> Which IMAP software is in use?

Dovecot… Is there a config option that corresponds?

**Comment by the-djmaze** [comment]
No idea, i will have a look why this happens.

**Comment by the-djmaze** [comment]
I found one when using the messages limit in Admin -> Domains -> Domain.

When the limit is reached, it tries a faster fetch for messages and:
1. Uses ID's (not UID)
2. SORT disabled
3. THREAD disabled

Say there are 5000 messages and a limit of 20, then the ID's are fetched in order: 4981, 4982, 4983, …, 5000
This causes a strange behavior as the newest received messages are ordered ascending.
So for next release i've changed that to be: 5000, 4999,  …, 4981

This still isn't perfect as the behavior is like SORT REVERSE ARRIVAL where some messages are delivered later.
So improvements can still be made.

I've also made more changes to indicate the "fast fetch" is used, by hiding the sort options button when active.

This should give more indications why things are sometimes not possible/disabled.

**Comment by jas8522** [comment]
Built my fork of master with these fixes and tested it out - worked perfectly. Thanks!

**Comment by the-djmaze** [comment]
Improved the sorting when using message_list_limit
Especially when using a virtual \All mailbox (like with Dovecot virtual.All or Gmail)

Although a bit slower, it now does an additional SORT request on the server.
1. "Messages on page" limit is multiplied by 3 to get a bigger range
2. a SORT command with that range is now requested to IMAP
3. a slice of the result (limit, say 20 messages) is returned to fetch those for the list

It is still not the best solution but at least it stays fast when using message_list_limit and the date sorting has improved.

**Comment by the-djmaze** [comment]
I will close this for now as the workarounds and improvements should be sufficient enough.
Bugs in it can be reported as new issues.

**Comment by jas8522** [comment]
Thanks @the-djmaze!
