### ISSUE TITLE
Custom page login not working for first time 

### ISSUE THREAD

**Issue by dfangys** [the-djmaze/snappymail#798]
Hello, 

I'm using a custom page login, so I used a custom design for the login page, so when I use the login for the first time on a new pc or browser the snappy mail redirects me to the original login page but if I retry this step second time it login successfully without original page, any idea? 

using a custom page in the same index.php dir name of the custom login page is index.html

**Comment by the-djmaze** [comment]
This is probably caused by #713 
I will think about solutions to generate token in PHP when it is missing.

**Comment by dfangys** [comment]
> This is probably caused by #713 I will think about solutions to generate token in PHP when it is missing.

I'm using SSO auth behind the custom page, so it redirects to the sso#hash token, for the first time on the browser not working, but if I retried the steps again it will work, also if I removed the cache from the browser will do the same bug.

**Comment by the-djmaze** [comment]
Correct. The system now generates an smctoken in localstorage.
I have to figure out how to prevent that with SSO.

**Comment by dfangys** [comment]
I'm sure when i was using rainloop i don't faced this issue before. 

Looking forward for your great solution 👏
