### ISSUE TITLE
F5 and Ctrl-F5 reload logs out of Snappymail in Chrome.

### ISSUE THREAD

**Issue by whataboutpereira** [the-djmaze/snappymail#800]
**Describe the bug**
F5 and Ctrl-F5 reload logs out of Snappymail in Chrome.
Ctrl-R reload works.

**To Reproduce**
1. Log into Snappymail.
2. Press F5 or Ctrl-F5
3. Will be thrown to the login screen.

**Expected behavior**
Expect the logged in user to remain logged in.

**Please complete the following information:**
- Browser: Chrome 108.0.5359.125
- IMAP daemon: Dovecot v2.3.20
- PHP version: v8.1.13
- SnappyMail Version: v2.24.2

**Comment by the-djmaze** [comment]
Caused by fix for #798

**Comment by whataboutpereira** [comment]
Thanks!

**Comment by gramakri** [comment]
Can confirm issue is fixed in 2.24.3 (Cloudron package)
