### ISSUE TITLE
Saving attachment to Nextcloud folders with escaped character ins folder names generates folders with literal escape sequences

### ISSUE THREAD

**Issue by noseshimself** [the-djmaze/snappymail#801]
**Describe the bug**
Title says it all: If you try saving an attachment to Nextcloud and the destination folder name will contain escape sequences in its URL form the attachment will be saved to a new folder with the %-sequences in place of the original characters. The problem will be visible in the folder selection pop-uo.

**To Reproduce**
1. Receive a mail with an attachment
2. If you don't have any, create a folder with a space character (or a percent sign or anything else requiring escaping) 
3.  Select "Save in Nextcloud"
4. Get a pop-up like this (see the "%20")
![image](https://user-images.githubusercontent.com/6132793/209671341-514a1530-02b5-4e1a-b764-4d3f486d1d63.png)
5. After saving the attachment(s) there will be a new folder "DMS%20(BNC)"

**Expected behavior**
I expect the files to be saved to the folder "DMS (BNC)"

**Please complete the following information:**
- Browser: Chrome, Firefox, Safari
- IMAP daemon: CommuniGate Pro 6.3
- PHP version: 8.1
- SnappyMail Version: 2.24.2

**Comment by the-djmaze** [comment]
1. Go to Nextcloud -> Admin -> Additional Settings.
2. Open the SnappyMail admin -> Extensions

Do you have Nextcloud extension 2.13 there?

**Comment by noseshimself** [comment]
(yes)
