### ISSUE TITLE
Switching accounts does not work anymore with 2.24.2

### ISSUE THREAD

**Issue by ro56** [the-djmaze/snappymail#802]
I have 6 mail accounts registered with snappymail. With the newly installed 2.24.2 in a standalone (no nextcloud) setup it's not possible anymore to switch accounts via pulldown in the right top corner in a standalone (no nextcloud). 
In the logs I only find:
[2022-12-27 17:25:35.867][982adc09] Crypt[WARNING]: Decrypt() invalid $data or $key.
These messages show in 2.24.1 as well.
My setup is 
nginx 1.23.2
php 8.1.13
postgresql 15.1

Switching accounts within a nextcloud integrated snappymail application works fine.

**Comment by the-djmaze** [comment]
Was caused by fix for https://github.com/the-djmaze/snappymail/issues/798

**Comment by ro56** [comment]
thx for the quick response,
rainer

**Comment by ro56** [comment]
bugfix confirmed,

rainer

**Comment by HenkVirtual** [comment]
2.24.3 account switching is working.
