### ISSUE TITLE
Releases are packaged as tarbombs

### ISSUE THREAD

**Issue by windowsrefund** [the-djmaze/snappymail#804]
Please provide tallballs and zips that extract to a directory as mentioned in the documentation.

**Comment by m-i-k-e-y** [comment]
They are there, scroll down to assets. For example [release 2.24.2](https://github.com/the-djmaze/snappymail/releases/tag/v2.24.2)

**Comment by the-djmaze** [comment]
Changing the tarbomb to tarball has impact for automation systems like this script.
https://github.com/the-djmaze/snappymail/blob/master/cli/upgrade.sh

Also when you do something like:
1. `cd /home/webmail/public_html`
2. `wget https://snappymail.eu/repository/latest.tar.gz`
3. `tar -xzf latest.tar.gz`

It would be better to update [Installation instructions](https://github.com/the-djmaze/snappymail/wiki/Installation-instructions)
