### ISSUE TITLE
l10n: continuous localization workflow (main app)

### ISSUE THREAD

**Issue by p-bo** [the-djmaze/snappymail#806]
Hi, would it be possible to deploy something like this please?
https://docs.weblate.org/en/latest/admin/continuous.html#github-setup
(it is possible to get hosted variant for free - see https://hosted.weblate.org/hosting/ )

...as it will provide following benefits (for instance):

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by the-djmaze** [comment]
Here's an example https://snappymail.eu/translate.php
All entries which are the same as English are orange.

Currently on save it provides you a zip with the translation.

**Comment by Cwpute** [comment]
What should we do with that zip ? i've added a couple of translated words and corrected some of others in french.
[snappymail-fr-FR.zip](https://github.com/the-djmaze/snappymail/files/13604469/snappymail-fr-FR.zip)

**Comment by the-djmaze** [comment]
> What should we do with that zip ?

You can create a pull request.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
