### ISSUE TITLE
l10n: (Nextcloud integration only) use Transifex localization workflow

### ISSUE THREAD

**Issue by p-bo** [the-djmaze/snappymail#807]
Hello,
(only for lang files in https://github.com/the-djmaze/snappymail/tree/master/integrations/nextcloud/snappymail/l10n )
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please (as it was for Rainloop)?

Don't worry, it shouldn't take you much time - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and that repo admin(s) are keen to help with that process.

Thanks :-)

**Comment by the-djmaze** [comment]
I've tried transifex, but it failed.
Also RainLoop added incorrect localization strings which makes it complex.
Not to mention the JSON format it is now.

However, the search for easy translating is still on my mind.

**Comment by p-bo** [comment]
> Also RainLoop added incorrect localization strings which makes it complex.

This was in times, when Rainloop project was active and part of continuous translation workflow - removed then there https://github.com/nextcloud/docker-ci/commit/f9587866e8e885100fc58f7841072ab2219767c7 - right? (understood in sense that Rainloop Nextcloud integration was translated this way, but there were problems you mentioned?)

> However, the search for easy translating is still on my mind.

That's great - looking for it :-)

**Comment by the-djmaze** [comment]
Here's an example https://snappymail.eu/translate.php
All entries which are the same as English are orange.

Currently on save it provides you a zip with the translation.

**Comment by the-djmaze** [comment]
#1358
