### ISSUE TITLE
All added accounts are not loading but only the first added account

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#808]
**Describe the bug**
I don't know since the recent update (2.24.3), only one account is being served on snappymail, when I click on other accounts, it loads the same account with a different theme I set for each added accounts. In my case, an account that's loading is the one I saved the credentials in nextcloud setting.

**To Reproduce**
1. Go to snappymail app
2. Click on the list of accounts you have added 
3. Click one of them, and it will load an email list of the first account but it retains the themes set for the accounts

**Expected behavior**
All accounts should be distinct and loads correctly

**Screenshots**

**Please complete the following information:**
- Browser: Firefox 108.0.1
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.4
- SnappyMail Version: 2.24.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Why did you close it?

**Comment by elhananjair** [comment]
@the-djmaze you have fixed the issue [here](https://github.com/the-djmaze/snappymail/commit/faa17ca3de48280ff630d67290cb7bba6e0cf140) 😅 and actually it's a duplicate https://github.com/the-djmaze/snappymail/issues/802
