### ISSUE TITLE
Avatar not showing up 

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#809]
**Describe the bug**
After the new update I couldn't see avatar showing up on the list of mail

**To Reproduce**
1. check your email list

**Expected behavior**
The avatar must have been shown as before

**Screenshots**
![image](https://user-images.githubusercontent.com/69236638/209941755-e992b790-1d3b-47cd-9d1c-7a9c2ff352dd.png)

**Please complete the following information:**
- Browser: Firefox 108.0.1
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.4
- SnappyMail Version: 2.24.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Go to SnappyMail Admin -> Extensions and update the Avatars extension

**Comment by elhananjair** [comment]
oww my bad thank you it works now
