### ISSUE TITLE
Attachment icon not shown for mails with PDF attachments

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#81]
**Describe the bug**
Right besides the mail size, an icon is shown to notify you, that the mail contains an attachment. This works correctly for pictures and mixed attachments (e.g. a picture and a PDF). But it does not work for PDFs only. Then the icon is not shown.

**To Reproduce**
see description above

**Expected behavior**
The attachment icon should be shown for mails with PDFs only as well.

**Screenshots**
![attachments](https://user-images.githubusercontent.com/2138442/114258958-b8ee4a80-99ca-11eb-8435-64671095f247.jpg)

**Desktop (please complete the following information):**
 - Browser: Chrome 89
 - SnappyMail: 2.5.0-RC2

**Comment by ervee** [comment]
I can confirm this one running the latest v2.5.0-rc.2

![image](https://user-images.githubusercontent.com/4435930/114310634-ac154800-9aeb-11eb-9b20-7bef15e0b057.png)

**Comment by ervee** [comment]
Indeed seems fixed in latest RC.
