### ISSUE TITLE
Opening and closing an email leaves it as unread.

### ISSUE THREAD

**Issue by LeifAndersen** [the-djmaze/snappymail#810]
**Describe the bug**
Frequently I find that when I open an email and then close it going back to the list, the email I just had open is still unread. This is unlikely a problem with my mailserver as it didn't happen when I was using rainloop.

**To Reproduce**
1. Go to inbox.
2. Open an unread email
3. Quickly close the email (with the esc key)
4. Notice that the email remains unread.

**Expected behavior**
I expect the email to be marked as read, unless I click the keep unread button.

**Screenshots**
N/A (although if I need to upload a screen recording I can do that.)

**Please complete the following information:**
- Browser: Firefox (latest)
- IMAP daemon: dovecot
- PHP version: 8.1.12
- SnappyMail Version: 2.24.3 (From nextcloud repo)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Unfortunately even after turning on logs and restarting none appear to be written. Is it possible they're going to journalctl somehow?

**Additional context**
N/A

**Comment by the-djmaze** [comment]
Did you set the setting 'mark read after N seconds'  to 0?

**Comment by LeifAndersen** [comment]
Ah yes, that did it. I guess I just didn't see that option. Thanks.

**Comment by the-djmaze** [comment]
You're welcome
