### ISSUE TITLE
[FeatureRequest] Select all messages of a date when clicking on the date for date grouped messages.

### ISSUE THREAD

**Issue by yogi81** [the-djmaze/snappymail#815]
It would be nice to a have a convenience feature:

When displaying messages grouped by date select all visible messages of a particular date, when user clicks on the date of the group.

Use case: When receiving a lot of unneeded mails allows:
1.  quickly select all messages of a day by clicking on the date
2. deselect only messages user wants to keep
3. delete all still selected messages

**Comment by the-djmaze** [comment]
There is already an option:

1. Select first message
2. Hold keyboard shift button pressed
3. Use mouse or arrow keys to select multiple

I do see that search SENTON= and ON= are not implemented yet, so activating those makes it also an additional option.

Clicking on grouped date or from could then have 2 options:
1. Select all
2. Search specific date or from

**Comment by the-djmaze** [comment]
In the latest release you can click on the date.
Then it will search all messages received on that date (not the sent date).
