### ISSUE TITLE
plugin change password for postfixadmin

### ISSUE THREAD

**Issue by jeromeg81** [the-djmaze/snappymail#819]
Bonjour et bonne année !

Serait-il possible de créer un plugin pour changer le mot de passe postfixadmin ?
Ou d'adapter celui existant pour Rainloop (https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password)

Merci pour votre travail !
------
Good morning and Happy New Year!

Would it be possible to create a plugin to change the password postfixadmin ?
Or adapt the existing one for Rainloop (https://github. com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password)

Thank you for your work!

**Comment by the-djmaze** [comment]
Looking at that plugin, it only updates a database table through PDO.
You can do the same with the default change-password plugin.

**Comment by jeromeg81** [comment]
I have already tested with the plugin change-password, but it does not work.
The password has not been changed!
In the plugin settings, I have activated PDO and filled in the fields DSN (mysql:host=127.0.0.1;dbname=postfixadmin;charset=utf8), User Password and Statement (UPDATE mailbox SET password = :newpass WHERE username = :username AND password = :oldpass).
Did I forget something?

**Comment by the-djmaze** [comment]
:oldpass might fail, maybe don't check that.

**Comment by jeromeg81** [comment]
Same thing when you remove it.

**Comment by the-djmaze** [comment]
I use dovecot and 2 types of users:
* System (like 'john' from /home/john)
* virtual (like jane@john.com)

My postfix uses dovecot db and it worked.

Will test again with latest releases.

**Comment by jeromeg81** [comment]
The problem seems to come from username because if instead of WHERE username=:username, I put WHERE username='mymail@mydomain. com', it works!

I'll check to see if I have the latest versions.
Thanks

**Comment by the-djmaze** [comment]
Instead of :username you can try :login_name or :email

**Comment by jeromeg81** [comment]
Great, it's working!
Thank you very much.
