### ISSUE TITLE
Support for ownCloud Infinite Scale Stack

### ISSUE THREAD

**Issue by jonmoesli** [the-djmaze/snappymail#821]
ownCloud released in late 2022 the stable version of their new platform (ocis), very promising solution for big installations.
Is there a plan to support standard webdav, and eventually direct support? It seems webdav is enabled just for nextcloud plugin.

**Comment by the-djmaze** [comment]
I've made an attempt by copying Nextcloud code to an ownCloud.
https://github.com/the-djmaze/snappymail/tree/master/integrations/owncloud/snappymail

But it seems that ownCloud still lacks some features and it partially works.

**Comment by the-djmaze** [comment]
I don't see much improvements in ownCloud compared to Nextcloud.
Therefore i will keep the example integration code where it is and others need to play with it.
I currently can't support it.
