### ISSUE TITLE
[Nextcloud] Improve file picker layout

### ISSUE THREAD

**Issue by hampoelz** [the-djmaze/snappymail#825]
Currently, the file selector for attaching/sharing files from the Nextcloud instance includes 3 buttons for each file in the list, which makes the view cluttered and sometimes confusing when there's for example an automatic line break (too long filename, etc.).

Before I start integrating the file picker into the new Nextcloud theme _(#629)_, I suggest the following changes:

The action buttons should appear at the bottom of the popup, and each file in the list should have a checkbox instead. This way, one (or more) files can be selected without overloading the list. And full functionality is retained. Another advantage of this would be that the file picker can be easily expanded to include additional actions without becoming even more confusing.

**Comment by the-djmaze** [comment]
It was on my todo, but faded away (although partially the code is there).

Good you point it out
