### ISSUE TITLE
Unable to change font/text colour when composing message using Safari

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#826]
**To Reproduce**
1. Open Safari, login to webmail, choose New Message button
2. Place cursor in the message text area
3. Click the A icon in the toolbar to change text colour
4. Notice that no color picker appears

When I use Firefox, the native macOS color picker appears and I can select a color. It works normally.

When I use Chrome, some other color picker appears in the upper left corner and I can select a color. It works normally.

**Expected behavior**
When choosing a color option in the squire toolbar, a color picker will appear.

SnappyMail Version: 2.24.4

**Comment by jas8522** [comment]
Works great, thank you! The safari color picker has a better UI than the other browsers too :)

**Comment by the-djmaze** [comment]
Your welcome!

I just received an old mac mini 2014 with macOS 12 for developing an app in Swift.
So you are lucky i could find and solve the issue!
