### ISSUE TITLE
Moving unread mail to Mailbox triggers notification

### ISSUE THREAD

**Issue by Cwpute** [the-djmaze/snappymail#827]
**Describe the bug**
Moving an unread message to the main Mailbox triggers a "new mail" notification

**To Reproduce**
1. Choose an email (from trash folder for example)
2. Set it to Unread
3. Move it to the main mailbox

**Expected behavior**
SnappyMail should probably not warn me about this, since i'm the one who moved this mail, and it's also not a new mail so this can be confusing for some users.

**Please complete the following information:**
- Browser: einkbro (android)
- IMAP daemon: unknown
- PHP version: unknown
- SnappyMail Version: latest

**Comment by Cwpute** [comment]
Probably keeping the behavior as is… I dwn't know the in and outs of how SnappyMail works, i can't tgink of any good and simple solution that wouldn't some unnecessary hacking bringing a lot other potential bugs.

**Comment by the-djmaze** [comment]
> i can't think of any good and simple solution that wouldn't require some unnecessary hacking

There is a solution but most IMAP servers don't support it.
There is a "hacking" solution but that is also not perfect.

So for now i will close this issue and we keep current behavior :wink:
