### ISSUE TITLE
In Snappy-Mail template get broken

### ISSUE THREAD

**Issue by avinash-0007** [the-djmaze/snappymail#831]
**Describe the bug**
I tried to invite using calendar app in nextcloud . The email layout is looking alright in different email client but when it comes to snappy its broken,

**To Reproduce**
1. Go to 'Calendar and create an invite
2. Now logged in from invited email id and go to snappy mail app .
3. Open the email
4. See error- As email is not showing alright- Showing Borders, Height of rows is not proper and also buttons.

**Expected behavior**
Email should show correctly

**Screenshots**
snappymail"
![mailtemplate](https://user-images.githubusercontent.com/21700809/210761047-e349bb2e-e37c-4966-9fbf-9afeb2c23f7e.png)
on other email client
![screencapture-mail-google-mail-u-0-2023-01-05-16_11_32](https://user-images.githubusercontent.com/21700809/210761861-e10dc4f2-48e2-41f3-975d-e9fc8e9ddad3.png)

**Comment by the-djmaze** [comment]
Looks fine here in Nextcloud 25 with Calendar 4.2.0

![afbeelding](https://user-images.githubusercontent.com/3752035/210782999-9d487d83-e00d-43c4-917c-adf880f0487e.png)

**Comment by the-djmaze** [comment]
Which Nextcloud Calendar version are you using?
