### ISSUE TITLE
Snappy mail doesn't remember "reply all"

### ISSUE THREAD

**Issue by Disco1** [the-djmaze/snappymail#834]
**Describe the bug**
In Rainloop, if I choose reply all, it becomes the default for the reply button. In SnappyMail it does not. I want to reply all much more often than I want to just reply. Is there a way to get that default back?

**To Reproduce**
1. Click reply all
2. Reply to another e-mail

**Expected behavior**
Snappymail remembers my reply all vs. reply choice

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
It does, as added in #496
Settings -> General -> Message view -> Default action

![afbeelding](https://user-images.githubusercontent.com/3752035/211302597-87d4eee9-9bda-47e7-b96f-f67939aefc9c.png)

**Comment by prilly-dev** [comment]
you can also set global parameter in admin panel, default is 1=reply, set it to 2=replay all
