### ISSUE TITLE
Pressing enter on suggested contacts doesn't load them into the To field

### ISSUE THREAD

**Issue by Disco1** [the-djmaze/snappymail#835]
**Describe the bug**
In Rainloop, if I start typing an email address, it suggests emails from my contacts, just as Snappymail does. But if I click Enter, it chooses the approprirate one. Snappy mail requires mouse for that, and it's a pain.

**To Reproduce**
1. Start typing an email address
2. Press enter
3. Nothing happens.

**Expected behavior**
Pressing enter chooses the contact

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Correct. SnappyMail uses the default HTML5 behavior of `<datalist>`.
Therefore you must use the arrow keys before using the enter key.
