### ISSUE TITLE
Can't open multiple mailboxes at the same time

### ISSUE THREAD

**Issue by CrazyOrient** [the-djmaze/snappymail#837]
**Describe the bug**
Can't open multiple mailboxes at the same time

**To Reproduce**
1. Add second email account (email2)
2. Open new tab with snappymail
3. In second tab change email to email2
4. In first tab click "Reload message list"
5. You will see messages from email2 account

**Expected behavior**
email account 1 and email account 2 should open in parallel (like in rainloop)

**Screenshots**
![2023-01-09_13-56](https://user-images.githubusercontent.com/122268237/211293306-1316cdd7-5151-4cc7-a996-b14031b94ff3.png)
![2023-01-09_14-00](https://user-images.githubusercontent.com/122268237/211293324-90bd30cc-b5d8-493e-94cd-ab46566eb42d.png)
![2023-01-09_13-58](https://user-images.githubusercontent.com/122268237/211293344-765562f6-81f0-4c9d-b877-247609f37f9f.png)

**Please complete the following information:**
- Browser: google chrome 108.0.5359.71
- IMAP daemon: dovecot
- PHP version: 7.4.3, 8.1.2
- SnappyMail Version: 2.24.4

**Comment by the-djmaze** [comment]
Read https://github.com/the-djmaze/snappymail/issues/650#issuecomment-1309856493

**Comment by CrazyOrient** [comment]
Ok. Thank you. Didn't find that post.
