### ISSUE TITLE
Hook "login.success" not called anymore?

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#838]
Hi,
at the moment I have problems to understand why my plugin ldap-mail-account isn't working anymore in newer versions of SnappyMail.
I had a look and I'm unsure if this problem raises because

https://github.com/the-djmaze/snappymail/blob/1311fd343b01ca24ce3aee5dc8fabd8d8c1a91d8/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/User.php#L35

isn't called anymore at all?
If true, multiple plugins would be affected of this: the nextcloud integration, proxyauth-login-example, two-factor-auth and ldap-mail-account have references in their source to this hook.

**Comment by the-djmaze** [comment]
Strange as it should still work at:
https://github.com/the-djmaze/snappymail/blob/1311fd343b01ca24ce3aee5dc8fabd8d8c1a91d8/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/User.php#L47

**Comment by cm-schl** [comment]
Man, your right 🤦‍♂️. My fault, I'm sorry!

**Comment by botsarenthuman** [comment]
What was the problem?
