### ISSUE TITLE
Temporarily save password for private key during session

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#840]
**Is your feature request related to a problem? Please describe.**
I really want to sign the emails I send out using my OpenPGP key. Unfortunately I have to enter my password for the OpenPGP key **every** time I send an email. This slows down the process of writing an email and helps people to choose a weak (or maybe no) password for their key.

**Describe the solution you'd like**
I would favor a solution like in Roundcube which offers to save my key temporarily in my browser for as long as the session stays valid (you could alternatively choose a custom time span).

**Describe alternatives you've considered**
Another alternative would be to mark the field as "password" field so that I can save the password in my browser. But I don't consider this solution as very secure so I would favor the first approach.

**Additional context**
This is the feature in Roundcube:

![image](https://user-images.githubusercontent.com/43847817/211320402-6a0261a0-4c41-47f2-a386-e7495e566d72.png)

**Comment by the-djmaze** [comment]
> Unfortunately I have to enter my password for the OpenPGP key **every** time I send an email

Correct.
SnappyMail can't see if your computer is locked when you are away from your keyboard.
So maybe someone else is sending emails in your behalf?

But indeed an option to "remember password" could be added.

**Comment by codiflow** [comment]
Hey @the-djmaze THANKS a lot for this feature. Works like a charm.

Just two things where I don't know if they are on purpose:

1. I have to enter the password again after switching accounts or reloading the window. So it seems to be login-session-based and not browser-session-based is that on purpose? Just good to know when I have to enter the password again.
2. If I enter a wrong password I have to reload the browser window / logout and relogin to be able to enter the correct password again because it won't display me the password prompt again:

![2023-02-02_13-49](https://user-images.githubusercontent.com/43847817/216330271-f59055ef-8056-4b74-9059-7ed7f85f5265.png)

Again THANKS for this feature making the usage of secure technologies like signing mails easier for me :-)

**Comment by the-djmaze** [comment]
> 1. I have to enter the password again after switching accounts or reloading the window. So it seems to be login-session-based and not browser-session-based is that on purpose? Just good to know when I have to enter the password again.

They are stored in a JavaScript Map() (not sessionStorage) so any time the page reloads/refreshes they are gone.
Could be changed to use sessionStorage though.

> 2. If I enter a wrong password I have to reload the browser window / logout and relogin to be able to enter the correct password again because it won't display me the password prompt again.

Ok that is a bug then :)
