### ISSUE TITLE
I can't use nextcloud contacts with snappymail

### ISSUE THREAD

**Issue by camala19** [the-djmaze/snappymail#845]
**Describe the bug**
I want to configure access to nextcloud contacts from snappymail.
I don't remember dsn localhost to "contacts".
Which admin account do i have to use in snappymail admin config ?
![image](https://user-images.githubusercontent.com/15215593/211753554-a2f6a79c-f746-41a7-8a7e-7409f9855a86.png)**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by Silberlog** [comment]
I think that Contacts configuration section in Admin Panel is here to configure contacts in a dedicated MySQL database (not related to specific Nextcloud database).
If you want Nextcloud contacts integration, you have to activate the Nextcloud extension in SnappyMail like this : 

![image](https://user-images.githubusercontent.com/121984435/211816489-07b57e34-8161-445f-bd89-e88a77f0bcb9.png)

**Comment by camala19** [comment]
> @Silberlog is correct

i continue to deal with the same issue.
Here is my configuration :
![image](https://user-images.githubusercontent.com/15215593/211830309-19b4f666-9a73-4c9e-910c-646b8ef7ddad.png)

**Comment by the-djmaze** [comment]
> I want to configure access to nextcloud contacts from snappymail.

1. Create new message to send
2. Type in the "to" field some text
3. See contact suggestions from Nextcloud

If you mean "I want to manage nextcloud contacts in snappymail." then the answer is: NO
This is because Nextcloud has bugs and we don't want to kill it.

**Comment by camala19** [comment]
> > I want to configure access to nextcloud contacts from snappymail.
> 
> 1. Create new message to send
> 2. Type in the "to" field some text
> 3. See contact suggestions from Nextcloud
> 
> If you mean "I want to manage nextcloud contacts in snappymail." then the answer is: NO This is because Nextcloud has bugs and we don't want to kill it.

I just want to use nextcloud contacts and contact groups.

**Comment by camala19** [comment]
Thanks,

> You can already use them with that configuration.
> 
> 1. Click on `Envoyer` (green button) to write a new mail
> 2. On the `À` field (`To`, in English) start typing something like `fred` if you have any contact like `Frederic` in your contacts.
> 3. All contacts containing `fred` in their name will appear. Click on it to send their an email.
> 
> This is what you can do with Nextcloud Contacts in Snappymail; to manage them, go to the Nextcloud Contacts app. Simple as that. I think that Groups can NOT be used tough; only single contacts.

Thanks a lot to all of you.
I can use contacts and even group contacts.
The way to use groups is to go to contacts app, then in group options, select send a mail
