### ISSUE TITLE
Extension "ldap-contacts-suggestions" suggestions bypassed

### ISSUE THREAD

**Issue by Silberlog** [the-djmaze/snappymail#849]
**Describe the bug**

Results returned by the LDAP search does not appear in the field "to:" when composing a new mail

**To Reproduce**
1. Go to 'New Mail'
2. Click on 'Field "To:'
3. Start typing contact name : e.g. ch.....

**Expected behavior**
LDAP contacts suggestions appears with contact auto-completion 

**Screenshots**
1- Add a debug output in file LdapContactsSuggestions.php
![image](https://user-images.githubusercontent.com/121984435/212196941-8569077b-45e9-4b43-bc62-7804717cc8c2.png)

2- Start to type the first letters in field "To:" of a new mail : eg : ch

3- Watch debug output

![image](https://user-images.githubusercontent.com/121984435/212197562-ad163ba5-69c3-44a2-bddd-5d1c2adbca35.png)

LdapSearch returns 1 entry (chloe@something.net) but this result is missing in the drop down list "To:" field.
Only the Nextcloud contacts are returned in JSON response.

**Please complete the following information:**
- Browser: chromium 108.0.5359.124, firefox 102.6.0esr
- IMAP daemon: dovecot
- PHP version: 8.0.27
- SnappyMail Version: 2.24.5
- Nextcloud 25.0.2

**Comment by the-djmaze** [comment]
Contact suggestions has a limit that is set in application.ini
Admin -> Config -> suggestions_limit

All suggestions handlers are merged on unique email address and then the limit amount (or less) are returned.

Did you scroll through the result list?
Did you count the entries in the result list?

**Comment by the-djmaze** [comment]
I've changed the code for handling suggestions in next release.
Maybe it will solve the problem.

**Comment by Silberlog** [comment]
Ok thanks, will check if next version resolve it ...

**Comment by Silberlog** [comment]
Problem still remains even after upgrading to 2.25.0 ...

**Comment by the-djmaze** [comment]
Enable debug mode, it should give more info now

**Comment by Silberlog** [comment]
Debug mode enabled like this : 

![image](https://user-images.githubusercontent.com/121984435/215172751-1c5aac86-659a-4e04-9ddb-5fe23ead3083.png)

But it's not much more verbose as before, and returned suggestions only comes from Nextcloud contacts.
Here is output when starting to type "chl" in field "To:" : 

![image](https://user-images.githubusercontent.com/121984435/215172542-936af76f-4309-410d-9583-20b34cb1eacc.png)

LDAP contacts are still missing.

**Comment by Silberlog** [comment]
After upgrading to SnappyMail v 2.25.1 / Ldap Contacts Suggestions v2.11, there's still problems.

If LDAP Contacts Suggestions and Nextcloud integration are enabled together, there's no suggestions at all in field "To:"
There's no more LDAP [INFO] lines in log file with debug level 7 enabled as before, it looks like LDAP step is bypassed.
If i enable only Nextcloud integration, contacts from Nextcloud are back.

**Comment by the-djmaze** [comment]
Did you update the plugin?

**Comment by the-djmaze** [comment]
Update to 2.12 of the plugin

**Comment by Silberlog** [comment]
Fantastic, works great for both now, Nextcloud contacts & LDAP Contacts uggestions, thanks a lot !

**Comment by the-djmaze** [comment]
you're welcome
