### ISSUE TITLE
Cannot access the repository at the moment.

### ISSUE THREAD

**Issue by Mululu** [the-djmaze/snappymail#85]
**SnappyMail version, browser, browser version:**
2.5.0-rc.4, Google Chrome, Version 89.0.4389.128

**Expected behavior and actual behavior:**
I have updated my Snappy Mail to the latest version now my plugins are deactivated and no longer visible. Login is no longer possible because I do not have the Custom Login Mapping plugin

I'm back to the old version for now.

One more question, you can't update directly via the admin panel?

**Steps to reproduce the problem:**
...
**Logs or screenshots:**
...

**Comment by the-djmaze** [comment]
Try 2.5.0

**Comment by ervee** [comment]
#87 related? I still have the mapping plugin in the admin panel though.

**Comment by the-djmaze** [comment]
Yes, i forgot to update the plugins repo

**Comment by Mululu** [comment]
For me the problem is not resolved.

What do I have to do to make it work again?

**Comment by kouinkouin** [comment]
> For me the problem is not resolved.
> 
> What do I have to do to make it work again?

For me, I cleaned all the folders in `_data_/_default_/plugins/` (`rm -rf _data_/_default_/plugins/*`). After that, I refreshed the /?admin#/packages page and the extensions are available.
I precise my data were from rainloop, so I guess the rainloop extensions are not fully compatible with snappymail.
