### ISSUE TITLE
Version 2.24.5 don't working on NC v24 & v25 [Update]

### ISSUE THREAD

**Issue by Akrobs** [the-djmaze/snappymail#855]
**Describe the bug**
Nextcloud 24 & 25, after updateSnappymail to latest version not working

**To Reproduce**
<img width="1395" alt="Snappy_nextcloud" src="https://user-images.githubusercontent.com/57731196/212491512-5110515c-51b3-402a-98d0-e70eeaa1cf0b.png">

Old version of snappymail works fine

**Comment by Akrobs** [comment]
Today i'm checked old versions and it's not loading((((

My setup:

Openlitespeed 1.7.16
LSHPH 8.1 (Try 8.0)
MariaDB 10.5.16

On dev console i have some errors
<img width="825" alt="Snappy_errors" src="https://user-images.githubusercontent.com/57731196/212736562-cfdf19b7-a6f1-4bf2-8577-df817bf0543b.png">

**Comment by the-djmaze** [comment]
https://forum.openlitespeed.org/threads/snappymail-with-openlitespeed-how-to-adapt-this-htaccess-file.5460/
