### ISSUE TITLE
535 5.7.8 Error: authentication failed: Server failed

### ISSUE THREAD

**Issue by jiriks74** [the-djmaze/snappymail#857]
**Describe the bug**
When I try to test the domain `atlas.cz`

**To Reproduce**
1. Go to `Admin panel`
2. Go to domains
3. Add domain atlas.cz
  i. `imap.atlas.cz`
  ii. SSL/TLS
  iii. Default port
  iv. `smtp.centrum.cz`
  v. SSL/TLS
  vi. Default port
4. Test the domain

**Expected behavior**
Successful test
Sending emails works

**Screenshots**
![image](https://user-images.githubusercontent.com/54378412/212525876-1d015f8f-7d67-483f-ae98-e75363a6ba12.png)

**Please complete the following information:**
- Browser: Firefox 109.0
- PHP version: 8.1.13
- SnappyMail Version: 2.24.5

**Additional context**
Installed as a Nextcloud app

**Comment by the-djmaze** [comment]
Try SMTP port 587 instead

**Comment by jiriks74** [comment]
I tried that but sadly it results in the exact same error

**Comment by the-djmaze** [comment]
1. Go to Admin -> Config
2. Enable `debug` and save
3. Test domain again
4. Open log in `/_data_/_default_/logs/`
5. Go to Admin -> Config
6. Disable `debug` and save

It should give you more insight information why it fails

**Comment by jiriks74** [comment]
I'm sorry that I didn't answer you. It got buried in my inbox and I didn't have the time go go through it all.

I'd just like to tell you that it works now with the `Force single command AUTH PLAIN login` option enabled.

**Comment by myuseraccount** [comment]
Strangely, for me the opposite is true:

- Test for the domain in Config always succeeds now (green test button, no error), whether Force single command AUTH PLAIN login is enabled or not
- With it on, sending a message in the client as a user gives a authentication failed error
- When I changed the setting for the domain to turn off force AUTH PLAIN and turned on use php_mail(), sending mail as a user succeeds
