### ISSUE TITLE
After page refreshes in background whilst editing a draft, the space bar stops working

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#860]
**Describe the bug**
This is an odd one.

Very often, whilst editing a draft, the space bar just randomly stops working. 

But it happen twice just now and I noticed it is happening after SnappyMail refreshes in the background (I guess checking for new mail or something).  I think perhaps something to do with losing focus or something?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to edit a draft
2. Notice the page refresh behind (I guess it's checking for new mail or something)
3. Realise the space bar doesn't work anymore
4. Save the draft, close the window, start editing again, wait for this to happen again, repeat this over and over until I've finished editing my draft
5. Get rather frustrated

**Expected behavior**
I expect the space bar to continue working.

**Please complete the following information:**
- Browser: Latest Firefox on latest Ubuntu
- IMAP daemon: dovecot
- PHP version: not sure, likely 8.1 (that is what the underlying Nextcloud is on)
- SnappyMail Version: Latest Nextcloud app

**Comment by jdaviescoates** [comment]
I just noticed it is also the letter U that stops working when this happens. And perhaps it is when the message is auto-saving as opposed to SnapyyMail checking for new message in the background.

**Comment by jdaviescoates** [comment]
This was getting so annoying that I stopped editing my long email using the Nextcloud app and went to compose it in the standalone app and I can confirm this doesn't happen there (despite the same refreshing/ saving or whatever is happening evidently happening there too - it doesn't break things when it happens like it does on the Nextcloud app)

But when using the Nextcloud app this basically happens every minute or so.

Here's a video of it happening. You can (hopefully) see the screen refresh in the background. After that the space bar (and some others keys) no longer work

https://youtu.be/fnA4ZTx30vE

**Comment by the-djmaze** [comment]
I see your movie and i'm really baffled.

Somehow i can't reproduce this issue in standalone nor nextcloud using Firefox.

**Comment by jdaviescoates** [comment]
Yeah, it's baffling. I'll see if I can reproduce it in other Nextclouds I'm running...

**Comment by the-djmaze** [comment]
This issue is similar to #690 and also weird.

1. Go to: Admin -> Config
2. Debug section enable `javascript`

Now in the browser developer console certain messages are logged:
```
Shortcuts scope set to: Compose
Shortcuts scope set to: Ask
Shortcuts scope set to: MessageList
```

The last `Shortcuts scope` is important when typing fails.

**Comment by jdaviescoates** [comment]
Yep, that sounds very similar. 

I'll give the above a try when I have a moment...

Thanks

**Comment by jdaviescoates** [comment]
I haven't noticed this happening recently whilst I'm originally drafting a message, but it does still seem to routinely happen when editing saved drafts...

I've gone into Admin -> Config and enabled javascript but I'm not sure what to do after that. I can't find anything about Shortcuts scope when looking in the browser web developer tools console thing, but here are some warnings etc:

![Screenshot from 2023-02-21 09-42-00](https://user-images.githubusercontent.com/2113743/220311983-de6aff8f-e90e-4fcb-a584-a6b893f72f65.png)

**Comment by jdaviescoates** [comment]
> I've gone into Admin -> Config and enabled javascript

Ah, but I hadn't clicked Save at the bottom and now going into a meeting... more later.

**Comment by jdaviescoates** [comment]
Here a new error after enabling javascript debugging:

![image](https://user-images.githubusercontent.com/2113743/220481975-93ebf11b-143b-4519-9016-7e8e558b6514.png)

and here's a load of logs mentioning the `Shortcuts scope` stuff

![Screenshot from 2023-02-21 23-29-33](https://user-images.githubusercontent.com/2113743/220482286-b02c6b70-0c8a-48bb-b709-bef289a3b522.png)

Does that shed any light on this issue?

**Comment by the-djmaze** [comment]
Great!

The scope goes from Compose to MessageList 1 minute later.

When you see the error it:
1. save draft
2. reload draft folder
3. reload message list
4. CRASH

Can you see why it crashes?
Take a look at the developer network tab, it should give response info about the issue.

**Comment by jdaviescoates** [comment]
Looks like the only things failing are to do with notifications?

![image](https://user-images.githubusercontent.com/2113743/220604067-023b2979-b85e-460b-a184-17ddcfc6a4c9.png)

But also says "cached" for those :thinking:

**Comment by jdaviescoates** [comment]
Or maybe it's something to do with these one that seemingly have no status code?

![image](https://user-images.githubusercontent.com/2113743/220604829-0cd43d92-96f9-4caf-ab43-6191c5a0d2fb.png)

**Comment by jdaviescoates** [comment]
This seems to be the moment it happens:

![image](https://user-images.githubusercontent.com/2113743/220606466-5e1a3341-3e30-4555-910b-c91e723f7ec6.png)

https://youtu.be/YuFnfNf3M-Y

**Comment by jdaviescoates** [comment]
But just updated to latest Snappymail Nextcloud app and now it seems it happens here:

![image](https://user-images.githubusercontent.com/2113743/220608029-470d8914-855c-4995-8583-ad2e25dbfd95.png)

https://www.youtube.com/watch?v=75TMAUsZQz0

**Comment by jdaviescoates** [comment]
Same thing still happens in standalone Snappymail too

![image](https://user-images.githubusercontent.com/2113743/220613244-ecbb0411-b5e0-414e-864e-9b0841cb6247.png)

https://youtu.be/1LYeBn8v3T8

**Comment by jdaviescoates** [comment]
I'm really hoping all this will help you to resolve this issue as when I'm crafting a long email it really bugs me :pray:

**Comment by the-djmaze** [comment]
I've found something. Maybe it helps in next release.

**Comment by jdaviescoates** [comment]
> I've found something. Maybe it helps in next release.

Yep, just updated to 2.26.4 version of the Nextcloud app and it seems to have helped! Thanks! :pray: 

I'll now close this (and hopefully won't need to reopen it in the future).
