### ISSUE TITLE
Snappymail error after upgrade to 2.24.5

### ISSUE THREAD

**Issue by jelle-e** [the-djmaze/snappymail#862]
SnappyMail doesnt load anymore after update to 2.24.5.

Message on page is:

Please refresh the page and try again. Failed loading /nextcloud/apps/snappymail/app/snappymail/v/2.24.5/static/js/min/libs.min.js

No idea where to look for a fix. Thanks for the help.

**Comment by jeroenim0** [comment]
The file does exist on the server.. could this be the same issue as this?

https://github.com/the-djmaze/snappymail/issues/358

**Comment by the-djmaze** [comment]
404 does indicate something is wrong.
In certain OpenLiteSpeed setups the .htaccess is parsed incorrectly.

Are you sure Apache is used and not OpenLiteSpeed?

**Comment by jelle-e** [comment]
Yes, it's Apache bundled with a Nethserver installation. It uses php8.

**Comment by mateors** [comment]
@the-djmaze I think version 2.24.5 is full of bugs, please solve this asap. My server still not working. I regret installing snappymail

**Comment by jelle-e** [comment]
Okay, it's fixed!

We replaced the .htaccess with the original one from github.
Also replaced the problematic .js files with the ones from the gzip in the (nextcloud-)snappymail folder.

Thanks again for the help.

**Comment by the-djmaze** [comment]
Good that it is solved. Let's hope next update will work as expected.
