### ISSUE TITLE
Failed load app data

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#864]
**Describe the bug**

Lot of users on our nextcloud instance complain about getting the following error.

```
An error occurred.
Please refresh the page and try again. Failed loading ./?/AppData/0/02556952101711385/
```

**To Reproduce**
1. Login to your nextcloud account
2. Close the tab and browser
3. Open browser and directly access the app with the link : https://nextcloud.org/apps/snappymail 

When you go to other app (files, dashboard) and then navigate to snappymail it loads fine. The issue happens only when accessing the link directly

**Expected behavior**

Load without error

**Screenshots**

![image](https://user-images.githubusercontent.com/16881005/213431551-1936e807-c5b4-4d04-859d-9564cc9196d8.png)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile] Firefox 108
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version: 2.23.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by akhil1508** [comment]
@Niveshkrishna I see this too, and the request goes to `./?/Appdata/...` and there is a 302 found at times.

At other times, it loads normally and I see it go to `/apps/snappymail/?/Appdata/...`

I see this script is added into the header by boot.js, so any idea on what is happening here? Why is it not going to the right url always?
@the-djmaze

**Comment by Niveshkrishna** [comment]
@the-djmaze thank you for fixing the issue so quickly. Will test out the latest release and share feedback

**Comment by Niveshkrishna** [comment]
@the-djmaze The original issue seems to be solved, app loads fine without the trailing slash. But after updating app to latest release, Admin section is broken

![image](https://user-images.githubusercontent.com/16881005/213642371-4cf9a841-ed5b-4156-bd17-db6251943360.png)

**Comment by the-djmaze** [comment]
> Admin section is broken

Yes, i know and already fixed for next release.
https://github.com/the-djmaze/snappymail/commit/95024aca10800ba32006ac5c8f33b79fa389a132

It is due to a change in layout as there were issues on mobile view mode.
And now that broke the Nextcloud integration layout.
