### ISSUE TITLE
CardDAV sync error - Request aborted

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#866]
**Describe the bug**
The CardDAV sync syncs the addressbook, but throws an error at the end.

**To Reproduce**
1. Go to Contacts
2. Click on hamburger icon
3. Click "Synchronization (CardDAV)"
4. Wait (depends on the size of your addressbook)
5. Error pops up

**Please complete the following information:**
- Browser: Chrome 109
- PHP version: 8.1
- SnappyMail Version: 2.24.5

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
[log.txt](https://github.com/the-djmaze/snappymail/files/10464268/log.txt)

**Comment by the-djmaze** [comment]
Mostly i see in your log `Decrypt() invalid $data or $key`
This means the decryption of the Account or CardDAV password fails (reason not logged, i could improve that).

Most Decrypt failures are caused by OpenSSL.
If you have Sodium active in PHP then save your CardDAV password again and then we can rule out that issue.

`PDOException: SQLSTATE[HY000]: General error: 1 no such table: rainloop_system`
Is your database corrupt or not initialized?

**Comment by phsc84** [comment]
It was a fresh install and I use SQLite, so I guess the database should neither be corrupt nor wrongly initialized.

Yes, Sodium is active (version 1.0.18). Again entering the password indeed helped to get rid of the decrypt errors. So I deleted the SQLite database and started the synchronization again. The system behaves the same, but I now get the following warning (actually it is not an error):
[2023-01-20 12:15:12.384][d2be2e60] PHP[WARNING]: Object of class Sabre\VObject\Parameter could not be converted to int /home/httpd/vhosts/url.com/httpdocs/apps/mail_new/snappymail/v/2.24.5/app/libraries/RainLoop/Providers/AddressBook/Legacy.php [line:25, code:2]

**Comment by phsc84** [comment]
I now activated the debug mode to get more information about the SQL ERROR. This time the system started the synchronization on its own after entering the addressbook. It seems, that the table rainloop_system is accessed before it is created.
[log_866-1.txt](https://github.com/the-djmaze/snappymail/files/10473891/log_866-1.txt)

**Comment by phsc84** [comment]
The "Request aborted" error in the browser seems to be caused by a Javascript issue. I now found the following in the browser console. Hope this helps.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/2138442/213904969-62fd74b1-a198-4765-ac8d-1a53d2af8a82.png">

**Comment by phsc84** [comment]
After activating the JS debug mode, I get the following in the browser console. The strange thing is, that it seems to make a difference if the synchronization is automatically or manually triggered. When automatically triggered, I do not get this "Request aborted" error at the end of the synchronization, but when manually triggered it pops up.
[log_866-2.txt](https://github.com/the-djmaze/snappymail/files/10473911/log_866-2.txt)
