### ISSUE TITLE
Adminpanel broken after upgrade to 2.24.6

### ISSUE THREAD

**Issue by scubamuc** [the-djmaze/snappymail#868]
**Describe the bug**
Adminpanel broken after upgrade to 2.24.6

**To Reproduce**
1. Upgrade app in Nextcloud
2. Go to Adminpanel
3. See error: Adminpanel view broken

**Expected behavior**
Adminpanel usable

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54933878/213699051-ec4aa46c-3123-4b78-8873-2637bd3d0c82.png)

**Please complete the following information:**
- Nextcloud-snap 25.02
- Browser: Chromium, FF, Edge
- PHP version: 8.1
- SnappyMail Version: 2.24.6

**Comment by ALEXSANPEDRO** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/63007698/213715196-4578d875-3924-447c-bee8-45bc6b856387.png)
same problem. 

NC: 25.0.3 - apache in docker
snappymail app:2.24.6

**Comment by the-djmaze** [comment]
Yes, i noticed after updating my Nextcloud instance and already fixed for next release.

https://github.com/the-djmaze/snappymail/commit/95024aca10800ba32006ac5c8f33b79fa389a132

**Comment by ALEXSANPEDRO** [comment]
> Yes, i noticed after updating my Nextcloud instance and already fixed for next release.
> 
> [95024ac](https://github.com/the-djmaze/snappymail/commit/95024aca10800ba32006ac5c8f33b79fa389a132)

When is next release?

**Comment by dhaluza** [comment]
When is next release?

**Comment by VBlack2019** [comment]
Please, give a temporary solution.
Thanks!
