### ISSUE TITLE
Image stretching

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#869]
**Describe the bug**
Some images in the body are stretching the width of the email

**To Reproduce**
Not sure of the exact steps but I have a sample of an image in a signature.

**Expected behavior**
Image matches the HTML structure of the email system that sent it.  The image is correct in Roundcube but not when viewed through SnappyMail.

**Screenshots**
SnappyMail:
![Screenshot 2023-01-20 145327](https://user-images.githubusercontent.com/93135814/213796187-0180992e-3d4d-4643-9f3f-6249a9fb5717.jpg)

Roundcube:
![Screenshot 2023-01-20 150151](https://user-images.githubusercontent.com/93135814/213796205-95310ea1-4b48-44b9-b99a-b7ca25ca7bb6.jpg)

**Please complete the following information:**
- Browser: Chrome (latest) and Brave (latest)
- IMAP daemon: dovecot
- PHP version: 7.4
- SnappyMail Version: 2.24.6

**Comment by the-djmaze** [comment]
Please post the html source of the message.
Or forward as attachment to issue869@snappymail.eu

Because SnappyMail modifies html to be responsive and that is different compared to most mail viewers.

**Comment by the-djmaze** [comment]
Got your email and looking for a solutions :wink:
