### ISSUE TITLE
v2.5.0 login mapping (and domain whitelist?) issue

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#87]
**SnappyMail version, browser, browser version:**
Snappymail 2.50
Firefox 88.0 64-bit
Windows 10 1903

**Expected behavior and actual behavior:**
Expect to just be able to login as with pre-2.5.0 versions
Actual: Can't login.

**Steps to reproduce the problem:**
I updated from 2.5.0-rc.3 to 2.5.0. I noticed I could not login due to a "Account is not allowed" message which is strange.

I use the Domain White List option, so I checked that and seemed okay.
BUTTTTT, in the White List I used to have the actual (short) user accounts listed, which did work for all users. But now it does not work for users with a Custom Login Mapping. So:
- For user "henk" with "henk@mydomain.tld" I have "henk" in the White List, which works.
- For user "kees" with "sjeeskees@mydomain.tld" I have Login Mapping "sjeeskees@mydomain.tld:kees" and "kees" in the White List. Which does not work anymore.

If I change "kees" to "sjeeskees" in the White List, I get ```snappymail: Auth failed: ip=192.168.x.y user=sjeeskees@mydomain.tld```
and a Dovecot/PAM ```authentication failure``` and ```check pass; user unknown``` because the logon is tried with "sjeeskees" and not the actual account name "kees".

So the White List changed and we need to use the pre-@ account instead of the actual account? Or I think the user mapping just does not work anymore?

**Logs or screenshots:**
n/a.

**Comment by the-djmaze** [comment]
Yes, i forgot to update the plugins repo

**Comment by ervee** [comment]
I updated the plugin via admin panel and I can login again! :)
