### ISSUE TITLE
Snappymail 2.24.6 broke the admin panel

### ISSUE THREAD

**Issue by lvarnava** [the-djmaze/snappymail#870]
Nextcloud  24.0.9
Snappymail 2.24.6

![2023-01-21_00-24-24](https://user-images.githubusercontent.com/32108411/213807916-720e93e0-ef2a-4608-98c1-7db1a385f99b.png)

**Comment by Gene-W** [comment]
I can share that I am experiencing this as well on a new install of the app.
![Screenshot from 2023-01-20 20-28-00](https://user-images.githubusercontent.com/19363963/213839935-3b4f6e32-62d1-4763-8fe4-0d1cc5ade440.png)

**Comment by the-djmaze** [comment]
Duplicate of #868

**Comment by ALEXSANPEDRO** [comment]
cant understand how to fix this
