### ISSUE TITLE
Nextcloud contacts suggestions is using system address book

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#872]
**Describe the bug**

Contacts suggestions in Nextlcloud plugin is using system addresbook to suggest contacts to users. It should suggests contacts only from user's addressbook. 

**To Reproduce**
1. Go to nextcloud instance with a new accounts (No contacts)
2. Click on new message
3. Start typing in `To` field
4. You will see contacts suggestions from users who are not present in your addressbook. 

**Expected behavior**

Suggest contacts only which are present in user's addressbook and not from system addressbook.

**Screenshots**
![image](https://user-images.githubusercontent.com/16881005/214126172-e51d5ee9-0794-4d97-b77f-876ed16a25ab.png)

None of these contacts are present in user's addressbook. They are coming directly from system addressbook

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

```bash
[2023-01-23 18:53:54.952][10363cbb] [INFO]: Array
(
    [0] => Array
        (
            [URI] => Database:test2.vcf
            [VERSION] => 3.0
            [PRODID] => -//Sabre//Sabre VObject 4.3.3//EN
            [UID] => test2
            [FN] => test2
            [N] => test2;;;;
            [EMAIL] => Array
                (
                    [0] => test2@e.email
                )

            [PHOTO] => VALUE=uri:http://0.0.0.0:8080/remote.php/dav/addressbooks/system/system/system/Database:test2.vcf?photo
            [CLOUD] => Array
                (
                    [0] => test2@0.0.0.0:8080
                )

            [isLocalSystemBook] => 1
            [addressbook-key] => 1
        )
)
```

**Additional context**

**Comment by the-djmaze** [comment]
There are several ways to have contacts.
1. JavaScript using Nextcloud logged in user
2. LDAP
3. CardDAV login in SnappyMail -> Settings -> Contacts

Which are you using?

**Comment by Niveshkrishna** [comment]
@the-djmaze I'm using the default contacts application of nextcloud https://apps.nextcloud.com/apps/contacts, and have Suggestions enabled in nextcloud plugin https://github.com/the-djmaze/snappymail/blob/7a53cae32f6ab37935e385deab2e509130380d45/plugins/nextcloud/NextcloudContactsSuggestions.php#L19

**Comment by the-djmaze** [comment]
Ok, then i have no idea why the Nextcloud Contacts app does that.
