### ISSUE TITLE
Some clarity on this app's dependency on Nginx for the sake of deploying inevitably to a Docker Swarm cluster with Traefik as ingress/reverse proxy.

### ISSUE THREAD

**Issue by Leopere** [the-djmaze/snappymail#873]
**Is your feature request related to a problem? Please describe.**
I'm looking to inevitably make the switch from RainLoop over to SnappyMail however I'm hoping that I can have my reverse proxy handle the TLS certificates instead of Nginx first of all is this possible or does the app have an opinion about how TLS is implemented and secondly is Nginx even necessary or is its role purely just to reverse proxy php and can I completely omit the nginx container from my deployment.

**Describe the solution you'd like**
Ideally just make it clear how to get a kick the tires works by default deployment from the docker-compose.yml with and without nginx and whether or not its going to be opinionated about it or not.  I really am hoping that I can inevitably deploy this to my Docker Swarm cluster and it would be really awesome if some of these conditions were met.

**Describe alternatives you've considered**
I've tried just pulling up a "kick the tires instance" by just doing `docker compose up -d` however nginx seems to fail instantly whining about TLS certificates that I don't wish to generate. 

**Additional context**
I think that about covers it from my perspective, I await any questions and am excited to get a chance to deploy this into my production!

**Comment by the-djmaze** [comment]
SnappyMail requires PHP and an HTTP Daemon.
You decide how that will be setup.

If you want to setup a "cloud" with many servers then it is important to know where you want to put the `_data_` directory.
The `_data_` contains all the configuration and user settings (domains, accounts, settings, cache, etc.).

**Comment by Leopere** [comment]
Ok fair enough, would it be feasible to get a slightly more vanilla Nginx example without TLS defaults?  The difference being that there are a number of self hosters that typically would have more than one web appliance on the same machine and like in my case I'm doing TLS termination via Traefik and LetsEncrypt certification.  Then doing cross host networking with Wireguard for full host to host encryption on the wire.  I only ask for an officially suggested method because I don't want to meddle with the app as much as possible.  Ideally I'd like to leave that entirely up to you and have my swarm cluster just pick up where you leave off and run with it.

**Comment by Leopere** [comment]
As for the _data_ directory I typically store mine on a GlusterFS or SeaweedFS storage volume however someone could probably do any number of alternative volumes like bind, sshfs, samba, nfs etc...

**Comment by the-djmaze** [comment]
I think the issue relies in the https/port 443 configuration that is shipped by default.

https://github.com/the-djmaze/snappymail/blob/f929c8fb69ea6f798364d2b0c95b6d637102cd69/docker-compose.yml#L57

https://github.com/the-djmaze/snappymail/blob/f929c8fb69ea6f798364d2b0c95b6d637102cd69/.docker/dev/nginx/default.conf#L3
https://github.com/the-djmaze/snappymail/blob/f929c8fb69ea6f798364d2b0c95b6d637102cd69/.docker/dev/nginx/default.conf#L13-L14

If so, i wonder if multiple docker-compose.yml configurations are possible.

**Comment by Leopere** [comment]
So one way you can go is you can have a number of compose style files like for example
base.yml 
tls.yml
notls.yml
Then you could use the old `docker-compose` to do something like compile an output file stacking variables together.

`docker-compose -f base.yml -f tls.yml config > docker-compose.yml` which will output a combined docker-compose.yml file.  I'm not 100% certain if the docker-compose-plugin is effectively capable of this yet they claim its in there.

**Comment by the-djmaze** [comment]
@Leopere read #965 it might help!

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/tree/master/examples

**Comment by Leopere** [comment]
> https://github.com/the-djmaze/snappymail/tree/master/examples

Thanks for all of your hard work!

**Comment by the-djmaze** [comment]
Thanks. You should also thank @leojonathanoh for making it.
