### ISSUE TITLE
[Nextcloud] Move themes outside of app folder 

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#875]
**Is your feature request related to a problem? Please describe.**

We have a custom theme developed for our nextcloud app. When a new release of snappymail is updated, our custom theme gets destroyed and theme gets reset for all users. 

**Describe the solution you'd like**

Move themes folder to appdata_snappymail 

**Describe alternatives you've considered**

Disable app, update app and then manually add our custom theme  to themes directory, enable app

**Additional context**

What is the best way to maintain a custom theme for snappymail nextcloud app?

**Comment by the-djmaze** [comment]
`appdata_snappymail` is also not a good idea because it could be outside public access (as it should, but that option is hidden on Nextcloud install).

You could make a pull request so that i ship it to all Nextcloud instances who use SnappyMail.

Else we could work out other options.

**Comment by Niveshkrishna** [comment]
Just in case anybody comes here looking for a solution: 

place your custom theme at `/var/www/html/themes/{YOUR_THEME}/snappymail/`

snappymail folder should contain
- style.css
- preview.png 


In admin settings of snappymail, set default theme as YOUR_THEME@nextcloud
