### ISSUE TITLE
Search contact suggestions

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#876]
Is it possible to add contact suggestions in search bar, and in the From and To Fields in the advanced search?

**Comment by the-djmaze** [comment]
> In the From and To Fields in the advanced search?

That would be a nice idea

**Comment by julio1501** [comment]
This was also integrated in the Rainloop and no longer works since the migration to snappymail.
That would be a very nice feature

**Comment by the-djmaze** [comment]
> This was also integrated in the Rainloop

Not in the versions i used. Did you have a special version?

**Comment by julio1501** [comment]
> Not in the versions i used. Did you have a special version?
In version 7.2.6, it was possible to see suggestions of contact addresses from Nextcloud without an existing address book.

**Comment by julio1501** [comment]
i solve it by using the plugin Contacts suggestions (LDAP)

**Comment by the-djmaze** [comment]
After much thought, currently this feature is too tricky.
Therefore i won't create it.
However, it should be possible that someone writes a plugin/extension that does it.
