### ISSUE TITLE
Admin in Nextcloud is overlapped

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#877]
Going to the admin section in Nextcloud it overlaps:

Removing 
position: absolute; 
in embed.css fixes it.

#content #rl-app #rl-left, #content #rl-app #rl-right {
    /*position: absolute;*/
}
![Screen Shot 2023-01-25 at 12 40 39 PM](https://user-images.githubusercontent.com/2196272/214654347-9ea7e936-cf99-488a-8e89-e6532d488376.png)

**Comment by cm-schl** [comment]
Hi,
thanks for your input - this is already discussed in #868 and will be fixed in the next release.
