### ISSUE TITLE
ZIP Files cannot be uploaded from Desktop to attachments (other files can be uploaded)

### ISSUE THREAD

**Issue by Bolli84** [the-djmaze/snappymail#878]
Zip-files cannot be uploaded to the attachments. All other files can be uploaded.

Drag and Drop a File (PDF) into the text window: Works
Add A File from Nextcloud: Works
Add a file (PDF) by the attachment button: Works
Drag and Drop a File (*.ZIP) into the text window: FAIL with unknown error
Add A File (*.ZIP) from Nextcloud: Works
Add a file (*.ZIP) by the attachment button: FAIL with unknown error

**Expected behavior**
Correct uploade

SnappyMail Version: 2.24,5

**Comment by jerheij** [comment]
I just bumped into this issue as well on 2.28.3.
