### ISSUE TITLE
Exception: Call to undefined method RainLoop\Actions::ThemeLink() 

### ISSUE THREAD

**Issue by kennyMC** [the-djmaze/snappymail#880]
**Describe the bug**
snappymail cannot open and throws an exception

**To Reproduce**
1. open snappymail via nextcloud

**Screenshots**
![image](https://user-images.githubusercontent.com/5913075/215080465-2d917eae-04d5-4931-95c0-4bcba532f05d.png)

**Please complete the following information:**
- IMAP daemon: dovecot
- PHP version: 8.0.27
- Nextcloud 25.0.3
- SnappyMail Version: 2.25.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Exception: Call to undefined method RainLoop\Actions::ThemeLink() in file '/var/www/clients/client1/web2/web/apps/snappymail/lib/Controller/PageController.php' line 69
/var/www/clients/client1/web2/web/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/clients/client1/web2/web/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/clients/client1/web2/web/lib/base.php - line 1047:

OC\Route\Router->match()

/var/www/clients/client1/web2/web/index.php - line 36:

OC::handleRequest()

Verursacht durch Error: Call to undefined method RainLoop\Actions::ThemeLink()
/var/www/clients/client1/web2/web/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\SnappyMail\Controller\PageController->index()

/var/www/clients/client1/web2/web/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/clients/client1/web2/web/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/clients/client1/web2/web/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/clients/client1/web2/web/lib/base.php - line 1047:

OC\Route\Router->match()

/var/www/clients/client1/web2/web/index.php - line 36:

OC::handleRequest()

**Comment by the-djmaze** [comment]
Please remove and reinstall again. Your setup is corrupt.

**Comment by the-djmaze** [comment]
P.S. Other option that might fix your issue is this code:
```php
<?php
opcache_reset();
```

**Comment by kennyMC** [comment]
> P.S. Other option that might fix your issue is this code:
> 
> ```
> <?php
> is_callable('opcache_reset') && opcache_reset();
> ```

thanks, this fixed the issue.
