### ISSUE TITLE
By default "most" emails are tagged with label1

### ISSUE THREAD

**Issue by CodingNomad** [the-djmaze/snappymail#881]
**Describe the bug**
I'm primarily using snappymail in a Nextcloud environment on a self-hosted postfix/dovetail system.
Before that I was using Rainloop. Since migrating to snappymail, most new messages in the inbox are tagged with label1. Is there a way to completely disable the tagging-feature, or at least making sure, that by default no labels are applied?

**To Reproduce**
1.) send email to my primary mail account
2.) open inbox
3.) see message appear labeled with a tag "important" (label1)

**Expected behavior**
Newly incoming messages should not appear with a tag.

**Screenshots**
<img width="214" alt="firefox_w3AQHymO1m" src="https://user-images.githubusercontent.com/24758984/215166294-e809bd1f-3c3d-48fb-aa83-591010043d22.png">

**Please complete the following information:**
- Browser: Firefox
- IMAP daemon: dovecot
- PHP version: 7.4.3
- SnappyMail Version: 4.2.5

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
-

**Additional context**
-

**Comment by the-djmaze** [comment]
SnappyMail never add flags auto-magically.
Are you certain no other application or Sieve filter is in use that does this?

`$label1` is a Thunderbird flag so if you are not using Thunderbird nor Sieve filter rules, then i have no idea.

And what happens if you remove the `$label1` flag? Does it come back?

**Comment by CodingNomad** [comment]
Thanks, @the-djmaze, for your reply. 

No, I haven't activated any Sieve scripts. 
>  Does it come back?
No, once removed, the message will be displayed without tags.

Is the $label1 tag stored in the message header itself, or are these additional attributes which are stored somewhere else?
Can the tagging-feature be turned off, completely?

**Comment by the-djmaze** [comment]
Tagging can't be turned off at the moment as it detects that the IMAP server supports it.

I will look if adding an option for it will work.

**Comment by CodingNomad** [comment]
Thank you, much appreciated.

**Comment by the-djmaze** [comment]
Tested, but this creates serious issues.
Not only $label1 is gone, but also the core IMAP flags and then you can't use seen, unseen, delete, etc.

I advice you to find out which mail application creates this iddiotic behavior.

**Comment by the-djmaze** [comment]
https://github.com/nextcloud/mail/issues/5260

**Comment by CodingNomad** [comment]
Good catch, @the-djmaze. Thank you. Sure enough, on my Nextcloud instance, the standard mail app was installed, due to a botched upgrade on SnappyMail. But I hadn't actively logged in to it, since SnappyMail was brought back to life. 

I've now disabled the app, and post a final update regarding this issue.

**Comment by CodingNomad** [comment]
Just as a follow-up to my previous message: It looks like - as mentioned by you, the Nextcloud Mail app was interfering in this case. Problem was resolved by disabling the app. Thanks, again.

**Comment by the-djmaze** [comment]
Your welcome!
It's good that my brain still works and did think about the Nextcloud Mail 😉

**Comment by scubamuc** [comment]
@the-djmaze, thanks for this tip. I was wondering why all my mails were being tagged without my request. Turns out that one of my instances had "Nextcloud Mail app" enabled and was happily tagging my mails. That's a bad decision by the Nextcloud Mail folks, to make that setting default. Sad but true. Another reason for using Snappymail... great software, great team ✔

**Comment by Luncheon3462** [comment]
> Tested, but this creates serious issues. Not only $label1 is gone, but also the core IMAP flags and then you can't use seen, unseen, delete, etc.
> 
> I advice you to find out which mail application creates this idiotic behavior.

@the-djmaze is it possible to add an option to hide tags/labels to avoid these errors but still have no tags viewable to the end user?

**Comment by the-djmaze** [comment]
And now you can disable the Nextcloud Mail "bug" by default.
https://github.com/nextcloud/mail/pull/9609
