### ISSUE TITLE
Incompatible with Cloudflare -> Rocket Loader

### ISSUE THREAD

**Issue by Stage4000** [the-djmaze/snappymail#882]
**Describe the bug**
Snappymail fails to load on domains that are proxied through Cloudflare with rocket loader enabled.

**To Reproduce**
1. Put site behind Cloudflare.
2. Enable rocket loader in the Cloudflare dashboard.
3. Load any portion of Snappymail.

**Screenshots**
<img src=https://screenshot.stage4000.com/VuKe0/JomEwAgo45/raw>

**Please complete the following information:**
- Browser: Chrome 109.0.5414.120
- IMAP daemon: Irrelevant
- PHP version: Irrelevant
- SnappyMail Version: 2.25.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
(anonymous) @ NwFyS9x3JmoO2AGYlJwCRH4tWiU.js:4
rocket-loader.min.js:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-151af67b-d413-48d7-9170-f6b3c0825623'". Either the 'unsafe-inline' keyword, a hash ('sha256-KheQcMe1ilQwRcXZxJB/oNgSiegYfBowcSHd8K3bzL0='), or a nonce ('nonce-...') is required to enable inline execution.

t.activateScript @ rocket-loader.min.js:1

**Additional context**
I have turned rocket loader off on my instance of Cloudflare but I feel that this issue may not be as easy for others to troubleshoot and so it may be necessary to catch the error and tell the user to turn off rocket loader via their Cloudflare dashboard or to make it work with rocket loader enabled.

**Comment by the-djmaze** [comment]
It's not that SnappyMail is "incompatible".
It's because SnappyMail doesn't want anyone to inject code (malicious or not) :wink: 

SnappyMail does allow to modify the CSP (content security policy) but it also doesn't need "Rocket Loader" as it faster without it.

**Comment by Stage4000** [comment]
Alright, I appreciate that response and figured as much.

I am running into another issue though, everything is working fine on the IMAP end of things, but when I try to send mail out it fails. I am only using the PHPmail function (because it is compliant with my host's TOS and firewalls.) and when I test everything comes back good. But when trying to send an actual message it fails.

`[2023-01-27 21:05:52.372][185a2eed] JSON[INFO]: {"Action":"SendMessage","Result":false,"ErrorCode":302,"ErrorMessage":"","ErrorMessageAdditional":"Typed property MailSo\\Net\\NetClient::$Settings must not be accessed before initialization","epoch":1674853552}`

**Comment by Stage4000** [comment]
SnappyMail is still trying to use SMTP despite being set to use PHPmail. This is returning a fun combination of errors relating to the fact that the SMTP host input is empty and no error handling exists for such a contingency.

**Comment by the-djmaze** [comment]
Thanks for finding php mail() bug.
This commit should fix it https://github.com/the-djmaze/snappymail/commit/c6500dfe14b3b938972318a102004ca35c5d447d

**Comment by Stage4000** [comment]
Ive made the changes to my copy but it is still giving me the same error.

**Comment by the-djmaze** [comment]
Oh nevermind, i see the real issue.
Will fix that later.

**Comment by Stage4000** [comment]
Alright, Ill be patiently waiting. Thank you for your prompt responses and support.

**Comment by the-djmaze** [comment]
Changes in #884 are better.
Editing on mobile, so i didn't test yet
