### ISSUE TITLE
SMTP error while using PHP mail()

### ISSUE THREAD

**Issue by the-djmaze** [the-djmaze/snappymail#884]
SnappyMail is still trying to use SMTP despite being set to use PHPmail. This is returning a fun combination of errors relating to the fact that the SMTP host input is empty and no error handling exists for such a contingency. 
I was able to trace back the error to /snappymail/v/2.25.0/app/libraries/RainLoop/Actions/Messages.php at approx line 862, its odd that the error traces back to a private function smtpSendMessage when I don't have SMTP enabled. Furthermore since I did not supply a SMTP host the error handler even managed to bug out causing layers of errors in the log.

_Originally posted by @Stage4000 in https://github.com/the-djmaze/snappymail/issues/882#issuecomment-1407154967_

**Comment by Stage4000** [comment]
This fix seems to work.

**Comment by the-djmaze** [comment]
Great
