### ISSUE TITLE
Provider List

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#886]
What email providers are using this as their webmail service?

**Comment by Zero3K** [comment]
I found one thanks to http://www.emaildiscussions.com/. It is at https://openmbox.net/.

**Comment by the-djmaze** [comment]
MXRoute also https://mxroute.com/

**Comment by Zero3K** [comment]
https://xyamail.com/ is another provider that uses it as its webmail service.

**Comment by the-djmaze** [comment]
Made a list that can be update :wink: 
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#email-providers

**Comment by Zero3K** [comment]
Thanks.
