### ISSUE TITLE
Failed loading /snappymail/v/2.25.0/static/js/min/libs.min.js

### ISSUE THREAD

**Issue by sgutermann** [the-djmaze/snappymail#890]
**Describe the bug**
Can not load snappymail in NextCloud anymore.

Failed loading /snappymail/v/2.25.0/static/js/min/libs.min.js

**To Reproduce**
Install newest Netcloud and SnappyMail App.

**Expected behavior**
Normal Screen.

**Please complete the following information:**
- NextCloud Version: 25.0.3
- SnappyMail Version: 2.25.0

**Additional context**
I guess the starting "/" slash seems like a typo as the js is somewhere in there and not in the root directory.

**Comment by sgutermann** [comment]
Thank you, fixed with v2.25.1 !!

**Comment by art2crazy** [comment]
Actually, I just updated to 2.25.1 and it broke my install with the message:
An error occurred.
Please refresh the page and try again.Failed loading /cloud/apps/snappymail/app/snappymail/v/2.25.1/static/js/min/libs.min.js

art

**Comment by the-djmaze** [comment]
Does it work when you delete `/cloud/apps/snappymail/app/snappymail/v/2.25.1/static/.htaccess`?

**Comment by stepcellwolf** [comment]
I'm having this issue with SnappyMail 2.36.0. I had the NC in one subdomain and + /cloud folder. After moving to another subdomain without a folder, I got the error when I tried to open SnappyMail.

`
An error occurred.
Please refresh the page and try again.Failed loading /cloud/apps/snappymail/app/snappymail/v/2.36.0/static/js/libs.js
`

Tried to delete the .htaccess file, reload nginx. Remove and install the app few times, still nothing. Any suggestions?

Nextcloud version: 28.0.3

Thanks.
