### ISSUE TITLE
Themes settings with multiaccount

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#891]
If you use more then one account, all accounts used one theme.

**To Reproduce**
1. Go to 'settings->themes'
2. Click on 'Linen'
3. Switch account
4. Go to 'settings->themes'
5. Click on 'Love'
6. Switch between two accounts.

**Expected behavior**
Every account use his own theme

**Please complete the following information:**
- Browser: Firefox 109
- PHP version: 8.1.14
- SnappyMail Version: 2.25

**Comment by Parodontitis** [comment]
Enhancement? This was working with 3 accounts and 3 themes very fine for years!

**Comment by the-djmaze** [comment]
Ah, i see and you are right. It still works for me.

**Comment by the-djmaze** [comment]
Try with https://github.com/the-djmaze/snappymail/releases/tag/v2.25.2

**Comment by Parodontitis** [comment]
unfortunately still broken. 

In version 2.25.1 was the second account master for the themes. In 2.25.2 is the first one. When logging in it shows the correct theme, but after the switch to the other account it remains so.

Thanks for your help.

**Comment by the-djmaze** [comment]
> unfortunately still broken.

Yes and i probably found it in the above commit (not part of v2.25.2) that's why i closed it.
Index.html gets cached but somehow the hash failed on some settings.

When edit application.ini in your current setup and set `cache_system_data` to `Off` it should work for now.

**Comment by Parodontitis** [comment]
Yep it works fine. Thank you
