### ISSUE TITLE
Settings Page is bigger than the Account Page

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#897]
The Settings Page is bigger than the Account Page. Here are some screenshots to show the issue:

![account](https://user-images.githubusercontent.com/6194332/216089107-3045122c-bc6b-4071-9d77-3ab5cc35f692.png)
![settings](https://user-images.githubusercontent.com/6194332/216089489-35bcbab9-d4e9-4fdd-bb2b-8f8926d7d3d1.png)

**Comment by the-djmaze** [comment]
This might solve it https://github.com/the-djmaze/snappymail/commit/2b8fbaf091b8ef6f28bae07791342cf22b9c0178

**Comment by the-djmaze** [comment]
Try with https://github.com/the-djmaze/snappymail/releases/tag/v2.25.2

**Comment by Zero3K** [comment]
I let him know about the new version. Now to wait for it to be upgraded and then I will let you know about this bug and the other one.

**Comment by Zero3K** [comment]
The commit that you mentioned has fixed the issue that is being reported.
