### ISSUE TITLE
Add Dark Theme Variants to Existing Light Themes

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#899]
**SnappyMail version, browser, browser version:**
2.25.2

Not sure if this is the best place for this, but, we love some of the themes available (namely Love and Stripes).

Can a dark variation be added to these themes and/or other themes? (Or can steps be provided to do so and we can submit a PR for them).

**Comment by the-djmaze** [comment]
You can create a PR:
1. Fork this project
2. Create your theme in snappymail/v/0.0.0/app/themes
3. Commit in branch
4. Create the PR

Or custom theme for your own, read https://github.com/the-djmaze/snappymail/wiki/Custom-Themes

**Comment by TheCuteFoxxy** [comment]
PR submitted #913

**Comment by the-djmaze** [comment]
Done
