### ISSUE TITLE
CardDAV sync broken

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#90]
**Describe the bug**
The synchronization of contacts with CardDAV fails.

**To Reproduce**
1. Go to the addressbook.
2. Manually start the CardDAV synchronization.

**Expected behavior**
Contacts get synchronized.

**Screenshots**
see attached error log

**Desktop (please complete the following information):**
 - Google Chrome Version 90.0.4430.212
 - SnappyMail Version 2.5.1

**Additional context**
[carddav_error.log](https://github.com/the-djmaze/snappymail/files/6511072/carddav_error.log)

**Comment by the-djmaze** [comment]
Your log says '401 Unauthorized'
Is the username and password correct?
