### ISSUE TITLE
Reloading status never finishes

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#903]
# Steps to reproduce the issue

1. Access to the sign in page.
2. Enter username and password. Then click 'Sign In'.
   -> Mailer page is displayed
3. Click 'Reload' button of the web browser.

# Expected behavior

Mailer page is displayed again.

# What really happens

Reloading status never finishes as following.

<img width="1525" alt="SnappyMail reloading" src="https://user-images.githubusercontent.com/5249848/216479415-4669236f-f5ac-4258-b5f9-f72d5860fb61.png">

To escape from it I need to remove cookies and sign in again.

# Conditions

- Browser:
  1. Google Chrome 109.0.5414.120 on 64bit Windows 2022H2
  2. Microsoft Edge 109.0.1518.78 on 64bit Windows 2022H2
  3. Mozilla Firefox 109.0.1 on 64bit Windows 2022H2
  4. Google Chrome 109.0.5414.177 on Android 12
  5. Microsoft Edge 109.0.1518.53 on Android 12
  6. Mozilla Firefox 109.1.1 on Android 12
- IMAP daemon: Dovecot 2.3.20
- PHP version: 8.2.1
- SnappyMail Version: 2.25.2

I have another instance that uses SnappyMail 2.25.2, PHP 7.4.33 and Dovecot 2.3.13, and the issue doesn't happen with it. So the issue may relate to PHP version.

**Comment by the-djmaze** [comment]
I also sometimes have this issue in PHP-FPM 8.2 and i must restart php-fpm to get it fixed.

Currently i also found nothing (even with PHP Xdebug trace) why it fails.

**Comment by the-djmaze** [comment]
When you open developer tools network tab of the browser.
Does the request also doesn't respond as on mine?

**Comment by yasuhirokimura** [comment]
Today I have to reboot the server in question and after that the issue dissapeared and never happens with any blowser.

> I also sometimes have this issue in PHP-FPM 8.2 and i must restart php-fpm to get it fixed.
> 
> Currently i also found nothing (even with PHP Xdebug trace) why it fails.

Before rebooting server I tried restarting php-fpm some times but the issue still happened.



> When you open developer tools network tab of the browser. Does the request also doesn't respond as on mine?

Sorry, I didn't try it. If the issue happen again, then I'll try.

**Comment by the-djmaze** [comment]
Ok, then i will close the ticket for now as it resolved.
Feel free to reopen when needed.
