### ISSUE TITLE
Minor Theme Issue - Page Numbers

### ISSUE THREAD

**Issue by HeyVern** [the-djmaze/snappymail#905]
**Describe the bug**
In many themes (default is one I use), the page numbers on email listings are hard to see.  Appears to be white on light grey.  Note I use the dark theme in NextCloud (not sure if that makes a difference)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48611220/216629983-450fc28d-5d7f-442e-bde9-aa9526e115c6.PNG)

**Please complete the following information:**
- Browser: [Chromium: 109.0.5414.119]
- SnappyMail Version: 2.25.2

**Comment by the-djmaze** [comment]
The dark theme in Nextcloud uses a light font.
The light theme in Nextcloud uses a dark font.

When you choose the opposite in SnappyMail you get this strange behavior.
The Nextcloud theme in SnappyMail should merge nicely with your Nextcloud theme.
