### ISSUE TITLE
Mobile View glitch with adding Nextcloud attachments to a new mail -  on cellphone only

### ISSUE THREAD

**Issue by Reis-A** [the-djmaze/snappymail#906]
**Describe the bug**
This happens with my Android phone on a Chrome browser with the mobile view of snappy mail on  next cloud.
It doesn't happen on a Desktop PC when I turn on the mobile setting manually.

In the snappymail mobile view, whe composing a new email, there is this greatly appreciated new feature of adding an attachment directly from nextcloud by link or direct attachment (by pressing this next cloud style blue button)
When I press this button to select the desired file from next cloud the three buttons that are supposed to be on the bottom are not shown on my cellphone screen. They seem to appear for a short moment of time but then the whole homedirectory tree has loaded, the buttons are not shown on the screen. it might be a problem with the size of some view box or so...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Browser: chrome on android
- IMAP daemon: [e.g. courier, dovecot] groupies
- PHP version: 8.1.9
- SnappyMail Version: the most recent 2.25.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
There are some more glitches in the mobile view.
My Firefox on Android renders higher then the actual view and that also makes it weird.
Every release i try to fix parts and find solutions 😉

**Comment by the-djmaze** [comment]
# Firefox
![Screenshot_2023-02-04-22-56-00-943_org mozilla focus](https://user-images.githubusercontent.com/3752035/216791476-d26b55a6-b11d-4ce2-9030-e139a6ed3339.jpg)
![Screenshot_2023-02-04-22-55-57-851_org mozilla focus](https://user-images.githubusercontent.com/3752035/216791477-f85ba516-00d0-48d0-a6d6-a2e94f72cafe.jpg)

# Chrome
![Screenshot_2023-02-04-22-57-36-048_com android chrome](https://user-images.githubusercontent.com/3752035/216791486-c7417cb0-bb72-4c5c-be15-085bbeb4c22e.jpg)

**Comment by the-djmaze** [comment]
I will do some more testing with `100dvh` and keyboard detection, as found at https://www.terluinwebdesign.nl/en/css/incoming-20-new-css-viewport-units-svh-lvh-dvh-svw-lvw-dvw/

**Comment by the-djmaze** [comment]
Should be fixed with v2.25.4
