### ISSUE TITLE
cosmetics: fixed arrows in thread view while scrolling down

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#908]
Hello,

**Describe the bug**
In thread view, with Firefox and Chromium, the arrows in front of each message in the thread are fixed with the default theme.
It break the layout as soon as we scroll down

**Expected behavior**
The should not be fixed.

**Screenshots**
Obviously, it is noticeable on long threads (otherwise no scrolling down or up). For the demo purpose in just reduce the window size: 

![Screenshot 2023-02-04 at 11-05-36 Boîte mail - e2](https://user-images.githubusercontent.com/1160681/216761614-9aa4c908-5082-46c5-a03c-8b433ac8c483.png)
![Screenshot 2023-02-04 at 11-05-47 Boîte mail - e2](https://user-images.githubusercontent.com/1160681/216761617-c2a98df6-dda7-40da-90de-0e427e770615.png)
![Screenshot 2023-02-04 at 11-06-11 Boîte mail - e2](https://user-images.githubusercontent.com/1160681/216761618-47911597-94a7-490b-ae9a-a73fb41eabb5.png)

**Please complete the following information:**
- Browser: chromium 109, firefox 109
- SnappyMail Version: 2.25.3

**Comment by the-djmaze** [comment]
Already solved in commit https://github.com/the-djmaze/snappymail/commit/a0a9d8fd65d28d614746529aa2edea5b442a3e7a
