### ISSUE TITLE
Square in certain email's subject

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#911]
There's a square in certain email's subject. Please see if it could be removed or not. The email is attached.

[Keeping your money safe from fraud -.txt](https://github.com/the-djmaze/snappymail/files/10610289/Keeping.your.money.safe.from.fraud.-.txt)

**Comment by the-djmaze** [comment]
These days people love emoji's.
 I also get emails with squares because my fonts don't have them all.

But when i'm behind a PC i will check it ;)

**Comment by the-djmaze** [comment]
I was correct! Nothing we can do about it.
![afbeelding](https://user-images.githubusercontent.com/3752035/216816249-35c78562-bfe7-4783-a90d-1bceefa2aafd.png)

**Comment by Zero3K** [comment]
What font is the one that has it?

**Comment by the-djmaze** [comment]
Firefox has it built in. Chrome has status "won't fix" and relies on OS you use

**Comment by Zero3K** [comment]
Is there any font that could be used?

**Comment by the-djmaze** [comment]
Maybe "Noto Color Emoji" font?

**Comment by Zero3K** [comment]
Okay.
