### ISSUE TITLE
Undefined variable $sUser

### ISSUE THREAD

**Issue by negati0ns** [the-djmaze/snappymail#915]
This is similar, I think, to #619.  I am running version 2.25.3.  In the logs I have:

 Undefined variable $sUser in /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php on line 128

I don't think it affects the app, just noting it for reference.

Great app.

**Comment by the-djmaze** [comment]
Thanks!

Issue caused by adding #898 and i couldn't test in Nextcloud 25.
