### ISSUE TITLE
Custom Theme Variants Repeat Background

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#918]
**Describe the bug**
Custom variants of the shipped themes, cause a repeated background, despite using identical image assets. This has been specifically observed on the "Blurred" theme and and themes using non-shipped assets.

**To Reproduce**
1. Copy an existing theme
2. Modify the styles.css to match [LoveDark CSS](https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/themes/LoveDark/styles.css)
3. Clear caches
4. Select new theme
5. Observe tiling

**Expected behavior**
The theme should cover the full viewport without repeating.

**Screenshots**
Correctly Displayed "LoveDark" theme
![LoveDark](https://cdn.thecutefoxxy.com/m1Jfv4.png)

Incorrectly Displayed "Blurred" theme with custom css and shipped assets
![BlurredDark](https://cdn.thecutefoxxy.com/RtpilF.png)

Incorrectly Displayed Custom theme with custom css and non-shipped assets
![BlackWood](https://cdn.thecutefoxxy.com/eMK6gh.png)

**Please complete the following information:**
- Browser: Firefox 109.0 (64-bit)
- PHP version: 7.4
- SnappyMail Version: 2.25.4

**Additional context**
The CSS used in my dark variation of "Love" is identical to the CSS being used in the new theme variants.

**Comment by the-djmaze** [comment]
Correct. `background-size: cover;` will solve that.

**Comment by TheCuteFoxxy** [comment]
> Correct. `background-size: cover;` will solve that.

We thought so to, but it did not do so for us. Are you able to reproduce an instance of this working using the CSS?

**Comment by TheCuteFoxxy** [comment]
We are using the following CSS for MAIN
```css
	--main-color: #fff;
	--main-bg-color: #48525C;
	--main-bg-image: url("images/background.jpg");
	--main-bg-size: cover;
```
