### ISSUE TITLE
v2.5.1: Plugin for password reset and registration URL missing from repository

### ISSUE THREAD

**Issue by Semirben** [the-djmaze/snappymail#93]
**Describe the bug**
In commit 8af35f7d39951cb67a2dcee8455728076be92184 you moved the "Forgot Password"-URL and "Registration"-URL to a plugin and therefore removed both options from the admin panel and UI.
Unfortunately the plugin doesn't seem to be in the plugin directory (https://github.com/the-djmaze/snappymail/tree/master/plugins) and so I'm unable to install it.

**To Reproduce**
1. Login to admin panel
2. Go to "Packages"
3. Expect plugin to re-enable mentioned URLs
4. No package with required function available (see screenshot)
![Snappymail_plugin_repo](https://user-images.githubusercontent.com/8372637/119257212-8d16d500-bbc4-11eb-9bd8-b0118417db35.png)

**Expected behavior**
Plugin to set password reset and registration URLs is available in repository

**Desktop:**
 - Firefox 88.0.1 64-Bit
 - SnappyMail Version 2.5.1
 - Linux Mint 20.1

**Comment by the-djmaze** [comment]
You could try with this file.
Rename to login-register.phar (github doesn't allow phar files).
Upload to your '/_data_/_default_/plugins' folder.

[login-register.phar.zip](https://github.com/the-djmaze/snappymail/files/6559399/login-register.phar.zip)

**Comment by Semirben** [comment]
Thanks, I added the file to `/data/_data_/_default_/plugins` folder like below
```
bash-5.1# ls -l /var/www/htdocs/mail.XXX/data/_data_/_default_/plugins/
total 12
drwxr-xr-x  6 www  www   512 May 23 12:16 change-password
-rw-r--r--  1 www  www  3678 May 28 10:55 login-register.phar
```
In the plugin tab I can enable the plugin but there's no option to configure it in any way (e.g. to set the required URLs). I then created the file `/data/_data_/_default_/configs/plugin-login-register.ini` with
```
; SnappyMail plugin (login-register)

[plugin]
forgot_password_link_url = "https://mail.XXX/reset-password"
registration_link_url = "https://mail.XXX/register"
```
but unfortunately none of the links appears on the login page.
Attached is a screenshot of the admin panel and one of the login page
![Screen_login-reset_admin](https://user-images.githubusercontent.com/8372637/119959632-7695c280-bfa4-11eb-875d-ec54668b3aec.png)
![screen_login](https://user-images.githubusercontent.com/8372637/119959723-8f9e7380-bfa4-11eb-8cfe-8ffa6bc7b39f.png)

**Comment by the-djmaze** [comment]
Thanks, i will do some tests when i have the time.

**Comment by the-djmaze** [comment]
Solved for next release.
Thanks for reporting!
