### ISSUE TITLE
Loading and no results are repeatedly displayed

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#933]
**SnappyMail version, browser, browser version:**
2.25.4
Safari(iOS), Safari(macOS)

**Expected behavior and actual behavior:**
One-time display. The process is not repeated.

**Steps to reproduce the problem:**
1. Search for words that will never be found.
2. Then, the text "not found" and "loading" are repeated. The repetition may stop after a few times.

**Feature Request**
Please add an "Unread Mail Extract" button to the tool buttons at the top.
I use SnappyMail mainly on my smart phone and often only show unread emails. I always open advanced search, then I scroll down the screen and enable the unread email checkbox. This procedure is very inconvenient.

**Comment by the-djmaze** [comment]
> Please add an "Unread Mail Extract" button to the tool buttons at the top.

You can click/touch on the unread counter.
![afbeelding](https://user-images.githubusercontent.com/3752035/217787919-c716b895-add1-485a-a3c0-34b2b02f387d.png)
