### ISSUE TITLE
About contact / API ?

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#934]
This is more a question, about the contacts management within the admin panel.

The choice `Mysql` is not clear to me : the default dsn is `mysql:host=127.0.0.1;port=3306;dbname=rainloop` but there is no mention of the table name and its structure ? 

I ask because we have our own contact database, and we were wandering if this option could be used to read our own contacts.
Also, would you consider a feature request that would add an API call option here ? 

Finally, I suppose that in the case Snappymail is a Nextcloud app, the external CardDAV server is Nextcloud, right ? How often contacts are read from Nextcloud when this option is active ?

Thanks for all you do in this great app !

**Comment by the-djmaze** [comment]
> there is no mention of the table name and its structure ?

Correct. SnappyMail and RainLoop use their own database tables.
The difference is that RainLoop has each field in separate table records and SnappyMail stores the whole VCARD in 1 record (with some backwards compatibilitiy.

If you want to use your existing tables, you must write a AddressBook extension/plugin that does all abacadabra.

> How often contacts are read from Nextcloud when this option is active ?

Depends how often the synchronization is called.

**Comment by the-djmaze** [comment]
Here's a custom AddressBook example:
https://github.com/the-djmaze/snappymail/tree/master/plugins/kolab

**Comment by mmallejac** [comment]
Thanks ! We'll see what we can do here !

**Comment by mmallejac** [comment]
Hello !

I re-open this issue since we've initiated the development of a small Snappymail plugin which goal is to provide contact suggestions based on our own contact database.
We've taken imap-contacts-suggestions as a base.

We're not very proficient in PHP, but it should be enough for that purpose.
So far our code does not work at all :-\ 

![image](https://github.com/the-djmaze/snappymail/assets/11666281/605a54c7-7dce-4b46-a0b0-9fe17a2d8506)

We're not sure about what is wrong, logging / printing debug messages do not seem to work.

Any hints would be very much appreciated !

Take care

**Comment by the-djmaze** [comment]
`mysql_connect` is very old. Are you sure that works?

**Comment by mmallejac** [comment]
Not at all !
Any advice to replace it ?
