### ISSUE TITLE
whitelist is not used with option always if DKIM valid - simplification of options

### ISSUE THREAD

**Issue by yeupou** [the-djmaze/snappymail#938]
Thanks for the work done on  #201

That being said, users that want to whitelist some address/domains are likely also interested into approval of images when DKIM is valid.

In current version 2.25.5, "show if DKIM is valid" is excluding other options like the whitelist.

I think you can simplify the whole option set. 
We can assume that if someone is not interested in whitelisting, he can simply empty/not use the whitelist.
We can also assume that  if undecided, the interface  will always provide the option (ask) to show the images.

So instead of a menu with four  options, you can have something shorter that will allow more use case (like whitelist + dkim)

External images  :
☐ always show 
☒ show if DKIM valid
additional whitelist :  [_________________________]

I dot not know if it is complicated to implement, but maybe if  "always show"  is checked,  the rest "show if DKIM ... whitelist"  could be greyed out.

**Comment by yeupou** [comment]
Additional info: it looks like currently, if the account is configured to use a whitelist that is empty, it will always match, instead of never match (and prevent any addition to the list, as a side effect).

So it prevents to set the whitelist as default for users. 

That problem would be fixed if whitelist is handled like suggested (always on, because why setting a whitelist otherwise?). 

Regards

**Comment by the-djmaze** [comment]
The list could be much bigger:

* Always ask
* Only ask when DKIM is valid
* Whitelist when DKIM is valid else ask
* Whitelist else ask
* Whitelist or when DKIM is valid
* Show always when DKIM is valid
* Show always

The question is: is it useful?
I don't think this complexity makes it easier for most users.
The option `Show always when DKIM is valid` is already not understandable by most users.

**Comment by yeupou** [comment]
Well, clearly I am advocating for less options than this and less than currently.

"always ask" makes little sense;  any other option means that obviously it is not "always not".

The current setup prevent benefiting from the whitelist and DKIM. I am only suggesting removing one option, not to add any.

So I stand by my suggestion, even though how to phrase it to reduce the level of confusion is not an easy task.

Autoload of external images:
☐ no matter the source
☒ when the mail is DKIM signed
according to whitelist: [_________________________]

Only two checks boxes and the whitelist list (that someone that does not want will leave empty). 


I think it cover most cases you listed:


**Always ask**
☐ no matter the source
☐ when the mail is DKIM signed
according to whitelist: [_________________________]

**Only ask when DKIM is valid**
_I dont understand this one:  you mean that the interface would completely disallow the user to show images if the message lack signature? That seems to be quite harsh considering we cannot expect all valid sender to use DKIM._ 

**  Whitelist when DKIM is valid else ask **
_Not sure to understand this one too. If we already directly show images when DKIM is valid, why would we need to fill the whitelist?  This would work with:_
☐ no matter the source
☒  when the mail is DKIM signed
according to whitelist: [_________________________]
_Or it is that you want to restrict addition to the whitelist from mails that are properly DKIM signed ? Rough, but why not._

**   Whitelist else ask **
☐ no matter the source
☐  when the mail is DKIM signed
according to whitelist: [blablabla bliblibli__________]

**   Whitelist or when DKIM is valid **
☐ no matter the source
☒  when the mail is DKIM signed
according to whitelist: [blablabla bliblibli__________]

** Show always when DKIM is valid **
☐ no matter the source
☒  when the mail is DKIM signed
according to whitelist: [_________________________]

**  Show always **
☒ no matter the source
(greyed out:  ☒  when the mail is DKIM signed
according to whitelist: [_________________________])


As said, I think we these two checkbox and the whitelist, most case are covered. If you feel it is best to have finely grained DKIM policy, in this case, I would suggest:

☐ no matter the source
DKIM policy :  menu [restrict whitelist to|always show] 
according to whitelist: [_________________________]

This would cover the additional case of restricting addition to whitelist to addresses from DKIM signed mails. Obviously, if the DKIM policy "always show" is set, no need to fill the whitelist.


Or to put in logic: 

- always show=1 :  show
- always show=0, whitelist=something : show if /something/m else  add_to_whitelist
- always show=0, whitelist=something, dkim_policy=show : show if (/something/m or dkim=valid)  else  add_to_whitelist
-  always show=0, whitelist=something, dkim_policy=restrict : show (if /something/m and dkim=valid) else if dkim=valid (add_to_whitelist)

Obviously, restricting the whitelist to DKIM signed mail is harsh. I am not sure it will be, in the current state of thing, very useful.

As you asked yourself, is that level of complexity useful. Probably not. But  this is almost what you already implemented:

- always show=1 :  show
- always show=0, whitelist=something : show if /something/m else  add_to_whitelist
- always show=0, whitelist=something, dkim_policy=show : show if (/something/m or dkim=valid)  else  add_to_whitelist

and can be done with my simple 2 checkboxes suggestion (and I think easier to understand - because myself got confused first with the current menu, I assumed that the DKIM signed was in addition to the whitelist, not an alternative).

If we check how Thunderbird did it, they do not ask if people want to use the whitelist.
There is the whitelist, always there. You can only select to allow remote content or not. If you do not, the whitelist will be in effect. Basically, there are down to :
 ☐ no matter the source
according to whitelist: [_________________________]

without the cool DKIM feature you implemented.

**Comment by the-djmaze** [comment]
DKIM, DMARC and SPF give some level of trust to the email address.
Now i have a clear picture why i implemented this and why it fails in this manner.

Say you trust `john@domain.com` or `@domain.com`.
Domain.com has SPF and DKIM but is missing DMARC and/or is missing ~fail or ~quarantine or other.
Then you could send as john@domain and the images are shown due to the whitelist.

What we need is a better whitelist where you can set a level of trust.
Say `john@domain.com+dkim+spf` to show images only if dkim and spf pass.
And `://domain.com+dkim` etc.

Then the current select is 2 options:
1. Whitelist
2. Always show

**Comment by yeupou** [comment]
>Then the current select is 2 options:
>    Whitelist
>    Always show

So it will be like in Thunderbird:  one checkbox to always load remote content and a whitelist?

BTW, ://domain.com means @domain.com ?
I thought it covered things like http://domain.comURL.

> So if you use ://domain.com+spf+dkim+dmarc all must pass

By pass, you mean do you mean the real SPF pass result ( "an explicit statement that the client is  authorized to inject mail with the given identity"  as in https://www.rfc-editor.org/rfc/rfc7208#section-2.6) or something of a broader scope also allowing "none" and "neutral" case?

I understand some users might want to enforce SPF/DKIM/DMARC and require a "pass" result in addition to the whitelist . 

Probably not most users (otherwise people should probably not browse the web otherwise!) won't expect such extra restriction but will enjoy an extra protection against "fails" results.
But since the SPF/etc check is already implemented, most users would benefit that the software act on a "fail" (instead of a pass) and consider that a "fails" make the whitelist entry being ignored as default behavior.

**Comment by yeupou** [comment]
I also think that Thunderbird approach to talk about "loading remote content" instead of "showing external images" is good.

External/internal might not be overly clear. Remote, we clearly get that we have getting data no included in the whole mail. 
Loading content vs showing image is also good because it states to the user that he might be loading things that wont be visible or noticeable, not only just images that visible in the page layout.

**Comment by yeupou** [comment]
I just installed the latest version 2.26.0. I guess it still a work in progress :-)  regarding the settings.

So right now there is a menu with three options:
[ always ask | add to whitelist or ask | always show ]

For the record, Thunderbird:
![image](https://user-images.githubusercontent.com/1160681/218079431-00a4e8c7-c373-470f-ae53-4cc9f0851629.png)

**Comment by the-djmaze** [comment]
Thunderbird works different as it also allows cookies.
SnappyMail does none of it and requires a proxy.
SnappyMail does only proxy remote images (not content like: movies, audio, css, javascript, etc.)

**Comment by yeupou** [comment]
(For the record, cookies in thunderbird as not part as "remote content". They have their specific settings with specific exception list)
