### ISSUE TITLE
Snappymail v2.25.5 - display error

### ISSUE THREAD

**Issue by hguilbert** [the-djmaze/snappymail#940]
I don't remember the configs.
Following #912 and reproducible on https://snappymail.eu/demo/, 02/09/2023 around 17h55.

![Capture1](https://user-images.githubusercontent.com/51283484/217885646-605cb6fc-38b1-46bd-b659-1102eda5cfb6.png)

![Capture2](https://user-images.githubusercontent.com/51283484/217885719-ab19c874-4899-4fc0-9cf9-723ce7a51317.png)

**Comment by the-djmaze** [comment]
I noticed after changing to display:flex
And fixed in https://github.com/the-djmaze/snappymail/commit/9d02be6a20d2d8b174361892074e2a545c9830bd
