### ISSUE TITLE
Nextcloud Snappymail user changes password doesn't updates password in nextcloud admin

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#946]
Nextcloud Snappymail user changes password doesn't updates password in nextcloud admin in the part that says: 

In: Nextcloud Settings: additional settings:

Enter an email and password to auto-login to SnappyMail.

This password doesn't updates when user changes password

**Comment by the-djmaze** [comment]
Correct, as it is the mailserver password not for nextcloud.

**Comment by chrisdent** [comment]
We use IMAP verification. 

The following is happening: 

If user changes password then email doesn't appear after nextcloud login. It appears a login screen and won't login, only after changing in Nextcloud settings >> additional settings.

Would be helpful that if user changes password it changes automatically the saved password as well so user experience is smooth.
