### ISSUE TITLE
[Feat. req.] Open mails in a tab or new window

### ISSUE THREAD

**Issue by ivoruetsche** [the-djmaze/snappymail#951]
Hi

Thanks for this great work, it's nice to work with the snappymail.

It would be nice, to have a personal setting, to open mails in a new tab or window in general. At the moment, it's only possible to select the mail, then open in a new tab, drag this tab outside of the browser to have it in a separate window.

Thanks a lot
Ivo

**Comment by the-djmaze** [comment]
How wide should the window be?
As it only works when the "windowFeatures" are different compared to the current window.

**Comment by the-djmaze** [comment]
P.S. You can test with v2.26.1

1. Enable `[debug] javascript`
2. delete `snappymail/v/0.0.0/static/js/app.js.br`
3. delete `snappymail/v/0.0.0/static/js/app.js.gsz`
4. modify `snappymail/v/2.26.1/static/js/app.js` line 4179
```js
				win = open('', 'sm-msg-'+this.requestHash
					,newWindow ? 'innerWidth=' + elementById('V-MailMessageView').clientWidth : ''
				),
```
5. Now test in your web browser
