### ISSUE TITLE
Issue with the footer of a certain email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#952]
The footer of the attached email is being shown improperly but is correct when it is viewed via a web based eml viewer. Screenshots of it in SnappyMail and the online viewer are also included.

![Prolific Email - Incorrect Footer](https://user-images.githubusercontent.com/6194332/218630750-a9d27fd2-4bd8-4cb9-b8c1-15dcb95e0455.png)
![Prolific Email - Correct Footer](https://user-images.githubusercontent.com/6194332/218630776-91bdf5e1-4bf6-4f5b-abaa-e9259e55b7b3.png)
[New study available.eml.txt](https://github.com/the-djmaze/snappymail/files/10728454/New.study.available.eml.txt)

**Comment by the-djmaze** [comment]
Currently it can't be solved.
The UL LI elements are styled using CSS in the STYLE element and they didn't use inline styling.

https://www.caniemail.com/features/html-style/

**Comment by Zero3K** [comment]
Can it ever be solved?

**Comment by the-djmaze** [comment]
In progess, so i merged and added something
https://github.com/the-djmaze/snappymail/commit/64818025e894edb79bc491525cd3d138bd77155a

**Comment by Zero3K** [comment]
The issue hasn't been fixed yet.

**Comment by Zero3K** [comment]
It's almost fixed. The images are now centered but have a space between them (unless that is how it is supposed to be).

**Comment by Zero3K** [comment]
This should be marked as completed. If the way that it is being shown is the correct way.

**Comment by Zero3K** [comment]
Oh, and remove the wontfix tag.
