### ISSUE TITLE
Issue with the top logo and text of a certain e-mail

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#953]
The position of them should be the same as in the screenshot of the email when viewed with mboxview. Screenshots of it under SnappyMail and mboxview are attached along with the email.

![GitHub - SnappyMail](https://user-images.githubusercontent.com/6194332/218634976-d789fb7d-0fd6-4993-a042-f813a1cb495a.png)
![GitHub - mboxview](https://user-images.githubusercontent.com/6194332/218634992-de61a518-eaeb-4970-b723-6e8f77b5e26e.png)
[-GitHub- Please verify your email address.eml.txt](https://github.com/the-djmaze/snappymail/files/10728592/-GitHub-.Please.verify.your.email.address.eml.txt)

**Comment by the-djmaze** [comment]
Currently it can't be solved.
The HTML is full of CSS class="" but there is no correct style="".

https://www.caniemail.com/features/html-style/

**Comment by Zero3K** [comment]
Can it ever be solved?

**Comment by Zero3K** [comment]
It is not fixed even with <style> CSS being enabled.

**Comment by Zero3K** [comment]
Are you planning on fixing it soon?

**Comment by Zero3K** [comment]
Hmm?

**Comment by Zero3K** [comment]
I can confirm that it has been fixed. Please mark this as completed and remove the wontfix tag.
