### ISSUE TITLE
Facebook logo missing from emails sent out by it

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#954]
The emails that Facebook sends out are missing its logo. Screenshots of the email under SnappyMail and mboxview are attached along with the email.

![Facebook Email - SnappyMail](https://user-images.githubusercontent.com/6194332/218636668-89cf4ae8-e5b0-4fc6-9972-d04c18a63794.png)
![Facebook Email - mboxview](https://user-images.githubusercontent.com/6194332/218636678-579a75da-18f8-4780-9918-2f290867f8e7.png)
[New email address added on Facebook.eml.txt](https://github.com/the-djmaze/snappymail/files/10728665/New.email.address.added.on.Facebook.eml.txt)

**Comment by the-djmaze** [comment]
Currently it can't be solved.
The HTML is full of CSS STYLE elements.

https://www.caniemail.com/features/html-style/

**Comment by Zero3K** [comment]
Can it ever be solved?

**Comment by Zero3K** [comment]
It hasn't been fixed yet.

**Comment by Zero3K** [comment]
Are you planning on fixing it soon?

**Comment by Zero3K** [comment]
Hmm?

**Comment by Zero3K** [comment]
I can confirm that it has been fixed. Please mark this as completed and remove the wontfix tag.
