### ISSUE TITLE
Links with @ in them are getting truncated 

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#955]
All links with @ in them are getting truncated. I am attaching screenshots of the email that is showing the issue under SnappyMail but not under mboxview and am also attaching the email.

![Motherless - SnappyMail](https://user-images.githubusercontent.com/6194332/218761658-425791a5-e34f-4de6-8710-e699854da003.png)
![Motherless - mboxview](https://user-images.githubusercontent.com/6194332/218761668-8a2291e9-00a1-4aa4-ae97-cc17932f29ff.png)
[A friend request from Violetath6.eml.txt](https://github.com/the-djmaze/snappymail/files/10733148/A.friend.request.from.Violetath6.eml.txt)

**Comment by the-djmaze** [comment]
`@` is not a valid URI character. Should be `%40`

**Comment by Zero3K** [comment]
What about adding code that detects if it is part of a text string that starts with http or https?

**Comment by the-djmaze** [comment]
No, because `https://username:password@domain.com` is the only valid way.

**Comment by Zero3K** [comment]
Okay.

**Comment by the-djmaze** [comment]
I've misread the RFC!
In the beginning the @ is marked as reserved, but while reading at the end the BNF notation says otherwise.
```
hsegment       = *[ uchar | ";" | ":" | "@" | "&" | "=" ]
search         = *[ uchar | ";" | ":" | "@" | "&" | "=" ]
```

So i will fix the parser.

**Comment by the-djmaze** [comment]
While at it, i also allow unicode in them like: `https://➡.ws/䨹` and `http://उदाहरण.परीक्षा`
