### ISSUE TITLE
Two issues with a certain email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#956]
1. The graphic(s) used to represent the browser icon are being stretched.
2. The buttons are not showing up fully.

Two screenshots that show it under SnappyMail and mbox view are attached along with the email.

![Chaturbate Email - SnappyMail](https://user-images.githubusercontent.com/6194332/218763394-a628182d-94c1-4b44-a51d-0de1712363f4.png)
![Chaturbate Email - mboxview](https://user-images.githubusercontent.com/6194332/218763445-5359227a-b331-4ec1-92c1-6a209be036a1.png)
[-Chaturbate Alert- New Login for zero3k.eml.txt](https://github.com/the-djmaze/snappymail/files/10733206/-Chaturbate.Alert-.New.Login.for.zero3k.eml.txt)

**Comment by the-djmaze** [comment]
Test v2.26.1

**Comment by Zero3K** [comment]
Not fixed.

**Comment by Zero3K** [comment]
The OS and Browser graphics are fixed. The bottom two buttons are still not displaying properly.

**Comment by Zero3K** [comment]
I'll let them know about it.
