### ISSUE TITLE
Issue with the spacing of images at the top of certain emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#957]
At the top of certain emails, the spacing of images is messed up. Screenshots of the issue happening under SnappyMail but not under mbox view are attached along with the email.

![Disqus - SnappyMail](https://user-images.githubusercontent.com/6194332/218765337-b314e4a4-68cd-48d2-b44f-08b64765bd67.png)
![Disqus - mboxview](https://user-images.githubusercontent.com/6194332/218765355-41f1a835-8c27-4185-b123-4a411fb1c5b9.png)
[Verify your email now, prevent stuck comments.txt](https://github.com/the-djmaze/snappymail/files/10733272/Verify.your.email.now.prevent.stuck.comments.txt)

**Comment by the-djmaze** [comment]
Test v2.26.1

**Comment by Zero3K** [comment]
Not fixed.

**Comment by the-djmaze** [comment]
Did you enable `<style>` in settings?

**Comment by Zero3K** [comment]
I just did. It is fixed (except for the color zero3k and the fact that it is underlined when I think it shouldn't be).

**Comment by Zero3K** [comment]
Now it looks correct. Thanks for fixing it.
