### ISSUE TITLE
Can't open PGP keys file.

### ISSUE THREAD

**Issue by luluwebmaster** [the-djmaze/snappymail#958]
Hello, in the continuation of #89,

I have a other problem with PGP Keys.

**Describe the bug**
It seems I can't open PGP key attachment files ( Attached automatically by Thunderbird ).

**To Reproduce**
1. Click on PGP attachment file
2. Look at the browser inspector
3. The app try to open the file as request ?

**Expected behavior**
Download PGP key ( Or import into SnappyMail ? )

**Screenshots**

![image](https://user-images.githubusercontent.com/15527061/218801742-69212792-c2d9-44f1-ad16-e41449d4b146.png)

![image](https://user-images.githubusercontent.com/15527061/218801878-4be714ab-b27c-4c26-b559-77e5c97da6e7.png)

**Please complete the following information:**
- Browser: Brave v1.48.158
- SnappyMail Version: 2.26.1

**Additional context**
My installation use the Docker image of @kouinkouin.

**Comment by the-djmaze** [comment]
What happens when you modify application.ini config `content_security_policy` to `default-src data:`

**Comment by luluwebmaster** [comment]
Hello,

Indeed it works correctly by changing this parameter !

Thank you for your help.
