### ISSUE TITLE
Can't close Sieve dialog

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#960]
**Describe the bug**
The Sieve dialog window can't be closed anymore.

**To Reproduce**
Open the Sieve filter page in Settings, open the modal, click the X in the upper right corner.

**Expected behavior**
Modal closes.

**Please complete the following information:**
- Browser: Firefox 104
- IMAP daemon: -
- PHP version: -
- SnappyMail Version: 2.26.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Browser console error: `Uncaught TypeError: this.modalVisible is not a function`

**Comment by the-djmaze** [comment]
Found the problem. It does not occur when you click the `[Esc]` on your keyboard.
It is caused by Knockout.js scope when using `$root.close` as the scope is then not $root.

I've made a workaround for it.
