### ISSUE TITLE
Issue with sending large text emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#962]
When I send a large text email with a lot of quoted text, it eventually gives a request timed out error when I try to do so. The size of the email was 2.1 MB.

**Comment by the-djmaze** [comment]
What does the logs say?

**Comment by Zero3K** [comment]
Would attaching the email as a zip archive help fix it?

**Comment by Zero3K** [comment]
Here's the log:

[Email Server Log.txt](https://github.com/the-djmaze/snappymail/files/10746193/Email.Server.Log.txt)
