### ISSUE TITLE
Hooks for "imap.before-login" and "smtp.before-login" not found in code

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#966]
Hi,
looking at the plugin here the hooks `imap.before-login` and `smtp.before-login` are used:
https://github.com/the-djmaze/snappymail/blob/8058c8d2f6188792e9be7fd05be8c62c21381079/plugins/login-override/index.php#L16
https://github.com/the-djmaze/snappymail/blob/8058c8d2f6188792e9be7fd05be8c62c21381079/plugins/login-override/index.php#L17

In the code of SnappyMail I can't find any active `RunHook('imap.before-login')` expression (only one comment in imapsync.php). So I'm asking myself if I'm only looking at the wrong point or if these hooks does not exist anymore?

**Comment by the-djmaze** [comment]
They are here:

https://github.com/the-djmaze/snappymail/blob/353fdda3e5f5fea8545e1315206c31a822e885ed/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php#L296-L298

**Comment by cm-schl** [comment]
🤦‍♂️ have looked for the whole string instead... thanks!
