### ISSUE TITLE
Non-latin symbols in Name break Avatar plugin

### ISSUE THREAD

**Issue by ss-smk** [the-djmaze/snappymail#967]
**Describe the bug**
If the first letters of the sender's name contain non-latin letters, avatar plugin can't generate avatar, and generate Javascript exception in browser console:
/Plugins/0/User/5774665b9792778f7dd5de66f60bfd00/:1 Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**To Reproduce**
1. Go to settings, and set Identity, for example "ększości tests"
2. Send mail to yourself (plugin Avatars must be activate, no matter before or after)

**Expected behavior**
Non-latin letters are not filtering or not escaped, and throw exception.

**Screenshots**
![mail](https://user-images.githubusercontent.com/100996249/219034271-4b7cf698-c8a4-407c-aa43-b7c209d42544.jpg)

**Please complete the following information:**
- Browser: FireFox 109.0
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.26.0, 2.26.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Browser exception:
?/Plugins/0/User/...../:1 Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Additional context**
Changing the plugin settings does not affect the problem in any way.

**Comment by the-djmaze** [comment]
This is what i get now:

![afbeelding](https://user-images.githubusercontent.com/3752035/219382887-86bb02d2-55b4-4b9d-ace2-ab4799cd1a7b.png)

**Comment by ss-smk** [comment]
As i see, all works good. 
Thank you for fast fix and response!
