### ISSUE TITLE
Select next email after archiving previous

### ISSUE THREAD

**Issue by meichthys** [the-djmaze/snappymail#968]
Great work on this - This is a great alternative to the 'not so usable' default Nextcloud mail app.

It would be nice if there was an option to auto-select the next email in the list after archiving the previous one.
(I think this could also be set as the default since many most(?) email clients do this by default)

**Describe alternatives you've considered**
Currently the alternative is to select the next email manually. This isn't very fun when trying to work through a large inbox.

**Comment by the-djmaze** [comment]
Define next...
And what i mean is...

## Case 1
Say you have messages sorted descending by date:
* Message 40 on 2023-02-15 15:00
* Message 39 on 2023-02-15 12:00
* Message 38 on 2023-02-11 17:00

You are reading Message 39 and archive that.
Should it open Message 40 or Message 38?

## Case 2
Say you have messages sorted ascending by date:
* Message 38 on 2023-02-11 17:00
* Message 39 on 2023-02-15 12:00
* Message 40 on 2023-02-15 15:00

You are reading Message 39 and archive that.
Should it open Message 40 or Message 38?

**Comment by the-djmaze** [comment]
P.S. There are reasons why SnappyMail doesn't load "next" message:
1. Maybe you don't want to
2. On mobile this could drain your MB/GB limit (roaming charges, etc.)
3. and a few small others

> since many most(?) email clients do this by default

Can you name a few Web based clients?
So not the app on your phone, tablet, desktop, etc.

**Comment by meichthys** [comment]
I could see there may be differing opinions on this but imo:

-    If you have the messages in descending order (newest on top), then we would want to open the next oldest message, 
-    If we are sorted in Ascending order (oldest on top), then we would want to open the next newest message.

I don't know of other web based clients - I was comparing to Thunderbird and iOS mail which both seem to handle it this way.

> * Maybe you don't want to
> * On mobile this could drain your MB/GB limit (roaming charges, etc.)
> * and a few small others

I think these could be mitigated by making this an option (not on by default).

**Comment by joergmschulz** [comment]
same should happen for deletion, not only archiving. And, yes, it should be an option (just like collapsing mail threads). Nextcloud mail does so (but let's not mention that as good example), apple mail proceeds to the nexe message as well. 
And, yes, there are many reasons pro and con: So this feature should only get implemented when it's solid and when it's configurable and when many users request it. My users didn't complain yet, but they are patient. And they are happy they aren't forced to use nextcloud mail.
