### ISSUE TITLE
BoundaryPrefix isn't configurable

### ISSUE THREAD

**Issue by electroflame** [the-djmaze/snappymail#97]
**Is your feature request related to a problem? Please describe.**
For HTML emails, the MIME Boundary is added to a few places in the email source.  Currently, the BoundaryPrefix is set to \_SnappyMail_ (as seen in Api.php).

```php
\MailSo\Config::$BoundaryPrefix = '_SnappyMail_';
```
I'm sure this was great for RainLoop branding and whatnot, but it seems a little tacky, especially for self-hosted webmail where you might not want to broadcast what you're using.

**Describe the solution you'd like**
I propose either A.) making this user-configurable (quite a bit of Api.php already is!), or B.) just removing the prefix entirely.  I don't believe it's strictly needed for a well-formed email template (the boundary is, but not the prefix, to my knowledge), but I could see the value of potentially wanting to white-label it if SnappyMail is being used by a mail service reseller or something.

Additionally, thank you for making SnappyMail!  It takes a lot of the pain out of RainLoop. :smile:

**Comment by the-djmaze** [comment]
Thanks for reporting!
I've made a small change to make it configurable

**Comment by electroflame** [comment]
Awesome, thanks!
