### ISSUE TITLE
The attached email causes a request failed message to be displayed

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#972]
*subject*

[messages-20230216141957.zip](https://github.com/the-djmaze/snappymail/files/10756887/messages-20230216141957.zip)

**Comment by Zero3K** [comment]
What was the issue?

**Comment by the-djmaze** [comment]
SVG elements were not stripped.
The change removes the whole SVG element tree

**Comment by Zero3K** [comment]
What is wrong with SVG elements?

**Comment by the-djmaze** [comment]
When someone writes emails, they should always check what is possible.
Patreon did not check https://www.caniemail.com/features/image-svg/ and just tries.

SnappyMail removes SVG for reasons.
SnappyMail is an email application, not a website.

**Comment by Zero3K** [comment]
The majority of the webmail providers listed on it support SVG.

**Comment by the-djmaze** [comment]
But not Gmail and Gmail is big...

**Comment by Zero3K** [comment]
I think you should be better than Gmail since even other small webmail providers support it. And it will give people another reason to use a SnappyMail based provider over Gmail.

**Comment by the-djmaze** [comment]
HTML5, SVG, MathML, etc. etc. have many different elements and element attributes.
If we are going to support it, a whole new cleanHTML parser has to be created that keeps track of all of them.

The current purpose of cleanHTML is to support where possible, but remove security related things like javascript, tracking pixels, etc. etc.

SVG would open new security issues and needs special handling with a tree walker and more.

Why overload parsing when it is already slow in your 2MB email?
Why overload mobile browser CPU?

What if you paste an SVG in the editor but recipient can't see it?

There are just so many expectations by people who don't understand why things don't work, that it is better to not support it at all.

Same with dark mode and people sending emails with text color black but not defining background color white.
What should we do?
* Disable dark mode?
* Strip all colors?
* Remove style elements?

Why should we fix screwups of others?

**Comment by Zero3K** [comment]
So, I should suggest that fix to them?

**Comment by the-djmaze** [comment]
Sure, go ahead. Maybe they will change it.

**Comment by Zero3K** [comment]
I have messaged their Twitter account regarding it. I will let you know their response when it I get it.

**Comment by Zero3K** [comment]
> Patreon could just have put the SVG as inline attachment and then an img element with a cid to that attachment and it will work.

Can it be done even though it is not using a .svg file hosted on one of their server(s)?

**Comment by the-djmaze** [comment]
Yes that would work the same.
