### ISSUE TITLE
Can not Add or Modify Domain Settings

### ISSUE THREAD

**Issue by sgutermann** [the-djmaze/snappymail#975]
**Describe the bug**
In Nextcloud in the SnappyMail Panel one can add Domains and configure the server where to get the Mail.

This worked fine in v25 this is where I added mine.

Upgraded to v26 and I can not "save" or "modify" anything. Same with 26.1.

**To Reproduce**
Go to the SnappyMail Admin Panel in NextCloud, Click on Domains and try to add one.

**Comment by the-djmaze** [comment]
Nextcloud v26 is still not released.

Enable SnappyMail debug and check why your setup is failing.
https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

As it works on my v25 setup.

**Comment by sgutermann** [comment]
Sorry, not enough coffee yet.

Nextcloud Version is 25.0.3
SnappyMail is what I ment. v2.26.0 and v2.26.1 do not let me work with Domains in the Admin Panel anymore.

**Comment by sgutermann** [comment]
Ok, will turn on some more logging. But as a side note ... my application.ini does for some reason state at the bottom:

[version]
current = "2.25.1"

... that was what I installed originally about a month ago or so.

**Comment by sgutermann** [comment]
I enabled Logging ... but am getting no data on this action. I guess that is because only the cancel button is aktive. I can not save anything, so no error in the log.

![grafik](https://user-images.githubusercontent.com/10127278/219598187-e244db81-504e-4a73-982d-7cbcb27a78bc.png)

**Comment by the-djmaze** [comment]
You must also fill in the SMTP tab

**Comment by sgutermann** [comment]
OMG - sorry for wasting your time.

**Comment by sgutermann** [comment]
Thank you and sorry gain.
