### ISSUE TITLE
Can not login when the extensions "blacklist" and "whitelist" are enabled (Version 2.26.1) Nextcloud

### ISSUE THREAD

**Issue by novallis66** [the-djmaze/snappymail#976]
**Describe the bug**
Authentication failed when try to login to SnappyMail in a nextcloud 25.0.3 environment.

I found, this is because the extensions "blacklist" and "whitelist" (both version 2.1) are enabled.

After disabling the two extensions, everything works as expected.

**To Reproduce**
1. Install and activate "blacklist" extension
2. Install and activate "whitelist" extension
3. Login

**Expected behavior**
Login works

**[Update]**

Here are two screenshots:
![image](https://user-images.githubusercontent.com/119486123/219684072-c3f42342-7827-48e9-8427-3a7ea42f933d.png)
![image](https://user-images.githubusercontent.com/119486123/219684137-4a3388c0-fe7a-4cb4-9f86-e7ecbd5471a9.png)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Since this is a hosted service, I have no access to logfiles or any debugg-code.

**Additional context**
It is simple.
If the two extensions "blacklist" and "whitelist " with the sample entries, are activated, i can not login and get the error (translated: "authentication failed"). If the two extensions are disabled, i can login and erverything is fine, so the problems seems coming from the extensions.

**Comment by the-djmaze** [comment]
Please fill in the questionsmarks

**Comment by the-djmaze** [comment]
Did you whitelist your email address that you use for login?
