### ISSUE TITLE
Tab key selects toolbar buttons

### ISSUE THREAD

**Issue by electroflame** [the-djmaze/snappymail#98]
**Is your feature request related to a problem? Please describe.**
Currently, if you use Tab to move from text field to text field, you end up having to tab over the various toolbar buttons.

**Describe the solution you'd like**
Ideally, after the last text field, it should jump directly to the text area containing the email's contents.

Looking at it, I see two relatively pain-free ways to handle this:
1.) Assign the tabindex attribute to the non-textfield toolbar buttons, and set it to -1 (i.e. never selectable via tab).
2.) Assign positive tabindex values to the text fields and text areas.

Given that there is some dynamic element to what text fields are displayed (i.e. some can be added by clicking the CC, BCC, etc. buttons) I think that the first option is probably the cleanest.

**Describe alternatives you've considered**
Alternatively, this might be a configuration option, as I could potentially see someone wanting to change font-size or something via the keyboard, but overall I think this is likely a bug.

**Additional context**
Looking at it further (and after comparing RainLoop and SnappyMail), this might just be a regression from switching CKEditor to Squire, as RainLoop handles skipping over the toolbar buttons correctly.

**Comment by electroflame** [comment]
After further investigation, this doesn't occur if the CKEditor plugin is used (the toolbar is skipped over), so this looks more like a regression related to switching to Squire.

However, when using the CKEditor plugin, the Content/Attachment buttons still get selected via tab before jumping down into the email text area, so it's not a perfect alternative.

**Comment by the-djmaze** [comment]
Resolved the issue with `tabindex="-1"`
