### ISSUE TITLE
Opening accounts in new tab

### ISSUE THREAD

**Issue by Syphere** [the-djmaze/snappymail#980]
I've just migrated over from the RainLoop app in Nextcloud and it's been lovely so far. But there's one thing that I miss that was available in RainLoop, albeit unofficially I'm sure.
It was possible to open accounts in new tabs/windows, allowing you to more easily view mail in whichever account you have open.

Attempting to do this on SnappyMail causes all opened tabs to switch to that account, rather than just opening the selected account in a new tab. Can this be made a feature?

**Comment by the-djmaze** [comment]
Sorry, no.
Read https://github.com/the-djmaze/snappymail/issues/837 and https://github.com/the-djmaze/snappymail/issues/650#issuecomment-1309856493
