### ISSUE TITLE
Plain text email including an URL with the @ symbol invalid

### ISSUE THREAD

**Issue by codiflow** [the-djmaze/snappymail#983]
**Describe the bug**
In plain text emails the procedure which generates clickable links from text is not respecting the @ symbol and breaks the link there.

**To Reproduce**
Send yourself / Receive a plain text email containing an URL with the @ symbol. The link ends **before** the @ so clicking on it leads to a wrong destination.

**Expected behavior**
The whole URL including the @ symbol is clickable and the link is not being "cut" before it.

**Screenshots**
![image](https://user-images.githubusercontent.com/43847817/220425107-2b6f18e4-c72b-432a-8c94-bbb9f5a73784.png)

No worries – the address and tokens in the screenshot have been replaced by random ones.

**Please complete the following information:**
- Browser: Firefox 109
- IMAP daemon: -
- PHP version: 8.0
- SnappyMail Version: 2.26.2

**Comment by the-djmaze** [comment]
Correct, as the @ is invalid in links.
See #955 where i mention why

**Comment by Zero3K** [comment]
@codiflow He fixed it. Please wait for a new release.
