### ISSUE TITLE
Sever error 500

### ISSUE THREAD

**Issue by HenkVirtual** [the-djmaze/snappymail#987]
Ater upgrade to v2.26.3 you get server error 500
**To Reproduce**

**Screenshots**

![Screenshot from 2023-02-22 09-06-53](https://user-images.githubusercontent.com/71253263/220560837-4250773c-a91a-4342-979b-05ea900f678e.png)
**Please complete the following information:**
- Browser: chromium  firefox 
- IMAP daemon: dovecot
- PHP version:8
- SnappyMail Version:2.26.3

**From the webserver log, nextcloud logging does not display this error.**
22/Feb/2023:09:44:30 +0100] "GET /apps/snappymail/?/AppData/0/15950192541735686/ HTTP/1.0" 500 63 "

is there an easy way to return back to the previous version?

**Comment by the-djmaze** [comment]
Can you check the logs why it fails?

**Comment by HenkVirtual** [comment]
The only log I have is the one mentioned in th issue;
`22/Feb/2023:09:44:30 +0100] "GET /apps/snappymail/?/AppData/0/15950192541735686/ HTTP/1.0" 500 63 "`

I enabled the logging for snappymail in `appdata_snappymail/_data_/_default_/configs/application.ini`
Refreshed the page several times but no logging is created.
Also deleted all cookies in both browsers.
<details>
<summary>**This is what I have got from the webserver log**</summary>

**This is what I have got from the webserver log**
`- - 
- - [22/Feb/2023:10:40:46 +0100] "GET /apps/side_menu/css/stylesheet?v=5 HTTP/1.0" 200 242 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 
like Gecko) Chrome/109.0.0.0 Safari/537.36" "2a10:3781:2015:1:194a:f3d4:d88f:3685"
- - [22/Feb/2023:10:40:46 +0100] "GET /apps/snappymail/?/AppData/0/41735129063525833/ HTTP/1.0" 500 63 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 
- - [22/Feb/2023:10:40:46 +0100] "GET /ocs/v2.php/search/providers?from=%2Fapps%2Fsnappymail%2F HTTP/1.0" 200 393 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
</details>

**Comment by Gymnae** [comment]
Facing the same issue, Developer console showed this error:
`GET https://cloud.domain.told/apps/snappymail/?/AppData/0/3355224287274796/ 500`
The page shows: `Call to undefined method NextcloudPlugin::setContactsSyncData()`

My Snappymail is correctly installed in custom_apps (and every update also causes nextcloud to drop to maintenance mode)

**Comment by the-djmaze** [comment]
@Gymnae thanks!
I did test my changes in the extension but forgot to delete my contacts sync data.
So the change i made to automatic configure carddav failed.

I've released a new version of the plugin.
1. delete `appdata_snappymail/_data_/_default_/cache`
2. Nextcloud -> Admin settings -> Additional -> SnappyMail Admin -> Extensions -> Upgrade `Nextcloud` plugin to 2.19

On failure you could delete `appdata_snappymail/_data_/_default_/plugins/nextcloud`

**Comment by daffydock** [comment]
Just as FYI for anyone else who has this issue and finds this. Tried the above and got it working just fine. 
Thanks @the-djmaze
