### ISSUE TITLE
Internal Server Error after update to 2.26.4

### ISSUE THREAD

**Issue by HenkVirtual** [the-djmaze/snappymail#991]
**Describe the bug**
Internal Server Error

![Screenshot from 2023-02-24 22-21-45](https://user-images.githubusercontent.com/71253263/221295575-36fc89c5-a786-48f1-b2b4-899060b475a2.png)
 <details>

<summary>From the snappymail logfile</summary>

[2023-02-24 21:13:04.011][cd8549f6] PHP[WARNING]: Undefined property: SnappyMail\HTTP\CSP::$script /usr/share/nginx/html/nextcloud/apps/snappymail/lib/ContentSecurityPolicy.php [line:19, code:2]
</details>
Nextcloud 25.0.4
nginx
php8

**Comment by makoehr** [comment]
I have the very same issue since now. Update to SnappyMail 2.26.4 and nextcloud 25.0.4

**Comment by nkinkade** [comment]
I don't know if this patch will have unintended consequences, but this resolves the issue for me:

```
$ diff -u ContentSecurityPolicy.php.orig ContentSecurityPolicy.php
--- ContentSecurityPolicy.php.orig      2023-02-24 22:30:09.114495982 +0000
+++ ContentSecurityPolicy.php   2023-02-24 22:49:53.624669970 +0000
@@ -16,7 +16,7 @@
        function __construct() {
                $CSP = \RainLoop\Api::getCSP();
 
-               $this->allowedScriptDomains = \array_unique(\array_merge($this->allowedScriptDomains, $CSP->script));
+               $this->allowedScriptDomains = \array_unique($this->allowedScriptDomains);
                $this->allowedScriptDomains = \array_diff($this->allowedScriptDomains, ["'unsafe-inline'", "'unsafe-eval'"]);
 
                // Nextcloud only sets 'strict-dynamic' when browserSupportsCspV3() ?
@@ -24,12 +24,12 @@
                        ? $this->useStrictDynamic(true) // NC24+
                        : $this->addAllowedScriptDomain("'strict-dynamic'");
 
-               $this->allowedImageDomains = \array_unique(\array_merge($this->allowedImageDomains, $CSP->img));
+               $this->allowedImageDomains = \array_unique($this->allowedImageDomains);
 
-               $this->allowedStyleDomains = \array_unique(\array_merge($this->allowedStyleDomains, $CSP->style));
+               $this->allowedStyleDomains = \array_unique($this->allowedStyleDomains);
                $this->allowedStyleDomains = \array_diff($this->allowedStyleDomains, ["'unsafe-inline'"]);
 
-               $this->allowedFrameDomains = \array_unique(\array_merge($this->allowedFrameDomains, $CSP->frame));
+               $this->allowedFrameDomains = \array_unique($this->allowedFrameDomains);
 
                $this->reportTo = \array_unique(\array_merge($this->reportTo, $CSP->report_to));
        }
```

In this latest release the CSP directives were both renamed, and made private:

https://github.com/the-djmaze/snappymail/compare/v2.26.3...v2.26.4#diff-a689911ec2cd77b40953d045217a4447d3617e82d8aa6b9dc2382af239515779R15

**Comment by pvalarezo** [comment]
> I don't know if this patch will have unintended consequences, but this resolves the issue for me:
> 
> ```
> $ diff -u ContentSecurityPolicy.php.orig ContentSecurityPolicy.php
> --- ContentSecurityPolicy.php.orig      2023-02-24 22:30:09.114495982 +0000
> +++ ContentSecurityPolicy.php   2023-02-24 22:49:53.624669970 +0000
> @@ -16,7 +16,7 @@
>         function __construct() {
>                 $CSP = \RainLoop\Api::getCSP();
>  
> -               $this->allowedScriptDomains = \array_unique(\array_merge($this->allowedScriptDomains, $CSP->script));
> +               $this->allowedScriptDomains = \array_unique($this->allowedScriptDomains);
>                 $this->allowedScriptDomains = \array_diff($this->allowedScriptDomains, ["'unsafe-inline'", "'unsafe-eval'"]);
>  
>                 // Nextcloud only sets 'strict-dynamic' when browserSupportsCspV3() ?
> @@ -24,12 +24,12 @@
>                         ? $this->useStrictDynamic(true) // NC24+
>                         : $this->addAllowedScriptDomain("'strict-dynamic'");
>  
> -               $this->allowedImageDomains = \array_unique(\array_merge($this->allowedImageDomains, $CSP->img));
> +               $this->allowedImageDomains = \array_unique($this->allowedImageDomains);
>  
> -               $this->allowedStyleDomains = \array_unique(\array_merge($this->allowedStyleDomains, $CSP->style));
> +               $this->allowedStyleDomains = \array_unique($this->allowedStyleDomains);
>                 $this->allowedStyleDomains = \array_diff($this->allowedStyleDomains, ["'unsafe-inline'"]);
>  
> -               $this->allowedFrameDomains = \array_unique(\array_merge($this->allowedFrameDomains, $CSP->frame));
> +               $this->allowedFrameDomains = \array_unique($this->allowedFrameDomains);
>  
>                 $this->reportTo = \array_unique(\array_merge($this->reportTo, $CSP->report_to));
>         }
> ```
> 
> In this latest release the CSP directives were both renamed, and made private: [bb77d0a](https://github.com/the-djmaze/snappymail/commit/bb77d0ae024bb98d03ee3169085a238b99dad680)

Bien... Gracias, resuelve el problema..

**Comment by the-djmaze** [comment]
Sorry. I changed CSP to allow secure iframe use as that was a problem.
Forgot to check Nextcloud CSP issues.

I've repackaged 2.26.4 for Nextcloud as 2.26.1.1 is not allowed there

**Comment by HenkVirtual** [comment]
> > I don't know if this patch will have unintended consequences, but this resolves the issue for me:
> > ```
> > $ diff -u ContentSecurityPolicy.php.orig ContentSecurityPolicy.php
> > --- ContentSecurityPolicy.php.orig      2023-02-24 22:30:09.114495982 +0000
> > +++ ContentSecurityPolicy.php   2023-02-24 22:49:53.624669970 +0000
> > @@ -16,7 +16,7 @@
> >         function __construct() {
> >                 $CSP = \RainLoop\Api::getCSP();
> >  
> > -               $this->allowedScriptDomains = \array_unique(\array_merge($this->allowedScriptDomains, $CSP->script));
> > +               $this->allowedScriptDomains = \array_unique($this->allowedScriptDomains);
> >                 $this->allowedScriptDomains = \array_diff($this->allowedScriptDomains, ["'unsafe-inline'", "'unsafe-eval'"]);
> >  
> >                 // Nextcloud only sets 'strict-dynamic' when browserSupportsCspV3() ?
> > @@ -24,12 +24,12 @@
> >                         ? $this->useStrictDynamic(true) // NC24+
> >                         : $this->addAllowedScriptDomain("'strict-dynamic'");
> >  
> > -               $this->allowedImageDomains = \array_unique(\array_merge($this->allowedImageDomains, $CSP->img));
> > +               $this->allowedImageDomains = \array_unique($this->allowedImageDomains);
> >  
> > -               $this->allowedStyleDomains = \array_unique(\array_merge($this->allowedStyleDomains, $CSP->style));
> > +               $this->allowedStyleDomains = \array_unique($this->allowedStyleDomains);
> >                 $this->allowedStyleDomains = \array_diff($this->allowedStyleDomains, ["'unsafe-inline'"]);
> >  
> > -               $this->allowedFrameDomains = \array_unique(\array_merge($this->allowedFrameDomains, $CSP->frame));
> > +               $this->allowedFrameDomains = \array_unique($this->allowedFrameDomains);
> >  
> >                 $this->reportTo = \array_unique(\array_merge($this->reportTo, $CSP->report_to));
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this latest release the CSP directives were both renamed, and made private: [bb77d0a](https://github.com/the-djmaze/snappymail/commit/bb77d0ae024bb98d03ee3169085a238b99dad680)
> 
> Bien... Gracias, resuelve el problema..

so what exact do I have to do ?

**Comment by the-djmaze** [comment]
Uninstall and the Install again

**Comment by HenkVirtual** [comment]
> Uninstall and then Install again

Thanks, that solved the problem.
