### ISSUE TITLE
Upgrade to 2.26.4 in yesterday broke ContentSecurityPolicy.php in my nextcloud 25.0.4.1

### ISSUE THREAD

**Issue by zmijunkie** [the-djmaze/snappymail#993]
**Describe the bug**
upgrade to snappymail 2.26.4 and nextcloud 25.0.4.1

**To Reproduce**
Try to use your configured mailbox

**Expected behavior**
I can read my mails

**Please complete the following information:**
- Browser: any
- IMAP daemon: courier
- PHP version: 8.1.14
- SnappyMail Version:2.26.4 

**Workaround

Disable all lines which access unknown properties like $CSP->script

```
$this->allowedScriptDomains = \array_unique(\array_merge($this->allowedScriptDomains, $CSP->script));
$this->allowedScriptDomains = \array_diff($this->allowedScriptDomains, ["'unsafe-inline'", "'unsafe-eval'"]);
$this->allowedImageDomains = \array_unique(\array_merge($this->allowedImageDomains, $CSP->img)); 
$this->allowedStyleDomains = \array_unique(\array_merge($this->allowedStyleDomains, $CSP->style));
$this->allowedStyleDomains = \array_diff($this->allowedStyleDomains, ["'unsafe-inline'"]);
$this->allowedFrameDomains = \array_unique(\array_merge($this->allowedFrameDomains, $CSP->frame));
```

**Comment by the-djmaze** [comment]
Already fixed in #991

**Comment by CSchaefer70** [comment]
So I have the same error... internal error  The logs show:
Undefined property: SnappyMail\HTTP\CSP::$script at /var/www/html/nc/apps/snappymail/lib/ContentSecurityPolicy.php#19

So you recommend uninstall Snappy and then reinstall to resolve?

******
PHP:
Version: 8.1.13
Memory limit: 512 MB
Max execution time: 3600
Upload max size: 356 MB 
*****
DB:


Type: mysql
Version: 10.6.12
Size: 38.5 MB
**************
SnappMail:
v 2.26.4

**Comment by CSchaefer70** [comment]
So I tried and simply uninstalled, removed and then installed the same version... so I can confirm remove and install works.
