### ISSUE TITLE
SSO not working on production

### ISSUE THREAD

**Issue by robmies1968** [the-djmaze/snappymail#995]
**Describe the bug**
Login with SSO does not work on production/cloud, but works on develop/local machine

**To Reproduce**
1. Go to 'snappymail/index.php'
2. Click on
3. Scroll down to
4. See  login screen with dropdown box instead of automatic login

**Expected behavior**
Automatic login with credentials 'behind the scenes'/

**Screenshots**

**Please complete the following information:**
- Browser: firefox 110.0
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0
- SnappyMail Version: 2.23.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Possibly related to same problem: logs are enabled but are not showing

**Additional context**

Login via:

![afbeelding](https://user-images.githubusercontent.com/4415882/221419149-4ee8277e-6368-4ead-8a02-47f7f7413296.png)

After this in an iFrame directing to: https://localhost/xxxx/snappymail/index.php/?sso&hash=" . $ssoHash;    

I happen to notice that in the method `getMainAccountFromToken` in the class UserAuth.php, on the local/develop machine the cookies smctoken, smsession and smaccount are set, but on the cloud/production machine they are missing (so, not even empty, but completely missing).

I hope you can help me with this one, as I have been struggling with this for over two days.

Kind regards,
Rob Mies

**Comment by robmies1968** [comment]
I have updated to the latest version (2.64.3) and it had some more application.ini settings (esp. for CSP). It looks like this works. Thanks!
BTW: became a sponsor. Keep up the good work!

**Comment by the-djmaze** [comment]
> BTW: became a sponsor. Keep up the good work!

Thank you too!
