### ISSUE TITLE
DB error at login

### ISSUE THREAD

**Issue by hydrian** [the-djmaze/snappymail#996]
**Describe the bug**
When logging in, after entering good credentials, browser returns to login page with no errors. 

**To Reproduce**
1. Browse to SnappyMail app in Nextcloud
2. Enter credentials
3. Click on 'Sign-in'
4. Login page redirects back to login

**Expected behavior**
Login to mail

**Screenshots**

**Please complete the following information:**
- Browser: Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)](https://brave.com/latest/)
- IMAP daemon: dovecot 2.2.33.2
- PHP version: 8.1.16 (Ubuntu 18.04)
- SnappyMail Version: 2.26.4 (NextCloud 25)

**[Debug/logging information](https://github.com/the-[2023-02-28 18:37:27.656][84569ff4] SQL[ERROR]: PDOException: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 3306? in /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Common/PdoAbstract.php:87
Stack trace:
#0 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Common/PdoAbstract.php(87): PDO->__construct()
#1 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Common/PdoAbstract.php(262): RainLoop\Common\PdoAbstract->getPDO()
#2 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Common/PdoAbstract.php(346): RainLoop\Common\PdoAbstract->initSystemTables()
#3 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(1249): RainLoop\Common\PdoAbstract->dataBaseUpgrade()
#4 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(1329): RainLoop\Providers\AddressBook\PdoAddressBook->SyncDatabase()
#5 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(96): RainLoop\Providers\AddressBook\PdoAddressBook->getUserId()
#6 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Actions.php(479): RainLoop\Providers\AddressBook\PdoAddressBook->SetEmail()
#7 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Actions.php(685): RainLoop\Actions->AddressBookProvider()
#8 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Actions/User.php(68): RainLoop\Actions->AppData()
#9 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#10 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#11 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.26.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#12 /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(97): RainLoop\Service::Handle()
#13 /var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#14 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#15 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#16 /var/www/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#17 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#18 /var/www/nextcloud/lib/base.php(1047): OC\Route\Router->match()
#19 /var/www/nextcloud/index.php(36): OC::handleRequest()
#20 {main}
[2023-02-28 18:37:27.656][84569ff4] AddressBook[ERROR]: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 3306?

**Additional context**
Database server is running on a remote server, not localhost. All other aspects of NextCloud are running properly, so DB is up and responding.

**Comment by cm-schl** [comment]
Port 3306 is the mysql port. SnappyMail normally does not need any database connection.
Do you maybe have activated some SnappyMail extensions that need a configuration not yet done?

**Comment by m-i-k-e-y** [comment]
Looks like this is contact sync. Maybe activated but not configured?

**Comment by hydrian** [comment]
Closing ticket as it was nut-behind-the-keyboard.

**Comment by the-djmaze** [comment]
![afbeelding](https://user-images.githubusercontent.com/3752035/224967992-cae6c628-1151-400c-9404-5b4b5a50861a.png)

**Comment by the-djmaze** [comment]
![afbeelding](https://user-images.githubusercontent.com/3752035/224969656-d156b330-2b98-4de9-aefa-792e88010110.png)
